### ISSUE TITLE
Links in generated PDF

### ISSUE THREAD

**Issue by waawal** [Kozea/WeasyPrint#1]
Hi!

I really find the cleanliness of the generated .pdf's astounding! Well done!

Is there a way to generate pdf's with `links` either reffering to other places in the document or externally (http://...)?
If not, is that something that's on the roadmap?

**Comment by sublee** [comment]
I'm using WeasyPrint 47. My result doesn't include clickable links. Is the hyperlink feature still available?

```
$ pip install weasyprint==47
$ weasyprint https://www.w3.org/TR/CSS21/selector.html selector.pdf
```

Demo: [selector.pdf](https://github.com/Kozea/WeasyPrint/files/3268841/selector.pdf)

**Comment by liZe** [comment]
Yes, it is, but you need at least Cairo 1.15.4. If you can't install a recent version of Cairo, you can use WeasyPrint 0.42.3 and get links (but miss the features added since).

**Comment by sublee** [comment]
@liZe Thanks for the very fast response.

I installed pycairo-1.18.1 but WeasyPrint still didn't generate clickable hyperlinks. Anyways, the workaround by WeasyPrint 0.42.3 you mentioned works well. I chose the version because I need only simple features.

Thank you so much :)

**Comment by liZe** [comment]
> I installed pycairo-1.18.1 but WeasyPrint still didn't generate clickable hyperlinks.

You need a recent version of Cairo, not PyCairo (WeasyPrint doesn't use PyCairo). But if 0.42.3 works for you, no problem :wink:.

**Comment by sublee** [comment]
@liZe Oh, that information of Cairo was confusing for me but now it's clear. libcairo2-1.14.6 has been installed in my system. Perhaps to install libcairo2-1.15.4+ is more complicated than WeasyPrint-0.42.3. So I decided to keep using WeasyPrint-0.42.3 as you recommended. Thank you for clarifying!
