### ISSUE TITLE
Pandoc highlight CSS renders weirdly 

### ISSUE THREAD

**Issue by roxspring** [Kozea/WeasyPrint#1000]
Given this markdown:

```js
function helloWorld() {
  return 'Hello, World!';
}
```

Pandoc (2.7.3) produces [this html](https://gist.github.com/roxspring/7f3b1f97b8fbf3eaa680fa6bd5b463cd) which safari renders reasonably as:

<img width="212" alt="Screenshot 2019-11-29 at 19 47 19" src="https://user-images.githubusercontent.com/783694/69888062-d80e9f80-12e1-11ea-98e2-31bb00da187a.png">

But when processed through WeasyPrint (48) some weird wrapping occurs:

![png](https://user-images.githubusercontent.com/783694/69888128-32a7fb80-12e2-11ea-80b0-057556ce6ead.png)

Has anybody else seen this?

Is there something odd in the pandoc-supplied CSS and tripping up WeasyPrint?

**Comment by liZe** [comment]
Small sample:
```html
<style type="text/css">
  code {
    white-space: pre-wrap;
  }
  code > span {
    display: inline-block;
    text-indent: -5em;
  }
</style>
<code><span><span>function</span> <span>helloWorld</span>() <span>{</span></span>
<span>  <span>return</span> <span>&#39;Hello, World!&#39;</span><span>;</span></span>
<span><span>}</span></span></code>
```

**Comment by runxel** [comment]
It's even worse for me... :/

![wtf](https://user-images.githubusercontent.com/2277182/75804451-400cd000-5d80-11ea-9f5f-992d0fc61375.png)

**Comment by liZe** [comment]
Thanks for your report. 

> Is there something odd in the pandoc-supplied CSS and tripping up WeasyPrint?

`text-indent` was applied twice on inline blocks. That’s often invisible for positive values when text is displayed on a transparent background (normal case), but it’s really bad for negative values.
