### ISSUE TITLE
Implement counter-set

### ISSUE THREAD

**Issue by nielsvanvelzen** [Kozea/WeasyPrint#1019]
I have a big document where the counters are not working as intended. Some counters don't reset when they should.

Unfortunately I was not able to reproduce that exact issue but I was able to get another counting issue that might be caused by the same problem. In this case the counter doesn't increment.

When converting this HTML snippet to PDF:
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>Counter bug</title>
	<style>
	html {
		counter-reset: h1 h2;
	}

	article h1 {
		counter-increment: h1;
		counter-reset: h2;
	}

	article h2 {
		counter-increment: h2;
		counter-reset: h3;
	}

	article h3 {
		counter-increment: h3;
	}

	article h1::before {
		content: counter(h1) ': ';
	}

	article h2::before {
		content: counter(h1) '.' counter(h2) ': ';
	}

	article h3::before {
		content: counter(h1) '.' counter(h2) '.' counter(h3) ': ';
	}
	</style>
</head>
<body>
	<article>
		<h1>Demo</h1>
	</article>
	<article>
		<h2>Should be 1.1</h2>
	</article>
	<article>
		<h3>Should be 1.1.1</h3>
	</article>
	<article>
		<h3>Should be 1.1.2</h3>
		<h3>Should be 1.1.3</h3>
	</article>
	<article>
		<h3>Should be 1.1.4</h3>
		<h3>Should be 1.1.5</h3>
	</article>
	<article>
		<h2>Should be 1.2</h2>
	</article>
</body>
</html>
```
The result looks like this:

![image](https://user-images.githubusercontent.com/2305178/71723842-6d93d680-2e2e-11ea-8da2-61c0ee56bd28.png)

Using version weasyprint 51

**Comment by liZe** [comment]
Hello!

It’s not a bug, it’s a feature :wink:. You can open this document in other browsers, they will give you the same rendering as WeasyPrint.

You have to reset a counter in a box that contains all the children that use this counter. Otherwise, the counter will only be available for the siblings (and descendants) of your child, but will be automatically reset when quitting your parent.

In your example, `article h2 { counter-reset: h3 }` creates one counter per article, that’s why it’s reset for each article. You have to define it outside, for example in `html`. Using `html { counter-reset: h1 h2 h3 }` fixes your problem.

**Comment by nielsvanvelzen** [comment]
Whoops, my example did indeed not reset it properly. I'll have to find another way to trigger the issue as I do properly reset everything in the document I was talking about.

**Comment by liZe** [comment]
> Whoops, my example did indeed not reset it properly. I'll have to find another way to trigger the issue as I do properly reset everything in the document I was talking about.

No problem! You can reopen this issue with another example.

**Comment by nielsvanvelzen** [comment]
I tried stripping down the document that had the bug to a minimal version and this time I am able to reproduce the bug properly.
This is the HTML:

```html
<!DOCTYPE html>
<html>
<head>
	<title>Counter bug</title>
	<meta charset="UTF-8" />
	<style type="text/css">
	body {
		counter-reset: h2 0 h3 0 h4 0;
	}
	
	body article h2 {
		counter-increment: h2;
		counter-reset: h3 0;
	}

	body article h2::before {
		content: counter(h2) ". ";
	}

	body article h3 {
		counter-increment: h3;
		counter-reset: h4 0;
	}

	body article h3::before {
		content: counter(h2) "." counter(h3) ". ";
	}

	body article h4 {
		counter-increment: h4;
	}

	body article h4::before {
		content: counter(h2) "." counter(h3) "." counter(h4) ". ";
	}
	</style>
</head>
<body>
	<article>
		<h2>1</h2>
	</article>
	<article>
		<h2>2</h2>
	</article>
	<article>
		<h3>2.1</h3>
		<h4>2.1.1</h4>	
		<h4>2.1.2</h4>
		<h4>2.1.3</h4>
	</article>
	<article>
		<h3>2.2</h3>
		<h4>2.2.1</h4>
	</article>
	<article>
		<h2>3</h2>
	</article>
	<article>
		<h3>3.1</h3>
	</article>
	<article>
		<h3>3.2</h3>
	</article>
	<article>
		<h2>4</h2>
		<h3>4.1</h3>
		<h3>4.2</h3>
		<h3>4.3</h3>
	</article>
</body>
</html>
```
And it looks like this:
![image](https://user-images.githubusercontent.com/2305178/71804808-dd8ba200-3064-11ea-8518-62dbc800b1bb.png)

As you can see, after section 3 we expect 3.1 and 3.2 but instead 3.3 and 3.4 show up.

**Comment by liZe** [comment]
> As you can see, after section 3 we expect 3.1 and 3.2 but instead 3.3 and 3.4 show up.

Browsers give the same result as WeasyPrint, so I suppose WeasyPrint is right there too :smile:.

> ```
> 	body article h2 {
> 		counter-increment: h2;
> 		counter-reset: h3 0;
> 	}
> ```

You should use [`counter-set`](https://developer.mozilla.org/fr/docs/Web/CSS/counter-set) here, instead of `counter-reset`. But this property is not widely implemented in browsers, and is not yet in WeasyPrint.

**Comment by nielsvanvelzen** [comment]
So if I understand it correctly the place where a `reset` is done is the "root" in the HTML tree for the counter and the `set` will update the value in the current tree. Glad it's already fixed. I will try it in the next release.

**Comment by liZe** [comment]
> So if I understand it correctly the place where a `reset` is done is the "root" in the HTML tree for the counter and the `set` will update the value in the current tree.

You understand it correctly. The spec tells that [`counter-reset` instantiates new counters](https://drafts.csswg.org/css-lists-3/#counter-reset) whereas [`counter-set` only manipulates the counter value](https://drafts.csswg.org/css-lists-3/#propdef-counter-set) (and create it only if it doesn’t exist).

> Glad it's already fixed. I will try it in the next release.

Have fun!
