### ISSUE TITLE
Proxy Support?

### ISSUE THREAD

**Issue by user4913** [Kozea/WeasyPrint#1022]
We have a forward proxy to get access to the internet, when I try to load raw html and write to a png it goes through and tries to access all the various URL's which proceed to timeout because proxy settings are not configured. There is mention of the URL fetchers and using a custom one, however the documentation does not provide guidance on how to configure proxy details in one. How can I configure proxy details to get this to work?

**Comment by liZe** [comment]
Hello!

In your custom URL fetcher, you can for example use [`requests`](https://2.python-requests.org//en/latest/api/#requests.request) that provides a simple way to handle proxies.

Let us know if it works!

**Comment by liZe** [comment]
> Let us know if it works!

@user4913 So… Does it work? :wink:

**Comment by user4913** [comment]
Thanks Mate, yes it worked :)
