### ISSUE TITLE
Counter prefix

### ISSUE THREAD

**Issue by mbarkhau** [Kozea/WeasyPrint#1029]
I just saw you implemented `@counter-styles`, great work :heart: While using it, it seemed to me that [`prefix`](https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style/prefix) was not working.

Not urgent at all, since I can just add it in my `content` rule.

**Comment by liZe** [comment]
Hello!

I’ve tried the example provided by MDN, and it works well for me:

```html
<style>
  @counter-style chapters {
    system: numeric;
    symbols: "0" "1" "2" "3" "4" "5" "6" "7" "8" "9";
    prefix: 'Chapter ';
  }

  .index {
    list-style: chapters;
    padding-left: 15ch;
  }
</style>
<ul class="index">
  <li>The Boy Who Lived</li>
  <li>The Vanishing Glass</li>
  <li>The Letters from No One</li>
  <li>The Keeper of the Keys</li>
  <li>Diagon Alley</li>
</ul>
```

Could you provide an example that doesn’t work for you?

**Comment by mbarkhau** [comment]
Oh, interesting, maybe this is an issue specific to me, I'll see if I can get a repro.

**Comment by mbarkhau** [comment]
Nope, I think the issue might be legitimate.

```html
<html>
<head>
<style>
    body {
        counter-reset: link;
    }
    @counter-style linkmark {
        system: numeric;
        prefix: "◯";
        symbols: "a" "b" "c" "d" "e" "f" "g";
    }
    a {
        counter-increment: link;
        text-decoration: none;
    }
    a:after {
        content: "▽" counter(link, linkmark);
        position: relative;
        bottom: 0.7em;
        font-size: 0.7em;
    }
</style>
</head>
<body>
Hello world <a href="moep">Test 1</a>.<br/>
Hello world <a href="moep">Test 2</a>.<br/>
Hello world <a href="moep">Test 3</a>.<br/>
</body>
```

Perhaps the prefix is not applied in the case of a `counter` and only in the case of lists?

**Comment by liZe** [comment]
> Perhaps the prefix is not applied in the case of a `counter` and only in the case of lists?

Yes, [prefix and suffix are not applied in `counter`](https://drafts.csswg.org/css-counter-styles-3/#descdef-counter-style-prefix), and Firefox gives the same result as WeasyPrint.

**Comment by mbarkhau** [comment]
Very well, thanks for the info.
