### ISSUE TITLE
CAIRO_STATUS_NO_MEMORY

### ISSUE THREAD

**Issue by jamma313** [Kozea/WeasyPrint#103]
When generating PDF with large images, Cairo failed with an out of memory error :

```
Failed to load image at [image.png] : MemoryError: ('cairo returned CAIRO_STATUS_NO_MEMORY: out of memory', 1)
WARNING:weasyprint:Failed to load image at http://example.com/image.png : MemoryError: ('cairo returned CAIRO_STATUS_NO_MEMORY: out of memory', 1)
```

Then weasyprint ends up generating a corrupted PDF.
Ghoscript says about it : 

```
   **** Warning: ignoring obj followed by multiple tokens.
   **** Warning: ignoring obj followed by multiple tokens.
   **** Error reading a content stream. The page may be incomplete.
```

Is there anything to do from weasyprint, or is it only Cairo related stuff ?

Thanks.

**Comment by cuu508** [comment]
I was getting the same error with Weasyprint versions 0.34 and 0.36, cairocffi versions 0.7.2 and 0.8.0. I eventually tracked the problem down to my use of webfonts. 

If I used `@font-face` in CSS, the document would usually render OK, but about 5% of times it would fail with the above error. Tried woff, otf, ttf formats, all were the same.

Once I switched to system-installed fonts (put fonts in `/usr/share/fonts` and use a simple `font-family: "Some Font"` CSS rule) the problem went away.

**Comment by liZe** [comment]
Just for future readers: the original issue is not related to `@font-face` as it wasn't supported at all in 2013.

@cuu508 thanks a lot for the report. If you can reproduce the issue, it would be interested to have this bug tracked in a separate issue.

**Comment by SimonSapin** [comment]
It seems that Cairo uses the same `CAIRO_STATUS_NO_MEMORY` error code for many unrelated error conditions.

**Comment by cuu508** [comment]
@liZe I was able to reproduce the issue, here's a sample: https://github.com/cuu508/weasyprint-103-testcase

If you create a new python3 virtualenv, install weasyprint and then run `render_in_loop.py`, it hits CAIRO_STATUS_NO_MEMORY after some dozens of iterations. Sometimes 20, sometimes 30, sometimes 100. 

Not sure where best to report this, and how to attach the binary files...

**Comment by liZe** [comment]
@cuu508 Thanks a lot, I can reproduce the issue too. You can open a new issue and keep your repository open until we find a solution, if it's OK for you.

**Comment by liZe** [comment]
Here's a simple version of your script without external SVG and font. DejaVu Sans needs to be installed on the system:
```python
from weasyprint import HTML

html = b"""
<style>
@page {
    @bottom-center {
        background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjxzdmcgd2lkdGg9IjEiIGhlaWdodD0iMSI+PHRleHQ+YTwvdGV4dD48L3N2Zz4K) no-repeat center center;
        content: "";
    }
    @bottom-left {
        content: "lorem ipsum";
        font-family: DejaVu;
    }
}
@font-face {
    font-family: DejaVu;
    src: local(DejaVu Sans);
}
</style>
"""

for i in range(0, 1000):
    print("Iteration %d" % i)
    HTML(string=html).write_pdf()
```

**Comment by liZe** [comment]
Even better:
```python
from weasyprint import HTML

html = b"""
<style>
  @font-face {
    font-family: DejaVu;
    src: local(DejaVu Sans);
  }
  html {
    font-family: DejaVu;
  }
</style>
lorem ipsum
<img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+Cjxzdmcgd2lkdGg9IjEiIGhlaWdodD0iMSI+PHRleHQ+YTwvdGV4dD48L3N2Zz4K"/>
"""

for i in range(0, 1000):
    print("Iteration %d" % i)
    HTML(string=html).write_pdf()
```

This example crashes only when the HTML text is rendered before the SVG, otherwise I get
```
process:18957): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='DejaVu Medium 12', text=' '
```

**Comment by cuu508** [comment]
Nice code golfing, @liZe ;-)
I opened #441
