### ISSUE TITLE
Ordered List Count Reset After Page-break

### ISSUE THREAD

**Issue by craigpla** [Kozea/WeasyPrint#1032]
My lists are getting their counters reset after a page-break. This is the html (with comments within the li tags):
```
<ol type="1">
<li>It's #1</li>
<li>It's #2</li>
</ol>
<div class="pb">

</div>
<ol start="3" type="1">
<li>It's #1 <-- supposed to be #3</li>
<li>It's #2 <-- supposed to be #4</li>
```
That pb div in css:
```
.pb { break-after: always; }
```
Is there something simple I can change in a config file somewhere, or is this bigger than that?

**Comment by liZe** [comment]
Hi!

The problem is not page breaks, it’s [presentational hints](https://weasyprint.readthedocs.io/en/stable/features.html#html). You have to launch WeasyPrint with the `--presentational-hints` option.
