### ISSUE TITLE
I cannot install cairo on amazon linux

### ISSUE THREAD

**Issue by izanf** [Kozea/WeasyPrint#1035]
Someone have any idea for fix this problem?

<img width="935" alt="Screen Shot 2020-01-17 at 05 29 32" src="https://user-images.githubusercontent.com/13179054/72596311-92865000-38ea-11ea-920f-27616af20b4d.png">

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)

**Comment by liZe** [comment]
Hello!

You should follow what’s in #952, and even write a little bit of documentation if it worked for you :wink:.

**Comment by izanf** [comment]
Not is the same, I'm not using lambda.

**Comment by izanf** [comment]
<img width="592" alt="Screen Shot 2020-01-17 at 18 19 25" src="https://user-images.githubusercontent.com/13179054/72649157-a61dcf00-395b-11ea-8608-5c373610c3d8.png">
I was installed cairo, but still it's showing the same error

**Comment by izanf** [comment]
**Update:**

I had not installed the cairo inside docker image, but on my operation system (Amazon Linux). I fixed this problem installing cairo and other dependencies on Alpine (Docker Image).

**Comment by liZe** [comment]
> I had not installed the cairo inside docker image, but on my operation system (Amazon Linux). I fixed this problem installing cairo and other dependencies on Alpine (Docker Image).

Thanks for updating this issue!
