### ISSUE TITLE
UserWarning: FontConfig: No fonts configured.

### ISSUE THREAD

**Issue by izanf** [Kozea/WeasyPrint#1038]
I'm having this error when I try to use the weasyprint

```
/usr/local/lib/python3.6/site-packages/weasyprint/fonts.py:230: UserWarning: FontConfig: No fonts configured. Expect ugly output.
  'FontConfig: No fonts configured. '
/usr/local/lib/python3.6/site-packages/weasyprint/document.py:36: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
```

and the rendering:
<img width="886" alt="Screen Shot 2020-01-22 at 20 30 16" src="https://user-images.githubusercontent.com/13179054/72943897-0a72d100-3d56-11ea-9a34-c96515cd68ab.png">

**Comment by izanf** [comment]
I resolve installing font-config on Alpine Linux

**Comment by EricLewe** [comment]
I got squares (and the warning) despite having fontconfig installed. This was due to me not having any other fonts installed. Hence it was resolved once I added google fonts. (This came in handy for me https://stackoverflow.com/questions/56937689/alpine-linux-fonts)

**Comment by yashvarshney003** [comment]
Any idea how to resolve for macos?

**Comment by realFranco** [comment]
For `alpine:3.20.0` this was solve installing the next fonts (follow the packages 

```bash
RUN apk update --no-cache && \
    apk add --no-cache
apk install 
        # weasyprint=62.1-r0 \
        # Add fonts.
        fontconfig=2.15.0-r1 \
        # ttf-freefont \
        font-noto=23.7.1-r0
        # terminus-font
```
