### ISSUE TITLE
Foreign language support

### ISSUE THREAD

**Issue by pinnareet** [Kozea/WeasyPrint#1042]
Hi, 

I'm trying to use HTML.write_pdf to convert an HTML in Thai language to PDF but it doesn't work. Is there a way to add a language or font in WeasyPrint? Thanks!
<img width="821" alt="Screen Shot 2563-01-27 at 23 56 26" src="https://user-images.githubusercontent.com/4829500/73245236-a2125e00-4160-11ea-958e-656f68b00402.png">

**Comment by pinnareet** [comment]
Figured out FontConfiguration. Thanks!

**Comment by liZe** [comment]
:smile:
