### ISSUE TITLE
Custom footer on all pages, except some

### ISSUE THREAD

**Issue by DougBeney** [Kozea/WeasyPrint#1043]
I have a basic footer:

```html
    <footer>
      <a href="#table-of-contents">Jump to the Table of Contents</a>
    </footer>
```

Styled with this CSS:

```
footer {
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
}
```

I would like to hide this footer on the cover page (`@page :first`) and one more page (`@page google-analytics`).

Is this possible?

**Comment by liZe** [comment]
Tontyna’s solution seems to be a good one. Feel free to reopen if needed.

**Comment by cagostino** [comment]
i've tried implementing the above solution but am not getting it to work.  
could you provide a more complete solution with the html and the actual css styling not just positioning? and with the weasyprint HTML calls?

**Comment by liZe** [comment]
> could you provide a more complete solution with the html and the actual css styling not just positioning? and with the weasyprint HTML calls?

You can now use [running elements](https://drafts.csswg.org/css-gcpm/#running-elements) and [named pages](https://drafts.csswg.org/css-page/#using-named-pages) to get your footer on all pages except some.

Here’s an example:
```html
<style>
  h1 { break-after: page }
  h1.do-not-display-footer { page: no-footer }
  footer { position: running(running-footer) }
  @page { @bottom-center { content: element(running-footer) } }
  @page no-footer { @bottom-center { content: none } }
</style>
<footer>footer</footer>
<h1>Page 1</h1>
<h1>Page 2</h1>
<h1 class="do-not-display-footer">Page 3 (no footer)</h1>
<h1>Page 4</h1>
```

**Comment by cagostino** [comment]
thanks for the help. i've got my issue working now at least in that i can include the link-bearing footer in the document footer. still strangely  not appearing on every page but ill figure that out and post a fixed version with the python calls too in case others run into this thread too

**Comment by cagostino** [comment]
okay, python method below. something that was not obvious to me when trying things out was that the <footer> tag in the html must appear before the other elements in the html body so mentioning that in case others run across this too.

`
from weasyprint import HTML

html_content = """
<!DOCTYPE html>
<html>
<head>
    <style>
        @page {
            margin: 1cm 0cm 4cm 0cm;
            @bottom-center {
                content: element(page-footer);
            }
        }
        footer {
            position: running(page-footer);
        }
    </style>
</head>
<body>
        <footer>
                This contains the example footer that will appear on every page.
            </footer> 
    <div>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>
        <p>Page content goes here. Repeat or add more content to ensure multiple pages are generated.</p>

    </div>
</body>
</html>
"""

# Path for the output PDF file
output_pdf_path = 'output.pdf'

# Generate the PDF directly from the HTML string
HTML(string=html_content).write_pdf(output_pdf_path)
`

**Comment by Sylvester-primeng** [comment]
> Tontyna’s solution seems to be a good one. Feel free to reopen if needed.





https://csser.space/questions/bottom-section-of-a-multi-level-website-with-horizontal-dividers
