### ISSUE TITLE
ordered list type ignored: <ol type="a"> numbers instead of a, b, c, ...

### ISSUE THREAD

**Issue by vackosar** [Kozea/WeasyPrint#1046]
```
<ol type="a">
  <li>First</li>
  <li>Second</li>
</ol>
```
converts to 
```
1. First
2. Second
```
but should be
```
a. First
b. Second
```

**Comment by vackosar** [comment]
Can I donate somewhere to get this one fixed?

**Comment by liZe** [comment]
Hi!

> Can I donate somewhere to get this one fixed?

Good news: it’s already fixed :wink:. `type="a"` is a [presentational hint](https://weasyprint.readthedocs.io/en/stable/features.html#html), adding the `--presentational-hints` parameter fixes the problem.
