### ISSUE TITLE
Installing WeasyPrint on Windows x32 

### ISSUE THREAD

**Issue by antuaneacion** [Kozea/WeasyPrint#1049]
I installed WeasyPrint in win32 and GTK but still i got this error  
" raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e"

**Comment by liZe** [comment]
Hello,

This message means that the Cairo library is not correctly installed on your system. You should carefully follow the instructions of the ["Installing" page](https://weasyprint.readthedocs.io/en/latest/install.html#windows), and in particular the paragraph about installing GTK on Windows 32 bit.

**Comment by antuaneacion** [comment]
I tried to install it but i could't ,thanks anyway.

**Comment by liZe** [comment]
Closing, as Windows 32 bit support will be dropped (even by Microsoft) soon. Please use 64 bit software :smile:.
