### ISSUE TITLE
Mac: Could not load GDK-Pixbuf. PNG and SVG are the only image formats available.

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1056]
Is there a way to get JPG support on MacOSX (Catalina)?

ERROR: Failed to load image at "file:///Users/ajung/src/print-css-rocks/lessons/lesson-basic/kanguru.jpg" (Could not load GDK-Pixbuf. PNG and SVG are the only image formats available.)

**Comment by liZe** [comment]
GDK-Pixbuf is supposed to be provided by [`brew gdk-pixbuf`](https://weasyprint.readthedocs.io/en/latest/install.html#macos), did you get an error during the installation?

**Comment by liZe** [comment]
I think that installing the gdk-pixbuf package fixes this error. Feel free to reopen if you have further information about this problem.

**Comment by endelwar** [comment]
I fixed this error on Debian 10 by installing libgdk-pixbuf2.0-dev

\`apt install libgdk-pixbuf2.0-dev\`

**Comment by FrankyBoy** [comment]
So why is this dependency not mentioned in the [installation instructions](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation), maybe as an optional dependency or such? Seems like a glaring omission to me.

**Comment by liZe** [comment]
> So why is this dependency not mentioned in the [installation instructions](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation), maybe as an optional dependency or such? Seems like a glaring omission to me. (PS: yes I just ran into the same issue)

Because it’s not needed since version 53 :wink:.

**Comment by FrankyBoy** [comment]
Heh, good point there ... yeah I def. need to update some packages in this old codebase I inherited here :D
