### ISSUE TITLE
Add support of block-overflow

### ISSUE THREAD

**Issue by colorcube** [Kozea/WeasyPrint#1057]
With very limited space or fixed layouts the possibilities to handle too long text are not enough (overflow).

For example it would be nice to be able to limit a text to 3 lines.

`overflow:hidden` is not really a solution to the problem because you need a fixed height. If my text is only 2 lines high, I'll get an empty line. That's not always what I want. Even setting a fixed height is not as easy as it sounds. For example the height of UL-LI is not predictable if you have LI margins different to line height and sometimes a  LI has two lines.

`text-overflow: ellipsis;` is implemented in weasyprint but it is very limited.

I know this issue is a very general one and describes not only one problem. As I don't know the solution(s) yet I would like to discuss the problem here. I'm aware that maybe CSS itself has no solution. 

What's needed (I guess):

- make text-overflow work with white-space: normal
- make text-overflow work with UL/OL
- possibility to use max-height with text-overflow
- the box shrink to the displayed lines/text and not max-height
- setting the max-height to x lines would be nice (that's way out of CSS spec I guess)

For a more visual description here's an image of `text-overflow: ellipsis;` and what the limitations are

![text-overflow](https://user-images.githubusercontent.com/13253123/74235793-19530080-4cd0-11ea-8c41-1ba75fd6993e.png)

**Comment by liZe** [comment]
Hi!

What you want is `[break-overflow](https://www.w3.org/TR/css-overflow-3/#block-ellipsis)`. It’s currently supported by browsers using the `-webkit-line-clamp` property (even in Firefox), but in a very limited way.

We should follow the specs and do better with WeasyPrint!

**Comment by rainer-maucher** [comment]
Hi there thanks for your awesome work on WeasyPrint. I would courrently have a big need on the feature requested here. - Can you give a forecast if it will be implemented and or when? - Or if already happened how i can use it? - I dont manage to get it to work...

**Comment by grewn0uille** [comment]
Hello @rainer-maucher! We have already worked on this feature, it should be merged very soon ;)
