### ISSUE TITLE
Performance number. 

### ISSUE THREAD

**Issue by keshcode** [Kozea/WeasyPrint#1060]
Do we have any performance numbers for this lib . what is the max html file size that we support. let assume , if the file size in Gb's . can we still use this lib. or some sort chunking has to be done. for better performance .

**Comment by liZe** [comment]
Hi!

Performance highly depends on the performance of your computer, there’s no hard limit. If you have very large documents, you’ll probably need a fast CPU and a lot of RAM.

Having more CPU cores won’t help.

You can find some interesting metrics on [WeasyPerf’s website](https://kozea.github.io/WeasyPerf/index.html). Time spent to render these documents is only useful to compare versions, but you can get a pretty good idea of the RAM you’ll need.

If you don’t rely on automatic page breaks, page numbers and other related features, chunking can be a solution.

**Comment by keshcode** [comment]
[Link](https://kozea.github.io/WeasyPerf/index.html) What is the difference between Large and Documentation in the mentioned.

**Comment by liZe** [comment]
You can click on the titles and view the sample documents (some URLs only work locally, that’s why CSS is sometimes missing). Documentation is an average document (258 KB) and Large is a larger (:smile:) document (2.8 MB, 721 pages).
