### ISSUE TITLE
circular import in example (gitlab/docker/alpine)

### ISSUE THREAD

**Issue by dcpc007** [Kozea/WeasyPrint#1065]
Hi i want try waesyprint for a simple html2pdf.

i create a script :
```
#!/usr/bin/env python3

try:
    from weasyprint import HTML
except ImportError as error:
    print('ImportError: ' + str(error))
    exit(1)

HTML(filename='www/cv.html').write_pdf('www/weasyprint.pdf')
```
and i get this error :
` ImportError: cannot import name 'HTML' from partially initialized module 'weasyprint' (most likely due to a circular import) (/builds/davidchalon/cv/weasyprint.py)`

i use it in gitlab.com via CI in a docker alpine image.

```.gitlab-ci.yaml
pdf:
  image: python:alpine
  stage: final
  script:
    - apk add --update make
    - apk add --update python3-dev 
    - apk add --update gcc musl-dev jpeg-dev zlib-dev libffi-dev cairo-dev pango-dev gdk-pixbuf-dev
    - pip3 install weasyprint
    - touch www/cv.html www/cv.en.html www/assets/css/cv.css
    - ./weasyprint.py 
```

**Comment by dcpc007** [comment]
i make another test : 
```
import weasyprint
HTML(filename='www/cv.html').write_pdf('www/weasyprint.pdf')
```
ang got 
```
Traceback (most recent call last):
  File "./weasyprint.py", line 6, in <module>
    import weasyprint
  File "/builds/davidchalon/cv/weasyprint.py", line 11, in <module>
    HTML(filename='www/cv.html').write_pdf('www/weasyprint.pdf')
NameError: name 'HTML' is not defined
```

**Comment by liZe** [comment]
Hi, and thank you for this issue.

> ```yaml
> ./weasyprint.py 
> ```

The problem is here: Python thinks that the `weasyprint` module is your `weasyprint.py` file, not the `weasyprint` module. Just use a different name for your script, it will fix your problem.

**Comment by dcpc007** [comment]
Arf... thank you...
Sorry for this beginner error...

**Comment by liZe** [comment]
> Arf... thank you...
> Sorry for this beginner error...

No problem :wink:, have fun with WeasyPrint!
