### ISSUE TITLE
problems to renders pdf with Cairo 1.15.4

### ISSUE THREAD

**Issue by sergio-c** [Kozea/WeasyPrint#1066]
UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html

This is problem was after install in the ubuntu 16.04!

**Comment by liZe** [comment]
> This is problem was after install in the ubuntu 16.04!

This is just a warning. You can find extra information [in this note](https://weasyprint.readthedocs.io/en/latest/install.html#id5). WeasyPrint works, but some features are missing.

You can use a more recent version of Ubuntu if you really need the missing features. Ubuntu 18.04 includes cairo 1.15.10.
