### ISSUE TITLE
'WeasyPrint/samples/report/' does not include source .py

### ISSUE THREAD

**Issue by mhunterak** [Kozea/WeasyPrint#1067]
I would love to see an example of how page numbers are executed

**Comment by liZe** [comment]
Hello!

There’s no Python source for the samples, you can generate the PDF using the `weasyprint` command in a terminal.

For the report sample, page numbers are added [by this CSS line](https://github.com/Kozea/WeasyPrint/blob/gh-pages/samples/report/report.css#L32): the `page` counter is put in the top-left margin of the page.
