### ISSUE TITLE
python / html2pdf : page layout not respected

### ISSUE THREAD

**Issue by dcpc007** [Kozea/WeasyPrint#1068]
Hi,

I try to use weasyprint via python to auto generate a pdf from an html+css web page in a CI job (on gitlab.com).

I succeed in configuring the docker image (alpine), environment and executing without major error the script.
I only got this currently : 
" /usr/local/lib/python3.8/site-packages/weasyprint/fonts.py:229: UserWarning: FontConfig: No fonts configured. Expect ugly output."

But the pdf ouput doen't take the page layout. each block, like title, right column, main columns, are displayed one after the other.

Here is the code : https://gitlab.com/davidchalon/cv/-/tree/16-pdf-rendering-error (working on it)
``` python3
from weasyprint import HTML, CSS
from weasyprint.fonts import FontConfiguration

font_config = FontConfiguration()
HTML(filename='www/cv.html').write_pdf('www/weasyprint.pdf', stylesheets=[CSS(filename='www/assets/css/cv.css')], font_config=font_config)
```

I'm on a python discord, don't know if there is other source of help. I try to use the examples in the tutorial doc

**Comment by liZe** [comment]
Hello!

> Here is the code : https://gitlab.com/davidchalon/cv/-/tree/16-pdf-rendering-error (working on it)

Your link is broken, maybe it’s a private repository?

> But the pdf ouput doen't take the page layout. each block, like title, right column, main columns, are displayed one after the other.

It often means that, for some reason, CSS has not been applied.

**Comment by dcpc007** [comment]
Visibility changed.
