### ISSUE TITLE
NBSP between HTML tags break

### ISSUE THREAD

**Issue by muzzamilkhan** [Kozea/WeasyPrint#1075]
Hi, 

First off, great job with WeasyPrint, have been using it for awhile now and seems a pretty reliable tool!

I am running into an issue when placing a non-breaking space (&nbsp;) between HTML tags do not work as expected. Eg: `<span>This sentence should not></span>&nbsp;<span>break</span>`

I have tried this html in the browser and it seems the sentence stays together but does not work when PDF is rendered through WeasyPrint. I have had luck with wrapping the whole thing in `<span style="white-space: nowrap;">....</span>` tag, but this seems like a hack rather than a proper solution. 

Really appreciate any help, thanks!

**Comment by liZe** [comment]
This bug is fixed, at least in 52.5 and 53.
