### ISSUE TITLE
Looking to create a PDF on a letterhead but letterhead doesn't show up

### ISSUE THREAD

**Issue by tapanpandita** [Kozea/WeasyPrint#1078]
Hi, I'm trying to create a PDF from HTML, such that, every page of the PDF is on a letterhead. I have an A4 size image of the letterhead which I have set as the background image of the page. However, when I try to create the PDF, the letterhead image just doesn't show up. Here's the code I'm using -
```python
from weasyprint import HTML, CSS


def make_pdf_from_html(html_path, top, bottom, left, right, output_path):
    page_css = '''
    @page {{
        size: A4;
        margin-top: {margin_top}mm;
        margin-bottom: {margin_bottom}mm;
        margin-left: {margin_left}mm;
        margin-right: {margin_right}mm;
        background-image: url("letterhead.jpg");
    }}

    table {{
        page-break-inside: avoid;
    }}

    h1, h2, h3, h4, h5 {{
        page-break-after: avoid;
    }}
    '''.format(
        margin_top=top,
        margin_bottom=bottom,
        margin_left=left,
        margin_right=right,
    )

    css = CSS(string=page_css)
    html = HTML(html_path)

    html.write_pdf(output_path, stylesheets=[css])


make_pdf_from_html('test.html', 30, 30, 10, 10, 'test.pdf')
```
Example letterhead I'm using to test - https://i.ibb.co/J7DzL2p/letterhead.jpg

Am I doing something wrong here?

**Comment by tapanpandita** [comment]
Ok, I expected it to pick up the letterhead image from the same folder but it didn't. If I use a hosted url for the letterhead image, it works then!

**Comment by liZe** [comment]
> Ok, I expected it to pick up the letterhead image from the same folder but it didn't. If I use a hosted url for the letterhead image, it works then!

You can give the `base_url` parameter to `CSS()` (with something like `file:///path/to/my/image/folder`) :wink:.
