### ISSUE TITLE
Support for <template> tag

### ISSUE THREAD

**Issue by jnsdrtlf** [Kozea/WeasyPrint#1080]
The `<template>` tag is supposed to hold HTML without rendering it (see https://developer.mozilla.org/de/docs/Web/HTML/Element/template). However, using this tag in a WeasyPrint document results in its content is being rendered.

**Comment by jnsdrtlf** [comment]
What I am trying to do is to set named stings (using something like this`string-set: text-bottom-right content()`) on a tag that is not rendered in the resulting PDF.  
This might be helpful to set the `content` of e.g. `@page @bottom-right` using HTML that might change on each new page, similar to the way headings might be implemented – just without displaying the tag that sets the variable.  
So what I am also asking is whether there is a easier and recommended way of doing so.

**Comment by jnsdrtlf** [comment]
Maybe this is similar to what #473 is trying to achieve.

**Comment by liZe** [comment]
> Maybe this is similar to what #473 is trying to achieve.

You’re right. The solution is to add `template { display: none }` to the [user agent stylesheet](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/css/html5_ua.css) and to fix #473.

We can do the first step and close this issue, #473 will have to be fixed later.

**Comment by jnsdrtlf** [comment]
Added in commit 29309aa:
https://github.com/Kozea/WeasyPrint/blob/29309aa67359a7629a47a37305306db6e87ecde4/weasyprint/css/html5_ua.css#L472

So this means that the `<template>` tag is now hidden. But extracting a string using 
```css
string-set: varname content()
```
is still not possible due to issue #473, right?

**Comment by liZe** [comment]
> is still not possible due to issue #473, right?

Right, we’ll have to fix #473 to make `string-set` work with hidden elements.
