### ISSUE TITLE
table border formating overritten for last row on page

### ISSUE THREAD

**Issue by krug33** [Kozea/WeasyPrint#1086]
Hello everybody,

first of all, I want to thank you for this great tool.

I’m working with it to make pdf-invoices with letterhead and content tables, which are separated in
*  `thead` with margin to top for page-break and column header on every page
*  `tfoot` with margin to the bottom for page-break
*  `tbody` with start, content and result rows

The column header and content rows have inner and outer borders, the start and result row have just an outer border and margin-rows have no border.

**Now my problem is**, if the table goes over more than one page, on every page the last content-row has the same border formatting as the last row of the whole table. In case of fig 1, this is the margin-row that is in `tfoot` and has no borders.

![grafik](https://user-images.githubusercontent.com/52001609/77548168-75539c00-6eae-11ea-9205-79d559d7a925.png)

I've tried several modifications to CSS but got no success.
Do I anything wrong or is it a bug?

Thank you and best regards
Thomas

PS: I attached the HTML including CSS and resulting PDF.

[pagingTableBorderExample.txt](https://github.com/Kozea/WeasyPrint/files/4381491/pagingTableBorderExample.txt)
[test.pdf](https://github.com/Kozea/WeasyPrint/files/4381592/test.pdf)

**Comment by liZe** [comment]
Hmmmm… I think that it’s been fixed, let me find the commit…

**Comment by liZe** [comment]
> Hmmmm… I think that it’s been fixed, let me find the commit…

It’s somehow fixed by f0231c8, but we still miss the bottom border. That’s strange…

**Comment by liZe** [comment]
> It’s somehow fixed by [f0231c8](https://github.com/Kozea/WeasyPrint/commit/f0231c8b15e45e06be6658a9865ed5bcc5a2a270), but we still miss the bottom border. That’s strange…

It’s because you have no border on your table footer. So… It’s fixed, and included in 52.2!
