### ISSUE TITLE
Declarative way to add accessibility tags to PDFs

### ISSUE THREAD

**Issue by codekiln** [Kozea/WeasyPrint#1088]
In many industries, accessibility is a big deal. It's impossible for a PDF to be considered accessible unless it's "tagged": 

1. [WebAIM's guide to accessible PDFs](https://webaim.org/techniques/acrobat/)
2. [Section 508's guide to creating accessible PDFs](https://www.section508.gov/create/pdfs)
3. [Acrobat's Accessibility Portal](https://www.adobe.com/accessibility/products/acrobat.html)
4. [U of MN's guide to Accessible PDFs](https://accessibility.umn.edu/documents/creating-accessible-pdfs)
5. [WebAIM mailing list archives that mention WeasyPrint](https://webaim.org/discussion/mail_thread?thread=9188) 

If accessibility tagging was added to weasyprint, it would be an ace in the hole for many industries. The current state of the art seems to be to do a whole lot of clicking in acrobat. 

If the input HTML had certain special attributes, weasyprint could apply the equivalent accessibility tags.

**Comment by liZe** [comment]
It would be possible if we had our own PDF generator or post-processor. If someone is interested in replacing Cairo…

**Comment by mohdnajdy** [comment]
@liZe 
1. how much work would you think it is to replace Cairo ?
2. to what you would suggest to replace it to ?

**Comment by liZe** [comment]
> 1. how much work would you think it is to replace Cairo ?

A lot (see #841).

> 2. to what you would suggest to replace it to ?

A pure-Python library generating PDF. I’m not fond of reportlab, but something like that should be OK.

(I’m currently reading the PDF spec to write such a library, but that’s a secret :wink:.)

**Comment by NicolasGoeddel** [comment]
This sounds very interesting. I would really appreciate the effort to implement the tagging of PDF documents.

**Comment by JohannesMunk** [comment]
Dear Lize!

We also now have the requirement of a tagged and accessible PDF. After some research I found:
https://www.cairographics.org/news/cairo-1.16.0/

> The PDF backend has gained support for .. tags.  Tags permit adding
  logical info such as headings, tables, figures, etc. that facilitates
  indexing, accessibility, text reflow, searching, and extraction of the
  tagged items to other software.  For details on this new PDF
  functionality, see:
    https://lists.cairographics.org/archives/cairo/2016-June/027427.html

And directly in the Cairo docs:
https://www.cairographics.org/manual/cairo-Tags-and-Links.html#doc-struct

It does seem to me, that Cairo does indeed support the required structural tagging. 

As a standard HTML uses all these tags allready, it should be quite straight forward to map those to the appropriate PDF-Tags?

Let me know, if we can assist in any way to help this issue along!

As always, thanks a lot for your great library!

Johannes

**Comment by liZe** [comment]
> It does seem to me, that Cairo does indeed support the required structural tagging.

It does, you’re right!

It means that it could be possible to add tags using Cairo. I don’t think that there’s currently an easy way to do this using only the public API of WeasyPrint, even with the new [`finisher` option](https://github.com/Kozea/WeasyPrint/pull/1096). We’ll drop Cairo soon, but it will be possible to do this with another library too.

If anyone wants to work on this, I can help!

**Comment by JohannesMunk** [comment]
Great news! 
1) Without any promises, how soon will you be dropping Cairo?
2) Assuming that 1) will not be happening in the next 4 weeks, if we supported your patreon campaign, would you be willing to tackle this issue still using Cairo?
3) If not, I would welcome some ideas on where and how you would like to see me implement this..

**Comment by liZe** [comment]
> 1. Without any promises, how soon will you be dropping Cairo?

Next release will come in September (I hope), next one will be without Cairo (may take time for users to test and report broken corner cases).

> 2\. Assuming that 1) will not be happening in the next 4 weeks, if we supported your patreon campaign, would you be willing to tackle this issue still using Cairo?

Big secret: we’re currently building a small structure dedicated to WeasyPrint and its dependencies (and misc free software), you shouldn’t give to the patreon campaign and wait for a the end of the month, we’ll have more time and more resources to implement the features you want :wink:.

> 3\. If not, I would welcome some ideas on where and how you would like to see me implement this..

It will be easier without Cairo, as we’ll have a dedicated library to create PDF files, and won’t have the Cairo surface / PDF bytestring separation as it’s done now.

**Comment by JohannesMunk** [comment]
Sounds great! Looking forward to a bright future, where pdf writing is fully under your control :-)

But I can't put our current project on that timetable. So I just looked into the code.. it was very straight forward to put a few calls to context.tag_begin and tag_end into draw.py with the appropriate mappings from element_tag. Next step will be nested sections and table structures.

Will keep you posted!

**Comment by noelleleigh** [comment]
> So I just looked into the code.. it was very straight forward to put a few calls to context.tag_begin and tag_end into draw.py with the appropriate mappings from element_tag. 

Would you be willing to share a snippet that explains how to implement this strategy @JohannesMunk ?

**Comment by dariux** [comment]
With the Cairo dependency removed, are there any plans to accommodate Tag structures in Weasyprint/pydyf?

**Comment by duklin** [comment]
any update on this feature?
@JohannesMunk can you please share the changes in draw.py that you've made?

**Comment by liZe** [comment]
> any update on this feature?

Cairo has been removed and we now have a custom PDF writer, we technically have everything needed to add this feature. That’s not in the [roadmap](https://github.com/Kozea/WeasyPrint/milestones) yet, but we’d be happy to get the different use cases users may have.

**Comment by julian-kappler** [comment]
Are there any news about this issue? We are really interested on this feature. Thanks!

**Comment by liZe** [comment]
> Are there any news about this issue? We are really interested on this feature. Thanks!

We would really like to work on this feature (that would be really nice for accessibility), but that’s quite complex and would require some time to chose the right API, define what’s actually supported and, of course, to implement the feature.

After version 55 is released (soon!), we have a lot of things to do in [version 56](https://github.com/Kozea/WeasyPrint/milestone/33) with a solid support of Flexbox and Grid, and some sponsored features awaiting. If some companies are interested in sponsoring this feature and get it earlier, don’t hesitate to [get in touch](https://www.courtbouillon.org/#support)!

**Comment by liZe** [comment]
Version 57 will include PDF/UA support that includes accessibility tags automatically added out of the HTML structure of the document. If anyone is interested in this feature, don’t hesitate to test the current master branch and add a comment here!

**Comment by bandirom** [comment]
> 
Hello!
Can you clarify how can I  test PDF/UA support?
Im using PAC free program for testing support PDF/UA.

How I can add this settings?

![image](https://user-images.githubusercontent.com/46032838/205319719-9a6dbb57-5612-4109-a8c8-b8c764503484.png)

**Comment by grewn0uille** [comment]
Hello @bandirom,
Did you set `pdf-variant` to `pdf/ua-1` to enable PDF/UA generation?

**Comment by bandirom** [comment]
> Hello @bandirom, Did you set `pdf-variant` to `pdf/ua-1` to enable PDF/UA generation?

Probably no :(. Can you help with it. How to set it?

**Comment by grewn0uille** [comment]
> Probably no :(. Can you help with it. How to set it?

If you’re using WeasyPrint by command line, you can set the [`--pdf-variant`](https://doc.courtbouillon.org/weasyprint/stable/manpage.html?highlight=variant#cmdoption-pdf-variant) like this `weasyprint --pdf-variant=pdf/ua-1 document.html document.pdf`.

If you’re calling `write_pdf()` in your code, you can set the [`variant` parameter to "pdf/ua-1"](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/document.py#L314-L316).

**Comment by liZe** [comment]
@codekiln @malnajdi @malnajdi @JohannesMunk @noelleleigh @dariux @duklin Now that PDF/UA includes accessibility tags, is that sufficient for your needs?

**Comment by bandirom** [comment]
![image](https://user-images.githubusercontent.com/46032838/206174010-b4d298b2-c1aa-4764-8585-091039c8a07b.png)


![image](https://user-images.githubusercontent.com/46032838/206174199-09a11757-a6a4-4ac9-85a6-7638eacd0d07.png)


I tested a table. And I dont understand what is the empty boxes. 
If I manually removed this boxes tests were passed

Can you help?

**Comment by liZe** [comment]
> Im testing my pdf file and Adobe show me almost good result. Im checking detected issues

Thanks a lot for your report. Could you please open a new separate issue telling that tags are broken with tables (and a link to your comment, there’s no need to copy the text/images)?

**Comment by liZe** [comment]
> @codekiln @malnajdi @malnajdi @JohannesMunk @noelleleigh @dariux @duklin Now that PDF/UA includes accessibility tags, is that sufficient for your needs?

Don’t hesitate to add a comment here if there’s something else to add to the current PDF/UA export.

If you have found a bug (invalid documents, problems with the structure), please open a separate issue!

**Comment by CosaroLisa** [comment]
Hello, 
I'm trying to use the variant parameter in the  write_pdf(),  in order to get a tagged pdf, but it doesnt seem to work. My html is very simple, this is my code: 
```
 html_content = '''
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <title>Accessible Document Title</title>
            </head>
            <body>
                <header>
                    <h1>Document Title</h1>
                    <nav>
                        <ul>
                            <li><a href="#section1">Section 1</a></li>
                            <li><a href="#section2">Section 2</a></li>
                        </ul>
                    </nav>
                </header>
                <main>
                    <section id="section1">
                        <h2>Section 1</h2>
                        <p>This is a sample paragraph in section 1.</p>
                        <img src="example.jpg" alt="Description of the example image">
                    </section>
                    <section id="section2">
                        <h2>Section 2</h2>
                        <p>This is a sample paragraph in section 2.</p>
                        <table>
                            <caption>Description of the sample table</caption>
                            <tr>
                                <th>Header 1</th>
                                <th>Header 2</th>
                            </tr>
                            <tr>
                                <td>Data 1</td>
                                <td>Data 2</td>
                            </tr>
                        </table>
                    </section>
                </main>
                <footer>
                    <p>Document Footer</p>
                </footer>
            </body>
            </html>
            '''

            # Write the HTML content to a temporary file (optional)
            with open('document.html', 'w') as file:
                file.write(html_content)

            # Load the HTML and generate the PDF
            html = HTML('document.html')  # You can also pass html_content directly if not saving to a file
            html.write_pdf(os.path.join(output_dir, 'document.pdf'), variant='pdf/ua-1',
                           metadata={'Title': 'Accessible Document Title', 'Author': 'Author Name'})
```

What I get is a completely untagged pdf:
![image](https://github.com/user-attachments/assets/8ada4a9c-f8e4-4568-9172-7a3454607047)
![image](https://github.com/user-attachments/assets/023a1efb-4287-4277-ba57-08688c327f8a)


I don't get where the problem is in my code, since for everybody else it seems to work from the previous comments.

**Comment by liZe** [comment]
Hi @CosaroLisa!

First of all, please don’t add a comment to a closed issue. Don’t hesitate to open a new one!

Your problem is that the option is [`pdf_variant`](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.DEFAULT_OPTIONS), not `variant`.
