### ISSUE TITLE
Punctuation wrongly affects character count for hyphenation

### ISSUE THREAD

**Issue by Smylers** [Kozea/WeasyPrint#109]
Normally short words aren't ever split across lines and hyphenated, but if they have adjacent punctuation then WeasyPrint (version 0.19.2) wrongly treats them as though they were a longer word.

We've found “(LST)” being split as “(L-” at the end of one line and “ST)” at the start of the next. Evidence that the parens are being counted as word characters: setting this property avoids “(LST)” being split:

```
-weasy-hyphenate-limit-chars: 6 3;
```

(But obviously that could still hyphenate a 4-letter word with 2 adjacent punctuation marks. And in the general case requires setting `hyphenate-limit-chars` higher than you wish, thereby also disallowing hyphenating some words without punctuation which you'd wish to allow.)

CSS says to strip punctuation characters between words for counting their characters: http://dev.w3.org/csswg/css-text-4/#hyphenate-char-limits

Pyphen say that punctuation-stripping should be done outside of Pyphen:
https://github.com/Kozea/Pyphen/issues/4

Let me know if you'd like a sample document showing this happening.

**Comment by liZe** [comment]
Now that #74 and #100 are fixed, it was easier to handle this case.
