### ISSUE TITLE
Is it possible to take a screenshot only of a target element?

### ISSUE THREAD

**Issue by SJS830** [Kozea/WeasyPrint#1090]

**Comment by liZe** [comment]
It should be possible to get the position and size of the target, and then crop the generated image to only get the target. Has anyone ever done that?

**Comment by SJS830** [comment]
Cropping probably isn’t possible because css spacing is different for weasyprint compared to other renderers. I’ll keep the issue open in case somebody finds a solution but I’m pretty sure it’s impossible.

**Comment by liZe** [comment]
> Cropping probably isn’t possible because css spacing is different for weasyprint compared to other renderers.

Why is it different?

**Comment by SJS830** [comment]
What I meant is that compared to chrome, files are rendered slightly differently. It would be hard to determine the dimensions of a certain element in order to crop it.

**Comment by liZe** [comment]
> What I meant is that compared to chrome, files are rendered slightly differently.

There are some differences for sure (pagination, text rendering, missing features, bugs…), but these differences shouldn’t be more important than they are between Chrome and Firefox :smile:.

> It would be hard to determine the dimensions of a certain element in order to crop it.

At the end of the [`Document.render()`](https://github.com/Kozea/WeasyPrint/blob/29309aa67359a7629a47a37305306db6e87ecde4/weasyprint/__init__.py#L136), you can reach the `html` tag box of the first page using `rendering.pages[0]._page_box.children[0]` (`rendering` being the result of `Document._render(…)`). You can easily do that by subclassing `HTML.render` (even if `_page_box` is not public API).

A box with children has a `children` attribute that you can use to reach a peculiar tag box. To get the position and the size of a box, you can read [the `Box` class](https://github.com/Kozea/WeasyPrint/blob/29309aa67359a7629a47a37305306db6e87ecde4/weasyprint/formatting_structure/boxes.py#L61).

**Comment by liZe** [comment]
Taking a screenshot of a target element is not really useful now that we only generate PDF documents. Following the instructions of the previous comment could be possible, but the best solution is probably to use another tool like wkhtmltopdf.
