### ISSUE TITLE
Possible to add request context to Url Fetcher for Authentication?

### ISSUE THREAD

**Issue by blueslurpee** [Kozea/WeasyPrint#1095]
Hello, 

I am using this wonderful library with Django. 

I have secure images that are protected behind some checks in an S3 bucket. They are placed in image tags, with the protected url as the src. 

I would like to add the request object to the url requests in the HTML Render so that my View can take the appropraite attributes from said request (user), authenticate in the backend view, and return the file to be rendered. 

Is this possible, does anyone have any pointers to achieve this?

Sorry if this is not the correct way to ask this question, this is my first GitHub issue. 

Many thanks and all the best. 
Blueslurpee

**Comment by liZe** [comment]
Hello!

Yes, it’s possible. If you just want to "bypass" Django’s authentication, you can use [django-weasyprint](https://github.com/fdemmer/django-weasyprint) that will allow you to render Django statics with no extra request.

If you want more specific behavior, you can give to [weasyprint.HTML](https://weasyprint.readthedocs.io/en/stable/api.html#weasyprint.HTML) a `url_fetcher` parameter that will be the function used to get external URLs. You can duplicate and adapt the [`default_url_fetcher`](https://github.com/Kozea/WeasyPrint/blob/079f21251d886918bf99b71bc02f2da39dcb3e68/weasyprint/urls.py#L174) function to fit your needs.

**Comment by blueslurpee** [comment]
Amazing! Thanks!
