### ISSUE TITLE
Float images up/down LaTeX-style

### ISSUE THREAD

**Issue by timtroendle** [Kozea/WeasyPrint#1098]
In my documents there are many images. Often they lead to large blank spaces at the bottom of pages, when there is not enough space to place the image there.

It would be great if the images could float up and down so that the blank spaces are filled with the following paragraph, even if that means the following paragraph gets (partly) pulled ahead of the image. This feature exists in LaTeX.

I did not find that in the CSS standard, nor do I know how much work it would be to implement it. But it would be a great feature.

**Comment by liZe** [comment]
I think that you want [page floats](https://www.w3.org/TR/css-page-floats-3/), see #259!

**Comment by timtroendle** [comment]
Thanks @liZe , the working draft describes exactly what I am looking for.

If anyone has an idea for a manual workaround, I am happy to discuss.
