### ISSUE TITLE
No font works when using it in WSL and how to solve

### ISSUE THREAD

**Issue by runxel** [Kozea/WeasyPrint#1103]
<del>Cambria (which is installed and works fine) doesn't load. Instead the text will be ouputted with "Deja Vu" as font.</del>
<ins>Edit: I just figured out I was using pandoc + weasyprint with a makefile – which I use via the WSL in Windows. If anyone stumbles over this later, you have to share your Windows fonts (which you're most likely to reference in your CSS, with the Linux subsystem. How you do that is written [here](https://x410.dev/cookbook/wsl/sharing-windows-fonts-with-wsl/).</ins>

**Comment by liZe** [comment]
> Edit: I just figured out I was using pandoc + weasyprint with a makefile – which I use via the WSL in Windows.

Just curious: was it easy to install WeasyPrint on WSL?

> If anyone stumbles over this later, you have to share your Windows fonts (which you're most likely to reference in your CSS, with the Linux subsystem. How you do that is written [here](https://x410.dev/cookbook/wsl/sharing-windows-fonts-with-wsl/).

Thanks a lot for the answer and for the link, I’m sure it’ll be useful for other users.

**Comment by runxel** [comment]
Hi @liZe! Thanks for checking in :)


> Just curious: was it easy to install WeasyPrint on WSL?

Oh yes! A much better experience than on Windows natively 😅  (GTK3 is a pain on Windows, but I have done that as well, and once you spent that 30 minutes it also works quite reasonably!)
With the WSL it is basically as smooth as it can be. Copy&Paste from ReadTheDocs.
It's so hasslefree I forgot I'm running it on Linux in the first place – luckily I sorted it out by myself (this would have been a nightmare to make a sense of otherwise).


> Thanks a lot for the answer and for the link, I’m sure it’ll be useful for other users.

I hope so! 😊
