### ISSUE TITLE
External Fonts in SVG

### ISSUE THREAD

**Issue by laktak** [Kozea/WeasyPrint#1105]
Is it possible to use external fonts in an SVG?

This does not work - is there a workaround?
```
<svg xmlns="http://www.w3.org/2000/svg" height="60" width="400">
<style>
    @font-face { font-family: BalooPaaji2; src:url("fonts/BalooPaaji2-Regular.ttf"); }
</style>
<text x="0" y="15" fill="red" style="font-size:18px;font-family:BalooPaaji2">Hello Baloo!</text>
<text x="0" y="35" fill="black" style="font-size:18px;font-family:Arial">Hello Arial.</text>
</svg>
```

**Comment by malnajdi** [comment]
@laktak If you are on a Linux machine try to download and install the fonts


> ![image](https://user-images.githubusercontent.com/15247545/80439663-b4429a80-890f-11ea-9e9b-a82943f7cff7.png)


`sudo cp BalooPaaji2-* /usr/share/fonts/`

> ![image](https://user-images.githubusercontent.com/15247545/80439585-8eb59100-890f-11ea-817a-782fc280c431.png)

**Comment by laktak** [comment]
@malnajdi Thanks, I will try that.

**Comment by liZe** [comment]
> Is it possible to use external fonts in an SVG?

`@font-face` is not supported in [CairoSVG](/Kozea/CairoSVG), the SVG renderer used by WeasyPrint. Installing the font is currently the only way to make it work.

If you are interested in having this feature supported in CairoSVG, you can open an issue there.

**Comment by laktak** [comment]
Thanks!
