### ISSUE TITLE
Setup PDF access level

### ISSUE THREAD

**Issue by fabiobatalha** [Kozea/WeasyPrint#1107]
Is it possible to setup the pdf files to be read/print only files?

**Comment by liZe** [comment]
It should be possible now with the `finisher` function. Does anybody know how to do this in the PDF?

**Comment by liZe** [comment]
This (and many other features) can be easily added with another post-processing library like [pypdf](https://pypdf.readthedocs.io/en/latest/modules/PdfWriter.html?highlight=encrypt#pypdf.PdfWriter.encrypt).
