### ISSUE TITLE
Comma converts 'solid' to tuple

### ISSUE THREAD

**Issue by Tlki** [Kozea/WeasyPrint#1114]
Hello, just remove that comma.
https://github.com/Kozea/WeasyPrint/blob/29309aa67359a7629a47a37305306db6e87ecde4/weasyprint/formatting_structure/build.py#L1078

**Comment by liZe** [comment]
Hello,

Thank you for this bug report!

Do you have an example where this problem appears? That would be a good source of inspiration for a non-regression test :smile:.

**Comment by Tlki** [comment]
Hi!
In this line raise because it tries to do, in my case, style_scores[('solid',)]

https://github.com/Kozea/WeasyPrint/blob/68f4f5385ad5e7b2d7de4f1a0e1d9c7c023a500b/weasyprint/formatting_structure/build.py#L1013

But it seems that my code is running twice and that's why it comes to set_one_border as a tuple.

**Comment by liZe** [comment]
This comma definitely wrong, it was left here by c779977. Thanks again for the report!
