### ISSUE TITLE
Invalid indexing

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#1117]
Consider following document:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
</head>
<body>
  <ol>
    <li>A</li>
    <ol>
      <li>AA</li>
      <li>AB</li>
      <li>AC</li>
    </ol>
    <li>B</li>
  </ol>
</body>
</html>
```

Which renders correctly with Chrome as:

<img width="148" alt="Screenshot 2020-05-18 at 21 52 53" src="https://user-images.githubusercontent.com/401107/82253801-f3ce3680-9951-11ea-8a1e-f745b5a766fc.png">

But when rendered with Weasyprint, the last `<li>` is indexed incorrectly:

<img width="155" alt="Screenshot 2020-05-18 at 21 53 32" src="https://user-images.githubusercontent.com/401107/82253849-08aaca00-9952-11ea-87a2-0c23a404ac79.png">

[ result.pdf](https://github.com/Kozea/WeasyPrint/files/4646375/result.pdf)

**Comment by liZe** [comment]
Hello, and thank you for this bug report.

That’s ugly :unamused:.

I’m actually not sure that it’s a "real" bug, because Firefox gives the same rendering.

I think that your HTML document is not valid because [`ol` tags only allow `li` (and scripting) tags inside](https://www.w3.org/TR/html52/grouping-content.html#the-ol-element). I don’t know the behavior required by the spec, but my intuition is that it’s undefined.

4 is a really good undefined behavior, don’t you think? (NB: Even if there’s a question mark, that’s not a question, that’s a statement :wink:.)

If it’s OK for you, this issue will be closed as it’s probably not a bug in WeasyPrint according to the specification.

**Comment by liZe** [comment]
The "right" HTML structure for your example is :
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
</head>
<body>
  <ol>
    <li>A
      <ol>
        <li>AA</li>
        <li>AB</li>
        <li>AC</li>
      </ol>
    </li>
    <li>B</li>
  </ol>
</body>
</html>
```

**Comment by Tontyna** [comment]
> 4 is a really good undefined behavior, don’t you think?

It is **not** undefined, it's according to the scope of nested counters. WeasyPrint implements the implicit counters of `<ol>` along the lines of:

```css
ol { counter-reset: list-item; }
li::before {counter-increment: list-item; }
```

You can see the actual `list-item` counter values used by WeasyPrint with:

```css
li::before {
  content:  '(' counters(list-item,'.') ') ';  
}
```

![olist-item](https://user-images.githubusercontent.com/35614937/82310323-83143200-99c4-11ea-9c6b-3c645c8f5f9f.png)

Probably Chrome has another algorithm to increment their ordered list counters and I guess they did it as a service to account for sloggy html.

**Comment by liZe** [comment]
> It is **not** undefined, it's according to the scope of nested counters.

Of course. By undefined, I mean undefined in the specification, not undefined in WeasyPrint.

> Probably Chrome has another algorithm to increment their ordered list counters and I guess they did it as a service to account for sloppy html.

Possible. We won’t add a workaround for this case, as it’s really easy to fix the HTML.

**Comment by Tontyna** [comment]
Oh, the spec -- yes, there's only a [Sample Style Sheet](https://www.w3.org/TR/css-lists-3/#ua-stylesheet) to show how `<ol>` could `counter-reset` the predefined [implicit `list-item` counter](https://www.w3.org/TR/css-lists-3/#list-item-counter), to acquire properly numbered lists. But that's only informative, and insofar: undefined.

Not having Chrome installed, I'm wondering whether it uses a counter named `list-item` at all to style numbered lists or increments it in elements being `display:list-item`. PaleMoon 28.9 -- rendering the **2. B** expected by @knyttl -- definitely doesn't.

**Comment by knyttl** [comment]
Ok, thanks everyone for such research.
