### ISSUE TITLE
Ordered List start attribute not honored

### ISSUE THREAD

**Issue by jj-jitterbit** [Kozea/WeasyPrint#1118]
This small page does not render correctly; the `ol` lists with the `start` attributes don't start correctly. Instead of starting at `3` they start at `1`:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
<style>
  .pb {
page-break-before: always;
}
</style>
</head>
<body>
  <ol>
    <li>A</li>
    <li>B</li>
  </ol>
  <ol start="3">
    <li>Should start with three</li>
    <li>AB</li>
    <li>AC</li>
  </ol>
  <p></p>
  <ol>
    <li>A</li>
    <li>B</li>
  </ol>
  <p>Page break!</p>
<div class="pb">
</div>
  <ol start="3">
    <li>Should start with three</li>
    <li>AB</li>
    <li>AC</li>
  </ol>
</body>
</html>
```
This means that adding page breaks before a list item to keep with-next-item doesn't work because you can't restart the list at the correct index.

**Comment by jj-jitterbit** [comment]
I do note that if the above HTML is changed to put the `pb` on a list item, it will work:
```
  <ol>
    <li>A</li>
    <li>B</li>
    <li class="pb">Should start with three</li>
    <li>AB</li>
    <li>AC</li>
  </ol>
```

**Comment by Tontyna** [comment]
@jj-jitterbit -- the `start` attribute is ignored unless you run WeasyPrint with **presentational_hints**,
see the [documenation](https://weasyprint.readthedocs.io/en/stable/features.html?highlight=presentational_hints#html)

**Comment by jj-jitterbit** [comment]
@Tontyna Thanks for this. That solved my problem. I think that this section of the documentation needs to made more prominent, and advise new users to read that page in its entirety.
