### ISSUE TITLE
Lower Level Headings in TOC

### ISSUE THREAD

**Issue by craigbass76** [Kozea/WeasyPrint#1119]
Is there a way to get H4 incorporated into the TOC? H5 and H6 (not that I see the need, but it might be nice to at least have the option)

**Comment by Tontyna** [comment]
Should be no problem. The way to achieve it depends on the way you create your TOC. 

If you're referring to the outline in the PDF -- per default all heading levels are incorporated unless you exclude them via CSS `bookmark-level: none`
