### ISSUE TITLE
ToC with links and numbered headings

### ISSUE THREAD

**Issue by EugenMayer** [Kozea/WeasyPrint#1121]
Hello - first thank you a lot for this project. Amazing work and quality!

We are currently trying to get our TOC working again, which we used to generate in Apache FOP
 
 - [x] TOC for all header headings (using #652 and https://github.com/Kozea/WeasyPrint/issues/23#issuecomment-320909718 )
 - [x] Add level based indentation for TOC entries
 - [x] Ensure page numbers are correctly and prepend the toc
 - [x] Make a TOC entry link to its chapter
 - [x] Add the "numbering" to the header itself ( so Chapter A in the content is `1. ChapterA` and `First Subchapter of A` is `1.1 First Subchapter of A`

**Make a TOC entry link to its chapter**
Since we use `make_bookmark_tree` to extract all the bookmarks and `target` seem to be the coordinates for the link, i'am yet not sure how to actually make this a valid `<a href="#anchor">` based link ( or similar ). Any hints on that?

in `write_pdf` i found

```python
  link_attribs = 'page={} pos=[{} {}]'.format(
                    page + 1, int(round(x * scale)),
                    int(round(y * scale)))
```

Which seem to be about what i need, but how is that used inside the toc?
AFAICs it is used for the "outline page" ( MATA PAGE ) of the PDF

```python
surface.add_outline(
                    levels.pop(), title, link_attribs,
                    cairo.PDF_OUTLINE_FLAG_OPEN if state == 'open' else 0)
```

But can i use this for the inline TOC somehow?

**Add the "numbering" to the header itself**
I'am not sure if that is possible at all. The bookmarks have been already generated at `self.bookmarks` .. not sure but i support this is done via `_gather_links_and_bookmarks()`

What would be the best way to add this numbering ( inline numbering ) for the chapters?

Thank you a lot!

**Comment by Tontyna** [comment]
Once upon a time I created my TOCs with the help of a modified `make_bookmark_tree`. It was called `make_bookmark_tree_with_anchors` because it

1. created a unique `page.anchor` for each bookmark
2. returned the root of a `bookmark_tree_with_anchors` suitable for creating the links in my TOC

Nowadays I prefer to snatch and modify the `xml.etree.ElementTree`

```python
myhtml = weasyprint.HTML(input)
root = myhtml.etree_element

# query and modify the xml
# collect headings, apply id attributes ...
# ...

# tell weasyprint about the modifications
myhtml.wrapper_element = cssselect2.ElementWrapper.from_html_root(
   root, content_language=None)
myhtml.etree_element = myhtml.wrapper_element.etree_element

# render and export the adjusted HTML
document = myhtml.render()
document.write_pdf(target=output)
```

**Numbered headings** can be achieved via CSS counters, see for example https://codepen.io/X-Raym/pen/dBprG.
Of course this has to be adapted to your document structure.

If you cant or dont want to utilize CSS, then the xml approach allows for injecting arbitrary nodes and text into your document.

**Comment by EugenMayer** [comment]
> Once upon a time I created my TOCs with the help of a modified `make_bookmark_tree`. It was called `make_bookmark_tree_with_anchors` because it
> 
>     1. created a unique `page.anchor` for each bookmark
> 
>     2. returned the root of a `bookmark_tree_with_anchors` suitable for creating the links in my TOC
> 
> 
> Nowadays I prefer to snatch and modify the `xml.etree.ElementTree`
> 
> ```python
> myhtml = weasyprint.HTML(input)
> root = myhtml.etree_element
> 
> # query and modify the xml
> # collect headings, apply id attributes ...
> # ...
> 
> # tell weasyprint about the modifications
> myhtml.wrapper_element = cssselect2.ElementWrapper.from_html_root(
>    root, content_language=None)
> myhtml.etree_element = myhtml.wrapper_element.etree_element
> 
> # render and export the adjusted HTML
> document = myhtml.render()
> document.write_pdf(target=output)
> ```
Thank you, i'll dig into that. Maybe though we should consider adding those anchors by design, i do not think they harm but they enable all such things - adding the actual anchor value to the bookmarks also makes sence]

> 
> **Numbered headings** can be achieved via CSS counters, see for example [codepen.io/X-Raym/pen/dBprG](https://codepen.io/X-Raym/pen/dBprG).
> Of course this has to be adapted to your document structure.
> 
> If you cant or dont want to utilize CSS, then the xml approach allows for injecting arbitrary nodes and text into your document.

That just works out of the box - thank you very much!

**Comment by EugenMayer** [comment]
After looking into both solutions i have seen that we cannot neither use the generated booksmarks to generate our TOC 

.. nor we can use the CSS solution for numbering.

Reasons are

a) the CSS based numbering will cause the headers to include the numbers, but not the toc ( solvable by adding the numbering while rendering the TOC entries using the level most probably )
b) CSS numbering would not respect "book outlines" where we subnest an entire-page to a different without changing the actual headers of the subpage. We use c) nesting container and then expect this to mean that "from now on every heading inside this nesting prefixes the parent header". This of course is a custom solution and not going to work with the CSS solution - just way to customized
d) Since "Linked TOC" needs preprocessing anyway, and the current ToC based on the boomarks would not support our "book nesting", we would go the route of using our own pre-processor before even passing the content to weasyprint

So what we most probably going to do is d) for ToC and als for "heading numbering" in our own application, then pass it own to weasyprint. The html document will then
 - already include a topic ( with anchor links)
 - all headers will have numbering (including ) and anchors ( for the links above )

Now while doing that is just effort on our side, i see that we run into one problem, and that is the PDF outline generated based on the bookmarks would be wrong since it will not know the nesting. So my question is, how would we be able to fix that without hackgin weasyprint in terms of upstream updates:

 - can we "hook in" a different bookmark generation logic or something like that ( sounds not possible right now looking at the arch )
 - can we generate our own outline based on our existing TOC information / anchors
 - can we disable the entire PDF outline

Is one of those possible?

**Comment by Tontyna** [comment]
No need to fight the PDF outline: When you preprocess your book to inject the numbering and the anchors you can at the same time apply the appropriate `bookmark-level` to the headings.

**Comment by EugenMayer** [comment]
Just an update on my side. I did the full pre-processing

- add the numbering to the header
- add the anchor to the header
- add a bookmark level to the header 

While this all works i cannot add a `a href` based navigation, because wrapping the toc table entry with 

```
<ul class="toc">
<li><a href="#toc-1.2.2.2">%s </a><span class="toc-entry-page-number">%s</span></li>
%s
</ul>
```

the entry will not be clickable until i add a path like `/#toc-1.2.2.2` which will then open the file explorer instead. Any clues on that particular topic?

**Comment by Tontyna** [comment]
I don't get it -- how do you inject those unclickable toc entries into your final document?

If you want WeasyPrint to create clickable links, both, the link and the anchor, must be present in the `Document` when you call its `write_pdf` method.

**Comment by EugenMayer** [comment]
Sorry @Tontyna for the late reply - got dragged away.

I was doing the exact thing you are expecting me to do and it was not working. That's why i described, prerendering (offsite weasypring, so on the source systme) the toc-table with a-href based navigation works, while inserting it with the same a-href navigation using python + weasypring does not work.

In the end the weasyprint based table head for more issues to deal with, compared with the prerendered toc table.

What i did finally and got all the bits working is

 - pre-render the entire toc-table on the source-backed (generating the html)
 - add all the needed numbering preprocessed, on the toc-table and the headers themself
 - ensure to set the bookmark-level preprocessed too, so the pdf outline aligns with the custom toc
 - ensure i can identify the toc-table entry ( a-href ) using eletree when traversing over bookmarks, means using the bookmark-title ( md5 hased as an id on the href ) .. "back referenced needed when traversing from bookmarks"
 - then in the python based rest service, let the bookmarks be generated and then traverse over the bookmarks, for each bookmark find the corresponding toc-table entry using the md5-hash identifier ( using eletree / xpath ) and then insert hte page for that bookmark to the toc-entry ( since the toc-table yet is missing all the page entries )

Leaving this information mainly for other people look for how to deal with complex toc-scenarios with weasyprint

This way i got all the bits working, including a complex toc for single pages / books, clickable outline but also clickable toc-table and some internal things too.

For me, this issue can be closed, thank you for all your suggestions. It was quiet a ride finding the right approach for us in the end, but your guidance was very useful to navigate there. 

Close the issue as soon as you like.

**Comment by speakASAP** [comment]
I have the same issue with converting # within URL:
Example:
`<a href="{% url 'seven_lesson' lesson.course.language.code lesson.order %}\#exercises">Try it</a>`

generates link:
https://speakasap.com/ru/cz/seven/1/%23exercises

Means sign `#` is converted by weasyprint to `%23`

There is only manual workaround: https://community.adobe.com/t5/acrobat/ist-replaced-by-23-in-urls-gt-error-404/td-p/5811448?page=1 (if weasyprint uses some Adobe API?)

I found no way to put # to PDF so far.

**Comment by liZe** [comment]
> weasyprint generates wrong link:
> https://speakasap.com/ru/cz/seven/1/%23exercises
> instead of
> https://speakasap.com/ru/cz/seven/1/#exercises

I don’t have this problem, WeasyPrint 51 generates this for me:
```
8 0 obj
<< /Type /Annot
   /Subtype /Link
   /StructParent 0
   /QuadPoints [ 62 779 88 779 88 766 62 766 ]
   /Rect [ 62 766 88 779 ]
   /A <<
      /Type /Action
      /S /URI
      /URI (https://speakasap.com/ru/cz/seven/1/#exercises)
   >>
   /BS << /W 0 >>>>
endobj
```

**Comment by EugenMayer** [comment]
i would suggest creating a dedicated bug for this issue. AFAIU it depends on the way you add those hrefs with anchors. if you use the python eletree api, it did not work for me.

If it is part of the html string we initially render, it does work.

**Comment by liZe** [comment]
> i would suggest creating a dedicated bug for this issue

You’re right. @speakASAP Could you please open a new issue?

**Comment by liZe** [comment]
I think that we probably said everything that could be said for table of contents. Feel free to reopen if you have more questions about this!
