### ISSUE TITLE
Memory leak on render

### ISSUE THREAD

**Issue by pinkynrg** [Kozea/WeasyPrint#1123]
I have a django view that returns a report. For debug purposes I may pass a ?debug=true and instead of returning a PDF will return a regular html page. 

Whenever I call the PDF generation without debug=true I have a memory bump that doesn't get released. If I request the report in HTML format I don't have this bump (this debug flag makes me pretty confident that the issue is WeasyPrint). 

<img width="237" alt="Screen Shot 2020-05-26 at 10 24 46 AM" src="https://user-images.githubusercontent.com/1474127/82878100-54093d80-9f3b-11ea-80d7-9e4db51fbabc.png">

I'm using:

- Python 3.7.3
- WeasyPrint 51

I'll try to narrow down the exact line of code and I'll update the issue with details. 

In the mean time, if someone knows of a workaround that would be appreciated (like generating the pdf in a separate process would work?).

**Comment by liZe** [comment]
I think that this has been fixed by #2130.
