### ISSUE TITLE
Use download attribute in <a> tag for attachment's filename

### ISSUE THREAD

**Issue by nempoBu4** [Kozea/WeasyPrint#1126]
There is [`download`](https://www.w3schools.com/tags/att_a_download.asp) attribute in `<a>` tag which allows to specify the filename. If the value is specified then it should be used as the filename of attachment. If there is no extension in `download` attribute then it should be determined from `href`.
This feature will be especially useful for `<a>` tags with data URI in `href`.

[`download` attribute playgroubd](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_a_download2)

**Comment by liZe** [comment]
Hello!

Thank you for this feature request. If anybody’s interested in diving into WeasyPrint’s code, it’s a good way to start, just ask and I can help.

**Comment by lmcnulty** [comment]
@liZe I'd like to give this a shot. It looks like the relevant parts are `write_pdf_metadata` and `_write_pdf_attachment` in `pdf.py`?

**Comment by liZe** [comment]
> @liZe I'd like to give this a shot. It looks like the relevant parts are `write_pdf_metadata` and `_write_pdf_attachment` in `pdf.py`?

Indeed.
