### ISSUE TITLE
nbsp between html tags does not prevent break

### ISSUE THREAD

**Issue by lnprieto** [Kozea/WeasyPrint#1129]
Hi

We are experiencing issues with sentences which break up even if any nbsp are present between html tags.

If you can help us, I have attached some example files (html and css, plus the pdf computed) and here is the command line we use:

/usr/local/bin/weasyprint --encoding utf8 --format pdf --stylesheet 'web2pdf.css' --base-url 'http://journals.openedition.org/rac/' -v -d rac6867.html rac6867.pdf

[rac6867.zip](https://github.com/Kozea/WeasyPrint/files/4695908/rac6867.zip)

Thank you very much for any help

**Comment by Tontyna** [comment]
Another case of #1075?

**Comment by liZe** [comment]
Hello @lnprieto, thanks for the bug report!

> Another case of #1075?

It is.
