### ISSUE TITLE
Alpine 3.8 fonts

### ISSUE THREAD

**Issue by jonwhittlestone** [Kozea/WeasyPrint#1130]
Hi
Does anyone know why I get this in an Alpine 3.8 container? A django app that has created a PDF from a Pandas dataframe via Jinja with code like this

```
        html_out = template.render(template_vars)
        HTML(string=html_out).write_pdf(dest_path, stylesheets=["style.css", "customer_sheet.css"])
```

The fonts (glyphs?) render fine not in docker, my native OS of Ubuntu 18.04. Presumably an OS dep is missing and not a pip package.

Can provide more info. Hopefully this might look familiar to someone?

![image](https://user-images.githubusercontent.com/1681212/83330581-d2414900-a287-11ea-95d3-bd7697b2ec8d.png)

**Comment by liZe** [comment]
Hello!

You need to install fonts. Quite a lot of [Alpine font packages](https://pkgs.alpinelinux.org/packages?name=font-*&branch=edge&arch=x86_64) are available, Liberation is a good choice for example.

**Comment by jonwhittlestone** [comment]
thanks :) Simple as that
