### ISSUE TITLE
Need a single PDF with three copies of same document with Copy 1, Copy 2 and Copy 3

### ISSUE THREAD

**Issue by POOJASAINIAQUEVIX** [Kozea/WeasyPrint#1132]
Hello,

Need a single PDF with three copies of same document with Copy 1, Copy 2 and Copy 3.

Please check the code for PDF:
applied counter-reset on page.
<style>
@page {
    counter-reset:page 1;
    counter-reset:pages 1;
}

@page {
    @bottom-right{
      content: "Page " counter(page) " of " counter(pages);
    }
}
</style>
currently i am getting "Page 1 of 3" instead of "page 1 of 1" for each copy
I need :
first copy having: 
page 1 of 1

second copy having:  
page 1 of 1

for third having: 
page 1 of 1

When i applied "counter-reset:pages 1" for total pages, it is not working.
How would it possible to set counter-reset on Total Pages?

Thank You !!

**Comment by liZe** [comment]
@POOJASAINIAQUEVIX Does the solution above fix your problem?
