### ISSUE TITLE
Weasyprint can't find font on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Avagenzo** [Kozea/WeasyPrint#1133]
For some reason weasyprint can't find the font to render the pdf correctly on Ubuntu 20.04. Did the same steps on a windows machine and it worked. It generates the following output with the `--debug` parameter: 

```
INFO: Step 1 - Fetching and parsing HTML - ...
INFO: Step 2 - Fetching and parsing CSS - .../css/e/sr/latin/e/ssr/latin/e/ssb/latin/m2.css
WARNING: Ignored `unicode-range: U+0-7F,U+A0,U+200A,U+2014,U+2018,U+2019,U+201C,U+201D,U+2022,U+2026` at 7:3, descriptor not supported.
...
INFO: Step 2 - Fetching and parsing CSS - CSS string
WARNING: Ignored `text-rendering:optimizeLegibility` at 1:92, unknown property.
DEBUG: Ignored `-webkit-font-smoothing:antialiased` at 1:126, prefixed selectors are ignored.
WARNING: Ignored `min-height:100vh` at 1:201, invalid value.
DEBUG: Ignored `-webkit-tap-highlight-color:transparent` at 1:440, prefixed selectors are ignored.
INFO: Step 2 - Fetching and parsing CSS - CSS string
INFO: Step 2 - Fetching and parsing CSS - CSS string
WARNING: Ignored `height:100vh` at 1:237, invalid value.
WARNING: Ignored `width:100vw` at 1:253, invalid value.
WARNING: Ignored `fill:rgba(0, 0, 0, 0.84)` at 1:332, unknown property.
WARNING: Ignored `box-shadow:0 4px 12px 0 rgba(0, 0, 0, 0.05)` at 1:443, unknown property.
WARNING: Ignored `fill:rgba(0, 0, 0, 0.9)` at 1:577, unknown property.
WARNING: Ignored `fill:rgba(0, 0, 0, 0.54)` at 1:912, unknown property.
WARNING: Ignored `fill:rgba(102, 138, 170, 1)` at 1:973, unknown property.
DEBUG: Ignored `cursor:pointer` at 1:1154, the property does not apply for the print media.
...
INFO: Step 2 - Fetching and parsing CSS - CSS string
INFO: Step 3 - Applying CSS
INFO: Step 4 - Creating formatting structure
INFO: Step 5 - Creating layout - Page 1
INFO: Step 5 - Creating layout - Page 2
...
INFO: Step 6 - Drawing
INFO: Step 7 - Adding PDF metadata
```

The generated PDF has weird numbers in squares in it, which looks like unicode.

I read the documentation and some issues and tried the following things:

1.  Change default fall back font from Dejavu Sans to Liberation as described here: [Changing default font Ubuntu](http://eosrei.net/articles/2016/02/changing-default-fallback-subsitution-fonts-linux) `fc-match` gives me: `LiberationSans-Regular.ttf: "Liberation Sans" "Regular"`
2.  I added all @font-faces from the webpage and followed the example from the documentation: [Intantiating HTML and CSS Objects](https://weasyprint.readthedocs.io/en/latest/tutorial.html#instantiating-html-and-css-objects). Didn't fix the problem.

I installed all fonts required and see them with `fc-list`, but i don't know where to add them to get a correct output. Any help would be appreciated.

**Comment by liZe** [comment]
Hello!

The squares usually mean that the font used is a [fallback font](https://en.wikipedia.org/wiki/Fallback_font).

The easiest way to find what’s going on is to render a very simple document with no extra CSS (an HTML file with just `abc` is enough), and to see if the text is correctly drawn. If it works (and it should), it means that something in your CSS makes WeasyPrint use the fallback font. If it doesn’t, then there’s something wrong in your FontConfig configuration.

By the way, you can find the font used in the properties of your document, it may also help to explain why this font is used.

**Comment by liZe** [comment]
Feel free to reopen if your problem is not solved.
