### ISSUE TITLE
Table is being shunted down to next page

### ISSUE THREAD

**Issue by adamcunnington** [Kozea/WeasyPrint#1134]
When my table is small, it sits on page 1 directly below the header but when it is big, it is pushed down to the second page.

It is as if there is a page break that is being inserted before the table. I have spent 7 hours inserting page-break-before/inside/after and break-before/inside/after in every single place where I can think of it and it has no absolutely no effect.

The code here should work as far as I am aware (see lines 26 and 27); https://github.com/adamcunnington/foodbank-southlondon/blob/master/backend/foodbank_southlondon/templates/shopping-lists.html

I have also posted on stackoverflow about this - I'd be really grateful for some direction.
https://stackoverflow.com/questions/62182194/stop-html-table-shunting-page-break-into-next-page-when-converted-to-pdf

**Comment by adamcunnington** [comment]
@liZe i'd be so grateful for any help here

**Comment by liZe** [comment]
Hi!

Your problem is caused by `table { break-inside: avoid-page }` that avoids page breaks inside tables. Removing it allows the table to be split.

[shopping-lists.pdf](https://github.com/Kozea/WeasyPrint/files/4756484/shopping-lists.pdf)

**Comment by adamcunnington** [comment]
Hi, that's what I had initially. It didn't remove the problem. My table
still breaks before it starts.

**Comment by liZe** [comment]
> Hi, that's what I had initially. It didn't remove the problem. My table still breaks before it starts.

:cry: 

I’ll need your HTML file to help you, because as you can see in the attached PDF file it-works-for-me™.

**Comment by adamcunnington** [comment]
Hey liZe, I can't see your attachment but the HTML is here:
https://github.com/adamcunnington/foodbank-southlondon/blob/master/backend/foodbank_southlondon/templates/shopping-lists.html

**Comment by adamcunnington** [comment]
Hi @liZe were you able to reproduce the issue?

The code I use to generate the PDFs is basically this:
`pages = []
for request in request_items:
    html = weasyprint.HTML(string=flask.render_template("shopping-list.html", request=request))
    document = html.render()
    pages.extend(document.pages)`

**Comment by adamcunnington** [comment]
@liZe please can you help with this? We are about to be forced to ditch weasyprint and use a different PDF generator because we can't get this working and it's blocking a charity project going live :(

**Comment by Tontyna** [comment]
@adamcunnington it's the floating image in the top right corner that moves the table onto the next page. That's probably a bug but there is a workaround.

Wrap your header lines in a clearfix like that:

```
<style>
.intro:after {
    display: block;
    content: "";
    clear: both;
} 
</style>
<body>
<div class="intro">
        <img src="{{ url_for('static', filename='logo.png', _external=True)}}">
        <h1>CLIENT SHOPPING LIST</h1>
        {% set postcode = request['postcode'] %}
        <h2>POSTCODE: {{ postcode }}</h2>
        <b>VOUCHER #:</b> {{ request['voucher_number'] }}
</div>
....
```

**Comment by adamcunnington** [comment]
Thank you so much!!
