### ISSUE TITLE
Pixbuf error: Error interpreting JPEG image file (Unsupported marker type 0xf7))

### ISSUE THREAD

**Issue by jesouhaite08** [Kozea/WeasyPrint#1136]
I'm receiving the following error when creating my PDF:

Failed to load image at "https://s3.amazonaws.com:443/inspector.bdzim.com/f595fec1-0bf6-4b11-826e-f18b509481a6.jpg" (Pixbuf error: Error interpreting JPEG image file (Unsupported marker type 0xf7))

Any ideas how to fix this? I see this [issue](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/64#note_829816) in gdf-pixbuf has been merged, but never released.

**Comment by liZe** [comment]
> Any ideas how to fix this? I see this [issue](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/64#note_829816) in gdf-pixbuf has been merged, but never released.

Unfortunately, I think that we’ll have to wait for the GDK-Pixbuf issue to be solved :unamused:.

If you want a quick&dirty fix and have some Python skills, you can hack [images.py](https://github.com/Kozea/WeasyPrint/blob/c443b9c9a61d82bd581c6f6aac7df746368c0073/weasyprint/images.py#L199) to transform your JPEG image into a PNG image, and give it to Cairo instead of using GDK-Pixbuf.

**Comment by AMontagu** [comment]
Here is a small snippet that is very ugly and time consuming but work:

```
from io import BytesIO
from PIL import Image
import requests

response = requests.get("picture_url")
im = Image.open(BytesIO(response.content))

# use this logging to be sure of your image format
# logging.info(im.format)

contents = response.content

# My tiff image are in JPEG format
if im.format == "JPEG":
    with BytesIO() as output:
        im.save(output, format="JPEG")
        contents = output.getvalue()
pdf_data["picture_data"] = (
    "data:"
    + response.headers["Content-Type"]
    + ";"
    + "base64,"
    + base64.b64encode(contents).decode("utf-8")
)
```

And in HTML:

```
{% if pdf_data.picture_data %}
  <img style="width: 200px; height: 150px" src="{{ pdf_data.picture_data }}" alt="">
{% endif %}
```

**Comment by liZe** [comment]
GDK-Pixbuf 2.42.0 has been released with a fix.

**Comment by AMontagu** [comment]
Thank for letting me know ! See you after the corona crisis !
