### ISSUE TITLE
OSError: [Errno cairo returned CAIRO_STATUS_WRITE_ERROR: b'error while writing to output stream'] 11

### ISSUE THREAD

**Issue by pierrevanrensburg** [Kozea/WeasyPrint#1138]
I get the following error when using django-weasyprint which uses Weasyprint under the hood.

Here is the traceback:

[2020-06-12 13:53:07 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7),
/usr/local/lib/python3.8/site-packages/weasyprint/fonts.py:229: UserWarning: FontConfig: No fonts configured. Expect ugly output.,
  warnings.warn(,
From callback for ffi.gc <cdata 'struct _cairo_pattern *' 0x5600e9883320>:,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/cairocffi/__init__.py", line 60, in __call__,
    self.func(*args, **kwargs),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 201, in handle_abort,
    sys.exit(1),
SystemExit: 1,
[2020-06-12 13:53:08 +0000] [167] [INFO] Booting worker with pid: 167,
[2020-06-12 13:53:43 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:167),
/usr/local/lib/python3.8/site-packages/weasyprint/fonts.py:229: UserWarning: FontConfig: No fonts configured. Expect ugly output.,
  warnings.warn(,
From callback for ffi.gc <cdata 'struct _cairo_pattern *' 0x5600e964e120>:,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/cairocffi/__init__.py", line 60, in __call__,
    self.func(*args, **kwargs),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 201, in handle_abort,
    sys.exit(1),
SystemExit: 1,
[2020-06-12 13:53:44 +0000] [244] [INFO] Booting worker with pid: 244,
[2020-06-12 13:54:19 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:244),
/usr/local/lib/python3.8/site-packages/weasyprint/fonts.py:229: UserWarning: FontConfig: No fonts configured. Expect ugly output.,
  warnings.warn(,
From cffi callback <function _make_write_func.<locals>.write_func at 0x7f034fa38ee0>:,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/cairocffi/surfaces.py", line 41, in write_func,
    @ffi.callback("cairo_write_func_t", error=constants.STATUS_WRITE_ERROR),
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 201, in handle_abort,
    sys.exit(1),
SystemExit: 1,
Internal Server Error: /pdf/orders-month/,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner,
    response = get_response(request),
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 217, in _get_response,
    response = self.process_exception_by_middleware(e, request),
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 215, in _get_response,
    response = response.render(),
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 107, in render,
    self.content = self.rendered_content,
  File "/usr/local/lib/python3.8/site-packages/django_weasyprint/views.py", line 102, in rendered_content,
    return document.write_pdf(),
  File "/usr/local/lib/python3.8/site-packages/weasyprint/document.py", line 634, in write_pdf,
    surface.show_page(),
  File "/usr/local/lib/python3.8/site-packages/cairocffi/surfaces.py", line 582, in show_page,
    self._check_status(),
  File "/usr/local/lib/python3.8/site-packages/cairocffi/surfaces.py", line 158, in _check_status,
    _check_status(cairo.cairo_surface_status(self._pointer)),
  File "/usr/local/lib/python3.8/site-packages/cairocffi/__init__.py", line 88, in _check_status,
    raise exception(message, status),
OSError: [Errno cairo returned CAIRO_STATUS_WRITE_ERROR: b'error while writing to output stream'] 11,

I am using python:3.8.1-alpine3.11

Here are bits of my install:

RUN apk add --no-cache         bash         cairo-dev         fontconfig         gcc         gdk-pixbuf-dev         jpeg-dev         libffi-dev         nodejs         nodejs-npm         musl-dev         pango-dev         postgresql-client         postgresql-dev         zlib-dev &&     wget 

Which results in the following installs:
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/113) Upgrading musl (1.1.24-r0 -> 1.1.24-r2)
(2/113) Upgrading libcrypto1.1 (1.1.1d-r3 -> 1.1.1g-r0)
(3/113) Upgrading libssl1.1 (1.1.1d-r3 -> 1.1.1g-r0)
(4/113) Installing bash (5.0.11-r1)
Executing bash-5.0.11-r1.post-install
(5/113) Installing libpng (1.6.37-r1)
(6/113) Installing freetype (2.10.1-r0)
(7/113) Installing fontconfig (2.13.1-r2)
(8/113) Installing pkgconf (1.6.3-r0)
(9/113) Installing expat-dev (2.2.9-r1)
(10/113) Installing zlib-dev (1.2.11-r3)
(11/113) Installing libpng-dev (1.6.37-r1)
(12/113) Installing freetype-dev (2.10.1-r0)
(13/113) Installing libblkid (2.34-r1)
(14/113) Installing libfdisk (2.34-r1)
(15/113) Installing libmount (2.34-r1)
(16/113) Installing libsmartcols (2.34-r1)
(17/113) Installing util-linux-dev (2.34-r1)
(18/113) Installing fontconfig-dev (2.13.1-r2)
(19/113) Installing libxau (1.0.9-r0)
(20/113) Installing libbsd (0.10.0-r0)
(21/113) Installing libxdmcp (1.1.3-r0)
(22/113) Installing libxcb (1.13.1-r0)
(23/113) Installing libx11 (1.6.9-r0)
(24/113) Installing libxrender (0.9.10-r3)
(25/113) Installing xorgproto (2019.2-r0)
(26/113) Installing libxau-dev (1.0.9-r0)
(27/113) Installing xcb-proto (1.13-r4)
(28/113) Installing libpthread-stubs (0.3-r5)
(29/113) Installing libxdmcp-dev (1.1.3-r0)
(30/113) Installing libxcb-dev (1.13.1-r0)
(31/113) Installing xtrans (1.4.0-r1)
(32/113) Installing libx11-dev (1.6.9-r0)
(33/113) Installing libxrender-dev (0.9.10-r3)
(34/113) Installing pixman (0.38.4-r0)
(35/113) Installing pixman-dev (0.38.4-r0)
(36/113) Installing util-macros (1.19.2-r1)
(37/113) Installing xcb-util (0.4.0-r1)
(38/113) Installing xcb-util-dev (0.4.0-r1)
(39/113) Installing libxext (1.3.4-r0)
(40/113) Installing libxext-dev (1.3.4-r0)
(41/113) Installing cairo (1.16.0-r2)
(42/113) Installing pcre (8.43-r0)
(43/113) Installing glib (2.62.6-r0)
(44/113) Installing cairo-tools (1.16.0-r2)
(45/113) Installing cairo-gobject (1.16.0-r2)
(46/113) Installing python3 (3.8.2-r0)
(47/113) Installing libgcc (9.2.0-r4)
(48/113) Installing libstdc++ (9.2.0-r4)
(49/113) Installing gettext-asprintf (0.20.1-r2)
(50/113) Installing libunistring (0.9.10-r0)
(51/113) Installing gettext-libs (0.20.1-r2)
(52/113) Installing libgomp (9.2.0-r4)
(53/113) Installing libxml2 (2.9.10-r3)
(54/113) Installing gettext (0.20.1-r2)
(55/113) Installing gettext-dev (0.20.1-r2)
(56/113) Installing bzip2-dev (1.0.8-r1)
(57/113) Installing libxml2-utils (2.9.10-r3)
(58/113) Installing libgpg-error (1.36-r2)
(59/113) Installing libgcrypt (1.8.5-r0)
(60/113) Installing libxslt (1.1.34-r0)
(61/113) Installing docbook-xml (4.5-r6)
Executing docbook-xml-4.5-r6.post-install
(62/113) Installing docbook-xsl (1.79.2-r2)
Executing docbook-xsl-1.79.2-r2.post-install
(63/113) Installing linux-headers (4.19.36-r0)
(64/113) Installing libffi-dev (3.2.1-r6)
(65/113) Installing libpcre16 (8.43-r0)
(66/113) Installing libpcre32 (8.43-r0)
(67/113) Installing libpcrecpp (8.43-r0)
(68/113) Installing pcre-dev (8.43-r0)
(69/113) Installing glib-dev (2.62.6-r0)
(70/113) Installing cairo-dev (1.16.0-r2)
(71/113) Installing binutils (2.33.1-r0)
(72/113) Installing gmp (6.1.2-r1)
(73/113) Installing isl (0.18-r0)
(74/113) Installing libatomic (9.2.0-r4)
(75/113) Installing mpfr4 (4.0.2-r1)
(76/113) Installing mpc1 (1.1.0-r1)
(77/113) Installing gcc (9.2.0-r4)
(78/113) Installing shared-mime-info (1.15-r0)
(79/113) Installing libjpeg-turbo (2.0.4-r0)
(80/113) Installing tiff (4.1.0-r0)
(81/113) Installing gdk-pixbuf (2.40.0-r0)
(82/113) Installing gdk-pixbuf-dev (2.40.0-r0)
(83/113) Installing libjpeg-turbo-dev (2.0.4-r0)
(84/113) Installing jpeg-dev (8-r6)
(85/113) Installing musl-dev (1.1.24-r2)
(86/113) Installing c-ares (1.15.0-r0)
(87/113) Installing nghttp2-libs (1.40.0-r1)
(88/113) Installing libuv (1.34.0-r0)
(89/113) Installing nodejs (12.15.0-r1)
(90/113) Installing npm (12.15.0-r1)
(91/113) Installing libxft (2.3.3-r0)
(92/113) Installing fribidi (1.0.8-r0)
(93/113) Installing graphite2 (1.3.13-r1)
(94/113) Installing harfbuzz (2.6.4-r0)
(95/113) Installing pango (1.44.7-r0)
(96/113) Installing fribidi-dev (1.0.8-r0)
(97/113) Installing icu-libs (64.2-r1)
(98/113) Installing harfbuzz-icu (2.6.4-r0)
(99/113) Installing graphite2-dev (1.3.13-r1)
(100/113) Installing icu (64.2-r1)
(101/113) Installing icu-dev (64.2-r1)
(102/113) Installing harfbuzz-dev (2.6.4-r0)
(103/113) Installing libxft-dev (2.3.3-r0)
(104/113) Installing pango-dev (1.44.7-r0)
(105/113) Installing libedit (20191211.3.1-r0)
(106/113) Installing db (5.3.28-r1)
(107/113) Installing libsasl (2.1.27-r5)
(108/113) Installing libldap (2.4.48-r2)
(109/113) Installing libpq (12.2-r0)
(110/113) Installing postgresql-client (12.2-r0)
(111/113) Installing openssl-dev (1.1.1g-r0)
(112/113) Installing postgresql-libs (12.2-r0)
(113/113) Installing postgresql-dev (12.2-r0)

...

Collecting CairoSVG>=2.4.0
  Downloading CairoSVG-2.4.2-py3-none-any.whl (50 kB)
Collecting tinycss2>=1.0.0
  Downloading tinycss2-1.0.2-py3-none-any.whl (61 kB)
Collecting cffi>=0.6
  Downloading cffi-1.14.0.tar.gz (463 kB)
Collecting Pyphen>=0.9.1
  Downloading Pyphen-0.9.5-py2.py3-none-any.whl (3.0 MB)
Collecting html5lib>=0.999999999
  Downloading html5lib-1.0.1-py2.py3-none-any.whl (117 kB)
Collecting cssselect2>=0.1
  Downloading cssselect2-0.3.0-py3-none-any.whl (31 kB)
Collecting cairocffi>=0.9.0
  Downloading cairocffi-1.1.0.tar.gz (68 kB)
Collecting defusedxml
  Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)

....

  Created wheel for cffi: filename=cffi-1.14.0-cp38-cp38-linux_x86_64.whl size=442568 sha256=cf29b5642dcb2b71571e3e165fa33dec1832eac077c78c616a1cef93847fd2d1
  Stored in directory: /tmp/pip-ephem-wheel-cache-7l7hkxev/wheels/89/96/42/98fbfabb3fd5a7ea40a01dab70dcbdf5d78e4652b30dbf9f33
  Building wheel for cairocffi (setup.py): started
  Building wheel for cairocffi (setup.py): finished with status 'done'
  Created wheel for cairocffi: filename=cairocffi-1.1.0-py3-none-any.whl size=88588 sha256=d52737d95150a651586081696526100d48e1e03d37fb5bd8508a047a45a1238a
  Stored in directory: /tmp/pip-ephem-wheel-cache-7l7hkxev/wheels/71/c7/16/0cd3bf6e08dae3bd2edeb3e731447c4864559f55bc1a15f7e1
  Building wheel for MarkupSafe (setup.py): started
  Building wheel for MarkupSafe (setup.py): finished with status 'done'
  Created wheel for MarkupSafe: filename=MarkupSafe-1.1.1-cp38-cp38-linux_x86_64.whl size=32123 sha256=abfcbb01f978f43ec6495f35cc3ab7c57b7d57b20b3f65e976e5bd6f765df3cb
  Stored in directory: /tmp/pip-ephem-wheel-cache-7l7hkxev/wheels/0c/61/d6/4db4f4c28254856e82305fdb1f752ed7f8482e54c384d8cb0e
Successfully built psycopg2 anyjson django-allauth django-minio-storage validate-email Pillow gevent splinter parse django-ckeditor django-autocomplete-light openapi-codec simplejson cryptography greenlet coreschema cffi cairocffi MarkupSafe
ERROR: django-weasyprint 0.6.0 has requirement Django>=2.2; python_version >= "3.6", but you'll have django 1.11.29 which is incompatible.
Installing collected packages: pytz, Django, psycopg2, anyjson, djangorestframework, django-filter, PyJWT, djangorestframework-jwt, uritemplate, itypes, MarkupSafe, jinja2, coreschema, idna, chardet, urllib3, certifi, requests, coreapi, openapi-codec, simplejson, django-rest-swagger, webencodings, tinycss2, pycparser, cffi, cairocffi, defusedxml, cssselect2, Pillow, CairoSVG, Pyphen, html5lib, WeasyPrint, django-weasyprint, python3-openid, oauthlib, requests-oauthlib, django-allauth, django-countries, django-appconf, billiard, vine, amqp, kombu, celery, django-celery-email, minio, django-minio-storage, cryptography, PyOpenSSL, josepy, mozilla-django-oidc, whitenoise, flatdict, validate-email, nameparser, phonenumbers, python-memcached, gunicorn, greenlet, gevent, sentry-sdk, selenium, splinter, parse, django-webpack-loader, django-js-asset, django-ckeditor, ptvsd, django-bootstrap-daterangepicker, django-autocomplete-light
Successfully installed CairoSVG-2.4.2 Django-1.11.29 MarkupSafe-1.1.1 Pillow-7.0.0 PyJWT-1.7.1 PyOpenSSL-19.1.0 Pyphen-0.9.5 WeasyPrint-51 amqp-2.6.0 anyjson-0.3.3 billiard-3.6.3.0 cairocffi-1.1.0 celery-4.4.0 certifi-2020.4.5.2 cffi-1.14.0 chardet-3.0.4 coreapi-2.3.3 coreschema-0.0.4 cryptography-2.9.2 cssselect2-0.3.0 defusedxml-0.6.0 django-allauth-0.40.0 django-appconf-1.0.4 django-autocomplete-light-3.5.1 django-bootstrap-daterangepicker-1.0.4 django-celery-email-2.0.0 django-ckeditor-5.3.1 django-countries-5.5 django-filter-2.2.0 django-js-asset-1.2.2 django-minio-storage-0.3.5 django-rest-swagger-2.2.0 django-weasyprint-0.6.0 django-webpack-loader-0.6.0 djangorestframework-3.11.0 djangorestframework-jwt-1.11.0 flatdict-3.4.0 gevent-1.4.0 greenlet-0.4.16 gunicorn-20.0.4 html5lib-1.0.1 idna-2.8 itypes-1.2.0 jinja2-2.11.2 josepy-1.3.0 kombu-4.6.10 minio-5.0.6 mozilla-django-oidc-1.2.3 nameparser-1.0.5 oauthlib-3.1.0 openapi-codec-1.3.2 parse-1.12.1 phonenumbers-8.11.2 psycopg2-2.8.3 ptvsd-4.3.2 pycparser-2.20 python-memcached-1.59 python3-openid-3.1.0 pytz-2020.1 requests-2.22.0 requests-oauthlib-1.3.0 selenium-3.141.0 sentry-sdk-0.14.1 simplejson-3.17.0 splinter-0.13.0 tinycss2-1.0.2 uritemplate-3.0.1 urllib3-1.25.9 validate-email-1.3 vine-1.3.0 webencodings-0.5.1 whitenoise-5.0.1

...

Requirement already satisfied: CairoSVG>=2.4.0 in /usr/local/lib/python3.8/site-packages (from WeasyPrint>=43; python_version >= "3.6"->django-weasyprint==0.6.0->cup==0.0.1) (2.4.2)
Requirement already satisfied: cairocffi>=0.9.0 in /usr/local/lib/python3.8/site-packages (from WeasyPrint>=43; python_version >= "3.6"->django-weasyprint==0.6.0->cup==0.0.1) (1.1.0)

NOTE:  Everything works fine on my local host and on the QA cluster, but not on the production cluster... :-(  All versions are the same for QA and production...

**Comment by liZe** [comment]
Hi!

Your problem probably comes from `UserWarning: FontConfig: No fonts configured. Expect ugly output`. You can try to install fonts ([Liberation](font-liberation-nerd) is a good default choice).

**Comment by pierrevanrensburg** [comment]
Hello Guillaume,

Thank you so much for your response.

I get the same warning about font config on my local host and on QA and on
production, yet on local host and QA (which are built in the same way as
production using Docker containers) I do not get the error mentioned in the
subject line...

I could not find how to configure the font config anyway so would
appreciate any pointers please.

Thanks again,
Pierre

**Comment by liZe** [comment]
If you get the problem with fonts installed, then there’s probably a real problem while writing the PDF file. You can check that the user used to launch your Django app has the right to write where you want to generate the document.

> NOTE: Everything works fine on my local host and on the QA cluster, but not on the production cluster... :-( All versions are the same for QA and production...

There **must** be a difference between your two configurations, and without this difference it’s hard to find the source of your problem :cry:… Any ideas?

**Comment by pierrevanrensburg** [comment]
Hello Guillaume,

Thank you again for your response.

Just to say I will attempt check in the morning. Do you know where
Weasyprint or Django-Weasyprint does the actual pdf creation? I don't know
where to check the user rights on system...

I will also try to find out the differences in production vs qa and revert
back to you.

Thanks again,
Pierre

**Comment by liZe** [comment]
@pierrevanrensburg Did you find a way to solve your problem?
