### ISSUE TITLE
How to create index list?

### ISSUE THREAD

**Issue by oussama-he** [Kozea/WeasyPrint#1139]
I would like to create a pdf from HTML and I want the pdf result to have an index list or index table like in the picture below:

![Screenshot at 2020-06-13 11-33-03](https://user-images.githubusercontent.com/18425315/84566563-23623a00-ad6a-11ea-9301-be12dc329056.png)

How can I do this using the weasyprint lib.

**Comment by liZe** [comment]
Hello!

You’ll find different solutions in #23, or you can take a look at the [report sample](https://weasyprint.org/samples/).

**Comment by Tontyna** [comment]
@oussama-he, if you just want an outline in your PDF there is no need to do anything at all -- it is generated automatically, containing the headings of your document.

**Comment by liZe** [comment]
> @oussama-he, if you just want an outline in your PDF there is no need to do anything at all -- it is generated automatically, containing the headings of your document.

Of course, @Tontyna is right. If you want to have bookmarks in your PDF reader, like in your screenshot, it’s automatically done by WeasyPrint with `h1` to `h6` tags, or manually with the [`bookmark-*` properties](https://www.w3.org/TR/css-content-3/#bookmark-generation).
