### ISSUE TITLE
Mix portrait and landscape - any progress?

### ISSUE THREAD

**Issue by bjornasm** [Kozea/WeasyPrint#1142]
In [this](https://github.com/Kozea/WeasyPrint/issues/108) issue a possibility to combine portrait and landscape was requested. I can't see if there has been any progress here, as there isn't anything I can find in the documentation. The reason this is needed is to accommodate for big tables. There is a proposed solution to combine different pdf's (one with vertical and one with horizontal), but this will require hacking and will destroy the table of contents and page numbering.

One 'hack' could be to first make that table as a picture, and insert it in portrait mode, however as many pdf's are read on the computer so the best way would be a way to align the pages vertically.

**Comment by Tontyna** [comment]
No hacking required, just *named pages*

```html
<style>
  @page portrait { size: A4; }
  @page landscape { size: A4 landscape; }
</style>
<div style="page:portrait">
  Portait of Lore ispum
</div>
<div style="page:landscape">
  Lore in a scape
</div>
```

**Comment by bjornasm** [comment]
Thank you for your swift reply.

**Comment by ckcollab** [comment]
@Tontyna thank you very much!
