### ISSUE TITLE
Is it possible to reset the page counter in the middle of a document?

### ISSUE THREAD

**Issue by arikrupnik** [Kozea/WeasyPrint#1143]
I can use `@page:first` to set the page counter to an arbitrary number. I can use the same rule to suppress printing the page number on the first page. This works for a title page, and the page count starts at `1` at the beginning of text.

          @page:first {
              counter-reset: page 0;
              @top-right {
                  content: "";
              }
          }

Is there a way to reset the page counter in the middle of the document? Here's a use case: a preface and the main content. Preface wants Roman page page numbers from `i`. Once I get to the main content, the page counter wants to reset to `1`. I'm OK if the preface has no page numbers at all, and page numbers simply start at `1` at the beginning of main content.

**Comment by Tontyna** [comment]
AFAIK appropriately positioned `named pages` is the only way to achieve this.

A simple frontmatter/mainmatter example could look like this:

```html
<html>
  <style>
    @page
    { 
      @bottom-center {
        content: 'Page: ' counter(page);
      }
    }
    @page frontmatter 
    { 
      @bottom-center {
        content: 'Page: ' counter(page, lower-roman);
      }
    }
    @page resetpagecounter
    { 
      counter-reset: page 1;
    }
  </style>
  <body>
    <div style="page:frontmatter">
      <div>
        Frontmatter page i
      </div>
      <div style="break-before: always">
        Frontmatter page ii
      </div>
    </div>
      
    <!-- reset page counter with empty div -->
    <div style="page:resetpagecounter"></div>
      
    <div>
      page 1
    </div>
    <div style="break-before: always">
      page 2
    </div>
  </body>
</html>
```

Of course, the actual css depends on the actual document's structure. 
https://github.com/Kozea/WeasyPrint/pull/631#issuecomment-390407469 shows how to reset the counter in harmony with (chapter) headings.

**Comment by arikrupnik** [comment]
This is brilliant! Thank you @Tontyna .This does exactly what I'm looking for. Plus, I got to read about named pages, which is a new concept to me. Thank you.
