### ISSUE TITLE
Weasyprint CLI verbosity is on by default with no disabling option

### ISSUE THREAD

**Issue by oliverbenns** [Kozea/WeasyPrint#1149]
The cli currently has verbosity enabled by default with no way of disabling. This is particularly an issue when relying on stdout as the verbosity is included:

in:
```
weasyprint - - -f pdf <<< "<html><head></head><body><a href="#">abcdef</a></body></html>"
```

out:
```
ERROR: No anchor # for internal URI reference
%PDF-1.5
%���
4 0 obj
...
```

The argument in the docs is for enabling verbosity. Which of course if this issue is correct, doesn't do much
```
-v, --verbose
```
> Show warnings and information messages.

**Comment by liZe** [comment]
Hello!

> The argument in the docs is for enabling verbosity. Which of course if this issue is correct, doesn't do much

You’re looking for the `--quiet` option. It’s not in the documentation (my bad), but it’s in the `--help` message.

If it’s OK for you, I’ll close this issue with a commit adding the missing documentation.
