### ISSUE TITLE
Suppress margins at page breaks

### ISSUE THREAD

**Issue by stephenstubbs** [Kozea/WeasyPrint#115]
When there is a (page) break between blocks, the (collapsed) margin at this point should be ignored. In particular, the content on the next page should start at the top of the page, ignoring any `margin-top` value.

Originally reported as:

---

`@page` inconsistent margin-top

I'm using version 0.19.2

If I set the following:

```
    @page {
        margin-top: 4cm;
    }
```

Then I create a document with 5 pages in my example.

I have inconsistent margins. All the odd pages seem to have the same top and bottom margins and all the even pages seem to have the same top and bottom margins but they are different from each other. I don't know if I'm doing something wrong or if this is a bug.

**Comment by liZe** [comment]
This bug is also reported in [the test suite](http://test.weasyprint.org/suite-css21/chapter13/section6/test41/).

**Comment by liZe** [comment]
See [the spec](https://www.w3.org/TR/css-break-3/#break-margins).

**Comment by SimonSapin** [comment]
The draft for the next level introduces a relevant property: https://drafts.csswg.org/css-break-4/#break-margins

**Comment by liZe** [comment]
> The draft for the next level introduces a relevant property: https://drafts.csswg.org/css-break-4/#break-margins

Thank you! Handling `margin-break` shouldn't be much more complicated that fixing this bug.
