### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pepa65** [Kozea/WeasyPrint#1150]
I always build like: `python3 setup.py build` but when I do that on 2b1490e492db3ac1da33cbd406ae276472ae1d2c it fails with: 
```
running build
running build_py
package init file 'weasyprint/formatting_structure/__init__.py' not found (or not a regular file)
```

**Comment by liZe** [comment]
Hello, thanks for this issue!

I have the same message, but it’s a warning, not an error for me. The `__init__.py` is not mandatory for modules nowadays, there’s no need to have one.

**Comment by pepa65** [comment]
I couldn't tell whether it was a error or warning, the full output is:
```
running build
running build_py
package init file 'weasyprint/formatting_structure/__init__.py' not found (or not a regular file)
```
I'll ignore that then..!
