### ISSUE TITLE
Installing GTK

### ISSUE THREAD

**Issue by tillfurger** [Kozea/WeasyPrint#1151]
Hi everyone

I'm really sorry to bother with such a basic question. I am working in a virtual environment. I have weasyprint installed and also followed the instructions concering the GTK installation. Not having set the PATH, I have the `no library called "cairo" was found` error as described in the manual. Setting the PATH:

`SET PROPER_GTK_FOLDER=C:\Users\Name\msys2\mingw64\bin
SET PATH=%PROPER_GTK_FOLDER%;%PATH%`

I suddely don't have weasyprint anymore (`C:\Users\Name\msys2\mingw64\bin\python.exe: No module named weasyprint`) but it does have the cairo stuff (`WHERE libcairo-2.dll -- >C:\Users\Name\msys2\mingw64\bin\libcairo-2.dll`). So my environment with all my packages is at a different location as the msys2\mingw64\bin stuff and setting the PATH gets me into this folder, where weasyprint and all my other packages are not present anymore. How do I have to proceed to get weasyprint working in my old environment?

My venv is here: C:\Users\Name\PycharmProjects\tool\venv
And the GTK stuff: C:\Users\Name\msys2\mingw64\bin

Thank you so much

**Comment by Tontyna** [comment]
Problem is: There isn't only the required GTK in your msys2, but also a Python -- `C:\Users\Name\msys2\mingw64\bin\python.exe` -- of course without WeasyPrint stuff.

I don't know your actually command to execute WeasyPrint, but it should definitely be run by the Python executable from your *old* environment.

If you created your environment via `venv` and pip-installed Weasyprint, then there should be a `weasyprint.exe` in the environment folder that automagically finds the right Python.

I recall that on Windows `venv` copies the executables into the `Scripts` folder.
So those command shouldn't fail:

```
C:\Users\Name\PycharmProjects\tool\venv\Scripts\python -m weasyprint --version
C:\Users\Name\PycharmProjects\tool\venv\Scripts\weasyprint --version
```

**Comment by Tontyna** [comment]
If you get tired of typing the full-path-to-the-right-python.exe you can of course insert it **in front of** the `PROPER_GTK_FOLDER` into your PATH

**Comment by liZe** [comment]
@tillfurger Can we do anything else for you?
