### ISSUE TITLE
Push layer to bottom of page but preventing content overlapping (invoice sample)

### ISSUE THREAD

**Issue by manelio** [Kozea/WeasyPrint#1159]
In the invoice sample, the totals table is absolutelly positioned and pushed to bottom with bottom: 0.

If there are more rows, the totals table is overlapping and hiding the table rows.

Is there any way to keep the totals stuck to the bottom of page but preventing the table overlapping?

I attach files with the result for 4 rows (ok), 11 rows (wrong) and 12 rows (ok).

I think is a very common use case the generation of tabular documents ending with some sort of summary.

### 4 rows (ok)

![4 rows](https://user-images.githubusercontent.com/2852852/87082589-87720400-c22b-11ea-8973-4cb584940be3.png)

### 11 rows (wrong)

![11 rows](https://user-images.githubusercontent.com/2852852/87082585-86d96d80-c22b-11ea-939a-ee6e4e863c32.png)

### 12 rows (ok)

![12 rows](https://user-images.githubusercontent.com/2852852/87082581-8640d700-c22b-11ea-92ad-a6c07829a10f.png)

**Comment by manelio** [comment]
I think this is an awesome tool, so I'm going to try to fix this bug or find some workaround (spacer/filler concept?). This is the only lack to have a perfect commercial documents engine (invoices, delivery notes, ...).

But when it comes at this project source code I start from scratch. If anyone can provide some direction or advice, would be great.

Anyway, keep the great work!

**Comment by liZe** [comment]
Hello!

When the size of the footer is fixed (it is here), you can add a bottom padding (that equals to the footer’s height) to the main container. We should actually have this in the sample!

**Comment by liZe** [comment]
(And I don’t know why I didn’t see this issue earlier, sorry for the delay.)

**Comment by liZe** [comment]
I’ve tried to find a clean way to solve this, but the problem is more logical than technical in my opinion: the bottom ribbon is so large than there’s no way to get a clean rendering in all cases.

But for the sake of finding a solution to this problem, I’ve updated the template to avoid the content to overlap. It works quite well when the height of the absolute element is fixed (even if the result is far from perfect visually, but that’s another problem.)

**Comment by ysennoun** [comment]
@liZe thnak you, I just tested it and it worked fine ;) !
Actually I found another workaround but les elegant than yours, I added a tfoot with fake rows to the items table and made all elements transparents. The height of the fake lines should be equal or greater than the height of the total table.
