### ISSUE TITLE
Jinja2 with WeasyPrint is too Slow

### ISSUE THREAD

**Issue by AliShahbazzz** [Kozea/WeasyPrint#1161]
I am creating a "Resume Builder" website using React and Django. React sends the resume data as json to django, where the pdf is generated. I am using WeasyPrint to generate pdfs and Jinja2 to insert data into the template. Jinja code includes few logical statements (I tried my best to use the least) and it contains little heavy CSS too. The time to generate a single page template is around 14-20 seconds and 20-30 seconds for a two page template. I tried to remove the CSS and kept only the HTML and data, the pdf was generated in a second or two then I removed the data and kept only the HTML and CSS and the pdf was generated in 5-10 seconds. Is there any solution to generate pdf in less than 5 seconds? 

Thank You in advance.

**Comment by DimaBogdan-phie** [comment]
I use Jinja2 too and I sure that there's no any relations between Jinja2 and WeasyPrint. Jinja returns html file and WasyPrint operates only with this file. Of course some render operations in WeasyPrint heavier than others and if you want to make it faster you need to find this operations and optimize your html+css

**Comment by AliShahbazzz** [comment]
@DimaBogdan-phie  Thank you for the reply. Yes, you are right, there's no relation between Jinja2 and WeasyPrint. Actually I figured it out after asking the question. My bad. Could you please suggest me some tips and tricks to optimize my HTML and CSS.
Thank You.
