### ISSUE TITLE
Support for macOS 10.14.x Mojave?

### ISSUE THREAD

**Issue by baszero** [Kozea/WeasyPrint#1164]
By when will Mojave be supported?
![image](https://user-images.githubusercontent.com/596855/87689242-45474600-c788-11ea-884c-830b99c55d07.png)

**Comment by liZe** [comment]
Hello!

I didn’t know that macOS Mojave wasn’t supported. What’s wrong?

**Comment by baszero** [comment]
No updates here? I want to know whether there is any plan to make it available for 10.14 and 10.15

**Comment by liZe** [comment]
> No updates here? I want to know whether there is any plan to make it available for 10.14 and 10.15

Please, tell me why you can’t install WeasyPrint on 10.14 and 10.15, so that I can fix your problem.

**Comment by baszero** [comment]
I got these errors:
![image](https://user-images.githubusercontent.com/596855/89028805-561dbd00-d32d-11ea-9b3e-1d14c608cce6.png)

and then this:
![image](https://user-images.githubusercontent.com/596855/89028961-a6951a80-d32d-11ea-9694-be86461a77f3.png)

As I need MacPorts, uninstalling that is not an option for me.

**Comment by liZe** [comment]
The first "error" is a warning. It’s probably displayed because your version of brew is old. You can update your version of brew, it may even fix your second error.

**Comment by liZe** [comment]
> You can update your version of brew, it may even fix your second error.

@baszero Did it fix your problem?

**Comment by baszero** [comment]
@liZe YES!
