### ISSUE TITLE
Better style should be added for inputs

### ISSUE THREAD

**Issue by Ksengine** [Kozea/WeasyPrint#1173]
![image](https://user-images.githubusercontent.com/63494497/88359171-3270da80-cd61-11ea-90a5-487f4f35be8a.png)

google looks like this

**Comment by liZe** [comment]
Hello!

> google looks like this

I’m surprised to see that a page that’s not at all designed for print is rendered pretty well :smile:.

Improving the style of inputs in the default CSS should be more than enough to get correct renderings.

There’s also a pull request (#1018) about including real form fields in PDF files. We have to use something different from Cairo for that.

**Comment by kakksanthusa** [comment]
No need to show blinking cursor
Only a box like input element  is better
I had changed user stylesheet using chrome user style sheet
And added default css showed by ch3devtools.
But i had same result
result
