### ISSUE TITLE
URL convert # sign to %23

### ISSUE THREAD

**Issue by speakASAP** [Kozea/WeasyPrint#1176]
I have issue with converting `#` within URL:
Example:
`<a href="https://speakasap.com/ru/cz/seven/1/#exercises">Try it</a>`

weasyprint generates wrong link:
https://speakasap.com/ru/cz/seven/1/%23exercises
instead of
https://speakasap.com/ru/cz/seven/1/#exercises

Means sign `#` is converted by weasyprint to `%23`

There is only manual workaround: https://community.adobe.com/t5/acrobat/ist-replaced-by-23-in-urls-gt-error-404/td-p/5811448?page=1 (if weasyprint uses some Adobe API?)

_Originally posted by @speakASAP in https://github.com/Kozea/WeasyPrint/issues/1121#issuecomment-665544600_

**Comment by liZe** [comment]
Thanks for the separate issue.

Could you please explain how you get the wrong URL? Putting your sample in an HTML file and using WeasyPrint’s command-line interface gives me the right URL.

**Comment by speakASAP** [comment]
I am not experienced in WeasyPrint command line, sorry.

I use this python script:
```
  template = get_template('site/seven/pdf.html')
            context = {
                'lesson': lesson,
                'course': lesson.course,
                'language': lesson.course.language,
                'template': lesson.get_template(),
                'render_type': 'pdf',
            }
            html = template.render(context)
            HTML(string=html, base_url="https://speakasap.com", media_type='all').render().write_pdf(path)
```
And I just realised I have this line in the requirements:
WeasyPrint==0.30

Seems it is an old version.

**Comment by liZe** [comment]
You can try this code:

```python
HTML(string='<a href="https://speakasap.com/ru/cz/seven/1/#exercises">Try it</a>').render().write_pdf(path)
```

If it gives you the right URL (as it does for me, even with WeasyPrint 0.30), it means that the URL is escaped elsewhere (probably in Jinja2, if that’s where your `get_template` function comes from).

**Comment by speakASAP** [comment]
I replaced my code with yours.
Here is output:
`https://speakasap.com/ru/cz/seven/1/%23exercises`
[lesson1.pdf](https://github.com/Kozea/WeasyPrint/files/5006324/lesson1.pdf)

**Comment by liZe** [comment]
There’s a `#` in your PDF file, not `%23`. Try `grep -a exercise lesson1.pdf`.

**Comment by Tontyna** [comment]
I suppose the problem isn't a missing `#` in the PDF at all, but how your PDF Viewer handles that URL. Probably your Viewer tries to be smart and helpful :smirk:

**Comment by speakASAP** [comment]
I see now. Thanks for help!

I use Apple Preview Version 11.0 (999.4) for opening PDF.
Also I tried Safari Version 13.1.1 (15609.2.9.1.2)
Google Chrome opened it correctly.

Seems it is an issue with Apple but not with the WeasyPrint...

Many thanks guys!

**Comment by liZe** [comment]
You’re not the only one: https://discussions.apple.com/thread/251041261
