### ISSUE TITLE
Grid of pictures with picture text, without page-break in the middle of element (Help - not bug)

### ISSUE THREAD

**Issue by bjornasm** [Kozea/WeasyPrint#1177]
Sorry if this has been answered, I've researched and have yet to find any good answers. 

I use the report sample out of the box, and want to have a 3x3 grid (2x3 grid in the first page as there is a heading there), however I find it hard to keep the section with picture and picture text from breaking and random. 

This is my code, on the standard Reports.html/pdf css code:

```
<body>
    <article id="offers">
      <h2 id="offers-title">Attachment 5: Pictures</h2>
      <section>
        <img src="S01.JPG" style="height: 300px;"></img>
        <ul>
          <li>Picturetext</li>
          <li>Subject: Ant</li>
          <li>Location: Woods</li>
          <li>Taken by: Bob</li>
        </ul>
      </section>
     ......
      x 24 at least


```

Preferrably these would come out in something like this (x is picture y is picture text, ----- denotes new page):

```
 Heading 
x  x  x
y  y  y
x  x  x
y  y  y

--------

x  x  x
y  y  y
x  x  x
y  y  y
x  x  x
y  y  y

---------

```
What happens:

```
 Heading 
x  x  x
y  y  y
x  x  x
y  y  y
x
---------
y  x  x
   y  y
x
```

I've also tried to experiment with picture height etc, but preferrably I could just throw in a page break or to define that a element should not be broken. I have also tried:
```
    html body article#offers section {
    break-before: always;
    page-break-before: always;}
```

**Comment by liZe** [comment]
Hello!

You could try to use something like:

```css
article { display: flex; flex-wrap: wrap }
h2 { width: 100% }
section { width: 33.3% }
```

**Comment by liZe** [comment]
Feel free to reopen if needed.
