### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by lisperatu** [Kozea/WeasyPrint#1179]
In badly formated html tables, ones which give warnings like:
`WARNING: This table row has more columns than the table, ignored 1 cells:`

At one-moment rendering crashes.

In:
`weasyprint/layout/preferred.py", line 386, in table_and_columns_preferred_widths`
`grid[row_number][cell.grid_x] = cell`

IndexError: list assignment index out of range

Just to ignore such cases, in my current setup I added:

```
    for cell in row.children:
    try:
        grid[row_number][cell.grid_x] = cell
    except IndexError:
        continue
```

I'm not sure that this is the right approach for such cases as a general solution. However, for me, it's a hack to have current environment working.

**Comment by liZe** [comment]
Hello!

Could you please provide a sample showing the problem?

**Comment by lisperatu** [comment]
Give me a day or two to prepare an example. The existing ones contain sensitive data and they are huge.

**Comment by liZe** [comment]
@lisperatu Can I close this issue?
