### ISSUE TITLE
list-style-type: square cannot be displayed

### ISSUE THREAD

**Issue by EugenMayer** [Kozea/WeasyPrint#1182]
Referring to an older issue #318 

We are using 

```css
font-family:  Helvetica, Arial, sans-serif;
```

and `list-style-type: square` is not shown (garbage as you have shown). We are using an alpine:latest container with 

```
apk --no-cache add msttcorefonts-installer fontconfig 
update-ms-fonts
fc-cache
```

reproduceable for weasy using

```bash
FROM alpine:latest

RUN apk --update --upgrade add supervisor cairo pango gdk-pixbuf py3-cffi py3-pillow py-lxml py3-pip \
 && apk --no-cache add msttcorefonts-installer fontconfig \
 && apk --no-cache add ca-certificates dpkg bash curl su-exec \
 && update-ms-fonts \
 && fc-cache
```

We also tried with `Roboto` and `Liberation Sans`

Liberation
```
RUN apk --update add ttf-liberation
```

Roboto

```shell
RUN wget https://github.com/google/fonts/archive/master.tar.gz -O gf.tar.gz \
 && tar -xf gf.tar.gz \
 && mkdir -p /usr/share/fonts/truetype/google-fonts \
 && find $PWD/fonts-master/ -name "*.ttf" -exec install -m644 {} /usr/share/fonts/truetype/google-fonts/ \; || return 1 \
 && rm -f gf.tar.gz \
 && fc-cache -f && rm -rf /var/cache/*
```

**Comment by liZe** [comment]
Hello, and thank you for your bug report.

As far as I can tell, Arial, Liberation and Roboto don’t have the ◾ character, that’s why you don’t have the character displayed. You’ll probably have the square if you install a font that includes the character, such as DejaVu (and hope that FontConfig is correctly configured, but I think it is, even on Alpine).

**Comment by liZe** [comment]
Feel free to reopen if you think that the problem comes from elsewhere.

**Comment by mikevoets** [comment]
Can we reopen this? This issue came up in our today's regression tests and seems to be related to some recent changes in Weasyprint. We updated Weasyprint to the latest on master from Weasyprint 5.1 a week ago, but didn't change our fonts between today and the previous regression tests, so that would rule out a problem with fonts.

**Comment by EugenMayer** [comment]
Just in case this makes any difference - we gave up on this and restyled the lists in the print to never use square. We tries several fonts and ended up using this workaround.

**Comment by liZe** [comment]
Thanks for your comments.

@EugenMayer Is it possible for both of you to install the [Noto-Emoji font](https://pkgs.alpinelinux.org/packages?name=font-noto-emoji&branch=edge)?

@mikevoets The character used for the square changed with #1017, that why the bug could come from a missing character even if the installed fonts didn’t change. Could you please install [NotoEmoji-Regular.ttf](https://github.com/googlefonts/noto-emoji/tree/master/fonts) and confirm that it fixes your bug?

Looks like the character used for this square is not included in common fonts. The one used previously was at least included in Liberation, Arial, Times New… We should get back to the old square.

**Comment by liZe** [comment]
> Looks like the character used for this square is not included in common fonts. The one used previously was at least included in Liberation, Arial, Times New… We should get back to the old square.

I changed the character because [the specification™](https://www.w3.org/TR/css-counter-styles-3/#simple-symbolic) proposes something "similar to U+25FE BLACK MEDIUM SMALL SQUARE". I suppose that the old and widely available "U+25AA BLACK SMALL SQUARE" is similar enough :wink:. Let’s revert this change.

**Comment by liZe** [comment]
You can now try the latest `master` branch or install NotoEmoji (or DejaVu), everything should be back to normal.

Please let me know if the problem is not fixed for you.

**Comment by EugenMayer** [comment]
I try this out ASAP and report back, thank you @liZe for taking such a quick action on this

**Comment by mikevoets** [comment]
@liZe I have tried it out and I confirm it is back to normal. Thanks so much for the expedience!
