### ISSUE TITLE
Add whitespace below top margin

### ISSUE THREAD

**Issue by matanper** [Kozea/WeasyPrint#1184]
I'm using the properties below to show info in the top margin, and I have a long table extends over a page, and in the second page of the table the top row is adjacent to the top margin without any whitespace between them. I tried to use different margin/padding/widows properties but couldn't make it work.

```
@page {
  @top-left {
    content: counter(page);
    text-align: center;
  }

  @top-center {
    content: string(heading);
    font-size: 9pt;
    height: 1cm;
  }
}
```

**Comment by liZe** [comment]
You can vertically align the text of a page margin using the `vertical-align` property. Using the `height` property on a page margin will probably hurt you more than it will solve your problems :wink:.

**Comment by matanper** [comment]
@liZe Thank you for the advice. Is it possible to do also with background (like in [report example](https://github.com/Kozea/WeasyPrint/blob/gh-pages/samples/report/report.css))?

**Comment by liZe** [comment]
> @liZe Thank you for the advice. Is it possible to do also with background (like in [report example](https://github.com/Kozea/WeasyPrint/blob/gh-pages/samples/report/report.css))?

I don’t understand what you want :/.

**Comment by matanper** [comment]
`vertical-alignment` works only on the content so when I added background with color it didn't affect it, but after some search I found `background-position` for that.   
thanks
