### ISSUE TITLE
Recommended grid system?

### ISSUE THREAD

**Issue by ckristhoff** [Kozea/WeasyPrint#1186]
Hello

I recently crashed to #36 issue 😞 

So I'm going to change all layout from tables to divs (apparently it works well). So, What's the recommended grid system ? flex, grid layout? Flex works well apparently, grid layout does not.

**Comment by liZe** [comment]
Hello!

Flex works for simple cases, and grid is not implemented at all, so… The choice is pretty obvious :wink:.

Unfortunately, if your goal is to avoid #36, using flex or any other layout won’t help you. WeasyPrint can’t split multiple sibling boxes between pages, even without tables :unamused:.

**Comment by ckristhoff** [comment]
😢 that's bad news for me. I'll still keep trying.
Thank you
