### ISSUE TITLE
Progress reporting - output to standard output?

### ISSUE THREAD

**Issue by JohannesMunk** [Kozea/WeasyPrint#1187]
Dear weasyPrint team!

I am looking for a way to get some indication of progress during the weasyPrint conversion. Disclaimer: It does not have to be overly precise.

Idea: Our host-programm could happily read and parse from weasyPrints std::cout special messages like "Stage: 2/3: <html processing> progress: 67% - 13566/20000" or so.

Could you give me a recommendation where you would put such an output in the weasyPrint process?

Thanks a lot in advance!

Johannes

**Comment by liZe** [comment]
Hello Johannes,

Good news, these messages already exist: there’s a [`weasyprint.progress`](https://weasyprint.readthedocs.io/en/stable/tutorial.html#logging) logger for you. You can see these messages using the `--verbose` CLI option, and you can configure this logger to only get these messages redirected to your program. It’s not precise, and it can’t be: we don’t even know the number of pages before the layout. But it should be useful for your needs!

**Comment by JohannesMunk** [comment]
Hey liZe! 

aah, nice. It will serve my purpose. Although it does not give an indication on how large the overall process is - as you said, you dont know the number of pages before the layout. But I guess the users will know roughly..

Just as an idea: The length of the already processed html might be an alternate way of reporting progress. And assuming that the time per input html element/code is more constant than the time per page with unknown/different complexity, it would probably also be more stable. But of course only useful for a progress bar, not direct user output/feedback.

Thank you!

**Comment by Tontyna** [comment]
Counting the input elements won't help at all when target-counters and target-strings require  (an unpredictable number of) repagination cycles.

**Comment by liZe** [comment]
> Counting the input elements won't help at all when target-counters and target-strings require (an unpredictable number of) repagination cycles.

True. And that’s not the only point.

As HTML is a tree, it’s suprisingly hard to count the number of rendered and not rendered tags (breaking an element at level N means that you only have rendered a ramdom part of all the tags at level N-X). Moreover, the number of tags is a very bad metric: tags with a large amount of text (ie. books) take a lot of time during the layout, whereas insane numbers of deeply nested empty divs (I’m looking at you, websites generated by "modern" JS frameworks) can be rendered very quickly.

So… In my opinion, adding some kind of percentage in the logs would only be a marketing feature creating a lot of frustration for real end users :smile:.
