### ISSUE TITLE
bullets and numbers misaligned in a page break.

### ISSUE THREAD

**Issue by fabiobatalha** [Kozea/WeasyPrint#1188]
When lists are in a page break, the bullets and numbers becomes misaligned.

![Capture du 2020-08-13 16-11-49](https://user-images.githubusercontent.com/504142/90182601-356b5380-dd80-11ea-8910-40aefe6112b0.png)

**Comment by liZe** [comment]
Hello, and thank you for this report.

Could you please provide an HTML sample? I can’t reproduce with a simple list.

**Comment by fabiobatalha** [comment]
Hello @liZe 

Thanks for the support, the example is below.

[erudit:erudit.ae49.ae03070.1039880ar.wp.html.zip](https://github.com/Kozea/WeasyPrint/files/5071327/erudit.erudit.ae49.ae03070.1039880ar.wp.html.zip)

[erudit:erudit.ae49.ae03070.1039880ar.wp.pdf](https://github.com/Kozea/WeasyPrint/files/5071328/erudit.erudit.ae49.ae03070.1039880ar.wp.pdf)

**Comment by GiovanniSalmeri** [comment]
Same (or similar) bug here, if I am not wrong: https://github.com/Kozea/WeasyPrint/issues/1058

**Comment by liZe** [comment]
> Same (or similar) bug here (with minimal HTML example), if I am not wrong: #1058

Exactly the same, thanks! Closing, we can continue the discussion over there.
