### ISSUE TITLE
Image Loading Failure

### ISSUE THREAD

**Issue by dwasyl** [Kozea/WeasyPrint#1192]
Hi all,

I'm running `weasyprint 51 ` through a Python 3.8/Django 2.2 application, and everything is loading fine, the PDF generated looks great, except for image loading. The images in the document don't load at all, the alt text appears fine, but no image file. The PDF loads the fonts (included as URLs with `{% static '' %}` tags as well) so it's not a `base_url` issue. I thought it might have been a issue communicating with the server, but since the font files load without any issue that can't be it.

Any other ideas as to what would prevent images from loading, or ways to debug the issue?

Thanks

**Comment by liZe** [comment]
Hello!

You probably have useful errors in logs, that’s the best solution to know what’s going on.

**Comment by dwasyl** [comment]
@liZe for whatever reason I hadn't thought of jumping up the logging level. I tracked down my error, although I never did get gif/jpgs to work (and there were no errors), but once I converted things to PNG it did so that's fine.
