### ISSUE TITLE
mermaid graphs cannot be parsed

### ISSUE THREAD

**Issue by Lucurus** [Kozea/WeasyPrint#1196]
Hi,

I have a problem with HTML files which include a mermaid graph.

Background: [mermaid](https://mermaid-js.github.io/mermaid/#/) allows creating diagrams via a programming language. This is then rendered by the browser, as outlined [here](https://mermaid-js.github.io/mermaid/#/usage?id=hosting-mermaid-on-a-web-page).

Sample code:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
</head>
<body>
  <div class="mermaid">
  graph LR
      A --- B
      B-->C[fa:fa-ban forbidden]
      B-->D(fa:fa-spinner);
  </div>
 <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
 <script>mermaid.initialize({startOnLoad:true});</script>
</body>
</html>

```

which renders to:
 [![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICAgIEEgLS0tIEJcbiAgICAgIEItLT5DW2ZhOmZhLWJhbiBmb3JiaWRkZW5dXG4gICAgICBCLS0-RChmYTpmYS1zcGlubmVyKTsiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGFyayIsInRoZW1lVmFyaWFibGVzIjp7ImJhY2tncm91bmQiOiIjMzMzIiwicHJpbWFyeUNvbG9yIjoiIzFmMjAyMCIsInNlY29uZGFyeUNvbG9yIjoiaHNsKDE4MCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwidGVydGlhcnlDb2xvciI6ImhzbCgyMCwgMS41ODczMDE1ODczJSwgMTIuMzUyOTQxMTc2NSUpIiwicHJpbWFyeUJvcmRlckNvbG9yIjoiaHNsKDE4MCwgMCUsIDIuMzUyOTQxMTc2NSUpIiwic2Vjb25kYXJ5Qm9yZGVyQ29sb3IiOiJoc2woMTgwLCAwJSwgMTguMzUyOTQxMTc2NSUpIiwidGVydGlhcnlCb3JkZXJDb2xvciI6ImhzbCgyMCwgMCUsIDIuMzUyOTQxMTc2NSUpIiwicHJpbWFyeVRleHRDb2xvciI6IiNlMGRmZGYiLCJzZWNvbmRhcnlUZXh0Q29sb3IiOiJyZ2IoMTgzLjg0NzYxOTA0NzUsIDE4MS41NTIzODA5NTIzLCAxODEuNTUyMzgwOTUyMykiLCJ0ZXJ0aWFyeVRleHRDb2xvciI6InJnYigyMjIuOTk5OTk5OTk5OSwgMjIzLjY2NjY2NjY2NjYsIDIyMy45OTk5OTk5OTk5KSIsImxpbmVDb2xvciI6ImxpZ2h0Z3JleSIsInRleHRDb2xvciI6IiNjY2MiLCJtYWluQmtnIjoiIzFmMjAyMCIsInNlY29uZEJrZyI6ImhzbCgxODAsIDEuNTg3MzAxNTg3MyUsIDI4LjM1Mjk0MTE3NjUlKSIsIm1haW5Db250cmFzdENvbG9yIjoibGlnaHRncmV5IiwiZGFya1RleHRDb2xvciI6ImhzbCgyOC41NzE0Mjg1NzE0LCAxNy4zNTUzNzE5MDA4JSwgODYuMjc0NTA5ODAzOSUpIiwiYm9yZGVyMSI6IiM4MUIxREIiLCJib3JkZXIyIjoicmdiYSgyNTUsIDI1NSwgMjU1LCAwLjI1KSIsImFycm93aGVhZENvbG9yIjoibGlnaHRncmV5IiwiZm9udEZhbWlseSI6IlwidHJlYnVjaGV0IG1zXCIsIHZlcmRhbmEsIGFyaWFsIiwiZm9udFNpemUiOiIxNnB4IiwibGFiZWxCYWNrZ3JvdW5kIjoiIzE4MTgxOCIsIm5vZGVCa2ciOiIjMWYyMDIwIiwibm9kZUJvcmRlciI6IiM4MUIxREIiLCJjbHVzdGVyQmtnIjoiaHNsKDE4MCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiY2x1c3RlckJvcmRlciI6InJnYmEoMjU1LCAyNTUsIDI1NSwgMC4yNSkiLCJkZWZhdWx0TGlua0NvbG9yIjoibGlnaHRncmV5IiwidGl0bGVDb2xvciI6IiNGOUZGRkUiLCJlZGdlTGFiZWxCYWNrZ3JvdW5kIjoiaHNsKDAsIDAlLCAzNC40MTE3NjQ3MDU5JSkiLCJhY3RvckJvcmRlciI6IiM4MUIxREIiLCJhY3RvckJrZyI6IiMxZjIwMjAiLCJhY3RvclRleHRDb2xvciI6ImxpZ2h0Z3JleSIsImFjdG9yTGluZUNvbG9yIjoibGlnaHRncmV5Iiwic2lnbmFsQ29sb3IiOiJsaWdodGdyZXkiLCJzaWduYWxUZXh0Q29sb3IiOiJsaWdodGdyZXkiLCJsYWJlbEJveEJrZ0NvbG9yIjoiIzFmMjAyMCIsImxhYmVsQm94Qm9yZGVyQ29sb3IiOiIjODFCMURCIiwibGFiZWxUZXh0Q29sb3IiOiJsaWdodGdyZXkiLCJsb29wVGV4dENvbG9yIjoibGlnaHRncmV5Iiwibm90ZUJvcmRlckNvbG9yIjoicmdiYSgyNTUsIDI1NSwgMjU1LCAwLjI1KSIsIm5vdGVCa2dDb2xvciI6IiNmZmY1YWQiLCJub3RlVGV4dENvbG9yIjoiIzFmMjAyMCIsImFjdGl2YXRpb25Cb3JkZXJDb2xvciI6IiM4MUIxREIiLCJhY3RpdmF0aW9uQmtnQ29sb3IiOiJoc2woMTgwLCAxLjU4NzMwMTU4NzMlLCAyOC4zNTI5NDExNzY1JSkiLCJzZXF1ZW5jZU51bWJlckNvbG9yIjoiYmxhY2siLCJzZWN0aW9uQmtnQ29sb3IiOiJoc2woNTIuOTQxMTc2NDcwNiwgMjguODEzNTU5MzIyJSwgNTguNDMxMzcyNTQ5JSkiLCJhbHRTZWN0aW9uQmtnQ29sb3IiOiIjMzMzIiwic2VjdGlvbkJrZ0NvbG9yMiI6IiNFQUU4RDkiLCJ0YXNrQm9yZGVyQ29sb3IiOiIjZmZmZmZmIiwidGFza0JrZ0NvbG9yIjoiaHNsKDE4MCwgMS41ODczMDE1ODczJSwgMzUuMzUyOTQxMTc2NSUpIiwidGFza1RleHRDb2xvciI6ImhzbCgyOC41NzE0Mjg1NzE0LCAxNy4zNTUzNzE5MDA4JSwgODYuMjc0NTA5ODAzOSUpIiwidGFza1RleHRMaWdodENvbG9yIjoibGlnaHRncmV5IiwidGFza1RleHRPdXRzaWRlQ29sb3IiOiJsaWdodGdyZXkiLCJ0YXNrVGV4dENsaWNrYWJsZUNvbG9yIjoiIzAwMzE2MyIsImFjdGl2ZVRhc2tCb3JkZXJDb2xvciI6IiNmZmZmZmYiLCJhY3RpdmVUYXNrQmtnQ29sb3IiOiIjODFCMURCIiwiZ3JpZENvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCa2dDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQm9yZGVyQ29sb3IiOiJncmV5IiwiY3JpdEJvcmRlckNvbG9yIjoiI0U4MzczNyIsImNyaXRCa2dDb2xvciI6IiNFODM3MzciLCJ0YXNrVGV4dERhcmtDb2xvciI6ImhzbCgyOC41NzE0Mjg1NzE0LCAxNy4zNTUzNzE5MDA4JSwgODYuMjc0NTA5ODAzOSUpIiwidG9kYXlMaW5lQ29sb3IiOiIjREI1NzU3IiwibGFiZWxDb2xvciI6IiNjY2MiLCJlcnJvckJrZ0NvbG9yIjoiI2E0NDE0MSIsImVycm9yVGV4dENvbG9yIjoiI2RkZCIsImFsdEJhY2tncm91bmQiOiJoc2woMCwgMCUsIDQwJSkiLCJmaWxsVHlwZTAiOiIjMWYyMDIwIiwiZmlsbFR5cGUxIjoiaHNsKDE4MCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGUyIjoiaHNsKDI0NCwgMS41ODczMDE1ODczJSwgMTIuMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGUzIjoiaHNsKDI0NCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGU0IjoiaHNsKDExNiwgMS41ODczMDE1ODczJSwgMTIuMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGU1IjoiaHNsKDExNiwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGU2IjoiaHNsKDMwOCwgMS41ODczMDE1ODczJSwgMTIuMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGU3IjoiaHNsKDMwOCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiY2xhc3NUZXh0IjoiI2UwZGZkZiJ9fSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/docs/mermaid-live-editor-beta/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICAgIEEgLS0tIEJcbiAgICAgIEItLT5DW2ZhOmZhLWJhbiBmb3JiaWRkZW5dXG4gICAgICBCLS0-RChmYTpmYS1zcGlubmVyKTsiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGFyayIsInRoZW1lVmFyaWFibGVzIjp7ImJhY2tncm91bmQiOiIjMzMzIiwicHJpbWFyeUNvbG9yIjoiIzFmMjAyMCIsInNlY29uZGFyeUNvbG9yIjoiaHNsKDE4MCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwidGVydGlhcnlDb2xvciI6ImhzbCgyMCwgMS41ODczMDE1ODczJSwgMTIuMzUyOTQxMTc2NSUpIiwicHJpbWFyeUJvcmRlckNvbG9yIjoiaHNsKDE4MCwgMCUsIDIuMzUyOTQxMTc2NSUpIiwic2Vjb25kYXJ5Qm9yZGVyQ29sb3IiOiJoc2woMTgwLCAwJSwgMTguMzUyOTQxMTc2NSUpIiwidGVydGlhcnlCb3JkZXJDb2xvciI6ImhzbCgyMCwgMCUsIDIuMzUyOTQxMTc2NSUpIiwicHJpbWFyeVRleHRDb2xvciI6IiNlMGRmZGYiLCJzZWNvbmRhcnlUZXh0Q29sb3IiOiJyZ2IoMTgzLjg0NzYxOTA0NzUsIDE4MS41NTIzODA5NTIzLCAxODEuNTUyMzgwOTUyMykiLCJ0ZXJ0aWFyeVRleHRDb2xvciI6InJnYigyMjIuOTk5OTk5OTk5OSwgMjIzLjY2NjY2NjY2NjYsIDIyMy45OTk5OTk5OTk5KSIsImxpbmVDb2xvciI6ImxpZ2h0Z3JleSIsInRleHRDb2xvciI6IiNjY2MiLCJtYWluQmtnIjoiIzFmMjAyMCIsInNlY29uZEJrZyI6ImhzbCgxODAsIDEuNTg3MzAxNTg3MyUsIDI4LjM1Mjk0MTE3NjUlKSIsIm1haW5Db250cmFzdENvbG9yIjoibGlnaHRncmV5IiwiZGFya1RleHRDb2xvciI6ImhzbCgyOC41NzE0Mjg1NzE0LCAxNy4zNTUzNzE5MDA4JSwgODYuMjc0NTA5ODAzOSUpIiwiYm9yZGVyMSI6IiM4MUIxREIiLCJib3JkZXIyIjoicmdiYSgyNTUsIDI1NSwgMjU1LCAwLjI1KSIsImFycm93aGVhZENvbG9yIjoibGlnaHRncmV5IiwiZm9udEZhbWlseSI6IlwidHJlYnVjaGV0IG1zXCIsIHZlcmRhbmEsIGFyaWFsIiwiZm9udFNpemUiOiIxNnB4IiwibGFiZWxCYWNrZ3JvdW5kIjoiIzE4MTgxOCIsIm5vZGVCa2ciOiIjMWYyMDIwIiwibm9kZUJvcmRlciI6IiM4MUIxREIiLCJjbHVzdGVyQmtnIjoiaHNsKDE4MCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiY2x1c3RlckJvcmRlciI6InJnYmEoMjU1LCAyNTUsIDI1NSwgMC4yNSkiLCJkZWZhdWx0TGlua0NvbG9yIjoibGlnaHRncmV5IiwidGl0bGVDb2xvciI6IiNGOUZGRkUiLCJlZGdlTGFiZWxCYWNrZ3JvdW5kIjoiaHNsKDAsIDAlLCAzNC40MTE3NjQ3MDU5JSkiLCJhY3RvckJvcmRlciI6IiM4MUIxREIiLCJhY3RvckJrZyI6IiMxZjIwMjAiLCJhY3RvclRleHRDb2xvciI6ImxpZ2h0Z3JleSIsImFjdG9yTGluZUNvbG9yIjoibGlnaHRncmV5Iiwic2lnbmFsQ29sb3IiOiJsaWdodGdyZXkiLCJzaWduYWxUZXh0Q29sb3IiOiJsaWdodGdyZXkiLCJsYWJlbEJveEJrZ0NvbG9yIjoiIzFmMjAyMCIsImxhYmVsQm94Qm9yZGVyQ29sb3IiOiIjODFCMURCIiwibGFiZWxUZXh0Q29sb3IiOiJsaWdodGdyZXkiLCJsb29wVGV4dENvbG9yIjoibGlnaHRncmV5Iiwibm90ZUJvcmRlckNvbG9yIjoicmdiYSgyNTUsIDI1NSwgMjU1LCAwLjI1KSIsIm5vdGVCa2dDb2xvciI6IiNmZmY1YWQiLCJub3RlVGV4dENvbG9yIjoiIzFmMjAyMCIsImFjdGl2YXRpb25Cb3JkZXJDb2xvciI6IiM4MUIxREIiLCJhY3RpdmF0aW9uQmtnQ29sb3IiOiJoc2woMTgwLCAxLjU4NzMwMTU4NzMlLCAyOC4zNTI5NDExNzY1JSkiLCJzZXF1ZW5jZU51bWJlckNvbG9yIjoiYmxhY2siLCJzZWN0aW9uQmtnQ29sb3IiOiJoc2woNTIuOTQxMTc2NDcwNiwgMjguODEzNTU5MzIyJSwgNTguNDMxMzcyNTQ5JSkiLCJhbHRTZWN0aW9uQmtnQ29sb3IiOiIjMzMzIiwic2VjdGlvbkJrZ0NvbG9yMiI6IiNFQUU4RDkiLCJ0YXNrQm9yZGVyQ29sb3IiOiIjZmZmZmZmIiwidGFza0JrZ0NvbG9yIjoiaHNsKDE4MCwgMS41ODczMDE1ODczJSwgMzUuMzUyOTQxMTc2NSUpIiwidGFza1RleHRDb2xvciI6ImhzbCgyOC41NzE0Mjg1NzE0LCAxNy4zNTUzNzE5MDA4JSwgODYuMjc0NTA5ODAzOSUpIiwidGFza1RleHRMaWdodENvbG9yIjoibGlnaHRncmV5IiwidGFza1RleHRPdXRzaWRlQ29sb3IiOiJsaWdodGdyZXkiLCJ0YXNrVGV4dENsaWNrYWJsZUNvbG9yIjoiIzAwMzE2MyIsImFjdGl2ZVRhc2tCb3JkZXJDb2xvciI6IiNmZmZmZmYiLCJhY3RpdmVUYXNrQmtnQ29sb3IiOiIjODFCMURCIiwiZ3JpZENvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCa2dDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQm9yZGVyQ29sb3IiOiJncmV5IiwiY3JpdEJvcmRlckNvbG9yIjoiI0U4MzczNyIsImNyaXRCa2dDb2xvciI6IiNFODM3MzciLCJ0YXNrVGV4dERhcmtDb2xvciI6ImhzbCgyOC41NzE0Mjg1NzE0LCAxNy4zNTUzNzE5MDA4JSwgODYuMjc0NTA5ODAzOSUpIiwidG9kYXlMaW5lQ29sb3IiOiIjREI1NzU3IiwibGFiZWxDb2xvciI6IiNjY2MiLCJlcnJvckJrZ0NvbG9yIjoiI2E0NDE0MSIsImVycm9yVGV4dENvbG9yIjoiI2RkZCIsImFsdEJhY2tncm91bmQiOiJoc2woMCwgMCUsIDQwJSkiLCJmaWxsVHlwZTAiOiIjMWYyMDIwIiwiZmlsbFR5cGUxIjoiaHNsKDE4MCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGUyIjoiaHNsKDI0NCwgMS41ODczMDE1ODczJSwgMTIuMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGUzIjoiaHNsKDI0NCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGU0IjoiaHNsKDExNiwgMS41ODczMDE1ODczJSwgMTIuMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGU1IjoiaHNsKDExNiwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGU2IjoiaHNsKDMwOCwgMS41ODczMDE1ODczJSwgMTIuMzUyOTQxMTc2NSUpIiwiZmlsbFR5cGU3IjoiaHNsKDMwOCwgMS41ODczMDE1ODczJSwgMjguMzUyOTQxMTc2NSUpIiwiY2xhc3NUZXh0IjoiI2UwZGZkZiJ9fSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

This is correctly rendered in a browser, but WeasyPrint only displays the raw text and does not render the diagram.

Is that something that can be remedied or is it inherently incompatible with WeasyPrint?

Thanks!

See also: https://github.com/mermaid-js/mermaid

**Comment by liZe** [comment]
Hello!

WeasyPrint doesn’t (and won’t) support JavaScript, that’s why your graph is not rendered. :/

More about this in #454.

**Comment by ticapix** [comment]
As I faced the same issue, here are my lessons learned.

# Option1

If you use only [class diagram](https://mermaid-js.github.io/mermaid/#/classDiagram), please check this bug https://github.com/mermaid-js/mermaid/issues/2124 and here is a hack to include in any `.md` file

This will convert `svg` element into an `Image` with inline base64 svg content.  
Cairosvg will then nicely convert it to an image and it'll be rendered in the PDF.

```javascript
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
 <script>
mermaid.initialize({
    startOnLoad: true,
    mermaid: {
        callback: function(id) {
            let s = document.querySelector('#' + id);
            let x = new XMLSerializer().serializeToString(s);
            let b = window.btoa(x);
            s.parentNode.innerHTML = "<img src='data:image/svg+xml;base64, " + b + "'/>";
        }
    }
});</script>
```

# Option 2

If you use other class, such as [flowchart](https://mermaid-js.github.io/mermaid/#/flowchart), the generated SVG will contains `<foreignObject>` which are not rendered by CairoSVG. Check https://github.com/Kozea/CairoSVG/issues/147. Typically, text will not be displayed.

The hack is then to:
1. transform the `svg` element into an `img` element
2. draw the `img` content into a `canvas`
3. insert a new image using the raw pixel data from the `canvas`

Unfortunately, due to some scaling interpolation, the rendered image is a bit blurry. Check https://stackoverflow.com/questions/7615009/disable-interpolation-when-scaling-a-canvas. Here is the code to add to any `.md` file

```javascript
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>
function fix2124(id) {
    // fix issue https://github.com/mermaid-js/mermaid/issues/2124
    document.querySelectorAll("#" + id + " marker[markerWidth]").forEach((elt) => {
        elt.setAttribute("markerWidth", elt.getAttribute("markerWidth") > 100 ? elt.getAttribute("markerWidth")/10 : elt.getAttribute("markerWidth"))
    });
    document.querySelectorAll("#" + id + " marker[markerHeight]").forEach((elt) => {
        elt.setAttribute("markerHeight", elt.getAttribute("markerHeight") > 100 ? elt.getAttribute("markerHeight")/10 : elt.getAttribute("markerHeight"))
    });
}

mermaid.initialize({
    startOnLoad: true,
    mermaid: {
        callback: function(id) {
            console.log("mermaid callback with id", id);
            let svg = document.querySelector('#' + id);
            fix2124(id);
            let data = new XMLSerializer().serializeToString(svg);
            let blob = window.btoa(data);
            let img = new Image();
            img.onload = function() {
                let canvas = document.createElement('canvas');
                // svg.parentNode.appendChild(canvas);
                canvas.height = svg.getBoundingClientRect().height;
                canvas.width = svg.getBoundingClientRect().width;
                let ctx = canvas.getContext('2d');
                ctx.mozImageSmoothingEnabled = false;
                ctx.webkitImageSmoothingEnabled = false;
                ctx.msImageSmoothingEnabled = false;
                ctx.imageSmoothingEnabled = false;
                ctx.drawImage(img, 0, 0);
                let img2 = document.createElement('img');
                img2.src = canvas.toDataURL();
                svg.parentNode.appendChild(img2);
                svg.remove();
            }
            img.src = "data:image/svg+xml;base64," + blob;
            // svg.parentNode.appendChild(img);
        }
    }
});</script>
```

This is not yet a good solution but it unblock the release of PDF document.  

Another options could be to:
- improve cairosvg to support `<foreignObject>`
- improve mermaid to not use `<foreignObject>`
- make a `XMLrequest` to call a remote API transforming the `svg` into a nice `png`
