### ISSUE TITLE
border CSS not supporting some elements

### ISSUE THREAD

**Issue by Azteker** [Kozea/WeasyPrint#1198]
I tried to add css style for a td in table, for example
```
table>tbody>tr>td {
     font-size: 14px;
     border: 1px solid black;
}
```
The border style is not working while the font-size works. However, border style does work for most other elements, like `table`.

**Comment by Azteker** [comment]
> > It is proper rendered on browser(every row has border)
> 
> Could you please provide a complete sample that I can test? It’s really hard to understand what your problem is without it.
> 
> Here’s my working sample:
> 
> ```
> <style>
> table{ border-collapse: collapse }
> table > tbody > tr {
>      font-size: 14px;
>      border: 1px solid black;
> }
> </style>
> <table><tbody>
> <tr><td>a</td></tr>
> <tr><td>b</td></tr>
> <tr><td>c</td></tr>
> ```
> 
> ![Capture d’écran de 2020-08-22 22-33-50](https://user-images.githubusercontent.com/952243/90965356-bedcfd00-e4c7-11ea-93eb-07207c11b187.png)

Looks some other CSS styles affect it, but I am not sure which one.

**Comment by liZe** [comment]
@Azteker Can I close this issue?
