### ISSUE TITLE
Converting to PNG not fully completed

### ISSUE THREAD

**Issue by Dung-Dang** [Kozea/WeasyPrint#1200]
Hi, I'm trying to use WeasyPrint to convert html file (Jupyter Notebook output) to PNG. Correct me if WeasyPrint isn't the suitable method for this.
When I run the code to convert the file, WeasyPrint always stop at a some point, instead of converting the entire file. May I ask what went wrong?

```
import weasyprint
weasyprint.HTML('example.html').write_png('screenshot.png')
```
[example.txt](https://github.com/Kozea/WeasyPrint/files/5115788/example.txt)

**Comment by liZe** [comment]
Hello!

> When I run the code to convert the file, WeasyPrint always stop at a some point, instead of converting the entire file. May I ask what went wrong?

Of course you can! :smile:

Your problem is #36: your `body` has the `position: absolute` property (line 9391), so the block never breaks. Removing this line (or adding `body { position: static }`) fixes the problem. The rendering is not perfect, you’ll need a couple of extra CSS properties to avoid the two first page breaks, but at least your code block will be split between pages.

**Comment by Dung-Dang** [comment]
sorry, I tried what you suggested, and still couldn't convert the HTML file to PNG

**Comment by liZe** [comment]
Oh, sorry, I did miss the last part with the graph 😒.

This part is not rendered because it’s generated with a JavaScript script, and JavaScript is not supported (and will never be) by WeasyPrint. You can read #454 to learn more about this.

**Comment by Dung-Dang** [comment]
Regarding the `position: absolute` problem, do I need to remove all parts with that line, or only the one at body part will do?

**Comment by liZe** [comment]
> Regarding the `position: absolute` problem, do I need to remove all parts with that line, or only the one at body part will do?

Removing only this line works for your document (ie. you’ll get more than one page), but you may have to remove other lines for other documents. It doesn’t fix the problem of the last part.

![screenshot](https://user-images.githubusercontent.com/952243/91056682-8dc70e80-e626-11ea-9e93-fce21da857ff.png)

**Comment by liZe** [comment]
@Dung-Dang Is there anything else we can do for you?
