### ISSUE TITLE
list-style-type as content being ignored

### ISSUE THREAD

**Issue by muzzamilkhan** [Kozea/WeasyPrint#1206]
With CSS3 introducing content being set as list-style-type, this is being ignored by Weasyprint:

CSS:
`ul {list-style-type: '-';}
ul ul {list-style-type: '+';}`

Console error:
WARNING: Ignored `list-style-type:\"-\"` at **, invalid value.
WARNING: Ignored `list-style-type:\"+\"` at **, invalid value.

**Comment by malnajdi** [comment]
Hey, I tested this with the `master` branch and it seems it's working.
```
<html>
<head>
 <style>
   ul {list-style-type: '-';}
   ul ul {list-style-type: '+';}
 </style>
</head>
<body>
  <ul>
    <li>Homammed<li>
    <ul>
      <li>Homammed<li>
    </ul>
  </ul>
</body>
</html>
```
![image](https://user-images.githubusercontent.com/15247545/94916633-b9f06d80-04b7-11eb-9393-1bc94441b8f3.png)

**Comment by liZe** [comment]
> Hey, I tested this with the `master` branch and it seems it's working.

There’s no code in WeasyPrint to handle that, and I get:
```
WARNING: Ignored `list-style-type: "-"` at 2:8, invalid value.
WARNING: Ignored `list-style-type: "+"` at 3:11, invalid value.
```
I don’t know how it could work for you :smile:.

**Comment by liZe** [comment]
> > Hey, I tested this with the `master` branch and it seems it's working.
