### ISSUE TITLE
weasyprint logo?

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1213]
I am preparing a presentation for the Frankfurt Bookfair on PrintCSS.
Is there an official Weasyprint logo that I could include?

**Comment by grewn0uille** [comment]
Hi!
You can include the logo [used on the WeasyPrint’s website](https://github.com/Kozea/WeasyPrint/blob/gh-pages/css/img/logotype-black.svg).
I don’t know what you’re going to say about WeasyPrint, but the project is no longer maintained by Kozea but by another organization named [CourtBouillon](https://www.courtbouillon.org). A clear communication about that is coming very soon :)
