### ISSUE TITLE
Extending the API of url_fetcher

### ISSUE THREAD

**Issue by WhyNotHugo** [Kozea/WeasyPrint#1217]
Hi there! Thanks for all the effort you've put into developing and maintaining weasyprint, it's been an indispensable tool for years!

Issue
------

Over time, I've worked on multiple projects that used weasyprint with custom `url_fetchers`:

- Custom schema for barcodes: `barcode://ean13/CODE`.
- Images generated from data `graph://orders/today`.
- Inside a webapp to resolve relative URLs as internal links.
- [`django-renderpdf`](https://django-renderpdf.readthedocs.io/en/latest/) has, for years, shipped its own `url_fetcher` (to handle django's static files, and recently, media files).
- I currently maintain [`python-barcode`](https://pypi.org/project/python-barcode/), and I'd love to have a `url_fetcher` that's easily reusable (I've used similar fetchers implemented in several codebases I've worked on, and it makes sense for me to upstream them).

They've all worked, however, when I need to use several of these in a single PDF, I need to create a custom `url_fetcher` that does a lot of delegation to other `url_fetchers`, with lots of funky fallback handling.

This needs to be done in every project, and kinda depends on the mix of fetchers one is using (which also kinda makes it hard to implement reusable, shippable `url_fetchers`.

Proposal
------

I'd like to propose iterating over the API around `url_fetchers`:

- Pass a _list_ of `url_fetchers`, not just one.
- Each one should return a file (as they do now), or raise `CannotFetch`.
- Weasyprint can try each fetcher in order, and only raise if the last one cannot handle this.

Ultimately, I'd like third-party projects to be able to provide fetchers, and if any project uses multiple libraries that provide `url_fetchers`, all the glue and integration is very simple to do, while keeping weasyprint's API nice and simple.

Sample now:

```python
    HTML(
        string=html,
        base_url="not-used://",
        url_fetcher=custom_fetcher_that_wraps_many,
    ).write_pdf(
        target=file_,
    )

```
Sample with my proposal:

```python
    HTML(
        string=html,
        base_url="not-used://",
        url_fetcher=[default_url_fetcher, barcode_url_fetcher, django_url_fetcher],
    ).write_pdf(
        target=file_,
    )

```
I think the `url_fetcher` parameter should take either a callable (as it does now), or a list of callables, for backwards compatibility.

I'd like to jump into working on this, but rather than come up with a PR out of nowhere, I though I'd share the idea first, and see if you think it makes sense (or maybe even have a far better idea to work on this!).

Does this make sense to you guys?

**Comment by liZe** [comment]
Hi!

I understand your needs, and it would nice to find a good solution. Changing the API is always a big change, even with backwards compatibility, and we have to be sure that there’s no other solution.

Having a list of fetchers opens new questions. We can call the fetchers in order and take the first one with a 200 response, as you want to do. But we could also call all the fetchers in parallel and get the fastest one. We also have do decide what to return when all the fetchers raise an error: the first error, the last error, another error?

I think that your idea is good, but that we’ll have more and more possibilities needed by users. Having to handle these possibilities would probably require extra keywords, and thus make the API more complex.

I’d prefer to give a Python sample in documentation, and let users adapt it if needed. Proposing something like this function would be a good start (not tested at all):

```python
def chained_url_fetcher(*fetchers):
    def fetch(*args, **kwargs):
        for fetcher in fetchers:
            try:
                return fetcher(*args, **kwargs)
            except:
                pass  # or log, or return the latest error, or…
        raise Exception()  # or create a dedicated exception, or…
    return fetch
```

You can then use this function:
```python
HTML(
    string=html,
    base_url="not-used://",
    url_fetcher=chained_url_fetcher(default_url_fetcher, barcode_url_fetcher, django_url_fetcher),
).write_pdf(
    target=file_,
)
```

That’s right, you’ll have to add 10 lines to your code, but it gives you the possibility to adapt it to your needs (and hopefully other users to adapt it to theirs :wink:).

Would this solution give you satisfaction?

**Comment by liZe** [comment]
@WhyNotHugo Can we do anything more to help you?

**Comment by WhyNotHugo** [comment]
Oh, sorry for my lack of reply!

Something like this really _would_ help:

```
def chained_url_fetcher(*fetchers):
    def fetch(*args, **kwargs):
        for fetcher in fetchers:
            try:
                return fetcher(*args, **kwargs)
            except:
                pass  # or log, or return the latest error, or…
        raise Exception()  # or create a dedicated exception, or…
    return fetch
```

I'm not a fan of having to copy the same snippet around in every project (I feel that this is required pretty much any time I use weasyprint). Any chances in can actually be included in weasyprint?

I can push a PR with docs if you think it's acceptable.

**Comment by liZe** [comment]
> Oh, sorry for my lack of reply!

No problem, I’m often late too!

> I'm not a fan of having to copy the same snippet around in every project (I feel that this is required pretty much any time I use weasyprint). Any chances in can actually be included in weasyprint?

I’m sorry, but I don’t think that it will be included. That’s exactly the kind of snippets that are really useful for someone, and that would be really useful to someone else with just a little change, and to someone else with this little extra feature, and… A friend of mine would say that it’s a cute puppy that will turn into a sadistic monster after a year or so :wink:.

An "easy" solution for you would be to create a Python module with this snippet and upload it to PyPI, so that you can use it everywhere. Having a specific URL fetcher is more or less what Flask-WeasyPrint and Django-WeasyPrint do (with a couple of extra features).

> I can push a PR with docs if you think it's acceptable.

I would love that, thank you! You can add a section to the Tips & Tricks page.

**Comment by liZe** [comment]
> I would love that, thank you! You can add a section to the Tips & Tricks page.

Please open a PR if you find the time for this! ❤️
