### ISSUE TITLE
WeasyPrint Navigator error 'PANGO_IS_FC_FONT_MAP'

### ISSUE THREAD

**Issue by SairamSV** [Kozea/WeasyPrint#1220]
Python Version: 3.7.8 (64-bit)
OS: Windows 7 (SP1) - 64Bit

**Actions:**
Opened http://127.0.0.1:5000/
clicked on "CSS Specifications"

**Below Error occurred**
(rptenv) E:\rptenv-64>python -m weasyprint.tools.navigator
Listening on http://127.0.0.1:5000/ ...
127.0.0.1 - - [28/Sep/2020 18:54:07] "GET / HTTP/1.1" 200 1280
127.0.0.1 - - [28/Sep/2020 18:54:08] "GET /favicon.ico HTTP/1.1" 404 18

(process:6000): GLib-GObject-WARNING **: 18:54:16.015: cannot register existing
type 'PangoFcFontMap'

(process:6000): GLib-GObject-WARNING **: 18:54:16.017: cannot add private field
to invalid (non-instantiatable) type '<invalid>'

(process:6000): GLib-CRITICAL **: 18:54:16.019: g_once_init_leave: assertion 're
sult != 0' failed

(process:6000): Pango-CRITICAL **: 18:54:16.019: pango_fc_font_map_set_config: a
ssertion 'PANGO_IS_FC_FONT_MAP (fcfontmap)' failed

**Comment by liZe** [comment]
I don’t know why this error happens. @SairamSV Is this problem fixed for you?
