### ISSUE TITLE
Roadmap/release schedule

### ISSUE THREAD

**Issue by pbregener** [Kozea/WeasyPrint#1222]
Hi and thanks for your great work on this project!

Version 51 was released late last year and it seems like a lot has happened on master since then!  
Is there a plan for a v52, yet? Is there even some kind of roadmap that I didn't see?

**Comment by grewn0uille** [comment]
Hi!
There are some changes on the management of the project. It’s no longer maintained by Kozea but by CourtBouillon.
A clear communication about is coming very soon, and of courses releases ;)

**Comment by pbregener** [comment]
See #1232
