### ISSUE TITLE
Break page instead to push elements to next one

### ISSUE THREAD

**Issue by realnot** [Kozea/WeasyPrint#1223]
Is normal that Weasyprint break the page instead to push content to next line? Here an example:

![wasyprint_break_page](https://user-images.githubusercontent.com/2405675/94544656-cbcdd880-024b-11eb-9ee7-c6f0af223d40.png)

There's a fix/solution for this?

Thanks in advance

**Comment by Tontyna** [comment]
Do I understand correctly? You want WeasyPrint to push the "Title" and the "Section 1" onto the next page?

The solution depends on your actual HTML and CSS -- could you provide a sample?

**Comment by realnot** [comment]
Yes, the first page contain a table (not visibile in the picture) and the second page contains the thumbnail of documents attached to relative sections. I would like to push / start the "document section" on second page (no matter what first page contains) and title of sections always on top of sections, instead here you see that title is in first page and related documents on second page.  I'll provide you the HTML and CSS as fast as possibile.

Thanks for your time

**Comment by realnot** [comment]
Here the HTML and CSS


[result_html_and_base_css.zip](https://github.com/Kozea/WeasyPrint/files/5299006/result_html_and_base_css.zip)

**Comment by Tontyna** [comment]
To push the "document section table" to the next page style it with `break-before:always`. Apply `break-after: avoid` to the  "section title" rows to glue them to their thumbnail section.

**Comment by realnot** [comment]
Fixed! Thanks a lot! The world has one less "bug" :)

**Comment by liZe** [comment]
> Fixed! Thanks a lot! The world has one less "bug" :)

👍🏼
