### ISSUE TITLE
Display <select> and <option> using a dedicated stylesheet

### ISSUE THREAD

**Issue by metapone** [Kozea/WeasyPrint#1224]
In the documentations I only see stylesheet for `input (text, checkbox, radio)` and `textarea`. Weird form type like `input[type=range]` would be hard to render in a quick-and-dirty way, I understand, but what about `select`?

I'm currently adding a `option:checked` next to `input` in my dedicated stylesheet, but the result doesn't look very good. All styles for `select` is lost because the actual element isn't rendered but only its selected option, but if I try to style `select` as well then `select` and `option` become separated as if they are different elements, with `select` being only a blank rectangular.

P.S. Is there a way to set a style to be used only for printing with WeasyPrint? Just in case if in the future I want to style the pages differently when they are printed versus when they are viewed online.

**Comment by grewn0uille** [comment]
Hi!
> P.S. Is there a way to set a style to be used only for printing with WeasyPrint? Just in case if in the future I want to style the pages differently when they are printed versus when they are viewed online.

You can use [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) to define css only for print `@media print { your_css }`

**Comment by liZe** [comment]
Let’s fix this problem in #1173 for all form inputs.
