### ISSUE TITLE
Long png / pdf without page break for roll receipt printing

### ISSUE THREAD

**Issue by goodwill** [Kozea/WeasyPrint#1226]
I would like to use weasyprint for thermal printer receipt generation, is there a way I can make all contents to output as one single page instead of breaking it into multiple pages?

**Comment by malnajdi** [comment]
Can you provide an example html of the issue you are trying to solve ?

**Comment by liZe** [comment]
Hi!

If you want to be sure to have only one page, you can set `position: absolute` on the `html` tag.

If you need more specific information, you can provide an example as proposed above and reopen this issue!
