### ISSUE TITLE
Unable to call from Notebook

### ISSUE THREAD

**Issue by parthi2929** [Kozea/WeasyPrint#1228]
Hi

I followed the entire "windows installation" instructions [here](https://weasyprint.readthedocs.io/en/latest/install.html#windows). I also checked in command prompt and found that weasyprint is working (there were many warnings, but generated a pdf at last). 

#### This works (conda VE `dataviz`):
![image](https://user-images.githubusercontent.com/11896263/95431282-8f485e00-096a-11eb-8a69-3a107a97ca80.png)

However I could not import weasyprint from jupyter notebook. Notebook says its unable to find cairo. I have tried installing [pycairo ](https://anaconda.org/conda-forge/pycairo/) as well thinking that might help but ended up with a different error. 

#### Not working  (conda VE `dataviz` with pycairo):
![image](https://user-images.githubusercontent.com/11896263/95431642-21506680-096b-11eb-8a96-471c7c7beacf.png)

#### Not working (conda VE `root` wo pycairo)
I also installed weasyprint in root conda VE, and tried. Again command prompt works, but not in notebook. I get error as below (no pycairo in this root VE)

![image](https://user-images.githubusercontent.com/11896263/95431768-59f04000-096b-11eb-85fe-b86abaab4529.png)

This then looks like some sort of python dependent files still required to run weasyprint via  notebook? Kindly help as I am stuck here. 

#### Path Assurance

Just to be sure python calls the newly installed msys64, I moved it to highest position in path environment variables list, and still getting same above errors. 

![image](https://user-images.githubusercontent.com/11896263/95433172-3a5a1700-096d-11eb-9141-5eadcd53e83f.png)

**Comment by liZe** [comment]
Hello!

Jupyter is installed using Anaconda, and Anaconda overrides environment variables to avoid loading external libraries. You have to install Cairo using Anaconda, or to install Jupyter without Anaconda.
