### ISSUE TITLE
Problem with custom size in pages / naming divs

### ISSUE THREAD

**Issue by JustDevZero** [Kozea/WeasyPrint#1233]
Hi,

I need to specify some pages in a different size, I know it can be done, because I did it in the past, but I don't remember the proper syntax and it's not documented on the docs.

The standard size it's pretty logic and follows the same logic than in xhtmltopdf, but the custom one seems to not work like I remember, or maybe I'm missing something else.

Could you please, lend me a hand and tell me what I'm doing wrong?

Thanks.

The code now looks like this:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>random title</title>
        <style type="text/css">
            @page initial {
                size: 800px 800px;
            }
            @page landscape { size: A4 landscape; }
        </style>

    </head>

    <body>

        <div style="page:initial">
            <div class="header-info">
               <h2>Details</h2>
                Here will be detailts
            </div>
        </div>

        <div style="page:landscape">
            <div class="header-info">
               <h2>Details</h2>
                Here will be detailts
            </div>
        </div>
    </body>
</html>
```

**Comment by malnajdi** [comment]
@JustDevZero i think everything seems fine

![image](https://user-images.githubusercontent.com/15247545/95861436-1d0cba80-0d6a-11eb-921d-bad0e1c20e63.png)

Can you share the error with us ?

**Comment by grewn0uille** [comment]
Hi @JustDevZero!

`initial` is a keyword in CSS which re-init the value of a property. Using `initial` as the name of a page is like using an empty string. That’s why it works with potato :) 


@malnajdi the problem here is that the first page hasn’t the right size as define in the CSS (800x800)

**Comment by JustDevZero** [comment]
@grewn0uille Thanks for the answer, i guess it makes sense :+1: 

Consider it closed then.
