### ISSUE TITLE
Attachments missing using <link rel=attachment>

### ISSUE THREAD

**Issue by aufdenpunkt** [Kozea/WeasyPrint#1236]
Hi guys,

first I want to say thanks for this awesome tool!

I'm using Django, and I'm generating a pdf preview using the following class. This is working fine so far.

```python
class PDFRenderer:
    @staticmethod
    def render_to_response(path: str, params: dict):
        html = render_to_string(path, params)
        response = HTML(string=html)
        pdf = response.write_pdf()
        response = HttpResponse(content_type="application/pdf;")
        with tempfile.NamedTemporaryFile(delete=True) as output:
            output.write(pdf)
            output.flush()
            output = open(output.name, "rb")
            response.write(output.read())
        return response
```

The HTML head section is looks like the following code:

```html
<head>
  <meta charset="utf-8">
  <title>{% trans "proposal" %}: {{ proposal.proposal_number }}</title>
  {% for attachment in proposal.attachments.all %}
  <link rel=attachment href="file://{{ attachment.file.path }}">
  <!-- while "attachment.file.path" is the absolute path on the filesystem -->
  {% endfor %}
  {% compress css inline %}
  <link rel="stylesheet" href="{% static 'proposals/scss/pdf.scss' %}?{{ timestamp }}" type="text/x-scss">
  {% endcompress %}
  <!-- beautify ignore:start -->
  <style>@page { @bottom-center { content: {% trans "'Page ' counter(page) ' of ' counter(pages)"%} } }</style>
  <!-- beautify ignore:end -->
</head>
```

I assume that the available attachments (proposal.attachments.all) will be added as additional pages.

Let's say I have a document with one page and two attachments. Attachment 1 would become page 2, and attachment 2 would become page 3, and so on.

But this isn't the case and there are no attachments anywhere.

Is this a bug, or am I do something wrong?

**Comment by grewn0uille** [comment]
Hi @aufdenpunkt!

Attachments are files that are embedded in the PDF itself. It doesn’t add new pages.
You can see the list of the attachments in your PDF reader (on the left panel under the paperclip icon if you use Firefox or Evince).

**Comment by aufdenpunkt** [comment]
Oooh, okay, makes sense. Thanks for clarifying.
