### ISSUE TITLE
OSError: no library called "cairo" was found

### ISSUE THREAD

**Issue by fehernandez12** [Kozea/WeasyPrint#1240]
Before you call this a duplicate of #589, #721, #957, #1147, etc., I have tried all tips in the documentation and in those issues, I have not another GFK installed, both my Python and GFK versions are 64bit, the GFK directory is at the top of PATH variable and I have tried with both its regular path and its regular path with a slash "\\".

**Comment by malnajdi** [comment]
@fehernandez12 can you let us know:
os:
os version:
python version:
what is the output of `WHERE libcairo-2.dll`: 

Thanks

**Comment by liZe** [comment]
@fehernandez12 Can you give us more information about your problem?

**Comment by Aisha-Barahim** [comment]
> @fehernandez12 can you let us know:
> os:
> os version:
> python version:
> what is the output of `WHERE libcairo-2.dll`:
> 
> Thanks

Hi,
I am facing the same issue
os: windows 10
os version: 64 bit - x64-based-processer
Python version: Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
what is the output of `WHERE libcairo-2.dll`: C:\msys64\mingw64\bin\libcairo-2.dll
also I added  C:\msys64\mingw64\bin to path and I am still getting this error:
OSError: no library called "cairo" was found
cannot load library 'C:\msys64\mingw64\bin\libcairo-2.dll': error 0x7f
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7f

**Comment by Tontyna** [comment]
What is your command to run WeasyPrint? What shell? Or are you within an IDE? Calling WeasyPrint as part of another project?

**Comment by Aisha-Barahim** [comment]
solved using cmd instead of git bash

**Comment by liZe** [comment]
> solved using cmd instead of git bash

OK, thanks!

**Comment by Tontyna** [comment]
Yepp, special settings & paths in every IDE/shell other than the default `cmd`. They all try to be helpful :smirk:

**Comment by oneheath** [comment]
if faced such problem when using igraph, try to " pip install pycairo", instead of " pip install cairocffi".
