### ISSUE TITLE
Blank PDF, how to find what's the problem?

### ISSUE THREAD

**Issue by tonioo** [Kozea/WeasyPrint#1242]
I'm in a strange situation: I'm using weasyprint in a project to render an HTML page as a PDF file. It was working as expected but now (I don't know when the problem began exactly), when I render a new PDF I get a blank document but with some content (for example, the index is present in the document).
It might be linked to a dependency upgrade I didn't noticed but I'm wondering how I can debug such a situation?
Any help would be appreciated! :)

**Comment by liZe** [comment]
Hello!

> It might be linked to a dependency upgrade I didn't noticed but I'm wondering how I can debug such a situation?

You can at least try to downgrade Cairo and/or Pango, and see if it fixes your problem. Otherwise, we’ll have to find a way to debug this situation :/.

**Comment by tonioo** [comment]
@liZe Thanks for your answer. I'm on a Debian buster, using default system packages, and it looks like nothing changed on this side for a few months now...

**Comment by tonioo** [comment]
Using weasyprint from the command line (with the same virtual environment as my app) to render a page works as expected. So I guess this blank content has something to do with the CSS I use...

**Comment by tonioo** [comment]
@liZe I've finally found the issue and it was not on weasyprint's side! Sorry for the noise ;)
