### ISSUE TITLE
Difficulty including stylesheet in Django

### ISSUE THREAD

**Issue by yesyves** [Kozea/WeasyPrint#1244]
Hi

I just can't seem to get a stylesheet to load in WeasyPrint-51 / Django-3.1.

In template it is just ignored :
```
<link rel="stylesheet" href="{% static 'css/print.css' %}">
```

In view, it leads to errors (I tried the 4 combinations, w/o CSS and w/o leading /) :
```
html_pdf.write_pdf(target='/tmp/portfolio.pdf', stylesheets=['/static/css/print.css']);
[Errno 2] No such file or directory: '/static/css/print.css'

html_pdf.write_pdf(target='/tmp/portfolio.pdf', stylesheets=[CSS(filename='static/css/print.css')]);
[Errno 2] No such file or directory: 'static/css/print.css'
```

I work around the problem with inline styles in the template :
```
<style media="print">
  ...
</style>
```

Any help would be appreciated !

**Comment by liZe** [comment]
Hello!

If you want to use WeasyPrint with Django, you should consider using [Django-WeasyPrint](https://github.com/fdemmer/django-weasyprint). If you already do, or if you don’t want to, or if it doesn’t fix your problem, let me know!

**Comment by yesyves** [comment]
Hi

Thanks for the fast follow-up. I did not know about django-WeasyPrint and was quite curious to see how it could do better than out-of-the-box WeasyPrint with its 3 lines command !

Actually it does not help for this case, but I did find the solution I needed in their docs :

```html_pdf.write_pdf(target='/tmp/portfolio.pdf', stylesheets=[settings.STATIC_ROOT + '/css/pdf.css']);```

The stylesheet does not even have to be mentioned in the template !
