### ISSUE TITLE
@font-face src:url invalid value

### ISSUE THREAD

**Issue by carlosmauri** [Kozea/WeasyPrint#1246]
Hi there,

Since I have installed the latest release (v52) 2 days ago, I'm facing an issue that I've never had before when generating the PDF.

I could find a workaround but anyway I'd like to share the "bug" with you.

So I'm using several Adobe fonts and this CSS code does not work anymore:
```
@font-face {
font-family:"proxima-nova";
src:url("https://use.typekit.net/af/b683e3/00000000000000003b9b306c/27/a?primer=f592e0a4b9356877842506ce344308576437e4f677d7c9b78ca2162e6cad991a&fvd=n9&v=3") format("opentype");
font-display:block;font-style:normal;font-weight:900;
}
```
when generating the pdf these are the warning I'm getting:
```
WARNING: Ignored `src:url("https://use.typekit.net/af/b683e3/00000000000000003b9b306c/27/a?primer=f592e0a4b9356877842506ce344308576437e4f677d7c9b78ca2162e6cad991a&fvd=n9&v=3") format("opentype")` at 34:1, invalid value.
WARNING: Missing src descriptor in '@font-face' rule at 32:1
```

The workaround is to remove the double quotes from the url attribute which I never had to do this before :(
```
@font-face {
font-family:"proxima-nova";
src:url(https://use.typekit.net/af/b683e3/00000000000000003b9b306c/27/a?primer=f592e0a4b9356877842506ce344308576437e4f677d7c9b78ca2162e6cad991a&fvd=n9&v=3) format("opentype");
font-display:block;font-style:normal;font-weight:900;
}
```
With the code snippet above I don't get the warning meaning the pdf has the proper font in place.

Any ideas why this could be happening? 

My machine's configuration:
```
$ weasyprint -i
System: Linux
Machine: x86_64
Version: #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
Release: 4.15.0-45-generic

WeasyPrint version: 52
Python version: 3.6.9
Cairo version: 11510
Pango version: 14014
CairoSVG version: 2.5.0
```

Happy to provide more insights if needed.

I look forward to your feedback,
Thank you!

**Comment by grewn0uille** [comment]
Hi!

This is because of a change in the spec that has been included in the last tinycss2 release (see [here](https://github.com/Kozea/tinycss2/issues/33#issuecomment-719785175)).

This issue has been fix in master by https://github.com/Kozea/WeasyPrint/commit/238e214f9d58da51eed8f790fce34dc5fc1dc67f. You can try it and tell us if it works for you :) 

We’ll do a new release very soon to include this fix!

**Comment by carlosmauri** [comment]
Awesome! 
I'll test again as soon as the new release is available.

Thanks a lot for your quick update @grewn0uille

**Comment by liZe** [comment]
Fixed in 52.1.

**Comment by carlosmauri** [comment]
Hi guys, 
I just did a quick test so just confirming that the issue is not happening anymore.

Kudos to @grewn0uille and @liZe 🥇 
Thanks!

**Comment by kingraphaii** [comment]
I am on WeasyPrint version 62.2 and encountering this issue

**Comment by liZe** [comment]
> src: url("http://localhost:8009/assets/srd/fonts/calibril.ttf") !important format("truetype")

I think that this declaration is invalid, because of the "!important" in the middle. The spec says:

> If the rule accepts properties, the spec for the rule must define whether the properties interact with the cascade, and with what specificity. If they don’t interact with the cascade, properties containing !important are automatically invalid

As `@font-face` rules are not cascaded, I think that it’s invalid. Firefox also gives a warning equivalent to WeasyPrint.

**Comment by kingraphaii** [comment]
Ah yes, that turned out to be the culprit. Had a script that would append that as a workaround for wkhtmltopdf's print-media-type.

Thanks!
