### ISSUE TITLE
incomplete pypi tarballs: test_draw, test_layout missing

### ISSUE THREAD

**Issue by FelixSchwarz** [Kozea/WeasyPrint#1247]
`WeasyPrint-52.1.tar.gz` seems to be incomplete. `test_draw` and `test_layout` are not present in the pypi tarball leading to test failures.

**Comment by liZe** [comment]
Fixed by #1248.

**Comment by eli-schwartz** [comment]
Note that using `packages =  find:` is probably less fragile...
