### ISSUE TITLE
<a> tag links don't open in new tab

### ISSUE THREAD

**Issue by MauricioFa** [Kozea/WeasyPrint#1255]
I'm triyng the next code
`<a href="https://example.com/picture.png" target="_blank"></a>`
But picture doesn open in new tab

**Comment by liZe** [comment]
Hi!

I don’t know if it’s possible to specify this behavior in the PDF. If it’s possible, we could implement it, that’s an interesting feature to have.

**Comment by liZe** [comment]
Bad news: it’s actually not possible 😒, according to this [SO question](https://stackoverflow.com/questions/39762965/open-link-in-new-tab-from-pdf-file) and the Adobe forum page linked in its answer.

We didn’t find anything in the PDF specification either.
