### ISSUE TITLE
Table <td> element 'right' position is not supported

### ISSUE THREAD

**Issue by ildarworld** [Kozea/WeasyPrint#1256]
Hello,

I'm adding HTML table, and td element inside with class "last-in-row". Also, I have added CSS where I've mentioned following instruction: 
```
td.last-in-row {
  right: 40px;
}
```
If I will render HTML everything is OK and I see the changes in the last <td> element but in PDF nothing changes.

**Comment by liZe** [comment]
Hello!

The `right` property only applies to elements that don’t have `position: static`. That’s probably not your case. Did you want to use `padding-right` instead?
