### ISSUE TITLE
HTML embed tag for txt file / Multiple language support for PDF output

### ISSUE THREAD

**Issue by jbecker069** [Kozea/WeasyPrint#1260]
I am wondering if I got it right that `<embed>` only works with images as stated [here](https://weasyprint.readthedocs.io/en/stable/features.html):

>"`<img>`, `<embed>` or `<object>` elements accept images either in raster formats supported by GdkPixbuf (including PNG, JPEG, GIF, …) or in SVG with CairoSVG. SVG images are not rasterized but rendered as vectors in the PDF output."

I would like to be able to render a PDF report in different languages. So basically I would like to load txt-files in the HTML body from either one or another source based on the language the report should be in. 

```
<div class="some class">
    <embed src="static/text/en/text.txt">
</div>
```
Can someone help?

**Comment by liZe** [comment]
Hello!

I think that the best solution for your problem is to use a templating language like [Jinja2](https://jinja2docs.readthedocs.io/en/stable/): you’ll be able to include your text (or even HTML) in a clean way, depending on the language.
