### ISSUE TITLE
Custom style in first page

### ISSUE THREAD

**Issue by ktowen** [Kozea/WeasyPrint#1262]
Its possible to have a different style for the first page of a document?

```
<!DOCTYPE html>
<html>
    <head>
        <style>
            /* Something like this is possible? */
            @page :first header  {
                background-color: red;
            }

            /* Or this? */
            @page :first {
                header  {
                    background-color: red;
                }
            }

            @page {
                size: letter portrait;

                @top-left {
                    content: element(header-content);
                }

            }

            header {
                position: running(header-content);
            }

            .page-break {
                page-break-after: always;
            }

        </style>
    </head>
    <body>
        <header>
            <h1>Header text</h1>
        </header>

        Some text
        <div class="page-break"></div>
        More text

    </body>
</html>
```

**Comment by ktowen** [comment]
Also something like this could be possible? To declare a custom property inside `@page`

```
:root {
    --color: red;
}

@page :first  {
    --color: blue;
}

body {
    background: var(--color);
}
```

**Comment by pbregener** [comment]
Have you actually tried any of your own suggestions? Yes, it is possible. Below works just as expected:
```html
<style>
@page :first {background-color: green;}
@page {background-color: red;}
h1 {page-break-before: always;}
</style>

<h1>Page 1</h1>
Hello, world!

<h1>Page 2</h1>
Hello, world!

<h1>Page 3</h1>
Hello, world!
```

It also works using custom properties as you described.

**Comment by ktowen** [comment]
Hi @pbregener thanks for you response, what I am trying to do is to apply the style to an element (header)  only in the first page.

**Comment by liZe** [comment]
> Hi @pbregener thanks for you response, what I am trying to do is to apply the style to an element (header) only in the first page.

Hello!

I think that there’s no way to change the style of the elements drawn on the first page. [`@page` rules can only contain page properties](https://www.w3.org/TR/css-page-3/#syntax-page-selector), and properties defined there only apply to the page and the page margins, not to the page content.

In real cases, you often know what’s on your first page, and you can add classes accordingly (even if it’s not a "clean" solution, I agree). But there are some cases when you really want to change the style of the content only on the first page, and … currently you can’t.

Reporting an issue to the CSSWG may be the best solution to get a way to solve this issue.

**Comment by ktowen** [comment]
Thanks @liZe. I will try to report it.
