### ISSUE TITLE
Issues with multiprocessing in macOS

### ISSUE THREAD

**Issue by bryand23** [Kozea/WeasyPrint#1267]
I have a flask application that takes a POST request, then performs some expensive operations asynchronously with multiprocessing.

The very last step is making and printing a label, which I'm doing with [blabel](https://pypi.org/project/blabel/) which uses Weasyprint to write a pdf.

```
worker = Process(target=async_tasks, daemon=True, args=(data,))
worker.start()
```
async_tasks does a handful of things, but it trips up when it comes time to make the pdf.

the snippet from blabel that gets called:

```
from weasyprint import HTML
...
weasy_html = HTML(string=html, base_url=base_url)
weasy_html.write_pdf(target, stylesheets=extra_stylesheets)
```

When I first fire up apache, it works fine. But after it's been running for a while, I see this:

```
App 83947 output: [ pid=25930, time=2020-12-11 14:39:24,343 ]: Step 2 - Fetching and parsing CSS - CSS string
App 83947 output: [ pid=25930, time=2020-12-11 14:39:24,353 ]: Step 2 - Fetching and parsing CSS - CSS string
App 83947 output: [ pid=25930, time=2020-12-11 14:39:24,354 ]: Step 3 - Applying CSS
App 83947 output: [ pid=25930, time=2020-12-11 14:39:24,357 ]: Step 4 - Creating formatting structure
App 83947 output: [ pid=25930, time=2020-12-11 14:39:24,366 ]: Step 5 - Creating layout - Page 1
App 83947 output: The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
App 83947 output: Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
```

If I restart apache, everything is fine again. My initial googling on the error suggested that it was due to using the mp.start_method('fork'), but the issue persists even after switching to spawn. This is on macOS 10.15.7, Python 3.7.9

Something in Step 5 is problematic - I'm relatively new to concurrency, so I'm not sure where to go from here.

**Comment by liZe** [comment]
Hi!

Your problem really, really looks like the error caused by the multiprocess start method. As it’s been fixed in Python 3.8, upgrading Python may be the easiest solution to be sure that it’s the source of the problem (and to fix it).

Otherwise, you have to be __sure__ that `set_start_method('spawn')` is called before `multiprocessing` is used, as explained in [the documentation](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods).

**Comment by bryand23** [comment]
Thanks for the reply! I'm absolutely setting the start method as spawn. My understanding is that the fix in 3.8 simply changes the default behavior in macOS. Also, if my start_method were the problem, shouldn't I expect to see this error as soon as the function is called and the fork happens?

That's what I thought was happening initially, it was after changing the start method to spawn (without solving the problem) that I started trying to narrow down specifically where I was getting the error. Then I learned that none of my other functions (calling other APIs, reading and writing some JSON files, etc.) failed to execute, it's always this particular step.

```
if __name__ == '__main__':
    mp.set_start_method('spawn')
    app.run(debug=True)
```

The fact that it works fine after restarting the app/apache makes me think zombie processes? Clearly the module works with multiprocessing... until it doesn't :)

**Comment by liZe** [comment]
> if __name__ == '__main__':
>     mp.set_start_method('spawn')
>     app.run(debug=True)

Oh, that’s where your problem comes from: this code is not executed when your program is used by Apache :wink:. You have to put the `mp.set_start_method('spawn')` line at the beginning of your file, for example.

**Comment by bryand23** [comment]
Oh, wow. I'm going to be super frustrated/relieved if it was that simple :)

Just edited and restarted, the error usually crops up after a day or so. I'll test it over the weekend. Thanks!

**Comment by bryand23** [comment]
Ok, so I added the start method to the beginning of the file (immediately after my import statements) and I'm getting this:

```
App 96953 output: Traceback (most recent call last):
App 96953 output:   File "<string>", line 1, in <module>
App 96953 output:   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
App 96953 output:     exitcode = _main(fd)
App 96953 output:   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
App 96953 output:     self = reduction.pickle.load(from_parent)
App 96953 output:   File "/private/var/www/myapp/src/app.py", line 27, in <module>
App 96953 output:     mp.set_start_method('spawn')
App 96953 output:   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 242, in set_start_method
App 96953 output:     raise RuntimeError('context has already been set')
App 96953 output: RuntimeError: context has already been set
```

Googling the error suggests adding the start_method after `if __name__ == '__main__'`, but we've already established that's no good here :)

I'm going to try the force=True kwarg, unless you have a better suggestion @liZe

**Comment by liZe** [comment]
> Googling the error suggests adding the start_method after `if __name__ == '__main__'`, but we've already established that's no good here :)

Code after `if __name__ == '__main__'` is only executed when the script is launched directly. Web servers generally import the module, don’t execute it (you don’t want to launch `app.run(debug=True)` in production, right 😉).

> I'm going to try the force=True kwarg, unless you have a better suggestion @liZe

A better solution: use Python 3.8+ if you can!

You can try `debug=True`, I hope that it will work.

If you get this error, it probably means that `set_start_method` has alerady set, probably by the web framework you use. Maybe your framework gives an option to change the default value.

> Edit: Actually, I'm going to try spawner = mp.set_context('spawn'), and create my worker with spawner.Process

Looks like a pretty clean solution.

**Comment by liZe** [comment]
@bryand23 Can I close this issue?

**Comment by bryand23** [comment]
Yes, thanks for your help!
