### ISSUE TITLE
css counter not incremented properly

### ISSUE THREAD

**Issue by SilverGeri** [Kozea/WeasyPrint#1269]
Hi, probably something similar as #1250 (thanks for the fix btw), actually same example applies.
In my example I'd like to add the id of the the page that contains my table on multiple page but the section counter is not increased. (also, I'd like to add the maximum number that's reached by the counter to display something like "1/4 attachment for der <order id>" but as far as I know it's not part of the standard yet)

~~~
        body {
            font-size: 11px;
            counter-reset: section;
        }

        h2::before {
            counter-increment: section;
            content: counter(section) ": ";
        }
~~~

~~~
<div style="page-break-before: always">
    <table>
        <thead>
            <tr>
                <td colspan="5">
                    <h2>attachment for order #{{ order.id }}</h2>
                </td>
            </tr>
            <tr>
                <th>id.</th>
                <th>productname</th>
                <th>price</th>
                <th>quantity</th>
                <th>sum</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ product.name }}</td>
                <td>{{ product.gross_price|floatformat:0 }}&nbsp;Ft</td>
                <td>{{ product.quantity }}&nbsp;{{ item.product.unit }}</td>
                <td>{{ product.total_price|floatformat:0 }}&nbsp;Ft</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="4">Sum</td>
                <td>{{ products_total_price|floatformat:0 }}&nbsp;Ft</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td class="footer" colspan="5">
                    <div class="footer-wrapper">
                        <span>
                            ........................................<br>
                            {{ name }}
                        </span>
                    </div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
~~~

**Comment by liZe** [comment]
Hello!

Some users complain when repeated headers are really independent boxes (see #138), and some complain when they are actually seen as one box repeated (as in this issue) :smile:.

For both cases, the specification is not clear enough. The W3C knows that the way table headers and footers are repeated should be defined more precisely (because [the CSS Print Community Group discussed about that](https://lists.w3.org/Archives/Public/public-cssprint/2020May/0000.html)), but there’s nothing official yet.

I think that this issue should be reported to [the CSSWG](https://github.com/w3c/csswg-drafts/), and that WeasyPrint will follow what’s in the specification. Until then, the rule is simple: if there’s no spec, there’s no bug :wink:.

**Comment by SilverGeri** [comment]
> Hello!
> 
> Some users complain when repeated headers are really independent boxes (see #138), and some complain when they are actually seen as one box repeated (as in this issue) .
> 
> For both cases, the specification is not clear enough. The W3C knows that the way table headers and footers are repeated should be defined more precisely (because [the CSS Print Community Group discussed about that](https://lists.w3.org/Archives/Public/public-cssprint/2020May/0000.html)), but there’s nothing official yet.
> 
> I think that this issue should be reported to [the CSSWG](https://github.com/w3c/csswg-drafts/), and that WeasyPrint will follow what’s in the specification. Until then, the rule is simple: if there’s no spec, there’s no bug .

okok, thanks. For now I'll just steal your quote: "if there’s no spec, there’s no bug", I love it :D
