### ISSUE TITLE
Adding other PDFs into output

### ISSUE THREAD

**Issue by wangkev** [Kozea/WeasyPrint#1271]
Is it possible to add other pdfs directly into a `weasyprint` output pdf? Basically interested in something like:

Output PDF document:
- weasyprint page 1
- weasyprint page 2
- other pdf page 1
- other pdf page 2
- weasyprint page 5
- ...

I think there was past discussion https://github.com/Kozea/WeasyPrint/issues/52, but not sure if it is exactly the same issue (and where it stands given the migration to `pydyf`).

My current solution is to leverage `PyPDF2`, but the links within the document break after merging the document (open issue https://github.com/mstamy2/PyPDF2/issues/471).

**Comment by liZe** [comment]
Hi!

WeasyPrint doesn’t offer the possibility to include other PDFs. Rendering HTML and CSS is already a big challenge, we’ve just [added the PDF generation part to this challenge](https://www.courtbouillon.org/pydyf), I think that’s difficult enough :wink:!

Using third-party libraries as you do is probably the best solution for now. Is that OK for you?

**Comment by wangkev** [comment]
Thanks for the reply!

Utilizing `PyPDF2` is fine, but a bit of a roundabout solution as I have to generate dummy pages to be replaced (to ensure page numbers are correct), and would be ideal to have the links work. Unfortunately, I am not super familiar with the inner workings of PDF, so not really sure why the links would break in the first place.

Naively, looking through the code, it seems like new pages are added here: https://github.com/Kozea/WeasyPrint/blob/8fc505afdb1a51ccedc9fda2d9df0651f020c12f/weasyprint/document.py#L1014

If I wanted to hack together a more `pydyf`/`weasyprint` solution, would it be possible to just inject the pages from the other PDF there?

**Comment by liZe** [comment]
> not really sure why the links would break in the first place.

I can’t really tell, it depends on how you use PyPDF2. The PyPDF2 team knows much more about PDF than we do!

> If I wanted to hack together a more `pydyf`/`weasyprint` solution, would it be possible to just inject the pages from the other PDF there?

As far as I know, there’s no easy way to add pages from one PDF to another. PDFs contain "objects", and copying a page means that you also have to copy the objects it contains. As these objects can reference other objects, you actually have to do this recursively.

Moreover, pydyf only generates PDF files, it’s totally unable to read them. So… **Use PyPDF2.** pydyf can’t help you for what you want to do.

**Comment by wangkev** [comment]
Understood -- appreciate the clarification. Would there be any possibility so support this in the future, or should I close this issue?

**Comment by liZe** [comment]
> Would there be any possibility so support this in the future, or should I close this issue?

I don’t think that this feature will ever be included in WeasyPrint, it’s too complicated and out of the scope. Sorry 😒.

**Comment by dmkallan** [comment]
Very much in search of the exact same capability: use some sort of HTML tag or CSS property to include pages from external PDFs inline.

**Comment by ericbf** [comment]
> Utilizing `PyPDF2` is fine, but a bit of a roundabout solution as I have to generate dummy pages to be replaced (to ensure page numbers are correct)

Can you elaborate on this workaround? I am wanting to get page numbers working when appending PDFs, and have no links to break in my docs.
