### ISSUE TITLE
Installing weasyprint breaks matplotlib in virtual environment

### ISSUE THREAD

**Issue by oconnelljon** [Kozea/WeasyPrint#1272]
Hey all,

I've never used weasyprint before but was handed some code that used it and ran into the infamous error
Exception has occurred: OSError
no library called "cairo" was found
no library called "libcairo-2" was found etc...

I'm also a new programmer, so this may not be a real problem and may be just me...

I do not have admin rights on my laptop so I work out of my user directory and I can't manage my system path variables or install GTK or anything like that.  Those things may have fixed my issue, but I didn't want to wait for IT and have to explain all that.

How to replicate my problem:
I create a virtual environment in VS Code using my python 3.9.1 64 bit installation in my appdata directory (not installed for all users!)
`python -m venv C:\Users\myname\.envs\matplotlib_venv `

Create a project folder and a simple script .py file like
```python
import matplotlib.pyplot as plt

x = [1,2,3,4]
y = [2,4,5,6]

plt.scatter(x,y)
plt.show()
```

In VS Code terminal, cmd, go to the virtual environment with:  "cd c:\users\myname\workspace\venv\test\scripts" 
From there do pip install matplotlib
In VS Code make sure the interpreter is set to the test virtual environment and run the script.  Should turn out fine.
Now in cmd do pip install weaslyprint

That brings up my error.  I dug into matplotlib and found it can use cairocffi OR pycairo in their matplotlib.backends.backend_cairo module like so:
```python
try:
    import cairo
    if cairo.version_info < (1, 11, 0):
        # Introduced create_for_data for Py3.
        raise ImportError
except ImportError:
    try:
        import cairocffi as cairo
    except ImportError as err:
        raise ImportError(
            "cairo backend requires that pycairo>=1.11.0 or cairocffi"
            "is installed") from err
```

So to solve this I did pip install pycairo and matplotlib went back to normal.

Broken pip list:
(base) C:\Users\myname\.envs\matplotlib_venv\Scripts>pip list
Package         Version
--------------- -------
cairocffi       1.2.0
CairoSVG        2.5.0
cffi            1.14.4
cssselect2      0.4.1
cycler          0.10.0
defusedxml      0.6.0
html5lib        1.1
kiwisolver      1.3.1
matplotlib      3.3.3
numpy           1.19.4
Pillow          8.0.1
pip             20.2.3
pycparser       2.20
pyparsing       2.4.7
Pyphen          0.10.0
python-dateutil 2.8.1
setuptools      49.2.1
six             1.15.0
tinycss2        1.1.0
WeasyPrint      52.2
webencodings    0.5.1

Working pip list with pycairo
(base) C:\Users\myname\.envs\matplotlib_venv\Scripts>pip list
Package         Version
--------------- -------
cairocffi       1.2.0
CairoSVG        2.5.0
cffi            1.14.4
cssselect2      0.4.1
cycler          0.10.0
defusedxml      0.6.0
html5lib        1.1
kiwisolver      1.3.1
matplotlib      3.3.3
numpy           1.19.4
Pillow          8.0.1
pip             20.2.3
pycairo         1.20.0
pycparser       2.20
pyparsing       2.4.7
Pyphen          0.10.0
python-dateutil 2.8.1
setuptools      49.2.1
six             1.15.0
tinycss2        1.1.0
WeasyPrint      52.2
webencodings    0.5.1

I'm not sure if this is how things are supposed to behave, but this was a real B to figure out.  And I can't figure out how to post code correctly...

**Comment by liZe** [comment]
Hello!

Installing WeasyPrint requires you to carefully follow [the instructions](https://weasyprint.readthedocs.io/en/stable/install.html#windows). Here, Cairo is not in your `PATH` for some reason.

Of course, having `cairocffi` not working breaks libraries that can use it. If you can’t change the `PATH` (I think you can even if you’re not an admin, but I don’t use Windows, I may be wrong), then there’s no easy way you can use `cairocffi` yet.

**Comment by oconnelljon** [comment]
To not run into other package issues I'll put in a support ticket to get the libraries installed and PATHs added.  The problem I've ran into in the past is I can't install updates to programs on the C drive which is why I'm living out of my windows user folder.  So if GTK needs an update, that is hard to pull off.  And if I share my code with another user at my job they may not have the libraries either then they have to go through IT.  At least I found this kind of work around in the meantime.

I did try adding PATHS through command prompt and no go :(

**Comment by Tontyna** [comment]
If you cannot run the "GTK Runtime installer" because it requires admin privileges you can download the ZIPped repository from https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer and unpack it into a writable folder of your choice, e.g. in your appdata. 
There will be a `bin` subfolder and that's your GTK_PATH.

AFAIK regular users can't modify the **system** PATH but there is a **user** PATH, too.

If you SET PATH through command prompt the modified PATHs are available in that same command prompt, they won't be available anywhere else and won't persist. And of course, the VS Code terminal has its own environment. But there should be a place in VS Code where you can modify the PATH it uses.

Instead of modifying the PATH environment variable you can modify Python's `os.environ['PATH']` before you import modules that wanna use cairo/GTK, e.g.:

```python
import os

# make GTK available to Python
GTK_PATH = r"C:\path\to\unzipped\gtk\bin"
os.environ['PATH'] =  GTK_PATH + os.pathsep + os.environ.get('PATH','')

# now you can import modules that require the GTK
import matplotlib.pyplot as plt
import weasyprint

```

**Comment by oconnelljon** [comment]
Thank you!  That is very helpful and worked first try!  I didn't think about trying to modify pythons environment but it works great!
