### ISSUE TITLE
segmentation fault:11

### ISSUE THREAD

**Issue by chul0717** [Kozea/WeasyPrint#1273]
Hi, I am having trouble trying to get WeasyPrint to work.
The current code I am trying to run is:
```python
from weasyprint import HTML

html = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weekly Report</title>
</head>

<body>
    <h2>dataframe </h2>

</body>
</html>
"""

HTML(string=html).write_pdf("output.pdf")

```
When I run this python script it get the following error:

>/Users/ckim/opt/anaconda3/lib/python3.7/site-packages/weasyprint/document.py:36: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
Segmentation fault: 11

I am currently using python 3.7.6 on MacOS Big Sur (version 11.1)

This is my first time trying to use WeasyPrint and I have no idea what Segmentation fault:11 means and where to go from here. Please let me know if you need any more information. 

Thank you in advance!

**Comment by liZe** [comment]
Hi!

Other people [complain about segmentation faults with Python](https://stackoverflow.com/questions/64841082/segmentation-fault-11-python-after-upgrading-to-os-big-sur) after upgrading macOS to Big Sur.

I hope that reinstalling `cairocffi` will fix your problem.

**Comment by chul0717** [comment]
I have reinstalled just the cairocffi package and got the same error. I then tried to reinstall the whole weasyprint package but had no luck. 
I pip installed weasyprint after I had already updated to Big Sur and it was my first time trying to use the package. Is there anything else that I can do?

**Comment by liZe** [comment]
There are lots of reports like yours, you’re not alone… The solution everyone finds is to reinstall random packages until it works 😒. I see that you use Anaconda, you can try to reinstall the usual suspects: cairo, pango, freetype, fontconfig, libpng, and virtually all the packages WeasyPrint installs.

**Comment by chul0717** [comment]
Thanks for getting back to me. I actually found a workaround and works great now! 
I had a bunch of packages installed on my base conda environment and I was guessing that one of them was conflicting with WeasyPrint. Just to be safe I made a new clean conda environment and started to reinstall only the packages I need, including WeasyPrint. Now it works fine!

**Comment by liZe** [comment]
> Thanks for getting back to me. I actually found a workaround and works great now!
> I had a bunch of packages installed on my base conda environment and I was guessing that one of them was conflicting with WeasyPrint. Just to be safe I made a new clean conda environment and started to reinstall only the packages I need, including WeasyPrint. Now it works fine!

😄
