### ISSUE TITLE
segfault when running tests with pytest and when html contains relative path to CSS file

### ISSUE THREAD

**Issue by toudi** [Kozea/WeasyPrint#1274]
hello

I was tracking down a bug that caused me much grief. The worst thing about it was that it was only reproducible on CI build (I wasn't able to reproduce it locally). What made the matter worse is the fact that the unit test actually passed and then pytest (after displaying the confirmation - i.e. 100% pass) would simply segfault with a dumped core.

anyhow, this was a very painful debugging process but in the end I was able to narrow it down to a single unit test which (under the hood) executed weasyprint with this simplified code:

```
  rendered_html = get_template(template_name).render(
      context=self.get_context_data()
  )

  pdf_file = ContentFile(
      HTML(string=rendered_html, base_url=settings.STATIC_ROOT).write_pdf()
  )

```
the crucial part of the problem was the html template, which, among other things had a reference to CSS like so:

```
<head>
  <link href="relative-path-to-css-file.css" rel="stylesheet" />
</head>

```

again, I want to stress out that everythig was fine with the tests and everything was fine locally. moreover, everything was fine on the CI runner up until 5 days ago when the build would start to segfault just after displaying this 100% report. I tried strace, that didn't get me far, I've tried inspecting the core dump file but I was only able to see some references to cffi calls but again without any success (no debugging symbols). I cannot remember how, but somehow I was able to see some messages about inability to open the file (maybe it was with pytest -vvv ? I honestly cannot remember, I've been staring at the screen for the past several hours now). anyhow to cut long story short here's how I fixed the problem:

```
    pdf_file = ContentFile(
        HTML(string=rendered_html, base_url=settings.STATIC_ROOT).write_pdf(
            stylesheets=[
                CSS(
                    settings.STATIC_ROOT + "relative-path-to-css-file.css"
                )
            ]
        )
    )

```

and now there's no segfault. Could you look into this ? maybe there's something like a close operation on the file or something ? the version of weasyprint was first 51 and then I upgraded it to 52.2 but the problem was still reproducible.

kindest regards

**Comment by liZe** [comment]
That’s a strange bug, for sure.

> I cannot remember how, but somehow I was able to see some messages about inability to open the file (maybe it was with pytest -vvv ? I honestly cannot remember, I've been staring at the screen for the past several hours now).

Without this information, it’s hard for me to tell what’s really happening. But…

Having a crash (and not a simple Python exception) means that there’s probably something wrong with low-level libraries. Finding something related to CFFI with strace isn’t a big surprise. Having a bug in Python is unlikely.

I honestly don’t know what could cause such an error. You can try to find what changed on your CI environment (I can even help if it’s a public CI service with some kind of changelog).

Do you use `@font-face` rules? I’ve already met similar errors with fonts before.

**Comment by toudi** [comment]
I am not using `@font-face`.  The css `<link href` is the only link to any CSS in the file (it has a relative path, not an absolute one) and the only thing that caused the segfault to appear. I think that the reason that I haven't seen the problem locally is that I had run `./manage.py collectstatic` locally prior to running the tests. As you can see, it really boils down to the fact that weasyprint cannot find the CSS file in question rather that it cannot interpret it's contents.

what solved the segfault from appearing was 1) running collectstatic on the CI prior to running the tests and 2) adding CSS=... rule to the weasyprint invocation. Although now that I think of it, I don't think that adding CSS= ... has anything to do with it, rather, running collectstatic should solve it because then weasyprint would be able to locate the file. I'll try to experiment and get back to you

**Comment by toudi** [comment]
ok I was just able to verify this - stylesheets parameter in the call has nothing to do with the fix - all it takes is running collectstatic prior to executing pytest. Now don't get me wrong - I totally understand that the problem is on my end (having forgot to collect the static files) but the segfault is what caught me off-guard. Had this would be an error message or a warning or log entry - it would be easier for me to fix it.

**Comment by liZe** [comment]
> Had this would be an error message or a warning or log entry - it would be easier for me to fix it.

Having a segfault is definitely a bad thing, but I’m not sure that it’s really a problem in WeasyPrint.

I don’t think that CFFI modules directly deal with files (except from fontconfig for `@font-face` rules, but you don’t use them). So, if we get a segfault while reading CSS files, it’s a problem in Python or in Pytest, not in WeasyPrint: we only use standard Python to open stylesheets.

Without a real trace, there’s no easy way to know what’s going on. Unless you find a way to find where exactly Pytest or WeasyPrint crashes, we’re stuck 😒.

One more question: do you use coverage, or other third-party Pytest plugins? You should try without them.

**Comment by toudi** [comment]
yes, initially I thought that this was due to coverage and I excluded it from the test scenario. I was then able to reproduce the segfault with just pytest, then I started to cut down strip tests (i.e. I was executing them manually) and in the end I was able to pinpoint it to a single unit test that executed weasyprint under the hood. I also do not think that this is a problem in pytest as pytest version was frozen in requirements and it was always the same. (weasyprint was also frozen in requirements which makes it even stranger - I also doubt that it's a problem in weasyprint per se). I also tried to obtain a proper stacktrace but I was very unsuccesful in doing that - I had a problem of producing a debug build of python that would also contain all of the requirements.

It is possible that what *did* change was the underlying testing image for python 3.7. as far as I'm aware it uses debian buster under the hood and this was not pinned to any particular release - just the head of 3.7 branch so it is possible that the container changed.

does it mean that the parsing of html (in order to load css files) is not done by weasyprint itself but rather by something else? because it cannot be a coincidence that when I made sure that the file existed then the segfault was fixed

**Comment by liZe** [comment]
> does it mean that the parsing of html (in order to load css files) is not done by weasyprint itself but rather by something else? because it cannot be a coincidence that when I made sure that the file existed then the segfault was fixed

HTML is parsed by html5lib, and CSS is parsed by tinycss2. These libraries are pure Python, I don’t know how they could raise a segmentation fault without a bug in Python.

**Comment by liZe** [comment]
@toudi Do you have more information about this issue? Without a traceback, I’ll assume that it’s a bug in Python and shamelessly close this issue :wink:.

**Comment by toudi** [comment]
@liZe I think you can close this. After all, my only explanation would also be that this must be something in the python interpreter as the problems only started on a particular day when the CI service updated their base images for python. maybe when somebody will find this issue they will at least know that a possible cause is a nonexistent static file :-)

**Comment by liZe** [comment]
> maybe when somebody will find this issue they will at least know that a possible cause is a nonexistent static file :-)

😄
