### ISSUE TITLE
Different line spacing with <sup>

### ISSUE THREAD

**Issue by fabiobatalha** [Kozea/WeasyPrint#1280]
I'm having different line spacing if the line as a ``sup``.

On the left the PDF generated with WeasyPrint, on the right the HTML used to generate de PDF.

![Screenshot from 2021-01-07 11-57-10](https://user-images.githubusercontent.com/504142/103928012-3ca54c00-50e9-11eb-8ca6-f0590f7585bc.png)
 
Has anybody any idea to solve this issue?

**Comment by liZe** [comment]
Hello!

Line height depends on inline elements in the line. With a `<sup>` tag, it’s possible that the line height has to be increased to make the tag fit.

Having different renderings for different browsers is normal, because the default values for `font-size` and `vertical-align` may differ for the `sup` tag (ie it’s not a bug in WeasyPrint). You can change the values of these attributes (and `line-height`) until it fits.

**Comment by fabiobatalha** [comment]
Sorry @liZe 

I found another example that contradicts the idea that the line height has to be increased.

In this example, using the same CSS we have a lot of available space for the ``sup`` content, even though, we can see a huge space between lines.

image left: WeasyPrint
image right: html in Firefox

![Screenshot from 2021-01-07 16-15-35](https://user-images.githubusercontent.com/504142/103946016-13de8000-5104-11eb-9766-e47afe92b65f.png)

**Comment by liZe** [comment]
The line height is increased on Firefox too, even if we have the impression that we have plenty of space. Could you share the source of your example, so that we can find the reason why?

**Comment by fabiobatalha** [comment]
Hello @liZe 

I finally found a way to workaround this issue including this in the CSS:

``` css
sup, sub {
     border: solid 1px;
     vertical-align: baseline;
    position: relative;
    top: -0.4em;
}
sub {
    top: 0.4em;
}
```

Results before de workaround:

![Screenshot from 2021-01-08 10-37-18](https://user-images.githubusercontent.com/504142/104033979-4937ac00-519e-11eb-84e4-651ffa7c8e2f.png)

Results after the workaround:

![Screenshot from 2021-01-08 10-37-51](https://user-images.githubusercontent.com/504142/104033944-39b86300-519e-11eb-99bc-ed59152da488.png)

For record purpose, here is the html sample:

``` html
<!DOCTYPE html>
<html xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mml="http://www.w3.org/1998/Math/MathML">
    <head>
        <title>Communiquer: La culture en tant que cultivation : vers une conception communicationnelle de la culture organisationnelle</title>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <style>

            .article .title-group .article-title {
                text-align:left;
                font-size:28px;
                color: #000;
            }

            .xref {
              font-size: 8px;
              color: #000;
            }

            sup, sub {
                border: solid 1px;
                vertical-align: baseline;
                position: relative;
                top: -0.4em;
            }

            sub {
                top: 0.4em;
            }
        </style>
    </head>
    <body>
        <div class="document">
            <div class="article">
                <div class="front">
                    <div class="title-group">
                        <div class="article-title">La culture en tant que cultivation : vers une conception communicationnelle de la culture organisationnelle<sup><a href="#no1" id="relno1" class="xref">1</a></sup></div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
```
