### ISSUE TITLE
Need some help. All the number in my pdf is blur

### ISSUE THREAD

**Issue by hong-duc** [Kozea/WeasyPrint#1282]
Here is my pdf, as you can see the all the number in my pdf is blur
![Screenshot_20210108_140352](https://user-images.githubusercontent.com/12032550/103985251-2c5da180-51bb-11eb-9862-d94bc3dbb26c.png)

Here is the above part in html
![Screenshot_20210108_140434](https://user-images.githubusercontent.com/12032550/103985410-78104b00-51bb-11eb-83b7-62ab4c19de31.png)

WeasyPrint: version 52.2
The command I use: `weasyprint -e utf8 -p -dv Domain\ Driven\ Design\ eac34892855a4238afc9056888a3d230.html DDD_3.pdf`

Thank you

**Comment by grewn0uille** [comment]
Hello!
The numbers are blur because an emoji font is used. Please see https://github.com/Kozea/WeasyPrint/issues/311#issuecomment-658124933

**Comment by hong-duc** [comment]
@grewn0uille Ah I see thank you, I just remove all font in CSS and generate again and it work normal
