### ISSUE TITLE
I followed the installation as it is in the docs. but got this error

### ISSUE THREAD

**Issue by sohamsjain** [Kozea/WeasyPrint#1286]
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:1686.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:1863.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:2040.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:2141.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:2242.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:2304.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:2367.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:2574.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:2782.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:2843.
WARNING: Ignored `width:100vw` at 1:3795, invalid value.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:4335.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:5559.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:6585.
WARNING: Ignored `overflow-x:hidden` at 1:6712, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:7421.
WARNING: Ignored `width:-moz-min-content` at 1:7652, invalid value.
WARNING: Ignored `width:-webkit-min-content` at 1:7675, invalid value.
WARNING: Ignored `width:min-content` at 1:7701, invalid value.
WARNING: Ignored `min-height:60vh` at 1:8072, invalid value.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:8441.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:9331.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:9528.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:9713.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:10036.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:10393.
WARNING: Ignored `box-shadow:0 0 0 .01em #1ee494` at 1:10702, unknown property.
WARNING: Ignored `box-shadow:0 0 0 .65em #19d489` at 1:11162, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:11297.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:11400.
WARNING: Ignored `background-position-y:0` at 1:11986, unknown property.
WARNING: Ignored `left:calc(-.8em - .35em / 2)` at 1:12201, invalid value.
WARNING: Ignored `background-position-y:100%` at 1:12526, unknown property.
WARNING: Ignored `max-width:calc(100% + 45px * 2 + 2px)` at 1:12778, invalid value.
WARNING: Ignored `box-shadow:0 1px 0` at 1:12905, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:14267.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:14713.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:14805.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:15475.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:15586.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:16755.
WARNING: Ignored `box-shadow:0 5px 5px 0 rgba(111,122,137,0.3)` at 1:17986, unknown property.
WARNING: Ignored `box-shadow:0 0 0 0 #e2e4e8` at 1:18090, unknown property.
WARNING: Ignored `background-position-x:0` at 1:18533, unknown property.
WARNING: Ignored `box-shadow:0 5px 5px 0 rgba(111,122,137,0.1)` at 1:19035, unknown property.
WARNING: Ignored `background-position-x:0` at 1:19870, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:19939.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:20047.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:21239.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:21432.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:21656.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:22331.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 831px)
WARNING: Invalid media type " screen and (min-width: 831px)" the whole @media rule was ignored at 1:26061.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 830px)
WARNING: Invalid media type " screen and (max-width: 830px)" the whole @media rule was ignored at 1:26276.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:29200.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:30333.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:30461.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:30620.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 581px)
WARNING: Invalid media type " screen and (min-width: 581px)" the whole @media rule was ignored at 1:30721.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:31681.
WARNING: Ignored `background-position-y:100%` at 1:32173, unknown property.
WARNING: Ignored `vertical-align:center` at 1:32414, invalid value.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 580px)
WARNING: Invalid media type " screen and (max-width: 580px)" the whole @media rule was ignored at 1:32773.
WARNING: Expected a media type, got screen/**/and/**/(min-width: 831px)
WARNING: Invalid media type " screen and (min-width: 831px)" the whole @media rule was ignored at 1:33286.
ERROR: Failed to load stylesheet at https://weasyprint.org/css/print.css : timeout: The read operation timed out
ERROR: No anchor # for internal URI reference

**Comment by liZe** [comment]
Hello!

Don’t worry, it’s normal :smile:.

Most these messages are only warnings, because of unknown CSS rules. Even the errors are not fatal, and shouldn’t prevent a document from being generated.

> ERROR: Failed to load stylesheet at https://weasyprint.org/css/print.css : timeout: The read operation timed out

This error is probably caused by a network problem on your computer. The URL is public and works, it shouldn’t be a problem t download it.

> ERROR: No anchor # for internal URI reference

It’s a problem in the HTML file, I don’t get it when I render `https://weasyprint.org`, so maybe it’s also caused by the problem on your network configuration.

**Comment by liZe** [comment]
Feel free to reopen if we can do anything more for you!

**Comment by FinnGu** [comment]
Was this warning resolved at some point? Normally it wouldn't bother me, but we use a logging service and this eats up our usage quota very quickly 😅

**Comment by liZe** [comment]
> Was this warning resolved at some point? Normally it wouldn't bother me, but we use a logging service and this eats up our usage quota very quickly

Hi!

You can disable warnings and only keep errors to avoid that 😁, logs can be configured [as explained in the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#logging).

There’s nothing to "solve": these are warnings, not errors. They are logged when CSS properties or values are unknown, either because there’s an error in your stylesheet or because it’s not supported yet in WeasyPrint. Other browsers do the same in the dev console.

**Comment by FinnGu** [comment]
> > Was this warning resolved at some point? Normally it wouldn't bother me, but we use a logging service and this eats up our usage quota very quickly
> 
> Hi!
> 
> You can disable warnings and only keep errors to avoid that 😁, logs can be configured [as explained in the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#logging).
> 
> There’s nothing to "solve": these are warnings, not errors. They are logged when CSS properties or values are unknown, either because there’s an error in your stylesheet or because it’s not supported yet in WeasyPrint. Other browsers do the same in the dev console.

Thank you for the explanation and also the pointer! I have now disabled warnings for my production environment, but kept them for local development in my django project.

```
# settings.py
if not DEBUG:
    warnings.filterwarnings('ignore', module='weasyprint')
```
