### ISSUE TITLE
Border for table not showing at the bottom of first page or top of second page

### ISSUE THREAD

**Issue by maddiestigler** [Kozea/WeasyPrint#1289]
Hi team,

We are trying to create a pdf where a table with a border continues across pages.  We expect the border to remain on all four sides regardless of the page split.  However, we are seeing the bottom border disappear as it splits across the bottom and the top border disappear as it splits across the top

Can we get some support on this? Thanks in advance

HTML:
```
<div style="line-height:1 !important; border:1px solid black;">
<table class="page-break-table">
...
</table>
</div>
```

CSS:
```
page-break-table {
    width: 90% !important;
    margin-left:4% !important;
    border-spacing:20px !important;
    font-size:10px !important;
    page-break-inside:auto !important;
}
```

**Comment by grewn0uille** [comment]
Hi @maddiestigler!

You can use `box-decoration-break: clone` on the div.

**Comment by maddiestigler** [comment]
That worked! Thank you
