### ISSUE TITLE
HTML object is not prepending the base_url when using css url() function

### ISSUE THREAD

**Issue by matheussouza9** [Kozea/WeasyPrint#1290]
The `style.css` file is loaded, but `bg.png` is not loaded

/home/user/project/test_html.py
```python
from weasyprint import HTML

base_url = '/home/user/project'
file_name = 'template.html'
html_obj = HTML(file_name, base_url=base_url)
html_obj.write_pdf('test.pdf')
```

/home/user/project/template.html
```html
<html>
    <head>
        <title>title</title>
        <link rel="stylesheet" type="text/css" href="./css/style.css">
    </head>

    <body>
        <h1>Content</h1>
        <div class="img-bg"></div>
    </body>
</html>
```

/home/user/project/css/style.css
```css
.img-bg {
    background-image: url("file://./images/bg.png");
}
```

**Comment by grewn0uille** [comment]
Hi @matheussouza9!

The url of the background image is relative and a relative uri doesn’t include the scheme (ie `file://`). You can see [this SO answer](https://stackoverflow.com/questions/7857416/file-uri-scheme-and-relative-files/19204256#19204256) for more details.
So the url of the background image should be `url("./images/bg.png")`.

Also, it could be nice to specify the scheme on the `base_url` so it would be an actual url and not a simple path (even if it works here).

**Comment by matheussouza9** [comment]
Nice. I also thought it was relative to the `base_url` attr from `HTML` object. Thanks :)
