### ISSUE TITLE
Problem on AWS Lambda after updating

### ISSUE THREAD

**Issue by lissizza** [Kozea/WeasyPrint#1294]
Hi there,

I had a working weasyprint on my AWS Lambda (deployed with terraform). I spent much time to make it work, and I had a working solution which was to unpack needed libraries to the root space of my Lambda. I used weasyprint-0.42.3, but recently after I've updated to the latest version (0.52.2) I started getting error: `cannot load library 'libpango-1.0.so.0' aws` despite I still have the same libraries in the same place. It works yet after downgrading back to 0.42.3.
Could you advise how I could fix it? Do I need new versions of those libs?

**Comment by liZe** [comment]
Hi!

Maybe you’ll find a solution in #1003, #916, #952. I don’t use AWS, I can’t really help you more… :/

**Comment by liZe** [comment]
Feel free to reopen if the comment in these issues don’t help you.
