### ISSUE TITLE
Ligatures do not seem to render

### ISSUE THREAD

**Issue by i-sf** [Kozea/WeasyPrint#1295]
Hi, thanks for this software. Ligatures seemingly don't render.

**System:** Windows 10
**GTK:** gtk3-runtime-3.24.24-2021-01-30-ts-win64.exe
**Python:** Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
**Version:**  WeasyPrint==52.2 

HTML used to reproduce the bug:

```html
<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
    <style>
        h1 {
            font-family: "Calibri";
        }
    </style>
    </head>
    <body>
        <h1>atib</h1>
    </body>
</html>
```

`weasyprint bug.html bug.pdf` output as rendered by SumatraPDF v3.2 64-bit (zoomed in):

![image](https://user-images.githubusercontent.com/75838947/107199386-a2da0300-69f6-11eb-9378-4695896fd0ac.png)

Expected output (as rendered by Windows settings):

![image](https://user-images.githubusercontent.com/75838947/107199345-95bd1400-69f6-11eb-80be-4849135ca4bd.png)

If I add `font-variant-ligatures: none;` to the style, the full text renders, but the font is gone (I guess Calibri lacks a variant with no ligatures):

![image](https://user-images.githubusercontent.com/75838947/107199743-1419b600-69f7-11eb-805f-1bef1f0515a6.png)

(As a side-note, I'm unable to display the generated `.pdf` on Firefox, "This PDF document might not be displayed correctly.", nor Acrobat Reader, "There was an error processing a page. There was a problem reading this document (114).").

**Comment by i-sf** [comment]
Interestingly, adding an empty `<span></span>` seems to make it work, so now I have a workaround!

![image](https://user-images.githubusercontent.com/75838947/107201059-c69e4880-69f8-11eb-8c9c-a031bdb5bfcd.png)

(I think it has cached `atib` and now consistently renders wrong, so I changed it for `atic` for testing).

**Comment by grewn0uille** [comment]
Hi!
Can you share the working and non-working PDFs please?

**Comment by i-sf** [comment]
Yes, [nonworking.pdf](https://github.com/Kozea/WeasyPrint/files/5942837/nonworking.pdf) and [working.pdf](https://github.com/Kozea/WeasyPrint/files/5942838/working.pdf).

**Comment by i-sf** [comment]
With regards to Acrobat being unable to read the file, if I [hold Control when pressing OK](https://community.adobe.com/t5/acrobat/what-causes-this-error-the-document-could-not-be-saved-there-was-a-problem-reading-this-document-114/td-p/8823925) it instead says "Unterminated string.". This is probably the ligature issue, as `working.pdf` opens fine.

**Comment by grewn0uille** [comment]
By looking the files content, it’s caused by a [bug in Cairo](https://gitlab.freedesktop.org/cairo/cairo/-/issues/449) which generate invalid font name.
You can downgrade Cairo to make it works.

Note: `master` doesn’t use Cairo anymore

Duplicate https://github.com/Kozea/WeasyPrint/issues/1292

**Comment by i-sf** [comment]
Okay, thank you for the quick resolution! I also posted a different error on that issue a few minutes ago caused by tables, but yeah, makes sense the Cairo version is buggy.

**Comment by i-sf** [comment]
> Note: `master` doesn’t use Cairo anymore

I can confirm that `pip install git+https://github.com/Kozea/WeasyPrint.git@2c919858c881d8d34eff7ba253e2c0462cb8da40#egg=WeasyPrint` gets rid of both this and the linked issue, thank you again.
