### ISSUE TITLE
Issue with tinycss2==1.1.0

### ISSUE THREAD

**Issue by ildarworld** [Kozea/WeasyPrint#1299]
Good day,

I have a found a bug related to version of tinycss2=1.1.0 in weasyprint 52.2.

I have css file which contains reference to another, so css file  which I use during write_pdf() looks like:

`@import url("main.css");`

and in Weasyprint with tinycss2==1.1.0 don't load data from "main.css",  at the same time with timycss2==1.0.2 it is working fine.

**Comment by liZe** [comment]
Thanks a lot for the report!

The bug has been introduced by the change described in Kozea/tinycss2#33. It had been changed everywhere else (we hope), but not there!

It’s been fixed in `master`, and backported to `52.x`.
