### ISSUE TITLE
What could be causing this font rendering issue?

### ISSUE THREAD

**Issue by Tristanhx** [Kozea/WeasyPrint#1303]
![Screenshot 2021-03-04 115119](https://user-images.githubusercontent.com/27008795/109953245-18787c80-7ce0-11eb-86d9-879e86fbf3b1.png)

This was rendered using this version of WeasyPrint:
WeasyPrint version: 52.3
Python version: 3.7.3
Cairo version: 11600
Pango version: 14203
CairoSVG version: 2.5.1

The font is WorkSans. The same issue persists whether I'm using ttf or otf format. The font looks fine in Opera browser. This issue presents itself when displaying the pdf in Adobe Reader. I'm using @font-face and am of course using FontConfiguration. The otf/ttf files are local and sourced using url("file://[absolutepathtofont]) format('opentype" or "truetype:);

The issue seems to only be there for weighty fonts so fonts that you would use for titles and such. The lighter fonts are not affected. The structure is such that for each component of the WorkSans font (WorkSans-Black, WorkSans-Bold, etc...) a new @font-face is added. 

We were previously using Python 3.5 with its latest WeasyPrint/Cairo release. I decided to upgrade to try to remedy this issue, but it is still present.

**Comment by grewn0uille** [comment]
Hello!

Can you please provide the PDF file and the related HTML/CSS?

**Comment by Tristanhx** [comment]
[rapport.pdf](https://github.com/Kozea/WeasyPrint/files/6083976/rapport.pdf)

[htmlcss.zip](https://github.com/Kozea/WeasyPrint/files/6084081/htmlcss.zip)

**Comment by grewn0uille** [comment]
Thanks.

The PDF you provided indicated that it is produced by PyPDF2 and not by WeasyPrint. I encounter no problem when I open it with Evince or Firefox.

![image](https://user-images.githubusercontent.com/13187416/109977600-4324fe00-7cfd-11eb-9809-ae3faf0fc9cb.png)

Also, I can’t reproduce with the HTML and CSS.

Maybe can you provide the font file (at least for ExtraBold) and the PDF directly output by WeasyPrint please?

**Comment by Tristanhx** [comment]
[report0.pdf](https://github.com/Kozea/WeasyPrint/files/6084453/report0.pdf)

We were indeed using PyPDF2 for its PdfFileReader, passing the result from WeasyPrint to PdfFileReader in preparation for overlaying on top of another pdf. I did not do the overlaying for the first pdf I sent, though it was passed to PdfFileReader as a bytes object. The pdf I send this time is the direct output from HTML.write_pdf (with stylesheets and font_config of course). You can see the issue seems to be resolved, but the smaller text underneath the title now displays this rendering fault.

[fonts.zip](https://github.com/Kozea/WeasyPrint/files/6084529/fonts.zip)
These are the fonts

Thanks for your help so far!

**Comment by Tristanhx** [comment]
> Thanks.
> 
> The PDF you provided indicated that it is produced by PyPDF2 and not by WeasyPrint. I encounter no problem when I open it > with Evince or Firefox.

The issue does not present itself when opening the file in a browser, but it does when using Adobe Reader, which most of our recipients will be using. I read on another forum (An employee at Adobe said) that browsers do not follow the pdf standards and somehow this results in no issues whatsoever. Pure luck he said.

**Comment by Tristanhx** [comment]
@grewn0uille It looks like the letters are made out of overlapping shapes (like SVG's) and where they overlap the color fill is missing.

**Comment by Tristanhx** [comment]
@grewn0uille I just noticed that in Adobe Acrobat Reader DC when zooming in at around 400% the rendering issue is gone. For the larger text 300% zoom is enough. Anything below this percentage presents the rendering issue.

**Comment by Tristanhx** [comment]
@grewn0uille I'm sorry I accidentally sent output from an older version of WeasyPrint

[report0.pdf](https://github.com/Kozea/WeasyPrint/files/6084931/report0.pdf)

This one was rendered with the latest version of WeasyPrint and dependencies, though the result is the same.

**Comment by liZe** [comment]
Feel free to reopen this issue if needed.
