### ISSUE TITLE
Non-identical rendering output when using it on windows and on ubuntu

### ISSUE THREAD

**Issue by howardlhw** [Kozea/WeasyPrint#1306]
When trying to generate the template, there are differences between the rendered pdf when using windows version and when using ubuntu version.  

The differences can be drastic when the font sizes are sensitive to the design of the document. I have attached a copy of the weasyprint rendered from windows and ubuntu respectively.

[weasyprint-win.pdf](https://github.com/Kozea/WeasyPrint/files/6092549/weasyprint-win.pdf)
[weasyprint-server.pdf](https://github.com/Kozea/WeasyPrint/files/6092548/weasyprint-server.pdf)

**Comment by liZe** [comment]
Hello!

It looks like you have different versions of some libraries: you have Cairo 1.15.10 on Linux and 1.17.4 on Windows. I suppose that the version of Pango and Freetype are also different, and cause this rendering difference.

**Comment by howardlhw** [comment]
I'm using bionic, the latest version of cairo that's available is 15.10-2ubuntu0.1.
https://packages.ubuntu.com/bionic-updates/libcairo2-dev

Similarly for pango, the windows version is 1.48.0, while ubuntu is 1.40.14-ubuntu0.1
https://packages.ubuntu.com/bionic/libpango-1.0-0

Correct me if I'm wrong, it doesn't seem like there is a way to upgrade on ubuntu nor downgrade on windows without recompiling the binary.

I've installed both versions using the instructions on the documentation. What would be the best solution?

**Comment by howardlhw** [comment]
The more I look at it, the more it seems like a rendering issue caused by font face, I'm not too sure what is the issue though, the font faces across two documents are certainly different.

**Comment by Tontyna** [comment]
Of course, different fonts on Windows and Ubuntu render differently, but in the weasyprint.org case all fonts are embedded in the PDF.

**weasyprint-win.pdf:**

![win-fonts](https://user-images.githubusercontent.com/35614937/110220997-cbf09500-7ec9-11eb-80ec-6d1d9a00a933.png)

**weasyprint-server.pdf:**

![server-fonts](https://user-images.githubusercontent.com/35614937/110221038-0b1ee600-7eca-11eb-9717-e37bc11effb4.png)

Donwgrading on Windows is possible -- just download (unzip, insert in your PATH) an older release from https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

**Comment by howardlhw** [comment]
Thanks for the response, decided to use linux for development purposes so we won't have to handle the product versioning from development to production. 

But during the experimental phase, we have discovered something interesting. On the windows system, there seem to be a requirement to generate 'sufficient text' for the pdf for it to render properly. I have attached two version of the pdf with the only difference being the additional line item. 

[Daily_NoError.pdf](https://github.com/Kozea/WeasyPrint/files/6125434/Daily_NoError.pdf)
[Daily_Error.pdf](https://github.com/Kozea/WeasyPrint/files/6125435/Daily_Error.pdf)

Do you have any idea what could be causing the problem?

**Comment by liZe** [comment]
> Do you have any idea what could be causing the problem?

Yes, that’s a different problem, caused by [a bug in Cairo 17.4](https://gitlab.freedesktop.org/cairo/cairo/-/issues/449). It’s already fixed in their code but no release has been made yet.

**Comment by howardlhw** [comment]
Got it. thanks for responding.
