### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by donnay** [Kozea/WeasyPrint#1307]
I just follow the simple steps to install WeasyPrint for MAC OS.
I saw a few error messages about pytho 3.8 & 3.9

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

```
To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

Possible conflicting files are:
/usr/local/bin/2to3 -> /usr/local/bin/2to3-3.8
/usr/local/bin/idle3 -> /usr/local/bin/idle3.8
/usr/local/bin/pip3
/usr/local/bin/pydoc3 -> /usr/local/bin/pydoc3.8
/usr/local/bin/python3 -> /usr/local/bin/python3.8
/usr/local/bin/python3-config -> /usr/local/bin/python3.8-config
/usr/local/share/man/man1/python3.1 -> /usr/local/share/man/man1/python3.8.1
/usr/local/lib/pkgconfig/python3-embed.pc -> /usr/local/lib/pkgconfig/python-3.8-embed.pc
/usr/local/lib/pkgconfig/python3.pc -> /usr/local/lib/pkgconfig/python-3.8.pc
==> /usr/local/Cellar/python@3.9/3.9.2_1/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.2_1/bin/pip3 install -v --global-option=--no-user-cfg --install-option=--force --install-option=
==> /usr/local/Cellar/python@3.9/3.9.2_1/bin/pip3 wheel --wheel-dir=/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/
==> Caveats
Python has been installed as
  /usr/local/bin/python3

```

Has any one see this errono 61 before?

**Comment by donnay** [comment]
Also,
We I attempt to use the WeasyPrint Navigator in Python3 I get the following error

```
weasyprint.urls.URLFetchingError: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
127.0.0.1 - - [07/Mar/2021 14:28:18] "GET /view/http://www.webstandards.org/files/acid2/test.html HTTP/1.1" 500 59
```

Thanks for you help!

**Comment by liZe** [comment]
Hello!

> Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /usr/local
> Could not symlink bin/2to3
> Target /usr/local/bin/2to3
> already exists. You may want to remove it:
> rm '/usr/local/bin/2to3'

This message just means that you already have a `/usr/local/bin/2to3` file and that Homebrew doesn’t want to erase it. If you don’t care about your current `/usr/local/bin/*` files, overwriting (as you did) is not a problem.

> We I attempt to use the WeasyPrint Navigator in Python3 I get the following error
> ```
> weasyprint.urls.URLFetchingError: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
> 127.0.0.1 - - [07/Mar/2021 14:28:18] "GET /view/http://www.webstandards.org/files/acid2/test.html HTTP/1.1" 500 59
> ```

That’s an error caused by a problem in the way certificates are configured on your system. You can find different solutions in #632.

**Comment by liZe** [comment]
@donnay Did you find a solution?

**Comment by donnay** [comment]
Thank you for following up. No, I did not find a solution I think my local development environment is hosed and I have yet to figure out how to rebuild it. Thanks again for your commitment to following up I do appreciate it. Have a great day
