### ISSUE TITLE
Margins are not repeated on tables with box-decoration-break

### ISSUE THREAD

**Issue by jrson83** [Kozea/WeasyPrint#1310]
With the [reports demo from samples](https://weasyprint.org/samples/), there is no space (bottom margin) between the @page header element when there is a table break on multiple pages.

Screenshot (can't upload here from linux):

https://i.postimg.cc/C55sn7Mz/Screenshot-20210311-163430.png

**Comment by liZe** [comment]
Hi!

When an element is split between multiple pages, its margin is not repeated. You can use [`box-decoration-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break) to repeat it.

(🤞🏽 it should work with tables too…)

**Comment by jrson83** [comment]
> Hi!
> 
> When an element is split between multiple pages, its margin is not repeated. You can use [`box-decoration-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break) to repeat it.
> 
> (🤞🏽 it should work with tables too…)

Thanks for the answer. Can you give an example how to use it? I can't find any examples with box-decoration-break and tables.

**Comment by jrson83** [comment]
Thanks, I got it working on the report.css sample.

```
html body h2 {
  margin-top: 0;
  padding-top: 0;
  break-before: always;
  font-size: 20pt;
  string-set: heading content(); }
html body article:not(#cover) {
  padding-top: 20px;
  box-decoration-break: clone }
```
The tables are inside `html body article section table`.

**Comment by liZe** [comment]
Reopening, as the bug exists even if there’s a nice workaround.

**Comment by kygoh** [comment]
The test case [`test_box_decoration_break_block_clone`](https://github.com/Kozea/WeasyPrint/blob/8aecf3853490d271115acf7fe271a43897651644/tests/layout/test_block.py#L616-L666) has:

https://github.com/Kozea/WeasyPrint/blob/8aecf3853490d271115acf7fe271a43897651644/tests/layout/test_block.py#L621-L622

If margins should be repeated, does it mean `paragraph.margin_top` on the page 2 should be 5? Does this contradict with the test?

https://github.com/Kozea/WeasyPrint/blob/8aecf3853490d271115acf7fe271a43897651644/tests/layout/test_block.py#L651-L656

**Comment by liZe** [comment]
> If margins should be repeated, does it mean `paragraph.margin_top` in page 2 should be 5? Does this contradict with the test?

[For block-level boxes, margins are always truncated.](https://drafts.csswg.org/css-break/#break-decoration) That’s why the top margin is 0.

So… My comment above is wrong, we don’t have margins applied on split tables, but that’s actually normal!
