### ISSUE TITLE
pango_context_set_round_glyph_positions not found

### ISSUE THREAD

**Issue by summersz** [Kozea/WeasyPrint#1312]
I am doing some testing with the master branch and received the following error:

`function/symbol 'pango_context_set_round_glyph_positions' not found in library 'C:\Program Files\GTK3-Runtime Win64\bin\libpango-1.0-0.dll': error 0x7f`

I have no issues with this document creating using 52.x versions.

**Comment by liZe** [comment]
Hi!

You have to use Pango >= 1.44.0 with the `master` branch. Upgrading GTK3 will solve the problem ([the current installer includes version 1.48.0](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer)).

**Comment by summersz** [comment]
Hi, is there a way to upgrade pango without upgrading Cairo? I also need to use the 52.x version so can’t use the latest Cairo included in the gtk3 installer. Thanks

**Comment by liZe** [comment]
If Cairo 1.17.2 is OK for you (it’s not perfect but better than 1.17.4 as far as I can remember), you can try [the previous version of the installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/tree/2020-11-22).
