### ISSUE TITLE
Leader links extend beyond the leader length

### ISSUE THREAD

**Issue by summersz** [Kozea/WeasyPrint#1313]
I am trialing the new leader support using the following in my css.

`.toc a::after {
  content: leader('.') target-counter(attr(href), page);
}`

Visually it looks as expected however the link when hovering over the leader or page number extends well beyond the leader and page:

![image](https://user-images.githubusercontent.com/7293216/111142661-d4596780-857c-11eb-97a7-b2c3668da74d.png)

**Comment by liZe** [comment]
Thanks a lot for testing the current `master` branch and for the report, that’s really useful :heart:.

Please let us know if the fix works for you!

**Comment by summersz** [comment]
Hi @liZe 
Just got round to testing this again today. Working perfectly, thanks! 

Any rough dates for when svg support can be tested?

**Comment by liZe** [comment]
> Just got round to testing this again today. Working perfectly, thanks!

:heart:

> Any rough dates for when svg support can be tested?

Next month. You can try the (really) unstable `pydyfsvg` branch if you really want to be a (really) early adopter!
