### ISSUE TITLE
how to render a image instead of pdf

### ISSUE THREAD

**Issue by saikumargurugu** [Kozea/WeasyPrint#1315]
can i render a image from html instead for pdf

**Comment by liZe** [comment]
> can i render a image from html instead for pdf

If you use the current stable version, you can generate a `.png` file and you’ll get an image.

If you use the `master` branch, WeasyPrint is not able by itself to generate images anymore. Using Ghostscript or Poppler is the best solution.

**Comment by saikumargurugu** [comment]
what is current stale version?

**Comment by liZe** [comment]
> what is current stale version?

It’s 52.5: https://pypi.org/project/WeasyPrint/
