### ISSUE TITLE
Table Headers only populate on second page during a page break

### ISSUE THREAD

**Issue by mgs4ff** [Kozea/WeasyPrint#1319]
Hi team,

I have a table with repeating thead objects, however on a page break, the headers are only showing up on the second page.  This only happens when the combined headers + data overflows the page pushing the data down.  I wasn't able to attach images to demonstrate this.  Any help would be appreciated

`page-break-table {
    width: 90% !important;
    margin-left:4% !important;
    border-spacing:20px !important;
    font-size:10px !important;
    page-break-inside:auto !important;
}`

**Comment by grewn0uille** [comment]
Hello @mgs4ff!
Can you please share the related HTML/CSS files?

**Comment by liZe** [comment]
Please reopen this issue if we can help you.
