### ISSUE TITLE
Cells at the end of a table rendered as transparent when using opacity elsewhere

### ISSUE THREAD

**Issue by vilarneto** [Kozea/WeasyPrint#1320]
(Using WeasyPrint version 52.4 with Python 3.9.2 on macOS 11.2.3; fontconfig==2.13.1, cairo==1.16.0, pango==1.48.3, gdk-pixbuf==2.42.4, libffi==3.3 through Homebrew)

When using `opacity` CSS property on some parts of a table, occasionally some of the cells at the very end of that table are rendered as totally transparent (the text can be selected and copied-pasted, but not visible).  See the example below:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <style>
.zero {
  opacity: 0.5;
}
</style>
</head>
<body>
<table>
  <tbody>
  <tr>
    <th>Line 1</th>
    <td>1.00</td>
    <td class="zero">0.00</td>
    <td class="zero">0.00</td>
    <td class="zero">0.00</td>
    <td>2.00</td>
    <td class="zero">0.00</td>
    <td>3.00</td>
    <td>4.00</td>
  </tr>
  <tr>
    <th>Line 2</th>
    <td>1.00</td>
    <td>0.00</td>
    <td>0.00</td>
    <td>0.00</td>
    <td>2.00</td>
    <td>0.00</td>
    <td>3.00</td>
    <td>4.00</td>
  </tr>
  </tbody>
</table>
</body>
</html>
```

Results after conversion through command-line interface (notice blank cells at second row):

<img width="452" alt="Screen Shot 2021-03-24 at 09 09 11" src="https://user-images.githubusercontent.com/8395999/112316130-330b9900-8c81-11eb-9d99-b5782d7d12cf.png">

The problem seems to manifest with any value other than `0` or `1` for `opacity`. (By the way, WeasyPrint rejects the percentage syntax, e.g., `opacity: 50%`.)

Furthermore, if one duplicates the `<table>...</table>` block then the first table is rendered as expected, i.e., second row is fully visible:

<img width="454" alt="Screen Shot 2021-03-24 at 09 08 52" src="https://user-images.githubusercontent.com/8395999/112316168-3c950100-8c81-11eb-981b-84dcc1ce1708.png">

The number of transparent cells vary (depends on some factors I didn't manage to track) and are not necessarily related with `<td>`s – I have some instances where only the last or the three last cells are invisible, with preceding visible `<td>`s at the same row.

**Comment by liZe** [comment]
Hmmmm… I can’t reproduce this problem, I get the right rendering with your sample (and the same libraries as you).

Could you please share the PDF you get?

**Comment by vilarneto** [comment]
Ok, dug deeper on my side – I am using Skim as my PDF reader and just installed & tested with other readers – both Acrobat Reader and Google Chrome render it correctly.  Also tested the PDF on a Windows machine, it's OK.  As it seems it all points to a bug in Skim itself.

What got me was the fact that both the macOS file previewer and Safari render the file incorrectly – I would guess they both defer PDF rendering to Skim, as it is defined as my default viewer.

I'm sharing the PDF anyway for the sake of completeness.  I assume this ticket can be closed.  Sorry for that!

[test1.pdf](https://github.com/Kozea/WeasyPrint/files/6236664/test1.pdf)

**Comment by liZe** [comment]
> I'm sharing the PDF anyway for the sake of completeness. I assume this ticket can be closed. Sorry for that!

No problem!
