### ISSUE TITLE
Loading external Images with Django

### ISSUE THREAD

**Issue by Thorbenl** [Kozea/WeasyPrint#1321]
Hello!
Currently on a small project that uses WeasyPrint for generating a PDF based on a Jinja2 HTML template. Here is the template:
```html 
       <div class="details">
            <img src="{{ image }}" style="height: auto; width: 50px"/>
            <img src="http://place-hold.it/300" alt={{ id }} width="120" height="90"/>
            <div class="img-div" style="background-image: url('{{ image }}');">
            </div>
        </div>
```
Im trying go get it to work with three different methods. `{{ image }}` has the content of `http://place-hold.it/300`. Im just wondering why this wouldnt work? Its just an image from an external source, no auth needed or anything. Could it be CORS in the django project? 

I have created wrapper functions:

```python
def render_template_to_pdf(template_name, output_file: IO, context: dict):
    # Render mail template using Django's template rendering
    template: Template = get_template(template_name)
    template_path = template.origin.name
    html = template.render(context)

    render_html_to_pdf(html, output_file, base_url=os.path.dirname(template_path))


def render_html_to_pdf(html: str, output_file: IO, base_url=None):
    import weasyprint
    pdf = weasyprint.HTML(string=html, base_url=base_url)
    pdf.write_pdf(target=output_file)
```

```python
def generate_pdf(output_file: IO):
    data = {
        "id": 2
        "image": "http://place-hold.it/300"
    }

    render_template_to_pdf(
        "test.html",
        output_file=output_file,
        context=data
    )
    output_file.seek(0)
```

```python
      # View function that uses bove generator
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'filename="test.pdf"'
        with NamedTemporaryFile() as output_file:
            generate_pdf(data, output_file)
            response.write(output_file.read())
        return response
```

The PDF gets created perfectly with the rest of the information that is just text and tables. Local images ALSO work, but we will have images served from an external source. 

Any pointers on how to get this to work? I am really lost :(

**Comment by grewn0uille** [comment]
Hello @Thorbenl 

Without Django I got the image. You may be interested in using [django-weasyprint](https://pypi.org/project/django-weasyprint/) to help you with URL fetcher.

Btw, with the second method, the image won’t have the size you specify because the width and height are HTML attributes. To make them works, you’ll have to use the `--presentional-hints` option when calling WeasyPrint.
With the third method, the image won’t be display because the div doesn’t have a height and a width, so you may want to define them.

**Comment by Thorbenl** [comment]
> Hello @Thorbenl
> 
> Without Django I got the image. You may be interested in using [django-weasyprint](https://pypi.org/project/django-weasyprint/) to help you with URL fetcher.
> 
> Btw, with the second method, the image won’t have the size you specify because the width and height are HTML attributes. To make them works, you’ll have to use the `--presentional-hints` option when calling WeasyPrint.
> With the third method, the image won’t be display because the div doesn’t have a height and a width, so you may want to define them.

Thanks for the quick answer and thanks for getting back to me. Im wondering what django does specifically behind the scenes. IT cant be the auth really, since its all deactivated for the endpoints, and also we implemented our down auth for these cases anyway, 

I will take a look a [django-weasyprint](https://pypi.org/project/django-weasyprint/) and get back to you if I managed, so we can close this issue.

**Comment by liZe** [comment]
Another possible problem: if you use a dev server with only one thread, rendering a template that needs static files may lead to a deadlock.

[Configuring logs](https://weasyprint.readthedocs.io/en/stable/tutorial.html?highlight=logging#logging) is also a good solution to find out what’s going on.

**Comment by Thorbenl** [comment]
> Another possible problem: if you use a dev server with only one thread, rendering a template that needs static files may lead to a deadlock.
> 
> [Configuring logs](https://weasyprint.readthedocs.io/en/stable/tutorial.html?highlight=logging#logging) is also a good solution to find out what’s going on.

I have been trying to configure logs to no avail with:
```python
def render_html_to_pdf(html: str, output_file: IO, base_url=None):
    import weasyprint
    from weasyprint.logger import LOGGER as weayprint_logger
    weayprint_logger.setLevel(logging.DEBUG)
    weayprint_logger.addHandler(logging.FileHandler(f"{os.path.abspath(os.path.dirname(__file__))}/weasy.log"))
    pdf = weasyprint.HTML(string=html, base_url=base_url)
    pdf.write_pdf(target=output_file)
```

Maybe Djangos logging is somehow intercepting here?

**Comment by liZe** [comment]
> Seems weird to me? shouldnt JPG be also allowed? Our users will be able to upload any image type, and then it will be stored as an object in S3, and served over the [Imgix](https://www.imgix.com/) service.

Handling JPG files requires the GDK-Pixbuf package to be installed. PNG and SVG already work, without GDK-Pixbuf.

**Comment by Thorbenl** [comment]
I think this can be closed then. After installing/updating GDK-Pixbuf, these images work well from different sources, without using `django-weasypring`. just the normal one :)
