### ISSUE TITLE
The justify-content does not work

### ISSUE THREAD

**Issue by lukeNguyen0202** [Kozea/WeasyPrint#1323]
I am working on an Django App, and the plugin is such in handy to transform the HTML template to PDF. I understand that you guys are working on the similar issue with the  justify-content, and I am waiting to heard back from you. 

Here is the CSS that is on the HTML template and will need to be converted to PDF.

```
.host-name-label {
            padding-left: 5px;
            width: 199px;
            height: 15px;
            font-size: {{ detail_data.vo_fs }};
            font-family: '{{ detail_data.vo_ff }}';
            {% for i in detail_data.vo_fst %}
                {% if i == 'Underline' %}
                    text-decoration: underline;
                {% elif i == 'Bold'%}
                     font-weight: bold;
                {% elif i == 'Italic'%}
                    font-style: italic;
                {% endif %}
            {% endfor %}
            {#font-weight: 500;#}
            display: flex;
            align-items: center;
            text-align: right;
            justify-content: right;
        }

```

Every thing else is perfectly correct, and beautiful, just the   ` justify-content: right;` that got ignored, and it make the attribute display incorrect as I expect. 

I just want to following up with the update

**Comment by liZe** [comment]
Hi!

`justify-content` is currently handled according to [Flexbox](https://www.w3.org/TR/css-flexbox-1/#justify-content-property) (a candidate recommendation) and not yet according to [Box alignment](https://drafts.csswg.org/css-align-3/#propdef-justify-content) (a working draft).

Using `justify-content: flex-end` should just do what you want.
