### ISSUE TITLE
No library called cairo was found error in virtualenv

### ISSUE THREAD

**Issue by mnnlthmpsn** [Kozea/WeasyPrint#1329]
I followed every instruction and yes Weasyprint works in my console. 
But this is the error I get in my virtualenv. I already did `python -m pip install WeasyPrint`

`OSError: no library called "cairo" was found
cannot load library 'C:\Program Files\GTK3-Runtime Win64\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1`

**Comment by liZe** [comment]
Hello!

Error 0xc1 means that the library has been found but could not be loaded. Do you have the 64-bits version of Python?

**Comment by mnnlthmpsn** [comment]
Yes please I do

________________________________

**Comment by Tontyna** [comment]
Since WeasyPrint works in your console but not in your virtualenv -- please check the `PATH` in your virtualenv and make sure that `C:\Program Files\GTK3-Runtime Win64\bin\` is still at the beginning of it.

**Comment by mnnlthmpsn** [comment]
Okay. I’ll do that

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by liZe** [comment]
@mnnlthmpsn Is there anything more we can do for you?
