### ISSUE TITLE
Problems with divs that can't fit in page

### ISSUE THREAD

**Issue by luizbraga** [Kozea/WeasyPrint#1332]
If there is content that doesn't fit in the empty space of the page, it will be thrown on the next page. Because of this, sometimes I get huge gaps between the pages. if the content is too big to fit. Is there something I can do? I'm trying to split the content into small sizes but sometimes I can't.

**Comment by liZe** [comment]
Hello!

Divs are supposed to be split … when it’s possible. Most of the blocks that are not split are listed in #36, are you in one of these cases?

**Comment by liZe** [comment]
Feel free to reopen if we can help you!
