### ISSUE TITLE
Emojis are rasterized

### ISSUE THREAD

**Issue by zellermario** [Kozea/WeasyPrint#1338]
Hi.

When I generate PDF from HTML files that contain emojis, emojis are embedded as raster images in the output.
E.g. when I use an HTML file with the below text as input,
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <h1>Emojis are rasterized. 😞</h1>
</body>
</html>
```
I get the following PDF as output: [out.pdf](https://github.com/Kozea/WeasyPrint/files/6326347/out.pdf).

Before installing an emoji font, the emojis were, of course, not displayed in the output. But after installing Noto Color Emoji, they are displayed as shown in the example.

My output for `weasyprint -i` is the following:
```
System: Linux
Machine: x86_64
Version: #1 SMP Debian 4.19.171-2 (2021-01-30)
Release: 4.19.0-14-cloud-amd64

WeasyPrint version: 52.4
Python version: 3.7.3
Cairo version: 11600
Pango version: 14203
CairoSVG version: 2.5.2
```

Any ideas why this happens?

**Comment by liZe** [comment]
Hello!

We rely on Cairo to generate the PDF file, and Cairo only supports emojis as PNG files included in font files. Vector emojis included in fonts (SVGinOT) are actually only supported by a very small amount of applications (mainly Firefox, Edge and Photoshop, see [twemoji-color-font](https://github.com/eosrei/twemoji-color-font#readme) about that. As far as I know, Noto Color Emoji only contains raster emojis.

But you’re right, Cairo doesn’t do a very good job when generating PDF files with colored emojis. They’re probably downscaled for some reason, as if they were rendered on a low-density raster surface. I don’t know if there’s a way to fix that 😒.

The current master branch, that doesn’t rely on Cairo, doesn’t support colored emojis. When we’ll add the support of colored emojis back, we’ll try to 1) support vector emojis, and 2) use large raster images.

**Comment by liZe** [comment]
The problem is solved … now that colored emojis are not supported anymore :/.

Let’s continue the discussion in #1406.
