### ISSUE TITLE
Fontconfig error when trying to run WeasyPrint

### ISSUE THREAD

**Issue by RSLak1** [Kozea/WeasyPrint#1339]
Hello,

I am trying to use WeasyPrint for an existing project but sadly, I ran into some issues while installing.
I followed the installation guide here: https://weasyprint.readthedocs.io/en/latest/install.html (I used the GTK+ 64bit installer during the installation).

After installation, the test call `python -m weasyprint https://google.com weasyprint.pdf` led to the following output: `Fontconfig error: Cannot load default config file`. No PDF was generated.
I was not able to find any real information what I could do to fix that. 

Windows version: Windows 10 Version 20H2 (OS Build 19042.867)
Output of `python --version --version`: `Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]`

**Comment by liZe** [comment]
Hello!

Thanks for reporting this issue.

This error should not prevent the generation of the PDF… Could you please launch `python -m weasyprint --debug https://google.com weasyprint.pdf` and report what’s displayed on your terminal?

**Comment by RSLak1** [comment]
Terminal Output:
```
(venv) D:\Repos\Scone\scone-server>python -m weasyprint --debug https://google.com weasyprint.pdf
Fontconfig error: Cannot load default config file
```
again, no PDF was generated.

**Comment by RSLak1** [comment]
I just realized this also happend when I try to run other weasypint commands:
```
(venv) D:\Repos\Scone\scone-server>python -m weasyprint --info
Fontconfig error: Cannot load default config file
```

**Comment by liZe** [comment]
> (venv) D:\Repos\Scone\scone-server>python -m weasyprint --info
> Fontconfig error: Cannot load default config file

I really don’t know how it is possible to get this error and no rendering. Installing Fontconfig with the GTK+ installer should install the default config file too. And even if there’s something wrong, we should get a Python traceback.

Could you please try to launch the Python interpreter, and then write `import weasyprint`?

**Comment by RSLak1** [comment]
Still the same. 
I tried to narrow it down with the PyCharm debugger.
I set a breakpoint on the first line of weasyprint/__init__.py, it crashes on the last line (473) `from .document import Document, Page  # noqa isort:skip`.
So I set a breakpoint in document... It crashes at line 24 `from .fonts import FontConfiguration`. In fonts, it crashes at line 454 `fontconfig.FcInitLoadConfigAndFonts()`. Since from here the execution flow enters a DLL, I dont know how to narrow it down further.

I will try installing GTK+ again, maybe that does something.

**Comment by RSLak1** [comment]
Okay, I am even more confused now.
I reinstalled GTK3+. Now I am getting a stacktrace for a completly different reason:
```Traceback (most recent call last):
  File "D:\Repos\Scone\scone-server\debug.py", line 2, in <module>
    import weasyprint
  File "D:\Repos\Scone\scone-server\venv\lib\site-packages\weasyprint\__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "D:\Repos\Scone\scone-server\venv\lib\site-packages\weasyprint\css\__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "D:\Repos\Scone\scone-server\venv\lib\site-packages\weasyprint\css\computed_values.py", line 15, in <module>
    from .. import text
  File "D:\Repos\Scone\scone-server\venv\lib\site-packages\weasyprint\text.py", line 260, in <module>
    pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0', 'libpango-1.0.so.0',
  File "D:\Repos\Scone\scone-server\venv\lib\site-packages\weasyprint\text.py", line 255, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "D:\Repos\Scone\scone-server\venv\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "D:\Repos\Scone\scone-server\venv\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "D:\Repos\Scone\scone-server\venv\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0'
```

strange about this is that line 260 in text.py lists multiple versions of pango: `pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0', 'libpango-1.0.so.0', 'libpango-1.0.dylib')`.

The second version is present on my system: 
```
(venv) D:\Repos\Scone\scone-server>WHERE libpango-1.0-0
INFO: Could not find files for the given pattern(s).

(venv) D:\Repos\Scone\scone-server>WHERE libpango-1.0-0.dll
C:\Program Files\GTK3-Runtime Win64\bin\libpango-1.0-0.dll
```

**Comment by Tontyna** [comment]
Ah another PyCharm! Looks like it loads DLLs that, sometimes even after restarting the IDE, interfere with the GTK3+ Runtime, even when the GTK3+ Runtime folder is the first in the system `PATH`. See e.g. #1334 

Can you find out what PyCharm does when it initializes its console/terminal?

I'm quite sure that somewhere in the PyCharm application folder (or PyCharm's special search path) you will find GTK related DLLs.

**Comment by RSLak1** [comment]
Got the error!

First of, why the error changed when I reinstalled GTK3+:
When I first installed GTK3+ I moved it to the front of the PATH just to be sure. Reinstalling GTK3+ removed it from my PATH and added it again at the back. Although `WHERE libpango-1.0-0.dll` returns the correct path (and although [procmon](https://docs.microsoft.com/en-gb/sysinternals/downloads/procmon) showed my that python indeed tried to access it) it seems like python used some other version of that DLL. Moving it back to the front helped.


Now to the original problem:
Since it worked well with the other problem, I used [procmon](https://docs.microsoft.com/en-gb/sysinternals/downloads/procmon) again to watch for every access to some path containing "fontconfig". Turns out python again loads the wrong DLL. 
The problem was that GTK may be at the front of my path, but since `dlopen` tries out one possible DLL name after the other and the correct for my system is at place 3, it loads the wrong DLL if one of the first two variants is present somewhere on my PATH. 
For another project I have graphviz installed, and graphviz comes with a DLL called `fontconfig.dll` which is on place 1. 



Thanks for your help and special thanks to @Tontyna, your comment brought me to the right track.

I dont know if there is anything you can do about these kind of problems (other than maybe add it to a troubleshooting list?), so I guess this issue can be closed?

**Comment by liZe** [comment]
> I dont know if there is anything you can do about these kind of problems (other than maybe add it to a troubleshooting list?), so I guess this issue can be closed?

This error goes into the long list of [problems with libraries on Windows](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#missing-library). To solve this problem, we already have possible solutions to try in the future (packaging libraries, generating executables, etc), so I’ll close this issue. If anyone gets this problem again, they will probably find these comments!

**Comment by xxxxxxming** [comment]
I also encountered this problem, it has been bothering me for a long time.I used cmd "WHERE fontconfig.dll",it was returned "D:\Program Files\Graphviz\bin\fontconfig.dll",emm..........., then I uninstalled Graphviz,weasyPrint was worked well!

**Comment by ubergeekseven** [comment]
oh my god. it was graphviz on windows. Broke it for some reason. Thanks everyone for this!!!

**Comment by ttklm20** [comment]
I got “Fontconfig error: Cannot load default config file” error as well when running "mkdocs build" command with pdf plugin configured！ After debuging the source code of WeasyPrint，specifically in text/fonts.py，I found GTK3 confilict with Meld. After uninstall Meld, this error was gone. If you still encounter this error, you can also debug text/fonts.py in WeasyPrint to see what's the problem.
