### ISSUE TITLE
Text in a code block is linked if it resembles a URL

### ISSUE THREAD

**Issue by jj-jitterbit** [Kozea/WeasyPrint#1342]
Any text in a code block that resembles a URL is being linked.

For example, some text that is intended to be looking like this:

`example.com`

and appears in the HTML as a `<code>` block:

```html
<code>
example.com
</code>
```
but ends up looking like this, as a clickable link:

[`example.com`](http://example.com)

This creates problems when the text in the code block is actually not real link, but may be an example or a prototype or incomplete in some way. I think code blocks should just be rendered as-is without any interpretation of the contents.

I looked to see how this could be turned off with CSS, but WeasyPrint does not support the `pointer-events: none` property which is suggested online as a solution on HTML pages.

I encountered it with WeasyPrint 52.5. I see on mouse-over that a small icon appears to the right of the link text in addition to the tool tip.

The sample HTML is
```html
<html>
<body>
<code>
example.com
</code>
</body>
</html>
```
I've attached a sample PDF from WeasyPrint  and a screen shot.

[example.pdf](https://github.com/Kozea/WeasyPrint/files/6360865/example.pdf)

<img width="242" alt="Screen Shot 2021-04-22 at 12 39 47 PM" src="https://user-images.githubusercontent.com/34282269/115776193-b4ca1180-a368-11eb-9c42-f1641f1da4ee.png">

**Comment by Tontyna** [comment]
WeasyPrint doesn't auto-create links. 

When I open your example PDF (with Document Viewer) there is neither a little hook nor a tooltip nor a clickable link.

Maybe it's a feature of your PDF reader. I recall that Adobe Reader can do that (Preference? Plugin?).

**Comment by liZe** [comment]
> Maybe it's a feature of your PDF reader. I recall that Adobe Reader can do that (Preference? Plugin?).

I think that PDF.js (used in browsers) has this feature. Is that what you use?

**Comment by liZe** [comment]
Feel free to reopen if there’s anything more we can do for you.
