### ISSUE TITLE
reset counter pages

### ISSUE THREAD

**Issue by erostefano** [Kozea/WeasyPrint#1347]
I am wrting a report and I want the first page of it to not include any page numbers.

What I want:
Title page: // no numbers
Second page: 1 / 2
Third page: 2 / 2

My code so far:

```
@page :first {

    margin: 0;
    counter-reset: page 0;

    @bottom-right {
        content: '';
    }
}

@page {

    @bottom-right {
        content: counter(page) ' / ' counter(pages);
    }
}
```

What I get:
Title page: // no numbers
Second page: 1 / 3
Third page: 2 / 3

Adding `pages 0`  doesnt do any difference.

`counter-reset: page 0 pages 0;`

Some I cannot reset pages. Any ideas?

**Comment by liZe** [comment]
Hello!

The `pages` counter can’t be manipulated according to [the specification](https://www.w3.org/TR/css-page-3/#page-based-counters), that’s why you can’t change it.

As far as I know, there’s no clean way to get what you want. You can try to play with [`target-counter`](https://drafts.csswg.org/css-content-3/#target-counter), but that’s only a dirty hack.

I close this issue, discussion can continue in #1180 (that’s somehow a duplicate).
