### ISSUE TITLE
HTML presentational hints such as the <font> tag

### ISSUE THREAD

**Issue by ivanprice** [Kozea/WeasyPrint#135]
Hello there,

I see in the doc that HTML presentational hints are not supported, as we favour CSS classes instead. My problem is that I am trying to make PDFs from text entered via a javascript editor (the mini WYSIWYG editor that comes with ExtJS) embedded in a webpage.

This editor does not allow me to set CSS classes on text but instead produces HTML with <font size/color=xx>  etc

Is there any way to convince Weasyprint to honour the old-school presentation tags or do i need to find a new WYSIWYG editor that supports classes ?

cheers for the great PDF machine

-i

**Comment by liZe** [comment]
Duplicates #253.
