### ISSUE TITLE
gobject-2.0

### ISSUE THREAD

**Issue by 4rake** [Kozea/WeasyPrint#1353]
raise OSError(msg)
OSError: cannot load library 'gobject-2.0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage
 to locate a library called 'gobject-2.0'

**Comment by liZe** [comment]
Hello!

This problem means that WeasyPrint doesn’t find the GObject library. Is it installed on your system?

**Comment by liZe** [comment]
Feel free to reopen if you have news about this issue.
