### ISSUE TITLE
Randomly Stopped Loading Linked CSS

### ISSUE THREAD

**Issue by allidoisace** [Kozea/WeasyPrint#1355]
Currently using version 52.5 and suddenly the linked stylesheet in the HTML that's used for the PDF is receiving the error below.

```
Failed to load stylesheet at http://test.localhost:8000/static/inventory/pdf.css : URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

I can access http://test.localhost:8000/static/inventory/pdf.css separately.

Really need some help on why this isn't loading all of a sudden.

**Comment by liZe** [comment]
Hello!

I don’t think that this bug is related to WeasyPrint, and it probably comes from a change in your network configuration. If you’re on Linux, the `test.localhost` domain is probably configured by [`systemd-resolved`](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html), and maybe something changed in your configuration.

Browsers keep a DNS cache, that’s why you can be able to open in it a browser. Can you also access it using something like `curl`?

**Comment by allidoisace** [comment]
I am currently on a Macbook (intel). Seems odd that the network config would change so randomly.

I cannot access it using curl:

```
curl: (6) Could not resolve host: test.localhost
```

**Comment by allidoisace** [comment]
I modified `/etc/hosts` on my mac to include the subdomain. Everything works as it should. My main issue, is on a production server hosted by Heroku, the same thing seems to be occurring, but not for every single instance. Kind of boggling my mind right now.

**Comment by liZe** [comment]
> My main issue, is on a production server hosted by Heroku, the same thing seems to be occurring, but not for every single instance. Kind of boggling my mind right now.

Then the problem may be on Heroku’s side. I don’t know how DNS are configured on Heroku, and it’s possible that the default configuration is different for each instance. You should open a ticket for Heroku and ask them what’s the most reliable way to have `test.localhost` working correctly.

**Comment by allidoisace** [comment]
Seemed to only be an issue when I started changing the concurrency of gunicorn. Pretty odd how that would affect this.

**Comment by liZe** [comment]
> Seemed to only be an issue when I started changing the concurrency of gunicorn. Pretty odd how that would affect this.

Yes, pretty odd…

I close this issue because it’s not related to WeasyPrint, feel free to add a comment if you think that we can help you more.
