### ISSUE TITLE
`font_info` not updated in Document's `write_pdf` font descriptor loop

### ISSUE THREAD

**Issue by aschmitz** [Kozea/WeasyPrint#1357]
When embedding fonts, `write_pdf` uses a variable for `font_type` to determine whether to describe the font as `FontFile3` (with OpenType subtype) or `FontFile2`, and which CIDFontType to give. It's used on several lines, but a representative sample is: https://github.com/Kozea/WeasyPrint/blob/fd2901c570098c9806278743c6a84f82545498b8/weasyprint/document.py#L1259

However, this variable is only set in the loop _before_ these fonts are output: https://github.com/Kozea/WeasyPrint/blob/fd2901c570098c9806278743c6a84f82545498b8/weasyprint/document.py#L1230

As a result, if both TTF and OTF fonts are included in a document, at least one of them will be output with the wrong type. Some PDF viewers (at a quick test: PDF.js, PDFium, and Poppler) seem to not mind this discrepancy, but macOS' Preview.app appears to substitute a slightly-deterministic built-in font.

I had first noticed this on a PDF file with a rendering issue in Preview.app. A minimized sample HTML document is as follows, and requires the [Inter](https://rsms.me/inter/) font and Ubuntu Mono font (the former installed from the GitHub release, the latter from the `fonts-ubuntu` Ubuntu package). There is a tab character before the final "a":

~~~html
<style>
  html {
    font-family: Inter;
  }
  code {
    font-family: Ubuntu Mono;
    white-space: pre-wrap;
  }
</style>
<code>Example</code>
text
<code>	a</code>
~~~

That produces [this PDF](https://github.com/Kozea/WeasyPrint/files/6498711/1357.pdf).

In PDFium, this renders as expected:

![1357-pdfium](https://user-images.githubusercontent.com/29508/118597046-c89f4280-b771-11eb-9eb0-e0f9991f7209.png)

However, in Preview.app, it appears to use a built-in PDF font (Helvetica?):

![1357-previewapp](https://user-images.githubusercontent.com/29508/118597110-da80e580-b771-11eb-9810-d3747f53d9e5.png)

A couple curiosities: using a different body font (such as Noto Sans) can make the problem disappear (which tracks with the same file type in both fonts fixing the problem), and removing the `white-space: pre-wrap` line (or the tab before the `a`) appears to make Preview.app render the code blocks in Courier Bold(?).

My current build process makes it a pain to actually modify WeasyPrint to test changes, but I'm hopeful that fixing this will resolve the issue, since it seems to be the root of the only nontrivial differences I can find between the PDF files when swapping fonts.

**Comment by liZe** [comment]
Thanks a lot for this **perfect** bug report :heart:.

**Comment by aschmitz** [comment]
Awesome, thanks! I can confirm that 5005459 fixes the issue with my larger test documents as well.
