### ISSUE TITLE
Broken order of inner-ol lists

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#1361]
Consider following html:

```html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8"/>
   </head>
   <body>
      <ol>
         <li>First</li>
         <li>Second</li>
         <li>Third</li>
         <ol>
            <li>Third-first</li>
            <li>Third-second</li>
         </ol>
         <li>Fourth</li>
      </ol>
   </body>
</html>
```

Which renders correctly in a browser:

<img width="717" alt="Screenshot 2021-05-20 at 10 05 53" src="https://user-images.githubusercontent.com/401107/118942413-fc858e00-b952-11eb-8131-93fc0b10ab6b.png">

Notice the correct order of inner and outer `li` elements.

But when you render this html with current version of weasyprint (52.4, I didn't manage to run the beta), the order is broken:

<img width="414" alt="Screenshot 2021-05-20 at 10 06 59" src="https://user-images.githubusercontent.com/401107/118942559-2343c480-b953-11eb-959a-28267c5d95e1.png">

[result.pdf](https://github.com/Kozea/WeasyPrint/files/6513995/result.pdf)

**Comment by liZe** [comment]
Hello!

Thanks for the bug report. Actually, that’s not a bug, that’s an undefined behavior because the HTML is not valid. The problem is explained in #1117.
