### ISSUE TITLE
SVG attribute 'visibility'

### ISSUE THREAD

**Issue by takesson** [Kozea/WeasyPrint#1362]
It seems like Weasyprint 53b1 does not respect SVG attribute visibility="hidden".

This is often used for hotspots / clickable areas.

I currently don't have a sample without proprietary data.

**Comment by liZe** [comment]
Hello!

It should be fixed, and unit tests have been added. We hope that it works for your documents too! :smile:

**Comment by takesson** [comment]
Looks good! Will test when the next beta is available.

Thanks!

**Comment by takesson** [comment]
Confirmed resolved on the svg where originally discovered.
