### ISSUE TITLE
WeasyPrint: Include header and footer of arbitrary complexity in a PDF

### ISSUE THREAD

**Issue by ReimGitHub** [Kozea/WeasyPrint#1363]
I am trying to use the class provided in the link below to add headers and footer to a main html file that I am converting to PDF using WeasyPrint:

https://weasyprint.readthedocs.io/en/stable/tips-tricks.html#include-header-and-footer-of-arbitrary-complexity-in-a-pdf

I am supposed to have three separate htmls: header_html, main_html, and footer_html. Providing the header and footer elements to the class is optional. My main_html is working fine, but every time I add a simple header_html, and try to create the PDF, I get this error:

AttributeError: 'NoneType' object has no attribute 'copy_with_children'

This error is thrown when the following chain of attributes are being called/used:

The render_pdf() --> which calls:

if self.header_html: header_body, header_height = self._compute_overlay_element('header') --> which calls:

element_body = PdfGenerator.get_element(element_page._page_box.all_children(), 'body') --> throws the error.

Can anyone help me with this problem? the best way would to have 2 simple html files: main and header that are working with this method. I have looked up all related posts, but no one has had this issue (maybe it is obvious).

Thanks

**Comment by liZe** [comment]
Hello!

> element_body = PdfGenerator.get_element(element_page._page_box.all_children(), 'body') --> throws the error.

It probably means that you have no `body` tag in your header HTML. I don’t remember everything about this snippet, but it looks like a `body` tag is required in all the HTML strings.

**Comment by TickingFeather** [comment]
Hello!
Don't want to be that guy who responds with "Just forget this and use something else", but I had a few issues with the PdfGenerator snippet too and I ended up using CSS running elements instead:
https://weasyprint.readthedocs.io/en/stable/features.html#css-generated-content-for-paged-media-module
I don't know if it fits your use case, but it may be worth a shot.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I also have problems to dive into the header/footer topic.

I want to use WeasyPrint with Python to generate PDF from my own generated HTML content.
For the first step I just want to have the page numbers in the footer.

I would be interested in a minimal working example demonstrating the possible solution. The code in the doc does not help me by understanding.

I also interested in example code about the css-page-media-module-way.

**Comment by liZe** [comment]
Hello!

> For the first step I just want to have the page numbers in the footer.

On the [sample page](https://weasyprint.org/samples/), there’s a report with page numbers (and many other features). It will probably be helpful for you!

**Comment by liZe** [comment]
I think that everything has been answered in this issue. Feel free to reopen if needed!
