### ISSUE TITLE
SVG: Wrong fill colors for some paths

### ISSUE THREAD

**Issue by pbregener** [Kozea/WeasyPrint#1365]
See images below.

I have not been able to investigate further myself, so far.

| `master` (incorrect) | v52 (correct) |
| --- | --- |
| ![v53](https://user-images.githubusercontent.com/6407709/119799823-bc875380-bedc-11eb-9042-58e05c1ddd6f.png) | ![v52](https://user-images.githubusercontent.com/6407709/119799844-c14c0780-bedc-11eb-9afe-7e02572dd68a.png) |

To reproduce:
```html
<html>
<body>
<img src="https://raw.githubusercontent.com/pbregener/weasyprint-data/main/matplotlib-bars-with-labels.svg" style="width: 100%;">
</body>
</html>

```

**Comment by liZe** [comment]
Thanks a lot for the bug report and the very useful example!

**Comment by pbregener** [comment]
Thanks a lot for another super-quick fix! I am currently testing the beta with lots of SVG-heavy documents, so there might be a few more reports coming soon!

**Comment by liZe** [comment]
> Thanks a lot for another super-quick fix! I am currently testing the beta with lots of SVG-heavy documents, so there might be a few more reports coming soon!

Don’t hesitate to report your issues, they’re really useful 😄.
