### ISSUE TITLE
SVG: Capstyles and joinstyles not applied (correctly)

### ISSUE THREAD

**Issue by pbregener** [Kozea/WeasyPrint#1366]
Using some matplotlib examples (for [capstyles]( https://matplotlib.org/stable/gallery/lines_bars_and_markers/capstyle.html) and [joinstyles](https://matplotlib.org/stable/gallery/lines_bars_and_markers/joinstyle.html)) it becomes obvious that SVG path capstyles and joinstyles are not rendered properly by non-cairo WeasyPrint.

| `master` (capstyles 🟥 , joinstyles 🟧) | v52 (capstyles ✅ , joinstyles 🟨 ) | Chrome 90 (reference) |
| --- | --- | --- |
| ![v53](https://user-images.githubusercontent.com/6407709/119820895-4392f680-bef2-11eb-8c5a-3126866260fd.png) | ![v52](https://user-images.githubusercontent.com/6407709/119820905-47267d80-bef2-11eb-8321-8eb914db11b8.png) | ![chrome](https://user-images.githubusercontent.com/6407709/119820961-51e11280-bef2-11eb-841c-55a8f039fdb7.png) |

To reproduce:
```html
<html>
<body>
<img src="https://raw.githubusercontent.com/pbregener/weasyprint-data/main/matplotlib-capstyles.svg" style="width: 100%;">
<img src="https://raw.githubusercontent.com/pbregener/weasyprint-data/main/matplotlib-joinstyles.svg" style="width: 100%;">
</body>
</html>
```

**Comment by liZe** [comment]
❤️
