### ISSUE TITLE
SVG: Opacity < 1 affects path (stroke) shape

### ISSUE THREAD

**Issue by pbregener** [Kozea/WeasyPrint#1367]
Another minor SVG issue. I have been able to reduce it to below example.

The two paths in the SVG are identical, except their fill color and their opacity values (1.0 for the green one and 0.999 for the red one).

| `master` (incorrect) | v52 (correct) |
| --- | --- |
| ![v53](https://user-images.githubusercontent.com/6407709/119860736-ef4e3d80-bf16-11eb-994d-bf1d85b44a1f.png) | ![v52](https://user-images.githubusercontent.com/6407709/119860765-f4ab8800-bf16-11eb-95fb-c7ec1099e4f4.png) |

To reproduce:
```html
<html>
<body>
<img src="https://raw.githubusercontent.com/pbregener/weasyprint-data/main/path-opacity.svg" style="width: 100%;">
</body>
</html>
```

**Comment by liZe** [comment]
Thanks again for the report.
