### ISSUE TITLE
SVG: Some "use"d paths are not rendered

### ISSUE THREAD

**Issue by pbregener** [Kozea/WeasyPrint#1369]
Some SVG paths simply aren't rendered in the latest beta (this is not a 53.0b2 regression, though. This has been present in all non-cairo versions).

I haven't been able to figure out why/how, but I have been able to reduce it to a reasonably short reproducible example (the file was originally created using matplotlib but then simplified and edited in Inkscape).

| `v53.0b2` | `v52.5` |
| --- | --- |
| ![53b2](https://user-images.githubusercontent.com/6407709/120187381-ffb33080-c214-11eb-86da-bdf4d5b8e7db.png) | ![52](https://user-images.githubusercontent.com/6407709/120187339-f4f89b80-c214-11eb-9d4c-524fe1d919e9.png) |

```html
<html>
<body>
<img src="https://raw.githubusercontent.com/pbregener/weasyprint-data/main/missing-paths.svg" style="width: 100%;">
</body>
</html>
```

**Comment by liZe** [comment]
Thanks a lot 🥇.

**Comment by pbregener** [comment]
Thanks, I can confirm this is fixed! When using very similar SVGs, I came across #1370, though.
