### ISSUE TITLE
SVG: Wrong fill colors for some "use"d paths

### ISSUE THREAD

**Issue by pbregener** [Kozea/WeasyPrint#1370]
I encountered this when confirming the fix for #1369. The result/effect is largely the same as seen in #1365, but I have no idea if the underlying problem is related.

I'll skip the comparison between current and previous versions of weasyprint here, as the problem is quite obvious: The white letters in the heading should be black. And I can confirm that the SVG renders correctly in v52.5.

![image](https://user-images.githubusercontent.com/6407709/120299387-3ea3bd80-c2cb-11eb-89d1-7780d8422d30.png)

To reproduce use
```html
<html>
<body>
<img src="https://raw.githubusercontent.com/pbregener/weasyprint-data/main/issue-1370.svg" style="width: 100%;">
</body>
</html>
```

**Comment by liZe** [comment]
Oh, edf47f5 fixes everything … but the little hyphen 😒.

**Comment by liZe** [comment]
It should be fixed for good now. Thanks again for your bug reports.

We need a much better test suite.
