### ISSUE TITLE
SVG: Support for <clipPath>

### ISSUE THREAD

**Issue by pbregener** [Kozea/WeasyPrint#1374]
I'm pretty sure you have this on your to-do list already (you mentioned clipping in some blog post and I saw some "todo" in the code), but I thought I'd open an issue anyways 😉 

For me, this is the last thing missing in terms of SVG support, and it is what currently keeps me on v52 in production. Cairo actually does a great job on the SVG side, but I also can't wait to get rid of it in WeasyPrint!

**Comment by pbregener** [comment]
Hi @liZe!
Just out of curiosity (and I have no idea how difficult this will be to implement):
Do you plan to have SVG clipping with `clipPath`s in v53.0, or will that need to wait for later?

**Comment by liZe** [comment]
> Do you plan to have SVG clipping with `clipPath`s in v53.0, or will that need to wait for later?

A couple of moths ago, we already tried to implement clip paths with the same features as the ones provided by CairoSVG. But that was actually way harder than what we thought, and we let the idea down.

We’ll probably try to add support of clip paths for simple cases before version 53, and we’ll update this issue as soon as we have news about this.

**Comment by liZe** [comment]
`clip-path` is now supported, but only for single paths. Handling more complex cases will probably require a lot of time, and we’ll keep that for later.

As we already explained in some comments earlier, SVG support will be improved in future versions, with lots of tests (and probably lots of fixes).
