### ISSUE TITLE
Custom url fetcher with redirect not working as expected

### ISSUE THREAD

**Issue by guidocioni** [Kozea/WeasyPrint#1375]
I'm running Weasyprint on a system with many limitations (under corporate proxy, closed system...) and trying to include images into a PDF.
The image is on an URL on the same system where the script is running (so in theory it shouldn't require proxies).
However the link that I have consists of an API request which responds with a PNG image. 

I have created my custom url fetcher 

```python
def photo_url_fetcher(url):
    r = requests.get(url, stream=True)
    r.raw.decode_content = True
    image_bytes = io.BytesIO(r.content)
    return dict(string=image_bytes.read(), mime_type='image/png')
```

and then used it when creating the `HTML` object 

```python
htmldoc = HTML(string=html_string, base_url="", url_fetcher=photo_url_fetcher)
```

The HTML part looks something like this 
```python
    html_string = "<img style='height:60px' src='https://api-endpoind/api-subfolder/image-id/'>"
```

The url `https://api-endpoing/api-subfolder/image-id` returns an image in Chrome. 

Weasyprint is not able to import the image as it cannot recognize the extension of the image 

```
Failed to load image  ImageLoadingError('Pixbuf error: Unrecognized image file format',)
```

However this should not happen as I'm passing the `mimetype` directly into the dict returned from the url fetcher so it should not infer it from the url.

What am I missing here?

**Comment by liZe** [comment]
Hello!

This error probably means that GDKPixbuf tried to read the image bytes, but found that it wasn’t an image. It’s not related to the mimetype, it’s related to the content of the `string`.

I suspect that what you get from `image_bytes.read()` isn’t the binary string of an image. I don’t really understand why you have:
```python
r = requests.get(url, stream=True)
r.raw.decode_content = True
image_bytes = io.BytesIO(r.content)
return dict(string=image_bytes.read(), mime_type='image/png')
```

For example, with an URL of a public image, this works:
```python
image_bytes = requests.get('https://weasyprint.org/css/img/sun.png').content
return dict(string=image_bytes, mime_type='image/png')
```

You can try to log what `image_bytes.read()` is in your example, and you’ll probably find that it’s not a valid PNG content for some reason (because it’s been decoded as if it was an Unicode stream, or because it’s actually an HTML page with the PNG in it, or…).

**Comment by guidocioni** [comment]
> Hello!
> 
> This error probably means that GDKPixbuf tried to read the image bytes, but found that it wasn’t an image. It’s not related to the mimetype, it’s related to the content of the `string`.
> 
> I suspect that what you get from `image_bytes.read()` isn’t the binary string of an image. I don’t really understand why you have:
> 
> ```python
> r = requests.get(url, stream=True)
> r.raw.decode_content = True
> image_bytes = io.BytesIO(r.content)
> return dict(string=image_bytes.read(), mime_type='image/png')
> ```
> 
> For example, with an URL of a public image, this works:
> 
> ```python
> image_bytes = requests.get('https://weasyprint.org/css/img/sun.png').content
> return dict(string=image_bytes, mime_type='image/png')
> ```
> 
> You can try to log what `image_bytes.read()` is in your example, and you’ll probably find that it’s not a valid PNG content for some reason (because it’s been decoded as if it was an Unicode stream, or because it’s actually an HTML page with the PNG in it, or…).

yeah, you were right. The problem was that, for some reason, on the system that I'm running this on, the URL with the image returns an empty response. The error message misled me :)
