### ISSUE TITLE
PixBuf not recognizing image format

### ISSUE THREAD

**Issue by vwasteels** [Kozea/WeasyPrint#1377]
Hello,

I just installed weasyprint and some dependencies , I'm struggling to get it to work properly, I am getting this for a moment now : 

```bash
ERROR: Failed to load image at "http://indivisible.test/projets/1" (Pixbuf error: Format d’image non reconnu)
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/weasyprint/__main__.py", line 214, in main
    getattr(html, 'write_' + format_)(output, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/weasyprint/__init__.py", line 222, in write_pdf
    self.render(
  File "/usr/local/lib/python3.9/site-packages/weasyprint/document.py", line 698, in write_pdf
    int(round(y * scale)))
ValueError: cannot convert float NaN to integer
```

I'm working on MacOS 10.14.6 with Python 3.8 , everything has been installed with HomeBrew

Any tought on this ?
Thanks a lot !!

**Comment by liZe** [comment]
Hello!

Could you please attach the file given by `wget http://indivisible.test/projets/1`? It’s probably not an image or an unsupported format.

**Comment by liZe** [comment]
(By the way, it shouldn’t crash, we have to fix this too.)

**Comment by vwasteels** [comment]
Thanks for this hint, I just found the image causing this and removed it ! thanks !!

**Comment by liZe** [comment]
(Reopening, because there’s a crash that we have to fix, even when the image doesn’t work.)

**Comment by liZe** [comment]
No more GDK-Pixbuf, no more crash :wink:.
