### ISSUE TITLE
Image Not Rendering

### ISSUE THREAD

**Issue by Archetype90** [Kozea/WeasyPrint#1381]
I am attempting to render an image on my PDF. I am generating my PDF like so:

```
    html = HTML(string=source_html)
    base_url = os.path.dirname(os.path.realpath(__file__))
    css = CSS("./templates/template.css", base_url=base_url)
    html.write_pdf(output_filename, stylesheets=[css])
```

I was originally getting the following error:

> Relative URI reference without a base URI: < img src here>

I am able to successfully render a background image using CSS, which makes this all the more weird. When I am trying to put an image directly on the page (either through CSS, content:url("") or in an img tag with src="") it does not work. 

After some reading, it led me to add the base_url property, which I thought would get rid of the error, but it still exists when I am attempting to put the image on the page with an img tag src="". I have also attempted to render the image using content:url("") from the CSS, as that works with the background image, but no luck. When I try to render the image through CSS it no longer shows the Relative URI error (no errors at all in the log), but it does not show up. 

Any help would be greatly appreciated. I was certain I was successfully rendering images much earlier today, but I have not been able to get myself back to that state and I am not sure what has caused the issue.

I did try to revert back to:

`HTML('http://weasyprint.org/').write_pdf('/tmp/weasyprint-website.pdf')`

With inline CSS after reading somewhere that the base_url property is only needed for CSS and thinking that may have been where things went wrong, but no luck. In fact, I took a step backwards, as the background image was not rendering. 

Any help would be **greatly** appreciated.

**Comment by Archetype90** [comment]
So it occurred this morning that during my development I switched from using an HTML file to an HTML string. That was the issue. 

```
    html = HTML(**filename**="template.html")
    base_url = os.path.dirname(os.path.realpath(__file__))
    css = CSS("./templates/template.css", base_url=base_url)
    html.write_pdf(output_filename, stylesheets=[css])
```

Updating the original code in my answer to the above HTML(filename="") instead of HTML(string="") fixes the issue. The problem is I am using Jinja to render my template as a string. If it is not possible to get this working one possible solution is for me to save the Jinja returned string as a file and convert it that way, but I would prefer to avoid that extra step, especially writing to disk.

**Comment by Tontyna** [comment]
What happens, when you give the `HTML()` a `base_url`, too:

```python
base_url = os.path.dirname(os.path.realpath(__file__))
html = HTML(string=source_html, base_url=base_url)
css = CSS("./templates/template.css", base_url=base_url)
html.write_pdf(output_filename, stylesheets=[css])

```

**Comment by Archetype90** [comment]
> What happens, when you give the `HTML()` a `base_url`, too:
> 
> ```python
> base_url = os.path.dirname(os.path.realpath(__file__))
> html = HTML(string=source_html, base_url=base_url)
> css = CSS("./templates/template.css", base_url=base_url)
> html.write_pdf(output_filename, stylesheets=[css])
> ```

Great stuff, this fixed it. Such a simple solution. I swore I had tried that earlier and was told it was an invalid parameter, but I must have done something wrong then. Thank you very much for your assistance.

**Comment by developer992** [comment]
so base_url should be url or path to local filesystem ?
