### ISSUE TITLE
Page widget size

### ISSUE THREAD

**Issue by GMKBabu777** [Kozea/WeasyPrint#1385]
I tried to create a pdf from html, table columns were added at random. When exporting to PDF it cut the last column.

Expected output
![image](https://user-images.githubusercontent.com/47376118/123679744-7d467c80-d865-11eb-83ba-72512e93ada1.png)

Actually Output:
![image](https://user-images.githubusercontent.com/47376118/123679708-6e5fca00-d865-11eb-9b16-bd6eea61c934.png)

Can you please tell me how to fix this?

**Comment by grewn0uille** [comment]
Hello!
Can you please share your HTML/CSS file?

**Comment by meganensar** [comment]
[pdf_template.zip](https://github.com/Kozea/WeasyPrint/files/6730537/pdf_template.zip)
Hello,

Here is the file I used.

**Comment by GMKBabu777** [comment]
Hello,

Here is the file I used.
[pdf_template.zip](https://github.com/Kozea/WeasyPrint/files/6730568/pdf_template.zip)

**Comment by grewn0uille** [comment]
So, some columns are cut because the table is too big and doesn’t fit the dimensions of the page.

**Comment by GMKBabu777** [comment]
Yes

**Comment by grewn0uille** [comment]
You can try to reduce paddings/margins, font-size… to make the table fits

**Comment by liZe** [comment]
@GMKBabu777 Is there something more we could do for you?
