### ISSUE TITLE
write_pdf crashes during font optimisation when glyphs are missing in 53b2

### ISSUE THREAD

**Issue by circlingthesun** [Kozea/WeasyPrint#1386]
Try create a PDF containing "부산시 " with Open Sans or any other font without korean glyphs. The resulting stack trace is:

```
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/__init__.py", line 180, in write_pdf
    self.render(
  File "/usr/local/lib/python3.8/dist-packages/weasyprint/document.py", line 1219, in write_pdf
    subsetter.subset(ttfont)
  File "/usr/local/lib/python3.8/dist-packages/fontTools/subset/__init__.py", line 2899, in subset
    self._closure_glyphs(font)
  File "/usr/local/lib/python3.8/dist-packages/fontTools/subset/__init__.py", line 2718, in _closure_glyphs
    raise self.MissingGlyphsSubsettingError(self.glyphs_missing)
fontTools.subset.Subsetter.MissingGlyphsSubsettingError: {268481280, 268483968, 268488896, 268486660, 268490244, 268486180, 268485284, 268480008, 268486565, 268479852, 268484784, 268484913, 268486320, 268486677, 268490296, 268481497, 268485340}

```

A workaround is to pass write_pdf `optimize_size=()`.

**Comment by circlingthesun** [comment]
On version 52.5 I got tofu characters instead of a crash. I managed to get rid of the error by installing the 'fonts-noto-cjk' package on Ubuntu, and at the same time got rid of the tofu characters. I'm assuming the noto font is being used a fallback. The only problem is that my PDF grew to 16mb from the original 67kb in version 52.5. That's without setting the optimize_size parameter to an empty tuple. I'm assuming the whole fallback is being embedded.

**Comment by liZe** [comment]
Hello! Thanks a lot for this report.

It’s not easy to test, because most systems have a fallback font for virtually any character, but it seems to work now. With 52.5, Cairo was probably able to insert a tofu character for missing glyphes.

Feel free to test, I hope that the generated document is valid.
