### ISSUE TITLE
API-reference on readthedocs?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [Kozea/WeasyPrint#1390]
I see the API is nice documented in the code itself and well prepared to be parsed by a (semi)auto-documentation-tool (e.g. Doxygen, Sphinx, ...)
https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/__init__.py

But I can not find the API reference in your readthedocs.

Did I missed it?

And by the way I find two readthedocs:
https://weasyprint.readthedocs.io/en/latest/index.html
https://doc.courtbouillon.org/weasyprint/latest/#

**Comment by liZe** [comment]
Hello!

> But I can not find the API reference in your readthedocs.
> 
> Did I missed it?

Sorry, the "latest" version of the documentation was missing the API part. it’s fixed now, thanks for the report!

> And by the way I find two readthedocs:

Yes, that’s a problem we’re aware of. We’ll redirect ReadTheDocs to CourtBouillon’s website soon.
