### ISSUE TITLE
53.0b2 generate much larger PDF (and much slower)

### ISSUE THREAD

**Issue by leesei** [Kozea/WeasyPrint#1392]
Original issue is PDF file too big (#969).  
53.0b2 should have fixed it but it didn't resolve the issue.

> It took 48 seconds to create the PDF of 141MB (the CPU load was not high).
> v52.5 took 13 seconds to create the PDF of 5.9MB.

Repo to reproduce this issue: https://github.com/leesei/WeasyPrint_1392

**Comment by takesson** [comment]
I am also seeing very large PDFs but I have not yet isolated it.

**Comment by liZe** [comment]
Improvements have been made on the master branch about image management. Tests are welcome!

> It took 48 seconds to create the PDF of 141MB (the CPU load was not high).
> v52.5 took 13 seconds to create the PDF of 5.9MB.

@leesei Here are the new results on my computer:
- 52.5: 21s, 5.8M PDF
- master: 23s, 2.4M PDF

That’s not bad ;). Image management is not perfect yet, we have performance loss with some cases, but it should be good enough for version 53. Feel free to test!

> I am also seeing very large PDFs but I have not yet isolated it.

Don’t hesitate to send us some samples, we can easily compare performance between WeasyPrint versions.

**Comment by leesei** [comment]
Great, thanks a lot.
I'm glad my use case helped to improve the project.

**Comment by leesei** [comment]
Is there any plan for a 53.0b3 release?
I can help validate and close these two issues.

Or would you like them closed when 53.0 is offcial?

**Comment by liZe** [comment]
> Is there any plan for a 53.0b3 release?

Next version will be 53.0, no 53.0b3 is planned.

> I can help validate and close these two issues.

Thanks a lot. The best solution for that is to try the current master branch, using `pip install git+https://github.com/Kozea/WeasyPrint.git`.

**Comment by takesson** [comment]
I found that it is important to run
```
pip3 uninstall weasyprint
```
before
```
pip3 install git+https://github.com/Kozea/WeasyPrint.git
```

**Comment by takesson** [comment]
Installing from current master branch did resolve #1394 but had no effect on the PDF size for my test document.

**Comment by liZe** [comment]
> Installing from current master branch did resolve #1394 but had no effect on the PDF size for my test document.
> 
> I should mention that I am getting:
> 
> ```
> WARNING: Unable to optimize font
> ```

Then the original problem caused by image management is probably solved. We’ll continue the discussion about optimized fonts in #1393.
