### ISSUE TITLE
Lettered ordered list <ol type="a"> ignored

### ISSUE THREAD

**Issue by bubonicfred** [Kozea/WeasyPrint#1397]
I'm using weasyprint via pandoc to convert markdown documents to pdf.
I have a lettered list i.e
a. Item one
b. item two
pandocs fancy_list extension interprets this as a lettered list instead of a numbered list thus outputs HTML as `<ol type="a">`
testing with prince this renders as a lettered list as desired, however weasyprint renders it as a numbered list.
weasyprint ver. 52.5

**Comment by grewn0uille** [comment]
Hello!

`type="a"` is a presentational hints and it’s not supported by default.
You can use the `--presentational-hints` parameter to enable it (by using `--pdf-engine-opt` pandoc option).

**Comment by bubonicfred** [comment]
Thank you! works now.
Looking forward to ver 53
