### ISSUE TITLE
Multiple page orientations / Workaround for wide tables

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [Kozea/WeasyPrint#1398]
I know about the problems with to big/wide tables (e.g. https://github.com/Kozea/WeasyPrint/issues/36) and understand how WeasyPrint work with this currently. This is not a bug report about that problem!

In my case I do not want to modify the big tables but I want to modify the related PDF pages. I want to change there orientation to horizontal and/or make them bigger (e.g. A3 or A2).

But I want to do this just for the one page with the big table not for all.

Technically (for Python3) broken down my questions:

1. Can I have different page orientations and sizes in one PDF file? And how do I do this? e.g. a piece of html-code like `<pdf:page-break:horizontal>` and after the table-code back `<pdf:page-break:default>`.
2. Is there a way check if a table is to wide for a page, e.g. a warning or an Exception.

**Comment by grewn0uille** [comment]
Hello!

> Can I have different page orientations and sizes in one PDF file? And how do I do this? e.g. a piece of html-code like <pdf:page-break:horizontal> and after the table-code back <pdf:page-break:default>.

Yes you can have different page orientations and sizes in a PDF file.
To do that, you can use `@page` CSS at-rule.

For example, if your HTML looks like:
```html
<div>bonjour</div>
<div class="horizontal">hello</div>
```
And your CSS:
```css
@page my_page {
    size: landscape;
}

.horizontal {
    page: my_page;
}
```
The first div will be on a portrait page, and the second one will be on a other page in landscape mode.

> Is there a way check if a table is to wide for a page, e.g. a warning or an Exception.
No there isn’t.

**Comment by liZe** [comment]
@Codeberg-AsGithubAlternative-buhtz Is there anything more we can do for you?
