### ISSUE TITLE
SVG rendered completely wrong in 53.0b2

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1403]
The HTML + SVG from 

https://www.dropbox.com/sh/asmhy3zwsv5ul5w/AACB-47TDaukvBGBp57Q6Bera?dl=0

is rendered completely wrong:

<img width="994" alt="Bildschirmfoto 2021-07-23 um 14 16 12" src="https://user-images.githubusercontent.com/594239/126780409-118991f7-21e3-4bb5-a4dd-a203f5ce166b.png">

**Comment by liZe** [comment]
Thanks for this bug report.

I’ve been writing SVG renderers for more than 10 years, and I’ve learned today that `x` and `y` don’t work **at all** as I’ve always believed.

Another fun fact: this SVG is not rendered at all with previous versions of WeasyPrint, it actually makes CairoSVG crash.

Another problem: the font used seems to be bold, but it shouldn’t be. I’ll fix that in another commit.
