### ISSUE TITLE
SVG: New regression related to transformations

### ISSUE THREAD

**Issue by pbregener** [Kozea/WeasyPrint#1408]
This is just a heads-up for now, a more detailed report (in this issue) will follow when I have the time.

The recent changes in commit 8d7bcead0ac4a2ecf104185b275ed9f25d31091d introduced some major regression(s) for me and various SVG elements end up misplaced now.

**Comment by grewn0uille** [comment]
Hello!

We just push https://github.com/Kozea/WeasyPrint/commit/11a175efc78fdf0d81e3dc8f76a89c7cade17ca1 to handle x and y in use tags. Maybe it’s the issue you encounter.

**Comment by pbregener** [comment]
Hi!
Thanks! And yes, I can confirm that it is fixed on `master` now :)
