### ISSUE TITLE
encoder jpeg2k not available on v53.0

### ISSUE THREAD

**Issue by hildogjr** [Kozea/WeasyPrint#1412]
I am generating a PDF file using weasyprint. I was previous using v52.5 and now I updated to v53.0 by the flollowed calls:

```python
# On weasyprint 52.5
printer.write_pdf(file_name_report,
                  stylesheets=report_css,
                  font_config=font_config,
                  optimize_images=True,  # Optimize the image size (resolution into the PDF?).
                  presentational_hints=True)  # Follow the image aspects given into the HTML.
```

```python
# On weasyprint 53.0
printer.write_pdf(file_name_report,
                  stylesheets=report_css,
                  font_config=font_config,
                  optimize_size=('fonts', 'images',)
                  presentational_hints=True)  # Follow the image aspects given into the HTML.
```

But got the bellow error on v53.0:

```
Exception has occurred: OSError
encoder jpeg2k not available

During handling of the above exception, another exception occurred:


```

System information:
Weasyprint 53.0
Python 3.8.10
OS Ubuntu 20.04

My PDF have PNG and JPG images. Is this error caused by the [libcairo removing](https://www.courtbouillon.org/blog/00009-weasyprint-53-what-s-new)?

**Comment by grewn0uille** [comment]
Hello!
You get this error because the version of Pillow you use is not compiled with jpeg 2000 support (you’re probably using the python3-pil package).
You can use the wheel which comes with jpeg 2000 support or compile Pillow yourself with the [needed dependencies](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#ubuntu-20-04).

**Comment by hildogjr** [comment]
My python pillow package was 7.0.0, I updated to the most recent and worked fine.
```
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (7.0.0)
Collecting pillow
  Downloading Pillow-8.3.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 1.9 MB/s 
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 7.0.0
    Uninstalling Pillow-7.0.0:
      Successfully uninstalled Pillow-7.0.0
```


But the https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#installation list `Pillow ≥ 4.0.0`, should we update https://github.com/Kozea/WeasyPrint/blob/master/pyproject.toml file? (I am proposing to pump the requirement version o pillow)

I am listing all dependencies versions:

| Python dependence name | My used version | List on doc list |
| ---  | -----------|----------------------|
| Python | 3.8.5 | 3.6+ |
| pydyf | 0.02 | >= 0.0.3 |
| cffi | 1.14.5 | >=0.6 |
| html5lib | 1.1 |  >=1.0.1 |
| tinycss2 | 1.1.0 | >=1.0.0 |
| 'cssselect2 | 0.4.4 | >=0.1 |
| Pyphen | ?? | >=0.9.1' |
| Pillow | **Last one** | >=4.0.0 |
| fonttools[woff] | ?? | >=4.0.0 |

**Comment by hildogjr** [comment]
@grewn0uille could you re-open this issue mark https://github.com/Kozea/WeasyPrint/pull/1413 for validation?

**Comment by grewn0uille** [comment]
According to the [Pillow documentation](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-2000), jpeg 2000 format was introduce in version 2.4.0.
We also tested with Pillow 7.0.0 and 6.0.0, and it works.

Maybe you compiled the previous Pillow without jpeg 2000 support and when updating, you get the wheel with jpeg 2000 support.

**Comment by hildogjr** [comment]
You are right, even installing weasyprint by `pip` with `pillow==6.2.2` already in the system (requirement of matplotlib 3.3.4), it was just needed a `pillow` reinstall.

I made the regression and its works fine with the weasyprint requirements.
