### ISSUE TITLE
PDF file size almost double in v53

### ISSUE THREAD

**Issue by hildogjr** [Kozea/WeasyPrint#1414]
I am reporting a issue that is affecting my migrating from WeasyPrint 52.5 to 53.0, as part of the issues on https://github.com/Kozea/WeasyPrint/issues/1412 (fix on https://github.com/Kozea/WeasyPrint/pull/1413): the PDF file almost double the size by using the bellow configurations on a report template example:

```python
# On weasyprint 52.5
font_config = weasyprint.fonts.FontConfiguration()
report_css = [weasyprint.CSS(filename=resource_path_join('report.css'), font_config=font_config)]
printer.write_pdf(file_name_report,
                  stylesheets=report_css,
                  font_config=font_config,
                  optimize_images=True,  # Optimize the image size (resolution into the PDF?).
                  presentational_hints=True)  # Follow the image aspects given into the HTML.
```
Found in https://hildogjr.gitlab.io/unicamp-electric-inventory/ (28.5MB)

```python
# On weasyprint 53.0
font_config = weasyprint.text.fonts.FontConfiguration()
report_css = [weasyprint.CSS(filename=resource_path_join('report.css'), font_config=font_config)]
printer.write_pdf(file_name_report,
                  stylesheets=report_css,
                  font_config=font_config,
                  optimize_size=('fonts', 'images',)
                  presentational_hints=True)  # Follow the image aspects given into the HTML.
```
(40.6MB) I could not attach the file.

**Comment by liZe** [comment]
Hello!

Could you please share your HTML, CSS and static files used to generate this document?

**Comment by hildogjr** [comment]
The file to convert is the "Relatório.html" with all static files on "Temporary". It appear to be not related with the JPG files, bellow a comparative (+/- temporary folder images and weasyprint version):

```
ls Relatório* -l
-rw-rw-r-- 1 lab lab 28492964 ago  2 16:00 Relatório+images_v52.pdf
-rw-rw-r-- 1 lab lab  3097807 ago  2 18:05 Relatório--images_v52.pdf
-rw-rw-r-- 1 lab lab 40594437 ago  2 15:52 Relatório+images_v53.pdf
-rw-rw-r-- 1 lab lab 15406735 ago  2 17:54 Relatório--images_v53.pdf
```

Compiling without the "Temparary" images folder I got 3.1MB on v52.5 and 15.4MB on v53.0.

The file is a 7z compressed file, I had to change de extension to attach here.
[Files for weasyprint.7z.txt](https://github.com/Kozea/WeasyPrint/files/6919592/Files.for.weasyprint.7z.txt)

**Comment by liZe** [comment]
The problem was caused by images not being deduplicated when they were included in patterns. In your case, the watermark displayed on each page was displayed as a pattern (because it’s a background), and the image was though embedded in the document **for each page** (+600 times).

Thanks a lot for the report and for your sample!

**Comment by hildogjr** [comment]
Confirmed now a reduction of 211kB compared with v52.5.
