### ISSUE TITLE
The procedure entry point inflateValidate could not be located in the dynamic link library libpng16-16.dll  / cannot load library 'pango-1.0'

### ISSUE THREAD

**Issue by Lorenzo-ITA** [Kozea/WeasyPrint#1415]
# In a nutshell
Hi all!
I want to create a conda environment with WeasyPrint and an other package (Prophet).
If I try to install WeasyPrint alone in the environment it works, after I install Prophet if I try WeasyPrint it gives me an error.

<pre><code> 
conda create -n myenv python=3.8
conda activate myenv38
conda install -c conda-forge weasyprint
weasyprint http://weasyprint.org pdf_test.pdf                            -> works
conda install -c conda-forge prophet
weasyprint http://weasyprint.org pdf_test.pdf                            -> Errors...
conda uninstall prophet
weasyprint http://weasyprint.org pdf_test.pdf                            -> works
</code></pre>

# Step by Step

I start creating the environment

#### **conda create -n myenv python=3.8**
<pre><code> 
  added / updated specs:
    - python=3.8

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2021.7.5-haa95532_1
  certifi            pkgs/main/win-64::certifi-2021.5.30-py38haa95532_0
  openssl            pkgs/main/win-64::openssl-1.1.1k-h2bbff1b_0
  pip                pkgs/main/win-64::pip-21.1.3-py38haa95532_0
  python             pkgs/main/win-64::python-3.8.10-hdbf39b2_7
  setuptools         pkgs/main/win-64::setuptools-52.0.0-py38haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.36.0-h2bbff1b_0
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py38_0
</code></pre>

I activate it...
#### **conda activate myenv38**
...and install WeasyPrint.
#### **conda install -c conda-forge weasyprint**

<pre><code> 
  added / updated specs:
    - weasyprint

The following NEW packages will be INSTALLED:

  cairo              conda-forge/win-64::cairo-1.16.0-hb19e0ff_1008
  cairocffi          conda-forge/noarch::cairocffi-1.2.0-pyhd8ed1ab_0
  cairosvg           conda-forge/noarch::cairosvg-2.5.2-pyhd8ed1ab_0
  cffi               conda-forge/win-64::cffi-1.14.6-py38hd8c33c5_0
  cssselect2         conda-forge/noarch::cssselect2-0.2.1-pyh9f0ad1d_1
  defusedxml         conda-forge/noarch::defusedxml-0.7.1-pyhd8ed1ab_0
  fontconfig         conda-forge/win-64::fontconfig-2.13.1-h1989441_1005
  freetype           conda-forge/win-64::freetype-2.10.4-h546665d_1
  fribidi            conda-forge/win-64::fribidi-1.0.10-h8d14728_0
  gdk-pixbuf         conda-forge/win-64::gdk-pixbuf-2.42.6-h1c5aac7_0
  gettext            conda-forge/win-64::gettext-0.19.8.1-h1a89ca6_1005
  glib               conda-forge/win-64::glib-2.68.3-h0e60522_0
  glib-tools         conda-forge/win-64::glib-tools-2.68.3-h0e60522_0
  html5lib           conda-forge/noarch::html5lib-1.1-pyh9f0ad1d_0
  icu                conda-forge/win-64::icu-68.1-h0e60522_0
  jbig               conda-forge/win-64::jbig-2.1-h8d14728_2003
  jpeg               conda-forge/win-64::jpeg-9d-h8ffe710_0
  lcms2              conda-forge/win-64::lcms2-2.12-h2a16943_0
  lerc               conda-forge/win-64::lerc-2.2.1-h0e60522_0
  libdeflate         conda-forge/win-64::libdeflate-1.7-h8ffe710_5
  libffi             conda-forge/win-64::libffi-3.3-h0e60522_2
  libglib            conda-forge/win-64::libglib-2.68.3-h1e62bf3_0
  libiconv           conda-forge/win-64::libiconv-1.16-he774522_0
  libpng             conda-forge/win-64::libpng-1.6.37-h1d00b33_2
  libtiff            conda-forge/win-64::libtiff-4.3.0-h0c97f57_1
  libxml2            conda-forge/win-64::libxml2-2.9.12-hf5bbc77_0
  lz4-c              conda-forge/win-64::lz4-c-1.9.3-h8ffe710_1
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openjpeg           conda-forge/win-64::openjpeg-2.4.0-hb211442_1
  pango              conda-forge/win-64::pango-1.42.4-hec34917_5
  pcre               conda-forge/win-64::pcre-8.45-h0e60522_0
  pillow             conda-forge/win-64::pillow-8.3.1-py38h794f750_0
  pixman             conda-forge/win-64::pixman-0.40.0-h8ffe710_0
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyphen             conda-forge/noarch::pyphen-0.11.0-pyhd8ed1ab_0
  python_abi         conda-forge/win-64::python_abi-3.8-2_cp38
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  tinycss2           conda-forge/noarch::tinycss2-1.1.0-pyhd8ed1ab_0
  tk                 conda-forge/win-64::tk-8.6.10-h8ffe710_1
  weasyprint         conda-forge/noarch::weasyprint-52.5-pyhd8ed1ab_1
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1
  zlib               conda-forge/win-64::zlib-1.2.11-h62dcd97_1010
  zstd               conda-forge/win-64::zstd-1.5.0-h6255e5f_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2021.7.5-h~ --> conda-forge::ca-certificates-2021.5.30-h5b45459_0
  certifi            pkgs/main::certifi-2021.5.30-py38haa9~ --> conda-forge::certifi-2021.5.30-py38haa244fe_0
  openssl              pkgs/main::openssl-1.1.1k-h2bbff1b_0 --> conda-forge::openssl-1.1.1k-h8ffe710_0
</code></pre>

If I try WeasyPrint...
#### **weasyprint http://weasyprint.org pdf_test.pdf**

It works (it gives me WARNINGS but it's normal).
After that I try to install Prophet.

#### **conda install -c conda-forge prophet**

<pre><code> 
  added / updated specs:
    - prophet

The following NEW packages will be INSTALLED:

  arviz              conda-forge/noarch::arviz-0.11.2-pyhd8ed1ab_1
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  cftime             conda-forge/win-64::cftime-1.5.0-py38hcb5f9af_0
  colorama           conda-forge/noarch::colorama-0.4.4-pyh9f0ad1d_0
  convertdate        conda-forge/noarch::convertdate-2.3.2-pyhd8ed1ab_0
  curl               conda-forge/win-64::curl-7.78.0-h789b8ee_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  cython             conda-forge/win-64::cython-0.29.24-py38h885f38d_0
  ephem              conda-forge/win-64::ephem-4.0.0.2-py38h294d835_0
  hdf4               conda-forge/win-64::hdf4-4.2.15-h0e5069d_3
  hdf5               conda-forge/win-64::hdf5-1.10.6-nompi_h5268f04_1114
  hijri-converter    conda-forge/noarch::hijri-converter-2.1.3-pyhd8ed1ab_0
  holidays           conda-forge/noarch::holidays-0.11.2-pyhd8ed1ab_0
  intel-openmp       conda-forge/win-64::intel-openmp-2021.3.0-h57928b3_3372
  kiwisolver         conda-forge/win-64::kiwisolver-1.3.1-py38hbd9d945_1
  korean_lunar_cale~ conda-forge/noarch::korean_lunar_calendar-0.2.1-pyh9f0ad1d_0
  krb5               conda-forge/win-64::krb5-1.19.2-hbae68bd_0
  libblas            conda-forge/win-64::libblas-3.9.0-10_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-10_mkl
  libcurl            conda-forge/win-64::libcurl-7.78.0-h789b8ee_0
  liblapack          conda-forge/win-64::liblapack-3.9.0-10_mkl
  libnetcdf          conda-forge/win-64::libnetcdf-4.8.0-nompi_hf689e7d_103
  libpython          conda-forge/win-64::libpython-2.0-py38haa244fe_1
  libssh2            conda-forge/win-64::libssh2-1.9.0-h680486a_6
  libzip             conda-forge/win-64::libzip-1.8.0-hfed4ece_0
  lunarcalendar      conda-forge/noarch::lunarcalendar-0.0.9-py_0
  m2w64-binutils     conda-forge/win-64::m2w64-binutils-2.25.1-5
  m2w64-bzip2        conda-forge/win-64::m2w64-bzip2-1.0.6-6
  m2w64-crt-git      conda-forge/win-64::m2w64-crt-git-5.0.0.4636.2595836-2
  m2w64-gcc          conda-forge/win-64::m2w64-gcc-5.3.0-6
  m2w64-gcc-ada      conda-forge/win-64::m2w64-gcc-ada-5.3.0-6
  m2w64-gcc-fortran  conda-forge/win-64::m2w64-gcc-fortran-5.3.0-6
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gcc-objc     conda-forge/win-64::m2w64-gcc-objc-5.3.0-6
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-headers-git  conda-forge/win-64::m2w64-headers-git-5.0.0.4636.c0ad18a-2
  m2w64-isl          conda-forge/win-64::m2w64-isl-0.16.1-2
  m2w64-libiconv     conda-forge/win-64::m2w64-libiconv-1.14-6
  m2w64-libmangle-g~ conda-forge/win-64::m2w64-libmangle-git-5.0.0.4509.2e5a9a2-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  m2w64-make         conda-forge/win-64::m2w64-make-4.1.2351.a80a8b8-2
  m2w64-mpc          conda-forge/win-64::m2w64-mpc-1.0.3-3
  m2w64-mpfr         conda-forge/win-64::m2w64-mpfr-3.1.4-4
  m2w64-pkg-config   conda-forge/win-64::m2w64-pkg-config-0.29.1-2
  m2w64-toolchain    conda-forge/win-64::m2w64-toolchain-5.3.0-7
  m2w64-toolchain_w~ conda-forge/win-64::m2w64-toolchain_win-64-2.4.0-0
  m2w64-tools-git    conda-forge/win-64::m2w64-tools-git-5.0.0.4592.90b8472-2
  m2w64-windows-def~ conda-forge/win-64::m2w64-windows-default-manifest-6.4-3
  m2w64-winpthreads~ conda-forge/win-64::m2w64-winpthreads-git-5.0.0.4634.697f757-2
  m2w64-zlib         conda-forge/win-64::m2w64-zlib-1.2.8-10
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.4.2-py38heae8d8c_0
  mkl                conda-forge/win-64::mkl-2021.3.0-hb70f87d_564
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  netcdf4            conda-forge/win-64::netcdf4-1.5.7-nompi_py38h58ef0d0_100
  numpy              conda-forge/win-64::numpy-1.21.1-py38h09042cb_0
  packaging          conda-forge/noarch::packaging-21.0-pyhd8ed1ab_0
  pandas             conda-forge/win-64::pandas-1.3.1-py38h60cbd38_0
  prophet            conda-forge/win-64::prophet-1.0.1-py38h43734a8_3
  pymeeus            conda-forge/noarch::pymeeus-0.5.10-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pystan             conda-forge/win-64::pystan-2.19.1.1-py38h02adce6_3
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  pytz               conda-forge/noarch::pytz-2021.1-pyhd8ed1ab_0
  scipy              conda-forge/win-64::scipy-1.7.0-py38he847743_0
  tbb                conda-forge/win-64::tbb-2021.3.0-h2d74725_0
  tornado            conda-forge/win-64::tornado-6.1-py38h294d835_1
  tqdm               conda-forge/noarch::tqdm-4.62.0-pyhd8ed1ab_0
  typing_extensions  conda-forge/noarch::typing_extensions-3.10.0.0-pyha770c72_0
  xarray             conda-forge/noarch::xarray-0.19.0-pyhd8ed1ab_1
</code></pre>

#### **weasyprint http://weasyprint.org pdf_test.pdf**
Result: (image below)
*python.exe - Entry Point Not Found
   The procedure entry point inflateValidate could not be 
   located in the dynamic link library.
   C:\Program Files\GTK3-Runtime Win64\bin\libpng16-16.dll.*
![image](https://user-images.githubusercontent.com/87006364/127977152-bd29e628-bbf8-4c97-ad04-64771c2beb58.png)
when i click ok, it gives me the same error again.
![image](https://user-images.githubusercontent.com/87006364/127977530-10fcac8e-337a-46bd-8b6c-acb54db0d332.png)

And in terminal:
<pre><code>
Traceback (most recent call last):
  File "C:\Users\abc\miniconda3\envs\myenv38\Scripts\weasyprint-script.py", line 5, in <module>
    from weasyprint.__main__ import main
  File "C:\Users\abc\miniconda3\envs\myenv38\lib\site-packages\weasyprint\__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\abc\miniconda3\envs\myenv38\lib\site-packages\weasyprint\css\__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\abc\miniconda3\envs\myenv38\lib\site-packages\weasyprint\css\computed_values.py", line 15, in <module>
    from .. import text
  File "C:\Users\abc\miniconda3\envs\myenv38\lib\site-packages\weasyprint\text.py", line 260, in <module>
    pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0', 'libpango-1.0.so.0',
  File "C:\Users\abc\miniconda3\envs\myenv38\lib\site-packages\weasyprint\text.py", line 255, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\Users\abc\miniconda3\envs\myenv38\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\abc\miniconda3\envs\myenv38\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\abc\miniconda3\envs\myenv38\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0'
</code></pre>

If i try to uninstall Prophet...

#### **conda uninstall prophet**

<pre><code>
  removed specs:
    - prophet

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libpng-1.6.37              |       h2a8f88b_0         333 KB
    ------------------------------------------------------------
                                           Total:         333 KB

The following packages will be REMOVED:

  arviz-0.11.2-pyhd8ed1ab_1
  bzip2-1.0.8-h8ffe710_4
  cftime-1.5.0-py38hcb5f9af_0
  colorama-0.4.4-pyh9f0ad1d_0
  convertdate-2.3.2-pyhd8ed1ab_0
  curl-7.78.0-h789b8ee_0
  cycler-0.10.0-py_2
  cython-0.29.24-py38h885f38d_0
  ephem-4.0.0.2-py38h294d835_0
  hdf4-4.2.15-h0e5069d_3
  hdf5-1.10.6-nompi_h5268f04_1114
  hijri-converter-2.1.3-pyhd8ed1ab_0
  holidays-0.11.2-pyhd8ed1ab_0
  intel-openmp-2021.3.0-h57928b3_3372
  jbig-2.1-h8d14728_2003
  kiwisolver-1.3.1-py38hbd9d945_1
  korean_lunar_calendar-0.2.1-pyh9f0ad1d_0
  krb5-1.19.2-hbae68bd_0
  lcms2-2.12-h2a16943_0
  lerc-2.2.1-h0e60522_0
  libblas-3.9.0-10_mkl
  libcblas-3.9.0-10_mkl
  libcurl-7.78.0-h789b8ee_0
  libdeflate-1.7-h8ffe710_5
  liblapack-3.9.0-10_mkl
  libnetcdf-4.8.0-nompi_hf689e7d_103
  libpython-2.0-py38haa244fe_1
  libssh2-1.9.0-h680486a_6
  libzip-1.8.0-hfed4ece_0
  lunarcalendar-0.0.9-py_0
  m2w64-binutils-2.25.1-5
  m2w64-bzip2-1.0.6-6
  m2w64-crt-git-5.0.0.4636.2595836-2
  m2w64-gcc-5.3.0-6
  m2w64-gcc-ada-5.3.0-6
  m2w64-gcc-fortran-5.3.0-6
  m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-core-5.3.0-7
  m2w64-gcc-objc-5.3.0-6
  m2w64-gmp-6.1.0-2
  m2w64-headers-git-5.0.0.4636.c0ad18a-2
  m2w64-isl-0.16.1-2
  m2w64-libiconv-1.14-6
  m2w64-libmangle-git-5.0.0.4509.2e5a9a2-2
  m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  m2w64-make-4.1.2351.a80a8b8-2
  m2w64-mpc-1.0.3-3
  m2w64-mpfr-3.1.4-4
  m2w64-pkg-config-0.29.1-2
  m2w64-toolchain-5.3.0-7
  m2w64-toolchain_win-64-2.4.0-0
  m2w64-tools-git-5.0.0.4592.90b8472-2
  m2w64-windows-default-manifest-6.4-3
  m2w64-winpthreads-git-5.0.0.4634.697f757-2
  m2w64-zlib-1.2.8-10
  matplotlib-base-3.4.2-py38heae8d8c_0
  mkl-2021.3.0-hb70f87d_564
  msys2-conda-epoch-20160418-1
  netcdf4-1.5.7-nompi_py38h58ef0d0_100
  numpy-1.21.1-py38h09042cb_0
  openjpeg-2.4.0-hb211442_1
  packaging-21.0-pyhd8ed1ab_0
  pandas-1.3.1-py38h60cbd38_0
  prophet-1.0.1-py38h43734a8_3
  pymeeus-0.5.10-pyhd8ed1ab_0
  pyparsing-2.4.7-pyh9f0ad1d_0
  pystan-2.19.1.1-py38h02adce6_3
  python-dateutil-2.8.2-pyhd8ed1ab_0
  python_abi-3.8-2_cp38
  pytz-2021.1-pyhd8ed1ab_0
  scipy-1.7.0-py38he847743_0
  tbb-2021.3.0-h2d74725_0
  tornado-6.1-py38h294d835_1
  tqdm-4.62.0-pyhd8ed1ab_0
  typing_extensions-3.10.0.0-pyha770c72_0
  xarray-0.19.0-pyhd8ed1ab_1

The following packages will be UPDATED:

  ca-certificates    conda-forge::ca-certificates-2021.5.3~ --> pkgs/main::ca-certificates-2021.7.5-haa95532_1

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            conda-forge::certifi-2021.5.30-py38ha~ --> pkgs/main::certifi-2021.5.30-py38haa95532_0
  cffi               conda-forge::cffi-1.14.6-py38hd8c33c5~ --> pkgs/main::cffi-1.14.6-py38h2bbff1b_0
  defusedxml         conda-forge::defusedxml-0.7.1-pyhd8ed~ --> pkgs/main::defusedxml-0.7.1-pyhd3eb1b0_0
  freetype           conda-forge::freetype-2.10.4-h546665d~ --> pkgs/main::freetype-2.10.4-hd328e21_0
  fribidi            conda-forge::fribidi-1.0.10-h8d14728_0 --> pkgs/main::fribidi-1.0.10-h62dcd97_0
  html5lib           conda-forge::html5lib-1.1-pyh9f0ad1d_0 --> pkgs/main::html5lib-1.1-py_0
  icu                      conda-forge::icu-68.1-h0e60522_0 --> pkgs/main::icu-68.1-h6c2663c_0
  libpng              conda-forge::libpng-1.6.37-h1d00b33_2 --> pkgs/main::libpng-1.6.37-h2a8f88b_0
  libtiff             conda-forge::libtiff-4.3.0-h0c97f57_1 --> pkgs/main::libtiff-4.2.0-hd0e1b90_0
  libxml2            conda-forge::libxml2-2.9.12-hf5bbc77_0 --> pkgs/main::libxml2-2.9.12-h0ad7f3c_0
  lz4-c                 conda-forge::lz4-c-1.9.3-h8ffe710_1 --> pkgs/main::lz4-c-1.9.3-h2bbff1b_0
  olefile            conda-forge::olefile-0.46-pyh9f0ad1d_1 --> pkgs/main::olefile-0.46-py_0
  openssl            conda-forge::openssl-1.1.1k-h8ffe710_0 --> pkgs/main::openssl-1.1.1k-h2bbff1b_0
  pcre                    conda-forge::pcre-8.45-h0e60522_0 --> pkgs/main::pcre-8.45-hd77b12b_0
  pillow             conda-forge::pillow-8.3.1-py38h794f75~ --> pkgs/main::pillow-8.3.1-py38h4fa10fc_0
  pixman              conda-forge::pixman-0.40.0-h8ffe710_0 --> pkgs/main::pixman-0.40.0-he774522_0
  pycparser          conda-forge::pycparser-2.20-pyh9f0ad1~ --> pkgs/main::pycparser-2.20-py_2
  six                  conda-forge::six-1.16.0-pyh6c4a22f_0 --> pkgs/main::six-1.16.0-pyhd3eb1b0_0
  tk                      conda-forge::tk-8.6.10-h8ffe710_1 --> pkgs/main::tk-8.6.10-he774522_0
  webencodings       conda-forge/noarch::webencodings-0.5.~ --> pkgs/main/win-64::webencodings-0.5.1-py38_1
  xz                       conda-forge::xz-5.2.5-h62dcd97_1 --> pkgs/main::xz-5.2.5-h62dcd97_0
  zlib               conda-forge::zlib-1.2.11-h62dcd97_1010 --> pkgs/main::zlib-1.2.11-h62dcd97_4
  zstd                   conda-forge::zstd-1.5.0-h6255e5f_0 --> pkgs/main::zstd-1.4.9-h19a0ad4_0
</code></pre>

Now weasyprint works again...

#### **weasyprint http://weasyprint.org pdf_test.pdf**

Result: warnings (as usual) but it works.

Is there any way to solve it?

**Comment by liZe** [comment]
Hello!

This bug is caused by a conflict between Prophet and WeasyPrint in Conda packages. I suppose that the `m2w64` packages break the way libraries are found for some random reason.

Unfortunately, there’s nothing we can really do for you here, as the problem comes from Conda packages, not from WeasyPrint (and actually not from WeasyPrint’s Conda package) :/. You’ll probably get better answers from the Conda maintainers.

What you can do is:
- install WeasyPrint,
- install the m2w64 libraries one by one using Conda, until WeasyPrint fails,
- note the m2w64 package that makes WeasyPrint fail (I’d try `m2w64-pkg-config` and `m2w64-zlib` first),
- report a bug in [this GitHub repository](https://github.com/ContinuumIO/anaconda-issues/issues).

Don’t hesitate to add a link to this issue, so that people with the same problem will find a link to the correct issue (and maybe a solution) :wink:.
