### ISSUE TITLE
Error using weasyprint on django project in IIS windows

### ISSUE THREAD

**Issue by Collin0012** [Kozea/WeasyPrint#1416]
I keep on getting this error below when i import weasyprint in my django project, when i try to run using windows IIS.
attribute error at / '_io.stringio' object has no attribute 'buffer'

**Comment by liZe** [comment]
Hello!

Could you please copy/paste the whole backtrace? It’s easier to know what’s happening with the exact place where the error occured.

**Comment by liZe** [comment]
Feel free to answer and reopen this issue if we can help you.
