### ISSUE TITLE
ModuleNotFoundError: No module named 'weasyprint.fonts'

### ISSUE THREAD

**Issue by judahpaul16** [Kozea/WeasyPrint#1419]
I could not import weasyprint.fonts after clean pip install. This appears to be a bug with version 53. I rolled back to ver 52.5 and all is well.

**Comment by liZe** [comment]
Hello!

> I could not import weasyprint.fonts after clean pip install. This appears to be a bug with version 53. I rolled back to ver 52.5 and all is well.

Could you please provide the whole backtrace please?

**Comment by york-schlabrendorff-liqid** [comment]
Had a similar issue. Apparently the import path has changed. This works for me:

```
from weasyprint.text.fonts import FontConfiguration  # for weasyprint 53
# from weasyprint.fonts import FontConfiguration  # for weasyprint 52
```

**Comment by liZe** [comment]
Oh, of course… The last comment is right. The API change is documented in the [changelog](https://github.com/Kozea/WeasyPrint/releases/tag/v53.0).

**Comment by Alex-CodeLab** [comment]
still not working. 
Release: 5.15.0-52-generic

WeasyPrint version: 57.1
Python version: 3.10.6

**Comment by liZe** [comment]
> still not working.
> Release: 5.15.0-52-generic

The problem is not in Weasyprint, it’s in the code using WeasyPrint. WeasyPrint’s API has changed, there’s no `weasyprint.fonts` module anymore. Use `weasyprint.text.fonts` instead.
