### ISSUE TITLE
Embed JSON

### ISSUE THREAD

**Issue by werk24** [Kozea/WeasyPrint#1423]
Great Library!

We are trying to embed a json document and create a link. 
Is that possible?

We tried the following:
`<embed src="/abs/path.json" True" id="embedded_json">
<a href="embedded_json">Click!</a>
`

But that does not seem to do the trick.
Any ideas?

Thank you!

**Comment by liZe** [comment]
Hello!

> Great Library!

Thank you ❤️.

> We are trying to embed a json document and create a link.
> Is that possible?

It depends on what you really want to do. Do you want to attach a JSON file to the PDF and open it in a text editor when the link is clicked, or would you prefer to display the JSON text as PDF content and scroll to this content when the link is clicked?

**Comment by werk24** [comment]
In a perfect world, clicking on the link would open the JSON document in a web browser 
(as we would benefit from the syntax highlighting).

**Comment by liZe** [comment]
It’s possible is to attach the file to the PDF. You can use something like:
```html
<a rel="attachment" href="/abs/path.json">Cilck!</a>
```
in your HTML header. The JSON file will be listed in the attachments list of your PDF by your PDF reader, and opening it will generally launch the default application for JSON files (or ask for the application to use, depending on your PDF reader).

**Comment by werk24** [comment]
Thank you for the fast response. 

I just tried it - but I can't seem to get it to work.
When I click on the link nothing happens.

I also added the file to the attachments in httml.write_pdf

Is there anything else to consider?

**Comment by liZe** [comment]
Oh, it’s not in the header as I wrote, it’s in the body. But if you see it in the document, it probably means that it should work.

Here’s a PDF document created with this sample, with a HTML file attached (that should be opened in your browser). Note that it’s not useful to pass the attachment to `write_pdf`, using `rel="attachment"` in the `a` tag is enough.

Does this document work for you? [test.pdf](https://github.com/Kozea/WeasyPrint/files/7020861/test.pdf)

**Comment by werk24** [comment]
Interesting... so your file works for me, BUT I need to double-click on the link. 
It I use a normal link to example.com, a single-click suffices.

I am wondering though what I do differently, I tried this simple example - and it does not work:
`<html>
<body>
    <a rel="attachment" href="/home/xxx/a.html">Cilck!</a>
</body>
</html>`

**Comment by werk24** [comment]
Now it works! I just reinstalled WeasyPrint and now the generated file contains a clickable link.

How would I now make the file link behave like a "normal" link (i.e., that it opens the file with a single click, rather than a double-click, on Linux)

**Comment by werk24** [comment]
Sorry for the back-and-forth. I just understood how to break it.

If I load the Template with `HTML(path="...")` it works.
If I load it as string `HTML(string="...")` it does not

**Comment by werk24** [comment]
Understood! The way `default_url_fetcher` is implemented, it needs the `base_url` in  `HTML(string="...", base_url="./template/index.html")` to point to a file. I had it pointed to a directory.

To anyone that is reading this in the future. When you are using a custom url_fetcher it might be another reason why including the file might not work.

**Comment by liZe** [comment]
> How would I now make the file link behave like a "normal" link (i.e., that it opens the file with a single click, rather than a double-click, on Linux)

The way links to attachments are handled depends on the PDF reader, not on WeasyPrint. You’ll get different behaviors if you use different readers (you can try to open the PDF in a browser for example). Unfortunately, there’s nothing we can do about that :/.

**Comment by werk24** [comment]
Thank you!
