### ISSUE TITLE
Example of new approach for html.write_png

### ISSUE THREAD

**Issue by sipsorcery** [Kozea/WeasyPrint#1425]
I spotted that the png output option has been removed from weasyprint >=53.0. In the announcement [blog post](https://www.courtbouillon.org/blog/00004-weasyprint-without-cairo-what-s-different) it's mentioned that the old `write_png` function can be replaced with Ghostscript or Poppler. Is there an example anywhere of doing that? I had a look at the unit tests but couldn't work out how to extract the logic.

In my script using weasyprint v52.4 I use:

````
html = wsp.HTML(string=html)
html.write_png(RESULTS_FILE_PATH)
````

**Comment by liZe** [comment]
Hello!

You’re right, we should have some documentation about that.

In the meantime, you can find interesting code here: https://github.com/Kozea/WeasyPrint/blob/v53.0/tests/conftest.py

**Comment by liZe** [comment]
Well… Maybe there’s nothing very interesting we can say about PDF to PNG conversion. WeasyPrint used to generate PNG files, but we now have more options using third-party tools. Reading the documentation of these PDF-to-* converters is the best way to find adapted solutions, and adding some limited code samples would probably raise more questions than the answers we’re trying to give.

So, we won’t add any documentation for that. Adapting the code that’s in `conftest.py` is a possible solution, but users will probably find other ways that are more adapted to their use cases. Our solution is basically calling Ghostscript (released under AGPL) on the generated PDF document to get one PNG per page, but many tutorials will give you other ideas depending on what you really want.

Don’t hesitate to ask if there’s anything you don’t understand in `conftest.py`!
