### ISSUE TITLE
Svg image displayed incorrectly

### ISSUE THREAD

**Issue by vicmion** [Kozea/WeasyPrint#1430]
Updating weasyprint from release 52.5 to 53.1 I have noticed that an image that was rendered flawlessly before now breaks.
I have uploaded the two pdf and a .zip folder containing the `index.html` and `main.py` to easily reproduce the problem.

[mypdf_52_5.pdf](https://github.com/Kozea/WeasyPrint/files/7067167/mypdf_52_5.pdf)
[mypdf_53_1.pdf](https://github.com/Kozea/WeasyPrint/files/7067172/mypdf_53_1.pdf)

[report-error.zip](https://github.com/Kozea/WeasyPrint/files/7067217/report-error.zip)

Thanks in advance.

**Comment by liZe** [comment]
> I kinda gotta ask, if you're going down the path of building your own svg parser, how big a corpus of test data do you have? you know it's like turing complete right? you're likely to keep cropping up on this sort of thing by walking away from cairo....

The SVG renderer we were using before was CairoSVG, and … we are also the creators of CairoSVG :wink:.
