### ISSUE TITLE
Webpage https://weasyprint.org/start/ shows latest version as 53.0b but 53.2 is the latest

### ISSUE THREAD

**Issue by mpasternak** [Kozea/WeasyPrint#1433]
Hi,

Webpage https://weasyprint.org/start/ shows latest version as 53.0b but 53.2 is the latest

Also the "News" section looks like it needs an update.

**Comment by grewn0uille** [comment]
Hello!

The website has just been rebuild to have the correct lastest version :)

We’re currently working on a tiny update for the website and it won’t contain news anymore, that’s why there aren’t news for the latest versions.
