### ISSUE TITLE
Broken with Python 3.8+ on Windows

### ISSUE THREAD

**Issue by oddMLan** [Kozea/WeasyPrint#1435]
Apparently the Python Software Foundation in a moment of pure brilliance decided to break DLL resolution in Python 3.8+
"it's not a bug; it's a feature": https://bugs.python.org/issue43173

>In 3.8+, the search path for the dependent DLLs of a normally imported extension module includes the following directories:
>
>    * the loaded extension module's directory
>    * the application directory (e.g. that of python.exe)
>    * the user DLL search directories that get added by 
>      SetDllDirectory() and AddDllDirectory(), such as with 
>      os.add_dll_directory()
>    * %SystemRoot%\System32
>
>If possible, the simplest approach is to put dependent DLLs in the same directory as the extension module. 

More details:
https://github.com/Kozea/WeasyPrint/issues/589#issuecomment-909531833

**Comment by liZe** [comment]
Hello!

Well… It’s probably time to follow what the Python devs say:

> If your application relies on [DLL loading], you should check for `add_dll_directory()` and if it exists, use it to add your DLLs directory while loading your library.

**Comment by liZe** [comment]
This bug is now closed 🚀.

We’ve added a `WEASYPRINT_DLL_DIRECTORIES` environment variable to list folders where the DLL files can be found. Python 3.8+ will look there to find the libraries. The default value is the default folder of the GTK3 installer.

Feedback is welcome!
