### ISSUE TITLE
Has anyone installed WeasyPrint on SolarisOS?

### ISSUE THREAD

**Issue by chfw** [Kozea/WeasyPrint#144]
Hi all,

My production server has python 2.6 and WeasyPrint was installed with some effort. For example, one of the problem is gobject is not found. In the end, my application runs but it give a segmenation fault when the pdf is to be generated.

Can you provide some hints to debug or share your experience on installing it in SoliarisOS?

Cheers

c

**Comment by liZe** [comment]
@chfw Did you try with recent versions of WP and deps?
