### ISSUE TITLE
css selector @page :not(:first) not supported

### ISSUE THREAD

**Issue by Jc-L** [Kozea/WeasyPrint#1445]
css selector `@page :not(:first)` is not supported. Workarounds are possible but supporting this selector would help to manage covers.

**Comment by grewn0uille** [comment]
Hello!

Thanks for the issue.
According to the [specification](https://www.w3.org/TR/selectors-3/#negation), `:not(X)` takes simple selector, and `:first` isn’t a simple selector ([it’s a pseudo-class](https://drafts.csswg.org/css-page/#first-pseudo)).
So this feature won’t be supported.

If you want to define things for all pages but not the first, you can define it globally and override them in the `@page :first`.
