### ISSUE TITLE
Mac M1 OSError: cannot load library 'gobject-2.0-0'

### ISSUE THREAD

**Issue by MikhailKravets** [Kozea/WeasyPrint#1448]
Hello! I could install `WeasyPrint==53.3` on my M1 mac. 

But when importing

```python
from weasyprint import HTML, CSS
```

I receive an error

```shell
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 2): image not found.  
Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

Was anyone able to handle this? 🤔

**Comment by liZe** [comment]
Hello!

Did you follow the [installation steps for macOS](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#macos)? GObject is installed as a dependency of Pango, so if you use Homebrew’s Python, it should work out of the box.

**Comment by MikhailKravets** [comment]
Hi @liZe , thanks for the reply. The problem was that symlinks to the libraries were not created (can't say should it be done by homebrew or weasyprint when installation) 🙈 .

So, I had to create symlinks to these libs manually

```bash
sudo ln -s /opt/homebrew/opt/glib/lib/libgobject-2.0.0.dylib /usr/local/lib/gobject-2.0
sudo ln -s /opt/homebrew/opt/pango/lib/libpango-1.0.dylib /usr/local/lib/pango-1.0
sudo ln -s /opt/homebrew/opt/harfbuzz/lib/libharfbuzz.dylib /usr/local/lib/harfbuzz
sudo ln -s /opt/homebrew/opt/fontconfig/lib/libfontconfig.1.dylib /usr/local/lib/fontconfig-1
sudo ln -s /opt/homebrew/opt/pango/lib/libpangoft2-1.0.dylib /usr/local/lib/pangoft2-1.0
```

This solved the problem 👍

**Comment by liZe** [comment]
> The problem was that symlinks to the libraries were not created

Oh. Maybe it actually means that you use your system’s Python, because I’m pretty sure that Homebrew’s Python is able to find libraries in `/opt/homebrew/`.

The `python3` executable is supposed to [reference Hombrew’s Python](https://docs.brew.sh/Homebrew-and-Python#python-3x), so if you installed Python with Homebrew and if you use `python3` in your script, you shouldn’t need an extra symlink.

**Comment by MikhailKravets** [comment]
I've installed Python3.9 with the installer. Then used Pipenv to manage virtual environment

**Comment by liZe** [comment]
> I've installed Python3.9 with the installer.

That’s why you get this error. You can either uninstall this version of Python installed with the installer and use the Hombrew version instead (that’s the "official" solution according to the documentation), or keep the symlinks if you prefer (and hope that everything will be fine after the next upgrade).

**Comment by Headmaster11** [comment]
Faced the same problem on MacOs M1.

Solution _using homebrew python_ does not suits me, because I use Python3.11.1 and this version is not supported by brew yet.

Also tried to link symlinks manually based on https://github.com/Kozea/WeasyPrint/issues/1448#issuecomment-925549118, but according to the error I face

`OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'`

it tries to search in `/usr/lib` and not `/usr/local/lib`. Any idea why? Is there any way to change path to locate?

**Comment by CaOs433** [comment]
@Headmaster11 did you find a solution for this? I have python 3.11 and symlinks are linked manually but still not working (worked in previous versions).

**Comment by Headmaster11** [comment]
@CaOs433 - based on the answers above, will you be able to use python 3.11 from homebrew?

**Comment by rbtsolis** [comment]
1. Install [Homebrew](https://brew.sh/)
2. `brew install pango libffi`

**Comment by liZe** [comment]
> * Install [Homebrew](https://brew.sh/)
> * `brew install pango libffi`

1. Install [Homebrew](https://brew.sh/)
2. brew install weasyprint

😄

**Comment by rbtsolis** [comment]
> > * Install [Homebrew](https://brew.sh/)
> > * `brew install pango libffi`
> 
> 1. Install [Homebrew](https://brew.sh/)
> 2. brew install weasyprint
> 
> 😄

It install weasyprint globally, if I need x version maybe is not the best solution

**Comment by shiplu** [comment]
If you are already installing weasyprint as a part of other installation method like poetry or pip, then installing it through brew is not an option.  Then you need to install the dependencies of weasyprint using brew. If you see the weasyprint [formula details](https://formulae.brew.sh/formula/weasyprint#default), you'll find following packages are declared as dependencies. 



formula name | version | description
-- | -- | --
cffi | 1.16.0 | C Foreign Function Interface for Python
fonttools | 4.43.1 | Library for manipulating fonts
pango | 1.50.14 | Framework for layout and rendering of i18n text
pillow | 10.1.0 | Friendly PIL fork (Python Imaging Library)
python@3.12 | 3.12.0 | Interpreted, interactive, object-oriented programming language
six | 1.16.0 | Python 2 and 3 compatibility utilities

If you install those formula 1 by 1 with `brew install` command, `weasyprint` library would find it's dependencies.

For me I just installed `pango` with `brew install pango`.

**Comment by sureshdsk** [comment]
In my case, I had installed pango with `brew install pango`
but for some reason gobject linking did not happen automatically. 
so i did `brew install glib` and then link again `brew link glib` which created necessary symlinks for goobject.

**Comment by cipherCOM** [comment]
I encountered the same problem when using `brew` or `conda`. I dug a little deeper an found the way how the libraries are loaded:
```
gobject = _dlopen(
    ffi, 'gobject-2.0-0', 'gobject-2.0', 'libgobject-2.0-0',
    'libgobject-2.0.so.0', 'libgobject-2.0.dylib',  'libgobject-2.0-0.dll')
```

This however doesn't work out of the box for macOS from what I can tell. Be it `conda` or `brew` used to install the dependencies the gobject library is just named differently (not `libgobject-2.0.dylib` but `libgobject-2.0.0.dylib`). Maybe it would be advisable to change the naming in the `weasyprint/text/ffi.py` accordingly or use the other naming in addition?

```
/opt/homebrew/Caskroom/miniconda/base/pkgs/libglib-2.80.0-hfc324ee_6/lib/libgobject-2.0.0.dylib
/opt/homebrew/Caskroom/miniconda/base/envs/<some_env_name>/lib/libgobject-2.0.0.dylib
/opt/homebrew/Cellar/glib/2.80.0_2/lib/libgobject-2.0.a
/opt/homebrew/Cellar/glib/2.80.0_2/lib/libgobject-2.0.0.dylib
```

**Comment by liZe** [comment]
It works with Homebrew out of the box on [GitHub Actions](https://github.com/Kozea/WeasyPrint/actions/runs/8835955656/job/24261385630).

And I don’t think that they had to change anything in `ffi.py` for their formula, for Apple Silicon or for Intel.

**Comment by eaparnell** [comment]
> In my case, I had installed pango with `brew install pango` but for some reason gobject linking did not happen automatically. so i did `brew install glib` and then link again `brew link glib` which created necessary symlinks for goobject. ✅

Thank you. This worked for me on my M1.

**Comment by EchoMaster** [comment]
dlopen(/usr/local/lib/gobject-2.0-0, 0x0002): tried: '/opt/local/lib/gobject-2.0-0' (no such file), '/opt/homebrew/opt/gobject-2.0-0' (no such file), '/opt/homebrew/opt/gobject-2.0-0' (no such file), '/opt/homebrew/opt//gobject-2.0-0' (no such file), '/opt/homebrew/opt//gobject-2.0-0' (no such file), '/gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/gobject-2.0-0' (no such file), '/usr/local/lib/gobject-2.0-0' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/opt/local/lib/libgobject-2.0.0.dylib' (no such file), '/opt/homebrew/opt/libgobject-2.0.0.dylib' (no such file), '/opt/homebrew/opt/libgobject-2.0.0.dylib' (no such file), '/opt/homebrew/opt//libgobject-2.0.0.dylib' (no such file), '/opt/homebrew/opt//libgobject-2.0.0.dylib' (no such file), '/libgobject-2.0.0.dylib' (no such file), '/opt/homebrew/Cellar/glib/2.80.2/lib/libgobject-2.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/glib/2.80.2/lib/libgobject-2.0.0.dylib' (no such file), '/opt/homebrew/Cellar/glib/2.80.2/lib/libgobject-2.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')).   I got this wrong.

**Comment by liZe** [comment]
> '/opt/homebrew/Cellar/glib/2.80.2/lib/libgobject-2.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

You have arm64 libraries installed with Homebrew, but Python is looking for x86_64 libraries. You shouldn’t have this problem if you use Homebrew’s Python.

(Please, don’t comment on closed issues, open new issues if needed.)
