### ISSUE TITLE
Installation problem on macOS M1 chip

### ISSUE THREAD

**Issue by shinokada** [Kozea/WeasyPrint#1451]
I have Python already on macOS version 11.6 using Pyenv.

```
$ python --version
Python 3.9.6
```

I followed the [doc](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#macos) for installation.

```
pip install weasyprint
brew install pango libffi
```

I get the following error.

```
 weasyprint --info
Traceback (most recent call last):
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/bin/weasyprint", line 5, in <module>
    from weasyprint.__main__ import main
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/lib/python3.9/site-packages/weasyprint/__init__.py", line 322, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/lib/python3.9/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/lib/python3.9/site-packages/weasyprint/css/computed_values.py", line 16, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/lib/python3.9/site-packages/weasyprint/text/ffi.py", line 380, in <module>
    gobject = _dlopen(
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/lib/python3.9/site-packages/weasyprint/text/ffi.py", line 377, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/shinichiokada/.pyenv/versions/3.9.6/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

I installed gtk3.

```
brew install gtk+3
```

But it doesn't solve the problem.

How can I solve the problem?

**Comment by shinokada** [comment]
I found the solution [here](https://stackoverflow.com/questions/69097224/gobject-2-0-0-not-able-to-load-on-macbook/69295303#69295303)

You need to run the following:

```
sudo ln -s /opt/homebrew/opt/glib/lib/libgobject-2.0.0.dylib /usr/local/lib/gobject-2.0
sudo ln -s /opt/homebrew/opt/pango/lib/libpango-1.0.dylib /usr/local/lib/pango-1.0
sudo ln -s /opt/homebrew/opt/harfbuzz/lib/libharfbuzz.dylib /usr/local/lib/harfbuzz
sudo ln -s /opt/homebrew/opt/fontconfig/lib/libfontconfig.1.dylib /usr/local/lib/fontconfig-1
sudo ln -s /opt/homebrew/opt/pango/lib/libpangoft2-1.0.dylib /usr/local/lib/pangoft2-1.0
```

Now it returns some info:

```
$ weasyprint --info
Unable to revert mtime: /Library/Fonts
System: Darwin
Machine: arm64
Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101
Release: 20.6.0

WeasyPrint version: 53.3
Python version: 3.8.10
Pydyf version: 0.1.1
Pango version: 14810
```

**Comment by liZe** [comment]
Hello!

Linking Hombrew libraries outside of Homebrew is not a good solution in my opinion. You should use Homebrew’s Python instead of using your system’s version of Python (see https://github.com/Kozea/WeasyPrint/issues/1448#issuecomment-925559421).

**Comment by tomkins** [comment]
For anyone else encountering this issue:

By default Python looks in `/usr/local/lib` for libraries with ctypes: https://github.com/python/cpython/blob/v3.10.0/Lib/ctypes/macholib/dyld.py#L22 - however Homebrew versions of Python patch this to look in `/opt/homebrew/lib`: https://github.com/Homebrew/homebrew-core/blob/af990d0d5e3d70bd52b1e9acf1b0636e74851cac/Formula/python@3.9.rb#L187 - which is something Python versions from pyenv are lacking.

Annoyingly the source for dyld.py suggests that setting `DYLD_FALLBACK_LIBRARY_PATH` as an environment variable could be a workaround for this. Sadly if you're calling Python with `#!/usr/bin/env` from a script (eg. Django `./manage.py`), macOS System Integrity Protection decides to remove such environment variables for security.

Ideally a patched Python is the best route for this, however failing that - symbolic links should work.

**Comment by ryanjcohen** [comment]
I'm getting the ```OSError: cannot load library 'gobject-2.0-0'``` issue on an M1 Mac at the moment even after adding the symbolic links. any suggestions?

**Comment by liZe** [comment]
> I'm getting the `OSError: cannot load library 'gobject-2.0-0'` issue on an M1 Mac at the moment even after adding the symbolic links. any suggestions?

Linking Hombrew libraries outside Homebrew is not a good solution in my opinion. You should use Homebrew’s Python instead of using your system’s version of Python (see [#1448 (comment)](https://github.com/Kozea/WeasyPrint/issues/1448#issuecomment-925559421)).

**Comment by lggwettmann** [comment]
@liZe Do you have any references or more info on how to do that in a good way?

**Comment by liZe** [comment]
> @liZe Do you have any references or more info on how to do that in a good way? I normally use pyenv.

With a simple venv, the best practice we propose are in [the installation guide](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#macos). With pyenv, we don’t know (because we don’t know how it works with Homebrew).

**Comment by Yarmayar** [comment]
@liZe , hello, i had same trouble..."OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no "
I read all the questions on the topic and newbie in programming, I'm learning Django from the Django book in practice, I have a mac os m1, I'm working in PyCharm, I initially installed weasyprint via brew, then added it to the project via pip and got an error. I tried the solution via sudo terminal, but I don't have such a path. Next, I installed python 3.12 (current stub version) via brew, launched a new project, but now it gives an error when installing weasyprint via pip install: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

I don’t even know how to formulate a request, I’m terrified, how can I get back to working with my project?

**Comment by Yarmayar** [comment]
<img width="1056" alt="Screenshot 2024-03-19 at 13 53 31" src="https://github.com/Kozea/WeasyPrint/assets/150394304/f98e1bfc-a38e-48a1-afad-3d04db3ddc9b">
Perhaps I'm doing it wrong from the very beginning, tell me, am I selecting the correct file in pycharm to run brew python?

**Comment by liZe** [comment]
> Perhaps I'm doing it wrong from the very beginning, tell me, am I selecting the correct file in pycharm to run brew python?

I’m sorry, I don’t use Pycharm, I don’t use Homebrew, I don’t use macOS. It seems to be the right interpreter, but I really don’t know if a virtual environment created this way works. That’s not a problem with WeasyPrint, that’s a problem with Pycharm, Homebrew and macOS.

**Comment by Yarmayar** [comment]
> Check that you can import Homebrew’s WeasyPrint from Homebrew’s Python. Then, try to create a fresh virtual environment with Homebrew’s Python, install WeasyPrint with pip and check that it works. 
Am I right? I should to do:
1. install python using brew
2. install weasyprint using brew
3. open python file and try to import weasymoney package (Before i use pip installation)
4. create venv
5. isntall WeasyPrint using pip?

> I’m sorry, but I can’t help you more than this. I don’t have a Mac, I’ve never used Homebrew other than for the CI.
How can i install and use weasymoney without python that i install from brew?

**Comment by liZe** [comment]
Don’t install weasymoney on step 3 (if that’s your project), just launch Homebrew’s Python and check that WeasyPrint works (`python3 -m weasyprint` should work, if `python3` is your Homebrew’s Python). Install it after step 5, and after checking that your venv’s WeasyPrint works too.

**Comment by Yarmayar** [comment]
<img width="556" alt="Screenshot 2024-03-19 at 15 03 34" src="https://github.com/Kozea/WeasyPrint/assets/150394304/dda06b6d-ce93-404a-bf59-aa5e468f1156">
1. I installed python (brew)
2. Installed weasymoney (brew) 
But "no module named weasyprint"
What's wrong with me? Help me please)

**Comment by liZe** [comment]
> What's wrong with me? Help me please

I’ve never used Homebrew. This problem is not related to WeasyPrint. I can’t help you.

**Comment by Yarmayar** [comment]
<img width="736" alt="Screenshot 2024-03-19 at 15 11 20" src="https://github.com/Kozea/WeasyPrint/assets/150394304/978734ce-293f-41ff-8894-20d371f0e284">

This way unsuccess, have you another one? without homebrew?

**Comment by Yarmayar** [comment]
![Uploading Screenshot 2024-03-19 at 18.29.49.png…]()
I got weasyprint working, it worked after I downloaded python 3.11 (python 3.12 just gives an error when starting a new project) But in the terminal of the command python3 -m weasyprint reports that there is no module, but everything works. I already have a bunch of Python and all sorts of packages for them, it’s not clear how to figure it out and put things in order in the system now(
