### ISSUE TITLE
Installing WeasyPrint on Windows 10

### ISSUE THREAD

**Issue by UGuntupalli** [Kozea/WeasyPrint#1464]
Hello, 

I am really interested in using WeasyPrint and have spent several hours just trying to sort the install on my windows machine. 

1. Follow instructions on (https://doc.courtbouillon.org/weasyprint/stable/). I tried to set up a new project with a venv and install weasy print after downloading and installing the GTK3 installer provided here, however that results in a an error as shown below: 

    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build
 Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\UI923816\AppData\Local\Temp\1\pip-install-_jgf5qdu\
cffi\
 
 
 2. I have tried installing it without downloading the GTK installer in an Anaconda Virtual Environment and a venv, but nothing seems to work. 

Can you please provide foolproof installation instructions for installing WeasyPrint on Windows 10 ? 

Thanks 
Uday

**Comment by UGuntupalli** [comment]
@liZe , 

I tried using Anaconda as well. My preferred approach would be to use Anaconda as well.

**Using an Anaconda Virtual Environment**; 
![image](https://user-images.githubusercontent.com/47903157/136463765-7da9170d-2c1a-4ab6-9286-9f8d88e16105.png)

There is a lot of errors and warnings, however, the primary issue seems to be around cffi

**Comment by liZe** [comment]
OK. Let’s summarize this crazy mess, for the record.

- Python 3.10 got released this week.
- As cffi (and probably other modules) doesn’t have wheels yet for Python 3.10, installing non-pure-Python packages requires a compiler.
- Fontconfig can’t find the configuration for some random reason.
- Conda-forge’s WeasyPrint package is broken, because there’s a broken rule somewhere that gets the Python version using "3.X" instead of "3.XX".

The best solution for you is probably to fix Conda-forge’s package. Let’s try to find the reason of this bug…

**Comment by Blaben** [comment]
WeasyPrint needs some libraries that are not installed by default. The easiest way is to use the official pre-built binaries:

Download the latest [GTK3+ bundle for Windows : https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

Run the installer and follow the prompts. By default, it installs to C:\Program Files\GTK3-Runtime Win64.

Add GTK to Your PATH
Open the Start menu, search for "Environment Variables", and edit your system PATH.
Add the path to the bin folder inside your GTK installation, e.g.: C:\Program Files\GTK3-Runtime Win64\bin

after open Command Prompt or in your virtual environment and type: 
pip install weasyprint 

This should also hel fix it

**Comment by liZe** [comment]
> Add GTK to Your PATH

Please don’t do that if you want to avoid future problems on your system.

Please follow [the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows).

**Comment by Blaben** [comment]
Okay. Thanks.
However, I installed it in my virtual environment, so I hope it won't cause much of a problem.
