### ISSUE TITLE
input type="hidden" takes up space in PDF

### ISSUE THREAD

**Issue by Christoph-Wagner** [Kozea/WeasyPrint#1471]
I upgraded from Weasyprint 51 to the current 53.3 and there was suddenly a new page at the beginning of the document:

![image](https://user-images.githubusercontent.com/1609329/137264257-e80b4d37-a9b5-45f8-8061-fbf2f186390d.png)

After some testing, I narrowed it down to `<input type="hidden">`-fields.

2 Examples:

Correct (1 page) [test-correct.pdf](https://github.com/Kozea/WeasyPrint/files/7343755/test-correct.pdf):
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <style>
      @page {
        size: A5 portrait;
      }
      #intro {
        page: Intro;
        height: 210mm;
      }
    </style>
  </head>
  <body>
    <div id="intro">
      <h1>Headline</h1>
    </div>
  </body>
</html>
```

Wrong (2 pages) [test-wrong.pdf](https://github.com/Kozea/WeasyPrint/files/7343756/test-wrong.pdf):
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <style>
      @page {
        size: A5 portrait;
      }
      #intro {
        page: Intro;
        height: 210mm;
      }
    </style>
  </head>
  <body>
    <input type="hidden" />
    <div id="intro">
      <h1>Headline</h1>
    </div>
  </body>
</html>
```

This is not important for me as I can luckily remove those fields, the only reason they are even there is that we use ancient and deprecated asp.net webforms technology. But I thought I should at least report it ;)

The correct behavior would be for `input type="hidden"` to be completely ignored. 

In case it matters, this is on Windows.

**Comment by liZe** [comment]
Thanks a lot for the bug report! As you can see in eebb6e5, the fix was quite easy 😉.
