### ISSUE TITLE
Pages cannot be duplicated

### ISSUE THREAD

**Issue by zelitomas** [Kozea/WeasyPrint#1473]
It seems that WeasyPrint is failing when I try to include a page more than twice, like so:

``` python
# Minimal example of the behaviour
from weasyprint import HTML

document = HTML(filename="./index.html").render()
duplicated_pages = document.copy([*document.pages, *document.pages])
duplicated_pages.write_pdf("result.pdf")
```
The document can be found here: https://gist.github.com/zelitomas/50aa47d4966e1b743588a284e12cf599 

## Actual Result
![Snímek z 2021-10-17 13-56-45](https://user-images.githubusercontent.com/3105674/137626263-1008bc10-f3f2-408f-9411-686d1eb4aba7.png)

[result.pdf](https://github.com/Kozea/WeasyPrint/files/7359818/result.pdf)

## Expected result
![Snímek z 2021-10-17 13-56-54](https://user-images.githubusercontent.com/3105674/137626273-ebecf9ea-cd3f-49e9-944b-631af0907331.png)

**Comment by liZe** [comment]
Thanks a lot for the bug report!
