### ISSUE TITLE
Fontconfig warning: line 5: unknown element "description"

### ISSUE THREAD

**Issue by cheenng** [Kozea/WeasyPrint#1474]
Hello Kozea,

I installed weasyprint today and got stuck on tackling a error:
```
C:\Users\ych>venv\Scripts\activate.bat
(venv) C:\Users\ych>weasyprint
Fontconfig warning: line 5: unknown element "description"

(venv) C:\Users\ych>python
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from weasyprint import HTML
Fontconfig warning: line 5: unknown element "description"

(venv) C:\Users\ych>  /* python crashes and exits */

(venv) C:\Users\ych>python -m weasyprint --info
Fontconfig warning: line 5: unknown element "description"

(venv) C:\Users\ych>
```
This warning matters because it causes python crashes with "Process finished with exit code -1073741819 (0xC0000005)" .
It seems that the file:
"C:\Program Files\GTK3-Runtime Win64\etc\fonts\fonts.conf" cannot be read correctly. The tag description cannot be understood. Below are the first 5 lines in fonts.conf:

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- /etc/fonts/fonts.conf file to configure system font access -->
<fontconfig>
	<description>Default configuration file</description>
```

Even though I removed the line of "description", python still crashed.

What did I miss regarding the installation? Is there Anyone encountering the same problem?
Which program read fonts.conf?

I followed the instruction in here for windows
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation

My Enviroment: 
Windows 10, Python Python 3.8.3 , GTK Installation by "gtk3-runtime-3.24.29-2021-04-29-ts-win64.exe"

Any responses would be very appreciated !
Thank you!

Best regards,
Yuan

**Comment by liZe** [comment]
> At the moment I just changed the code in {my python}\Lib\site-packages\weasyprint\text\ffi.py to force that the libfontconfig.dll is loaded before fontconfig.dll.

OK, then I’ll close this issue and we’ll continue the discussion in #1435.
