### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by 0kzh** [Kozea/WeasyPrint#1484]
Are there any options I can specify to get emojis to render properly? Example:

**Input**
```html
<body>
  🥺
</body>
```

**Output**
```
ðŸ¥º 
```

**Details**
- WeasyPrint 53.3, also tried with 52.2
- Python 3.7
- MacOS Big Sur 11.6

**Comment by liZe** [comment]
Hello!

You have to set an encoding supporting emojis, with `weasyprint -e utf-8 input.html output.pdf`, or adding `<meta charset="utf-8">` into your HTML header (assuming that your file is in utf-8).

Side note: colored emojis are not supported in the current stable version (v53.x), but they are in the previous versions and will be in the next versions (see #1406).

**Comment by 0kzh** [comment]
Hey! I just tried that but the result is a question mark block:

<img width="161" alt="Screen Shot 2021-11-03 at 1 13 38 PM" src="https://user-images.githubusercontent.com/9621004/140185642-fc68d582-5db1-4804-a78a-cbce3c9bc30f.png">

However, when I copy it + paste it elsewhere, the emoji renders correctly.
Any ideas why this might be happening?

**Comment by liZe** [comment]
> Any ideas why this might be happening?

You don’t have any font installed with black and white emojis. This character probably comes from a default font that replaces unknown characters with question marks.

Try WeasyPrint 52 or the current master branch, and you should get images if you have a font installed with colored emojis.

**Comment by jmhammond** [comment]
Thanks @liZe! I run grade reports for my students and have some silly emojis in there that didn't appear now.  In case anyone else just needs a quick-and-dirty fix, I downgraded weasyprint via:

`pip3 install 'weasyprint<53.0' --force-reinstall`

and the reports generated like old times. It's probably not elegant, but I just needed it to work this afternoon 😄
