### ISSUE TITLE
Duplicate images when rendering pdf from pages

### ISSUE THREAD

**Issue by wf-r** [Kozea/WeasyPrint#1486]
Hi,

the changes from https://github.com/Kozea/WeasyPrint/issues/1414 / https://github.com/Kozea/WeasyPrint/commit/694eddbc711da6144591fe2e6bce439ed70023c9 break the following workflow:

```
pdf_pages = []  # List to collect pdf pages
# Collect different pdf pages from html (e.g., from jinja)
for i in range(3):
    pdf_pages.extends(
        weasyprint.HTML(string=<some html string containing an image>).render().pages
    )
# Output collected pdf pages
with open('out.pdf', 'w+b') as out:
    weasyprint.Document(pages=pdf_pages, metadata=weasyprint.document.DocumentMetadata(), font_config=weasyprint.text.fonts.FontConfiguration(), url_fetcher=None, optimize_size='none').write_pdf(out)
```

All images on the different pages are a duplicate of the corresponding image from the first rendering, as the `image_name` computed in `Stream.add_image()` only contains the index of the image on this page (and therefore, the first image of all pages obtains the same id).

Versions:

* weasyprint: 53.3
* Python: 3.8.6

**Comment by liZe** [comment]
Hello, and thanks a lot for the bug report.

Using `Document` isn’t really using the public API (or is it? 😁), but there’s probably a way to reproduce using other ways, so it’s worth fixing.

We’ve fixed the bug (with two commits actually removing lines, these fixes are the best) and added a test. Feel free to test with real use cases!

**Comment by wf-r** [comment]
Thanks for the quick fix (and sorry, I really did not realize that the `Document` constructor was not part of the public API :))

**Comment by wf-r** [comment]
As a side note (if anybody stumbles upon this): the above fix only works if the image urls used in the separate page renderings are different from another. Rendering each page in the same temporary directory with identical image url (and then deleting it after the rendering) will not work.
