### ISSUE TITLE
I'm trying to set a header and footer in the same place across different pages. 

### ISSUE THREAD

**Issue by JulianLucena** [Kozea/WeasyPrint#1488]
### Hello

Im trying the set both a header and a footer in the same place in every page. So far they have different places across the pages.

Take for example the header from page 1.

![page 1](https://user-images.githubusercontent.com/63055363/140391616-bb0b4cd1-a7df-4642-9458-7330d2841527.png)

And this is how it looks on page 2.

![page 2](https://user-images.githubusercontent.com/63055363/140391625-bc992f93-a178-4568-8566-cff8a3e2521d.png)

### HTML

```
	<header class="header">
	<img src="file://{{CURDIR}}/logochico2.png"/>                        
		<div class="con_info">
			<p class="con_textA">Dirección: Simpson's house</p>
			<p class="con_textA">Teléfono: 123456789</p>
			<p class="con_textA">Sitio web: www.website.com.ar</p>
			<p class="con_textB">Horarios: </p>
			<p class="con_textB">whatever.</p>
			<p class="con_textB">Sábados:</p>
		</div>
	</header>
```
	
### CSS

```
	body{
            margin: 0cm;
            border: 0.10cm solid rgba(52,140,158,1);   
            border-bottom: none;
            font-family: Arial, Helvetica, sans-serif;
            height: 23cm;
            padding-top: 4cm;
        }
        header{
            position: running(header);
            height: 4cm;
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            background: linear-gradient(122deg, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 46%, rgba(80,167,185,1) 54%, rgba(52,140,158,1) 100%);
            margin-top: 5.2cm;
        }
        footer{
            position: running(footer);   
            height: 3cm;
            background: linear-gradient(122deg, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 46%, rgba(80,167,185,1) 54%, rgba(52,140,158,1) 100%);       
        }
        @page{
            @top-center{
                content: element(header);
                width: 99%;
                margin-top: 1cm;
            }
            @bottom-center{
                content: element(footer);
                width: 100%;
                margin: 0cm 0cm 5cm 0cm;
            }
            size: A4;
        } 
```

As you can see, the headers doesn't quite fit in page 2 onwards.

### Page 1

![page 3](https://user-images.githubusercontent.com/63055363/140391655-c80e905b-29ca-487a-baa0-6c01f422b6ab.png)

As you can see, it doesn't ever show it on page 1.

### Page 2

![page 4](https://user-images.githubusercontent.com/63055363/140391672-a06972a6-17c2-4b16-8a32-6b886bbc50fa.png)

However it does shows it on page 2, but off the page.

### HTML
```
	<footer class="footer">
		<img src="file://{{CURDIR}}/qr_imax.png" class="qr"/>
	</footer>
```

### CSS
```
	footer{
            position: running(footer);   
            height: 3cm;
            background: linear-gradient(122deg, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 46%, rgba(80,167,185,1) 54%, rgba(52,140,158,1) 100%);       
        }
        @page{
            @top-center{
                content: element(header);
                width: 99%;
                margin-top: 1cm;
            }
            @bottom-center{
                content: element(footer);
                width: 100%;
                margin: 0cm 0cm 5cm 0cm;
            }
            size: A4;
        }        
```

**Comment by liZe** [comment]
Hello,

The best solution for you could be to use elements with `position: fixed` so that they get repeated on each page. If you know the height of your header and footer, you’ll get better results by having page margins and putting the fixed elements in these margins using negative `top` and `bottom` values.

You can also try [running elements](https://drafts.csswg.org/css-gcpm/#running-syntax), it’s cleaner but sometimes a bit more difficult to use.

**Comment by JulianLucena** [comment]
Hello, thanks for responding!

I've solved the issue regarding the header using **position: fixed**.

I would like to ask now about this problem regarding a sidebar I tried implementing.

![Screenshot_1](https://user-images.githubusercontent.com/63055363/141354790-4fb5a998-15f6-4d0c-8813-f33086369031.png)

I need the sidebar (red block) to be higher in the second page onwards. What can I do?

Thanks in advance.

**Comment by liZe** [comment]
It’s a complicated problem. The best solution I can think of for your use case is to use different margin sizes for the first page and for the other pages, and then to put your content in the margin using [`running()`](https://drafts.csswg.org/css-gcpm/#running-syntax).

**Comment by stegro** [comment]
@JulianLucena Please, if you got support for free, do not keep you solution for yourself and say "I have solved it", but post it here for the other people to see.

In fact, I fail to define `running` header and footer blocks.
The header appears in this minimal example, but the footer is not repeated on every page.
To me, this looks like a bug.

[footer appears only on last page but should be on everyone.pdf](https://github.com/Kozea/WeasyPrint/files/8486525/footer.appears.only.on.last.page.but.should.be.on.everyone.pdf)

[simple.html.txt](https://github.com/Kozea/WeasyPrint/files/8486542/simple.html.txt)

**Comment by grewn0uille** [comment]
Hello!

If you want to use `position: fixed`, you have to:
* set margins on your page according to the height of your header and footer with a `@page` rule
* use negative top and bottom to place your header and footer.

If you want to use `running()`:
* put your footer before the content. Indeed, `running()` puts element on each page if it "saws" the element, with the footer at the end, the footer is saw only when the last page is reached so it cannot appeared on the previous pages.

**Comment by stegro** [comment]
Mercie beaucoup Lucie, the `running()` header and footer now appears as intended, if I place the `<footer>` element before the main content.
(I have not had the time to try your advice regarding the `position: fixed` method yet.)
