### ISSUE TITLE
Problems rendering special characters

### ISSUE THREAD

**Issue by KianShah** [Kozea/WeasyPrint#1498]
Having some issues rendering some specific characters, mainly:

🟢
🟡
🟠
Neither of these characters are rendered when written to a pdf. I have confirmed that this issue is prevalent in version 53 and up. The characters display perfectly in v52.5 and did not display in v53.0

Cheers

**Comment by liZe** [comment]
Hello, and thanks for the report.

That’s probably a duplicate of #1484. Could you try the current master branch please?

**Comment by kian-supportinglines** [comment]
Sorry for the late reply. I'll test it out when the next release is issued. Thanks for your help!

**Comment by liZe** [comment]
This bug is probably fixed. Please reopen if you still have it with 54-rc.
