### ISSUE TITLE
Test failures in Tumbleweed build

### ISSUE THREAD

**Issue by coogor** [Kozea/WeasyPrint#1502]
Hi,
I updated WeasyPrint to the latest version for openSUSE. Then compiling it for Tumbleweed, the rolling release, 2 errors come up in tests (see end of attached log).
Can you comment on those? Do tests require an online access at that point in time (which is not possible in build service)
Thanks!
[log.tar.gz](https://github.com/Kozea/WeasyPrint/files/7574620/log.tar.gz)

**Comment by liZe** [comment]
> Hi,

Hello!

> I updated WeasyPrint to the latest version for openSUSE.

Thanks a lot!

> Then compiling it for Tumbleweed, the rolling release, 2 errors come up in tests (see end of attached log).

This problem may be caused by an old version of tinycss2. Do you have tinycss2 1.1.0 installed?

**Comment by coogor** [comment]
No, it was tinycss 1.0.2

With update to tinycss2 1.1.0 all tests passed for weasyprint, but tinycss2 tarball has a problem (separate report)

Thanks
