### ISSUE TITLE
Strange output fonts with sphinx litteralinclude for a file with tabs.

### ISSUE THREAD

**Issue by oz123** [Kozea/WeasyPrint#1515]
I have a document which include a bash script with the following:

```
case ${DELTA_PODS} in
-+([[:digit:]]))
      echo "negative"
      ;;
0)
      echo "no change"
     ;;
+([[:digit:]]))
    echo "positive"....
   ;;
esac
```

The output of sphinx target `singlehtml` is used to create the PDF with weasyprint. 
The fonts are rendered like this:
![bugs?](https://user-images.githubusercontent.com/1083045/144725518-d007ab83-a8e0-4cf9-b128-7f1a5be775e1.png)

As you can see, the operators `-` and `+` are overlaid  on the character `i`.
The script a code block as below rendered the expected output:

```
.. code:: bash

   ...
   case ${DELTA_PODS} in
   -+([[:digit:]]))
    echo "negative"
      ;;  
      0)
      echo "no change"
     ;;
    +([[:digit:]]))
    echo "positive"....
   ;;
   esac
 ....
```

The HTML in both cases is identical. However, upon closer inspection I realized that the included file has tabs, changing it
to spaces, solved the problem.

**Comment by grewn0uille** [comment]
Hello,
What is the version of Pango installed on your machine?

**Comment by liZe** [comment]
The bug should be fixed in master, tests are welcome!

**Comment by oz123** [comment]
🤩 so fast ! Thank you very much.
