### ISSUE TITLE
@font-face vs. @font-config typo in the docs

### ISSUE THREAD

**Issue by qwenger** [Kozea/WeasyPrint#1519]
The [docs on CSS](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.CSS) say

> An additional argument called `font_config` must be provided to handle `@font-config` rules.

You probably mean

> An additional argument called `font_config` must be provided to handle `@font-face` rules.

**Comment by liZe** [comment]
Thanks for the bug report!
