### ISSUE TITLE
Cell split over table boundary causes error with `border-collapse: collapse`

### ISSUE THREAD

**Issue by aschmitz** [Kozea/WeasyPrint#1523]
In WeasyPrint 54.0b1, rendering the following HTML gives an error:

~~~html
<style>
  table {
    border-collapse: collapse;
  }
</style>

<div style="height: 24cm"></div>

<table><tr><td>
  a<br>
  a<br>
  a<br>
  a
</td></tr></table>
~~~

(You may have to adjust the height of the spacing div to force the table to split over the page boundary depending on your font.)

The error is an `IndexError: list index out of range` on [line 856 of draw.py](https://github.com/Kozea/WeasyPrint/blob/v54.0b1/weasyprint/draw.py#L856), as it tries to index in to `vertical_borders` past its length. It appears as though build.py's `collapse_table_borders` returns one more horizontal border than there are columns, but only as many vertical borders as there are rows.

I can fix the error by changing [line 889 of draw.py](https://github.com/Kozea/WeasyPrint/blob/v54.0b1/weasyprint/draw.py#L889) to `for y in range(grid_height - 1):`, but I suspect the correct behavior may be to extend the output of `collapse_table_borders` for an additional row.

**Comment by aschmitz** [comment]
It appears adding this to your CSS is a temporary fix to revert back to the "pages can't split in the middle of a row" behavior from versions prior to 54:

~~~css
td, th {
  break-inside: avoid;
}
~~~

(In particular, it appears as though *tables* breaking over the edge of a page are still not a problem, just *rows*.)

**Comment by liZe** [comment]
Thanks a lot for the bug report.

It’s now fixed, with many other use cases of tables with collapsed cells.
