### ISSUE TITLE
OSError: ctypes.util.find_library() did not manage to locate a library called 'fontconfig-1'

### ISSUE THREAD

**Issue by magicnight** [Kozea/WeasyPrint#1530]
Today when I tried to setup WeasyPrint on my Windows for my mkdocs project. After all the setup I've got the line error as below:

> python -m weasyprint http://weasyprint.org weasyprint.pdf

Traceback (most recent call last):
  File "E:\Cloud\miniconda3\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "E:\Cloud\miniconda3\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "E:\Cloud\miniconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "E:\Cloud\miniconda3\lib\site-packages\weasyprint\__init__.py", line 322, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "E:\Cloud\miniconda3\lib\site-packages\weasyprint\css\__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "E:\Cloud\miniconda3\lib\site-packages\weasyprint\css\computed_values.py", line 16, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "E:\Cloud\miniconda3\lib\site-packages\weasyprint\text\ffi.py", line 389, in <module>
    fontconfig = _dlopen(
  File "E:\Cloud\miniconda3\lib\site-packages\weasyprint\text\ffi.py", line 377, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "E:\Cloud\miniconda3\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "E:\Cloud\miniconda3\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "E:\Cloud\miniconda3\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'fontconfig-1'

My ENV
Windows 11 64 bit
Python 3.9
miniconda
...

As I use miniconda to install WeasyPrint, and I am sure the lib fontconfig has been installed already. I have no idea what is "fontconfig-1".

**Comment by liZe** [comment]
Hello!

This bug is actually a bug in Conda’s Fontconfig, it’s already been reported here: https://github.com/Kozea/WeasyPrint/issues/1472.

**Comment by schinckel** [comment]
Hmm. I'm seeing this and I don't use conda.

**Comment by liZe** [comment]
> I'm running on macOS, and this is a new(ish) computer, so I'm guessing there's something mis-configured.

It will work if you carefully follow [the documentation](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#macos): you have to install the dependencies using Homebrew and check twice that your virtual environment is created using Homebrew’s Python.

**Comment by schinckel** [comment]
Hmm. That's useful (but also not that useful).

It's not always possible to use the Homebrew installed python - we use `asdf` for python version management, so it's going to use that.

I'll see what I can figure out.

**Comment by schinckel** [comment]
I wonder if this is because Homebrew on Apple Silicon seems to put the files in `/opt/homebrew` instead of `/usr/local`

I copied the `libfontconfig.*` files into `/usr/local/lib`, and that fixed my issue.

**Comment by schinckel** [comment]
So, the only way to resolve this on my machine was to manually put the libraries that Homebrew installed into a location that ctypes looks for them: namely, from `/opt/homebrew/Cellar/fontconfig/<version>/lib/libfontconfig.*` in `/usr/local/lib`.

**Comment by liZe** [comment]
> So, the only way to resolve this on my machine was to manually put the libraries that Homebrew installed into a location that ctypes looks for them: namely, from `/opt/homebrew/Cellar/fontconfig/<version>/lib/libfontconfig.*` in `/usr/local/lib`.

You can read the comments of [this issue](https://github.com/Kozea/WeasyPrint/issues/1556) to see that it’s a common solution even if I wouldn’t recommend it.

It’s probably safer to set an environment variable (`LD_LIBRARY_PATH`, `DYLD_LIBRARY_PATH`?) to the paths containing the libraries installed by Homebrew before you launch WeasyPrint.

> It's not always possible to use the Homebrew installed python - we use `asdf` for python version management, so it's going to use that.

[asdf is packaged for Homebrew](https://formulae.brew.sh/formula/asdf), but I understand that it’s not always possible to use Homebrew.

**Comment by schinckel** [comment]
macOS does not set DYLD_LIBRARY_PATH. It ignores it if you try.

**Comment by schinckel** [comment]
That’s blocked too. 

When I get into my computer I’ll find the links that detail that.

**Comment by schinckel** [comment]
Oh, and we use asdf installed through Home-brew, that doesn't prevent the issue.

**Comment by lirsacc** [comment]
Hi!

We've run into the same issue this week with on fresh installs with brew installed `fontconfig` but a non-brew installed python (both with `asdf` and `pyenv`, although I think the former just wraps the latter).

We've managed to resolve this with `DYLD_FALLBACK_LIBRARY_PATH` as noted by @schinckel that's not guaranteed to work for everyone. 

However we found that the latest `fontconfig` brew package installs `libfontconfig.1.dylib` in `/opt/homebrew/lib/` and thus if we patch https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/text/ffi.py#L408-L410:

```diff
    'libharfbuzz-0.dll')
fontconfig = _dlopen(
     ffi, 'fontconfig-1', 'fontconfig', 'libfontconfig', 'libfontconfig.so.1',
-    'libfontconfig-1.dylib', 'libfontconfig-1.dll')
+    'libfontconfig-1.dylib', 'libfontconfig-1.dll', 'libfontconfig.1.dylib')
 pangoft2 = _dlopen(
     ffi, 'pangoft2-1.0-0', 'pangoft2-1.0', 'libpangoft2-1.0-0',
     'libpangoft2-1.0.so.0', 'libpangoft2-1.0.dylib', 'libpangoft2-1.0-0.dll')
```

This works again; specifically it looks like the cffi backend can now find the library and doesn't have to fallback tp `ctypes.util.find_library`.

Although I am not clear exactly on what changed that would have lead to `libfontconfig.1.dylib` being present, I assume instead of `libfontconfig-1.dylib`.

@liZe would that be a possible solution to include in weasyprint? 

PS: I realise this is closed but given it's the same issue thought better to not open a new issue. Happy to open another if that's preferable.

**Comment by liZe** [comment]
> @liZe would that be a possible solution to include in weasyprint?

Thanks, it’s been included.

> Although I am not clear exactly on what changed that would have lead to `libfontconfig.1.dylib` being present, I assume instead of `libfontconfig-1.dylib`.

Maybe there’s a difference between the Intel and Apple Silicon platforms. On the older Intel platform used for our CI, it looks like libfontconfig-1.dylib is installed.

But maybe it’s also just a typo. Everything I find online talks about `libfontconfig.1.dylib`, not `libfontconfig-1.dylib`. The filename had bee added in 2016 by me, just by copying the filename pattern of the other libraries. It may just be wrong since the beginning, I’ve tried to remove the old filename to see if the CI works.

**Comment by lirsacc** [comment]
> Thanks, it’s been included.

Great, thanks!

**Comment by frnhr** [comment]
I ran into the same issue...
 * weasyprint 1.56.1 (latest)
 * python 3.9.13
 * homebrew
 * Apple silicon M1

I fixed the problem with a very vulgar crude ugly and evil copying of lib files, but maybe this tickets needs reopening?

**Comment by liZe** [comment]
> I fixed the problem with a very vulgar crude ugly and evil copying of lib files, but maybe this tickets needs reopening?

I’ve got good news for you: [WeasyPrint is now packaged in Homebrew](https://formulae.brew.sh/formula/weasyprint)! Installing and using it should now be quite straightforward.

**Comment by jonahgeorge** [comment]
I also ran into this with fontconfig installed via homebrew and weasyprint installed via pip-- solved via copying instructions above:
```sh
sudo cp $(brew --prefix fontconfig)/lib/libfontconfig.* /usr/local/lib
```

**Comment by ahmedtuzinac** [comment]
Thanks! 👍
