### ISSUE TITLE
Documentation for upgrading from v52.5

### ISSUE THREAD

**Issue by NathanQ** [Kozea/WeasyPrint#1542]
For instance, we were using [PDFFile](https://github.com/Kozea/WeasyPrint/blob/bf2b21b6e0cbaf04245082c08f5d10308c76f2ff/weasyprint/pdf.py#L139), but the `pdf.py` file where the class was written was [removed](https://github.com/Kozea/WeasyPrint/commit/97521429592b29363a8ccefd9a4cd050cd6005e2) w/o mention of upgrade procedure in changelog or docs. Thank you!

**Comment by grewn0uille** [comment]
Hello!
Sorry for the inconveniance, but PDFFile wasn’t something considered "public" and so that’s not something recommended to rely on, as indicated in the [documentation](https://doc.courtbouillon.org/weasyprint/v52.5/api.html).
What was your usecase?

**Comment by NathanQ** [comment]
Hello,

Ok, no problem. I believe I used the [example code snippet](https://doc.courtbouillon.org/weasyprint/v52.5/tips-tricks.html?highlight=pdffile#id3) when we started using the package. The use case is using `PDFFile` to write pdf files. 

 ```git
 def render_to_pdf_response(template_name, filename, context):
-    html = HTML(string=render_to_string(template_name, context))
-    pdf_file = PDFFile(BytesIO(html.write_pdf(
-        stylesheets=[],
-    )))
-    pdf_content = pdf_file.fileobj.getvalue()
+    html = HTML(string=render_to_string(template_name, context))
+    pdf_file = html.write_pdf()

     response = HttpResponse()
     response['Content-Type'] = 'application/pdf'
-    response['Content-Length'] = len(pdf_content)
+    response['Content-Length'] = len(pdf_file)
     response['Content-Disposition'] = f'attachment; filename="{filename}"'
-    response.write(pdf_content)
+    response.write(pdf_file)
```

`HTML.write_pdf` seems to be generating the same file as before.  Anything look problematic?

Thank you for your help!

**Comment by grewn0uille** [comment]
The snippet was for editing the PDF. It seems that you didn’t do anything after with the PDF, so to just write PDF, your new code works the same :)
