### ISSUE TITLE
WeasyPrint Infinite Loop?

### ISSUE THREAD

**Issue by VikR0001** [Kozea/WeasyPrint#1549]
I've got an infinite loop in WeasyPrint 54.0, with a particular html file (one of many I'm processing). What is considered the best practices way of handling this? I can skip this html file and move on to the next one - but is there a way to detect and break out of an infinite loop occurring in WeasyPrint?

**Comment by liZe** [comment]
Hello!

To solve the bug, the best solution is to report the bug with a HTML/CSS sample reproducing the problem. 

Unfortunately, there’s no easy way to detect infinite loops in WeasyPrint 😒. Playing with [the weasyprint.progress logger](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#logging) could be helpful, but I don’t know a clean solution to stop the rendering.

**Comment by LukasKlement** [comment]
@VikR0001 if you're working with columns, you may experience the same issue as here: https://github.com/Kozea/WeasyPrint/issues/1020

What I did was to run a seperate WeasyPrint==47 instance to deal with column layouts. To catch any other infinite loops, I use multiprocess together with a timeout signal to raise a timeout error if a specified maximum execution time is exceeded.

**Comment by VikR0001** [comment]
Very good.
