### ISSUE TITLE
mimetype guessing when using url_fetcher fails for .css after upgrading to 0.20.x

### ISSUE THREAD

**Issue by dosena** [Kozea/WeasyPrint#155]
In 0.19.2, the code below worked in my url_fetcher.

Starting in 0.20.x, I have to explictly add `d['mimeType'] = 'text/css'` in order for the stylesheet to be applied to the resulting PDF. If I don't, I get a completely style-less document.

Note that other files such as PNGs are found and inserted into the resulting PDF as expected.

The workaround is easy (explicitly add the mimetype), but I thought I'd let you know...

``` 
   def __call__(self, url):                                                                               
        if url.startswith("file://"):
                ...                                 
                with open(path) as f:
                    d = {'string': f.read()}                                                               
                    return d
        return weasyprint.default_url_fetcher(url)
```

**Comment by liZe** [comment]
@dosena is your problem solved now?

**Comment by xzy3** [comment]
I am getting this same error in 0.42.3. Setting `text/css` manually as the `mime_type` works.

The message is: `Unsupported stylesheet type None for <css url>`
