### ISSUE TITLE
Text duplicated after line break at non-breaking space

### ISSUE THREAD

**Issue by Greunlis** [Kozea/WeasyPrint#1561]
I just found a strange regression between versions 53.4 and 54.
When this HTML is rendered (no CSS applied)
`Lorem ipsum dolor sit <b>amet</b> Somehow this part is duplicated on next line&nbsp;<b>bold</b> text.`
WeasyPrint v. 54.0 ignores non-breaking space and duplicates part of the text on next line.
See [test.pdf](https://github.com/Kozea/WeasyPrint/files/8007671/test.pdf)
Version 53.4 ignores the non-breaking space too, but at least doesn't duplicate the text.

When last few words are wrapped in a span, it seems fine in both versions.
`Lorem ipsum dolor sit <b>amet</b> Somehow this part is duplicated on next <span>line&nbsp;<b>bold</b> text.</span>`

Thanks for looking into it.

**Comment by liZe** [comment]
Thanks for the report!

This bug has been fixed by 562a2499 (the commit message has the wrong commit number 😒). Real-world tests are welcome!
