### ISSUE TITLE
lib/python3.6/site-packages/weasyprint/fonts.py:219: UserWarning: @font-face not supported: FontConfig cannot load default config file   '@font-face not supported: '

### ISSUE THREAD

**Issue by yashvarshney003** [Kozea/WeasyPrint#1567]
How to solve this issue I want to run a python script from Django shell? 
@practicingruby

**Comment by liZe** [comment]
Hello.

We’ll need more information to solve your problem. Could you please provide your OS version and the full backtrace?

**Comment by yashvarshney003** [comment]
Back trace:- Fontconfig error: Cannot load default config file
/Users/computername/myenv/lib/python3.6/site-packages/weasyprint/fonts.py:217: UserWarning: @font-face not supported: FontConfig cannot load default config file
 '@font-face not supported: '
/Users/{computername}/myenv/lib/python3.6/site-packages/weasyprint/fonts.py:455: UserWarning: Expect ugly output with font-size: 0
 warnings.warn('Expect ugly output with font-size: 0')
 
 Os name: Mac os BIg sur

**Comment by liZe** [comment]
Don’t hesitate to reopen if you have more information.
