### ISSUE TITLE
How to set the page width for the paper width

### ISSUE THREAD

**Issue by lazex** [Kozea/WeasyPrint#1579]
In the browser, the size of 1px changes according to the width of the body.
However, in WeasyPrint, the size of 1px is fixed.
How can I specify the page width for the paper width? 

---

Below is my HTML.

```html
<!doctype html>
<meta charset="utf-8" />

<style>
	@page {
		size: A4;
	}
	
	body {
		width: 400px; /* change here */
	}
	
	h1 {
		font-size: 32px;
	}
	p {
		font-size: 16px;
	}
	.box {
		background: red;
		width: 300px;
		height: 300px;
	}
</style>

<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<div class="box"></div>
```

### Browser & 400px

![browser-400px](https://user-images.githubusercontent.com/6133978/155727031-baa79b70-f1c3-47e5-bccc-01218aad762f.png)

### Browser & 1000px

![browser-1000px](https://user-images.githubusercontent.com/6133978/155727039-4cef8fe9-7308-4a1f-8bed-08fe7439f63c.png)

### WeasyPrint & 400px

![wp-400px](https://user-images.githubusercontent.com/6133978/155727046-4fa6ce4a-dedb-412a-a65e-9bce6dbaf973.png)

### WeasyPrint & 1000px

![wp-1000px](https://user-images.githubusercontent.com/6133978/155727055-d61b0b9d-2988-433b-b7d8-93f426e93c1e.png)

---

```
# weasyprint --version
WeasyPrint version 54.1
```

**Comment by grewn0uille** [comment]
Hello!
The conversion between px and cm are defined in the [spec](https://www.w3.org/TR/css-values-3/#absolute-lengths). So 400px is always the same number of cm.
When you use the browser to convert your HTML into PDF, it scales the content to make it fit into the page. That’s why when you put a size of 1000px it fits.
If you want to change the size of the paper width, you can modify the size in your [at-page rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size).

**Comment by lazex** [comment]
I want to keep the PDF paper size at A4.
I tried the transform scale function, but it seems that the page breaks at the position before scale.
Is this normal behavior?
Doesn't it have a scale function like a browser?

```css
	body {
		width: 1000px;
		transform: scale(0.66);
		transform-origin: 0 0;
	}
```

---

```html
<!doctype html>
<meta charset="utf-8" />

<style>
	@page {
		size: A4;
	}
	
	body {
		width: 1000px;
		transform: scale(0.66);
		transform-origin: 0 0;
	}
	
	h1 {
		font-size: 32px;
	}
	p {
		font-size: 16px;
	}
	.box {
		background: red;
		width: 300px;
		height: 300px;
	}
</style>

<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<h1>title</h1>
<p>
	text11 text12 text13 text14 text15
	text21 text22 text23 text24 text25
	text31 text32 text33 text34 text35
	text41 text42 text43 text44 text45
	text51 text52 text53 text54 text55
</p>
<div class="box"></div>
```
![transform-scale](https://user-images.githubusercontent.com/6133978/155741135-6fa0b61c-410b-4daa-9312-80df33526001.png)

**Comment by liZe** [comment]
> I tried the transform scale function, but it seems that the page breaks at the position before scale.
> Is this normal behavior?

Yes. The transformation functions change the drawing, but not the layout.

> Doesn't it have a scale function like a browser?

No. But you have at least 2 solutions:
- Generate a larger PDF with WeasyPrint and scale it with Ghostscript (or another PDF manipulation tool).
- Use the `em` unit everywhere, and change the font size in the `html` tag to get the scale you want.

**Comment by lazex** [comment]
I solved this problem by outputting a large paper size with the same aspect ratio and scaling it with cpdf.

```css
@page {
	/* A4(210mm 297mm) * 1.5  */
	size: 315mm 445.5mm;
}
```

```sh
weasyprint doc.html doc.pdf
cpdf -scale-to-fit a4portrait doc.pdf -o doc.pdf
```

Thank you.
