### ISSUE TITLE
Fonts not being loaded on WeasyPrint 53.4

### ISSUE THREAD

**Issue by HoshiYamazaki** [Kozea/WeasyPrint#1581]
[This is rather question/help request rather than current project issue, but if you can help -> thanks!]

Hey,
So I wanted to update WeasyPrint from 52.5 to 53.4 on my project, and now for some reason is not loading fonts into pdf correctly (I think). I wanted to know what changed from the version to version and why it can behave like this.

WeasyPrint 53.4:
![image](https://user-images.githubusercontent.com/21007545/155988004-e3e7eb67-f20c-4a80-8731-10965fedfa85.png)

WeasyPrint 52.5:
![image](https://user-images.githubusercontent.com/21007545/155988112-242090c9-a604-4f76-80ef-20534c401cb0.png)

Fonts are loaded using FontConfig, from template `style.css` file, and also by using font-faces like this:
```html
@font-face {
      font-family: 'Roboto';
      src: local('Roboto'), url('{% static 'reports/avantage/fonts/Roboto-Regular.ttf' %}') format('truetype');
      unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

**Comment by grewn0uille** [comment]
Hello!
Can you please provide HTML/CSS files and generated PDFs?

**Comment by HoshiYamazaki** [comment]
Hmm, I don't really want to provide generated PDF's because they are actually indeed targeted for commercial use, but I can help with logs and code.

Python code:
```python
file_buffer = io.BytesIO(html.write_pdf(
        stylesheets=[
            f'{base_css}/style.min.css',
            CSS(string="""
                @page {
                    size: A4;
                    margin: 0.5cm;
                    background-color: rgb(245, 245, 245) !important;
                }
                body {
                  background-color: rgb(245, 245, 245) !important;
                }
            """),
        ],
        font_config=fonts.FontConfiguration(),
    ))
```

HTML before body:
```
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Raport PDF</title>
  <style>
    body{
      margin: 48px 48px 0 48px;
      font-size: 13px;
    }

    div, p{
    text-align: justify;
      text-justify: inter-word;
    }

    .page-selector{
      page-break-before: always;
      margin-bottom: 48px;
    }

    @font-face {
      font-family: 'Roboto';
      src: local('Roboto'), url('{% static 'reports/avantage/fonts/Roboto-Regular.ttf' %}') format('truetype');
      unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
    }

    @font-face {
      font-family: 'Sarabun';
      src: local('Sarabun'), url('{% static 'reports/avantage/fonts/Sarabun-Regular.ttf' %}') format('truetype');
      unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
    }

    .logo-xyz {
      display: inline-block;
      width: 100%;
      margin-bottom: 24px;
    }

    .logo-xyz img {
      width: 175px;
      float: right;
    }

    #input-data tr:nth-child(odd),
    #calculated-report tr:nth-child(odd) {
      background: #FFF;
    }

    #input-data tr:nth-child(even),
    #calculated-report tr:nth-child(even) {
      background: rgba(237, 244, 247, 1);
    }

    .tr-breakpoint {
      background: rgba(219, 233, 240, 1) !important;
    }

    #calculated-report td:not(:first-child) {
      text-align: right;
    }

    #components{
      width: 95%;
      display: block;
      margin-left: auto;
      margin-right: auto;
    }

    #nested-raport{
      width: 90%;
      margin-left: auto;
      margin-right: auto;
    }

    #calculated-report td:first-child {
      width: 60%;
    }
  </style>
</head>
```

And the styles are also loaded from style.css from Avantage template: 
https://themeforest.net/item/avantage-consulting-wordpress-theme/23821574?gclid=CjwKCAiAgvKQBhBbEiwAaPQw3DWndnvE-aLrgYlFtXmwHEu_OmfaL8KelJcvCt_MZgWOenMEbB-pmRoC2MkQAvD_BwE

WeasyPrint log:
https://pastebin.com/zuhykAEB

**Comment by grewn0uille** [comment]
Hm, that’s strange that you got italic with 52.5 as the fonts are Regular.
Also, in the CSS, there is nothing to define the font-family to use. 

Can you look if there are other font-faces in the style of Avantage template?

**Comment by HoshiYamazaki** [comment]
> Hm, that’s strange that you got italic with 52.5 as the fonts are Regular. Also, in the CSS, there is nothing to define the font-family to use.
> 
> Can you look if there are other font-faces in the style of Avantage template?

I got italic font since I used `<i>text</i>` HTML tag, and this is correct behaviour. What is wrong, that 53.4 doesn't generate italic font, like, it doesn't load fonts described in styles. And I'm not really sure why. I also use macOS that has rolling packages, so I'm more keen on that the packages are not really outdated in my system.

**Comment by grewn0uille** [comment]
With the CSS you shared, the Roboto font is never really called. If you want to define fonts and use them on elements, you have to do something like this (please see the example below). 

Here, we define two font-face, one with Regular Roboto and one with Italic Roboto, and we say that the whole body uses Roboto. So, Roboto is used everywhere and, as we gave information about Roboto Italic, WeasyPrint is able to apply Roboto Italic on i tags.

``` css
@font-face {
  font-family: Roboto;
  src: url("Roboto-regular.ttf");
}
@font-face {
  font-family: Roboto;
  src: url("Roboto-italic.ttf");
  font-style: italic;
}

body {
  font-family: Roboto;
}
```

With 52.5, a false italic was generated by cairo. As we don’t rely on cairo anymore, you have to define all the font-face you need.

**Comment by HoshiYamazaki** [comment]
Thanks very much - I will check it tomorrow in the project and respond to thread. Then if everything will work correctly I will close the issue.

**Comment by HoshiYamazaki** [comment]
It works! I was only loading normal weight 400 fonts, when I added next types (italic/bold) it started working. Thanks!
