### ISSUE TITLE
Alignment of footnotes spawning multiple rows

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1582]
https://print-css.rocks/lesson/lesson-footnotes

All footnote texts should be left-aligned.
Please compare to the other renderings above.

<img width="966" alt="Bildschirmfoto 2022-02-28 um 18 09 10" src="https://user-images.githubusercontent.com/594239/156026899-57940227-b038-4f4b-b146-2c7d4137971e.png">

**Comment by grewn0uille** [comment]
Hello!
Do you mean the alignment on green on the picture?
![footnotes](https://user-images.githubusercontent.com/13187416/156029326-7dcdf548-5802-4db4-8b41-aba01fcfea80.png)

**Comment by zopyx** [comment]
yes

**Comment by liZe** [comment]
Let’s keep the current behavior for now, as it follows the current specification (at least for supported features).

But you’re right, the specification could be improved. If anyone is interested in browser interoperability, the W3C will be happy to discuss this topic [on their bug tracker](https://github.com/w3c/csswg-drafts).
