### ISSUE TITLE
Data after comma in meta data is removed

### ISSUE THREAD

**Issue by Spenhouet** [Kozea/WeasyPrint#1584]
I'm unable to explain what is going on here. I'm generating a PDF via a HTML template and in the header I'm including the PDF meta data "keywords".

```html
<head>
    <meta name=keywords content='{
          "0": [38, 16],
          "1": [38, 16],
          "2": [38, 16],
          "3": [38, 16],
          "4": [38, 16],
          "5": [38, 16],
          "6": [38, 16],
    }'>
</head>
```

But when I check the PDF, the actual stored meta data is:

```
b'{\n        "0": [38, 16], "1": [38, "2": [38, "3": [38, "4": [38, "5": [38, "6": [38, }'
```

As you can see this is far from what I provided. One thing is the change in line breaks.
But ignoring this, why does it not store the `16],` part? Where does this go?

If I change the content to (notice the different number per line):

```html
<meta name=keywords content='{
        "0": [38, 11],
        "1": [38, 12],
        "2": [38, 13],
        "3": [38, 14],
        "4": [38, 15],
        "5": [38, 16],
        "6": [38, 17],
    }'>
```

Then suddenly the output is correct:

```
b'{\n        "0": [38, 11], "1": [38, 12], "2": [38, 13], "3": [38, 14], "4": [38, 15], "5": [38, 16], "6": [38, 17], }'
```

Any idea what is going on?

**Comment by liZe** [comment]
Hello!

The keywords are [a set of fields separated by a comma](https://html.spec.whatwg.org/multipage/semantics.html#meta-keywords). WeasyPrint removes the duplicates, that’s why the first example remove the extra `16]` values.

So… You shouldn’t use commas if you want a single keyword!

**Comment by Spenhouet** [comment]
I want to store a JSON in the PDF meta data. So this will make it hard.
Is there another way to do this? It seems it is not possible to set XMP data with weasyprint? Any other option?

**Comment by liZe** [comment]
You can use another field that’s not comma-separated, such as "description".

Otherwise, you can [attach](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#cmdoption-a) the json files to the PDF.

**Comment by Spenhouet** [comment]
Thanks @liZe for helping me figuring this out.
I guess doing it via attachments is cleaner.

I included the file like this:

```python
pdf = HTML(string=finished_html).write_pdf(
            optimize_size=('fonts', 'images'),
            attachments=[Attachment(filename=temppath / 'data.json')])
```

but how do I read this now?
We are using PyPDF4 for somethings so I tried it with that as explained here: https://kevinmloeffler.com/2018/07/08/how-to-extract-pdf-file-attachments-using-python-and-pypdf2/

This is looking for the file name here:
```python
catalog = pdf.trailer["/Root"]
fileNames = catalog['/Names']['/EmbeddedFiles']['/Names']
```

But there is no `/EmbeddedFiles`.
You know where I need to look for the attachments (given weasyprint stored the correctly)?

If one is not overly familiar with the PDF spec, this is really hard to navigate. Thanks for any help!

**Comment by Spenhouet** [comment]
I can not get the attachments to work.
They also do not show up in Adobe Acrobat.

I tried with filename, file file_obj and string (where string does not work at all with `Attachment`).
I'm probably missing something or should I open a new bug report?

**Comment by liZe** [comment]
Your example works for me, and so does the PyPDF2 script. I get an "attachment0" file with the content of the json.

Here is my [PDF sample](https://github.com/Kozea/WeasyPrint/files/8169736/meta.pdf), can you find the attachment included?

**Comment by Spenhouet** [comment]
Interesting, it did not work for me at all.
Could you share a MWE so that I can run 1:1 the same code on my side and see if your code works here too?

**Comment by liZe** [comment]
Here’s the PyPDF2 script I used (from your link):
```python
import PyPDF2

def getAttachments(reader):
    catalog = reader.trailer["/Root"]
    fileNames = catalog['/Names']['/EmbeddedFiles']['/Names']
    attachments = {}
    for f in fileNames:
        if isinstance(f, str):
            name = f
            dataIndex = fileNames.index(f) + 1
            fDict = fileNames[dataIndex].getObject()
            fData = fDict['/EF']['/F'].getData()
            attachments[name] = fData
    return attachments

handler = open('meta.pdf', 'rb')
reader = PyPDF2.PdfFileReader(handler)
dictionary = getAttachments(reader)
print(dictionary)
for fName, fData in dictionary.items():
    print(fName)
    with open(fName, 'wb') as outfile:
        outfile.write(fData)
```

And here’s the WeasyPrint script:
```python
from pathlib import Path
from weasyprint import HTML, Attachment

pdf = HTML('meta.html').write_pdf(
    optimize_size=('fonts', 'images'),
    attachments=[Attachment(filename=Path('meta.js'))])
open('meta.pdf', 'wb').write(pdf)
```

**Comment by liZe** [comment]
Don’t hesitate to reopen if needed!
