### ISSUE TITLE
'created' timestamp seems very low; regarding as unix timestamp

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1585]
Where is the message `'created' timestamp seems very low; regarding as unix timestamp` coming from and why?
I have a fresh Ubuntu 21.10 installation, EXT4 filesystem, the timestamps on the filesystem look fine.

**Comment by liZe** [comment]
That’s a warning given by [fontTools](https://github.com/fonttools/fonttools/blame/main/Lib/fontTools/ttLib/tables/_h_e_a_d.py#L57). There’s probably a font on your system whose "created" field is wrong.

**Comment by liZe** [comment]
Closing. If there’s a problem, it’s definitely in fontTools that should not display logs on stderr by default.

(I wasn’t sure about silencing library logs by default, but #412 really convinced me.)

**Comment by Django-27** [comment]
I ran into the same issue and found this warning in the fontTools source code and followed the lead to solve it in the hope that it will help other people who come across it


1. first， find the warning location

Envs\py311\Lib\site-packages\fontTools\ttLib\tables\_h_e_a_d.py
`
for stamp in "created", "modified":
    if value < 0x7C259DC0:  # January 1, 1970 00:00:00
        log.warning(
            "'%s' timestamp seems very low; regarding as unix timestamp", stamp
        )
        value += 0x7C259DC0
        setattr(self, stamp, value)`

2. second, find the .ttf file in your project 

3. third, open .ttf file edit website like https://font.qqe2.com/#, and modify the content like the picture

![image](https://github.com/Kozea/WeasyPrint/assets/10075605/b5ce3c2c-505a-4075-a87f-b40e925bd8b5)

**Comment by kdipippo** [comment]
Created https://github.com/fonttools/fonttools/issues/3538 to advise, as I think either strategy of checking the font when it's added in `stream.py::add_font()` or checking the results of `Subsetter::subset()` requires this input.
