### ISSUE TITLE
UserWarning: There are known rendering problems and missing features with cairo < 1.15.4

### ISSUE THREAD

**Issue by AnneCQ** [Kozea/WeasyPrint#1590]
I installed weasyprint52.5 with python under the windows system. After the installation is complete, I run the code and report the following error:

` STDERR:
           C:\Program Files\Python36\lib\site-packages\weasyprint\document.py:36: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the
 note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
             'There are known rendering problems and missing features with '
`
I checked a lot of information, but I can't solve it, what's going on?

System: Windows
Machine: AMD64
Version: 10.0.17763
Release: 10

WeasyPrint version: 52.5
Python version: 3.6.2
Cairo version: 11412
Pango version: 14014
CairoSVG version: 2.5.2

**Comment by liZe** [comment]
> I checked a lot of information, but I can't solve it, what's going on?

You have an old version of Cairo (1.14.2), so some features will be missing, as [explained in the documentation](https://doc.courtbouillon.org/weasyprint/v52.5/install.html#id5).

If you want to solve this problem, you can either:
- use a more recent version of WeasyPrint (since version 53, Cairo is not used anymore), or
- upgrade Cairo.

**Comment by AnneCQ** [comment]
> * se a more recent version of WeasyPrint (since version 53, Cairo is not used anymore)

When I upgrade weasyprint to 53, I get the following error:
` AttributeError: function/symbol 'pango_context_set_round_glyph_positions' not found in library 'C:\gstreamer\1.0\x86_64\bin\libpango-1.0-0.dll': error 0x7f`

My version is as follows:

System: Windows
Machine: AMD64
Version: 10.0.17763
Release: 10

WeasyPrint version: 53.0
Python version: 3.6.2
Pydyf version: 0.1.2
Pango version: 14014

I use the command    `pip install Pango -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com` to upgrade pango ，but still get an error, the error message is as follows:
`ERROR: Could not find a version that satisfies the requirement Pango (from versions: none)
ERROR: No matching distribution found for Pango
`

**Comment by liZe** [comment]
> `AttributeError: function/symbol 'pango_context_set_round_glyph_positions' not found in library 'C:\gstreamer\1.0\x86_64\bin\libpango-1.0-0.dll': error 0x7f`

Yes, [WeasyPrint 53 requires Pango 1.44](https://doc.courtbouillon.org/weasyprint/v53.4/first_steps.html#installation) and you have Pango 1.40.

Pango is not a Python package, it’s not installed with `pip`. If you followed the [installation guide](https://doc.courtbouillon.org/weasyprint/v53.4/first_steps.html#windows), you used the [GTK3 installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases). Its [latest version includes Pango 1.50.3](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/tree/2022-01-04).

So:
- if you can/want to use old libraries, you’ll have to use an old version of WeasyPrint,
- if you can/want to update these old libraries, you’ll be able to use recent versions of WeasyPrint.

**Comment by AnneCQ** [comment]
> > `AttributeError: function/symbol 'pango_context_set_round_glyph_positions' not found in library 'C:\gstreamer\1.0\x86_64\bin\libpango-1.0-0.dll': error 0x7f`
> 
> Yes, [WeasyPrint 53 requires Pango 1.44](https://doc.courtbouillon.org/weasyprint/v53.4/first_steps.html#installation) and you have Pango 1.40.
> 
> Pango is not a Python package, it’s not installed with `pip`. If you followed the [installation guide](https://doc.courtbouillon.org/weasyprint/v53.4/first_steps.html#windows), you used the [GTK3 installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases). Its [latest version includes Pango 1.50.3](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/tree/2022-01-04).
> 
> So:
> 
> * if you can/want to use old libraries, you’ll have to use an old version of WeasyPrint,
> * if you can/want to update these old libraries, you’ll be able to use recent versions of WeasyPrint.

Thank you, following your method, I have solved my problem
