### ISSUE TITLE
The WeasyPrint Matrix Robots Project is Born

### ISSUE THREAD

**Issue by FrancoisCapon** [Kozea/WeasyPrint#1594]
Hi,

As you saw, I studied how WeasPrint work (as enduser) and I decide to create a complementary project ([The WeasyPrint :books: Matrix Robots :robot: Project ](https://github.com/FrancoisCapon/TheWeasyPrintMatrixRobotsProject)) to help to create WeasyPrint templates and documents because WeasyPrint is really an "awesome document factory" :+1: .

I opened a discussion to get your feedback if you have, of course,  time to look a this project:
* https://github.com/FrancoisCapon/TheWeasyPrintMatrixRobotsProject/discussions/1

**Comment by liZe** [comment]
Thanks for sharing this project! I’ve added a comment in the discussion, I hope that you’ll find the time do develop it!
