### ISSUE TITLE
Suspected clipPath regression in v53 after moving away from Cairo

### ISSUE THREAD

**Issue by br-cpvc** [Kozea/WeasyPrint#1595]
Problem: SVG images with clipPath substructures is overwritten by a black box covering the entire clipPath rect.

The problem started occurring after updating weasyprint from 52.5 to 53.0 (or higher - tested until 54.2) and trying to convert files containing structures like in the following example:

```
cat foo.html 
<html>
  <body>
    <table>
      <tr>
        <td><img src="foo.svg"></td>
      </tr>
    <table>
  </body>
</html>


cat foo.svg 
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 24.3.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
         viewBox="0 0 612 82.88" style="enable-background:new 0 0 612 82.88;" xml:space="preserve">
<style type="text/css">
        .st0{fill:#FF0000;}
        .st1{clip-path:url(#SVGID_2_);fill:#00FF00;}
</style>
<g>
        <g>
                <polygon class="st0" points="330,60 50,60 0,25 95,25"/>
                <g>
   <defs>
    <rect id="SVGID_1_" x="477.92" y="-4.11" width="96.74" height="48.41"/>
   </defs>
   <clipPath id="SVGID_2_">
    <use xlink:href="#SVGID_1_"  style="overflow:visible;"/>
   </clipPath>
   <path class="st1" d="M500,10h50v50h-50v-50"/>
  </g>
        </g>
</g>
</svg>
```

The green box that should be drawn in the example (using the clipPath) is getting overwritten by a black box covering the clipPath rect. See attached pdfs rendered using different weasyprint versions: [foo_52.5.pdf](https://github.com/Kozea/WeasyPrint/files/8260209/foo_52.5.pdf) [foo_53.0.pdf](https://github.com/Kozea/WeasyPrint/files/8260195/foo_53.0.pdf)

I suspect that this has something to do with the change described in: https://github.com/Kozea/WeasyPrint/issues/1374

**Comment by liZe** [comment]
Hi!

> I suspect that this has something to do with the change described in: #1374

Yes, this case is not in the "simple cases" supported.

**Comment by liZe** [comment]
Fun to see that this bug has just been reported and fixed in CairoSVG too!

https://github.com/Kozea/CairoSVG/issues/395
