### ISSUE TITLE
Bootstrap grid system in all pages

### ISSUE THREAD

**Issue by Danscath** [Kozea/WeasyPrint#1596]
Im not sure if this is a "issue" or just a feature its not possible to do but I want to generate a dynamic PDF with data from my models.

I have a total of 4 models, two of them I want to display on the left part with more width than the others two so I have some like 
col-8 and col-4 

The problem is the next, when I render a PDF if the data's to long and I have more than 1 page, the col-4 content only display on the last one, and I want to put it on the first page and keep the background color on the others if there's no data

Here is a image with part of the last 2 pages. As I say I want all the right part with the gray background and only display the data (text white) on the first page and so on in case there's data enough to get the next pages

![Screenshot_3](https://user-images.githubusercontent.com/38579689/158633461-0e53d5a1-b3c4-4c77-8b17-5b03cb2c7ffa.jpg)

So far I onlye want to know if its possible so i dont send any code yet so I dont waste your time reading code with nosense xD

**Comment by Danscath** [comment]
> As far as I can remember, Bootstrap’s grid system relies on flex. We know that the flex layout is very limited right now, and it will be improved in [version 56](https://github.com/Kozea/WeasyPrint/milestone/33). So… the best thing to do now is to wait for version 56.

Thanks!! But I also have a problem, my system is Centos7 and I cant download a pango version beyond 1.42 with Yum so I cant use the most recent versions x_x im trying tu find a rpm and install with dependencies but there's a lot of errors with the dependencies version of pango like glib2 is there any way to skip the pango requirement? I dont think so but for ask i dont lost anything

**Comment by liZe** [comment]
> is there any way to skip the pango requirement?

Unfortunately no. If you use Centos7, you’re basically stuck with older but stable versions of packages, and thus of WeasyPrint (and that’s actually the goal of this distribution).

**Comment by Danscath** [comment]
> > is there any way to skip the pango requirement?
> 
> Unfortunately no. If you use Centos7, you’re basically stuck with older but stable versions of packages, and thus of WeasyPrint (and that’s actually the goal of this distribution).

Ok! Thanks anywhere for made this tool I just change the design of pdfs to create something I can with the version I can use ^^
