### ISSUE TITLE
\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib     raise OSError(msg) OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

### ISSUE THREAD

**Issue by Maha-s200** [Kozea/WeasyPrint#1602]
\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by liZe** [comment]
Hello!

This error means that WeasyPrint can’t find gobject. Did you follow [the installation guide for Windows](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows)?
