### ISSUE TITLE
function/symbol 'pango_context_set_round_glyph_positions' not found in library 'libpango-1.0.so.0': /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: pango_context_set_round_glyph_positions

### ISSUE THREAD

**Issue by AhmedSalam22** [Kozea/WeasyPrint#1610]
![image](https://user-images.githubusercontent.com/35177448/159520126-964a181f-8303-4662-951d-422c58e823d0.png)

![image](https://user-images.githubusercontent.com/35177448/159520096-91a8c3d0-b32c-4a87-aed8-73d695e63ced.png)
I don't know how to upgrade pango version

i have used this command in the documentation

**Comment by summersz** [comment]
From the installation instructions:
If the version of Pango provided by your distribution is too old, you can use version 52.5 of WeasyPrint which does not need recent Pango features.

**Comment by AhmedSalam22** [comment]
> From the installation instructions: If the version of Pango provided by your distribution is too old, you can use version 52.5 of WeasyPrint which does not need recent Pango features.

with weasyprint==52.5 create this error
![image](https://user-images.githubusercontent.com/35177448/159531175-7e45af11-6067-4ea2-afa4-49519f2d6ead.png)

**Comment by night-fury-web** [comment]
@liZe I think the libpango required for WeasyPrint 53 or above series is available in ubuntu 20.04.
Did you ever install libpango 1.44 on ubuntu 18.04 successfully?
Or should I upgrade OS to 20.04 to use the latest WeasyPrint?

**Comment by grewn0uille** [comment]
Hello!

According to [Ubuntu packages](https://packages.ubuntu.com/bionic/libpango-1.0-0), the version of libpango on Ubuntu 18.04 is 1.40 which isn’t recent enough for [recent WeasyPrint versions](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#installation).

So, if you want to use WeasyPrint on Ubuntu 18.04, you’ll be limited to WeasyPrint 52.5.

**Comment by Faruq-Shobola** [comment]
This solved my problem, Thanks

**Comment by caarmen** [comment]
Hello!

Is this still an issue? I'm on Ubuntu 18, yet weasyprint version 66.0 seems to work fine now.

**Comment by liZe** [comment]
> Is this still an issue? I'm on Ubuntu 18, yet weasyprint version 66.0 seems to work fine now.

@caarmen You can check your Pango version with `weasyprint --info`. You need at least 1.44.

**Comment by caarmen** [comment]
> > Is this still an issue? I'm on Ubuntu 18, yet weasyprint version 66.0 seems to work fine now.
> 
> [@caarmen](https://github.com/caarmen) You can check your Pango version with `weasyprint --info`. You need at least 1.44.

Thanks!

Actually, I double-checked, and I'm on a more recent ubuntu after all 😅
