### ISSUE TITLE
Access images in protected directory (HTTPError: HTTP Error 403: Forbidden)

### ISSUE THREAD

**Issue by poly82** [Kozea/WeasyPrint#1617]
Hi, I'm trying to use WeasyPrint to generate PDFs in Django and when I try to access the image path I get a 403 error due to lack of permissions.

`2022-03-29 10:52:45,988 weasyprint   ERROR    Failed to load image at "http://myweb.com/media/manuals/1/images/image_1.png" (HTTPError: HTTP Error 403: Forbidden)`

I've noticed that the WeasyPrint HTML request doesn't keep the original authentication header and it doesn't add "same-origin" to identify that the call is internal.

`2022-03-29 10:52:45,987 myweb.views ERROR    {'Host': 'myweb.com', 'X-Real-Ip': 'XX.XX.XX.XX', 'X-Forwarded-For': 'XX.XX.XX.XX', 'Connection': 'close', 'User-Agent': 'WeasyPrint 52.2 (http://weasyprint.org/)', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate'}`

My PDF generation code is:

```
@action(detail=True)
def informToPDF(self, request, pk = None):
template = get_template('inform.html')
context = {'manual': get_object_or_404(mdb.Manual,pk=pk),
            	'comp': {'name': 'MyWeb'},
        	}        
html_template = template.render(context)
pdf = HTML(string=html_template, base_url=request.build_absolute_uri(settings.MEDIA_URL)).write_pdf()
return HttpResponse(pdf, content_type='application/pdf')

```
	

The HTML code where I use the images is as follows:

```

{% for step in manual.steps.all %}
<tr>
<td class="text-center">{{ step.id }}</td>
<td>{{ step.names.es }}</td>
<td class="text-center">{{ step.descs.es }}</td>
<td class="text-center">
<img src="{{step.images.first.path}}" alt="" border=3 height=100 width=300>
</td>
</tr>
{% endfor %}

```

How can I modify the HTML class header or get it to access the images without creating a security hole?

Thanks in advance

**Comment by liZe** [comment]
Hello!

[Django-WeasyPrint](https://github.com/fdemmer/django-weasyprint) fixes this kind of problems. Otherwise, you’ll have to use your own custom URL fetcher.

**Comment by poly82** [comment]
Thanks you
