### ISSUE TITLE
Use local fonts without installing them to system

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#1618]
I am trying to run weasyprint as a Google Cloudfunction which unfortunately forbids installing fonts to the system. 

Is there a way to tell Weasyprint to use fonts placed in the same (or some other relative) directory?

**Comment by liZe** [comment]
Hello!

You can use `@font-face` rules with a `file://…` URL.

**Comment by knyttl** [comment]
Yeah, but that would be a bit overkill when we use this font everywhere and would lead easily to human errors. So there is no way to link to it directly without installing them?

**Comment by liZe** [comment]
> Hi, thanks for a quick response!

No problem!

> So there is no way to link to it directly without installing them?

Not directly.

Another (more complex) solution would be to add the folder where you put the fonts into Fontconfig’s configuration. I don’t know If it’s possible to do that with Google Cloudfunction, but if you don’t have access to the filesystem you can do that in Python using code equivalent to [what’s done for `@font-face` rules](https://github.com/Kozea/WeasyPrint/blob/3f3956844a4b1f960b68747f70ac6c69dfdcfd6f/weasyprint/text/fonts.py#L235-L272). This way, you’ll be able to give Fontconfig a folder where fonts will be searched, just as if they were installed. You’ll probably only need a `<dir…` tag, as explained in [Fontconfig’s documentation](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html):

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <dir>/path/to/folder</dir>
</fontconfig>
```

I’ve never done that, but I suppose that [creating a `FontConfig` object](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#instantiating-html-and-css-objects), adding the configuration with `fontconfig.FcConfigParseAndLoad()` and giving it to `write_pdf()` will do the trick!

**Comment by knyttl** [comment]
👍 👍 👍  thanks for a great comment! Will try!

**Comment by knyttl** [comment]
note that

```
from weasyprint.text.fonts import FontConfiguration
```

seems to be superseded with:

```
from weasyprint.fonts import FontConfiguration
```

in the linked documentation 👍

**Comment by liZe** [comment]
`weasyprint.fonts` is for [52.x](https://doc.courtbouillon.org/weasyprint/v52.5/tutorial.html#instantiating-html-and-css-objects), but `weasyprint.text.fonts` has to be used since [53.x](https://doc.courtbouillon.org/weasyprint/v53.4/first_steps.html#instantiating-html-and-css-objects).

**Comment by knyttl** [comment]
the `stylesheets=[css]` does not seem to work for me - see here - I include the same font from the `css` field and then from html `<head><style>`, but only the `<style>` seems to work. Am I missing something here?

```python
import functions_framework
from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration
from flask import Flask, request, make_response
import os

@functions_framework.http
def entrypoint(request):
       name = request.args.get('filename', 'export.pdf')
       title = request.args.get('title', 'Untitled')
        # regular PDF rendering
        print(os.getcwd())
        html = HTML(string=
                    '''
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <meta charset="utf-8"/>
                        <title>Test File</title>
                        <style>
                            /** this works */
                            @font-face {
                                font-family: ProximaNova-header;
                                font-weight: normal;
                                src: url(https://static.goout.net/fonts/ProximaNovaRegular.woff) format('woff');
                            }
                            body {
                                font-family: sans-serif;
                                font-weight: normal;
                            }
                        </style>
                    </head>
                    <body>
                        <div>Hello World (correctly sans-serif)</div>
                        <div style="font-family: ProximaNova-css;">Hello World (still sans-serif)</div>
                        <div style="font-family: ProximaNova-header;">Hello World (only this works)</div>
                    </body>
                    </html>
                    ''')
        font_config = FontConfiguration()
        css = CSS(
            string='''
                /** this is being ignored */
                @font-face {
                    font-family: ProximaNova-css;
                    font-weight: normal;
                    src: url(https://static.goout.net/fonts/ProximaNovaRegular.woff) format('woff');
                }
                ''',
            font_config=font_config
        )
        pdf = html.write_pdf(stylesheets=[css])
        response = make_response(pdf)
        response.headers['Content-Type'] = 'application/pdf'
        response.headers['Content-Disposition'] = 'inline;filename=%s' % name
        return response
```

<img width="435" alt="Screenshot 2022-03-31 at 11 01 59" src="https://user-images.githubusercontent.com/401107/161018556-ee7a0d0d-e350-4ac9-8a9e-e14ab26709e6.png">

**Comment by liZe** [comment]
> Am I missing something here?

You need to give `font_config` to `write_pdf`.

**Comment by knyttl** [comment]
👍
