### ISSUE TITLE
Multiple values for "text-decoration" are not applied correctly

### ISSUE THREAD

**Issue by Morikko** [Kozea/WeasyPrint#1621]
We have found a few cases where `text-decoration` values are not applied correctly: only a single value is possible at a time.

The HTML output is based on Firefox 98 and the PDF is generated with `weasyprint==54.3`.

```python
import weasyprint
from IPython.display import display_pdf

css_size = weasyprint.CSS(string="""
@page {
  size: 100mm;
}
""")

def generate_pdf(data_str):
    html_obj = weasyprint.HTML(string=data_str)
    pdf_data = html_obj.write_pdf(stylesheets=[css_size])
    display_pdf(pdf_data, raw=True)
```

## Single Tag with multiple options

```html
<span style="text-decoration: underline line-through;">
        demo text
</span>
```

### HTML

![2022-04-12_11-16 html_single_span_multi_values](https://user-images.githubusercontent.com/7831572/162927438-1ccb991f-556c-4e4b-8456-66fa8f012d32.png)

### PDF

![2022-04-12_11-17 pdf_single_span_multi_values_regression](https://user-images.githubusercontent.com/7831572/162928680-77f375a3-b423-4c0d-bd45-04ce4d54a999.png)

It used to work with `weasyprint==52.5`.

![2022-04-12_11-17 pdf_single_span_multi_values](https://user-images.githubusercontent.com/7831572/162927441-c35d4861-fbf5-49f0-8a86-2a51dbc70402.png)

## Two tags with different options

```html
<span style="text-decoration: underline;">
    <span style="text-decoration: line-through;">
        demo text
    </span>toto
</span>
```

### HTML

![2022-04-12_11-22 html_multi_spans](https://user-images.githubusercontent.com/7831572/162927444-03a0ab35-acf0-4c3b-bb48-1dcdb8b3268b.png)

### PDF

![2022-04-12_11-23 pdf_multi_spans](https://user-images.githubusercontent.com/7831572/162927447-3114d248-d241-438a-b7ec-5c179095601e.png)

## Historical HTML tags

```html
<p><u><s>demo text</s>toto</u></p>

<p><del><u>demo text</u>toto</del></p>
```

### HTML

![2022-04-12_11-23 html_html_tags](https://user-images.githubusercontent.com/7831572/162927452-2170e1da-32dd-4832-b1d7-960325196da3.png)

### PDF

![2022-04-12_11-23 pdf_html_tags](https://user-images.githubusercontent.com/7831572/162927453-2515976d-4fa7-4460-8a39-d344c5f4c977.png)

## With other CSS properties

Other CSS properties like `color` or `font-weight` are applied aside only a single value `text-decoration`:
```html
<del style="color: blue;"><u>d<span style="font-weight: bold;">em</span>o te<b>xt</b></u></del>
```
### HTML
![2022-04-12_11-26 html_cross_css](https://user-images.githubusercontent.com/7831572/162928265-7a3b20d4-ef2d-4ee4-af00-44a9c63746fc.png)

### PDF
![2022-04-12_11-26 pdf_cross_css](https://user-images.githubusercontent.com/7831572/162928268-326959f0-d8ef-4c17-90b8-4e22760f020d.png)

**Comment by liZe** [comment]
Thanks a lot for the bug report and the examples! It should be fixed (and tested) in master, real-life tests are welcome.

**Comment by Morikko** [comment]
Thank you for the reactivity. I can confirm that the case `Single Tag with multiple options` (regression) is fixed.

However all the other cases are still broken. Only the most nested value of `text-decoration` is kept.

**Comment by liZe** [comment]
> However all the other cases are still broken. Only the most nested value of `text-decoration` is kept.

Sorry, I shouldn’t have closed this issue. Only the first example is fixed.

**Comment by liZe** [comment]
The CSS specification is [full of surprises about inheritance](https://www.w3.org/TR/2019/CR-css-text-decor-3-20190813/#line-decoration).

**Comment by liZe** [comment]
This bug is now closed, because all the examples given here are now rendered "correctly".

But, even if the new behavior is better than the previous one, it’s far from perfect. Here are some examples of what doesn’t work yet:

> For all other box types, the decorations are propagated to all in-flow children.

Decorations are currently propagated to all children.

> […] for underlines and overlines the UA must use a single thickness and position on each line for the decorations deriving from a single [decorating box](https://www.w3.org/TR/2019/CR-css-text-decor-3-20190813/#decorating-box).

That’s not true for thickness (because of font-weight or font-size), that’s not true for color.

If anyone needs this problem to be fixed, please open a new issue! Unfortunately, it will require more complicated code (and more time).

**Comment by liZe** [comment]
(There’s one more bug that needs to be fixed, sorry…)

**Comment by liZe** [comment]
(Tests now pass.)

**Comment by Morikko** [comment]
Great, I confirm that all the cases in this issue are fixed :tada:. Thank you very much. That CSS specification is definitively not simple :sweat_smile: 

Do you know when 55 is planned to be released ?

--- 

For the non technical CSS people like me, here the visual impact of the non cover cases

```html
<div style="color: red;text-decoration: underline blue;">
a
<span style="text-decoration: line-through lime;">b</span>
c</div>
```

![2022-04-13_11-07 color diff weasyprint](https://user-images.githubusercontent.com/7831572/163141920-1d46c879-7207-4bb0-b537-66fe193ac3b3.png)

```html
<div style="color: red;text-decoration: underline blue;">a<span style="float: right;">b</span></div>
```

![2022-04-13_11-11 weasyprint float case](https://user-images.githubusercontent.com/7831572/163142639-7c817d4e-463c-412d-b7bf-7e3d82c5c3c3.png)

**Comment by liZe** [comment]
> Do you know when 55 is planned to be released ?

You can expect a beta to be released in the next days / weeks.
