### ISSUE TITLE
border for pagedjs_page_content not working

### ISSUE THREAD

**Issue by benz-law** [Kozea/WeasyPrint#1623]
Hello All

.pagedjs_page_content {border: 1px solid;}

This line creates a border around the pagedjs_area but it is not being rendered.

**Comment by liZe** [comment]
Hello!

This project is WeasyPrint, not [PagedJS](https://pagedjs.org/), that’s why you can’t use a PagesJS-specific property.

If you want to add a border to the page content, you can try to add a border to the `html` or `body` tag for example.
