### ISSUE TITLE
`inline-block` elements taller than page get clipped

### ISSUE THREAD

**Issue by iabw** [Kozea/WeasyPrint#164]
A `block` will clip off the bottom of the page once it no longer contains "real" content ( f.e., an element with a height of 3000px, but no child elements ). This in itself seems slightly problematic and you're already aware of, I believe.

However, an `inline-block` will clip even if it has valid content, once it's taller than the page. It also seems to add a blank page before itself?

Since floats and tables don't cross page boundaries, this seems to make it impossible to have a column layout with a column taller than a page. I assume I'm doing something wrong, since no one else seems to have this problem...

I was having this problem on a "real" page, with 2 columns, one of which is very tall. I reduced it to the following reproduction:

An example pdf with a `block` with a set height of 3000px, and enough text to go onto 3 pages.
![block](https://f.cloud.github.com/assets/1054569/2056595/f7be290a-8ae2-11e3-88f4-51ceeb18647d.gif)

The same block flagged as an inline-block only shows one page of Text before clipping.
![inline-block](https://f.cloud.github.com/assets/1054569/2056593/ec045aa8-8ae2-11e3-806a-128bbdd1025c.gif)

Here's the html for this test -

```
<div>

    <div style="    /* display: inline-block; */  width: 70%;   height: 3000px;    background: blue;">
  
        <div style="height:10px;">Text</div> <!-- repeat a couple hundred times -->

    </div>
    <div>Text here</div>
</div>
```

**Comment by liZe** [comment]
Duplicates #36.
