### ISSUE TITLE
Support font-variant: small-caps approximation

### ISSUE THREAD

**Issue by meunierd** [Kozea/WeasyPrint#166]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant

If a font doesn't provide actual small caps, weasyprint should do Mozilla's scaling trick.

**Comment by joostrijneveld** [comment]
There appear to be two issues on this topic: see https://github.com/Kozea/WeasyPrint/issues/123. I figured I'd just refer to the other one here for completeness.

**Comment by liZe** [comment]
Let's say it's a duplicate of #123.
