### ISSUE TITLE
How to Implement Conftest.py

### ISSUE THREAD

**Issue by kmcilwain112** [Kozea/WeasyPrint#1663]
Hi I understand that WeasyPrint no longer supports PNG generation and I also saw the conftest.py code. What I don't understand is how to integrate that code. I'm helping to develop an instance of Inventree, an opensource stock tracker that uses WeasyPrint to generate stock item labels. https://github.com/inventree. Any help with this? I'm also very to new to coding and Python/Django.

**Comment by liZe** [comment]
Hi!

The code that’s in `conftest.py` is not meant to be used directly outside of WeasyPrint’s tests, but you can of course copy it, adapt it and use it in your own project. The main code is in these lines, you can adapt the content of the variables for your own requirements:

https://github.com/Kozea/WeasyPrint/blob/ae83010c838c409cf8ec6d7d83a632dba58cd2da/tests/conftest.py#L30-L34

The main problem you may have is Ghostscript’s license: AGPL. We’ve asked Artifex if we could use this code to test WeasyPrint without changing WeasyPrint’s code licence, and they were OK, but it should not be the case for a web service like yours. The other widely open-source implementation is Poppler, and it’s also distributed under a viral licence: GPL.
