### ISSUE TITLE
Issue with floating container with multiple elements

### ISSUE THREAD

**Issue by TadaCZE** [Kozea/WeasyPrint#1664]
A container of multiple elements floated left is duplicating some of them in a weird way. I will link to [the document](https://filebin.net/2tdmz5ys8q9kpqtp) I am working on which exhibits the issue.

**Comment by liZe** [comment]
Hi!

I can reproduce your issue with version 54.3, but it seems to be fixed in 55.0. Could you try this version please?

**Comment by TadaCZE** [comment]
I see, I was using the version from debian repos, which is slightly older. I tried the version from python pip and it works. Thanks!
