### ISSUE TITLE
EXIF metadata for image rotation not supported

### ISSUE THREAD

**Issue by takkaria** [Kozea/WeasyPrint#1667]
Steps to reproduce:
1. Make an HTML file:
```
<!DOCTYPE html>
<img src="img.jpg">
```
2. Get [img.jpg from here](https://user-images.githubusercontent.com/405490/176438593-c6e4bb26-5ca6-4c94-8855-b66195246b34.jpg)
3. Run `weasyprint in.html out.pdf`
4. Open the PDF

What I expected:
* the PDF shows the image the correct way round

What happens:
* It's rotated 180 degrees

Suggested fix:
* Somewhere we need to call ImageOps.exif_transpose: `image = PIL.ImageOps.exif_transpose(image)`, presumably inside [`RasterImage`](https://github.com/Kozea/WeasyPrint/blob/358b9469bf250dd13e37752180a4eeae173eb4c5/weasyprint/images.py#L31), maybe in `draw`?

**Comment by liZe** [comment]
Thanks for the bug report and for the hint! It’s fixed in `master`, tests are welcome!
