### ISSUE TITLE
@page :nth(an+b) rule bug

### ISSUE THREAD

**Issue by kian-supportinglines** [Kozea/WeasyPrint#1668]
Version: 52.5 (No fix found in changelogs of newer versions)

I've noticed that when using the `@page :nth(an+b)` rule, the `b` value is not being used.

E.g. `@page :nth(2n+5)` will apply to every other page, instead of every other page after the 5th page.

A simple way to reproduce this bug:

HTML:
```
<body>
    <div>
        <p>Some content here</p>
    <div>
    <div style="page-break-before:always">  <!-- To enforce a new page being created -->
        <p>Some other content here</p>
    <div>
</body>
```
CSS:
```
@page :nth(n+1) {
    bottom-right: {
        content: counter(page);
    }
}
```
This should put page numbers for the second page only, but you should see that it creates page numbers for both pages. I tried debugging and only found that the stylesheets were getting correctly parsed, but I don't know why when rendering the CSS it doesn't take into account the `b`.

**Comment by liZe** [comment]
Hi!

Thanks a lot for your bug report, it’s fixed in `master` and will be fixed in version 56.
