### ISSUE TITLE
Even more weird float issues with duplicating elements

### ISSUE THREAD

**Issue by TadaCZE** [Kozea/WeasyPrint#1669]
![scrsht1](https://user-images.githubusercontent.com/33400123/176546105-3f9a4391-3935-4f8e-9dae-3c6de2e8582d.png)

In that image, every element is included only once on the page. The two sides are floating left and right respectively, exactly half the size of the parent container. Interesting thing is, that another instance of almost the same technique being used later displays no issue.

Firefox render:

![scrsht2](https://user-images.githubusercontent.com/33400123/176546141-d2aa80c4-bf79-40a6-8ae1-4db2f6546155.png)

Using weasyprint 55.0 from pip

**Comment by liZe** [comment]
Hi!

Could you please include a whole HTML/CSS document with images and fonts? This kind of bug is hard to reproduce without an example.

**Comment by TadaCZE** [comment]
gimme a moment i am uploading to filebin

**Comment by TadaCZE** [comment]
also uses alegreya sans as a system font, but not sure if it is necessary for reproduction

**Comment by liZe** [comment]
Hi!

Thanks a gain for the bug report.

The bug has been fixed and tested in `master`. The diff is quite small but it includes a "big" change in the way floats (and other out-of-flow elements) are handled, so it won’t be included in version 56 (as a beta has already been released) but in version 57.

Tests (and more bug reports 😁) are welcome!
