### ISSUE TITLE
page break in table ignores page margin

### ISSUE THREAD

**Issue by fatelgit** [Kozea/WeasyPrint#1673]
Hello,
first of all I would like to say that I really appreciate you work on weasyprint - it's a truly amazing tool! Although I am facing a weird issue. I was trying to generate an invoice/report with a repeating header/footer on each page.
When the table exceeds the page size it will break to a new page but it seems to ignore the @page top margin - the footer seems to be calculated fine but the table continues right on top of the second page. I have created a gist with my code: https://gist.github.com/fatelgit/0bb129ac6e7a4eb572a90b92a8c16dc5

This is my result: [test.pdf](https://github.com/Kozea/WeasyPrint/files/9053062/test.pdf)
System info:
```System: Linux
Machine: x86_64
Version: #1 SMP PREEMPT Wed May 18 09:20:53 UTC 2022
Release: 5.17.9-1-MANJARO

WeasyPrint version: 55.0
Python version: 3.10.4
Pydyf version: 0.2.0
Pango version: 15007
```

**Comment by liZe** [comment]
Thanks for the bug report! It’s been fixed in master and will be included in version 56.
