### ISSUE TITLE
Footnote Area: Support Max Height

### ISSUE THREAD

**Issue by andrewerlanger** [Kozea/WeasyPrint#1674]
Hi there!

First and foremost: many thanks for the amazing work you've done on the footnotes front already, really impressive stuff 👏 

I just wanted to add one more item to the short [list of features missing from the specification](https://github.com/Kozea/WeasyPrint/issues/298#issuecomment-991720941): supporting the `max-height` property for the footnote area. 

Per the [w3.org footnote specs](https://www.w3.org/TR/css-gcpm-3/#footnote-area-size):
> The [max-height](http://www.w3.org/TR/CSS21/visudet.html#propdef-max-height) property on the footnote area limits the size of this area, unless the page contains only footnotes (as may happen on the last page of a document).
>
> Since it is undesirable for a page to consist only of footnotes, user agents may set a default max-height value on the footnote area.

As it stands, setting a `max-height` on the footnote area will technically limit the height, but the footnotes themselves overflow from the container rather than being displayed on the following page.

For example, the following css...

```css
@footnote {
  max-height: 6cm;
  background: red;
  float: bottom;
}
```

...produces this in the PDF:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/29393156/177791802-fc58c80b-a254-421c-a550-c524a712165e.png">

Ideally, footnotes `5.` onwards would be displayed on the following page 🤓

**Comment by liZe** [comment]
Hi @andrewerlanger 

The feature has been added and tested, we hope that it works well for your use case!

**Comment by andrewerlanger** [comment]
@liZe thanks for the super quick turnaround, much appreciated! 🙏
