### ISSUE TITLE
Letter spacing regression in v55 and v56 - I can't reopen #1662 

### ISSUE THREAD

**Issue by violuke** [Kozea/WeasyPrint#1675]
I have commented on https://github.com/Kozea/WeasyPrint/issues/1662#issuecomment-1178982582 which is closed and cannot re-open it, sorry. I hope I've provided enough information, and thanks for all your help and the brilliant package :pray:

**Comment by grewn0uille** [comment]
Thanks for the information on #1662 :)! 
We reopened it.
