### ISSUE TITLE
Left and right gap around page area

### ISSUE THREAD

**Issue by preahkumpii** [Kozea/WeasyPrint#1676]
There is an unexplained "margin" around the page area, between the page area and the margin boxes on the left and right. I say "margin" because I do not think this is caused by the `margin` property in CSS. See the image attached. I colored the background of the page area and various margin boxes to make the gap stand out.

![CleanShot 2022-07-08 at 14 28 46@2x](https://user-images.githubusercontent.com/2834324/178050037-2189b098-417e-47bb-a854-052e217cb6c0.png)

**Comment by liZe** [comment]
Hi!

There’s a 8px margin on the body in the user agent stylesheet, that’s probably what you see. Setting `body { margin: 0 }` should fix this.

**Comment by preahkumpii** [comment]
That fixed the problem. Thanks. May I suggest the documentation note this default margin in the body?

**Comment by liZe** [comment]
> That fixed the problem. Thanks.

🚀

> May I suggest the documentation note this default margin in the body?

It’s hard to know what to put in the documentation without overloading it, but here I think that it shouldn’t be mentioned: this rule is pretty well known by CSS users as it’s set in all the browsers.

If anyone comes here and want to know more about the user agent stylesheet (where the default style is), you can read it [in the repository](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/css/html5_ua.css).
