### ISSUE TITLE
Test failure in test_otb_font (Python 3.11, Fedora rawhide)

### ISSUE THREAD

**Issue by FelixSchwarz** [Kozea/WeasyPrint#1677]
I'm seeing test failures with WeasyPrint 56.0 when trying run the build for Fedora rawhide.

Any idea if this test is problematic or if this might be a Python 3.11 problem?

    =================================== FAILURES ===================================
    ________________________________ test_otb_font _________________________________
    [gw6] linux -- Python 3.11.0 /usr/bin/python3

    assert_pixels = <function assert_pixels.<locals>.<lambda> at 0x7fc79e119c60>

        def test_otb_font(assert_pixels):
    >       assert_pixels('''
                ____________________
                __RR______RR________
                __RR__RR__RR________
                __RR__RR__RR________
                ____________________
                ____________________
            ''', '''
              <style>
                @page {
                  size: 20px 6px;
                  margin: 1px;
                }
                @font-face {
                  src: url(weasyprint.otb);
                  font-family: weasyprint-otb;
                }
                body {
                  color: red;
                  font-family: weasyprint-otb;
                  font-size: 4px;
                  line-height: 1;
                }
              </style>
              AaA''')

    tests/draw/test_text.py:827: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    tests/conftest.py:99: in <lambda>
        return lambda *args, **kwargs: draw.assert_pixels(
    tests/draw/__init__.py:53: in assert_pixels
        assert_pixels_equal(name, width, height, pixels, expected_pixels)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    name = 'otb_font', width = 20, height = 6
    raw = <ImagingCore object at 0x7fc79e28d070>
    expected_raw = [(255, 255, 255), (255, 255, 255), (255, 255, 255), (255, 255, 255), (255, 255, 255), (255, 255, 255), ...]
    tolerance = 0

        def assert_pixels_equal(name, width, height, raw, expected_raw, tolerance=0):
            """Take 2 matrices of pixels and assert that they are the same."""
            if raw != expected_raw:  # pragma: no cover
                pixels = zip_longest(raw, expected_raw, fillvalue=(-1, -1, -1))
                for i, (value, expected) in enumerate(pixels):
                    if expected is None:
                        continue
                    if any(abs(value - expected) > tolerance
                           for value, expected in zip(value, expected)):
                        actual_height = len(raw) // width
                        write_png(name, raw, width, actual_height)
                        expected_raw = [
                            pixel or (255, 255, 255) for pixel in expected_raw]
                        write_png(f'{name}.expected', expected_raw, width, height)
                        x = i % width
                        y = i // width
    >                   assert 0, (
                            f'Pixel ({x}, {y}) in {name}: '
                            f'expected rgba{expected}, got rgba{value}')
    E                   AssertionError: Pixel (2, 1) in otb_font: expected rgba(255, 0, 0), got rgba(255, 255, 255)

    tests/draw/__init__.py:102: AssertionError
    ----------------------------- Captured stderr call -----------------------------
    INFO: Step 1 - Fetching and parsing HTML - HTML string
    INFO: Step 2 - Fetching and parsing CSS - CSS string
    INFO: Step 3 - Applying CSS
    INFO: Step 4 - Creating formatting structure
    INFO: Step 5 - Creating layout - Page 1
    INFO: Step 6 - Creating PDF
    INFO: Step 7 - Adding PDF metadata
    ------------------------------ Captured log call -------------------------------
    INFO     weasyprint.progress:__init__.py:88 Step 1 - Fetching and parsing HTML - HTML string
    INFO     weasyprint.progress:__init__.py:226 Step 2 - Fetching and parsing CSS - CSS string
    INFO     weasyprint.progress:__init__.py:62 Step 3 - Applying CSS
    INFO     weasyprint.progress:document.py:189 Step 4 - Creating formatting structure
    INFO     weasyprint.progress:page.py:843 Step 5 - Creating layout - Page 1
    INFO     weasyprint.progress:__init__.py:240 Step 6 - Creating PDF
    INFO     weasyprint.progress:__init__.py:400 Step 7 - Adding PDF metadata

**Comment by FelixSchwarz** [comment]
Actually the problem is not Python 3.11 as I suspected but some difference between F35 and F36: https://copr.fedorainfracloud.org/coprs/fschwarz/weasyprint56/build/4620611/
(if you are curious the root.log shows all installed packages + versions)

**Comment by liZe** [comment]
Thanks for the report.

I’ve tried to reproduce the problem with the exact same versions of Python dependencies on Gentoo (with Python 3.11 too), but the test passes.

If you ever have a way to get the PDF generated by this test, it would be really useful to understand where the problem comes from.

**Comment by FelixSchwarz** [comment]
Thank you for looking into this and trying to reproduce this. I think I managed to capture the pdf/png which causes the failing test: [debug.pdf](https://github.com/Kozea/WeasyPrint/files/9081758/debug.pdf), [debug.png](https://user-images.githubusercontent.com/212753/178211921-4b9a7d37-facb-4abf-af23-7dedfbb70def.png) (I hope I really caught the right files)

Just in case you want to debug this more in depth in fedora here is how to do it:

    # grab the src.rpm from https://download.copr.fedorainfracloud.org/results/fschwarz/weasyprint56/fedora-36-x86_64/04620611-weasyprint/
    $ mock --rebuild --no-cleanup-after -r fedora-rawhide-x86_64 weasyprint-56.0-1.fc36.src.rpm
    # wait for the build process to fail
    $ mock -r fedora-rawhide-x86_64 shell --unpriv --cwd /builddir/build/BUILD
    # now you can look around inside the build container, run stuff, whatever
    $ cd weasyprint-56.0
    $ pytest tests/draw/test_text.py

Just a few notes:

- Fedora's build process runs inside a container-like environment so it should be reproducible.
- you might need to add your unix user to the mock group to use mock.

**Comment by liZe** [comment]
> I think I managed to capture the pdf/png which causes the failing test

That’s wonderful, thanks a lot!

Very good news: WeasyPrint finds and reads the font correctly, the problem is a 1-pixel vertical shift. This test is young and hasn’t been tested for years on different platforms, that’s probably a problem caused by a rounding "error" in a non-Python library (Harfbuzz? Pango? Ghostscript?).

We can find a workaround in the test to make it pass everywhere. We’ll try this week to launch the tests in the container and fix the problem.

**Comment by FelixSchwarz** [comment]
Thank you very much :-)

**Comment by liZe** [comment]
> Thank you very much :-)

Sorry, I didn’t add a comment here. Does the commit fix the bug for you?
