### ISSUE TITLE
Links do not work in debian OS in the generated PDF

### ISSUE THREAD

**Issue by tshailesh-vmw** [Kozea/WeasyPrint#1681]
I am creating a PDF document in which I am using anchor tag so that it can be used to open links.

The issue is link works in the generated pdf in my dev server which is in ubuntu server
```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

But the links in generated pdf using same data do not work in debian server.
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

The python libraries installed are same in both servers. Any pointers to solve this issue?

**Comment by liZe** [comment]
Hi!

Could you please share the PDFs you have generated on Ubuntu and on Debian?

**Comment by tshailesh-vmw** [comment]
PFA of the PDFs. Also the version I am using is weasyprint==52
[debian.pdf](https://github.com/Kozea/WeasyPrint/files/9103150/debian.pdf)
[ubuntu.pdf](https://github.com/Kozea/WeasyPrint/files/9103151/ubuntu.pdf)

**Comment by grewn0uille** [comment]
Hello!

The Debain PDF has been generated using cairo 1.14.8 while the Ubuntu one has been generated using cairo 1.15.10.

Cairo > 1.15 is [needed to have working links](https://github.com/Kozea/WeasyPrint/issues/915#issuecomment-519241879).
