### ISSUE TITLE
Support PDF/UA

### ISSUE THREAD

**Issue by grewn0uille** [Kozea/WeasyPrint#1682]

**Comment by flintflump** [comment]
As I have not seen this issue until now, I spent the last few days reading the PDF spec trying to understand marked content and structured data and implement it in weasyprint.

Did you already start to implement this feature? Can I maybe help here?

**Comment by grewn0uille** [comment]
Hi @flintflump,

Sorry for the delay.

Yes it’s indeed a recent issue. We already start working on this!
You can have a look on the related [branch](https://github.com/Kozea/WeasyPrint/tree/pdf-ua) and [pr](https://github.com/Kozea/WeasyPrint/pull/1704).
