### ISSUE TITLE
Really slow rendering of balanced 3 column layouts and 2 column breaking blocks

### ISSUE THREAD

**Issue by LukasKlement** [Kozea/WeasyPrint#1689]
Similar to the issue https://github.com/Kozea/WeasyPrint/issues/1642 - I have found another infinite loop with 3-column layouts, when column-fill is set to balance and there are exactly two direct child blocks of the columned div with `page-break-before: always;` set.

In the above scenario, with a single-page PDF:
Rendering with `column-fill: balance;`: >100s
Rendering with `column-fill: auto;`: <10s

WeasyPrint version: v56.0

**Comment by liZe** [comment]
Hi! Thanks for your bug report.

I’ve tried to reproduce this problem with this code, but it works with version 56:

```html
<style>
  div {columns: 3}
  article {page-break-before: always}
</style>
<div>
  <article>1</article>
  <article>2</article>
</div>
```

Could you please provide a sample that’s broken for you?

**Comment by liZe** [comment]
Please add a comment if you can provide a sample that’s broken for you with current master branch.
