### ISSUE TITLE
cannot load library 'libcairo-2.dll': error 0x7e

### ISSUE THREAD

**Issue by killwasf** [Kozea/WeasyPrint#1701]
raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by liZe** [comment]
Hi!

Cairo is not used by WeasyPrint anymore. Please follow the documentation and try the latest version of WeasyPrint!
