### ISSUE TITLE
Receiving URLFetchingError

### ISSUE THREAD

**Issue by steverae1** [Kozea/WeasyPrint#1702]
Hi Folks,

First off, thanks for WeasyPrint. It's been terrific for me.

I'm receiving the URLFetchingError from urls.py below:

```python
@contextlib.contextmanager
def fetch(url_fetcher, url):
    """Call an url_fetcher, fill in optional data, and clean up."""
    try:
        result = url_fetcher(url)
    except Exception as exception:
        raise URLFetchingError(f'{type(exception).__name__}: {exception}')
    result.setdefault('redirected_url', url)
    result.setdefault('mime_type', None)
    if 'file_obj' in result:
        try:
            yield result
        finally:
            try:
                result['file_obj'].close()
            except Exception:  # pragma: no cover
                # May already be closed or something.
                # This is just cleanup anyway: log but make it non-fatal.
                LOGGER.warning(
                    'Error when closing stream for %s:\n%s',
                    url, traceback.format_exc())
    else:
        yield result
```

My url itself has been verified correct as it runs fine through flask/gunicorn. The error arrives when your render_url is called.
The URL itself is very long so I suspect I'm violating a length limit for your url variable above?? My spcific error follows...

Thank you for any help/info you could provide.

Regards,

Steve

Here is my exact error message:

```
 File "/usr/local/lib/python3.7/site-packages/weasyprint/urls.py", line 254, in fetch
raise URLFetchingError('%s: %s' % (type(exc).__name__, str(exc)))
weasyprint.urls.URLFetchingError: ValueError: Flask-WeasyPrint got HTTP status 500 INTERNAL SERVER ERROR
```

and here is the url being submitted:

`http://localhostb'/aggregatetopdf/HC-31/%5B1478%2C%201272%2C%2086.06%2C%201066%2C%20343%2C%2079%2C%201234%2C%2097.01%2C%201016%2C%20218%2C%2038%2C%202.99%2C%2033%2C%205%2C%2084%2C%206.6%2C%2036%2C%202.83%5D/%5B%2712:00%27%2C%20%2712:05%27%2C%20%2712:10%27%2C%20%2712:15%27%2C%20%2712:20%27%2C%20%2712:25%27%2C%20%2712:30%27%2C%20%2712:35%27%2C%20%2712:40%27%2C%20%2712:45%27%2C%20%2712:50%27%2C%20%2712:55%27%2C%20%2713:00%27%2C%20%2713:05%27%2C%20%2713:10%27%2C%20%2713:15%27%2C%20%2713:20%27%2C%20%2713:25%27%2C%20%2713:30%27%2C%20%2713:35%27%2C%20%2713:40%27%2C%20%2713:45%27%2C%20%2713:50%27%2C%20%2713:55%27%2C%20%2714:00%27%2C%20%2714:05%27%2C%20%2714:10%27%2C%20%2714:15%27%2C%20%2714:20%27%2C%20%2714:25%27%2C%20%2714:30%27%2C%20%2714:35%27%2C%20%2714:40%27%2C%20%2714:45%27%2C%20%2714:50%27%2C%20%2714:55%27%2C%20%2715:00%27%2C%20%2715:05%27%2C%20%2715:10%27%2C%20%2715:15%27%2C%20%2715:20%27%2C%20%2715:25%27%2C%20%2715:30%27%2C%20%2715:35%27%2C%20%2715:40%27%2C%20%2715:45%27%2C%20%2715:50%27%2C%20%2715:55%27%2C%20%2716:00%27%5D/%5B17%2C%2020%2C%2022%2C%2022%2C%2022%2C%2023%2C%2025%2C%2026%2C%2029%2C%2035%2C%2047%2C%2081%2C%20273%2C%20725%2C%20862%2C%20941%2C%201012%2C%201026%2C%201055%2C%201066%2C%201056%2C%201051%2C%201042%2C%201043%2C%201006%2C%20992%2C%20969%2C%20557%2C%20190%2C%20153%2C%20130%2C%20113%2C%20106%2C%2095%2C%2086%2C%2077%2C%2073%2C%2072%2C%2071%2C%2067%2C%2065%2C%2063%2C%2063%2C%2061%2C%2057%2C%2055%2C%2054%2C%2051%2C%2049%5D/%5B1%2C%204%2C%202%2C%201%2C%201%2C%202%2C%202%2C%201%2C%203%2C%206%2C%2012%2C%2035%2C%20197%2C%20453%2C%20145%2C%2090%2C%2081%2C%2035%2C%2045%2C%2037%2C%2016%2C%2023%2C%2016%2C%2015%2C%2015%2C%2012%2C%2013%2C%208%2C%205%2C%206%2C%205%2C%204%2C%204%2C%206%2C%201%2C%202%2C%201%2C%200%2C%202%2C%200%2C%201%2C%201%2C%201%2C%200%2C%200%2C%200%2C%200%2C%200%2C%201%5D/%5B0%2C%201%2C%200%2C%201%2C%201%2C%201%2C%200%2C%200%2C%200%2C%200%2C%200%2C%201%2C%206%2C%202%2C%209%2C%2011%2C%2011%2C%2021%2C%2017%2C%2028%2C%2027%2C%2028%2C%2025%2C%2014%2C%2052%2C%2026%2C%2036%2C%20420%2C%20371%2C%2043%2C%2028%2C%2021%2C%2011%2C%2015%2C%2010%2C%2011%2C%205%2C%201%2C%203%2C%204%2C%203%2C%203%2C%201%2C%202%2C%204%2C%202%2C%201%2C%203%2C%203%5D/%5B%2712:00%27%2C%20%2712:05%27%2C%20%2712:10%27%2C%20%2712:15%27%2C%20%2712:20%27%2C%20%2712:25%27%2C%20%2712:30%27%2C%20%2712:35%27%2C%20%2712:40%27%2C%20%2712:45%27%2C%20%2712:50%27%2C%20%2712:55%27%2C%20%2713:00%27%2C%20%2713:05%27%2C%20%2713:10%27%2C%20%2713:15%27%2C%20%2713:20%27%2C%20%2713:25%27%2C%20%2713:30%27%2C%20%2713:35%27%2C%20%2713:40%27%2C%20%2713:45%27%2C%20%2713:50%27%2C%20%2713:55%27%2C%20%2714:00%27%2C%20%2714:05%27%2C%20%2714:10%27%2C%20%2714:15%27%2C%20%2714:20%27%2C%20%2714:25%27%2C%20%2714:30%27%2C%20%2714:35%27%2C%20%2714:40%27%2C%20%2714:45%27%2C%20%2714:50%27%2C%20%2714:55%27%2C%20%2715:00%27%2C%20%2715:05%27%2C%20%2715:10%27%2C%20%2715:15%27%2C%20%2715:20%27%2C%20%2715:25%27%2C%20%2715:30%27%2C%20%2715:35%27%2C%20%2715:40%27%2C%20%2715:45%27%2C%20%2715:50%27%2C%20%2715:55%27%2C%20%2716:00%27%5D/%5B17%2C%2020%2C%2022%2C%2022%2C%2022%2C%2023%2C%2025%2C%2026%2C%2029%2C%2035%2C%2047%2C%2081%2C%20273%2C%20725%2C%20862%2C%20941%2C%201012%2C%201026%2C%201055%2C%201066%2C%201056%2C%201051%2C%201042%2C%201043%2C%201006%2C%20992%2C%20969%2C%20557%2C%20190%2C%20153%2C%20130%2C%20113%2C%20106%2C%2095%2C%2086%2C%2077%2C%2073%2C%2072%2C%2071%2C%2067%2C%2065%2C%2063%2C%2063%2C%2061%2C%2057%2C%2055%2C%2054%2C%2051%2C%2049%5D/%5B%270-5%27%2C%20%275-10%27%2C%20%2710-15%27%2C%20%2715-20%27%2C%20%2720-25%27%2C%20%2725-30%27%2C%20%2730-35%27%2C%20%2735-40%27%2C%20%2740-45%27%2C%20%2745-50%27%2C%20%2750-55%27%2C%20%2755-60%27%2C%20%2760-65%27%2C%20%2765-70%27%2C%20%2770-75%27%2C%20%2775-80%27%2C%20%2780-85%27%2C%20%2785-90%27%2C%20%2790-95%27%2C%20%2795-100%27%2C%20%27100-105%27%2C%20%27105-110%27%2C%20%27110-115%27%2C%20%27115-120%27%2C%20%27120-125%27%2C%20%27125-130%27%2C%20%27130-135%27%2C%20%27135-140%27%2C%20%27140-145%27%2C%20%27145-150%27%2C%20%27150-155%27%2C%20%27155-160%27%2C%20%27160-165%27%2C%20%27165-170%27%2C%20%27170-175%27%2C%20%27175-180%27%2C%20%27180-185%27%2C%20%27185-190%27%2C%20%27190-195%27%2C%20%27195-200%27%2C%20%27200-205%27%2C%20%27205-210%27%2C%20%27210-215%27%2C%20%27215-220%27%2C%20%27220-225%27%2C%20%27225-230%27%2C%20%27230-235%27%2C%20%27235-240%27%5D/%5B31%2C%2027%2C%2039%2C%2026%2C%2027%2C%2036%2C%2027%2C%2041%2C%2037%2C%2045%2C%2057%2C%2073%2C%2069%2C%20172%2C%20298%2C%2067%2C%2031%2C%2024%2C%2010%2C%208%2C%2013%2C%204%2C%201%2C%203%2C%203%2C%205%2C%209%2C%2010%2C%205%2C%201%2C%204%2C%204%2C%203%2C%206%2C%206%2C%2011%2C%204%2C%202%2C%200%2C%200%2C%200%2C%200%2C%200%2C%200%2C%200%2C%200%2C%200%2C%202%5D/%5B%27Ontario%27%2C%20%27Other%27%5D/%5B%27Unknown%27%2C%20%27Alberta%27%2C%20%27British%20Columbia%27%2C%20%27Manitoba%27%2C%20%27New%20Brunswick%27%2C%20%27Newfoundland%20and%20Labrador%27%2C%20%27Nova%20Scotia%27%2C%20%27Ontario%27%2C%20%27Prince%20Edward%20Island%27%2C%20%27Quebec%27%2C%20%27Saskatchewan%27%2C%20%27Washington%27%5D/%5B%27rgb%28222%2C%20204%2C%20118%29%27%2C%20%27rgb%2818%2C%2069%2C%209%29%27%5D/%5B1298%2C%20178%5D/%5B0%2C%2021%2C%2017%2C%2035%2C%203%2C%203%2C%2010%2C%201298%2C%203%2C%2083%2C%202%2C%201%5D/%5B0.0%2C%201.42%2C%201.15%2C%202.37%2C%200.2%2C%200.2%2C%200.68%2C%2087.94%2C%200.2%2C%205.62%2C%200.14%2C%200.07%5D/1476/%5B%27app80.hc-sc.gc.ca%27%2C%20%27unknown%27%2C%20%27Other%27%5D/%5B%27rgb%28232%2C%2016%2C%2016%29%27%2C%20%27rgb%28250%2C%2082%2C%2070%29%27%2C%20%27rgb%2897%2C%2074%2C%20224%29%27%5D/%5B208%2C%201266%2C%203%5D/1477'`

**Comment by liZe** [comment]
Hi!

This URL seems to be wrong, with `b'…'` after `localhost`, meaning that a string and a bytestring have been concatenated. How did you build this URL?

**Comment by steverae1** [comment]
Bonjour Guillaume,

Merci pour ton reply. It is greatly appreciated!!

All is fine for me now. I discovered a small typo in my aggregatetopdf route definition.
Sorry to bother you for nothing!!

Best Regards,

Steve
