### ISSUE TITLE
Cropped tables in generated document

### ISSUE THREAD

**Issue by lcc** [Kozea/WeasyPrint#1705]
First I would like to thank you guys for developing this great tool! 

So I've a really big table to render and the generated document "crops" the final part of the table. I am taking a look at your documentation/issues, but this doesn't seem to have a documented solution.  Can you guys give any directions/advice? 

![Screen Shot 2022-08-08 at 10 34 16](https://user-images.githubusercontent.com/22527121/183430730-8b4a64b9-be69-4fee-a315-01263b7ae383.png)

**Comment by liZe** [comment]
Hi!

Could you please share the HTML/CSS causing this problem? Thanks!

**Comment by lcc** [comment]
Here you go.

CSS:
```
css = wsp.CSS(string=f"""
    @font-face {{
        font-family: {font_family};
    }}
    
    @page {{
        width: {width};
        margin: 0;
        padding: 0;
    }}
    
    html, body {{
        font-size: {font_size};
    }}
""", font_config=font_config)
```

[HTML](https://github.com/Kozea/WeasyPrint/files/9282777/test.txt)

**Comment by liZe** [comment]
Looks like it works for me:
[table.pdf](https://github.com/Kozea/WeasyPrint/files/9284504/table.pdf)

Do you use the latest version of WeasyPrint? If you do, could you share your PDF please?

(The "1" being put alone at the top of some pages is caused by their 5px bottom padding, making them higher than the other cells of the row.)

**Comment by lcc** [comment]
I am using an older version of this library (one that still has write_png), sorry I didn't make this clear, I also needed to print this in one page. I was able to make it work with some adaptations from [#274](https://github.com/Kozea/WeasyPrint/issues/274#issuecomment-150668169) so everything should be good by now. 

Thank you so much for your help, I am going to close this issue as it's been resolved.
