### ISSUE TITLE
Footnote Positioning in Multicolumn Layouts

### ISSUE THREAD

**Issue by andrewerlanger** [Kozea/WeasyPrint#1707]
Hi team! I've been running into what I think might be two related issues when working with footnotes in multicolumn layouts.

The first is that the footnotes are quite often rendered on the following page of the PDF. So if the `::footnote-call` appears on page 1, for example, the corresponding `::footnote-marker` will appear on page 2:
<img width="751" alt="Screenshot 2022-08-15 at 09 59 04" src="https://user-images.githubusercontent.com/29393156/184607067-7a192889-f7b0-4cbc-a49a-9e7d4f8acbc0.png">

The (potentially) related issue is that the ordering of footnotes is also sometimes thrown off in multicolumn layouts. Here, for example, footnote `18` appears ahead of `17` in the footnotes container, despite coming afterwards in the actual text:
<img width="734" alt="Screenshot 2022-08-15 at 10 04 35" src="https://user-images.githubusercontent.com/29393156/184608676-6346fa68-9b1c-4285-9205-e2d7c8959792.png">

I'm unfortunately not well-versed enough in Python or PDF to propose a fix myself, but thought I'd leave this issue here in the hope someone else might have a solution in mind :)

Thanks!

**Comment by liZe** [comment]
Everything should now work correctly and [many tests](https://github.com/Kozea/WeasyPrint/blob/master/tests/draw/test_footnote_column.py) have been added to avoid regressions.
