### ISSUE TITLE
Doesn't render RTL text in span correctly

### ISSUE THREAD

**Issue by kesara** [Kozea/WeasyPrint#1711]
Input:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>RTL test</title>
  </head>
  <body>
    <p>
      The following example shows how the Hebrew-language string
      <span>
        "שלום" (HEBREW LETTER SHIN, HEBREW LETTER LAMED, HEBREW LETTER VAV,
        HEBREW LETTER FINAL MEM, U+05E9 U+05DC U+05D5 U+05DD)
      </span>
      is represented. Note the <code>rtl</code> direction expressed by setting
      the third element in the array to "true".
    </p>
  </body>
</html>
```

Weasyptint info:
```
$ weasyprint --info
System: Darwin
Machine: arm64
Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101
Release: 21.6.0

WeasyPrint version: 53.0
Python version: 3.10.6
Pydyf version: 0.2.0
Pango version: 15009
```

Command:
```
weasyprint test.html -o test.pdf
```

Generated output: 
[test.pdf](https://github.com/Kozea/WeasyPrint/files/9397955/test.pdf)
<img width="791" alt="Screen Shot 2022-08-23 at 10 23 00 AM" src="https://user-images.githubusercontent.com/1027692/186029243-444fb427-4930-49ed-ac9c-492339f7ed6c.png">

Expected output:
<img width="790" alt="Screen Shot 2022-08-23 at 10 23 49 AM" src="https://user-images.githubusercontent.com/1027692/186029353-feeac36c-9a36-459f-b5a1-a6c7305f1d17.png">

When the RTL text is inside the `<p>` tag without `<span>` tag, WeasyPrint output is correct.

**Comment by liZe** [comment]
Hi!

Unfortunately, bidirectional text is known to be broken in many ways for a very long time. Solving this issue would require quite a lot of dedicated time, and the topic was not a priority in [our last survey](https://www.courtbouillon.org/blog/00010-weasyprint-survey-2021) 😢. So, to be honest, it won’t be solved soon unless someone wants to invest some personal time or some money to get this very old issue closed.

Let’s continue the discussion in #106 if needed.
