### ISSUE TITLE
Width is not rendered properly in pdf

### ISSUE THREAD

**Issue by ariefsn** [Kozea/WeasyPrint#1714]
Hi, I have a problem while using the MJML.
So what I'm doing is, create a document with MJML, and export to HTML version.
Then uses this HTML string to build the PDF.

- browser version
![image](https://user-images.githubusercontent.com/33569737/188822681-388636d7-7cba-45bb-ab9d-05a33a2b974a.png)
- pdf version
![image](https://user-images.githubusercontent.com/33569737/188822826-69e34187-f9fe-488e-b8d5-eef17ac30ba7.png)

please help.

**Comment by liZe** [comment]
Hi!

If height is set in the HTML file (and not in CSS), you have to use the [`--presentational-hints`](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html?highlight=hints#cmdoption-p). If it doesn’t fix your problem, please share your whole HTML and CSS files, we’ll reopen the issue.
