### ISSUE TITLE
Warn that unsupported properties are unsupported or unimplemented instead of unknown

### ISSUE THREAD

**Issue by victorwss** [Kozea/WeasyPrint#1720]
Some standard CSS properties are unsupported by weasyprint. Like `box-shadow`, `text-shadow`, `user-select`, `font-size-adjust` among others. Many have poor support even in the mainstream browsers.

Weasyprint report them as unknown, just as if their name were typoed, gibberish or anything like that, it gives a message like this:

```
WARNING:weasyprint:Ignored `box-shadow:0px 10px 20px #808080` at 4:647, unknown property.
WARNING:weasyprint:Ignored `user-select: none` at 143:3, unknown property.
```

Instead of telling that they are unknown, it would be nice to say that they are unsupported or unimplemented or something like that.

**Comment by liZe** [comment]
Hi, and thanks for this issue!

It’s a good idea, but we don’t want to follow the endlessly increasing list of CSS properties to differentiate unknown and unsupported properties. 

Actually, WeasyPrint behaves just like other browsers, that use the same error message for unknown and unsupported properties:
- Safari gives "Unsupported property name",
- Chrome gives "Unknown property name",
- Firefox gives "Invalid property name".

So… We’ll just do as they do, and continue to use the same error message everywhere 😁.
