### ISSUE TITLE
 cannot load library 'pango-1.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0

### ISSUE THREAD

**Issue by Danuragtiwari** [Kozea/WeasyPrint#1721]
OSError: cannot load library 'pango-1.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0' i am getting this error how to reslove it in windows?

**Comment by grewn0uille** [comment]
Hello @Danuragtiwari,
You can find troubleshooting steps in the [documentation](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#troubleshooting) and [installation steps for Windows](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#windows).
