### ISSUE TITLE
rendering doesn't work on my intranet

### ISSUE THREAD

**Issue by rlindao-siglo21** [Kozea/WeasyPrint#1729]
I have a web portal published on a windows server web server with ISS, the problem is that on the server the report is correct but on the user's computer the expected report does not appear.

![image](https://user-images.githubusercontent.com/81703006/192330541-372599d4-143c-42c7-8516-ba74bfd9b5b8.png)

![image](https://user-images.githubusercontent.com/81703006/192330838-cad81ed2-e100-435d-9e37-8a273ce9644d.png)

**Comment by liZe** [comment]
Hi!

I’m not sure to understand your problem. Does your message mean that, from the same HTML file, WeasyPrint installed on the server generates the top PDF document, and WeasyPrint installed on the user’s computer generates the bottom PDF document?

**Comment by rlindao-siglo21** [comment]
Correct, the same HTML file installed on the server generates the document on the top and if someone accesses the portal as a client the pdf of the bottom is generated


{% load static %}
<!DOCTYPE html>
<html lang=es>
  <head>
    <meta charset="utf-8">
    <title>LlamadaServicio</title>
    <meta name="description" content="Llamada de Servicio">

    
  </head>
  
  <body>


    <div class="row">
      <div class="column" style="max-width: 30% "><img src="static/logo-sg21.png" alt="Lamp" style="object-fit:contain;
            width:200px;
            height:100px;
          "/></div>
      <div class="column" style="max-width: 25% "><img src="static/Service-21-LogoCS.jpg" alt="Lamp" style="object-fit:contain;
            width:200px;
            height:100px;
          "/></div>
      <div class="column" style="max-width: 45% ; border: thin solid black ; margin-left: 10.4em;">
        <p style="font-size:20px;"><strong>Llamada de Servicio</strong> </p>
        <p style="margin-top: 0.4em;"><strong> N° de Llamada:</strong>          {{data.CALLID}}</p>
        <p><strong>Creado el:</strong>              {{data.CREADO_EL }} {{data.CREADO_EL_HORA}}</p>
        <p><strong>Status:</strong>                 {{data.STATUS}}</p>

      </div>
    </div>


      {% comment %} Primer Recuadro {% endcomment %}
      <div class="row" style="border: thin solid black">
            <div class="column" style="max-width: 70% ">
              <p><strong>Razon social:</strong>          {{data.RAZON_SOCIAL}}</p>
              <p style="margin-top: 0.4em;" ><strong>Persona de Contacto:</strong>   {{data.PERSONA_CONTACTO}}</p>
            </div>

            <div class="column" style="max-width: 30%; margin-left: 7em; ">
              <p><strong>RUC/CI:</strong>               {{data.RUC}}</p>
              <p style="margin-top: 0.4em;"><strong>Teléfono:</strong>              {{data.TELEFONO}}</p>
            </div>
        
      </div>
      {% comment %} Fin Primer Recuadro {% endcomment %}

    {% comment %} Segundo Recuadro {% endcomment %}

    <div class="row" style="margin-top: 0.5em; border: thin solid black">

      <div class="row" style="margin-top: 0.1em">
            <div class="column" style="max-width: 50% ">
              <p><strong>Código:</strong>                 {{data.CODIGO_ITEM}}</p> 
            </div> 
            <div class="column" style="max-width: 50%;margin-left: 10em; " >
              <p><strong>N° Referencia:</strong>          {{data.NOREF}}</p>
            </div> 
      </div> 

      <div class="row" style="margin-top:  0.5em">
        <p><strong>Descripción:</strong>            {{data.DESCRIPCION}}</p>
      </div> 

      <div class="row" style="margin-top:  0.5em">
            <div class="column" style="max-width: 50% ">
              <p><strong>Serie:</strong>                 {% if data.SERIE%}{{data.SERIE}} {% endif %}</p>
            </div> 
            <div class="column" style="max-width: 50%;margin-left: 10em; " >
              <p><strong>Serie del Fabricante:</strong>   {% if data.SERIE_FABRICANTE%}{{data.SERIE_FABRICANTE}}{% endif %}</p>
            </div> 
      </div> 
    </div>
    {% comment %} Fin Segundo Recuadro {% endcomment %}


    {% comment %} Tercer Recuadro {% endcomment %}
    <div class="row" style="margin-top: 0.5em; ">
      <p><strong>Asunto:</strong>                {{data.ASUNTO}}</p>
    </div>
    {% comment %} Fin Recuadro {% endcomment %}
    
    {% comment %} Cuarto Recuadro {% endcomment %}
    <div class="row" style="margin-top: 0.5em; border: thin solid black">
      <div class="row" >
        <div class="column" style="max-width: 40% ">
          <p><strong>Origen:</strong>         {{data.ORIGEN}}</p>
        </div>
        <div class="column" style="max-width: 20%;margin-left: 5em; ">
          <p><strong>Prioridad:</strong>       {{data.PRIORIDAD}}</p>
        </div>
        <div class="column" style="max-width: 40%;margin-left: 2em; ">
          <p><strong>Tipo de llamda:</strong>   {{data.TIPO_DE_LLAMADA}}</p>
        </div>
      </div>

      <div class="row" >
        <div class="column" style="max-width: 70%;margin-top: 0.5em ">
          <p><strong>Técnico:</strong>               {{data.TECNICO}}</p>
        </div>
        <div class="column" style="max-width: 50%;margin-left: 1em;margin-top: 0.5em ">
          <p><strong>Responsable:</strong>           {{data.RESPONSABLE}}</p>
        </div>
      </div>

      <div class="row" style="margin-top: 0.5em">
        <p><strong>Clase de Problema:</strong>     {{data.CLASE_PROBLEMA}}</p>
      </div>
    </div>
    {% comment %} Fin del cuarto Recuadro {% endcomment %}
    
    
    {% comment %} Quinto Recuadro {% endcomment %}
    <div class="row" style="margin-top: 1em; border: thin solid black">
      <p><strong>Comentarios:</strong><br/>         {{data.COMENTARIOS}}</p>
      {% if data.COMENTARIOS|length < 80   %}
          <br/>
          <br/>
          <br/>
          <br/>
      {% endif %}
    </div>
    {% comment %} Fin Quinto Recuadro {% endcomment %}
  
    {% comment %} SEXTO Recuadro {% endcomment %}
    {% if data.RESOLUCION %}
    <div class="row" style="margin-top: 1em; border: thin solid black">
      <p><strong>Resolución:</strong>            {{data.RESOLUCION}}</p>
    </div>
    {% else %}
    <div class="row" style="max-height: 500px; visibility: hidden;margin-top: 1em">
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
    </div>
    {% endif %}

    {% comment %} Fin SEXTO Recuadro {% endcomment %}
    
    
    {% comment %} Septimo Recuadro {% endcomment %}
    <div class="row" style="margin-top: 1em; ">
      <p style="text-align:center;margin-top: 0.3em;"><strong>ADVERTENCIA:</strong></p>
      <p  style="font-size:10px;"> Estimado Cliente <br>
          Por medio del presente documento le ponemos a su conocimiento las condiciones que rigen para el servicio de garantía o reparación de equipos y el retiro de los mismos en nuestro centro de servicio.
          <br>
          1. El periodo de vigencia de la garantía del equipo que se presente en nuestro centro de servicio se validará desde la fecha indicada en la factura de compra del producto.

          <br>
          2. Para retirar el equipo se deberá presentar este documento ( llamada de servicio ) junto con la identificación correspondiente (cédula de identidad).

          <br>
          3. Para los equipos en garantía de provincias, que se encuentren listos para su entrega, el Cliente deberá confirmar el medio de retiro en un lapso máximo de 7 días laborables, caso contrario y transcurrido dicho plazo, se lo enviará al domicilio
          que consta en la llamada de servicio con cargo del flete al cobro.

          <br>
          4. Los equipos ingresados para reparacón, luego de haberse proporcionado la cotización, se les concederá 8 días laborables para cancelar dicho valor y confirmar la citada proforma, caso contrario y transcurrido dicho plazo,
          se lo enviará al domicilio que consta en la llamada de servicio con cargo del flete al cobro.


          <br>
          5. En cualesquiera de los casos, en que el equipo fue recibido en nuestro departamento técnico se encuentre listo para entregar, a disposición del Cliente y no haya sido retirado en el período de 60 días calendario desde 
          la fecha de ingreso, Service 21 podrá disponer desechar el equipo, como a bien tuviere, incluso para poder sufragar los gastos ya generados sin opción a reclamo posterior alguno.
          <br>
          6. No se receptará ningún tipo de reclamo una vez retirado el equipo de nuestras instalaciones.
          <br>
          7. Todo proceso de cobertura de garantía se realiza conforme con las políticas del fabricante.
        </p>

        <p align="center" style="text-align:center;font-size:10px;"> 
          <br>
          <strong>
            ** SERVICE21 NO SE RESPONSABILIZA POR LA PERDIDA DE INFORMACIÓN EN DISCOS DUROS EN TODOS SUS ESTADOS, MEMORIAS INTERNAS O PEN DRIVERS, SISTEMAS OPERATIVOS O PROGRAMAS INSTALADOS. EL CLIENTE ES EL UNICO RESPONSABLE DE SALVAGUARDIAS SU INFORMACIÓN. **
          </strong>
          <br> <br>
          <strong>
           *El cliente al enviar su equipo por courier o al ingresarlo en nuestro centro de serivicio técnico, acepta las condiciones estipuladas en esta sección de Advertencias*
          </strong>
      </p>
    </div>
    {% comment %} Fin Septimo Recuadro {% endcomment %}

    {% comment %} Octavo Recuadro {% endcomment %}
    <div class="row" style="margin-top: 1em">
        <div class="column" style="max-width: 50% ">
          <p>________________________________</p>
          <p style="margin-top: 0.4em;font-size:10px;"><strong>Cliente</strong></p>
          <p style="margin-top: 0.4em;font-size:10px;"><strong>C.I.:</strong></p>
        </div>

        <div class="column" style="max-width: 50%; margin-left: 10em; ">
          <p>________________________________</p>
          <p style="text-align:center;margin-top: 0.4em;font-size:10px;"><strong>RECIBIDO/ENTREGADO</strong></p>
        </div>
      
    </div>
    {% comment %} Fin Octavo Recuadro {% endcomment %}



    {% comment %} Noveno Recuadro {% endcomment %}
      <div class="row" style="margin-top: 1em">
        

        <p style="font-size:12px;text-align:center;">LÍNEAS DE ATENCION AL CLIENTE PARA GARANTIAS O SERVICIO TECNICO:</p>
        <p style="font-size:12px;text-align:center;">GUAYAQUIL (04) 3732121 EXT. 4343 - 4347 WHATSAPP GYE: 0958891912 -          QUITO (02) 3732121 EXT. 2192  <br> WHATSAPP UIO: 0979685359</p>
        <p style="font-size:12px;color:red;text-align:center;" >CONSULTE EL STATUS DE SU EQUIPO EN <br>  www.service-21.net</p>
    </div>
    {% comment %} Fin Noveno Recuadro {% endcomment %}

    <div class="footer" style=" border-top:1px solid black">
      

      <div class="row" style="margin-top: 1em;">
        <div class="column" style="max-width: 50% ">
          <p><strong>Página 1</strong> </p>
        </div>

        <div class="column" style="max-width: 50%; margin-left: 5em; ">
          <p><strong>Fecha/Hora Impresión:</strong>  {{Prindate}}</p>
        </div>

        <div class="column" style="max-width: 50%; margin-left: 5em; ">
          <p><strong>Autor:</strong> {{data.RESPONSABLE}}</p>
        </div>
      
    </div>

    </div>
  </body>
</html>






@import url('https://fonts.googleapis.com/css?family=Arial');
/* @font-face {
    font-family: Arial;
    src: url(Arial.ttf);
  } */

  
  @page {
    size: A4;
    font-family:  Arial;
    margin: 0.4cm;

   /*  @bottom-left-corner{        content: "Página " counter(page)     } */

  }

  .column {
    float: left;
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  

  .partthree {
    display: flex;
    margin: 0 90px;
    color: aliceblue;
  }
  .partthree div {
    display: inline-block;
    flex-grow: 1;/* flex:1; would make them equal width */
    font-family:  Arial;
    font-size: 23px;
    /* extra ?*/
    margin: 0 0.5em;
    border:solid;
    text-align:center;
  }
  
  p {
    margin:0;
  }


  .footer {
    position: fixed;
    left: 0;
    bottom: 0;
    height: 5%;
    width: 100%;
    text-align: center;
  }

**Comment by liZe** [comment]
> Correct, the same HTML file installed on the server generates the document on the top and if someone accesses the portal as a client the pdf of the bottom is generated

Sorry, but I don’t understand :/. Could you please exactly explain, for each document:
- where WeasyPrint is installed
- how WeasyPrint is called (by a web application, by the command line…)
- how the HTML is given to WeasyPrint (using an URL, passed to the library as a string…)

It would also be helpful to have the two different PDF files so that we can compare them.

(By the way, there’s obviously something wrong with the fonts, as the first document doesn’t use Arial. Maybe the problem just comes from the different fonts.)

You can often get interesting information by activating [logging](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html?highlight=logging#logging), that’s a good first step to understand what’s going on.

**Comment by rlindao-siglo21** [comment]
1- ) weasyprint is installed in my development that is placed on the server
2- ) is called by web application, the web page is published
3-) by string method

[46814_Server.pdf](https://github.com/Kozea/WeasyPrint/files/9708307/46814_Server.pdf)
[46814_Client.pdf](https://github.com/Kozea/WeasyPrint/files/9708308/46814_Client.pdf)

**Comment by liZe** [comment]
The difference is in the fonts.

`@import url('https://fonts.googleapis.com/css?family=Arial')` doesn’t work because Google Fonts doesn’t provide Arial. Use another font that’s provided by Google Fonts and everything will be OK.

**Comment by rlindao-siglo21** [comment]
I already changed the letter but it's still the same
@import url('https://fonts.googleapis.com/css?family=Lato');

**Comment by liZe** [comment]
The URL is wrong. You should use `@import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');`, as provided by the Google Fonts website.

**Comment by rlindao-siglo21** [comment]
I already made the change but it still does not work


`
@import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');

/* latin-ext */
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/lato/v23/S6uyw4BMUTPHjxAwXjeu.woff2) format('woff2');
}
  
  @page {
    size: A4;
    font-family:  'Lato';
    margin: 0.4cm;

   /*  @bottom-left-corner{        content: "Página " counter(page)     } */

  }

  .column {
    float: left;
  }
  
  /* Clear floats after the columns */
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  

  .partthree {
    display: flex;
    margin: 0 90px;
    color: aliceblue;
  }
  .partthree div {
    display: inline-block;
    flex-grow: 1;/* flex:1; would make them equal width */
    font-family:  'Lato';
    font-size: 23px;

    margin: 0 0.5em;
    border:solid;
    text-align:center;
  }
  
  p {
    margin:0;
  }


  .footer {
    position: fixed;
    left: 0;
    bottom: 0;
    height: 5%;
    width: 100%;
    text-align: center;
  }
`

**Comment by liZe** [comment]
> I already made the change but it still does not work

Could you please at least explain what changed or provide the PDF files that are now generated? If we don’t know what "does not work", we can’t help you.

You don’t need the `@font-face` rule, the `@import` rule is enough.

> You can often get interesting information by activating [logging](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html?highlight=logging#logging), that’s a good first step to understand what’s going on.

As explained above, please read the logs, it’s a good idea to find what’s wrong.

**Comment by rlindao-siglo21** [comment]
[46814_Server.pdf](https://github.com/Kozea/WeasyPrint/files/9710224/46814_Server.pdf)
[46814_Client.pdf](https://github.com/Kozea/WeasyPrint/files/9710225/46814_Client.pdf)

ok I deleted the `@font-face` rule.

I use the `loggin` but it didn't show me any error I don't know if I'm implementing it correctly this is my code.
`
import logging
logger = logging.getLogger('weasyprint')
if not logger.handlers:
        logger.addHandler(logging.NullHandler())
        logger.addHandler(logging.FileHandler('media/LlamadasServicio/weasyprint.log'))
            

from io import BytesIO
import os
			
# insert the GTK3 Runtime folder at the beginning
GTK_FOLDER = r'C:\msys64\mingw64\bin'
os.environ['PATH'] = GTK_FOLDER + os.pathsep + os.environ.get('PATH', '')

from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from django.contrib.staticfiles import finders
from weasyprint import HTML ,CSS
from django.template.loader import render_to_string
from AppSiglo21.settings import DIRECTORIO_PDF_SOLICITUD_NC
from weasyprint.text.fonts import FontConfiguration  # for weasyprint 53
# from weasyprint.fonts import FontConfiguration  # for weasyprint 52



def render_pdf_view(request,template_path,file_name,context,mostrar,ruta= 'media/LlamadasServicio/LlamadasServicio.pdf'):    
        #template_path = 'app_venta/solicitud.html'
        #context = {'myvar': 'this is your template context'}
        # Create a Django response object, and specify content_type as pdf
        try:
        
                
                response = HttpResponse(content_type='application/pdf')

                #response['Content-Disposition'] = 'inline; filename="' + file_name + '"' #% file_name 
                if mostrar == 'INLINE':
                        response['Content-Disposition'] = 'inline; filename="%s"' % file_name        
                else:
                        response['Content-Disposition'] = 'attachment; filename="%s"' % file_name
                # find the template and render it.
                #template = get_template(template_path)
                #html = template.render(context)
                #print('I am here...' + file_name)
                # create a pdf
                
                html = render_to_string(template_path, context)
                font_config = FontConfiguration()
                print(settings.STATICFILES_DIRS[0])
                print(settings.STATIC_ROOT)
                csp = str(settings.STATICFILES_DIRS[0])
                
               
                css_file = os.path.join(csp, "dist" , "css", "LlamadaServicio.css" )
                print(css_file)
                css = CSS(css_file)
                css_file_local = os.path.join(settings.STATIC_ROOT + "\LlamadaServicio.css")
                print("ruta l" , css_file_local)
                css_local =  CSS(css_file_local)
                
                if css:
                        print("Entro" , css)
                        pdf = HTML(string=html, base_url=request.build_absolute_uri("/")).write_pdf(ruta, font_config=font_config, stylesheets=[css_local], presentational_hints=True )
                        HTML(string=html, base_url=request.build_absolute_uri("/")).write_pdf(response, font_config=font_config, stylesheets=[css], presentational_hints=True,  )
                        logger = logging.getLogger('weasyprint')
                        logger.addHandler(logging.FileHandler('media/LlamadasServicio/weasyprint_CSS.log'))
                else:
                        pdf = HTML(string=html, base_url=request.build_absolute_uri("/")).write_pdf(ruta, font_config=font_config, stylesheets=[css]  )
                        HTML(string=html, base_url=request.build_absolute_uri("/")).write_pdf(response, font_config=font_config)
                        logger = logging.getLogger('weasyprint')
                        logger.addHandler(logging.FileHandler('media/LlamadasServicio/weasyprint_sinCSS.log'))
        
                #HTML(string=html).write_pdf(response, font_config=font_config, stylesheets=[css])
                
                
                #pisa_status = pisa.CreatePDF(html, dest=response, link_callback=link_callback)


                # if error then show some funy view
                #if pisa_status.err:
                #       return None
                        #return HttpResponse('We had some errors <pre>' + html + '</pre>')
                
        except Exception as e:
                if hasattr(e, 'message'):
                        response = 'Error en GeneraPdfSolicitud: ' + e.message
                        print(response)
                else:
                        response ='Error en GeneraPdfSolicitud: ' + str(e)
                        print(response)
                        
        return response
                        
        `

**Comment by liZe** [comment]
As you can see, your PDF files don’t use the Lato font.

Read carefully the documentation, try to understand how the logging module works, and you’ll get interesting messages.

Your problem probably comes from the `font_config` attribute that has to be given to the `CSS` class, [as explained in the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#instantiating-html-and-css-objects) too.
