### ISSUE TITLE
Background-color and (font)color not working together with Bootstrap 3.0

### ISSUE THREAD

**Issue by snirp** [Kozea/WeasyPrint#173]
When using custom CSS together with Bootstrap, the "background-color" is rendered as white and the "color" as black, instead of the custom CSS settings. This goes for both block and inline elements.

Use the following example to reproduce:

```
<!DOCTYPE html>
<html lang='nl'>
<head>
  <meta charset=utf-8>
  <title>weasytest</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <style>
    .bordered { border: 1px solid black;}
    .redbg {
      background-color: red;
      color: #fff;
    }
  </style>
</head>
<body>
  <div class="bordered redbg">red block element</div>
  <span class="bordered redbg">red inline element</span>
</body>
</html>
```

A browser would show a block and an inline element with white letters on a red background. The PDF shows black on white text. Observe that the borders are respected.

When the bootstrap CSS is removed, everything functions as expected.

**Comment by kinkoazc** [comment]
As an update on this issue, in Bootstrap 4's case, it has been modified to something on the lines of:
@media print{
  * {
    text-shadow: none !important;
    box-shadow: none !important;
  }
}
