### ISSUE TITLE
OSError: cannot load library 'gobject-2.0-0': error 0x7e.

### ISSUE THREAD

**Issue by endo-aki22** [Kozea/WeasyPrint#1730]
I can't install Weasyprint v56.1 on Windows 11.
I installed the gtk4-runtime on the default directory.
![2022-09-28_23-52](https://user-images.githubusercontent.com/61251512/192950131-ccc6dbdb-4f06-4d3e-9ea3-b46f9e174a7e.png)
![2022-09-28_23-55](https://user-images.githubusercontent.com/61251512/192950465-a804b584-1d7d-49b6-9e3b-3e217fc7d434.png)

**Comment by liZe** [comment]
Hi!

Could you try to [set the `WEASYPRINT_DLL_DIRECTORIES` environment variable](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting)?

**Comment by liZe** [comment]
@endo-aki22 Does WeasyPrint work on your system now?

**Comment by endo-aki22** [comment]
Sorry. I didn't try it.

**Comment by endo-aki22** [comment]
let me try it.

**Comment by liZe** [comment]
Feel free to add a comment if we can help.
