### ISSUE TITLE
Cannot load default config file: No such file

### ISSUE THREAD

**Issue by abdelmalek0** [Kozea/WeasyPrint#1734]
```
>python -m weasyprint --info
Fontconfig error: Cannot load default config file: No such file: (null)
C:\SmartPrints\PDFS\sdc_env\lib\site-packages\weasyprint\text\fonts.py:60: UserWarning: FontConfig cannot load default config file. Expect ugly output.
  warn('FontConfig cannot load default config file. Expect ugly output.')
```

When I use Weasyprint version 52.5 No warning appears but when I use versions older than 55.0 I get this warning ( My code needs weasyprint >=55.0 )

System: Windows 10 64 bit

**Comment by liZe** [comment]
Hi!

How did you install the external libraries (including FontConfig)? If you used [the GTK+ installer for Windows](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer), you shouldn’t have this problem as [the default config files are included](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/tree/master/gtk-nsis-pack/etc/fonts).

**Comment by liZe** [comment]
@abdelmalek0 Does WeasyPrint work on your system now?

**Comment by abdelmalek0** [comment]
I just downgraded the weasyprint to 52.5

**Comment by liZe** [comment]
> I just downgraded the weasyprint to 52.5

OK.

If anybody has the same problem with WeasyPrint 53+ but not with 52.5, please add a comment here, we’ll try to find the source of the problem. But for now, I don’t know what could be wrong other than a problem in GTK’s installation or another version of Fontconfig installed elsewhere.
