### ISSUE TITLE
Possibility to keep header of table on the same page that first line

### ISSUE THREAD

**Issue by AMontagu** [Kozea/WeasyPrint#1735]
Hello !

Is it possible in Weasyprint or in css to keep the header (first tr) in the same page the first line (second tr) without use `page-break-inside: avoid;` on the all table.

I explain the need: 
A big table that fix in more than 1 page but firts line just at the end of a page. The render is ugly:

![Capture d’écran de 2022-10-07 17-27-20](https://user-images.githubusercontent.com/11883225/194591239-eb9aeb51-3d4a-474e-b62b-c98717602f7b.png)

We already put a custom fix that said if the table is less than 6 tr we set the page-break-inside: avoid. But we also want it for bigger table.

**Comment by grewn0uille** [comment]
Hello!

How does the HTML of the table look like?

If it’s structured like this, it shouldn’t break between the header and the first line.
```html
<table>
  <thead>
    <tr>
      <td>Intervenants</td> <td>Signatures</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Responsable</td><td></td>
    </tr>
    <tr>
      <td>Responsable</td><td></td>
    </tr>
    <tr>
      <td>Responsable</td><td></td>
    </tr>
  </tbody>
</table>
```

Now we support `:has()` selector, and so it should be easier to avoid page breaks on small tables.
Here is an example avoiding page breaks on tables with less than 4 rows.
```css
table:not(:has(tr:nth-of-type(4))) {
  break-inside: avoid;
}
```

**Comment by AMontagu** [comment]
Working well.
Seem like 10% of our 180 table was wrongly written. Didn't see it when looking at it.

Thank you :)
