### ISSUE TITLE
Crash in SVG processing caused by currentColor Keyword in svg tag

### ISSUE THREAD

**Issue by vgoehler** [Kozea/WeasyPrint#1740]
I had a crash with the following end of the traceback:

```bash 
 File ".virtualenvs/pythonProject/lib/python3.8/site-packages/weasyprint/svg/__init__.py", line 608, in fill_stroke
    red, green, blue, alpha = color(fill_color)
ValueError: too many values to unpack (expected 4)
```
So `fill_stroke` is trying to set the fill_color in line 608 (same for setting of stroke_color in line 619) but gets a string instead of the 4 tupple.

The problem is obviously in the `color`  function of `utils.py`
```python
def color(string):
    """Safely parse a color string and return a RGBA tuple."""
    return parse_color(string or '') or (0, 0, 0, 1)
```
It handles a 4-tupple RGBA return of `tinycss2.color3.parse_color`  but does not handle the string *currentColor* return of `parse_color`.
The docstring of parse_color states following return states:
```python
"""
  :returns:
        * :obj:`None` if the input is not a valid color value.
          (No exception is raised.)
        * The string ``'currentColor'`` for the ``currentColor`` keyword
        * Or a :class:`RGBA` object for every other values
          (including keywords, HSL and HSLA.)
          The alpha channel is clipped to [0, 1]
          but red, green, or blue can be out of range
          (eg. ``rgb(-10%, 120%, 0%)`` is represented as
          ``(-0.1, 1.2, 0, 1)``.)
"""
```

Line 149 in `svg\__init__.py`s `__iter__` Method of the `Node` Class has a replace functionality for *currentColor*, but the `SVG` Class is lacking this. I prepared a demo. `EXAMPLE` crashes and `EXAMPLE2` works fine, because of *currentColor* in SVG tag vs. in one of the childs.

```python
import weasyprint
# Source of Example https://www.washingtonpost.com/technology/2022/09/10/fall-prevention-robot/
# this will crash
EXAMPLE = """
<svg width="30" viewBox="0 0 23 22" version="1.1" xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink" stroke="currentColor" stroke-width="1.5">
    <g stroke-width="1.5" fill="none">
        <circle cx="9.20757329" cy="8.99160695" r="8.50646589"></circle>
        <path d="M14.8522097,14.6362434 L20.7140392,20.4980728" id="Line-4"></path>
    </g>
</svg> 
"""
# this will work
EXAMPLE2 = """
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 26 26">
    <circle fill="red" cx="13" cy="13" r="13"></circle> 
    <path d="M9.9 9.9l6.5 6.5M16.4 9.9l-6.5 6.5" stroke="currentColor"></path>
</svg>
"""


def main():
    weasyprint.HTML(string=EXAMPLE).write_pdf('this_will_crash.pdf')


if __name__ == '__main__':
    main()
```

For a quick fix `color` could set the string *currentColor* value to a default return value (like invalid values do). Of course it would be better to get the real currentColor but I didn't investigate that deep in the class.

**Comment by vgoehler** [comment]
I experimented some what on [mozillas Reference on SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color) with a Vivaldi (chrome) browser, as the CSS3 Refence is not very narrow on what should happen.
The Browser did not give the color of a higher element to the svg, when it was nested in it. But a color attribute in the svg tag got used up by all currentColor positions that where nested in it. A currentColor value in the svg tag (for instance at a fill attribute) gets also recognized further down the line. Additionally a color further down in the nest overrides as it should.

**Comment by liZe** [comment]
Hi!

Thanks for the bug report.

`currentColor` is known to be unsupported for now (#1497), but WeasyPrint shouldn’t crash. We can at least fix the crash in this issue and talk about what should be done to support `currentColor` in the other issue.
