### ISSUE TITLE
sphinx-generated manpage contains too much information

### ISSUE THREAD

**Issue by dkg** [Kozea/WeasyPrint#1741]
Over in https://bugs.debian.org/1014936 i noted that the `weasyprint.1` manpage contains too much information.

 > The manpage in section 1 should make it clear how to use the command
 > line utility.
 > 
 > the current manpage contains:
 > 
 >  - retreival and build instructions (including packaging for different
 >    distros)
 > 
 >  - descriptions of how to use the python module
 > 
 >  - explanations of CSS
 > 
 >  - full changelog
 > 
 >  - instructions on how to contribute
 > 
 > the python API could be included in a different manpage in section 3.
 > the other stuff should maybe just live in /usr/share/doc/weasyprint/

I think the `man_pages` section in `conf.py` should be a bit more selective, if possible.  This might require some reorganization of the documentation, or maybe some fancier sphinx trickery than i know how to do.

Thanks very much for weasyprint!

**Comment by liZe** [comment]
Hi!

Thanks for this bug report.

I didn’t know that anyone was generating the man pages with Sphinx … and you’re right, the result is definitely ugly.

Here’s what I’ve managed to get, would it be OK for you?

[weasyprint.zip](https://github.com/Kozea/WeasyPrint/files/9793148/weasyprint.zip)

**Comment by kitterma** [comment]
I think that looks great.  It's a substantial step forward from where we are now.

**Comment by liZe** [comment]
> I think that looks great. It's a substantial step forward from where we are now.

Then we’ll start with that, it’s possible without changing a lot of things.
