### ISSUE TITLE
Nested ordered lists cause incorrectly affect the parent ordered list's numbering

### ISSUE THREAD

**Issue by MH-ZShearer** [Kozea/WeasyPrint#1743]
```yaml
WeasyPrint Version: 56.1
OS: Windows 10 21H2 (19044.2130)
Python: 3.10.5
```

With the following HTML, WeasyPrint doesn't generate the expected output

```html
<ol type="a">
    <li>(a.) Item 1</li>
    <li>(b.) Item 2</li>
    <ol type="1">
      <li>(1.) Item 2.1</li>
      <li>(2.) Item 2.2</li>
      <li>(3.) Item 2.3</li>
    </ol>
    <li>(c.) Item 3</li>
    <li>(d.) Item 4</li>
</ol>
```

Browser output:
![image](https://user-images.githubusercontent.com/84808922/195914898-b5f2eecb-c2a9-4b38-8f7c-135d53dd55a2.png)

WeasyPrint output:
![image](https://user-images.githubusercontent.com/84808922/195914955-29120ab4-698b-4bf7-906f-63d6a6b4c6c2.png)

This also happens to showcase that nested ordered lists aren't handled correctly either. Changing `type="a"` to `type="1"` (default), creates the same output.

**Comment by MH-ZShearer** [comment]
I found out that passing `--presentation-hints` fixes the issue of ordered lists only using numbers. However, `Item 3` and `Item 4` end up being `d.` and `e.` respectively.

![image](https://user-images.githubusercontent.com/84808922/195926769-142971f4-434e-47b4-b4cb-db19c8b039f3.png)

**Comment by liZe** [comment]
Hi!

`ol` and `ul` elements only allow `li` elements as children, embedding `ol` in `ol` is not valid HTML.

You can use this instead:
```html
<ol type="a">
    <li>(a.) Item 1</li>
    <li>(b.) Item 2
      <ol type="1">
        <li>(1.) Item 2.1</li>
        <li>(2.) Item 2.2</li>
        <li>(3.) Item 2.3</li>
      </ol>
    </li>
    <li>(c.) Item 3</li>
    <li>(d.) Item 4</li>
</ol>
```

**Comment by MH-ZShearer** [comment]
Huh, I swore that is what I tried first. I suppose it was before I found out about `--presentational-hints` and it was an attempt to fix my ignorance.

Is there a reason that presentational hints aren't enabled by default? Reading the documentation left me with more questions than what it actually answered. Are there downsides to enabling it?

**Comment by liZe** [comment]
> Huh, I swore that is what I tried first. I suppose it was before I found out about `--presentational-hints` and it was an attempt to fix my ignorance.

😀️

> Is there a reason that presentational hints aren't enabled by default? Reading the documentation left me with more questions than what it actually answered. Are there downsides to enabling it?

The main reason is that it’s slow.

As most of these features are more or less deprecated in HTML, users generally prefer to use the corresponding CSS properties. For lists, for example, a lot of things can be handled using the [CSS Lists and Counters module’s properties](https://www.w3.org/TR/css-lists-3/#text-markers).

**Comment by MH-ZShearer** [comment]
That makes sense. Unfortunately, our use case is converting markdown files to PDFs with Pandoc and WeasyPrint. We had a specification in our contract that required a single ordered list to contain letters with a nested ordered list inside so using CSS to target such a specific thing (that was generic to all of our documentation) didn't feel right. 

I expected that `--presentation-hints` was more the "true" representation of the webpage, however, I can definitely understand the performance impact of having it as the default.

Thank you for the assistance and information!
