### ISSUE TITLE
Bad rendering of HTML to PDF - what is the issue?

### ISSUE THREAD

**Issue by clstaudt** [Kozea/WeasyPrint#1744]
Looking for help with the following question:
https://stackoverflow.com/questions/74087611/bad-rendering-of-html-to-pdf-with-weasyprint

**Comment by liZe** [comment]
Hi!

There’s an obvious problem in your rendering: the numbers are missing. It sometimes happen when there’s something strange/wrong in Fontconfig’s configuration, and Fontconfig uses an emoji-only font to render numbers.

If you now how Fontconfig works, you can dig into the configuration and fix what’s wrong. If you don’t, you can use `font-family` rules exactly defining the font you want to use, or even use `@font-face` rules, to force the right font to be used for numbers.

**Comment by clstaudt** [comment]
@liZe  attached is one of the PDFs generated by weasyprint
[2022-10-17-01-central.pdf](https://github.com/Kozea/WeasyPrint/files/9802148/2022-10-17-01-central.pdf)

I am on macOS 12.6 with `weasyprint` 56.1.

I should mention that converting this HTML to PDF worked flawlessly with `[pdfkit](https://github.com/JazzCore/python-pdfkit)`. However, I would prefer to use `weasyprint` because it is a pure Python module without binary dependencies.

**Comment by liZe** [comment]
> @liZe attached is one of the PDFs generated by weasyprint
> [2022-10-17-01-central.pdf](https://github.com/Kozea/WeasyPrint/files/9802148/2022-10-17-01-central.pdf)

The problem is that Apple-Color-Emoji is used for numbers.

Did you set `font-family: Helvetica` on `html` or `body` in your CSS file?

**Comment by clstaudt** [comment]
[timesheet-anvil.zip](https://github.com/Kozea/WeasyPrint/files/9809323/timesheet-anvil.zip)

@liZe  please find attached the template used to generate the document.

In `web/modern-normalize.css` I find the following style definition:

```css

body {
	font-family:
		system-ui,
		-apple-system, /* Firefox supports this but not yet `system-ui` */
		'Segoe UI',
		Roboto,
		Helvetica,
		Arial,
		sans-serif,
		'Apple Color Emoji',
		'Segoe UI Emoji';
}
```

There is both Helvetica and Apple Color Emoji...   
Removing the last two fonts leads to the numbers being rendered. 

[2022-10-18-01-central.pdf](https://github.com/Kozea/WeasyPrint/files/9809366/2022-10-18-01-central.pdf)

I am not entirely happy with this rendering, I would like to get the previous font back. Any ideas?

**Comment by liZe** [comment]
> I am not entirely happy with this rendering, I would like to get the previous font back. Any ideas?

You probably removed the trailing `;` with the two last fonts, breaking your whole `font-family` rule 😁️. Using only `font-family: Helvetica;` will work.

If you want to keep your old rule for the web rendering, you can use:
```css
@media print {
  body {
    font-family: Helvetica;
  }
}

**Comment by clstaudt** [comment]
Good catch. With a bit of font size tweaking I am now getting an acceptable result. Glad that I can use `weasyprint` as a replacement of `pdfkit` now, thanks @liZe .

[2022-10-18-01-central.pdf](https://github.com/Kozea/WeasyPrint/files/9809682/2022-10-18-01-central.pdf)
