### ISSUE TITLE
❯ symbol hides all subsequent text on same line

### ISSUE THREAD

**Issue by LukasKlement** [Kozea/WeasyPrint#1748]
When you use this symbol: ❯, the subsequent text on the same line is hidden. This does not happen with all symbols (e.g. › does not cause this issue).

For example, the following:
```
<span class="primary-language">❯ Daily Deli Sandwich Bar &amp; Panini</span>
```

Actual: https://share.getcloudapp.com/9Zug9p9m
Expected: https://share.getcloudapp.com/Jru8EBEJ

WeasyPrint v57.0

**Comment by liZe** [comment]
Thanks a lot for the bug report. The problem should now be fixed (and a test has been added).
