### ISSUE TITLE
Strange page breaking with float

### ISSUE THREAD

**Issue by castedo** [Kozea/WeasyPrint#1751]
With weasyprint 56 and 57 the following simplified HTML:
[test.html.txt](https://github.com/Kozea/WeasyPrint/files/9843215/test.html.txt)
results in a strange page break (between the "4" at end of page 1 and its associated text on page 2):
[out.pdf](https://github.com/Kozea/WeasyPrint/files/9843216/out.pdf)
which I do not see happening with Chrome print preview (and never on a screen).

I don't understand CSS well enough to know if this is a bug or not, but it looks fishy. I suspect this simple case is identifying some missing logic.

In the real more complicated HTML I've hit, I'm able to work around this by adding a `break-inside: avoid` on the div.

Hope that helps.

**Comment by liZe** [comment]
Hi!

I think that there’s nothing preventing a page break between the float and the text, that’s why WeasyPrint breaks here. From [CSS Fragmentation](https://drafts.csswg.org/css-break/#possible-breaks), breaks are allowed:

> When the block flow direction of the siblings' containing block is parallel to that of the fragmentation context: […] **a float and an immediately-adjacent in-flow or floated box** […].

Using `break-inside: avoid` is normal if you want to avoid page breaks.

(It’s often a good idea to compare what other browsers do, for everything … but not for page breaks where they usually are really bad 😁️.)
