### ISSUE TITLE
Version 57 breaks display of glyphs in fonts; works in <57

### ISSUE THREAD

**Issue by leducvin** [Kozea/WeasyPrint#1757]
`test.html`:

```
<!DOCTYPE html>
<html lang="fr-CA">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="test.css">
  </head>
  <body>
    <section>
    <p>An arrow and a heart →  ♥</p>
    </section>
  </body>
</html>
```

`test.css`:

```
html {
    font-family: Noto;
}
```

Note: am using the Noto font which definitely includes these glyphs: →  and ♥.

`cat test.html | weasyprint -s test.css - test.pdf`

WeasyPrint 56.1:
![image](https://user-images.githubusercontent.com/22982038/198719537-c4675ea4-8ea7-40dc-80e4-08f170d54d25.png)

WeasyPrint 57:
![image](https://user-images.githubusercontent.com/22982038/198719633-2841abe6-bfda-4596-8d20-b2b8d69485aa.png)

**Comment by liZe** [comment]
Hi!

Thanks for the report.

Could you please try the current `master` version? It’s probably a duplicate of #1748.

**Comment by leducvin** [comment]
Hi!

Yes, I can confirm it works with master (commit 3c6ac5ec). Sorry if this was a duplicate... I'll close it now.
