### ISSUE TITLE
Weasyprint output differs between Operating systems

### ISSUE THREAD

**Issue by jamie-96** [Kozea/WeasyPrint#1762]
I am printing the same html and css files on both MacOS locally and Alpine 3.16 in a docker container and the output differs between the 2. On Mac everything is set up correctly, it comes out properly formatted and in the correct order, but in the docker container it comes out with text overlaying other text (duplicated, as if one page is overlayed on itself slightly to the right), extra blank pages and sections in the wrong order.

**Package versions:**
**Alpine 3.16:**
- gcc-11.2.1
- musl-dev-1.2.3-r1
- Python 3.9.15
- pango-1.50.7
- zlib-dev-1.2.12
- jpeg-dev-9d-r1
- openjpeg-dev-2.5.0
- g++-11.2.1
- libffi-dev-3.4.2

**MacOS Monterey**
- Python 3.9.13
- pango-1.50.11

**Comment by liZe** [comment]
Hi @jamie-96,

Is your problem now fixed?
