### ISSUE TITLE
List over page break

### ISSUE THREAD

**Issue by craigbass76** [Kozea/WeasyPrint#1763]
I had a problem where <li> would get strange formatting (margins, position) if they went over a page break. I used to fix it by editing boxes.py and changing the == to a != on a line (somewhere in the 350 vicinity) that read:
```
if (start or end) and old_style == self.style:
```
I don't see such a line any more. I'm on v54.1

**Comment by liZe** [comment]
Hi!

Could you please try the latest version of WeasyPrint?

**Comment by liZe** [comment]
Feel free to add a comment if the bug is not fixed with version 57.
