### ISSUE TITLE
Attachment added using rel=attachment in HTML breaks printing in Adobe Acrobat Reader

### ISSUE THREAD

**Issue by Salamek** [Kozea/WeasyPrint#1764]
Hi, when i add attachment using this code:
```python
        from weasyprint import HTML
        html = '<a href="{0}" title="{1}" rel=attachment>{1}</a>'.format(
            'https://d39-a.sdn.cz/d_39/c_img_gS_r/XI1CD/profimedia-0736827206.jpeg', # Type of attachment does not matter, just use random URL to jpg from web when this link is not working anymore
            'attachment.jpeg'
        )

        pdf = HTML(string=html).render()

        handle = open('test.pdf', 'wb')
        pdf.write_pdf(target=handle)
        handle.close()
```
And when trying to print a resulting PDF i get "The document could not be printed", also https://www.pdf-online.com/osa/validate.aspx reports:

```
Validating file "test.pdf" for conformance level pdf1.7
The "endobj" keyword is missing.
The key AS is required but missing.
The document does not conform to the requested standard.
The file format (header, trailer, objects, xref, streams) is corrupted.
The document contains annotations or form fields with ambigous or without appropriate appearances.
The document does not conform to the PDF 1.7 standard.

Done.
```
Also attachment added by this method is not listed in PDF attachments, when i looked into src it looks like "HTML"(rel=attachment) attachments are implemented differently then adding attachments in `write_pdf` (i always thought that "HTML" attachment is just link to normal attachment)?

When i use this code to attach a file without using HTML rel=attachment printing in Adobe Acrobat Reader works file (but i can't link to it from content):
```python
        from weasyprint import HTML, Attachment
        html='<h1>TEST No HTML</h1>'

        pdf = HTML(string=html).render()

        attachments = [
            Attachment(
                filename='profimedia-0736827206.jpeg',
                description='Test image'
            )
        ]

        handle = open('test_att.pdf', 'wb')
        pdf.write_pdf(target=handle, attachments=attachments)
        handle.close()
```

Also https://www.pdf-online.com/osa/validate.aspx validation is ok...

**Comment by Salamek** [comment]
Hi, that was fast!
Printing now works in Adobe Acrobat Reader and file is listed in attachments in Adobe Acrobat Reader, also works in other PDF readers as ~expected with minor weirdness around and one Adobe Acrobat Reader minor bug:

### Ocular
File is not listed in attachments, but it is listed in annotations probably Ocular handles this type of attachments differently? [no biggie, works ok]
![Screenshot_2022-11-12_16-02-35](https://user-images.githubusercontent.com/1226241/201480815-64c4c2dc-786d-4187-80ac-56968e29f40a.png)
![Screenshot_2022-11-12_16-03-42](https://user-images.githubusercontent.com/1226241/201480818-39900e2f-3e69-4e1c-8f17-6ac84c9e1731.png)

### Xreader
After clicking on the link and viewing the attachment in native app it tries to add ?note? [no biggie, works ok, likely bug in xreader?]

![Screenshot_2022-11-12_16-01-09](https://user-images.githubusercontent.com/1226241/201480834-b94748f0-8821-4f36-b033-f287c3cf1bba.png)

### Chromium/Chrome PDF reader
Ignores the link click [no biggie, probably not implemented]

### Gnome Evince
Crashes after clicking on link :smile: [likely bug in Evince]

### Adobe Acrobat Reader
Shows weird rectangle quite far bellow after first click on the link (my guess is to highlight active/clicked element) but it is incorrectly positioned [most likely some related object is not positioned correctly in PDF?]

![Screenshot_2022-11-12_15-52-21](https://user-images.githubusercontent.com/1226241/201480855-e235d65d-5e31-417f-bf03-5ebc49a3a535.png)


Overall it looks like fixed, maybe that Adobe Acrobat rectangle thing could be fixed but i'm not really crazy about it :)

**Comment by liZe** [comment]
> Hi, that was fast!

🚀️

Evince and Okular are both based on Poppler, so they should behave quite similarly. I only have Evince installed here, and it works fine (no crash!), even if I get the same note open as in XReader. As in Okular, it’s listed in annotations, not attachments.

The attachment doesn’t work with Chrome, but it works surprisingly well with Firefox (you can download the image by double-clicking the link).

I suspect that the Acrobat’s rectangle is a variant of the note seen with XReader and Evince. The way attachments are handled in WeasyPrint (with annotations when `a rel=attachment` is used) is probably wrong. Do you have an example of a PDF with a link to an attachment that doesn’t display the note?

**Comment by Salamek** [comment]
I was trying to create a link to attachment in PDF in "Adobe PDF Crap whoever Pro" and i was unable to do it... so IDK how correct implementation looks :-) I guess this has to do for now...

**Comment by umaplehurst** [comment]
I found that the Adobe Acrobat Reader strange rectangle issue described above is somehow related to `AP` and `AS` in 419c771331b3f531069055f03b81d71470b6a77b. If I remove them entirely so there is just the `Rect` the link is then in the right place (however, there will then be a rendered pin icon -- probably not what most users will want). I guess that the `AP`'s `BBox` needs to be somehow differently-transformed to something else from `Rect` to fix the problem.

**Comment by liZe** [comment]
If someone wants to read the PDF specification and find a way to display attachments "correctly", please open a new issue or even a pull request! 😄
