### ISSUE TITLE
Object tag doesn't work for html pages

### ISSUE THREAD

**Issue by tommy932** [Kozea/WeasyPrint#1769]
If you try to embed an html page into another with the tag object, it doesn't work. 

Example 
`<object data="file:///app/test.html"></object>`

**Comment by onakitoki** [comment]
@liZe , if you guys aint gonna implement it, do you know another library that does support this?.
Regards!

**Comment by liZe** [comment]
@onakitoki To handle HTML in HTML, we don’t need another library, "just" code in WeasyPrint to take care of this.

(Let’s please continue this conversation in #1010 if needed!)
