### ISSUE TITLE
[Feat] preserve svg group names

### ISSUE THREAD

**Issue by hiaselhans** [Kozea/WeasyPrint#1770]
I have a couple of svg's and svg's in html's that i would like to convert to pdf.
After the conversion the svg is flattened, and the group information is not there anymore.

I am happy to send a PR if you just give me a thumbs up and some guiding:

I checked svg/shapes and it looks like shapes are written to the stream here:
https://github.com/Kozea/WeasyPrint/blob/419c771331b3f531069055f03b81d71470b6a77b/weasyprint/svg/__init__.py#L367

with an existing add_group() function on the pdf stream:
https://github.com/Kozea/WeasyPrint/blob/419c771331b3f531069055f03b81d71470b6a77b/weasyprint/pdf/stream.py#L333

am i looking in the right direction to simpy add a "shape" <g> which adds a group and resets the stream after drawing its children?

**Comment by liZe** [comment]
Hi!

I’m not sure about what you’re trying to achieve. Do you want to add something in the PDF file when there’s a `g` tag in an SVG?

**Comment by hiaselhans** [comment]
Hi!

yes, i want to add optional content groups for svg groups.
i saw #1238 as a related issue and i think my original path is not going to work as it seems ocgs are not added to the stream.
