### ISSUE TITLE
URLError on urlopen of CSS File for WeasyPrint

### ISSUE THREAD

**Issue by allidoisace** [Kozea/WeasyPrint#1775]
I don't have this issue, but a friend gets this error in a `weasyprint.log`. This prevents the stylesheet from loading on the print page. Not sure why there is a difference between our environments when everything is the exact same in the Pipfile. 

```
Failed to load stylesheet at http://test.localhost:8000/static/app/pdf-style.css: URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

**Comment by liZe** [comment]
Hi!

Your friend’s computer doesn’t resolve `test.localhost`, contrary to yours. The difference is not related to WeasyPrint or Python at all, it comes from how the computer is configured. Your friend’s computer may not use [`systemd-resolved`](https://unix.stackexchange.com/questions/401966/how-does-every-subdomain-of-localhost-point-to-localhost-on-fedora).

**Comment by serbboy23** [comment]
> Hi!
> 
> Your friend’s computer doesn’t resolve `test.localhost`, contrary to yours. The difference is not related to WeasyPrint or Python at all, it comes from how the computer is configured. Your friend’s computer may not use [`systemd-resolved`](https://unix.stackexchange.com/questions/401966/how-does-every-subdomain-of-localhost-point-to-localhost-on-fedora).

So I am able to hit test.localhost in the browser, just seems like urlopen refuses. We are on Mac M1 (Apple Silicon).

Sorry this has become off topic now.

**Comment by serbboy23** [comment]
> Hi!
> 
> Your friend’s computer doesn’t resolve `test.localhost`, contrary to yours. The difference is not related to WeasyPrint or Python at all, it comes from how the computer is configured. Your friend’s computer may not use [`systemd-resolved`](https://unix.stackexchange.com/questions/401966/how-does-every-subdomain-of-localhost-point-to-localhost-on-fedora).

You were right about `test.localhost` not resolving. Oddly it does on the browser, but with `urlopen` it doesn't. I had to edit my `/etc/hosts` file to map `127.0.0.1` to `test.localhost`. Thank you!

**Comment by allidoisace** [comment]
Pretty odd, I didn't have to do that. Just works without having to map that hostname.
