### ISSUE TITLE
v57.0 breaks font fallback for missing glyphs

### ISSUE THREAD

**Issue by mmoreaux** [Kozea/WeasyPrint#1776]
For characters in a document that are not present in the selected font the renderer should fall back to some other font. This worked in v56.0, but doesn't in v57.0.

Example input:

```
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <style>
    @font-face { font-family: ArchitectsDaughter; src: url(ArchitectsDaughter-Regular.ttf); }
    body { font-family: ArchitectsDaughter; }
  </style>
</head>
<body><p>Here follow some Greek characters: α β γ δ ε π σ ω. The end.</p></body>
```

The font is [Architects Daughter](https://fonts.google.com/specimen/Architects+Daughter), because it doesn't have the greek characters, and you can clearly see that Weasyprint substituted characters from a different font. I also observed the behaviour with other fonts.

Output of `pip install weasyprint==56.0; weasyprint test.html test.pdf`:
![Screenshot from 2022-12-14 12-26-37](https://user-images.githubusercontent.com/7665839/207591347-30b67d9d-52bb-4598-8f6a-bdb44e9e7937.png)

Output of `pip install weasyprint==57.0; weasyprint test.html test.pdf`:
![Screenshot from 2022-12-14 12-26-46](https://user-images.githubusercontent.com/7665839/207591440-07bd71dd-c633-4e1f-945d-46566830233a.png)

**Comment by grewn0uille** [comment]
Hello,
I can reproduce the issue with v57.0, but it works well with v57.1. Can you try with the lastest version v57.1?

**Comment by mmoreaux** [comment]
Whoops, I can't believe I missed the fact that there's a newer version... XD

It seems to work perfectly fine with v57.1! Closing this issue.
