### ISSUE TITLE
Excess PDF file size when included images have some particular EXIF fields (not all fields identified yet)

### ISSUE THREAD

**Issue by AlexanderNeilson** [Kozea/WeasyPrint#1777]
Sorry for the lack of clarity in some of this as I haven't been able to fully isolate what is the causing feature (btw does anyone know a good metadata gui editor that allows for selective removal of fields - I am using Metadata++ so far to investigate but it doesn't seem to allow selecting and removing any random lines however it will allow bulk delete).

Background:
When images with particular metadata tags in them are included in PDF's generated by WeasyPrint (57.1, 57.0, 56.1, 56.0, 55.0) (and some versions tried with Pillow 9.3.0, 9.2.0) the output PDF file size is significantly larger than normally expected (the example that will be attached to this shows the file with stripped metadata tags renders at 348KB and with all metadata tags included the same image renders into a PDF as 2,885KB)

Currently identified factors:
* So far all triggering photos were taken on iPhone 14 Pro Max running iOS 16.1.2
* The images were resized before upload by our website front end to 1600 x 1200 pixels from the original ~4kx3k pixels
* iPhone 13 Pro Max running iOS 16.3 Dev Beta one doesn't trigger the issue
* The images include metadata fields identified in Metadata++ as in a category Apply some of which are named but others are un named and identified only by code and the body of those tags are not clearly understandable in the ui
* This metadata is not included in the images uploaded from the iPhone 13 Pro Max
* The EXIF fields identifying the pixel dimensions of the image are not updated by our front end when they do their resizing
* Fixing the pixel dimensions in the EXIF fields did fix the file size when the PDF is generated on a MacOS system (Python 3.10) however the file still generates large files when run on Windows 10 and Debian 11 (both Python 3.9)

Please let me know if I can provide any further information, we are continuing to try trace why its happening and at least work around it for our needs but happy to work with the community with a proper fix more than just working around it.

[WeasyPrint.zip](https://github.com/Kozea/WeasyPrint/files/10267393/WeasyPrint.zip)

**Comment by liZe** [comment]
Hi!

The problem was actually caused by the iPhone 14 storing multiple images in its photographs. The format is then detected as MRO instead of JPEG by Pillow (see https://github.com/python-pillow/Pillow/issues/1138), leading to a useless conversion to PNG.
