### ISSUE TITLE
Use PDF "named destinations" for bookmarks/outlines

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/WeasyPrint#178]
We use CSS’s [bookmarks](http://dev.w3.org/csswg/css-gcpm/#bookmarks) feature to generate PDF "outlines". We should additionally generate "named destinations" for these, to take advantage of pdf.js’s support for navigating to them with a fragment identifier:

http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#M11.9.20535.3Heading.Named.Destinations

https://github.com/mozilla/pdf.js/blob/34f0f0962f5404b5897e00506bf434ca50cb4251/src/core/obj.js#L354

**Comment by liZe** [comment]
Oh, it's done now (actually just because of [Cairo limitations](dfab8a8), but who cares)…
