### ISSUE TITLE
Open PDF-file instead of saving it with weasyprint in python

### ISSUE THREAD

**Issue by miguelet17** [Kozea/WeasyPrint#1781]
I am creating a pdf file in python with the weasyprint package. Creation and saving it works fine but I would prefer python to simply create the PDF and open it in a viewer so that the reader can save it manually.

A sample code of the saving version is as follow:

```python
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML


env = Environment(loader=FileSystemLoader('.'))

string = <!DOCTYPE html><html><head lang="en"><meta charset="UTF-8"><title>TEST</title></head><body><h2>Test</h2></body></html>

HTML(string = string, base_url = '.').write_pdf('example.pdf')
```

How can I open the created PDF instead of saving it, please?

**Comment by liZe** [comment]
Hi!

What you want is to open a file with the default PDF reader configured on your system. That’s not related to WeasyPrint, so that’s probably more a question for StackOverflow than for this bug tracker 😁️.

[This answer](https://stackoverflow.com/questions/434597/open-document-with-default-os-application-in-python-both-in-windows-and-mac-os) may be useful, you’ll find the code you want depending on your operating system.

**Comment by miguelet17** [comment]
Hello, I don't want to open it in a default operating system, since we migrated our PDF generator to weasyprint, we generate them fine, we look at them on s3 too but when the client wants to download them on any platform they can be opened, always keep that download.

**Comment by liZe** [comment]
I’m sorry but I don’t understand your problem. Your code creates a file called `example.pdf`, you can keep it on your server and give a link to your clients to share it, don’t you?

**Comment by miguelet17** [comment]
We generate the pdf, upload it to an amazon bucket and share the link.
Before we generated it with another library, we did the same and the client, when downloading the pdf, could open it directly. Now, since we used this library, it could only be opened from the file manager.

**Comment by liZe** [comment]
> Before we generated it with another library, we did the same and the client, when downloading the pdf, could open it directly.

Do you mean that it was displayed in the browser instead of being downloaded as a file? Then it’s only related to the [HTTP response headers](https://stackoverflow.com/questions/6293893/how-do-i-force-files-to-open-in-the-browser-instead-of-downloading-pdf), not at all with the PDF file itself.

**Comment by miguelet17** [comment]
Perfect, thank you very much
