### ISSUE TITLE
PDF/UA-1 and links

### ISSUE THREAD

**Issue by jjsarton** [Kozea/WeasyPrint#1782]
I have an HTML5 File with a few links. Generating the PDF file seem to work well. Checking it with verapdf report:

```
A Link annotation is nested within null tag instead of Link
--
root/document[0]/pages[11](33 0 obj PDPage)/annots[8](42 0 obj PDLinkAnnot)
A Link annotation is nested within null tag instead of Link
```

With this exception, a great work!

**Comment by liZe** [comment]
Hi!

Could you please test the current master branch? There’s a commit that could fix your problem.

Otherwise, could you please share a document that shows the problem?

Thank you!

**Comment by jjsarton** [comment]
Hi,
I have tested against the master branch.
The html code is:

```
<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
	<title>PDF/UA-1</title>
	<style  type="text/css">
	body {
		font-family: sans-serif;
	}
    #conteneur {
		max-width: 50em;
		margin-right: auto;
		margin-left: auto;
	}
	@page {
		size: A4 portrait;
		margin: 20mm;
		padding-top: 1em;
  		widows: 5;
		@top-right {
			content: '';
		}
		@top-left {
			content: '';
		}
		@bottom-left {
			content: "PDF/UA-1";
			font-size: 9pt;
		}
		@bottom-right {
			content: "Page " counter(page) " / " counter(pages);
			font-size: 9pt;
		}
	}	
	</style>
</head>
<body>
	<main id="conteneur">
		<h1>Liens importants</h1>
			<ul>
				<li><a href="https://github.com/Kozea/WeasyPrint" target="_blank">Weasyprint</a></li>
				<li><a href="https://webaim.org" target="_blank">WebAIM</a></li>
			</ul>
			<p>
				Lien dans un texte <a href="https://github.com/Kozea/WeasyPrint" target="_blank">Weasyprint</a> est
				logiciel de grande qualité.
			</p>
	</main>
</body>
```
The pdf file was produced with /path/to/weasyprint --pdf-version 1.7 --pdf-variant pdf/ua-1 test.html test.pdf.
The file pass the verapdf tests. Thanks for continuing the development.
While testing the result with orca, some output seem to be strange and the NVDA output seem also to be wrong.

The bullet point were announced after the paragraph (NVDA). With orca there are also problems with the two list-item.

**Comment by liZe** [comment]
> The file pass the verapdf tests. Thanks for continuing the development.

🚀

> While testing the result with orca, some output seem to be strange and the NVDA output seem also to be wrong.
> 
> The bullet point were announced after the paragraph (NVDA). With orca there are also problems with the two list-item.

We know that the tag structure is far from perfect, that’s why it’s marked as experimental. The first step was to get valid documents (and that was a huge step!), but the real goal is of course to get PDFs that are really accessible.

If you have some time, it would be very useful to open new issues when you get problems with the tag structure, such as this one. We’ll close this issue as the original problem is fixed. But it’s really important to get separate issues to get track of the problems, and hopefully find the time/contributors/sponsors that will help to solve the problems quickly.

Thank you!
