### ISSUE TITLE
Tibetan pagination

### ISSUE THREAD

**Issue by RimeOCRLIB** [Kozea/WeasyPrint#1786]
For Tibetan text print layout it is need insert ༄༅། in beginning of first text string on every odd page.

Please help us understand how apply this rule for page layout

With best regards
Open Source Buddhism Library
Alexander Stroganov
![tibetan pagination](https://user-images.githubusercontent.com/1236488/209484714-ffe2c828-5f37-4f42-bd67-2edf5866e33d.png)

**Comment by liZe** [comment]
Hi!

As far as I know, the `@page` rules don’t provide a way to add something in the text of the page content. So, if you don’t know before the layout on which page each block is displayed, I don’t think that there’s a way to add this character 😢️.

Maybe there’s something included somewhere in a CSS specification to handle this use case. There’s a [dedicated section in a W3C document](https://www.w3.org/TR/tlreq/#head_marks), but not CSS feature seems to be linked to this requirement.

The next step to solve this problem is to find a feature in the CSS specification that could be useful. And if it doesn’t exist, it should be interesting to open an issue on [the CSSWG’s repository](https://github.com/w3c/csswg-drafts/issues) explaining this requirement and asking for a feature that could help.

**Comment by RimeOCRLIB** [comment]
Look for that it is need access to Python pages and phrases rendering rules.
For that reason we can not use plain QT WebView engine for that. Does Weasyprint have Python access to phrases and pages level of HTML render?

**Comment by liZe** [comment]
> Does Weasyprint have Python access to phrases and pages level of HTML render?

It’s theoretically possible to change the content on the fly, but you’ll need to rely on a private API that may change in the future.

I’ve used the sample you provided in the other issue and I’ve added some code before this line: https://github.com/Kozea/WeasyPrint/blob/005aa31e663139841779174436f7b1b50b7d7527/weasyprint/layout/inline.py#L37

```python
if 30 < position_y < 31:
    child = box
    child_skip_stack = skip_stack
    while isinstance(child, boxes.ParentBox):
        if child_skip_stack:
            skip = tuple(child_skip_stack.keys())[0]
            child_skip_stack = child_skip_stack[skip]
        else:
            skip = 0
        child = child.children[skip]
    if child_skip_stack:
        skip = tuple(child_skip_stack.keys())[0]
    else:
        skip = 0
    child.text = child.text[:skip] + 'abc' + child.text[skip:]
```

[book.pdf](https://github.com/Kozea/WeasyPrint/files/10310703/book.pdf)

**Of course, that’s a huge hack, and you’ll need more work to get something more robust that than.**

The test of the position (the first line) is a quick and dirty way to check that we’re at the top of the page (and not on the second line, or in a page margin). There’s probably a much better way to do this…

The `while` loop takes the box (that’s the line box) and recursively finds the current child in it, using `skip_stack` (that’s a pointer to the current position in the tree). It goes through the tree, taking each time the nth child, until it finds a box that’s not a parent box. At the end, `child` is the text box that’s displayed at the top of the page, and `child_skip_stack` is the current position in this text.

We then insert the text we want at the current position. Here’s, it’s `'abc'`, but of course you can put the correct string instead.

You can modify WeasyPrint itself for your needs, or just monkey-patch the `iter_line_boxes` function, but either way it’s a hack that may be broken and may need to be fixed when you update WeasyPrint.

**Comment by RimeOCRLIB** [comment]
Great!
May be we may ask add Language tag in init CSS and set  layout/inline.py handle this language tag?
It will need some time for us to read inline.py and try to set another rules.

On question for now.
How we may detect page number in inline.py? This ༄༅ sign need set on odd pages and not on even pages.

Thank you from my heart for help.
Merry Christmas and Happy New Year.
Alexander

**Comment by liZe** [comment]
> May be we may ask add Language tag in init CSS and set layout/inline.py handle this language tag?
> It will need some time for us to read inline.py and try to set another rules.

The "clean" way would be to have a CSS specification we could follow. We never add unspecified behaviors directly in WeasyPrint, it’s already really hard and time consuming to implement the existing specifications 😄. But, of couse, you can hack WeasyPrint to fit your needs. It’s even possible to override WeasyPrint’s function without touching its code, that’s part of Python’s beauty (or ugliness, who knows?).

> How we may detect page number in inline.py? This ༄༅ sign need set on odd pages and not on even pages.

The `context` variable has a `current_page` attribute.

Happy new year for you too!
