### ISSUE TITLE
Running elements  @bottom doesn't work.

### ISSUE THREAD

**Issue by sahilrl** [Kozea/WeasyPrint#1787]
The header works flawlessly but the footer doesn't appear on all the pages except the last one.

Here is the CSS

`@page { 
    margin: 6em 0;

   @top-center {
        content: element(headerCenter);
        width: 100%;
        height: 7em;
   }

   @bottom-center {
        content: element(footerCenter);
        width: 100%;
        height: 7em;
   }
}

header {
    position: running(headerCenter);
    display: flex;
    justify-content: space-around;
    color: #152238;
    background-color: #c0e6f0;
    align-items: center;
  }

footer {
    position: running(footerCenter);
    background-color: #00008B;
    display: flex;
    justify-content: space-around;
    align-items: center;
    color: #fff;
}`

**Comment by liZe** [comment]
Hi!

The value given by `element(X)` is updated each time `running(X)` is called. So, `element(footerCenter)` is not defined until `footer` is seen and (`running(footerCenter)` is called. If you want to display the footer everywhere, you’ll have to put it at the top of the HTML document (just as the header).

**Comment by sahilrl** [comment]
Thank you for explaining in detail.  Its working now.
