### ISSUE TITLE
Section, Subsection Header Display

### ISSUE THREAD

**Issue by leek9** [Kozea/WeasyPrint#1791]
I could not create section and subsection headers that repeats across page.

Things that I have tried:
i)  nested table hoping <thead> would repeat but only the most inner <thead> is repeated. (I have heard to avoid nested table in weasyprint for now)
ii)  The CSS method of setting page headers with running(header)/element(header) with page media doesn't work with the subsection header. 

Is there any other suggestions I could try?

Thank you.

**Comment by liZe** [comment]
Hi!

I don’t fully understand your needs. Could you please share an image of what you have and an image of what you’d like to have?

**Comment by leek9** [comment]
Thanks for replying. I figure it out with combination of running headers and named page. Thank you so much.
