### ISSUE TITLE
How to repeat header column and caption on new pages for long table 

### ISSUE THREAD

**Issue by technqvi** [Kozea/WeasyPrint#1794]
I try to find how to print header column of table in case multiple page to show long table.
As figure below.

Whenever we print new page , it must print caption and header column on every page to show long table. How can I configure the thing on html or CSS or python to fulfill this requirement?
![image](https://user-images.githubusercontent.com/38780060/213701592-da21ac59-00aa-453a-9a55-f278f4a26bcc.png)

**Comment by liZe** [comment]
Hi!

The content of the `thead` and `tfoot` tags are automatically repeated on each page. You can probably put your headers and your caption there.

**Comment by technqvi** [comment]
Ok
