### ISSUE TITLE
Systematic Fontconfig warning

### ISSUE THREAD

**Issue by macdeport** [Kozea/WeasyPrint#1797]
Regardless of the html content the execution of the statement
`easy_html.write_pdf`(...)
generates systematically the following warning
`'Fontconfig warning: ignoring UTF-8: not a valid region tag'`
What is the reason for this ?

**Comment by liZe** [comment]
Hi!

This error is not directly related to WeasyPrint, but to your Fontconfig configuration. You can find a reason why this error happens and possibly how to solve it in [this StackOverflow thread](https://stackoverflow.com/questions/24712158/how-to-solve-imagemagicks-fontconfig-warning-ignoring-utf-8-not-a-valid-regi).

**Comment by macdeport** [comment]
This has fixed this warning perfectly. Thanks for your help by return.
