### ISSUE TITLE
Bullet list problem

### ISSUE THREAD

**Issue by Olavusk** [Kozea/WeasyPrint#1798]
Hello. I am experiencing a bug regarding colors and bullet-list. I am creating a system where i use weasyprint to make pdf-files. I use TinyMCE for my text-editors. When i render my pages in HTML everything works fine. But when i convert the page to PDF, bullet points with either: text-color, background-color or underline get a weird indent. 

Here are some pictures describing boat parts, where the formatting gets buggy. 

Html-render:

![image](https://user-images.githubusercontent.com/123564451/214583039-66d62a43-1152-493c-b6df-d8c8c1b63529.png)

PDF-Format:
![image](https://user-images.githubusercontent.com/123564451/214583119-690a285d-a3cb-45cc-8a5a-af272af50281.png)

As noted above, this is only a problem with bullet-points and list-numbering, it does not happen with regular text.

Hope somebody can help with this issue.

**Comment by Olavusk** [comment]
Django Template HTML file, relevant parts are the "content" parts:




    <article id="toc">
        <h4 style="color: rgb(80, 145, 205);  font-family: muli; font-weight: 400; font-size: 14pt; " >Content</h4>
        {% for chapter in spek.chapter_set.all|dictsort:"chapter_num" %}
        <div>
            <div class="filler"></div>
            <h5 style="font-size: 10pt;"><a href="#chapter-{{chapter}}" ></a></h5>
        </div>
        <ul style="width: 100%;">
            {% for sfi in chapter.sfi_set.all|dictsort:"SFI_num"|sortsfi  %}
                <li><div href="#sfi-{{sfi}}" class="filler"></div><a href="#sfi-{{sfi}}" ></a></li>
                
                

            {% endfor %}
                
        </ul>
        {% endfor %}
    </article>


    <article id="content">
        
        
        {% for chapter in spek.chapter_set.all|dictsort:"chapter_num" %}
        <article id="chapter">
            <h3 id="chapter-{{chapter}}" style="color: rgb(0, 45, 91);  font-family: muli; font-weight: bold; font-size: 16pt;" >SFI {{chapter.chapter_num}}: {{ sfi_to_header|get_header_en:chapter.chapter_num|upper}}</h3>
            {% for sfi in chapter.sfi_set.all|dictsort:"SFI_num"|sortsfi %}
                <h4 id="sfi-{{sfi}}" style="color: rgb(0, 45, 91);  font-family: muli; font-weight: bold; font-size: 13pt; margin-top: 25px;" >{{sfi.SFI_num}}. {{ sfi_to_header|get_header_en:sfi.SFI_num|upper}}</h4>

                {% for module in sfi.Modules.all|dictsort:"order"   %}
                    {% for content in module.content_set.all|dictsort:"order"  %}
                        {% if content.includedIn != "Kun Byggespek" %}

                             {% if content.payload_en != "" %}
                            <div style="font-family: muli; font-size: 10pt;" class="contentContainer">
                                {% parsePointer content.payload_en spek "en" as parsed %}
                                {{parsed|safe}}
                            </div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
                    
            
            
            {% endfor %}
                
        
        
        </article>
        {% endfor %}
                
    </article>
</body>






<div>
<style>
    @page{
        @top-center{
            content:"{{spekname}} {{spek.propulsion_en}}";
            overflow: visible;
            line-break: strict;
            white-space: nowrap;
        }
        @top-right{
            content:"{{currentdate}}"
        }
        
        @top-left{
            background-image: url("{% static 'images/moenmarin.png' %}");
            margin-top: 10px;
            background-repeat: no-repeat;
            background-size: 130px 31px;
            width: 50%;
        }
    }
    @page:first{
        border: none;
        padding-top: 12px;
        @top-center{
            content:"";
        }
        @top-right{
            content:"";
        }
        @top-left{
            content:"";
            background-image: none;
        }
}


    p {
        font-family: muli; font-size: 10pt; line-height: 140%;color: rgb(0, 45, 91);
    }

    ol, ul{
        font-family: muli; font-size: 10pt; line-height: 120%;color: rgb(0, 45, 91);
    }

    th, td {
        font-family: muli; font-size: 10pt; margin-top: 35px;color: rgb(0, 45, 91);
    }

    #toc h5 a {
        font-family: muli; font-size: 10pt; font-weight: 400; letter-spacing: 150%;color: rgb(0, 45, 91);
    }

    #toc li a {
        font-family: muli; font-size: 10pt; font-weight: 400; margin-left: 20px;color: rgb(0, 45, 91);

    }

    table{
        border-collapse: collapse;
    }
    thead, tr {
        font-family: muli; font-size: 10pt;
        line-height: 1.2rem;
        border-bottom: 1px solid black;
    }
    


</style>
</div>

**Comment by Olavusk** [comment]
Is it realistic to expect a solution to this?

**Comment by liZe** [comment]
> Is it realistic to expect a solution to this?

Hi.

I didn’t manage to reproduce your bug with your code. Could you please send an HTML/CSS sample that reproduces your problem?

**Comment by Olavusk** [comment]
This is code snippet from a HTML rendered page. It looks fine while rendered in the browser as html, but it looks weird when converted to PDF. 


``

<html lang="en">
--
  | <head>
  | <meta charset="UTF-8">
  | <meta name="description" content="template">
  | <title></title>
  | <link rel="stylesheet" href="https://use.typekit.net/ojb0cvu.css"> 
  | <link rel="icon" href="https://storage.googleapis.com/mspek_bucket/images/MM_icon.jpg" type="image/x-icon">
  | 
  |  
  | </head>
  |  
  |  
  | <body>
<article id="content">
  |  
  |  
  |  
  | <article id="chapter">
  | <h3 id="chapter-Olav Sin Båt kap: 1" style="color: rgb(0, 45, 91);  font-family: muli; font-weight: bold; font-size: 16pt;" >SFI 1: SHIP GENERAL</h3>
  |  
  |  
  |  
  |  
  |  
  |  
  | <h4 id="sfi-SFI100" style="color: rgb(0, 45, 91);  font-family: muli; font-weight: bold; font-size: 13pt; margin-top: 25px;" >100. GENERAL</h4>
  |  
  |  
  | <div style="font-family: muli; font-size: 10pt;" class="contentContainer">
  |  
  | <p>This is normal text</p>
  | <p><span style="color: #e74c3c;">This is normal text with color</span></p>
  | <ul>
  | <li>This bullet point with no colors, is no problem</li>
  | <li><span style="color: #e74c3c;">This text in bulletpoint creates a problem</span></li>
  | <li><span style="color: #e74c3c; background-color: #2fcc71;">This text creates <span style="color: #000000; background-color: #ffffff;">a problem</span></span></li>
  | </ul>
  | <ol>
  | <li><span style="color: #e74c3c; background-color: #2fcc71;"><span style="color: #000000; background-color: #ffffff;">This is&nbsp;<span style="color: #e74c3c; background-color: #000000;">a problem</span></span></span></li>
  | <li><span style="text-decoration: underline;">This text with underscore is a problem</span></li>
  | </ol>
  | <p><span style="text-decoration: underline; color: #000000; background-color: #e74c3c;">This text with coloring, but no bullet point works fine.</span></p>
  | </div>
  |  </article>
  | </body>
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <style>
  | @page{
  | @top-center{
  | content:"NabCat 2423 Electric";
  | overflow: visible;
  | line-break: strict;
  | white-space: nowrap;
  | }
  | @top-right{
  | content:"17.02.2023"
  | }
  |  
  | @top-left{
  | background-image: url("https://storage.googleapis.com/mspek_bucket/images/moenmarin.png");
  | margin-top: 10px;
  | background-repeat: no-repeat;
  | background-size: 130px 31px;
  | width: 50%;
  | }
  | }
  | @page:first{
  | border: none;
  | padding-top: 12px;
  | @top-center{
  | content:"";
  | }
  | @top-right{
  | content:"";
  | }
  | @top-left{
  | content:"";
  | background-image: none;
  | }
  | }
  |  
  |  
  | p {
  | font-family: muli; font-size: 10pt; line-height: 140%;color: rgb(0, 45, 91);
  | }
  |  
  | ol, ul{
  | font-family: muli; font-size: 10pt; line-height: 120%;color: rgb(0, 45, 91);
  | }
  |  
  | th, td {
  | font-family: muli; font-size: 10pt; margin-top: 35px;color: rgb(0, 45, 91);
  | }
  |  
  | #toc h5 a {
  | font-family: muli; font-size: 10pt; font-weight: 400; letter-spacing: 150%;color: rgb(0, 45, 91);
  | }
  |  
  | #toc li a {
  | font-family: muli; font-size: 10pt; font-weight: 400; margin-left: 20px;color: rgb(0, 45, 91);
  |  
  | }
  |  
  | table{
  | border-collapse: collapse;
  | }
  | thead, tr {
  | font-family: muli; font-size: 10pt;
  | line-height: 1.2rem;
  | border-bottom: 1px solid black;
  | }
  |  
  |  
  |  
  | </style>

``

**Comment by Olavusk** [comment]
[20230217 Olav Sin Båt en specification.pdf](https://github.com/Kozea/WeasyPrint/files/10765392/20230217.Olav.Sin.Bat.en.specification.pdf)

Pdf showing the error (first chapter)

**Comment by liZe** [comment]
We’re really sorry, but we can’t reproduce your problem with your sample.
[out.pdf](https://github.com/Kozea/WeasyPrint/files/10765870/out.pdf)

Could you please share a sample that reproduces your error?

**Comment by Olavusk** [comment]
Sorry, I didn't include all the css, here is another file used for the styling:

`
@font-face {
    font-family: Verdana;
    font-weight: 400;
    font-style: normal;
    src: url('https://use.typekit.net/ojb0cvu.css');
  }

@page{
    size: a4;
}

@page{
    @top-center{
        content: "Spekname"; /* Default if spek doesn't have name */
        color: rgb(0, 45, 91);
        font-size: 8pt;
        font-weight: bold;
        height: 1cm;
        border-bottom: 1px rgb(217, 116, 38);
    }
    @top-left{
        content: ''; /* Required to add logo */
        height: 1cm;
    }
    @top-right{
        content: "dd.mm.yyyy"; /* default if date is not found */
        color: rgb(217, 116, 38);
        font-size: 8pt;
        font-weight: bold;
        height: 1cm;
    }
    @bottom-right{
        content: counter(page) " of " counter(pages);
        color: rgb(217, 116, 38);
        font-size: 8pt;
        font-weight: bold;
        height: 1cm;
    }
    @bottom-center{
        content: "Made by mSPEK";
        color: rgb(0, 45, 91);
        font-size: 8pt;
        /* font-weight: bold; */
        height: 1cm;
    }
    @bottom-left{
        content: "Moen Marin AS";
        color: rgb(0, 45, 91);
        font-size: 8pt;
        font-weight: bold;
        height: 1cm;
    }
}

@page {
    border-top: 1px rgb(217, 116, 38) solid;
    padding-top: 25px;
}

hr {
    height: 0.5pt;
    border: none;
    background-color: rgb(217, 116, 38);
}


.centering { /* Requires width != auto */
    display: block;
    margin: 0 auto;
}

#toc {
    page-break-before:always;
}

#chapter {
    page-break-before:always;
}

.h { /* classes appended to content dependent on format (chosen in editor) */
    font-weight: bold;
    text-transform: uppercase;
}

.p {
    line-height: 140%;
    margin:0
}


li span {
    position: relative;
    left: 15px;
}

.ul {
    display: list-item;
}

/* ('h', 'Overskrift'),
        ('p', 'Tekst'),
        ('ol', 'Liste med nummer'),
        ('ul', 'Kulepunkter'), */



#toc h5 {
    padding: 0;
    margin: 0;
}

#toc h5 a {
    color: inherit;
    text-decoration-line: inherit;
}

#toc h5 a::before {
    content: target-text(attr(href));   
    background-color: white;

}

#toc h5 a::after {
    color: #000000;
    content: target-counter(attr(href), page);
    float: right;
    background-color: white;

}

#toc ul {
    list-style: none;
    padding-left: 0;
    margin-top: 0;
}

#toc li {
    margin-top: 10px;
}


#toc ul li a {
    color: inherit;
    text-decoration-line: inherit;
}
#toc ul li a::before {
    content: target-text(attr(href));
    background-color: white;
}



#toc ul li a::after {
    color: #000000;
    content: target-counter(attr(href), page);
    float: right;
    margin-top: 4px;
    margin-right: 20px;
    background-color: white;
}

/* #toc .toc-sfiHeader::before {
    content: target-text(attr(href));
    margin: 0;
    padding: 0;
}


#toc .toc-sfiPage {
    float: right;
}

#toc .toc-sfiPage::after {
    content: target-counter(attr(href), page);
} */


li .filler {
    position: absolute;
    left: 0;
    margin-top: 12px;
    margin-left: 35px;
    margin-right: 20px;
    z-index: -10;
    right: 0;
    border-bottom: 2px dotted rgb(78, 78, 78);
}

div .filler {
    position: absolute;
    left: 0;
    margin-top: 11px;
    margin-left: 35px;
    margin-right: 20px;
    z-index: -10;
    right: 0;
    border-bottom: 1px dashed #000;
}



.contentContainer  ol, .contentContainer  ul {
    margin: 0;
}

.contentContainer  li {
    padding-bottom: 6px;
  }`

**Comment by Olavusk** [comment]
Sorry, This seems to have been an error from my side, it was

`li span {
    position: relative;
    /* left: 15px; */      <- this part
}`

that caused the error. I am sorry for wasting your time.
