### ISSUE TITLE
Header section  :I can not print content on header for other pages except the first page . 

### ISSUE THREAD

**Issue by technqvi** [Kozea/WeasyPrint#1799]
Hi 

I try to find out the way  to deal with printing content on the header  as link below
[https://stackoverflow.com/questions/70528074/how-to-set-a-header-in-the-same-place-across-different-pages-by-using-weasyprint](https://stackoverflow.com/questions/70528074/how-to-set-a-header-in-the-same-place-across-different-pages-by-using-weasyprint)

It work on the first page , but it didn't work on other pages at all.
I suppose that I probably configure something wrong on CSS file in @top-center  part.
How to fix it?

Honestly,I am data engineer,  mostly I work on big data , and machine learining project,  so that's why  I don't have much experience about this thing but  This is a small part of my urgent task that I have to get it done soon.   

Below are my html  file and css file ( focusing on the header  part)  and picture to show result of printing pdf  file.  
pdf_pm_overview.css file
```
header {
    /*position: running(header);*/
    border-style: none;
    width: 100%;
    font-family: 'Times New Roman';
    font-size: 14px;
    font-weight: bold;
    color: #0f74a8;
}
.table_report_header {
    border-style: none;
}
.th_report_header {
    border-style: none;
    vertical-align: bottom;
    width: 50%;
}
@page {
    size: letter; /* Change from the default size of A4 */
    margin: 1.0cm; /* Set defaultmargin on each page 2.0-2.5 */
    @top-center {
          content: element(head);
    }
    @bottom-right {
        content: "Page " counter(page) " | " counter(pages);
    }
}



```

html file
```

<body>

<header>
    <table class="table_report_header">
        <thead>
        <tr >
            <th class="th_report_header">
                PREVENTIVE MAINTENANCE REPORT
            </th>
            <th class="th_report_header">
                  <img src="file:{{ Report_Logo }}"    />
            </th>
        </tr>
        </thead>
    </table>
    <hr>
</header>

<div class="caption_table">
    Customer Details
</div>


</body>


```

This is the first page. , it appear header as expected.
![image](https://user-images.githubusercontent.com/38780060/214795460-b2c67d8d-fa06-4619-88fd-c041a6cd8257.png)

but next page, there is no header.
![image](https://user-images.githubusercontent.com/38780060/214795786-f3d1eb3c-5316-4995-b880-903ddb0efc23.png)

Thank you a lot
Pongthorn

**Comment by grewn0uille** [comment]
Hello @technqvi,

Running elements are a good way to have header on each pages.

In your CSS, you have `running(header)` and `element(head)`. It should be the same name in both parenthesis, so `running(head)` and `element(head)` for example.

Don’t forget to uncomment the `position: running()` line.

**Comment by technqvi** [comment]
> running(head)

Thank you. 
I uncomment   position: running(header) as per your advice, It  can iterate the header content through each page successfully

let's see the figure shown in below.
but the header position on the second page is quite terrible.
the first page , some points as I highlight, it are in the right position as compared to what I want that I refer to the picture as below on the right-hand side.  the left-hand sider is results from printing.

I don't have much knowledge about CSS, do you have any idea to do something in CSS file  to satisfy my requirement as picture below?
![image](https://user-images.githubusercontent.com/38780060/214841757-d71af846-b154-4f3a-acf7-84bc10f31c3e.png)


Please advice me on css file

this is css file and html file
```
header {

    position: running(header);
    border-style: none;
    width: 100%;
    height: 1.5cm;

    font-family: 'Times New Roman';
    font-size: 14px;
    font-weight: bold;
    color: #0f74a8;
}
@page {
    size: letter; /* Change from the default size of A4 */
    margin: 1.0cm; /* Set defaultmargin on each page 2.0-2.5 */
    @top-right {
          content: element(header);

    }
    @bottom-right {
        content: "Page " counter(page) " | " counter(pages);
    }
}


```

```
<header>
    <div>
        PREVENTIVE MAINTENANCE REPORT &nbsp;&nbsp;&nbsp; <img src="file:{{ Report_Logo }}"    />
    </div>

    <hr>
</header>


```

Thank you for any help
Pongthorn

**Comment by grewn0uille** [comment]
Hello,

To have a text and an image in the top of your page, it’s easier to use a running element for the text and another for the image.

Your HTML would look like to:
```html
<body>
<header>
    <p>PREVENTIVE MAINTENANCE REPORT</p>
</header>

<div id="logo">
    <img src="logo-red.svg" />
</div>

<div class="caption_table">
    Customer Details
</div>
</body>
```

On the CSS part, you’ll have to add a new running element and choose where you want the text and where you want the image.

You can notice that I also changed the margins of the page. Indeed, the top margin height need to be sufficient enough to contain the image (here it’s 2.5cm, but you put whatever you need).

Your CSS would look like something like this:
```css
<style>
header {
    position: running(head);
    border-style: none;
    font-family: 'Times New Roman';
    font-size: 14px;
    font-weight: bold;
    color: #0f74a8;
}
#logo {
    position: running(logo);
}
#logo img {
    width: 2cm;
}
@page {
    size: letter; 
    margin: 2.5cm 1cm 1cm 1cm;
    @top-left {
         content: element(head);
    }
    @top-right {
        content: element(logo);
    }
    @bottom-right {
        content: "Page " counter(page) " | " counter(pages);
    }
}
</style>
```

And you get something like this:

![image](https://user-images.githubusercontent.com/13187416/215068519-15bed424-97ac-4ac8-8843-4c3e1b2144d1.png)

**Comment by technqvi** [comment]
Thank you very much
I appreciate your kind support

**Comment by technqvi** [comment]
ok
