### ISSUE TITLE
SmallCaps not working in PDF even font supports it and HTML is well displaying the smallcaps.

### ISSUE THREAD

**Issue by fabiobatalha** [Kozea/WeasyPrint#1800]
WeasyPrint version : 52.5
Input HTML :  [1093584ar.zip](https://github.com/Kozea/WeasyPrint/files/10512625/1093584ar.zip)
PDF Output :  [1093584ar.pdf](https://github.com/Kozea/WeasyPrint/files/10512628/1093584ar.pdf)

The error is in the bibliographic section of the document.

The HTML file output (OK)

![Screenshot from 2023-01-26 14-17-58](https://user-images.githubusercontent.com/504142/214929197-cd21f0f5-317a-46c5-b51b-4c6175ad5af1.png)

The PDF file output (Not OK)

![Screenshot from 2023-01-26 14-19-23](https://user-images.githubusercontent.com/504142/214929389-7c5ab90a-6a13-4af9-af21-47d84cb462e2.png)

The CSS to apply the small caps is:

```css
.smallcaps {
  font-variant: small-caps;
}
```

**Comment by liZe** [comment]
Hi!

The Maax and Open Sans fonts used in your document don’t have the OpenType small-caps feature. The small caps displayed by your browser are [synthetic small caps](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#font-variant-caps-prop), and this feature is not supported by WeasyPrint.

If you’re interested in this feature, we can continue the discussion in #123.
