### ISSUE TITLE
Keep original PNG in PDF

### ISSUE THREAD

**Issue by palb91** [Kozea/WeasyPrint#1801]
Hello!

Thanks for your tool and your amazing continuous work!

I create reports using weasyprint that contains screenshots. These screenshots are often (if not always) PNGs, and some of them have transparency.
If I extract the file from the PDF, they are different from the original image (probably compressed), and for images with transparency I have two PNGs, one is the PNG without transparency, the second a "transparency mask" of the same PNG. 
Moreover, the metadata are not kept (If I directly use a JPG with metadata, the file is not exactly the same as the original but at least the metadata are still here).

**Do you know if there is a way to keep the original PNG in the final PDF? Maybe by using the Attachment class and reusing it? Or maybe there is an obscur parameter to toggle in order to keep PNGs?**

---

**Use case:** I can't keep the sources of my report, so my goal is to embed the sources in the report in order to be able to edit it again if someone give me the original PDF. I already embed the text source in the report as attachment, but if I do the same with PNGs, the final size of the report is just… insane. So I'd like to be able to retrieve the original PNGs directly from the content of the PDF.

**Workaround:** I may convert PNGs to JPGs while keeping metadata, so I would be able to retrieve them later, but it implies to also modify the sources that are normally written by hand and should not be automatically modified.

**Note1:** Something like `<img rel=attachment href="x.png" />` would have been perfect, but it's not a valid `img` attribute.

**Note2:** The tools I used for extracting images (`pdfimages` and `Python PyMUPDF`) allow me to extract the images in the correct order, but with the masks and the images in headers/footers that are also extracted it's not really reliable.

---

    Linux 6.1.9
    python 3.10.9
    WeasyPrint version 57.2
    pdfimages version 23.02.0

**Comment by liZe** [comment]
> Do you know if there is a way to keep the original PNG in the final PDF?

It’s not currently possible, and to be honest I’m not sure that it’s actually possible with the PDF format. As far as I know, it’s possible to embed images using an PNG-like format, but not directly in "real" PNG files. So, even theoretically, it may actually be impossible.

> **Workaround:** I may convert PNGs to JPGs while keeping metadata, so I would be able to retrieve them later, but it implies to also modify the sources that are normally written by hand and should not be automatically modified.

Some JPEG files are stored directly in the PDF, so that could be a solution.

**Comment by palb91** [comment]
Hello,

> Some JPEG files are stored directly in the PDF, so that could be a solution.

From my recent tests, some JPG still lose their metadata, some not, so even with this format it seem to be random. I’ll try to find another "stable" way… or just embed all files in the format I want in a big final PDF file.

Anyway, thanks for your time and your reply!
