### ISSUE TITLE
Image filling all available space

### ISSUE THREAD

**Issue by DuignanSean** [Kozea/WeasyPrint#1802]
We have started using WeasyPrint for pdf document generation over LaTex and have been able to successfully port all functionality bar one. Maybe someone can shed some light.

Consider an A4 page with nothing but a h2 title (with some margin/padding) followed by an image (img with no margin/padding). We are trying to allow the image to fill up the rest of the A4 page (hight-wise) as much as possible while still respecting its container (the page width) and the container's existing content (the h2 title and styling).

It seems like something that should be possible, but we're coming up short. Any help would be appreciated, thanks for the great tool.

**Comment by liZe** [comment]
Hi!

Here’s a sample that should do what you want:

```html
<style>
  @page { margin: 0 }
  body { margin: 0; display: flex; flex-direction: column }
  h2 { margin: 0; flex: none }
  div { flex: auto; background: url(…) center / cover }
</style>
<div>
  <h2>Title</h2>
  <div></div>
</div>
```
