### ISSUE TITLE
Is customized user-agent available?

### ISSUE THREAD

**Issue by sprindjack** [Kozea/WeasyPrint#1808]
For some web provide different type of contents showing methods. Desktop version and Mobile version.

**Comment by grewn0uille** [comment]
Hello,

The cleanest way is to [define your own url fetcher](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#url-fetchers).

A dirtier way, but simpler, is to import urls from weasyprint and change [urls.HTTP_HEADERS](https://github.com/Kozea/WeasyPrint/blob/16cf66c807e12fabcd703cad3f1b76c8bf19b62e/weasyprint/urls.py#L32). But note that’s not a public API and may change in the future.

**Comment by sprindjack** [comment]
> Hello,
> 
> The cleanest way is to [define your own url fetcher](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#url-fetchers).
> 
> A dirtier way, but simpler, is to import urls from weasyprint and change [urls.HTTP_HEADERS](https://github.com/Kozea/WeasyPrint/blob/16cf66c807e12fabcd703cad3f1b76c8bf19b62e/weasyprint/urls.py#L32). But note that’s not a public API and may change in the future.

Thank you for fast responce and suggestions. I will give it a try.
