### ISSUE TITLE
How to detect that glyph is missing?

### ISSUE THREAD

**Issue by survtur** [Kozea/WeasyPrint#1810]
I see that weasyprint prints nothing if character is missing. Is it possible to get an error in this case?

**Comment by liZe** [comment]
> I see that weasyprint prints nothing if character is missing.

Yes, that’s what browsers usually do too (or draw tofus, or draw question marks…)

> Is it possible to get an error in this case?

That would probably be quite hard, because applications dealing with missing glyphs are usually not supposed to give errors. What’s your use case? Installing fonts with a very wide glyph coverage (such as [noto](https://fonts.google.com/noto)) is often the best way to solve this kind of problems.

**Comment by survtur** [comment]
The idea is simple. I just want to be sure that everything is printed. Earlier I used some selenium-browser-then-print as document rendering system and I had javascript that tests width of every symbol used in HTML. If symbol has zero width it raises an error. Of course I had lists of zero-width symbols that should not raise exceptions.

Also at previous stages my python script had listed all symbols from different fonts in my collection. And I checked all texts to be used in document and get list of fonts that will cover all used symbols.

I have a lot of Noto fonts installed. And sometimes I get an error about some symbol that does not exist in my collections. This is how I know that I have to find/update a font with this symbol.

So now I'm looking a way to switch from slow browser-js-print way to faster weasyprint way, keeping my current good "symbol-exist" checks.

**Comment by liZe** [comment]
I don’t think that there’s a way to do this with the current public API, but you can override `draw_first_line` to reliably detect missing glyphs. We actually already do this here:

https://github.com/Kozea/WeasyPrint/blob/96c97d19f832e01ebf8e6d3f9522184a8cae15b7/weasyprint/draw.py#L1145-L1146

The first condition finds zero-width empty glyphs, the second one finds missing glyphs (that’s what you want to detect).

**Comment by survtur** [comment]
Thank for pointing me at this code for the future use. Maybe :smile:
