### ISSUE TITLE
How to make WeasyPrint & Firefox rendering more similar

### ISSUE THREAD

**Issue by macdeport** [Kozea/WeasyPrint#1812]
When the attached HTML file is opened using Firefox, an image appears at the top and the links are blue.

However, this is not the case with the PDF file produced by WeasyPrint...

How can I make the PDF file look like the Firefox rendering?
[ni-subventions-ni-deductibilite.html.zip](https://github.com/Kozea/WeasyPrint/files/10775259/ni-subventions-ni-deductibilite.html.zip)
[ni-subventions-ni-deductibilite.pdf.zip](https://github.com/Kozea/WeasyPrint/files/10775260/ni-subventions-ni-deductibilite.pdf.zip)

**Comment by liZe** [comment]
Hi.

Try to activate the [print mode](https://i.stack.imgur.com/DKyGp.png) in Firefox, you’ll get the image removed and the black links just as in WeasyPrint. It means that your CSS includes explicit rules to apply these changes for print.
