### ISSUE TITLE
Pixbuf error: Unrecognized image file format

### ISSUE THREAD

**Issue by mzu** [Kozea/WeasyPrint#182]
Hi
I am running WeasyPrint 0.21 on Ubuntu (12.04) and installed all the dependencies according to http://weasyprint.org/docs/install/#debian-ubuntu including GdkPixbuf:
libgdk-pixbuf2.0-0 (2.26.1-1) 
gir1.2-gdkpixbuf-2.0 (2.26.1-1) 
libgdk-pixbuf2.0-dev (2.26.1-1) 

Rendering of HTML+PNG to pdf works fine. I am only running into problems if there are any jpgs. The error I am getting looks like:

Pixbuf error: Unrecognized image file format

When I run gdk-pixbuf-query-loaders  I can see:
"/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so"
"jpeg" 5 "gdk-pixbuf" "The JPEG image format" "LGPL"
"image/jpeg" ""
"jpeg" "jpe" "jpg" ""
"\377\330" "" 100

I also checked the jpg file with jpeginfo:
jpeginfo skateboard-1.jpg 
skateboard-1.jpg 1200 x 1200 24bit JFIF  P   64299 

Do I have anything missing to get jpg support with weasyprint?

**Comment by netoxico** [comment]
I had the same Pixbuf error: Unrecognized image file format error, updated shared-mime-info and error gone

**Comment by pathumego** [comment]
Im having the same issue on macOS. Im new to WeasyPrint and links mentioned by @SimonSapin are broken. Any clues on how to fix?

**Comment by mohdnajdy** [comment]
Hello, I am getting the same issue when i enable logging for weasyprint.

> Failed to load image at "<url-of-my-image>" (Pixbuf error: Unrecognized image file format)

I know my issue but i don't know how to solve it in respect to weayprint. My issue is the image is served with non trusted certificate. so it's an ssl issue and i am not sure how can i disable ssl check in weasyprint
