### ISSUE TITLE
Adding fuzz testing and integrating with Google/OSS-Fuzz

### ISSUE THREAD

**Issue by jesslatimer** [Kozea/WeasyPrint#1821]
Hi,

I would like to help keep WeasyPrint running smoothly by adding fuzz testing and integrating it with google/oss-fuzz. In case you are not familiar with fuzz testing, briefly, it is an additional layer of testing that throws many different scenarios at the code to ensure it can handle various inputs as well as find and test those hard-to-reach and unexpected bugs (the inputs evolve each time with the goal to reach the most lines of code). [Wikipedia ](https://en.wikipedia.org/wiki/Fuzzing)explains it nicely:

>In programming and software development, fuzzing or fuzz testing is an automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program. The program is then monitored for exceptions such as crashes, failing built-in code assertions, or potential memory leaks.

Google offers a free, continuous fuzzing service called OSS-fuzz. If WeasyPrint is integrated into oss-fuzz, the fuzz tests under WeasyPrint will be built and then run once a day, to search for bugs and vulnerabilities. This service can be integrated with the CI for WeasyPrint so that the fuzz tests are run for 10min or so for every pull request, preventing buggy code from being merged.

I've opened up a pull request to add a basic fuzz-testing harness here https://github.com/Kozea/WeasyPrint/pull/1820. 
If you are keen on adding WeasyPoint to oss-fuzz I'd be happy to champion the integration :)

**Comment by liZe** [comment]
Hi!

Thanks for your contribution.

Unfortunately, we’re not really convinced by this proposition, for 2 main reasons.

1. Fuzzy testing can definitely help to find unexpected behaviors, but it can take a lot of time to configure correctly, maintain the tests, detect false positives, etc. We’re currently working on another solution to improve our testing coverage: use the W3C test suite, with more than 10,000 tests for CSS only. Both can be complementary, but we’ll stick with the test suite right now.

2. We would like to avoid depending on external tools when possible. We already rely on GitHub for important steps of our workflow, and depending on extra Google services is not on our roadmap 😁.
