### ISSUE TITLE
Is it possible to prevent page-break inside div and let it overflow?

### ISSUE THREAD

**Issue by survtur** [Kozea/WeasyPrint#1826]
Here is a code. I hoped that `break-inside: avoid` would help me. It does not. Image rendered image and is below. 
```html
<html lang="en">
    <head>
        <style>
        body {margin: 0; font-size: 4mm}
        @page {size: 100mm 100mm; margin: 10mm 30mm 50mm 30mm}
        </style>
    </head>
    <body>
        <div style="break-inside: avoid; background-color: lightpink">
           Lorem ipsum dolor sit amet, consectetur adipisicing elit.
           Accusantium blanditiis consequatur cum, doloremque excepturi
           perspiciatis possimus quos ratione sed voluptas voluptate!
        </div>
      
    </body>
</html>
```

![image](https://user-images.githubusercontent.com/4893428/222962801-4e9d21bc-c161-4d06-b1b5-002ec549cbd7.png)

Is there a way to prevent page break inside div and allow overflow. Even if it will not fit on page.

**Comment by liZe** [comment]
Hi!

`break-inside: avoid` doesn’t prevent page breaks, it only avoids them when it’s possible to do so without overflowing.

One "solution" is to use something like `margin-top: -100rem; transform: translate(0, 100rem)`. The negative margin puts it far away from the bottom margin, and the translation displays it at the right place (without changing the layout, and thus without breaking the block).
