### ISSUE TITLE
Empty <em/> tag leaks italics style to all following text

### ISSUE THREAD

**Issue by eudoxos** [Kozea/WeasyPrint#1830]
I have this MWE which contains an empty `<em/>` at one point, making all subsequent text (even in parent elements) italicized. It happened by an accident (I would not use useless `<em/>` normally) but might be worth attention. Thanks for WeasyPrint :)

```html
<html>
<body>
  <dl>
    <dt>Foo 1</dt>
      <dd>Empty &lt;em&gt; follows: <em/> this should be upright again..?</dd>
    <dt>Foo 2 (should be upright)</dt>
      <dd>This should be upright.</dd>
  </dl>
</body>
```
![image](https://user-images.githubusercontent.com/1029876/223392749-71fbe47a-f3e8-43d1-9799-dc7426ff38e6.png)

**Comment by liZe** [comment]
Hi!

Other browsers do this too, so I suppose that WeasyPrint correctly follows what’s in the HTML specification (and I don’t want to know why it does this 😁).

**Comment by liZe** [comment]
> I don’t want to know why it does this

I actually do want to know.

According to [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags):

>Self-closing tags (`<tag />`) do not exist in HTML. If a trailing / (slash) character is present in the start tag of an HTML element, HTML parsers ignore that slash character.

So `<em/>` is seen as `<em>`, that’s why the text is in italic.
