### ISSUE TITLE
Weasyprint emits "Invalid or unsupported selector" warning on import

### ISSUE THREAD

**Issue by iamlikeme** [Kozea/WeasyPrint#1839]
Repro:

```python
import logging
logging.basicConfig(level=logging.WARNING)

import weasyprint
```

Output:

```
WARNING:weasyprint:Invalid or unsupported selector 'select:not(:has(option[selected])) option:first-of-type,
option[selected]:not(option[selected] ~ option[selected]) ', ('Unknown pseudo-class', 'has')
```

The warning is triggered by [this line](https://github.com/Kozea/WeasyPrint/blob/ffda5be946f3d1dc376c67eb81dd5f0b957110d8/weasyprint/css/html5_ua.css#L380), added in 02369a909ab63a80ae29c6468baee3f6042d92ac.

Unfortunately I don't know how to fix this issue and cannot submit a patch :slightly_frowning_face:.

**Comment by liZe** [comment]
Hi!

The `:has` selector is supported in cssselect2 since [0.7.0](https://doc.courtbouillon.org/cssselect2/latest/changelog.html#version-0-7-0). Maybe you don’t have this version installed?

**Comment by iamlikeme** [comment]
> The :has selector is supported in cssselect2 since [0.7.0](https://doc.courtbouillon.org/cssselect2/latest/changelog.html#version-0-7-0). Maybe you don’t have this version installed?

Indeed, that was the problem. Thank you :slightly_smiling_face: 

Is there some reason that weasyprint depends on `cssselect2 >=0.1` and not `cssselect2 >=0.7`?

**Comment by liZe** [comment]
> Is there some reason that weasyprint depends on `cssselect2 >=0.1` and not `cssselect2 >=0.7`?

The Python API didn’t change, so there’s no reason to technically force users to use a more recent version. Of course, you’ll have unfixed bugs and missing features if you use an older version!
