### ISSUE TITLE
1px gray border around page

### ISSUE THREAD

**Issue by floek** [Kozea/WeasyPrint#1849]
Like in #1316, I'm using weasyprint to create labels. I'v discovered a strange 1px gray border arround the pages. My attempts to remove it using pixels instead od milimeters or setting css shadow parameters were unsuccessful. Here is a minimal example and a screenshot of the result:
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <style>
        @page {
            size: A6;
            margin: 0;
        }
        div {
            height: 148mm;
        }
    </style>
</head>
<body>
    <div>
    </div>
</body>
</html>
```

<img width="612" alt="image" src="https://user-images.githubusercontent.com/5064958/227759522-927ef591-c1ed-47f7-aaac-1cd44e1fb835.png">

Any ideas?

Thanks,
floek

**Comment by liZe** [comment]
Hi!

Your example doesn’t create a border for me. Could you please share a PDF with a border, and the HTML/CSS source that created it?

**Comment by floek** [comment]
[border_debug.pdf](https://github.com/Kozea/WeasyPrint/files/11071052/border_debug.pdf)
 here is the PDF for code above. You need to zoom in to a very high level to see the border. But it is there...

**Comment by liZe** [comment]
I’m sorry but I can’t see it, even with the maximum zoom level, with pdf.js (in Firefox or Chrome), with poppler (used by many Linux PDF readers), or when converting the PDF into an image with GhostScript.

Which PDF reader do you use? Isn’t it a display artifact?

**Comment by floek** [comment]
Interesting, indeed it seems to be an issue with macOS preview and safari. I can't see the border in Firefox, Chrome or Adobe Reader...

**Comment by liZe** [comment]
> Interesting, indeed it seems to be an issue with macOS preview and safari.

Good luck! If you open a bug on Apple’s bug tracker, you can add the link in a comment here, so that other users can follow it in the future.
