### ISSUE TITLE
base64 image data

### ISSUE THREAD

**Issue by bb4L** [Kozea/WeasyPrint#1851]
I'm using django and try to add an image to a pdf by passing in the base64 data:

` <img alt="not-working" src="data:image/png;base64,{{image_data}}" /> `

but i always get the alt text, if i directly return the html response i get the image.

weasyprint 57.1

and the dependencies from [here](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#ubuntu-20-04) are installed as well as the `pango1.0-tools` package

**Comment by liZe** [comment]
Hi!

Could you please share an example of `image_data` you use? A common problem is to have something that’s not a string (for example a bytestring), resulting in a buggy base64 string.

**Comment by bb4L** [comment]
my bad there was a wrong `url_fetcher` defined
