### ISSUE TITLE
GCP Cloud Run installation

### ISSUE THREAD

**Issue by YDA93** [Kozea/WeasyPrint#1861]
Is it possible to install weasyprint using Google Cloud Platform - Cloud run?
That is their default docker file:

```
FROM python:3.10-slim

ENV APP_HOME /app
WORKDIR $APP_HOME

ENV PYTHONUNBUFFERED 1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD exec gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 project.wsgi:application
```

**Comment by grewn0uille** [comment]
Hello @YDA93,
The Docker image `python:3.10-slim` [is based on Debian Bullseye](https://github.com/docker-library/python/blob/4c86fbef4c546a65e372c9bc8c27b8c17bfe42fd/3.10/slim-bullseye/Dockerfile) (11).
You can install WeasyPrint [using the package manager of the distribution](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#linux) or, if you want a more recent version, you can install it [using pip](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#debian-11).

**Comment by YDA93** [comment]
@grewn0uille Thank you!
