### ISSUE TITLE
Alternative way to do "write_png" in WeasyPrint v58

### ISSUE THREAD

**Issue by whaoran** [Kozea/WeasyPrint#1863]
Hi, 
I used to use WeasyPrint v52 with "write_png" to render the png image of "WeasyPrint.Document".
Recently I am trying to upgrade to new version of WeasyPrint but I found "write_png" is removed and I can't find any clues in documents.
Could you tell me an alternative way to do "write_png" in WeasyPrint v58 or higher version?

Thank you so much!

**Comment by SummersRA** [comment]
Hi,

Please refer to issue https://github.com/Kozea/WeasyPrint/issues/1857 for an explanation and suggestion.

**Comment by whaoran** [comment]
Thanks a lot! @SummersRA 

One more question about new features, have we support writing-mode=vertical-rl or vertical-rl in WeasyPrint v58 or higher version now?

**Comment by whaoran** [comment]
Many thanks for your support! @SummersRA
