### ISSUE TITLE
Problem rendering SVG image containing <symbol> and <use>

### ISSUE THREAD

**Issue by anselmlingnau** [Kozea/WeasyPrint#1864]
I have a simple HTML file which embeds an SVG image like so:
```
<!DOCTYPE html>
<html>
  <body>
    <img src="file:///tmp/pic.svg" />
  </body>
</html>
```
The SVG file basically looks like
```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="…" version="1.1">
<defs>
<g>
<symbol overflow="visible" id="glyph0-0">
<path style="stroke:none;" d=" … stuff … " />
</symbol>
</g>
</defs>
<g id="surface1">
<path style="… stuff …" d="… more stuff …" />
<g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
  <use xlink:href="#glyph0-0" x="14.7" y="45.82" />
</g>
</g>
</svg>
```
(for the record, it derives from `pdf2svg` output, but I edited it down to make it smaller).

When I render the HTML file to PDF using Weasyprint 58.1, the symbol doesn't show up, although the hard-coded `<path>`  above it does. When I change the SVG file so the actual `<path>` element from the `<symbol>` definition appears in place of the `<use>` (with a suitable `transform` on the `<path>` to move it to the appropriate location) , it looks fine. Is there something wrong with the `<use>` feature?

Here's what the SVG file looks like (as rendered by Github). When I run this through Weasyprint as above, the `THE` does not appear in the PDF output.

![pic](https://user-images.githubusercontent.com/23383976/232813400-f21e29bc-7946-4001-b458-3f74b0817c7e.svg)

I'm attaching the files in question.
[weasyprint-use-issue.zip](https://github.com/Kozea/WeasyPrint/files/11262984/weasyprint-use-issue.zip)

**Comment by liZe** [comment]
Hi,

Thanks for the report! It’s fixed, don’t hesitate to test and give some feedback.

**Comment by anselmlingnau** [comment]
Wow, that was fast. It seems to work now (using the ff869274 commit). Thank you!
