### ISSUE TITLE
Pdf attachment internal links

### ISSUE THREAD

**Issue by foxtrot-dfm1** [Kozea/WeasyPrint#1865]
Hello, how can I add the link to attached file?

**Comment by grewn0uille** [comment]
Hello,

To attached a file, you can use the `a` element. 
For example: 
```html
<a href="path/to/the/file" rel="attachment">some text</a>

**Comment by summersz** [comment]
Yes, depending on if the pdf reader supports it. It doesn’t work with the chrome pdf reader but does with Firefox (single click) and Acrobat (double click).

**Comment by foxtrot-dfm1** [comment]
> Yes, if the pdf reader supports it. It should work with chromium browsers and Firefox and also acrobat.

Thanks :)
