### ISSUE TITLE
Image not appearing in PDF

### ISSUE THREAD

**Issue by murraycollingwood** [Kozea/WeasyPrint#1879]
Hi folks

Hoping you can help.
I have a couple of images included in my HTML.

The first one has a URL that is verified before the image is downloaded.  This one doesn't include my image.
`<img src='https://sobs/ui/fap.php?fap=WyJub3RpY2VBdHRhY2htZW50IiwxNTU3OCwiLi5cL3VwbG9hZHNcLzE1XC9ub3RpY2VzXC8yMDIzXC8wNVwvMTU1NzhfMTY4NDExMzc4Ml8xLmdpZiJd' style='max-width:600px;' />
`
This second one has a URL that just points directly to an image.  This one works includes the image in the PDF, no problem.
`<img src='https://sobs/pix/notices/dash.gif' style='max-width:600px;' />
`
What do I need to do to get my first URL to work with WeasyPrint?

Cheers
Murray

PS Neither of these URLs will work for you as they are only valid on my local machine.

**Comment by liZe** [comment]
Hi,

With no access to the URLs it will be hard to help, but I can try!

The first step to know what’s wrong is to read logs. You get warnings in the console if you use the command-line interface, or you can [store them in a file](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#logging) if you use WeasyPrint as a Python library. You’ll probably get an error if your image can’t be donwloaded!

**Comment by murraycollingwood** [comment]
> Hi,
> 
> With no access to the URLs it will be hard to help, but I can try!
> 
> The first step to know what’s wrong is to read logs. You get warnings in the console if you use the command-line interface, or you can [store them in a file](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#logging) if you use WeasyPrint as a Python library. You’ll probably get an error if your image can’t be donwloaded!

Hi liZe
Both URLs are working perfectly in a web browser.  
I believe the format of the first URL is causing WeasyPrint an issue as it doesn't have any recognisable image extension in the filename (at a guess).  I'm just trying to confirm why that image wouldn't work.

Here are a couple of real URLs as examples you can play with.
First a real image that will work: 
`https://sobs.com.au/docs/pix/simple-example.png
`
Second, a secure image retrieval: 
`https://sobs.com.au/ui/fap.php?fap=WyJub3RpY2VBdHRhY2htZW50Iiw3NjI5MjksIi4uXC91cGxvYWRzXC8xNVwvbm90aWNlc1wvMjAyM1wvMDVcLzc2MjkyOV8xNjg0MTQwOTE5XzEuanBnIl0
`

I guess everybody will look at these images just to see what they are... lots of surprises... but the second one is ignored by WeasyPrint when generating a PDF.  

Now we have a real example.

Cheers
Murray

**Comment by liZe** [comment]
I’ve created a HTML document with only:
```html
<img src="https://sobs.com.au/ui/fap.php?fap=WyJub3RpY2VBdHRhY2htZW50Iiw3NjI5MjksIi4uXC91cGxvYWRzXC8xNVwvbm90aWNlc1wvMjAyM1wvMDVcLzc2MjkyOV8xNjg0MTQwOTE5XzEuanBnIl0" style="max-width:600px">
```

With WeasyPrint launched from the command line, it works, without any warning or error.

**Comment by murraycollingwood** [comment]
Hmmm, tested here with the command line, it also works.  I've been working with php-weasyprint and now I'm wondering if that is the problem.
Thanks for your help @liZe
