### ISSUE TITLE
<p align="right" style="font-size:30px">Text</p> ignores the align

### ISSUE THREAD

**Issue by Wissperwind** [Kozea/WeasyPrint#1888]
Hi,

I have a problem. In the `<p>` tag the align option is ignored.
The Text is aligned left. But if I open the HTML in any browser the text is correctly aligned right.

**Comment by grewn0uille** [comment]
Hello!

`align="right"` is a presentational hint and it’s not supported by default. You can use the `--presentational-hints` parameter to enable it.

**Comment by Wissperwind** [comment]
Tank you for the hint. I'll try that.
