### ISSUE TITLE
white-space: nowrap still wraps on hyphens

### ISSUE THREAD

**Issue by Smylers** [Kozea/WeasyPrint#189]
With `white-space: nowrap`, WeasyPrint will still wrap text on a hyphen (technically U+2D hyphen-minus) even when it won't wrap on a space at that point.

See: http://www.stripey.com/demo/weasyprint/nowrap_hyphen.html, which WeasyPrint (version 0.21) renders as: http://www.stripey.com/demo/weasyprint/nowrap_hyphen.pdf

Obviously hyphens aren't white space, but it doesn't seem helpful to wrap at this point. Unfortunately the stable CSS2.1 spec makes no mention of what the `white-space` property should do with wrapping characters that aren't white space: http://www.w3.org/TR/CSS2/text.html#white-space-prop

However the CSS3 editors' draft makes clear that `white-space` governs all ‘soft wrap opportunities’, which includes punctuation characters where wrapping can occur: http://dev.w3.org/csswg/css-text/#white-space-property

**Comment by Smylers** [comment]
> rather than just replace spaces with no-break spaces as (IIRC) we do now.

In that case, another possible way of getting this working would be to additionally massage the input text to Pango by inserting U+2060 word joiners just before and after each hyphen or slash character.

That is actually what I'm now doing in the HTML template for affected text, though obviously that's a layering violation, since it means that the HTML has to know which CSS rules will be applied where.

**Comment by SirNeuman** [comment]
So is there any simple workaround for this problem currently? In my css i have white-space: nowrap, which works for spaces but not for hyphens.

**Comment by Smylers** [comment]
> So is there any simple workaround for this problem currently?

Its simplicity is subjective, but the workaround I mention above is to process text that's going to be put in `nowrap` containers with:

````perl
$text =~ s!([/-])!\N{WORD JOINER}$1\N{WORD JOINER}!g;
````

I happen to be using Perl, but the underlying idea should translate straightforwardly to other text-processing languages.

**Comment by SirNeuman** [comment]
Ahh ok. Sorry, by simple i meant either html or css way of doing it. I'll have to find the python equivalent of this then. I'm not too good with regex stuff, but it's always satisfying figuring it out.

**Comment by liZe** [comment]
Grouped in #301.

**Comment by liZe** [comment]
Even without rewriting the line breaking algorithm, this bug is fixed in a quite clean way.
