### ISSUE TITLE
Page counter not working from document

### ISSUE THREAD

**Issue by oscardimanno** [Kozea/WeasyPrint#1896]
Hello,
I'm trying to get page counter from the document but just not working.
I've seen that this bug was resolved in a previous issue but isn't working again.
#91 

`                            <div class="value">
                                <span style="content: counter(page)"></span>
                                <span>of</span>
                                <span style="content: counter(pages)"></span>
                            </div>`

Why isn't working again?

**Comment by liZe** [comment]
Hi!

The problem you have is caused by #1521: you can only use `content` in `::after` or `::before` pseudo-elements.

Here is a working example:
```html
<style>
.page::before { content: counter(page) }
.pages::before { content: counter(pages) }
</style>
<div class="value"> <span class="page"></span> <span>of</span> <span class="pages"></span> </div>
```

**Comment by oscardimanno** [comment]
Thanks. Resolved it.
I close 'cause it's duplicated.
