### ISSUE TITLE
Problem with named pages and out of normal page flow elements

### ISSUE THREAD

**Issue by MWedl** [Kozea/WeasyPrint#1897]
## Problem

When rendering following HTML with weasyprint, the CSS for `named-page` is not applied on the first page. The first page is blue (from the default `@page` rule), but it contains content of the named page.

```html
<html>
    <head>
        <style>
            #header { position: running(header); }
            #watermark { position: fixed; top: 10cm; left: 5cm; font-size: 30pt; }
            
            @page {
                size: A4;
                background-color: blue;
                @top-center { content: element(header); }
            }
            
            #named-page { page: named-page; }
            @page named-page { background-color: red; }
            
            .pagebreak { break-after: page; }
        </style>
    </head>
    <body>
        <div id="header">HEADER</div>
        <div id="watermark">WATERMARK</div>
        <div id="named-page">
            NAMED PAGE 1
            <div class="pagebreak"></div>
            NAMED PAGE 2
        </div>
    </body>
</html>
```

![Screenshot_20230620_090329](https://github.com/Kozea/WeasyPrint/assets/29510012/7eefeb2c-30c6-4e49-be9d-a6e8d3327d5c)

You can get the expected result (both pages in red) by moving the HTML elements for the header and watermark below the named page. However, I think this is unexpected behavior.

## Suggestion

I think the problem is in calculating the start page value of the first page. Currently the start page value of the first element (`#header`) is used which results in an unnamed page. I think weasyprint should exclude elements that are out of the normal page flow from the start/end page value calculation (such as `position: running()` and `position: fixed`).

This should be compliant with the CSS specification for `page` (https://drafts.csswg.org/css-page-3/#propdef-page):

> 2. Next, a start [page](https://drafts.csswg.org/css-page-3/#propdef-page) value and end [page](https://drafts.csswg.org/css-page-3/#propdef-page) value is determined for each box as the value (if any) propagated from its first or last child box (respectively), else the used value on the box itself. A child propagates its own [start](https://drafts.csswg.org/css-page-3/#start-page-value) or [end page value](https://drafts.csswg.org/css-page-3/#end-page-value) if and only if the [page](https://drafts.csswg.org/css-page-3/#propdef-page) property applies to it.
>
> > NOTE: A first or last child _box_ is not always generated by a first or last child _element_. For example, an element could only have a previous sibling with 'display: none' which does not generate any box.

What is your opinion on that?

**Comment by liZe** [comment]
Hi!

According to the specification, the 'page' names should be inherited from:
- elements that create a box, AND
- elements that allow 'page' to be applied to it, ie. [boxes that create class A break points](https://drafts.csswg.org/css-page-3/#propdef-page).

The second point is slightly different from "elements in the flow" (because floats create class A break points for exemple even if they’re not in the flow), but your overall diagnostic seems to be the right one.

The code to fix this is probably in the `page_values` methods in `boxes.py` and in the places where they’re called.
