### ISSUE TITLE
Nested elements subvert white-space: nowrap

### ISSUE THREAD

**Issue by Smylers** [Kozea/WeasyPrint#190]
With `white-space: nowrap`, WeasyPrint still allows wrapping at tag boundaries for nested elements within the text.

Demo: http://www.stripey.com/demo/weasyprint/nowrap_elements.html, which WeasyPrint (version 0.21) renders as: http://www.stripey.com/demo/weasyprint/nowrap_elements.pdf

@liZe already mentioned this in a comment to Issue #176, but it seemed worth having a separate number for this, so it's documented as a known issue.

**Comment by liZe** [comment]
Grouped in #301.

**Comment by liZe** [comment]
Fixed by closing #301.
