### ISSUE TITLE
Data in filled forms is shown as blank when you print the pdf, but filled when you view on computer

### ISSUE THREAD

**Issue by Crowdedlight** [Kozea/WeasyPrint#1903]
When generating PDF having form fields with weasyprint and then filled using Adobe Reader DC (optionally signed), the filled data is saved and shown when viewing the document on the computer, but when printing it all form fields are blank as if they have never been filled. 

Taking the same document and making a new form field in PDF Suite or Acrobat Pro, then filling it, and that one field then works. It feels like weasyprint need to set an attribute or something on the generated form fields, to allow the data in them to be printed. 

I have tried to print both "as image" and normally and none of them includes the form data. I have selected the print option to include "document and form data".

The pdf on the computer show:
![billede](https://github.com/Kozea/WeasyPrint/assets/7889925/0878629f-d158-4298-bd67-600db4ed779f)

And the output when saved, signed and printed to file with "Microsoft print to file":
![billede](https://github.com/Kozea/WeasyPrint/assets/7889925/13375674-3123-4a30-a65b-a8b872f2cecf)

Reading the adobe documentation it seems like there are some options for form fields: 
![billede](https://github.com/Kozea/WeasyPrint/assets/7889925/9a8f5e5b-71b0-45c8-a8b1-0645c90ba3f1)

But I am not sure what the option is coded to at this point and didn't see any obvious way to tell weasyprint what setting to use? 
I am trying to make a custom finisher to see if I could detect fields that were form inputs and explicitly set that configuration to ``visible``, but I am not well versed in the PDF specification, so I am not sure how to detect form fields and set this specific option from the given ``pydyf.PDF`` object.

**Comment by liZe** [comment]
Hi!

Thanks for this bug report.

> Reading the adobe documentation it seems like there are some options for form fields:

Where did you find this option? I can’t find this sentence in the specification.

**Comment by Crowdedlight** [comment]
I read it on the adobe website: https://helpx.adobe.com/acrobat/using/pdf-form-field-properties.html 
A bit down on that page under "General tab for form field properties". 

In hindsight this might be acrobat specific? I didn't find it when searching in the specification: https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf 

I did find this in Table 22. It mentions some flags needed to be allowed for print. 
![billede](https://github.com/Kozea/WeasyPrint/assets/7889925/67647e36-15b8-436e-858d-9bdf6b4e6d9a)

Table 165 in the specification does mention bits/flags set for annotations and it seems like they have the print flags option. But unsure if that also applies to widgets? 
![billede](https://github.com/Kozea/WeasyPrint/assets/7889925/51b6d76b-bea0-4738-99d8-5f367b59862c)

Is there a way to see the raw data of a pdf to compare it? As I got one manually created in PDF Suite that can print with the entered form data, and one from weasyprint that makes them blank on print. But haven't found an easy way to compare the raw data between them to see what the difference is in those fields.

**Comment by liZe** [comment]
> Is there a way to see the raw data of a pdf to compare it? As I got one manually created in PDF Suite that can print with the entered form data, and one from weasyprint that makes them blank on print. But haven't found an easy way to compare the raw data between them to see what the difference is in those fields.

It’s a bit complex to read PDF because some parts are compressed, but if you can generate a very small and simple document that includes a printable field, we can probably find the flag we need to set.

**Comment by Crowdedlight** [comment]
I made a blank pdf that only has a single text field as form input. One made with PDF Suite that shows the data when printing, and one made with weasyprint that doesn't show the data when printing. 

PDF Suite, that works:
[form_debug_pdfsuite_printing.pdf](https://github.com/Kozea/WeasyPrint/files/11990457/form_debug_pdfsuite_printing.pdf)

Weasyprint:
[form_debug_weasyprint_not_printing.pdf](https://github.com/Kozea/WeasyPrint/files/11990458/form_debug_weasyprint_not_printing.pdf)

**Comment by liZe** [comment]
Thanks!

You were right, that’s fixed by setting the "Print" flag.

**Comment by Crowdedlight** [comment]
Ah, perfect. Thank you very much for the very rapid fix and response! :)
