### ISSUE TITLE
HTML to PDF conversion cuts off table content towards right

### ISSUE THREAD

**Issue by zorro786** [Kozea/WeasyPrint#1905]
Hi!

I am switching over from `wkhtmltopdf` to `weasyprint` and on using the same HTML with `presentational_hints` True, the content of tables in PDF is cut off and normal text paragraphs are wrapped around with fewer words on each line which wasn't the case with PDF generated by `wkhtmltopdf`. The page sizes are same. I have tried several things like zoom and other CSS properties to adjust margins etc. but none have any effect. Following is my style FWIW:

```
<style>
      @page {
        size: A4; /* Adjust the page size as needed */
        margin: 20mm; /* Adjust the margins as needed */
      }
      {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }

      td, th {
        padding: 8px;
        font-size:12px;
      }

      tr:nth-child(even){background-color: #f2f2f2;}

      tr:hover {background-color: #ddd;}

      th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4f86f7;
        color: white;
      }

      img.logo {
        vertical-align: middle;
      }

      .break-after {
        page-break-after: always;
      }

      .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-family: sans-serif;
        min-width: 400px;
        /*box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);*/
      }

      .styled-table thead tr {
        background-color: #4f86f7;
        color: #ffffff;
        text-align: left;
      }

      .styled-table th,
        .styled-table td {
          padding: 12px 15px;
      }

      .styled-table tbody tr {
        border-bottom: 1px solid #dddddd;
      }

      .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
      }

      .styled-table tbody tr:last-of-type {
        border-bottom: 2px solid #4f86f7;
      }

      table th:first-child{
        border-radius:10px 0 0 0;
      }

      table th:last-child{
        border-radius:0 10px 0 0;
      }
    </style>
    
```

I have seen a few folks encountering similar issues on stackoverflow but none of them seemed to have found an answer. Any pointers appreciated @liZe

**Comment by liZe** [comment]
Hi!

Thanks for the bug report.

Could you please share a whole HTML+CSS sample so that we can easily reproduce your problem? You can send a mail if you can’t share some information publicly.

**Comment by zorro786** [comment]
> Hi!
> 
> Thanks for the bug report.
> 
> Could you please share a whole HTML+CSS sample so that we can easily reproduce your problem? You can send a mail if you can’t share some information publicly.

Thank you for the quick response. I have shared it with you on your email address.

**Comment by liZe** [comment]
The problem you have is that your tables are too large, there’s no way to get narrower tables without violating the CSS rules. You can get a correct rendering using this for example:

```css
@page {
  margin: 10mm;
}

.styled-table th,
.styled-table td {
  font-size: 8px;
  padding: 4px 6px;
}
```

You’ll also probably want to avoid page breaks in rows:

```css
tr {
  break-inside: avoid;
}
```

I don’t know what wkhtmltopdf does to avoid this, but you can have a hint by checking the differences between the two PDF.

Another solution is to use a landscape page size, that’s often a good alternative for large tables.

**Comment by zorro786** [comment]
Thank you for the suggestion @liZe. It does fix some tables but not all. But I get the idea on what needs to change in CSS. I am not an expert in HTML/CSS but it looks like `wkhtmltopdf` has some way of "shrink to fit width" on a given page. If you see the PDF generated with `wkhtmltopdf` (I have shared it with you) and compare it with `weasyprint`, all the content including text outside of tables appear on similar width as they do in HTML rendering. Does `weasyprint` support any such configuration?

**Comment by liZe** [comment]
> Does `weasyprint` support any such configuration?

No, it doesn’t. WebKit is able to scale down the content, just as it does on a mobile browser for non-responsive websites, as a dirty (and useful) fallback solution. But there’s nothing like this in WeasyPrint, that’s more aimed to documents specifically designed for pagination.

If your documents always include the same tables, using a smaller font face and cell padding until everything fits is probably the best solution. And if the text is too small, then it’s probably time to remove some of the columns, or use another paper size :smile:.

**Comment by liZe** [comment]
> WebKit is able to scale down the content, just as it does on a mobile browser for non-responsive websites, as a dirty (and useful) fallback solution.

Looking more closely at your document, I can see that some tables overflow too with wkhtmltopdf. So I suspect that there’s something in wkhtmltopdf to change the size of the CSS pixel for all tables, but it doesn’t adapt automatically for each table either.
