### ISSUE TITLE
Balance columns before "column-span: all"

### ISSUE THREAD

**Issue by pocomane** [Kozea/WeasyPrint#1914]
Is the [column-span](https://www.w3.org/TR/css-multicol-1/#column-span) attribute correctly handled? In my experimentation it seems just ignored, but maybe I am missing something. I used it as a property of an img tag.

**Comment by liZe** [comment]
Hi!

Is your problem related to #980? `column-span` currently only works with direct clients.

**Comment by pocomane** [comment]
Sorry, I did a search in the issues already open, but I did not find it. However I am not sure it is related, since my image is a direct child of  the only multi-column element (body). However I will make some test to be sure it is not related to that issue. I will try to write a minimal example that reassembles my scenario.

**Comment by liZe** [comment]
Then maybe you forgot to set `display: block` on your image ([`column-span` only works on block-level elements](https://www.w3.org/TR/css-multicol-1/#column-span))? A simple example works well for me.

**Comment by pocomane** [comment]
There was a `<p>` tag I forgot about, so what I saw was the effect of #980 . However I am not still able to got a good result:

![image](https://github.com/Kozea/WeasyPrint/assets/14974494/20019c54-31b5-4d7c-a162-43fe9896ddd3)

Why the white-space in the top-right section? If I open the same file with firefox I got that area filled by text, as I would expect. The relevant tags are:

`<body style="column-count:2;column-fill:auto;">`

It contains just a long lorem ipsum text, then:

`<img src="https://picsum.photos/536/354" style="display:block;column-span:all;"></img>`

**Comment by liZe** [comment]
Could you please share a full HTML/CSS sample, so that we can easily reproduce your problem?

**Comment by pocomane** [comment]
[test.html.zip](https://github.com/Kozea/WeasyPrint/files/12071944/test.html.zip)

**Comment by liZe** [comment]
Why do you use `column-fill: auto`? The default value is `balance` and balances the content of the columns, that’s probably what you want. `auto` is designed to fill the first columns sequentially, and to be honest I don’t know what it’s supposed to do with `column-span` on paged media. If you find any evidence in the specification that the current behaviour is wrong, we can let this issue open to solve the problem, but for now I tend to think that it’s an undefined behaviour and that WeasyPrint is not "wrong" here.

**Comment by pocomane** [comment]
I used the `column-fill:auto` because I  want that the last column be fully filled before passing to the next one [1]

However I do not know if the CSS specification mandates a behavior or not. The only things I can say against the weasyprint output are:

- I do not like it (not very important)
- I can not see any logic in it (still not very important, as long as someone can)
- Both chrome and firefox behave differently [2]

[1] In other words, I like this:

![Screenshot from 2023-07-19 14-56-04](https://github.com/Kozea/WeasyPrint/assets/14974494/868689f6-c369-4b25-8681-8bb5c5df957f)

and I dislike this:

![Screenshot from 2023-07-19 14-55-42](https://github.com/Kozea/WeasyPrint/assets/14974494/3c41c681-5ee1-4fe5-a8ea-3a5fadf57aa3)

[2] Screenshot from firefox:

![Screenshot from 2023-07-19 14-53-02](https://github.com/Kozea/WeasyPrint/assets/14974494/c42189de-1e5b-4dc9-822d-215aabae89f9)

**Comment by pocomane** [comment]
> I don’t say that Firefox and Chrome are right or wrong,

Me neither. I spoke about the two browsers just as a hint that MAYBE a specification exists, and it demands something like that output. But I agree with you that it is not enough to start changing stuff inside WeasyPrint.

> The next step is thus to find in it what we exactly have to do.

100% agree also on this but I was not able to find the answer on the W3C specification, so for now I will just switch to the `balanced` property.

**Comment by liZe** [comment]
The answer is in the [`column-span: all` definition](https://www.w3.org/TR/css-multicol-1/#valdef-column-span-all):

>Content in the normal flow that appears before the element is automatically balanced across all columns in the immediately preceding [multi-column line](https://www.w3.org/TR/css-multicol-1/#multi-column-line) before the element appears […]
