### ISSUE TITLE
Is it possible to use one style for start of text and modified style for its continuation on next pages?

### ISSUE THREAD

**Issue by survtur** [Kozea/WeasyPrint#1920]
For example some text block starts at unknown page of document. It is possible to make it has one style on that page and another styles on next pages where it is continued.

In the example below first page always blue, while continuations are red.
![image](https://github.com/Kozea/WeasyPrint/assets/4893428/2aeb83d1-3078-4c41-bb31-a2621e18ac31)

**Comment by liZe** [comment]
Unfortunately, I’m pretty sure that it’s not possible in CSS :/.

I’m closing the issue, as there’s nothing we can do in WeasyPrint about that. If you really want to have this feature, it’s possible to open an issue in [w3c/csswg-drafts](https://github.com/w3c/csswg-drafts/issues) and see if they think that it’s useful!
