### ISSUE TITLE
Footnotes & Page Breaks

### ISSUE THREAD

**Issue by andrewerlanger** [Kozea/WeasyPrint#1924]
Hi Team! Thanks as always for the amazing work you're doing with WeasyPrint, it remains a real joy to work with :)

I've run into what I think may be a bug that relates to footnotes and page breaks:

- Let's say I have a text element with footnotes, which should be rendered on page 1.
- If the vertical space required for the `text element + footnotes` is too large to fit on page 1, both the text element _and_ the footnotes are displayed on page 2 (which is fine!).
- _But_, the rest of the content on page 1 seems to be displayed as if the footnotes container _was_ actually rendered on page 1 (even though it's been moved to page 2). As a result, I have page breaks in unexpected places and, more generally, some unanticipated positioning of elements within the body of the page.

I've added a couple of screenshots to try to demonstrate the above. On the left, there's enough space for the `text element + footnotes` and everything is rendered correctly. On the right, the `text element + footnotes` are moved to the second page, but the remaining content on the first page also breaks early.

![footnotes](https://github.com/Kozea/WeasyPrint/assets/29393156/48158217-94f8-4c1b-9ec1-e2cd601c9393)

My `@footnote` properties, in case this helps, are:

```css
@footnote {
  border-top: 0.5px solid $black20;
  float: bottom;
  margin-top: 16px;
  padding-top: 8px;
  width: 80%;
}
```

**Comment by oshmoun** [comment]
Did you check if you have any `break-*: avoid` properties set in your css? Just to rule out the trivial possibilities :sweat_smile:

**Comment by sahilrl** [comment]
@andrewerlanger 
Could you please try setting footnote-policy to the span.footnote like below.

`span.footnote {
    float: footnote;
    footnote-policy: line;
   }`

https://www.w3.org/TR/css-gcpm-3/#footnote-policy

**Comment by liZe** [comment]
Here’s an example to reproduce:

```html
<style>
  @page { margin: 0.5cm; size: 450px 500px }
  body { margin: 0; font-family: Liberation Sans }
  span { float: footnote }
</style>

<div>
  <p>
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
    This is big. This is big. This is big. This is big. This is big. This is big.
  </p>
  <p style="break-before: avoid">
    This is big<span>I'm the footnote</span>. This is big. This is big. This is big. This is big. This is big.
    This is big<span>I'm the footnote</span>. This is big. This is big. This is big. This is big. This is big.
    This is big<span>I'm the footnote</span>.
  </p>
</div>
```

> Did you check if you have any `break-*: avoid` properties set in your css?

Even with the `break-before: avoid` of the example, it should be possible to find a better way to display this.

> Could you please try setting footnote-policy to line.

Unfortunately, it doesn’t help in this case 😢.

**Comment by liZe** [comment]
> it should be possible to find a better way to display this.

Here’s what Prince does, for example:
![Capture d’écran du 2023-08-05 11-59-46](https://github.com/Kozea/WeasyPrint/assets/952243/0234e480-ced5-4c7c-9f8c-bdfaa50d4bb9)

**Comment by liZe** [comment]
After discussing with Andrew and thinking about a nice solution, we’ve finally agreed that there’s no magical way to handle these cases and that Prince’s rendering is not actually better than WeasyPrint’s in other equivalent cases.

Using more flexible CSS rules is probably the best way to get what we really want!
