### ISSUE TITLE
The CSS attribute "outline" is not handled correctly

### ISSUE THREAD

**Issue by fat-wabbit** [Kozea/WeasyPrint#1928]
Hi all,

In the attached zip file, there's an HTML file and a CSS file. It's very simple: draws two boxes with different colors. If I use the CSS attribute "outline," the boxes are drawn incorrectly (see foon.pdf). If I use the CSS attribute "border," the boxes are drawn correctly  (see foon-02.pdf).

[demo.zip](https://github.com/Kozea/WeasyPrint/files/12208773/demo.zip)
[foon.pdf](https://github.com/Kozea/WeasyPrint/files/12208774/foon.pdf)
[foon-02.pdf](https://github.com/Kozea/WeasyPrint/files/12208775/foon-02.pdf)

**Comment by liZe** [comment]
Hi!

It’s not a bug.

With outlines, the margin of `content-box` goes through the body and shifts the body to the bottom. That’s called [margin collapsing](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing). It’s a bit like if the content box’ margin was applied to the body instead.

Borders prevent margins from collapsing, that’s why you don’t have the same result with borders!
