### ISSUE TITLE
Contribute pip install instructions require surrounding single quotes on macOS/zsh

### ISSUE THREAD

**Issue by alenards** [Kozea/WeasyPrint#1930]
In starting to look at an issue and contribute, I noticed that on macOS Ventura [13.5 (22G74)] & zsh, I had to surround the `.[doc,test]` with single quotes, `'.[doc,test]'`, in order for zsh to send the value through as expected: 

```
# iTerm2
$> venv/bin/pip install -e .[doc,test]
zsh: no matches found: .[doc,test]
```

But `venv/bin/pip install -e '.[doc,test]'` was successful. 

I did confirm that if I run bash, the arguments are passed _totally_ fine and dependencies are installed.  

---- 

I realize that most of the contributors are likely on Linux or familiar with a quirk in argument passing in zsh that they wouldn't run into this. 

If it's not a distraction in the `.rst` docs, I'm up for putting in a pull request to note the zsh issue. 

I'm also fine having this issue opened & closed. I searched the closed issues when I ran into this. I think that's likely what another person would do (and that way the documentation isn't littered with special cases). 

🙇

**Comment by grewn0uille** [comment]
Hello,

As the quoting syntax is POSIX, we totally can update the install instructions with it!

**Comment by alenards** [comment]
@grewn0uille - I submit a PR for that.
