### ISSUE TITLE
Don’t hang with NotoColorEmoji SVG

### ISSUE THREAD

**Issue by pareshbalar** [Kozea/WeasyPrint#1935]
Hi,

I am using the latest version of Weasyprint and using it in docker.

Also, I have installed all the Google fonts into my docker.

Here is my docker file config to install Weasyprint and Google fonts.

```
FROM node:latest

RUN apt-get update && apt-get install -y pipx && \
    pipx install weasyprint && pipx ensurepath && \
    mv /root/.local/bin/* /usr/bin/

RUN wget https://github.com/google/fonts/archive/main.tar.gz -O gf.tar.gz && \
  tar -xf gf.tar.gz && \
  mkdir -p /usr/share/fonts/truetype/google-fonts && \
  find $PWD/fonts-main/ -name "*.ttf" -exec install -m644 {} /usr/share/fonts/truetype/google-fonts/ \; || return 1 && \
  rm -f gf.tar.gz && \
  rm -rf $PWD/fonts-main && \
  rm -rf /var/cache/* && \
  fc-cache -f
```

Here is the Weasyprint version & config
```
WeasyPrint version: 59.0
Python version: 3.11.2
Pydyf version: 0.7.0
Pango version: 15012
```

Here is my HTML content.
```
<!DOCTYPE html>
<html>
  
<head>
    <meta charset="UTF-8">
</head>
  
<body>
  
    <h1>Emoji List:</h1>
  
    <p>Grinning face : <span> 😀 </span> </p>
    <p>Face having tears of joy : <span> 😂 </span> </p>
    <p>Fire : <span> 🔥 </span> </p>
    <p>Thumbs up : <span> 👍 </span> </p>
    <p>Bell : <span> 🔔 </span> </p>
  
</body>
  
</html>
```
When I am trying to convert this HTML file to PDF using Weasyprint, the entire process hangs and I need to restart the server in order to recover it.

Command 
`weasyprint --verbose emoji.html out.pdf`

Output
```
INFO: Step 1 - Fetching and parsing HTML - emoji.html
INFO: Step 3 - Applying CSS
INFO: Step 4 - Creating formatting structure
INFO: Step 5 - Creating layout - Page 1
INFO: Step 6 - Creating PDF
```

It is not creating PDF after step 6.

I tried removing the google fonts from the docker and It is working fine but not printing Emojis.

Please help.

**Comment by pareshbalar** [comment]
Hi,
Up on debugging this issue more, I have found that It's the size of the font file of Emoji is creating an issue.

See the below screenshot.
![image](https://github.com/Kozea/WeasyPrint/assets/10231683/fe6f0039-ff02-40dc-8439-cf66229a4464)

The size of the Google Emoji fonts are 56MB and 23MB and that is causing this issue.

If I remove these two fonts, the system is able to convert HTML To PDF but color emojis are not displayed. It's printing black & white emojis.

Any suggestions on how can we print color emojis in PDF?

**Comment by liZe** [comment]
It’s [a known problem](https://github.com/Kozea/WeasyPrint/issues/1768#issuecomment-1335813008). A quick fix is just to use the version proposed by your distribution: `apt install fonts-noto-color-emoji`.

If it’s OK for you, we can close this issue.

**Comment by liZe** [comment]
(Using this font system-wide actually breaks many applications, so WeasyPrint is not the only one having trouble with this terrible file that includes a stupidly large amount of SVG images…)

**Comment by liZe** [comment]
Actually, there may be a way to fix this. Let’s keep this issue open.

**Comment by liZe** [comment]
OK, that’s fixed.

Here’s the truth: this font is awful. It uses a 14MB SVG (!!!) and lets users automatically parse, change and render it differently for each glyph. It should be possible to do something smart to avoid reparsing this SVG each time a new glyph is found, but I’m not sure that we want to spend some time on this. On my computer, when using this font, even browsers lag when they first try to display an emoji.

So, that’s slow, but it doesn’t crash and renders quite well (when SVG is not too complicated).

If someone reads this thread: just use the raster version of NotoColorEmoji, it’s packaged with your Linux distribution.

**Comment by pareshbalar** [comment]
> It’s [a known problem](https://github.com/Kozea/WeasyPrint/issues/1768#issuecomment-1335813008). A quick fix is just to use the version proposed by your distribution: `apt install fonts-noto-color-emoji`.
> 
> If it’s OK for you, we can close this issue.

Yes, that worked for me.

I have removed Google Noto fonts and have installed them using 
`apt install fonts-noto` 

and that worked :)

Thanks 👍
