### ISSUE TITLE
Homebrew install gives an error "cannot load library 'pangoft2-1.0-0'"

### ISSUE THREAD

**Issue by marcoheleno** [Kozea/WeasyPrint#1939]
I have installed WeasyPrint through Homebrew on macOS 13.5. I also have all Homebrew's packages updated.
When using the WeasyPrint test command: weasyprint https://weasyprint.org /tmp/weasyprint-website.pdf or other command line tests, I get the following error:

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 

-----

Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 5, in <module>
    from weasyprint.__main__ import main
  File "/usr/local/Cellar/weasyprint/59.0/libexec/lib/python3.11/site-packages/weasyprint/__init__.py", line 387, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/weasyprint/59.0/libexec/lib/python3.11/site-packages/weasyprint/css/__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "/usr/local/Cellar/weasyprint/59.0/libexec/lib/python3.11/site-packages/weasyprint/css/computed_values.py", line 11, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/usr/local/Cellar/weasyprint/59.0/libexec/lib/python3.11/site-packages/weasyprint/text/ffi.py", line 441, in <module>
    pangoft2 = _dlopen(
               ^^^^^^^^
  File "/usr/local/Cellar/weasyprint/59.0/libexec/lib/python3.11/site-packages/weasyprint/text/ffi.py", line 417, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/opt/cffi/lib/python3.11/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/opt/cffi/lib/python3.11/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/opt/cffi/lib/python3.11/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pangoft2-1.0-0': dlopen(pangoft2-1.0-0, 0x0002): tried: 'pangoft2-1.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSpangoft2-1.0-0' (no such file), '/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/../../../../../../../../../../../lib/pangoft2-1.0-0' (no such file), '/usr/lib/pangoft2-1.0-0' (no such file, not in dyld cache), 'pangoft2-1.0-0' (no such file), '/usr/local/lib/pangoft2-1.0-0' (no such file), '/usr/lib/pangoft2-1.0-0' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pangoft2-1.0-0'

**Comment by liZe** [comment]
Hi!

That’s strange: PangoFT2 is the last library loaded, so it means that all the other ones have been imported successfully.

Could you please paste the result of `brew list pango`?

**Comment by marcoheleno** [comment]
The result after brew list pango:

/usr/local/Cellar/pango/1.50.14/bin/pango-list
/usr/local/Cellar/pango/1.50.14/bin/pango-segmentation
/usr/local/Cellar/pango/1.50.14/bin/pango-view
/usr/local/Cellar/pango/1.50.14/include/pango-1.0/ (37 files)
/usr/local/Cellar/pango/1.50.14/lib/libpango-1.0.0.dylib
/usr/local/Cellar/pango/1.50.14/lib/libpangocairo-1.0.0.dylib
/usr/local/Cellar/pango/1.50.14/lib/libpangoft2-1.0.0.dylib
/usr/local/Cellar/pango/1.50.14/lib/girepository-1.0/ (5 files)
/usr/local/Cellar/pango/1.50.14/lib/pkgconfig/ (5 files)
/usr/local/Cellar/pango/1.50.14/lib/ (6 other files)
/usr/local/Cellar/pango/1.50.14/share/gir-1.0/ (5 files)

**Comment by liZe** [comment]
> /usr/local/Cellar/pango/1.50.14/lib/libpangoft2-1.0.0.dylib

That’s the file you want. Is this file really installed on your filesystem?

**Comment by marcoheleno** [comment]
What should I do with this file: /usr/local/Cellar/pango/1.50.14/lib/libpangoft2-1.0.0.dylib
Should I run any command?

**Comment by liZe** [comment]
I just wanted to know if the file is really in your filesystem, looks like it is. Then, there’s not much we can do here 😒. If the file’s there, then it’s supposed to work.

It’s more a problem with Homebrew then, `brew install weasyprint` is supposed to find libraries correctly. You should get in touch with them: here’s the [troubleshooting page](https://docs.brew.sh/Troubleshooting). You need help more from a macOS guru than from WeasyPrint’s maintainers 😄.
