### ISSUE TITLE
Some SVG images ignore CSS when called inside python using only 59 "Options" syntax

### ISSUE THREAD

**Issue by AlexanderNeilson** [Kozea/WeasyPrint#1940]
Hi Team

When calling weasyprint to create a PDF inside Python (Django project) I use presentational_hints to ensure proper layout.

Up to 58.1 this has worked in the normal way as a kwarg inside write_pdf.

When converting my code over to 59.0 and moving it inside the "options" dictionary kwarg I found that most things continued to work however some SVG images we use to represent "tick box" status show up at a massive size (possibly their native size).

If I return the original presentational_hints kwarg (at the same time as I keep it in options) the output is "normal"

I haven't yet been able to work out the code path this could be taking where it isn't respecting the move to the new options.

Working as expected:

    generated_pdf = HTML(
        string=html,
        base_url=request.build_absolute_uri(),
    ).write_pdf(
        presentational_hints=True,
        font_config=font_config,
        options={
            "presentational_hints": True,
            "optimize_images": True,
            "jpeg_quality": 85,
            "dpi": 200,
        },
    )

Not working as expected:

    generated_pdf = HTML(
        string=html,
        base_url=request.build_absolute_uri(),
    ).write_pdf(
        font_config=font_config,
        options={
            "presentational_hints": True,
            "optimize_images": True,
            "jpeg_quality": 85,
            "dpi": 200,
        },
    )

Text of the HTML generated by render_to_string that is fed in to these examples
[ReportBigSVG.txt](https://github.com/Kozea/WeasyPrint/files/12352893/ReportBigSVG.txt)

Working as expected output
[GL-QA7739-DEV3.pdf](https://github.com/Kozea/WeasyPrint/files/12352898/GL-QA7739-DEV3.pdf)

Not working as expected output
[GL-QA7739-DEV.pdf](https://github.com/Kozea/WeasyPrint/files/12352901/GL-QA7739-DEV.pdf)

Python 3.9, Windows 11 22H2, Django 4.1.10,

Please let me know if you need further details or need me to run tests / snag specific files for investigation.

Thank you

Regards
Alexander

**Comment by liZe** [comment]
Hi!

The new API gets `**options`, not `options`. It means that you have to give keyword arguments (ie. `presentational_hints=True`), not a single `options` dictionary (ie. not `options={'presentational_hints': True}`).

So, the code you want is:

```python
generated_pdf = HTML(
    string=html,
    base_url=request.build_absolute_uri(),
).write_pdf(
    font_config=font_config,
    presentational_hints=True,
    optimize_images=True,
    jpeg_quality=85,
    dpi=200,
)
```

And if you prefer to use an `options` dictionary, you can use:
```python
options = {
    "presentational_hints": True,
    "optimize_images": True,
    "jpeg_quality": 85,
    "dpi": 200,
}

generated_pdf = HTML(
    string=html,
    base_url=request.build_absolute_uri(),
).write_pdf(
    font_config=font_config,
    **options
)
```
