### ISSUE TITLE
CLI error (xref stream, offset 17448405): Cross-reference stream's /W contains impossibly large values

### ISSUE THREAD

**Issue by datawithdev** [Kozea/WeasyPrint#1941]
PDF generated using weasyprint cli version 59 installed using Homebrew created corrupted PDF

WARNING: review.pdf: Attempting to reconstruct cross-reference table
qpdf: review.pdf: unable to find trailer dictionary while recovering damaged file
(base) Devs-MacBook-Pro:generateall username$ 
(base) Devs-MacBook-Pro:generateall username$ 
(base) Devs-MacBook-Pro:generateall username$ 

Surprisingly, I am able to open the same PDF using online editors and once I reexport the file can be opened again.

**Comment by liZe** [comment]
Hi!

Could you please check that you use the latest version of pydyf (v0.7.0)? If you do, could you please share your PDF and your HTML/CSS document if possible? If it’s not public, you can send a mail.
