### ISSUE TITLE
background-image doesn't cover bleed area

### ISSUE THREAD

**Issue by pmjdebruijn** [Kozea/WeasyPrint#1943]
When using background-image, the bleed area remains white, see the following test case:

[background-image-bleed-bug.zip](https://github.com/Kozea/WeasyPrint/files/12437885/background-image-bleed-bug.zip)

This may also illustrate another bug, when using named pages, a pagebreak gets inserted when you wouldn't expect it...

**Comment by liZe** [comment]
Hi!

Thanks for this bug report.

Could you please open a separate issue for the page break introduced by the page name?

**Comment by pmjdebruijn** [comment]
I just noticed that this is the proper way to scale the background-image
https://developer.mozilla.org/en-US/docs/Web/CSS/image-resolution

Updated test case: [background-image-bleed-bug.zip](https://github.com/Kozea/WeasyPrint/files/12439431/background-image-bleed-bug.zip)

The initial reported issue still persist however.

**Comment by liZe** [comment]
Should now be fixed, feedback welcome!

**Comment by pmjdebruijn** [comment]
Confirmed fixed.
