### ISSUE TITLE
leader() length determination in ::after bug

### ISSUE THREAD

**Issue by pmjdebruijn** [Kozea/WeasyPrint#1946]
It seems when leader() is used in ::after, combined with padding-left, something strange happens, as the page numbers fail to line up nicely:

[toc-bug.zip](https://github.com/Kozea/WeasyPrint/files/12456344/toc-bug.zip)

**Comment by pmjdebruijn** [comment]
**Result**
`
Lorem Ipsum . . . . . . 1
  Lorem Ipsum . . . . . . 1
    Lorem Ipsum . . . . . . 1
`

**Expected**
`
Lorem Ipsum . . . . . . 1
  Lorem Ipsum . . . . . 1
    Lorem Ipsum . . . . 1
`

**Comment by pmjdebruijn** [comment]
The following seems to offer workable solution for the time being:

```
#contentspage ul li a.h2::before { content: '    '; white-space: pre; }
#contentspage ul li a::after { content: ' ' leader(' . ') ' ' target-counter(attr(href), page); font-kerning: none; }
```

**Comment by liZe** [comment]
Thanks a lot for the bug report! It should now be fixed.

**Comment by pmjdebruijn** [comment]
Excellent. Confirmed Fixed.
