### ISSUE TITLE
Italic does not render correctly in the generated pdf

### ISSUE THREAD

**Issue by kgish** [Kozea/WeasyPrint#1949]
For some strange reason, italics do not work:
```
<p><em>This should be in italics but isn't.</em></p>
```
but the following works just fine:
```
<p><b>This is in bold as expected.</b></p>
```
What might I be doing wrong, and how can I get it to render correctly?

**Comment by liZe** [comment]
WeasyPrint doesn’t synthesize faux italique and faux bold. You probably have to install the italic variant of the font you use.

**Comment by kgish** [comment]
Can you please be more specific, what do you mean by `install the italic variant of the font you use.`

How can I do this, do you have an example?

**Comment by liZe** [comment]
Let’s say you want to use the font called "Liberation". You can [download the font](https://github.com/liberationfonts/liberation-fonts/files/7261482/liberation-fonts-ttf-2.1.5.tar.gz) and see in the archive that there are multiple `.ttf` files: they correspond to different weights (regular, bold, etc) and variants (normal, italic, etc). If you want to use Liberation italic, you’ll then have to install the italic variant.

The way to install fonts depends on your operating system, you can find some documentation about this online.

**Comment by AnandKM369** [comment]
> WeasyPrint doesn’t synthesize faux italique and faux bold. You probably have to install the italic variant of the font you use.

I have follow-up question on this. Does this also has an impact on tags <strong> and <i> for the font family Tahoma? Because I am facing issues with rendering these attributes. Also, It would be really helpful if you could share the installers for Tahoma font(bold weight and italic variant) as I failed to find them online.

Thanks for your time!

**Comment by liZe** [comment]
> Also, It would be really helpful if you could share the installers for Tahoma font(bold weight and italic variant) as I failed to find them online.

According to Microsoft, [Tahoma doesn’t have an italic variant](https://learn.microsoft.com/fr-fr/typography/font-list/tahoma). The bold variant should work though.

The font is already provided on Windows and macOS. On other OSes, you can [buy it here for example](https://www.fonts.com/font/microsoft-corporation/tahoma).

> I have also tried linking below CSS mapping to see if it works, unfortunately it doesn't helped.

No need for this, these rules are already in [WeasyPrint’s default stylesheet](https://github.com/Kozea/WeasyPrint/blob/main/weasyprint/css/html5_ua.css).

**Comment by liZe** [comment]
Closing, as there’s nothing we can do in WeasyPrint for this. #1470 is the place to discuss about synthesis of fonts.
