### ISSUE TITLE
Unable to use Weasyprint within virtualenv

### ISSUE THREAD

**Issue by lawrenceadams** [Kozea/WeasyPrint#1955]
Hello,

Sadly I am struggling to install Weasyprint within a virtualenv on Azure ML Compute instance (although I don't think this should be a problem)

`uname -a`: `Linux xxx 5.15.0-1040-azure #47~20.04.1-Ubuntu SMP Fri Jun 2 21:38:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

After installing weasyprint (version 59.0) with poetry and trying to invoke with command line, or within python I get the following error:

`OSError: cannot load library 'gobject-2.0-0': gobject-2.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'`

I have installed Weasyprint as a system package/via `apt`, and if I deactivate the virtualenv this can be run without issue:

```shell
azureuser@ladams:~/cloudfiles/code$ weasyprint --version
WeasyPrint version 51
```

I have tried installing all the packages as laid out in the [instructions](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#ubuntu-20-04), but still am unable to use weasyprint when the virtualenv is active.

I am sorry - I can imagine these install questions are dull, but I am unsure what to do next! Many thanks

**Comment by liZe** [comment]
Hi!

Does it work without poetry?

```
python3 -m venv venv
venv/bin/pip install weasyprint
venv/bin/weasyprint --version
```

**Comment by pmjdebruijn** [comment]
I'm guessing this would work:

```
pip install --no-binary :all: weasyprint
```

Though some -dev packages would likely need to be installed for that to work.

**Comment by lawrenceadams** [comment]
@liZe Sadly this didn't work, however... 
@pmjdebruijn this worked perfectly! It looks like [there is a way to integrate this](https://python-poetry.org/blog/announcing-poetry-1.2.0/#opting-out-of-binary-distributions) with my poetry workflow.

Thank you very much both for your fast response and efforts with WeasyPrint! :smile: ❤️
