### ISSUE TITLE
Handle HTML5 <wbr>

### ISSUE THREAD

**Issue by castedo** [Kozea/WeasyPrint#1965]
With version 59 the following [test.html.txt](https://github.com/Kozea/WeasyPrint/files/12607836/test.html.txt) generates [test.pdf](https://github.com/Kozea/WeasyPrint/files/12607838/test.pdf).

What is unexpected is that WeasyPrint seems to use the `<wbr>` as a reason to not break at all but rather let the text break out of the green fixed-width `word-wrap: break-word` paragraph, essentially the opposite of what `wbr` should cause.

I am not sure whether the HTML5 `<wbr>` element  (Word Break Opportunity) should work in WeasyPrint. I am guessing there are only a few corner cases where this is valuable. `<wbr>` seems like a nice complement to `white-space: nowrap` to allow more control over where text should and should not be broken (but without adding a hyphen like &amp;shy;). I was going to use `<wbr>` but now I am only using `white-space: nowrap` since `<wbr>` does not seem to work as expected in WeasyPrint.

**Comment by liZe** [comment]
Hi!

`<wbr>` is not supported at all, that’s why it doesn’t work, but…

Maybe it’s "just" a CSS oneliner. Could you try to add `wbr::before { content: "\200B" }` into your CSS? If it does work for you (seems to work for me), then the bug should be easy to fix in WeasyPrint :smile:.

**Comment by castedo** [comment]
Nice, that does work for me! :+1: Smart thinking!

**Comment by liZe** [comment]
> Nice, that does work for me! 👍 Smart thinking!

That’s already how `br` is already handled, and [that wasn’t even my idea](https://www.w3.org/TR/CSS2/sample.html#q22.0) 😄.
