### ISSUE TITLE
Cannot load default config file 

### ISSUE THREAD

**Issue by zl945** [Kozea/WeasyPrint#1969]
python -m weasyprint --info
Fontconfig error: Cannot load default config file
System: Linux
Machine: x86_64
Version: #1 SMP Mon Jul 29 17:46:05 UTC 2019
Release: 3.10.0-957.27.2.el7.x86_64

WeasyPrint version: 59.0
Python version: 3.9.18
Pydyf version: 0.7.0
Pango version: 14810

**Comment by liZe** [comment]
Hi!

This message means that your Fontconfig installation can’t read its default configuration file. It shouldn’t be the case if you used your Linux distribution packaging system to install Fontconfig. Did you use another way to install Fontconfig?

**Comment by zl945** [comment]
@liZe Thanks! I istalled weasyprint by conda， could conda also reinstalled Fontconfig at the same time? 
How can i find and  reconfiguration its default configuration file?

**Comment by liZe** [comment]
Then Conda has installed Fontconfig, because it’s a dependency of Pango that’s a dependency of WeasyPrint.

That’s a bug in the Conda’s Fontconfig package. You can report an issue [in their repository](https://github.com/conda-forge/fontconfig-feedstock), there’s not much we can do here.

Note that it’s just a warning, maybe it doesn’t break anything in the rendering.

**Comment by zl945** [comment]
Yes,  that it’s just a warning!  Another question.   The numbers 1 and 2 in the image represent the HTML content that contains the table. The number 3 represents the PDF generated using WeasyPrint, but the table is not displaying. How can I make it display?
![image](https://github.com/Kozea/WeasyPrint/assets/47781232/da22d287-4572-4639-888b-e7e8b673e634)
If it's convenient, could you please take a look at this file? How can I convert the HTML content in this file to a PDF, including displaying tables, showing images correctly, and handling page breaks, etc.?
[1.zip](https://github.com/Kozea/WeasyPrint/files/12697320/1.zip)

**Comment by liZe** [comment]
WeasyPrint doesn’t support JavaScript, that’s why the table (created in JS) is not displayed on the PDF.

**Comment by zl945** [comment]
Thank you very much. Do you have any other recommended software to support it?
