### ISSUE TITLE
WP 60.0 regression: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by castedo** [Kozea/WeasyPrint#1974]
Bad news on 60.0.

STEPS:

Running weasyprint 60.0 with [input7.html.txt](https://github.com/Kozea/WeasyPrint/files/12755304/input7.html.txt)
```
weasyprint input7.html out.pdf
```
I get exception:
```
  File "/usr/local/lib/python3.11/site-packages/weasyprint/layout/preferred.py", line 312, in inline_line_widths
    child_text[resume_index:].decode(), child.style,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
Here's the full stderr output I get:
[stderr.txt](https://github.com/Kozea/WeasyPrint/files/12755333/stderr.txt)

Looking at the HTML and knowing the pipeline I use i don't think there is anything unusual with unicode here.

This is a regression affecting the document pipeline that I run regularly.

**Comment by castedo** [comment]
Also, I run this within a container so I can share the container image if you have trouble reproducing.

**Comment by liZe** [comment]
Hi @castedo!

It’s probably a duplicate of #1973. Does the current `main` branch work for you?

**Comment by castedo** [comment]
Good news! The main branch does work for me!
