### ISSUE TITLE
Elements in SVG document with opacity < 1 are not rendering

### ISSUE THREAD

**Issue by audy** [Kozea/WeasyPrint#1976]
I am encountering an issue when trying to render an SVG document that contains elements with opacity < 1.0. Elements in w/ opacity < 1.0 do not render in `Weasyprint==60.1`.

I have attempted to create a minimal SVG document that recreates the issue [here](https://gist.github.com/audy/908f9308fa1c7f2ccd65458da7301381).

I am converting using the weasyprint CLI:

```
weasyprint example.xml example.pdf
```

This is a screenshot of the same XML document rendered using Chrome:

![Screenshot 2023-10-02 at 9 23 33 PM](https://github.com/Kozea/WeasyPrint/assets/115904/18193211-57f0-45c6-809d-e94105c8f417)

This is a screenshot of the same document rendered using weasyprint. The two points that are still visible have `opacity=1.0`:

![Screenshot 2023-10-02 at 9 23 20 PM](https://github.com/Kozea/WeasyPrint/assets/115904/466bbf06-52e4-4230-beb0-6da7b4ece1ec)

Let me know if I can provide any more information.

**Comment by liZe** [comment]
Thanks for the bug report and for the example. It’s now fixed and tested!

**Comment by audy** [comment]
@liZe amazing! works on my end. thank you!
