### ISSUE TITLE
Markers with viewBox attribute have a border applied around the viewBox automatically

### ISSUE THREAD

**Issue by michaellisitsa** [Kozea/WeasyPrint#1982]
There is an issue where markers with a viewBox attribute are showing with a rectangular border in >v55
![image](https://github.com/Kozea/WeasyPrint/assets/58811856/33386044-047f-4892-a549-bbc5a03daaf2)
Browsers do not have this behaviour see https://codepen.io/michaellisitsa/pen/xxmBbye and couldn't find anything in the https://www.w3.org/TR/SVG/painting.html#RenderingMarkers 

**Investigation of bug**
The bug only surfaced at v55.0 where a fix was made to the viewBox for markers https://github.com/Kozea/WeasyPrint/commit/607f26fbd7b886fbf9ff567d6cf44ecfb6fea0ed

A check occurs in `svg/__init__.py` file for the viewBox attribute on the marker node, and as a results a clip box is created on
https://github.com/Kozea/WeasyPrint/blob/4dfe6079c2d1bd91cccfd9a7d78f8924e2dfabef/weasyprint/svg/__init__.py#L544

Further down, a check is done for the `clip_box` and a rectangle is drawn. I believe this shouldn't be the case.

https://github.com/Kozea/WeasyPrint/blob/4dfe6079c2d1bd91cccfd9a7d78f8924e2dfabef/weasyprint/svg/__init__.py#L589

**Reproducable example** 
```
<svg
          width="600"
          height="217"
          role="img"
          viewBox="0 0 600 217"
          style="pointer-events: all; width: 100%; height: 100%"
        >
          <defs>
            <marker
            id="circle"
              viewBox="0 0 10 10"
              refX="10"
              refY="5"
              markerWidth="15"
              markerHeight="15"
              orient="auto"
              stroke="none"
            >
              <circle cx="2.5" cy="7.5" r="2.0" stroke="red" fill="transparent" stroke-width="1"/>
            </marker>
          </defs>
            <path
              d="M102.86664121071314,106.99999999999997L102.86664121071314,59"
              style="
                fill: none;
                stroke: black;
                pointer-events: stroke;
                marker-end: url(#circle);
                stroke-width: 2;
              "
              role="presentation"
              shape-rendering="auto"
            ></path>
        </svg>
```

**Comment by liZe** [comment]
Hi!

Thanks for the report.

We should add `self.stream.end()` after clipping, otherwise the rectangle will be used during the drawing. The push/pop state is probably also useless. I’ll push the fix as soon as I find the time to add some related tests!

**Comment by liZe** [comment]
This problem is fixed and some tests have been added, but there are probably many problems left with markers and their wonderful list of available attributes. Don’t hesitate to report more issues if needed!
