### ISSUE TITLE
RecursionError: maximum recursion depth exceeded when converting a big Document

### ISSUE THREAD

**Issue by vince-vibin** [Kozea/WeasyPrint#1983]
I have a very big HTML Document (~1000 Pages) which i want to convert to a PDF. But i am getting this error
`RecursionError: maximum recursion depth exceeded` 
my guess is that the recursion depth needs to be increased like [here](https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-and-how-to-increase-it).
For the call I am using this command 
`weasyprint input.html output.pdf`

**Comment by grewn0uille** [comment]
Hello!

Can you please share the related HTML/CSS files?
So we can see if it’s possible to do something about it without changing the recursion depth.

**Comment by vince-vibin** [comment]
Hi,
I can't upload the file because its sensitive but i've tried @lukas-holzner's fix and it worked perfectly fine. 
The file is an auto generated HTML file with ~80000 lines.

**Comment by grewn0uille** [comment]
You can send a mail if you can’t share some information publicly

**Comment by liZe** [comment]
Hi!

Could you please share by mail your document? It looks like you have a depth of ~400 nested tags in your HTML, is that possible?

**Comment by liZe** [comment]
Hi @lukas-holzner,

Is this problem solved for you?

**Comment by vince-vibin** [comment]
We where able to fix the issue with @lukas-holzner's fix. 
I don't know if you want to merge this in the state its in but we really cant share the document.

**Comment by liZe** [comment]
> We where able to fix the issue with @lukas-holzner's fix.
> I don't know if you want to merge this in the state its in but we really cant share the document.

Just to be sure: does your HTML include ~400 levels of depth? If it does, we can consider that it’s an extreme corner case that can be solved by setting the recursion limit it a Python script calling WeasyPrint’s API.

**Comment by lukas-holzner** [comment]
It might have 400 levels of depth. @vince-vibin  could you please check that?

**Comment by vince-vibin** [comment]
yes it has ~380

**Comment by liZe** [comment]
> yes it has ~380

Thanks for checking!

Then we can consider this as a corner case, and the easiest way to solve it is to use WeasyPrint with a Python script that sets the recursion limit.
