### ISSUE TITLE
Opacity does not support percentage

### ISSUE THREAD

**Issue by michaellisitsa** [Kozea/WeasyPrint#1986]
Failure occurs in v59 of weasyprint. There is no support for percentage values, instead the print fails. I believe we should support it per https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-opacity or if that's too hard at least have a fallback incase its not a float. 

**Source code**

It appears like the problem might be with trying to coerce the value to a float https://github.com/Kozea/WeasyPrint/blob/ff3b417e91a26987430f6a7fc15899e7babf3ded/weasyprint/svg/__init__.py#L634

Failure log
```text
File \"/usr/local/lib/weasyprint/.venv/lib/python3.8/site-packages/weasyprint/svg/__init__.py\", line 633, in fill_stroke\n    stroke_opacity = float(node.get('stroke-opacity', 1))\nValueError: could not convert string to float: '40%'\n",
```

**Comment by liZe** [comment]
Hi!

Thanks for the bug report.

All `opacity` and `*-opacity` properties should allow percentages, in SVG and CSS, as defined in [CSS Color Level 4](https://www.w3.org/TR/css-color-4/#transparency).

Correctly handling errors in SVG is not done yet, so I’m not sure that we’ll implement a nice fallback just here. But handling percentages will definitely fix your problem.
