### ISSUE TITLE
Incorrect scoping of nested-counters in <ol>

### ISSUE THREAD

**Issue by cdelnooz** [Kozea/WeasyPrint#1991]
When using nested counters to create a table of contents, the child-level counter does not go out of scope at the `</ol>` tag of the nested list. Minimal sample to reproduce:
```html
<html>
    <head>
        <style>
         /* Style the Table of Contents */
         .toc {
             page-break-before: always;
         }
         @page {
             size: a4;
             margin: 3cm 1.8cm 2.5cm 1.8cm;
         }
         .toc ol {
             counter-reset: toc;
             list-style-type: none;
         }
         .toc li::before {
             counter-increment: toc;
             content: counters(toc, ".") " ";
         }
        </style>
    </head>
    <body>
        <div class="toc">
            <ol>
                <li>Chapter 1</li>
                <ol>
                    <li>Section 1.1</li>
                    <li>Section 1.2</li>
                    <li>Section 1.3</li>
                </ol>
                <li>Chapter 2</li>
                <ol>
                    <li>Section 2.1</li>
                    <li>Section 2.2</li>
                </ol>
                <li>Chapter 3</li>
                <li>Chapter 4</li>
            </ol>
        </div>
    </body>
</html>
```
When rendering this in Firefox, I get a correct rendering:
![firefox_toc_render](https://github.com/Kozea/WeasyPrint/assets/35438160/80f8ce76-9ceb-4b0f-a651-face72244410)

However, weasy print renders as below, basically maintaining the second level counter rather than returning to the top-level:
![weasyprint_toc_render](https://github.com/Kozea/WeasyPrint/assets/35438160/d008aa7d-bc72-4988-9c37-ff5054c74ae3)

I think this is potentially related to #1685, but it does read slightly different.
Version info: Weasyprint 60.1 on Ubuntu 20.04, Python 3.8.10

**Comment by liZe** [comment]
Hi!

Using `ol` tags in `ol` tags is not allowed in HTML, you have to put them in `li` tags.

https://dev.w3.org/html5/spec-LC/grouping-content.html#the-ol-element

Here’s the correct structure:
```html
        <div class="toc">
            <ol>
                <li>Chapter 1
                    <ol>
                        <li>Section 1.1</li>
                        <li>Section 1.2</li>
                        <li>Section 1.3</li>
                    </ol>
                </li>
                <li>Chapter 2
                    <ol>
                        <li>Section 2.1</li>
                        <li>Section 2.2</li>
                    </ol>
                </li>
                <li>Chapter 3</li>
                <li>Chapter 4</li>
            </ol>
        </div>
```

**Comment by cdelnooz** [comment]
Thanks for pointing that out, I hadn't realized that was the case. After correcting my HTML, nested counters work as expected. Cheers!
