### ISSUE TITLE
How is Pango installed on Windows 11

### ISSUE THREAD

**Issue by tmblog** [Kozea/WeasyPrint#1994]
I have installed GTK3 runtime and it's in the environment variables:
`C:\Program Files\GTK3-Runtime Win64\bin`

Do I need to install it separately so it's in the pip list as well? If so how?

Thanks for the awesome library.

**Comment by Khnsimeon29** [comment]
install them separately and sync

**Comment by grewn0uille** [comment]
Hello @tmblog,

> Do I need to install it separately so it's in the pip list as well? If so how?

Pango is provided by the GTK3 bundle. There is no need to install it separately with pip :)

**Comment by Khnsimeon29** [comment]
As I write these few lines, Gtk+ v4 has already been released.  We will see that, whatever the version of Gtk+ chosen, the installation of these libraries is the same.  The configuration of Code::Blocks will also be identical.

 A quick reminder first.  Gtk, for Gimp Tool Kit, is originally a toolkit designed to create The Gimp (Graphical Image Manipulation Program) under Linux.  Since then, this toolbox has been used in many other applications, but also for desktop management.  Gnome who is the spearhead.

 Which version to choose?

 If you are a beginner with these libraries, the latest version is required.  Programming in Gtk+v2 will limit your possibilities and you will have more and more difficulty finding a community to help you.
 If the project imposes a particular version on you, for example linked to the possibilities that end users will have to access administrator rights to install the latest version of Gtk+, then the choice is offered to you between v2, v3 or v4.
 The Gtk+ team provides us with a page dedicated to installation under Windows: https://www.gtk.org/docs/installations/windows/.  Might as well use it.

**Comment by tmblog** [comment]
Thank you all for the replies, I recently moved to a windows 11 and now the issues started to happen.
I can see the libpango-1.0-0.dll in the bin of gtk-runtime. But weasyprint fails to run without any warnings just get an exit code 1.
Not sure how to solve this.

**Comment by grewn0uille** [comment]
You can have a look at the `WEASYPRINT_DLL_DIRECTORIES` variable and more about troubleshooting on Windows [in the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting).

**Comment by tmblog** [comment]
No luck with that either, I have tried a brand new project with the quickstart but still no luck.
Here's what I get from typing python on cmd:

`Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32`
Then when I do:
`python -m weasyprint --info`
it exits with code 1.
Is there any other way to debug this?

Cheers thus far and in advance

**Comment by liZe** [comment]
> it exits with code 1.

Could you please provide the whole stacktrace?

**Comment by tmblog** [comment]
> > it exits with code 1.
> 
> Could you please provide the whole stacktrace?

This is what I get: 

```
PS C:\Users\User\Documents\dev\python\hw>  & 'C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe' 'c:\Users\User\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '50492' '--' 'C:\Users\User\Documents\dev\python\hw\app.py' 
PS C:\Users\User\Documents\dev\python\hw>  c:; cd 'c:\Users\User\Documents\dev\python\hw'; & 'C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe' 'c:\Users\User\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '50501' '--' 'C:\Users\User\Documents\dev\python\hw\app.py' 
PS C:\Users\User\Documents\dev\python\hw>  c:; cd 'c:\Users\User\Documents\dev\python\hw'; & 'C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe' 'c:\Users\User\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '50526' '--' 'C:\Users\User\Documents\dev\python\hw\app.py'
PS C:\Users\User\Documents\dev\python\hw>  c:; cd 'c:\Users\User\Documents\dev\python\hw'; & 'C:\Users\User\AppData\Local\Programs\Python\Python312\python.exe' 'c:\Users\User\.vscode\extensions\ms-python.python-2023.18.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '50541' '--' 'C:\Users\User\Documents\dev\python\hw\app.py'
```
Otherwise please direct me how to get better info, I get this through launch.json only. Nothing else except breakpoints gives me the stack trace. Alternative the try/except  also raises nothing.

Thank you again!

**Comment by liZe** [comment]
> Otherwise please direct me how to get better info,

Could you please write what `python -m weasyprint --info` returns?

**Comment by tmblog** [comment]
> > Otherwise please direct me how to get better info,
> 
> Could you please write what `python -m weasyprint --info` returns?

Nothing, which is weird I can see it in my pip list.
![image](https://github.com/Kozea/WeasyPrint/assets/11068215/470e847b-1587-4303-b7e2-d9a6f8d06d87)

Here's my pip list:

```
Package            Version
------------------ ---------
asgiref            3.7.2
asyncio            3.4.3
blinker            1.6.2
Brotli             1.1.0
certifi            2023.7.22
cffi               1.15.1
charset-normalizer 3.2.0
click              8.1.7
colorama           0.4.6
cssselect2         0.7.0
Flask              2.3.3
Flask-Cors         4.0.0
flaskwebgui        1.0.6
fonttools          4.42.1
html5lib           1.1
htmlwebshot        0.1.2
idna               3.4
itsdangerous       2.1.2
Jinja2             3.1.2
MarkupSafe         2.1.3
Pillow             10.0.1
pip                23.3.1
psutil             5.9.5
pycparser          2.21
pydyf              0.8.0
PyPDF2             3.0.1
pyphen             0.14.0
pywin32            306
requests           2.31.0
six                1.16.0
tinycss2           1.2.1
urllib3            2.0.4
weasyprint         60.1
webencodings       0.5.1
Werkzeug           2.3.7
zopfli             0.2.3
```

**Comment by liZe** [comment]
> Nothing, which is weird

That’s weird, for sure. Can you just launch `python`, and then type `import weasyprint` if `python` opens a Python shell?

**Comment by liZe** [comment]
Python crashes with no error, it shouldn’t happen.

> Do I need to install python from within the app store?

You can try.

**Comment by tmblog** [comment]
I got this message when installing from scratch again is this important?

```
 WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.      
  WARNING: The script weasyprint.exe is installed in 'C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. 
```

**Comment by tmblog** [comment]
OK uninstalling everything including gtk then installing from app store. did the trick. Thank you for your help!
