### ISSUE TITLE
Margin-top in body style only affects the first page when margin-top: 0; in @page

### ISSUE THREAD

**Issue by SystemError7** [Kozea/WeasyPrint#2002]
I have the margins in the ```@page``` in 0 like this:
```
@page {
    margin-top: 0cm;
    margin-bottom: 0cm;
    margin-left: 0cm;
    margin-right: 0cm;
}
```
because I want to cover all the background-color in the ```<body> style```, but if I don't put the margins at 0, then it would have the margins with 2cm, and not covering all the surface of the document.
Also, I put a margin-top of 1.5cm in the ```<body> style```, but that only affects the fitst page of the document generated, as you can see in the following pictures. The image of the ruler has a ```position: fixed;```
![image](https://github.com/Kozea/WeasyPrint/assets/146701483/589c51ab-9bb5-4423-9d35-6ebea9722ab9)
![image](https://github.com/Kozea/WeasyPrint/assets/146701483/72d3e16e-e3ea-491c-aa94-2ad7a5ed7989)

**Comment by liZe** [comment]
> because I want to cover all the background-color in the `<body> style`, but if I don't put the margins at 0, then it would have the margins with 2cm, and not covering all the surface of the document.

You can set a background to the `@page` to recover the whole page, including the margins.

> Also, I put a margin-top of 1.5cm in the `<body> style`, but that only affects the fitst page of the document generated, as you can see in the following pictures.

You can set negative values in [`background-position`](https://developer.mozilla.org/en/docs/Web/CSS/background-position) to put the background image of the page in the margin.

**Comment by liZe** [comment]
Also note that it’s normal to have the margin only on the first page when a block is split between pages. You can check [`box-decoration-break`](https://www.w3.org/TR/css-break-3/#break-decoration) and [`margin-break`](https://www.w3.org/TR/css-break-4/#break-margins) properties.

**Comment by liZe** [comment]
If you want to have page margins but put some elements in them, it’s better to use running elements and named page. See [Generated Content for Paged Media](https://drafts.csswg.org/css-gcpm/#running-elements) to learn more about this feature.

**Comment by SystemError7** [comment]
And there's no option to quit the margin when generating a document??? The pages of the document has always a 2cm of margin and the only way to quit it is with the ```@page { margin: 0; }```. There is a way to quit that option in the ```html``` or in the weasyprint.

**Comment by liZe** [comment]
> And there's no option to quit the margin when generating a document??? The pages of the document has always a 2cm of margin and the only way to quit it is with the `@page { margin: 0; }`. There is a way to quit that option in the `html` or in the weasyprint.

The 2cm margin is defined in [WeasyPrint’s default stylesheet](https://github.com/Kozea/WeasyPrint/blob/main/weasyprint/css/html5_ua.css).

Styling is done with CSS, and margins are style, so… Yes, you have to use CSS to change this, just as any other margins, borders, paddings, colors, etc.

Why is this a problem for you?

**Comment by SystemError7** [comment]
To create ```html``` in a comfortable way, because I don't have any references with the margin of 2cm of the page to adjust the content on the page, only if I do a margin left and top of 2cm in the ```body``` and the deleting the margin.
But, if I want to have a costume margins, not 2cm, it should be done by setting the margin of the ```@page``` at 0, and then, in the body setting your own margins and the margin of the ```@page``` not prevail to the body if it's at 0. It could be a feature.

**Comment by liZe** [comment]
Page margins and body margins are different. Of course, you can change their values to get exactly what you want depending on the context. As for everything in CSS, it may take some time to learn and understand how page margins work, but they become very powerful when you master them.

**Comment by SystemError7** [comment]
And there's no way to set the ```<body style="margin: 1em">``` to prevail over the ```@page``` default margin?
In ```weasyprint``` or in ```html```

**Comment by liZe** [comment]
> And there's no way to set the `<body style="margin: 1em">` to prevail over the `@page` default margin?
> In `weasyprint` or in `html`

@SystemError7 The margin is applied on the page, and there’s no tag in HTML representing the page, so you can’t set it using a `style` attribute on a tag. You have to use a stylesheet.

You can use `<style>@page{margin:0}</style>` if you want to define the rule directly in your HTML file. It’s better to put it in your HTML’s `head` tag, but it actually works everywhere.

**Comment by SystemError7** [comment]
I found out a way to solve it.
It's simple you have to use ```@page :first```.
In that attribute you set the margin-top and margin-left at 0.
Then, set the margin top of the ```<body>``` in ```@page``` so you would have the margin of the body in all the generated pages.
