### ISSUE TITLE
WeasyPrint ignores start attribute in ol

### ISSUE THREAD

**Issue by kesara** [Kozea/WeasyPrint#2003]
WeasyPrint ignores the `start` attribute in the `ol` element.

Example HTML:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>WeasyPrint ol test</title>
  </head>
  <body>
    <h1>Ordered list 1</h1>
    <ol>
      <li>item 1</li>
      <li>item 2</li>
      <li>item 3</li>
    </ol>
    <h1>Ordered list 2 (start=4)</h1>
    <ol start="4">
      <li>item 4</li>
      <li>item 5</li>
      <li>item 6</li>
    </ol>
    <h1>Ordered list 3 (start=7)</h1>
    <ol start="7">
      <li>item 7</li>
      <li>item 8</li>
      <li>item 9</li>
    </ol>
  </body>
</html>
```

WeasyPrint v60.1 output:
<img width="468" alt="Screenshot 2023-11-17 at 10 07 09" src="https://github.com/Kozea/WeasyPrint/assets/1027692/4fbfa5ad-c204-4b59-94a6-5ab7dd2cf608">

Expected output:
<img width="330" alt="Screenshot 2023-11-17 at 10 07 39" src="https://github.com/Kozea/WeasyPrint/assets/1027692/e6f56224-11cc-4c27-b933-5be7dfa9d0d6">

**Comment by liZe** [comment]
Hi!

You can use the `--presentational-hints` option if you want to handle HTML presentational hints such as `start`.

**Comment by kesara** [comment]
Thanks @liZe.

For ref: https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#supported-html-tags
