### ISSUE TITLE
Option to ignore page size definitions

### ISSUE THREAD

**Issue by madduck** [Kozea/WeasyPrint#2004]
Several projects out there use weasyprint to turn email messages into beautiful PDF files.

Unfortunately, software like Microsoft Outlook exists that creates really horrible HTML email messages, including hard-coding the paper size into emails. It's even worse though, in this case of a German tenant, mails are sent "on A4 paper" except for a couple of users who are using a US English UI, and that causes their mail to be sent "on US Letter paper".

One of the beauties of HTML is that it's medium-agnostic, and the text will simply flow within the container within which it is rendered. It should be my decision, as recipient, how I want the text to be layed out, but in order to do that, I would need to be able to tell weasyprint to ignore `@page` rules.

Is this something that might get added to the CLI and API?

Thanks for your consideration.

**Comment by grewn0uille** [comment]
Hello,

You can override them with a custom stylesheet and then use `weasyprint -s your_stylesheet.css email.html email.pdf`.

**Comment by madduck** [comment]
@grewn0uille you mean just override the `@page` rules? But I don't know what they are called, in any given document, and I don't want to just override all CSS…

Here is what I see in one email:

```
@page WordSection1
  {size:612.0pt 792.0pt;
  margin:70.85pt 70.85pt 2.0cm 70.85pt;}
div.WordSection1
  {page:WordSection1;} 
```

and then in another email from the same person on the same day, it's called `WordSection3`. And that's just this particular Outlook. Who knows what other rubbish Microsoft and others have in store.

Anyway, I'll give it a try!

Thanks for the hint.

**Comment by grewn0uille** [comment]
To override only the `@page` rules without knowing their name, you can use `!important` in your stylesheet like this:
```css
@page {
size: A4 !important;
}
```
Then all the page will have A4 size.

**Comment by madduck** [comment]
Thanks, that works. May this issue serve others trying to do the same!

**Comment by madduck** [comment]
One addition, I also found it makes sense to have:

```
* {
  page: inherit !important;
}
```

to prevent page breaks being inserted in general.
