### ISSUE TITLE
Missing unicode character right single quotation mark

### ISSUE THREAD

**Issue by Keithcat767** [Kozea/WeasyPrint#2005]
Hello!

While working with HTML from Confluence, we are seeing a missing unicode character for the right single quotation mark (\u2019). It looks like this might be a python issue, and I can solve it by replacing all instances with the ' character. But wanted to see if there was anything you can do to fix it.

Here is the results without replacing the character: 
<img width="242" alt="Screenshot 2023-11-20 at 11 52 41 AM" src="https://github.com/Kozea/WeasyPrint/assets/11504891/11d8f259-30f7-417c-9d82-0ec0ce561061">

Thank you!

**Comment by liZe** [comment]
Hi!

It’s an encoding problem.

HTML is considered as encoded in Latin-1 because it’s the default encoding of HTTP, but you’re using UTF-8 for you file, and you’re right!

You can add `<meta charset="utf-8">` tag in your `head` tag, or use the `-e utf-8` option if you launch WeasyPrint in the CLI.

**Comment by Keithcat767** [comment]
Hello!

Awesome - the -e argument worked perfectly. Thank you for the help!
