### ISSUE TITLE
unwanted code-indent in code-block

### ISSUE THREAD

**Issue by slartibart70** [Kozea/WeasyPrint#2009]
Hi, 

since recently weasyprint adds an additional margin to the left of code-blocks.

See my sample html and pdf files, the html looks as it should, but the pdf does not.
Could you please have a look into it?

[test2.zip](https://github.com/Kozea/WeasyPrint/files/13458587/test2.zip)

**Comment by slartibart70** [comment]
i tried with older versions of weasyprint (56, 50, ...) but - same behavior as 60.1
so, delete the 'recently' above.

This seems to be a real bug, not a regression

**Comment by liZe** [comment]
Hi!

You have some CSS only for print, in `@media print {…}`, that’s why you don’t get the same rendering.

**Comment by slartibart70** [comment]
oh, yes... I'm deeply sorry, my fault with the css. (yes, i want to have a different print layout)
I did not see those changes...
Closing this ticket now.
