### ISSUE TITLE
Rendering issue on MacOS preview

### ISSUE THREAD

**Issue by FozzieHi** [Kozea/WeasyPrint#2010]
I'm running into a rendering issue on MacOS preview, where neither text, nor images are rendered (but styling such as borders are).
<img width="1169" alt="rendering_issue" src="https://github.com/Kozea/WeasyPrint/assets/23139726/a0174f20-8dde-4b5b-9126-3a66ef83bdbb">

I'm converting a HTML document generated by [Bikeshed](https://github.com/speced/bikeshed), and the PDF does display correctly on readers such as Chrome and Firefox, so I'm reporting it here instead of on the Bikeshed repo, but can of course move it to there if need be.

I've attached the HTML document Bikeshed generates, and the output PDF WeasyPrint generates, and can provide more info if needed. Thanks!
[index.zip](https://github.com/Kozea/WeasyPrint/files/13461311/index.zip)

**Comment by FozzieHi** [comment]
I've managed to get this down to a small reproducible by playing around with the CSS Bikeshed outputs. If you try and generate a PDF using the following HTML, the text will not render properly using MacOS Preview, and a warning will be generated when trying to check the PDF using QPDF.
```html
<html>
    <style>
        :root {
            --p-text: currentcolor;
        }
        p {
            color: var(--p-text);
        }
    </style>
    <body>
        <p>
            Test
        </p>
    </body>
</html>
```

```
$ qpdf --check test.pdf
WARNING: test.pdf object stream 13 (object 4 0, offset 179): unknown token while reading object; treating as string
checking test.pdf
PDF Version: 1.7
File is not encrypted
File is not linearized
qpdf: operation succeeded with warnings
```

**Comment by liZe** [comment]
Hi!

Thanks for the bug report.

That’s a miracle to not get a crash in this case. That’s once again a problem like #1287, caused by #1175. We can definitely try to find a workaround, but the whole management of CSS functions has to be rewritten to get a real fix.

**Comment by FozzieHi** [comment]
@liZe Thanks, do you mean #1165 instead of #1175?

I'm not very familiar with CSS in PDFs, but is there a way to just not render this specific styling so that the document as a whole would render fine? Is MacOS Preview correct to not render in this case, and other readers are just trying to work around the problem?

Also, this should probably be opened as a different issue, but is it worth running a QPDF check during the WeasyPrint processing, to outline warnings like these to the user? Otherwise, there is no output from WeasyPrint to indicate any kind of problem.

**Comment by liZe** [comment]
> @liZe Thanks, do you mean #1165 instead of #1175?

I do (I’ve edited the comment.)

> Is MacOS Preview correct to not render in this case, and other readers are just trying to work around the problem?

The PDF is broken, that’s a bug in WeasyPrint. It magically works in PDF.js, but it’s broken in some other rendering tools.

> Also, this should probably be opened as a different issue, but is it worth running a QPDF check during the WeasyPrint processing, to outline warnings like these to the user? Otherwise, there is no output from WeasyPrint to indicate any kind of problem.

We already use Ghostscript to find these kind of bugs, and it also breaks with your example. We didn’t catch the bug earlier because this case wasn’t tested, that’s all. We’ll include a non-regression test when it’s solved!

I’m currently trying to fix the problem in a quite solid way.

**Comment by liZe** [comment]
> We already use Ghostscript to find these kind of bugs, and it also breaks with your example.

We actually don’t fail on Ghostscript errors. Let’s fix that too!

**Comment by liZe** [comment]
@FozzieHi the problem should be fixed in `main`, feedback is welcome!

**Comment by FozzieHi** [comment]
@liZe Yup, that's fixed the issue. Thanks so much for your help!
