### ISSUE TITLE
Unreachable area/border at bottom of page

### ISSUE THREAD

**Issue by jdus** [Kozea/WeasyPrint#202]
There seems to be a small area/fine border at the bottom of a page, that weasyprint cannot reach, at least nothing is drawn there. Maybe someone could confirm this.

```
<html>

<head>
<title>Bottom  test</title>

<style>

* {
	margin: 0;
	padding: 0;
}

.bottomDiv{
	position: absolute;
	bottom:0;
	width: 100%;
	height: 20px;
	background-color: #000;
}

@page{
	margin: 0;
	padding: 0;
}

</style>
</head>

<body>
<div class="bottomDiv"></div>
</body>

</html>
```

In the PDF produced by weasyprint, there is a fine white line at the bottom of the page. With "position: absolute; bottom: 0;" this shouldn't happen, should it?

![bottom_area](https://cloud.githubusercontent.com/assets/5982613/3147063/a56eb862-ea51-11e3-8b73-e73cf6ec40e8.png)

**Comment by liZe** [comment]
Even a simple example with floating values fails with both pycairo and cairocffi, so I suppose that rounding down is the good solution.
