### ISSUE TITLE
Overflow hidden not working when content is too large to fit in a page.

### ISSUE THREAD

**Issue by pareshbalar** [Kozea/WeasyPrint#2026]
Here is my simple HTML code (added in zip) where there are just two div containers with fixed 100px height and overflow hidden. [Update: correct HTML file added]
[html.zip](https://github.com/Kozea/WeasyPrint/files/13777188/html.zip)

When I am converting this HTML to PDF using Weasyprint, the first box seems to be fine but I am facing an issue with the second box.

Here is the Output PDF:
[out.pdf](https://github.com/Kozea/WeasyPrint/files/13776637/out.pdf)

**Here are the versions.**
System: Windows
Machine: AMD64
Version: 10.0.19045
Release: 10

WeasyPrint version: 60.2
Python version: 3.12.1
Pydyf version: 0.8.0
Pango version: 15003

Please help.

**Comment by liZe** [comment]
Hi!

Your input HTML doesn’t correspond to the PDF you provide, and there’s no `overflow` CSS property in it. Could you please provide the HTML file that gives your output PDF?

**Comment by pareshbalar** [comment]
My mistake :( 
Attached wrong html file.

Here is the correct HTML file.
[html.zip](https://github.com/Kozea/WeasyPrint/files/13777138/html.zip)

Here is the screenshot of CSS & HTML
![image](https://github.com/Kozea/WeasyPrint/assets/10231683/e478437b-a18e-400f-8d2d-9782e5181963)
![image](https://github.com/Kozea/WeasyPrint/assets/10231683/48fe1754-ca6b-453f-b295-634ce9ceabb0)

**Comment by liZe** [comment]
Thanks for the report! It’s fixed and tested, feedback is welcome!

**Comment by pareshbalar** [comment]
Hi @liZe Thanks for the quick reply.

I am using the Weasyprint 60.2 version which is the latest I think.

Is this fix released in this version or it's planned in an upcoming release (61.0)?

If it's not yet released, when can we expect it or is there a way I can use it now?

Thanks again! Really appreciate the quick answer.

**Comment by pareshbalar** [comment]
Hi @liZe, I installed the current main branch using the cmd you mentioned.

![image](https://github.com/Kozea/WeasyPrint/assets/10231683/cafef754-5a5d-4c10-80f0-9e020d89c6fd)

However, the issue is still there.

Attached output pdf.
[out.pdf](https://github.com/Kozea/WeasyPrint/files/13778905/out.pdf)

Am I missing anything?

FYI, I am on Windows.

**Comment by pareshbalar** [comment]
Worked :) 

Thanks a lot.
