### ISSUE TITLE
`@media print` and `@media screen` is not working as intended

### ISSUE THREAD

**Issue by milanjelisavcic** [Kozea/WeasyPrint#2027]
I try to set a PDF where a section should be displayed in PDF and section when printed:
```python
import os
from weasyprint import HTML

# HTML content with different visibility settings
html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Visibility Example</title>
    <style>
        @media screen {
            .visible-print {
                display: none;
            }
        }

        @media print {
            .visible-pdf {
                display: none;
            }
        }

        /* Styles for visible in both remain as is */
        .visible-both {
            display: block;
        }
    </style>
</head>
<body>
    <div class="visible-both">1. in PDF and print</div>
    <div class="visible-pdf">2. in PDF only</div>
    <div class="visible-print">3. in print only</div>
</body>
</html>
"""

# Generate PDF from HTML
pdf = HTML(string=html_content).write_pdf()

# Save PDF to a file
output_path = 'visibility_example.pdf'
with open(output_path, 'wb') as f:
    f.write(pdf)

```
Instead I get this output file [visibility_example.pdf](https://github.com/Kozea/WeasyPrint/files/13778592/visibility_example.pdf) where only both PDF and print and print only tagged elements are displayed.
Is there another way to set this or is it a work in progress?

**Comment by liZe** [comment]
Hi!

By default, WeasyPrint follows the rules for `print`, not for `screen` (as PDF is paged media, see [the CSS2 specification](https://www.w3.org/TR/CSS2/media.html#media-types)). Your output PDF is what’s expected.

If you want to change this, you can use the [`media_type` parameter](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.HTML):

```python
pdf = HTML(string=html_content, media_type='screen').write_pdf()
```

**Comment by liZe** [comment]
> @liZe If I add an option to include both simultaneously, would that be a good candidate for PR?

Unfortunately, I don’t think so 😢, because the CSS2 specification explicitly forbids that:

> Media types are mutually exclusive in the sense that a user agent can only support one media type when rendering a document.

And each time we tried not to follow what’s in the specification, it created more problems that it actually solved. So, even if I get your point, I’ll trust the specification and believe that it’s a good idea to get this feature.

What’s your use case? Maybe we can find another solution for your problem.

**Comment by milanjelisavcic** [comment]
> What’s your use case? Maybe we can find another solution for your problem.

I wanted to make a PDF that would preview the form with filled information but when printed, print the positioned information on the preprinted form.

**Comment by liZe** [comment]
> I wanted to make a PDF that would preview the form with filled information but when printed, print the positioned information on the preprinted form.

I’m not sure to fully understand what you expect. Could you please provide PDF samples (or images) of what you’d like to get?
