### ISSUE TITLE
wrong linebreaks in words containing parentheses

### ISSUE THREAD

**Issue by aschosser** [Kozea/WeasyPrint#203]
Strings containing parentheses eg. "Lehrer(innen)" are not treated as one single word. Sometimes there is a linebreak before "(" when the word appears at the end of a long line.

Simon mentioned that it is an issue with pango and that a possible solution would be to do line breaking directly in WeasyPrint.

Thank you
Andreas

**Comment by liZe** [comment]
See #301.

**Comment by liZe** [comment]
For the record: this bug was probably fixed by a new Pango version.
