### ISSUE TITLE
PDF failed when highchart axis labels are being cutoff

### ISSUE THREAD

**Issue by pareshbalar** [Kozea/WeasyPrint#2030]
Hi,

Here is the image of the chart rendered in my HTML. I am using the HighChart.

![image](https://github.com/Kozea/WeasyPrint/assets/10231683/ee8c85c6-2558-4326-a12b-832b23e0bd98)

The issue is when the labels are being cut off, weasyprint is not able to export it to PDF.

Getting the below error.

![image](https://github.com/Kozea/WeasyPrint/assets/10231683/fa5bf53b-a8cb-44ab-a7b5-7413bca78419)

**Workaround for me**
I tried adding a margin to the right side of the chart so that the chart does not cut off and the Weasyprint was able to convert it to PDF.

![image](https://github.com/Kozea/WeasyPrint/assets/10231683/3b43416e-a217-4de4-be7b-0de3f2be284e)

Output PDF:

![image](https://github.com/Kozea/WeasyPrint/assets/10231683/2e5f553b-8d1b-46f3-99b4-f5843f94a5ca)

**Comment by liZe** [comment]
Hi!

Thanks for your bug report.

Could you please share your HTML file so that we can reproduce the problem?

**Comment by pareshbalar** [comment]
Here is the HTML.

[chart.zip](https://github.com/Kozea/WeasyPrint/files/13816694/chart.zip)

Here is how HTML looks a like

![image](https://github.com/Kozea/WeasyPrint/assets/10231683/4812e41b-9c4a-47f8-afca-b41cb244509d)

We are first converting web pages to HTML and then converting HTML to PDF using Weasyprint.

Here is the crash log

![image](https://github.com/Kozea/WeasyPrint/assets/10231683/073567aa-c0bb-49d7-8a2a-e07edd7b9aed)

**Comment by pareshbalar** [comment]
Hi @liZe , Any update on this issue?

**Comment by liZe** [comment]
> Any update on this issue?

No, we would have written a new comment otherwise.

**Comment by alexandergitter** [comment]
In the code you uploaded, the issues seems to be (at partially) caused by one or more `tspan`'s having `visibility: hidden` set.
Here is a much simpler example that crashes in the same way:
```html
<svg width="100px" height="100px">
  <text>
    <tspan x="10" y="10" style="visibility: hidden">Text</tspan>
  </text>
</svg>
```

**Comment by liZe** [comment]
@alexandergitter Thanks for the simple sample!

I think that this issue is now fixed, feedback is welcome.

(Our current SVG test coverage is poor, don’t hesitate to add new tests if you’re interested!)
