### ISSUE TITLE
Timeout on generating pdf. [weasyprint.urls.URLFetchingError: TimeoutError: The read operation timed out]

### ISSUE THREAD

**Issue by AmoahDevLabs** [Kozea/WeasyPrint#2031]
I have deployed a django projects on render.com for testing but I'm getting an error from weasyprint. The error is as below. How do I get this error resolved?

```
File "/opt/render/project/src/.venv/lib/python3.11/site-packages/weasyprint/urls.py", line 251, in fetch
    raise URLFetchingError(f'{type(exception).__name__}: {exception}')
weasyprint.urls.URLFetchingError: TimeoutError: The read operation timed out
```

Or am I doing something wrong in my view?

```python
class StudentDetailPDFView(LoginRequiredMixin, StudentDetailMixin, SchoolContextMixin, DetailView):
    model = Student
    template_name = 'students/student_detail_pdf.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(**kwargs)

        html = render_to_string(self.template_name, context)
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'filename="{context["student"].get_full_name()}_detail.pdf"'
        css_url = request.build_absolute_uri(settings.STATIC_URL + 'css/pdf.css')
        weasyprint.HTML(string=html, base_url=request.build_absolute_uri()).write_pdf(response, stylesheets=[
            weasyprint.CSS(css_url)])
        return response
```

**Comment by liZe** [comment]
Hi!

If you want to use WeasyPrint with Django, you should use [Django-WeasyPrint](https://github.com/fdemmer/django-weasyprint) that takes care of many problems for you.

Here, the timeout is caused by your `request` taking too much time to get an answer. This problem sometimes happens when you launch your server with a single thread: your server is already answering your `get` request, but you need to get the result of another concurrent request, causing a deadlock. Maybe it’s unrelated, but one thing is sure: your server takes too much time to answer a concurrent GET request, for some reason.

You can try to use Django-WeasyPrint and see if it fixes the problem.

**Comment by AmoahDevLabs** [comment]
I able update the view with temporal fix it by removing css path from request.build_absolute_uri() method.
However timeout error still shows when I run the project with gunicorn whereas Django dev server shows no error.

How do I resolve this ?

_#Line issuing timeout error_
weasyprint.HTML(string=html, base_url=request.build_absolute_uri()).write_pdf(response, stylesheets=[
            weasyprint.CSS(css_url)])


_#Temporal Fix_

class StudentDetailPDFView(LoginRequiredMixin, StudentDetailMixin, SchoolContextMixin, DetailView):
    model = Student
    template_name = 'students/student_detail_pdf.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(**kwargs)

        html = render_to_string(self.template_name, context)
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'filename="{context["student"].get_full_name()}_detail.pdf"'
        css_url = settings.STATIC_ROOT + '/css/pdf.css'
        weasyprint.HTML(string=html).write_pdf(response, stylesheets=[
            weasyprint.CSS(css_url)], presentational_hints=True)
        return response

**Comment by liZe** [comment]
Please try to use Django-WeasyPrint and see if it fixes the problem.

**Comment by AmoahDevLabs** [comment]
Django-WeasyPrint works fine locally with both django dev server and gunicorn but rendering of  images on our test server (Render.com) issues an error on a missing package. Below is the error.

_function/symbol 'pango_context_set_round_glyph_positions' not found in library 'libpango-1.0.so.0': /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: pango_context_set_round_glyph_positions_

#views.py

```
class StudentDetailPDFView(LoginRequiredMixin, StudentDetailMixin, SchoolContextMixin, WeasyTemplateResponseMixin,
                           DetailView):
    model = Student
    template_name = 'students/student_detail_pdf.html'
    pdf_attachment = False  # Show PDF in-line by default

    def get_pdf_filename(self):
        # Generate the filename for the PDF
        student_full_name = self.get_object().get_full_name()
        return f"{student_full_name}_detail.pdf"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Additional context data if needed
        return context

    def get_pdf_stylesheets(self):
        # Define stylesheets for the PDF
        css_path = settings.STATIC_ROOT + '/css/pdf.css'
        return [
            css_path,
        ]

```

Since I'm using a free tier of Render  I do not  have access to install this package. I believe upgrading to a paid plan would give me privileges to rectify any error on Render as well as other platforms.

Weasyprint itself is really amazing and I really love to integrating it into my projects.

**Comment by liZe** [comment]
> Below is the error.

You need to install at least Pango 1.44. That’s a problem discussed in other issues such as #1670.

If you’re stuck with an older version of Pango, you can use an older WeasyPrint version such as 52.5 (but that’s not supported anymore.)

> Weasyprint itself is really amazing and I really love to integrating it into my projects.

Good to know, have fun with WeasyPrint!
