### ISSUE TITLE
Differences in rendering stylesheets - Weasyprint 52.5

### ISSUE THREAD

**Issue by dwasyl** [Kozea/WeasyPrint#2034]
Hi there,

Just wanted to share an experience I've had. Up until today I had a `weasyprint==52.5` installation generating PDFs that included a bootstrap 5 -based stylesheet just fine. The template included `sass_src` to compile it and everything worked fine. Then all of a sudden, one of the servers stopped rendering the stylesheets altogether.

There are some server differences, one running Python 2.9 and the other 3.7, etc. But up until today both worked fine. Then suddenly without other changes it stopped. Interestingly adding the `stylesheets=[CSS()]` to `write_pdf` worked great and solved the issue entirely.

It's challenging to debug when it works fine in one environment and not the other. Any idea what could have impacted the importing of a stylesheet from within the template?

**Comment by OttoAndrey** [comment]
Recently pdf stop generating for me too. It is happening when I call  `.write_pdf()`. Process fails without specific error :(

os: MacOS 14.2.1
python: 3.11.6

deps:
- weasyprint==60.2                         
 - cffi >=0.6
 - cssselect2 >=0.1
 - fonttools >=4.0.0
 - html5lib >=1.1
 - Pillow >=9.1.0
 - pydyf >=0.8.0
 - Pyphen >=0.9.1
 - tinycss2 >=1.0.0

**Comment by liZe** [comment]
Feel free to add a comment if you think that we can help you.
