### ISSUE TITLE
Process "ForkPoolWorker-9" pid:60701 exited with "signal 11 (SIGSEGV)"

### ISSUE THREAD

**Issue by OttoAndrey** [Kozea/WeasyPrint#2037]
Hi and thanks for very useful package!

Recently (after New Year) pdf generating through html stoped working. PDF generating doesn't work only for one of my projects on Django and locally (I am using macos).

pdf generating is working fine for:
debian dev env;
locally for simple terminal command from tutorial (`weasyprint https://weasyprint.org /tmp/weasyprint-website.pdf`);
locally for scripts through `python3 pdf_generating_example.py` which uses pdf generating (`HTML('https://weasyprint.org/').write_pdf('/tmp/weasyprint-website.pdf')`);

Only for one of my projects I got `Process "ForkPoolWorker-9" pid:60701 exited with "signal 11 (SIGSEGV)"` without any  :(

I tried: reinstall `weasyprint`, remove `.venv`, reboot system.

My setup:
MacOS 14.2.1
Django 4.2.9
weasyprint 60.2

Do you have suggests for me to check/reinstall something to understand whats wrong?..

**Comment by liZe** [comment]
Hi!

With no extra information, there’s not much we can do for you. Do you use the version provided by Homebrew?

**Comment by OttoAndrey** [comment]
> Hi!
> 
> With no extra information, there’s not much we can do for you. Do you use the version provided by Homebrew?

Yes. I reinstalled weasyprint through `brew reinstall weasyprint`

**Comment by liZe** [comment]
> Recently (after New Year) pdf generating through html stoped working.
> Yes. I reinstalled weasyprint through `brew reinstall weasyprint`

Then the problem is probably in one of Hombrew’s packages, and unfortunately there’s not much we can do for you about this. It’s probably possible to open an issue about this problem on [Hombrew’s GitHub page for core packages](https://github.com/Homebrew/homebrew-core/issues).

> I tried: reinstall `weasyprint`, remove `.venv`, reboot system.

Did you use Homebrew’s Python to build your virtual environment?

**Comment by OttoAndrey** [comment]
> Did you use Homebrew’s Python to build your virtual environment?

I am using python from pyenv. Like this

```bash
pyenv shell $(pyenv latest 3.11)

pyenv shell
>>>3.11.7

which python
>>>/Users/otto/.pyenv/shims/python

poetry env use $(which python) && poetry install && source .venv/bin/activate

poetry show weasyprint
name         : weasyprint                   
version      : 60.2                         
description  : The Awesome Document Factory 

dependencies
 - cffi >=0.6
 - cssselect2 >=0.1
 - fonttools >=4.0.0
 - html5lib >=1.1
 - Pillow >=9.1.0
 - pydyf >=0.8.0
 - Pyphen >=0.9.1
 - tinycss2 >=1.0.0
```

**Comment by OttoAndrey** [comment]
> In this case, you’re not using Homebrew’s Python. Please try to use it instead of the one from pyenv.

Oh, it helped! Thank you) It is working now, strange...

> It could also be useful to get the backtrace. Once your virtual environment is activated, could you try to launch `weasyprint --info`?

This command has same result under pyenv python and system python.

```bash
System: Darwin
Machine: arm64
Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
Release: 23.2.0

WeasyPrint version: 60.2
Python version: 3.11.7
Pydyf version: 0.8.0
Pango version: 15014
```

**Comment by liZe** [comment]
> Oh, it helped! Thank you) It is working now, strange...

Using Homebrew’s Python is always a good idea if you want to use other packages installed by Homebrew (such as Pango for WeasyPrint). Glad to see that it works for you!

> This command has same result under pyenv python and system python.

I asked that to know if WeasyPrint was crashing as soon as you launch it, but it looks like it doesn’t, even with pyenv’s Python, so it doesn’t help.
