### ISSUE TITLE
Table of content line breaking page number display

### ISSUE THREAD

**Issue by ewuerger** [Kozea/WeasyPrint#2046]
Hi dear weasyprint devs,

I have a bug where on almost too long table of content items  the page number is written to the next item such that two page numbers are displayed:
![image](https://github.com/Kozea/WeasyPrint/assets/50786483/2f7426b7-6c09-42c0-9027-436cf90c34c0)

If the item is way too long it is rendered correctly:
![image](https://github.com/Kozea/WeasyPrint/assets/50786483/53bbd9e9-920d-4122-b952-6db5d743544b)

Is there a way to handle this with CSS styling?

Thanks in advance!

**Comment by liZe** [comment]
Hi!

You should use leaders for that:

```html
<html>
  <head>
    <style>
      body { font-family: Arial }
      #toc { border: 1px solid; width: 14.5em }
      #toc a { color: inherit; text-decoration: none }
      #toc a::after { content: leader(' ') target-counter(attr(href), page) }
      h2 { break-before: page }
    </style>
  </head>
  <body>
    <h1>Book</h1>
    <ol id="toc">
      <li><a href="#chapter1">My First Chapter</a></li>
      <li><a href="#chapter2">The Second Very Long Chapter</a></li>
      <li><a href="#chapter3">Third</a></li>
    </ol>
    <h2 id="chapter1">Chapter 1</h2>
    <h2 id="chapter2">Chapter 2</h2>
    <h2 id="chapter3">Chapter 3</h2>
  </body>
</html>
```

![Capture d’écran du 2024-01-22 14-51-12](https://github.com/Kozea/WeasyPrint/assets/952243/2d8e1208-d4d5-4d72-92af-64bbb04296ef)

**Comment by ewuerger** [comment]
Thank you very much! That works.
