### ISSUE TITLE
Retain URL in pdf

### ISSUE THREAD

**Issue by LostKobrakai** [Kozea/WeasyPrint#2047]
When using weasyprint cli with a url I'd like to retain that url in the generated PDF, so I can refer back to it at a later time. Currently I only see metadata like title being set.

**Comment by liZe** [comment]
Hi!

To find a solution for your needs, could you please explain what’s your exact use case and how you currently use WeasyPrint to generate your documents?

**Comment by LostKobrakai** [comment]
I'm using the CLI to do `weasyprint [url] [path]` to power an automation I've setup. I'd love to have the url be retained in the pdf metadata, so I don't need to retain the url separately to the pdf generated.

**Comment by liZe** [comment]
There are different possibilities to put the URL in the PDF metadata.

- If you generate the source HTML, you can include the URL in the meta tags that will be automatically included in the PDF metadata.
- You can write a short Python script that changes the metadata of the [Document](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.document.Document).
- You can attach the URL as plain text in a [PDF attachment](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#cmdoption-a).
- You can use a third-party library such as ExifTool to add metadata (`exiftool -Subject='https://your-url.org/xxx' document.pdf`).

**Comment by LostKobrakai** [comment]
Ok, I had hoped there might be something with the CLI, though it kinda makes sense if this is also used with local urls. My usecase is for urls I don't control. I'll take a look at exiftool for my automation. Thanks for the suggestion.
