### ISSUE TITLE
OSError : cannot load library 'pango-1.0-0'

### ISSUE THREAD

**Issue by Leopold194** [Kozea/WeasyPrint#2057]
I have this error when i want to execute a command-line to convert html to pdf : OSError: cannot load library 'pango-1.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'

**Comment by liZe** [comment]
Hi!

You should carefully follow [the installation steps](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation). This [troubleshooting](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#missing-library) entry could help you too.

(You probably got these links in a message just before the error 😄)

**Comment by liZe** [comment]
Please add a comment if there’s anything we can do for you!

**Comment by Khnsimeon29** [comment]
yes do it
