### ISSUE TITLE
Firefox problem on showing the rendered SVG in PDFs

### ISSUE THREAD

**Issue by MohammadKhalatbari** [Kozea/WeasyPrint#2061]
I’m using the Weasyprint(V60,2) in a Django application.
after upgrading the version from 52,4 to 60,2, I have a problem showing the rendered SVGs in Firefox. Generated SVGs are fine in all browsers and PDF readers except Firefox. I have some extra borders or strokes on the rendered SVG when I open the generated PDFs on Firefox. And, I can not see the changed styles in Firefox. In the attached images, you can see the same PDF in Firefox and a PDF reader.
And it happened after upgrading Weasyprint. Do you know what is the problem?
<img width="919" alt="Screenshot 2024-02-09 at 10 20 26" src="https://github.com/Kozea/WeasyPrint/assets/12957138/6f98ca0d-42b3-4b03-ac87-013a90235c68">
<img width="1026" alt="Screenshot 2024-02-09 at 10 20 05" src="https://github.com/Kozea/WeasyPrint/assets/12957138/0cd5b10d-45ef-43ba-a787-a80c2bf21c30">

**Comment by liZe** [comment]
Hi!

Could you please share your SVG file, so that we can try to reproduce your problem?

**Comment by MohammadKhalatbari** [comment]
> Hi!
> 
> Could you please share your SVG file, so that we can try to reproduce your problem?

Sure,
I attached the generated SVG code. And, to make it clear how the program works, I will leave you a piece of code.
```
if pdf:
        driver = setup_chromedriver()
        plot.output_backend = "svg"
        svg = get_svgs(plot, driver=driver)[0]
        svg = fix_svg(svg)
        b64_svg = b64encode(svg.encode())
        tag = (
            '<img src="data:image/svg+xml;charset=utf-8;base64,%s">' % b64_svg.decode()
        )
        return mark_safe(f"{section_title}\n{tag}")
```
[SVG-file.txt](https://github.com/Kozea/WeasyPrint/files/14219616/SVG-file.txt)

**Comment by grewn0uille** [comment]
Hi @MohammadKhalatbari,

After testing your SVG with different PDF readers, indeed only Firefox shows the issue.
Some investigation seems to point that Firefox PDF reader doesn’t support / comply with a 0 opacity for text stroke.

You can open an issue on [Bugzilla](https://bugzilla.mozilla.org/home) with the attached PDF sample (uncompressed PDF, suits best  for debugging :))

Don’t hesitate to add the link to the issue here.
[sample.pdf](https://github.com/Kozea/WeasyPrint/files/14219954/sample.pdf)

**Comment by MohammadKhalatbari** [comment]
> Hi @MohammadKhalatbari,
> 
> After testing your SVG with different PDF readers, indeed only Firefox shows the issue. Some investigation seems to point that Firefox PDF reader doesn’t support / comply with a 0 opacity for text stroke.
> 
> You can open an issue on [Bugzilla](https://bugzilla.mozilla.org/home) with the attached PDF sample (uncompressed PDF, suits best for debugging :))
> 
> Don’t hesitate to add the link to the issue here. [sample.pdf](https://github.com/Kozea/WeasyPrint/files/14219954/sample.pdf)

I will do that. Thanks
