### ISSUE TITLE
Unexpected numbers appear when rendering a footnote with "float: footnote"

### ISSUE THREAD

**Issue by dmitryperets** [Kozea/WeasyPrint#2062]
With WeasyPrint 60.2, I am getting this strange rendering result which I cannot figure out...

Attached is a simple HTML with a footnote (generated by pandoc, so I cannot really influence the way how the footnote is represented):

```html
<p>Hello world and all that<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<section id="footnotes" class="footnotes footnotes-end-of-section" role="doc-endnotes">
  <hr />
  <ol>
    <li id="fn1">
      <p>This is a Pandoc-style footnote.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p>
    </li>
  </ol>
</section>
```

This is rendered perfectly fine:

![render1](https://github.com/Kozea/WeasyPrint/assets/48552949/d3872e10-e766-4e92-a6bd-f70d75d0ad09)

But then I add the following CSS (in order to move the footnote to the bottom of the page):

```css
section.footnotes {
    float: footnote;
    font-size: 12px;
}
```

The result is:

![render2](https://github.com/Kozea/WeasyPrint/assets/48552949/3c8bf961-d5b5-481a-9877-ca91b6517df8)

The footnote indeed moves to the bottom of the page, but notice the weird additional numbers "1" appearing in two places. 
Any idea where they are coming from...?

Replication step is straightforward, using the atteched files:
```
weasyprint footnotes.html footnotes.pdf
```

[footnotes.html.txt](https://github.com/Kozea/WeasyPrint/files/14222217/footnotes.html.txt)
[document.css.txt](https://github.com/Kozea/WeasyPrint/files/14222220/document.css.txt)

**Comment by liZe** [comment]
Hi!

Your CSS code doesn’t do what you think it does. 😄

The footnote section is rendered as a footnote entry, not a footnote section. So, the section doesn’t appear on the page, but at the bottom, just where footnote entries are supposed to be. The "1" number on the page at the top is the footnote number (that’s usually displayed as an exponent), and "1" at the bottom is the footnote number displayed before the footnote.

Here’s how footnotes are supposed to be used in HTML/CSS:
```html
<style>.footnote { float: footnote }</style>
<p>Hello world and all that<span class="footnote">This is a Pandoc-style footnote.</span></p>
```

I don’t know if Pandoc can generate this kind of HTML.

If you want to keep using the current HTML structure, you can probably find a workaround like:
```css
.footnotes li { float: footnote }
.footnotes li p { display: inline }
.footnotes { height: 0; overflow: hidden }
```
Note that it’s just a quick and dirty workaround, and that it’s probably broken in many ways. 😄

**Comment by dmitryperets** [comment]
Hi @liZe,

Thank you for the explanation!

> Here’s how footnotes are supposed to be used in HTML/CSS:

This is exactly how I was doing them before. Yes, I can do it with pandoc, using custom classes. But now I am trying to use the [native Pandoc Markdown syntax](https://pandoc.org/MANUAL.html#footnotes), and so this is the HTML it generates. So I was looking for a good way to style it. 

Anyway, your proposed CSS works excellent! It is rendered exactly the way I want it!
Thank you!
