### ISSUE TITLE
Can not save attached files in Acrobat Reader

### ISSUE THREAD

**Issue by kesara** [Kozea/WeasyPrint#2064]
This issue is in the current `main` branch (`8aecf3853490d271115acf7fe271a43897651644`) not in `60.2`.
So probably introduced with #1869.

The issue is Adobe Acrobat Reader (version: 2023.008.20470) cannot save attachments from PDFs generated from the `main` branch.
Acrobat  Reader shows the attachments but when you select *Save attachment* nothing happens.
This functionality works fine for PDFs generated with `60.2`.

Acrobat Reader also does not show the file size for attachments of PDFs created with the `main` branch while it does for `60.2`.

With [Poppler](https://poppler.freedesktop.org/)'s  `pdfdetach`, I can save the attached files from PDFs generated with both `60.2` and `main` branch.

### Example
Command:
```
weasyprint foobar.html foobar.pdf
```

`foobar.html`:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Foobar</title>
    <link href="foobar.xml", rel="attachment", type="application/xml", title="source" />
</head>
<body>
    <h1>Hello, World!</h1>
</body>
</html>
```

`foobar.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <foobar />
</root>
```

**Comment by liZe** [comment]
Hi!

Thanks for the report. Is this bug fixed by #2063?

**Comment by kesara** [comment]
https://github.com/Kozea/WeasyPrint/commit/586998ea8d593e5c31c067db12d4672806278be3 fixed that issue.
Thanks @liZe.

**Comment by liZe** [comment]
PDFs with attachments were valid for many libraries and validation tools (including Vera), but they were actually broken according to an online validator. Thanks for your feedback!
