### ISSUE TITLE
WeasyPrint Deployment on GCP Failing to Support Multiple Languages in PDF Conversion

### ISSUE THREAD

**Issue by arvindmn01** [Kozea/WeasyPrint#2080]
I am using WeasyPrint to convert HTML to PDF. The HTML file contains text in multiple languages such as **Hindi**, **Telugu**, and **Tamil**. WeasyPrint is functioning correctly on my local system, but upon deploying it on GCP, it fails to support the aforementioned languages. I haven't explicitly installed any dependencies for WeasyPrint.
I've simply defined `pip install WeasyPrint` in requirements.txt. Do I need to install additional dependencies to support multiple languages on the cloud? If so, how can I do that? <br>
Thanks in advance.

**Comment by liZe** [comment]
Hi!

You need to install fonts that support these languages, or to reference them with `@font-face` rules in your stylesheet.

**Comment by grewn0uille** [comment]
Feel free to reopen if needed.
