### ISSUE TITLE
WeasyPrint v61.1 executable is apparently recognized as Program:Win32/Wacapew.C!ml

### ISSUE THREAD

**Issue by braggpeaks** [Kozea/WeasyPrint#2081]
v61.1 of weasyprint.exe is recognized by Windows Defender as 
[Program:Win32/Wacapew.C!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Program%3AWin32%2FWacapew.C!ml)
I assume this is a false positive. I do not know how to prevent this false recognition and reported it via [this page](https://www.microsoft.com/en-us/wdsi/filesubmission).

**Comment by drboone** [comment]
The MS security tooling has apparently been flagging pyinstaller this way since at least 2021.

**Comment by braggpeaks** [comment]
The executable was confirmed by Microsoft as a false positive:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

It might be necessary to go through this for new releases, but it's rather straight forward, see link above. One has to provide a detection name, which in this case was: "An active 'Wacatac' malware was blocked".
