### ISSUE TITLE
page-break-* style properties do not work inside tables

### ISSUE THREAD

**Issue by szlend** [Kozea/WeasyPrint#209]
WeasyPrint handles automatic page breaks for tables, but any page-break-\* properties inside the table are ignored. This would be useful for adding manual page breaks before or after a row or grouping certain rows together so they're not separated between pages.

Edit: Row groups can be done by applying page-break-inside: avoid on tbody so that already works. But there's still a case for other page-break properties.

**Comment by liZe** [comment]
Related to #36.

**Comment by jeffgabhart** [comment]
I'm running into this as well. Is there a way to force a page break for each row ?

**Comment by liZe** [comment]
> I'm running into this as well. Is there a way to force a page break for each row ?

Unfortunately, I don't think so :sad:.
