### ISSUE TITLE
Arbitrary File Read via Unvalidated URL in urllib.request.urlopen

### ISSUE THREAD

**Issue by sec1-security** [Kozea/WeasyPrint#2098]
Vulnerability Description:
https://github.com/Kozea/WeasyPrint/blob/b195aabafdf5e705fcff100015197fbff72fea0c/weasyprint/urls.py#L223
The default_url_fetcher function is vulnerable to arbitrary file reading through unvalidated URLs. The function uses urllib.request.urlopen to fetch the contents of a provided URL, but it does not properly validate or sanitize the url parameter before passing it to urlopen.

The specific vulnerability lies in the following code:
def default_url_fetcher(url, timeout=10, ssl_context=None):
    # ...
    if UNICODE_SCHEME_RE.match(url):
        url = iri_to_uri(url)
        response = urlopen(
            Request(url, headers=HTTP_HEADERS), timeout=timeout,
            context=ssl_context)
        # ...
The url parameter is passed through the iri_to_uri function, which applies URL encoding but does not validate or restrict the URL scheme. This means that if an attacker provides a file:// URL, it will be accepted and used in the urlopen call.

For example, an attacker could provide a URL like file:///etc/passwd to read the contents of the /etc/passwd file on the system.

Remediation:
To mitigate this vulnerability, will recommend

1. Validate and sanitize the url parameter before using it in urllib.request.urlopen. This can include:
  - Checking and restricting the URL scheme to allow only specific schemes (e.g., http://, https://) and disallowing file:// or other potentially dangerous schemes.
  - Sanitizing the URL to remove any potentially malicious characters or sequences.
  - Implementing a whitelist approach to allow only specific URLs or domains.

2. Consider using a library like requests that provides higher-level abstractions and built-in security features for making HTTP requests.
3. Ensure that the application runs with the least privileges necessary and restrict access to sensitive files and directories.

**Comment by liZe** [comment]
Yes, WeasyPrint can access all files, just as any browser by default: open file:///etc/passwd in your browser and you’ll read your file.

Everything is explained in [documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#access-to-local-files), with multiple ways to avoid this normal behaviour if you don’t want to allow it.
