### ISSUE TITLE
PDF restricted to single page in Letter when using body height: 100%

### ISSUE THREAD

**Issue by michaellisitsa** [Kozea/WeasyPrint#2100]
Going from v60.2 to v61, there is an issue with content being cut off at one page. It appears to be related to minor rounding errors in the "Letter" page size that causes the below newly added code to falsely think the content is overflowing.

I have made a replit here
https://replit.com/@mlisitsa/Python-Weasyprint-Bug-Print-Cut-to-Single-Page#script.py

The issue occurs when you have `body {height: 100%}` and `@page {size: letter, margin: 15mm}`.

The offending code looks to be https://github.com/Kozea/WeasyPrint/commit/bc971312ac847d2b7d62de5d8e0189f1fe435c9b, where the `resume_at` gets set to `None`, even though there is more content in the `body` tag. 

https://github.com/Kozea/WeasyPrint/blob/1ac1594cf3fe326ff09c4035d158b65fdc684b71/weasyprint/layout/block.py#L743-L750

The resume_at then gets returned eventually to the make_page function 

https://github.com/Kozea/WeasyPrint/blob/1ac1594cf3fe326ff09c4035d158b65fdc684b71/weasyprint/layout/page.py#L645-650

When I debugged it with `Letter`, you have the calculated position_y is approximately equal but ever so slightly bigger.

```
box.position_y + box.height
>> 999.3070866141732

position_y
>> 999.3070866141733
```

When using `A4` page size, they are the same, and content prints correctly over multiple pages

```
position_y
>> 1065.8267716535433
box.position_y + box.height
>> 1065.8267716535433
```

**Comment by liZe** [comment]
Hi!

Thanks for reporting this issue. A lot of rounding errors have been fixed in the past to detect overflow on pages, that’s another case we have to handle.
