### ISSUE TITLE
Fillable form field limits

### ISSUE THREAD

**Issue by dkrasnikow** [Kozea/WeasyPrint#2101]
Hi all,

While trying to create a PDF with fillable forms, I've noticed that the character input limit provided in the source code isn't respected in the output PDF file, e.g.

`<input type="text" maxlength="50" placeholder="[Enter company name address]" autocomplete="on" wrap="soft">`

doesn't produce any errors when printing. However, when I try to enter more than 50 characters into this field, it works. 

The same concerns `textarea`. 

Is this an expected behavior or am I missing something? Thank you for any assistance in advance.

**Comment by liZe** [comment]
> Is this an expected behavior or am I missing something? Thank you for any assistance in advance.

It’s not supported yet. Looks like the feature is actually available in the PDF specification, that seems "quite easy" to support.

Interested in opening a pull request? I can guide you, of course!

**Comment by dkrasnikow** [comment]
Is there really anything easy about PDF format? )) I could, of course, open a pull request, but unfortunately I am much more a tech writer rather than an engineer (however, quite a happy tech writer since I've found your library and can finally stop using a browser for PDF output :P ).  So unfortunately the only use of me at this point perhaps would be my feedback.

**Comment by grewn0uille** [comment]
@dkrasnikow, if you can give a try to the main branch, your feedback is welcome :)
