### ISSUE TITLE
question of download attachment

### ISSUE THREAD

**Issue by zsmatrix62** [Kozea/WeasyPrint#2110]
Hi,

Im able to embed the attachments using link tags like:

```html    
<link href="att.txt" rel="attachment" title="source" />
<link href="att.zip" rel="attachment" title="source" />
```

how can i make a link in my html template and then download it from generated pdf? currently when i use `a` tag with href="att.txt" it always links to local file path not embeded one.

Thanks.

**Comment by liZe** [comment]
Hi!

You can do this with `<a href="att.txt" rel="attachment">test</a>`. It will only work if your PDF reader supports the feature.

**Comment by zsmatrix62** [comment]
Im using adobe acrobat reader but below codes does not work, the `Download att.txt` in my converted pdf is not clicable. ಥ_ಥ

do you have any exmaples of a full script? Thank you very much in advance!

```html
<html>
  <head>
    <link rel="stylesheet" href="styles/sop-doc.css" />
    <link href="att.txt" rel="attachment" title="source" />
    <link href="att.zip" rel="attachment" title="source" />
  </head>
  <body>
    <a href="att.txt" rel="attachment" download="att.txt">Donwload att.txt</a>
</body>
</html>

**Comment by liZe** [comment]
> Im using adobe acrobat reader but below codes does not work, the `Download att.txt` in my converted pdf is not clicable. ಥ_ಥ

I don’t have Acrobat Reader, but it works with my PDF reader. Maybe it’s not supported by Adobe Reader. Do you have another PDF that works with Adobe Reader?

**Comment by liZe** [comment]
Please add a comment if there’s anything more we can do for you.
