### ISSUE TITLE
Auto-expand font size

### ISSUE THREAD

**Issue by hadmut** [Kozea/WeasyPrint#2115]
Feature proposal:

I was looking for a way to print some (possibly multi-line text after word-wrapping) text (where I don't know the text or the length in advance) as large as possible fitting into an outer box. Use case is printing labels on a label printer.  The interactive MacOS software coming with the printer can do this, but I'm looking for a way to automatically get it done by a job on Linux to avoid entering every single label text on the keyboard. 

As an example, have something like

<div class="sticker">
Apples Oranges
</div>

autoexpanded to the size given in the CSS style for div.sticker 

Unfortunately, HTML+CSS seem to be unable to do the job. Therefore, there is javascript libraries to do this task like jquery and textfit. Since weasyprint does not support javascript, they are unusable here. 

Would be great to have some way, e.g. a proprietary CSS extension, to adjust a font size so that a given text fills it's outer box element as much as possible.  

regards

**Comment by liZe** [comment]
Hi!

Thanks for your feature proposal.

It’s a good idea, but… We already spend a lot of time to support the existing CSS specification and drafts. It’s hard to implement these specifications, and it’s even harder to write these specifications, so we’re trying hard to avoid proprietary extensions for which we’d have to do both. And of course, writing specifications and implementing a solution is always the "easy" part: the hard part is to maintain them. 😄

So, unless there’s already a CSS draft for this (maybe there is?), and even if it would be very useful, we won’t implement it. If you **really** want to see it implemented, the first step is to search for an existing open an issue in the W3C issue tracker, and to open a new one if needed.

**Comment by liZe** [comment]
Don’t hesitate to add a comment if there’s anything more we can do!
