### ISSUE TITLE
How to control the background color of hovered links in a generated PDF?

### ISSUE THREAD

**Issue by araichev** [Kozea/WeasyPrint#2116]
The [docs say](https://doc.courtbouillon.org/weasyprint/v52.5/features.html#selectors-level-3) the :hover pseudo-class won't do it, so what will?
Thanks for your attention.

**Comment by grewn0uille** [comment]
Hi @araichev,

I don’t think there is something to dynamically change style in PDF.

**Comment by araichev** [comment]
I should add that i'm currently seeing a light yellow background color on hover.
I'd like to change that color.

**Comment by liZe** [comment]
> I should add that i'm currently seeing a light yellow background color on hover.
> I'd like to change that color.

This color is added by your PDF reader, it’s not defined in the PDF file, and I don’t think that it can be. You’ll get different renderings with different PDF readers.

**Comment by araichev** [comment]
Ah OK, thanks for the explanation.
Sounds like what i'm after can't be done at present.
