### ISSUE TITLE
Covert multiple html files

### ISSUE THREAD

**Issue by trans** [Kozea/WeasyPrint#212]
I could not find any documentation on how to convert multiple html files into a single PDF. How does one do it?

**Comment by david-alejandro-reyes-milian** [comment]
Hello, guys, what about creating a 2000 pages PDF full of images(10 images per page, images with size>=500KB). So far I'm not able to do it since my memory is not enough :(. I was thinking that actually, one approach would be to render separated pages, keep it on disk, and merge at the end. Is this possible?

**Comment by SimonSapin** [comment]
@david-alejandro-reyes-milian WeasyPrint alone cannot do that, but several other tools support concatenating pages from multiple PDF files into a single file. They probably use less memory than WeasyPrint rendering everything at once (included keeping decoded uncompressed images in memory).

**Comment by david-alejandro-reyes-milian** [comment]
Hi @SimonSapin, thanks for fast answer. You mentioned before a `.copy` feature from WeasyPrint. Is it deprecated? Why do you point to another tool when WeasyPrint has the feature? Could you please mention those tools? Thanks

**Comment by SimonSapin** [comment]
`.copy()` is still there but it operates on WeasyPrint’s intermediate Python objects, not PDF files. It’s not gonna help you with memory use.

As to these tools, there’s among others pdftk on the command line and pdfrw in Python. The latter is already used by WeasyPrint, and their README links to this example code: https://github.com/pmaupin/pdfrw/blob/master/examples/cat.py

**Comment by david-alejandro-reyes-milian** [comment]
True, thanks, will give it a try :+1:  Cheers!

**Comment by david-alejandro-reyes-milian** [comment]
Good, also taking a look at: `https://github.com/Kozea/WeasyPrint/commit/344cb08f60f82f52e4d8cfcc36c019b2ae5f1947`. Thanks for helping.
