### ISSUE TITLE
Add support for border-image properties

### ISSUE THREAD

**Issue by xavidotron** [Kozea/WeasyPrint#2124]
[CSS Backgrounds and Borders Module Level 3](https://www.w3.org/TR/css-backgrounds-3/#border-images) defines a series of properties to use images for box borders. Especially with SVG images, this can allow for fancy borders beyond what can otherwise be defined in CSS.

This includes the following properties:
* border-image
* border-image-source
* border-image-slice
* border-image-width
* border-image-outset
* border-image-repeat

I'd like to implement these, and since (unless you prefer otherwise) I'd like to implement this in a series of pull requests instead of all in one huge pull request, I wanted to create an issue to attach my pull requests to.

**Comment by liZe** [comment]
Closed by #2125.
