### ISSUE TITLE
Cropped PDF after generating it from HTML

### ISSUE THREAD

**Issue by nomercy3** [Kozea/WeasyPrint#2127]
Hi!

We've recently updated our project to use latest Weasyprint (61.*) and encountered unwanted behaviour: when we generate PDF files from HTML template, it will come out cropped — containing only 1 page instead of multiple pages. Attached you will find HTML Template we are using.

I am curious if this problem known? Since we did not have this problem on 60.* version of the library, seems pretty fresh. 

If you need any additional info to test it, please let me know!
[WeasyPrintHtmlTemplate.html.zip](https://github.com/Kozea/WeasyPrint/files/15011599/WeasyPrintHtmlTemplate.html.zip)

**Comment by liZe** [comment]
Hi!

That’s because of `html, body { height: 100% }`. Your main container’s height is the height of one page, so your document has only one page.

If you have this rule to ensure that your html and body tags take at least one page’s height, you can use `max-height` instead of `height`.
