### ISSUE TITLE
FontConfiguration object has no attribute _folder

### ISSUE THREAD

**Issue by LukasKlement** [Kozea/WeasyPrint#2128]
With version 61.2 I'm frequently getting this exception:

Exception ignored in: <function FontConfiguration.__del__ at 0x7ff94e0745e0>
Traceback (most recent call last):
File "/home/igeltech/.virtualenvs/renderenv/lib/python3.9/site-packages/weasyprint/text/fonts.py", line 258, in __del__
     rmtree(self._folder, ignore_errors=True)
AttributeError: 'FontConfiguration' object has no attribute '_folder'

I do not know how to reproduce it, it appears randomly.

**Comment by liZe** [comment]
Thanks for the bug report.

I get this error too when I launch tests. It’s strange:
https://github.com/Kozea/WeasyPrint/blob/245e4f5fa2cad60af241db0c4d76abb1201f1348/weasyprint/text/fonts.py#L259-L261

As `self._folder` is created when the object is initialized, I don’t see how it could not be present…

**Comment by liZe** [comment]
This bug can happen when a `FontConfiguration` object is destroyed before its initialization is finished. It can for example happen when tests are launched in parallel: when one test fails, other processes are stopped, maybe at this wrong place.

Your use case is probably different, but the fix should work for you too.
