### ISSUE TITLE
No border on table

### ISSUE THREAD

**Issue by greycat70** [Kozea/WeasyPrint#213]
`<html><head><title>Title Here</title></head>`
`<body><table border="1"><tr><td>Col 1</td><td>Col 2</td></tr></table></body>`
`</html>`

The generated PDF has no borders, at all.  Neither around the outside of the table, nor between the columns.

**Comment by Kunal31** [comment]
I am Currently using version 0.30 of WeasyPrint. I am using CSS for table border as suggested, still i am not able to get border for html table.

**Comment by liZe** [comment]
It works for me. Here is an example you can try:

```html
<style>table, td { border: 1px solid black }</style>
<table><tr><td>Col 1</td><td>Col 2</td></tr></table>
```

I get borders around tables and cells.

**Comment by gcocce** [comment]
I doesn't work

**Comment by liZe** [comment]
> I doesn't work

![Capture d’écran de 2020-10-21 17-37-56](https://user-images.githubusercontent.com/952243/96743345-31813080-13c4-11eb-9a2b-4daf6f88fd68.png)

You’ll have to be a little bit more specific, or I won’t be able to help you :wink:.

**Comment by gcocce** [comment]
> > I doesn't work
> 
> ![Capture d’écran de 2020-10-21 17-37-56](https://user-images.githubusercontent.com/952243/96743345-31813080-13c4-11eb-9a2b-4daf6f88fd68.png)
> 
> You’ll have to be a little bit more specific, or I won’t be able to help you .

I erase my comment cos it was an accident. I does work. Thanks

**Comment by itzzmesid** [comment]
> ```css
> table, td { border: 1px solid }
> ```

Thank you! Worked perfectly
