### ISSUE TITLE
unexpected hyphenation, dash seems to be replaced with a hyphen

### ISSUE THREAD

**Issue by dmitryperets** [Kozea/WeasyPrint#2132]
Consider the following simple HTML input:

```html
<pre><code>kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml</code></pre> 
```

When rendering it with my CSS, it so happens that the text "kube-flannel.yml" is wrapped:

![image](https://github.com/Kozea/WeasyPrint/assets/48552949/2de96db1-d1bd-4c41-9add-41ec12cafe6f)

And this is totally fine. But what is not fine is that the dash seems to be rendered into a hyphen and then also something weird seems to happen to the line wrap... If I try to copy-paste this text from the PDF into a text editor, I get:

```
kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kubeflannel.
yml
```

So, there is a line break after the dot and the dash simply disappears. 
Could you please help to understand what happens here and whether we can control it...?

Attaching the HTML, the PDF and the CSS.
[hyphen.html.txt](https://github.com/Kozea/WeasyPrint/files/15075283/hyphen.html.txt)
[hyphen.pdf](https://github.com/Kozea/WeasyPrint/files/15075284/hyphen.pdf)
[document.css.txt](https://github.com/Kozea/WeasyPrint/files/15075285/document.css.txt)

WeasyPrint version 61.1

**Comment by liZe** [comment]
Hi!

> And this is totally fine. But what is not fine is that the dash seems to be rendered into a hyphen

I’ve checked the PDF source, it’s exactly the same character than the one in "-f" or in "flannel-io".

> If I try to copy-paste this text from the PDF into a text editor, I get:

That’s your PDF reader trying to be smart: when there’s an dash at the end of the line, it thinks that the word is split and removes it. It doesn’t happen with all PDF readers: the ones I’ve tried (Evince, Firefox) are "stupid" and keep the dash.

There’s a way to make PDF readers not copy some characters, like hyphens really used to split words, or markers for example. It’s not in WeasyPrint, but it would be useful. Unfortunately, you want the opposite feature (force a PDF reader to keep a character), but I don’t think that it exists.

**Comment by liZe** [comment]
Feel free to add a comment if there’s anything more we can do for you!
