### ISSUE TITLE
Weasyprint.exe : Fontconfig error: Cannot load default config file: No such file: (null)

### ISSUE THREAD

**Issue by aditya119** [Kozea/WeasyPrint#2138]
Executing the weasyprint.exe works on some machines but fails on others.
Please let me know if there are some prerequisites to run the exe properly, I think the GTK and python installation is needed only for using it as a library.
I have seen other issues but they focus on running weasyprint python library on Windows, whereas I'm just trying to run the exe.

It is working fine on my development system, but fails with above error when deploying to server.

I have added various stack traces that I could extract:

```
WeasyPrint exited with code -1073741819.
Error: Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: "memory", line 2: SHGetFolderPathA failed
Fontconfig error: "memory", line 3: SHGetFolderPathA failed
Fontconfig error: No writable cache directories
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: "memory", line 2: SHGetFolderPathA failed
Fontconfig error: "memory", line 3: SHGetFolderPathA failed
Fontconfig error: No writable cache directories
```

```
>weasyprint.exe --info abc.html abc.pdf
Fontconfig error: Cannot load default config file: No such file: (null)
System: Windows
Machine: AMD64
Version: 10.0.17763
Release: 2019Server

WeasyPrint version: 61.2
Python version: 3.12.2
Pydyf version: 0.9.0
Pango version: 15014
```

```
>weasyprint --debug abc.html abc.pdf
Fontconfig error: Cannot load default config file: No such file: (null)
INFO: Step 1 - Fetching and parsing HTML - abc.html
Fontconfig error: Cannot load default config file: No such file: (null)
INFO: Step 3 - Applying CSS
INFO: Step 4 - Creating formatting structure
INFO: Step 5 - Creating layout - Page 1
```

Thanks in advance.

**Comment by liZe** [comment]
Hi!

> Please let me know if there are some prerequisites to run the exe properly, I think the GTK and python installation is needed only for using it as a library.

No, the exe file includes everything.

I suspect that WeasyPrint can’t reach the default Windows folders that contain fonts, for your system and for your user.

**Comment by aditya119** [comment]
Thanks.
Can you please share if there is a way to find out what files/paths weasyprint is looking for?
That would help me figure out a fix.

**Comment by liZe** [comment]
> Can you please share if there is a way to find out what files/paths weasyprint is looking for?

Disclaimer: I don’t use Windows at all.

Fontconfig’s default config searches fonts in WINDOWSUSERFONTDIR and WINDOWSFONTDIR, that seem to be constant values only used in Fontconfig. Here’s the code:

https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/main/src/fcxml.c

So I suspect that the unavailable folder is `CSIDL_LOCAL_APPDATA`, which according to [this documentation](https://learn.microsoft.com/en-us/windows/win32/shell/csidl) should be something like `C:\Documents and Settings\<username>\Local Settings\Application Data`.

**Comment by aditya119** [comment]
Thanks for your response.
I have looked at the folders in both server and local system, the structure, files and env variables are same.
I'm not able to find the difference.
Thanks for providing the link to source code, I'll check if I can debug and figure out the root cause.

**Comment by liZe** [comment]
On the server, do you launch your script with a user that has a home directory? Sometimes, on servers, scripts are launched by specific users with less rights than "normal" users.

**Comment by aditya119** [comment]
Yes, the user on server is less privileged and not a 'normal' user, but I tested by running WeasyPrint.exe manually from Admin user as well and got the same error.

**Comment by aditya119** [comment]
Not sure about the root cause, but adding the weasyprint.exe file path to PATH environment variable seems to fix the problem.

**Comment by liZe** [comment]
> Not sure about the root cause, but adding the weasyprint.exe file path to PATH environment variable seems to fix the problem on server.

OK, that’s strange. Let’s close the issue for now, and reopen it if the problem comes back.

**Comment by BCompertoreWAG** [comment]
I'm also experiencing this error and unfortunately adding weasyprint as a Path environment variable didn't solve the problem. @aditya119 was there anything else you remember doing to fix this issue? Any help is much appreciated!

**Comment by BCompertoreWAG** [comment]
Thanks for the fast reply! Unfortunately that didn't work either, anything else you can think for me to try?

**Comment by aditya119** [comment]
Unfortunately, i can't think of anything else.
Adding below c# code that worked for me, maybe you can figure it there's something missing.
```
    string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
    string fontconfigPath = Path.Combine(localAppData, "fontconfig");

        using var process = new Process();
        process.StartInfo.FileName = _weasyprintExePath;
        process.StartInfo.Arguments = $"\"{inputHtmlPath}\" \"{outputPdfPath}\"";
        process.StartInfo.UseShellExecute = false;
        process.StartInfo.RedirectStandardOutput = true;
        process.StartInfo.RedirectStandardError = true;
        process.StartInfo.EnvironmentVariables["PATH"] = _weasyprintExePath;
        process.StartInfo.EnvironmentVariables["FONTCONFIG_PATH"] = fontconfigPath;
        process.StartInfo.UseShellExecute = false;

        process.Start();
```

**Comment by BCompertoreWAG** [comment]
No worries, appreciate the help @aditya119! @liZe have you happen to see similar issues for other users?

**Comment by liZe** [comment]
> No worries, appreciate the help @aditya119! @liZe have you happen to see similar issues for other users?

No.

As explained above, Fontconfig is configured to look for config files in `CSIDL_LOCAL_APPDATA`. Does this folder exist for the user launching WeasyPrint?

**Comment by BCompertoreWAG** [comment]
Yes, the folder does exist and I see the "fontconfig" subfolder which contains a "cache" folder.

**Comment by liZe** [comment]
Then I don’t know why this message appears on your computer.

Is WeasyPrint able to use the fonts installed on your system?

**Comment by sachinvelmeni** [comment]
This is happening for me also. I have setup the env. paths and everything the fontconfig folder exists too.

**Comment by liZe** [comment]
> This is happening for me also. I have setup the env. paths and everything the fontconfig folder exists too.

Could you try a recent build, like [this one](https://github.com/Kozea/WeasyPrint/actions/runs/11085110960). Maybe #2238 fixed the problem.
