### ISSUE TITLE
Wrong line wrap

### ISSUE THREAD

**Issue by jjsarton** [Kozea/WeasyPrint#215]
Ia have a document with the following

<p>
some text ... ... ... (<a href="#">link text</a>) following text
</p>
This is rendered as follow:

some text ... ... ... (
link text) following
text

Wrapping after the "(" character appear wromg for me.

**Comment by liZe** [comment]
Even if the title of the bug can be misleading, it's technically the same as #163, as :before creates a pseudo-element. Same problem, same solution: we just have to rewrite the whole text module to find the correct line breaks :p.
