### ISSUE TITLE
Grid support with errors (print-css-rocks)

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#2152]
The print-css.rocks example

https://github.com/zopyx/print-css-rocks/tree/master/lessons/lesson-grid

renders with errors:

Correct rendering:

<img width="711" alt="Bildschirmfoto 2024-05-09 um 07 28 43" src="https://github.com/Kozea/WeasyPrint/assets/594239/d59259bd-a368-4a8b-9f84-fc6534a974d2">

Weasyprint rendering:

<img width="716" alt="Bildschirmfoto 2024-05-09 um 07 28 36" src="https://github.com/Kozea/WeasyPrint/assets/594239/22eeaeab-b989-4f71-ad17-ceff6376ac91">

**Comment by zopyx** [comment]
Is this fixed in 62.1?

**Comment by liZe** [comment]
> Is this fixed in 62.1?

No, it will be in 62.2.
