### ISSUE TITLE
Issue when trying to write a pdf with the openssl_md5 function in your library

### ISSUE THREAD

**Issue by SamDth** [Kozea/WeasyPrint#2156]
When trying to write a HTML string to a pdf with the writepdf() function i  the HTML class it throws an error that openssl_md5() takes at most one argument, but two are given. Can I fix it in my Code or does this need to be fixed in the library?

![error](https://github.com/Kozea/WeasyPrint/assets/170091081/99f8854f-36a8-4067-9483-5bcd11f43c45)

**Comment by liZe** [comment]
Hi!

The second argument of md5 has been added in Python 3.9, you probably use an older version of Python. The latest versions of WeasyPrint [require Python 3.9](https://doc.courtbouillon.org/weasyprint/v62.1/first_steps.html).
