### ISSUE TITLE
Failure when building wheel for 62.1 from pypi

### ISSUE THREAD

**Issue by himalayanelixir** [Kozea/WeasyPrint#2157]
Hey! I was trying to update the WeasyPrint Docker (https://github.com/4teamwork/weasyprint-docker) to the latest version and ran into this failure when building the wheel for 62.1. Wasn't sure how to fix it. :/ 

```bash
38.50 >>> py3-weasyprint: Fetching https://files.pythonhosted.org/packages/3b/0b/b2b165439954c1d4ed4045ad95cb7fb2bd0c696e3b90ecba56533b8aa12f/weasyprint-62.1.tar.gz
38.50 >>> py3-weasyprint: Checking sha512sums...
38.51 weasyprint-62.1.tar.gz: OK
38.51 >>> py3-weasyprint: Unpacking /var/cache/distfiles/weasyprint-62.1.tar.gz...
38.55 * Getting build dependencies for wheel...
38.61 * Building wheel...
38.68 Successfully built weasyprint-62.1-py3-none-any.whl
38.88 ImportError while loading conftest '/work/py3-weasyprint/src/weasyprint-62.1/tests/conftest.py'.
38.90 tests/conftest.py:18: in <module>
38.90     from weasyprint import HTML
38.90 weasyprint/__init__.py:419: in <module>
38.90     from .css import preprocess_stylesheet  # noqa: I001, E402
38.90 weasyprint/css/__init__.py:30: in <module>
38.90     from .validation import preprocess_declarations
38.90 weasyprint/css/validation/__init__.py:4: in <module>
38.90     from tinycss2 import parse_blocks_contents, serialize
38.90 E   ImportError: cannot import name 'parse_blocks_contents' from 'tinycss2' (/usr/lib/python3.11/site-packages/tinycss2/__init__.py)
38.93 >>> ERROR: py3-weasyprint: check failed
38.93 >>> py3-weasyprint: Uninstalling dependencies...
```

**Comment by liZe** [comment]
Hi!

You probably need to update tinycss2 (and possibly other dependencies).

**Comment by himalayanelixir** [comment]
Thanks for the super quick reply! Looking that the APKBUILD ([link](https://github.com/himalayanelixir/weasyprint-docker/blob/872ae8f7fbc18c5fd1ab5685a7b5c266acbee26f/packages/py3-weasyprint/APKBUILD#L15)) I'm working with, I'm not specifying a version. So I'm pretty sure it's pulling latest?

The issue can be recreated by running `docker compose up` in that repo ([link](https://github.com/himalayanelixir/weasyprint-docker))

**Comment by liZe** [comment]
You use [Alpine 3.19.1](https://github.com/himalayanelixir/weasyprint-docker/blob/872ae8f7fbc18c5fd1ab5685a7b5c266acbee26f/Dockerfile#L1), whose version of tinycss2 is [1.2.1](https://pkgs.alpinelinux.org/packages?name=py3-tinycss2&branch=v3.19&repo=&arch=&maintainer=). You need tinycss2 [1.3.0+](https://doc.courtbouillon.org/weasyprint/v62.1/first_steps.html#installation).

**Comment by liZe** [comment]
And WeasyPrint is already packaged for Alpine really, really quickly, you can probably just use Alpine’s edge packages?

**Comment by himalayanelixir** [comment]
oh ic, that makes sense. Just checked the docker image repo and the maintainer actually updated it (for the first time in 5 months) to use WeasyPrint 62.1 last night. It all works now.

Thank you so much for your help. :)
