### ISSUE TITLE
@page formatting elements

### ISSUE THREAD

**Issue by jjsarton** [Kozea/WeasyPrint#216]
css3 has some element which shall be supported. see http://www.w3.org/TR/css-gcpm-3/.
Such feature may allow to dynimically assign the content for @page-???

**Comment by liZe** [comment]
@jjsarton Running elements have been added, does it fit your needs?

**Comment by liZe** [comment]
Let's say it does.

**Comment by jeffgabhart** [comment]
So running() and element() are supported now?
Should the docs be updated?
http://weasyprint.readthedocs.io/en/latest/features.html#css

**Comment by liZe** [comment]
> So running() and element() are supported now?

No. My bad.

- [Running elements as defined by the spec](https://www.w3.org/TR/css-gcpm-3/#running-elements) are **not** supported, but
- [Running elements based on named strings](https://www.w3.org/TR/css-gcpm-3/#named-strings) work, and should be enough if you don't need markup.
