### ISSUE TITLE
python api: set created date

### ISSUE THREAD

**Issue by till** [Kozea/WeasyPrint#2160]
I am trying to set the created date using the metadata class/object:

```python
        meta_data = weasyprint.document.DocumentMetadata(
            authors = [self.meta_data['author']],
            title = self.meta_data['title'],
            generator = self.meta_data['generator'],
            description = self.meta_data['subject'],
            created = datetime.now(timezone.utc).isoformat(),
        )
        self.documents[0].metadata = meta_data
```

Everything is set, but the date in the PDF is empty. It seems like, `datetime.now(timezone.utc).isoformat()` doesn't create a w3c accepted date format. Does anyone know how to work around that?

**Comment by liZe** [comment]
Hi!

Here’s some code that works for me:
```python
from weasyprint import HTML, document
from datetime import datetime, timezone

html = HTML('https://weasyprint.org/').render()
metadata = document.DocumentMetadata(
    title='Super title',
    created=datetime.now(timezone.utc).isoformat(),
)
html.metadata = metadata
html.write_pdf('/tmp/weasyprint-website.pdf')
```

I don’t know what’s different in your example, there’s probably something wrong in the code around your sample.

**Comment by till** [comment]
I'll have a look, thanks so much for responding quickly!

**Comment by till** [comment]
I am not sure what I did on Friday, but it does work now. Shows created date in the inspector when I open the PDF. Sorry for the noise. :) And thanks for providing weasyprint!
