### ISSUE TITLE
Table Auto Column Sizing and &nbsp;

### ISSUE THREAD

**Issue by pmjdebruijn** [Kozea/WeasyPrint#2173]
When using \&nbsp; to prevent awkward line breaks, table colum auto sizing gets worse:

![table-nbsp-colsize-defect](https://github.com/Kozea/WeasyPrint/assets/929583/f8e9f3d0-754e-43dd-9a71-34f3f195e698)

You'll note that the the border between the second and third column shifts to the left, while there is more empty space available on the right, which seems very counter intuitive and suboptimal.

Example:
[table-nbsp-colsize-defect.zip](https://github.com/user-attachments/files/15525714/table-nbsp-colsize-defect.zip)

**Comment by liZe** [comment]
Hi!

I actually get the same results with browsers, I doubt that this is a bug.

With Firefox:
![Capture d’écran du 2024-06-02 18-25-54](https://github.com/Kozea/WeasyPrint/assets/952243/0981443c-974a-4357-a8c6-7e512def7fbe)

With Chrome:
![Capture d’écran du 2024-06-02 18-27-23](https://github.com/Kozea/WeasyPrint/assets/952243/6dd24c1a-3f94-4d37-b834-49d8a3ee3cd7)

The auto sizing algorithm relies on the minimum width of the column, that changes with the nbsp. That’s why we have different results.

**Comment by liZe** [comment]
Please add a comment if there’s anything more we can do about this.
