### ISSUE TITLE
Is @page:last supported by weasyprint

### ISSUE THREAD

**Issue by SachinVNaik** [Kozea/WeasyPrint#2176]
## Explanation
I'm converting a an HTML file to PDF, and i want to set different footer only for last page, 

If the number of pages are fixed this can be achieved using selectors like `@page:nth(page number)`
but in my case last page contains a table which might spill over to new pages, in this case is there a way to set the different footer only for last page ? 

is there something like `@page:last` ?

**Comment by liZe** [comment]
Hi!

Unfortunately, there’s no `@page :last` selector in [the specification](https://drafts.csswg.org/css-gcpm/#the-first-page-pseudo-element).

But you can use a [running element](https://drafts.csswg.org/css-gcpm/#running-elements) at the end of your document, that will be visible only on the last page.

**Comment by SachinVNaik** [comment]
HI, 

Thanks for the answer, 

This resolves the issue partially, 

we can set a footer on last page using this approach, but if we want to set different footers for first `n-1` pages and a different footer for `n`th page, it's not achievable from this method, is my understanding right ?

**Comment by liZe** [comment]
> we can set a footer on last page using this approach, but if we want to set different footers for first `n-1` pages and a different footer for `n`th page, it's not achievable from this method, is my understanding correct?

You can use one running element for odd pages and another one for even pages, you just have to define them both in your HTML before the first page ends (the beginning of the HTML page is a good idea).

**Comment by SachinVNaik** [comment]
assume there are 6 pages in a PDF, my requirement is first 5 pages should have one footer and 6th page should have different footer, 6 is just an example i took, the number of pages will be different based on amount of data. how can this be achieved using odd and even page selectors ?

**Comment by liZe** [comment]
> how can this be achieved using odd and even page selectors ?

Sorry, I thought that `n` and `n-1` were selectors, such as `:nth(2n)` that means "odd". Forget that!

> assume there are 6 pages in a PDF, my requirement is first 5 pages should have one footer and 6th page should have different footer

```html
<style>
  footer { position: running(footer) }
  @page { @bottom-center { content: element(footer) } }
  h1 { break-before: page }
</style>
<footer>All pages but last</footer>
<h1>First page</h1>
<h1>Second page</h1>
<h1>Third page</h1>
<h1>Last page</h1>
<footer>Only last page</footer>
```

**Comment by liZe** [comment]
Feel free to add a comment if there’s anything more we can do for you!

**Comment by qdphung19** [comment]
> > how can this be achieved using odd and even page selectors ?
> 
> Sorry, I thought that `n` and `n-1` were selectors, such as `:nth(2n)` that means "odd". Forget that!
> 
> > assume there are 6 pages in a PDF, my requirement is first 5 pages should have one footer and 6th page should have different footer
> 
> <style>
>   footer { position: running(footer) }
>   @page { @bottom-center { content: element(footer) } }
>   h1 { break-before: page }
> </style>
> <footer>All pages but last</footer>
> <h1>First page</h1>
> <h1>Second page</h1>
> <h1>Third page</h1>
> <h1>Last page</h1>
> <footer>Only last page</footer>

Hello,
Your code has helped me a lot, but I have an issue. When I generate content into a PDF dynamically, if there is more than one page, your code works very well. However, when there is only one page, your code still displays the footer "All pages but last", whereas I would like it to show "Only last page" if there is only one page.
Do you have a solution for this? Thank you very much!

**Comment by qdphung19** [comment]
Hello,
Your code has helped me a lot, but I have an issue. When I generate content into a PDF dynamically, if there is more than one page, your code works very well. However, when there is only one page, your code still displays the footer "All pages but last", whereas I would like it to show "Only last page" if there is only one page.
Do you have a solution for this? Thank you very much!

> > how can this be achieved using odd and even page selectors ?
> 
> Sorry, I thought that `n` and `n-1` were selectors, such as `:nth(2n)` that means "odd". Forget that!
> 
> > assume there are 6 pages in a PDF, my requirement is first 5 pages should have one footer and 6th page should have different footer
> 
> <style>
>   footer { position: running(footer) }
>   @page { @bottom-center { content: element(footer) } }
>   h1 { break-before: page }
> </style>
> <footer>All pages but last</footer>
> <h1>First page</h1>
> <h1>Second page</h1>
> <h1>Third page</h1>
> <h1>Last page</h1>
> <footer>Only last page</footer>
