### ISSUE TITLE
font-feature-settings: "tnum" seems to be ignored

### ISSUE THREAD

**Issue by martijnhartlief** [Kozea/WeasyPrint#2177]
Are font-feature-settings supported?

**Comment by liZe** [comment]
Hi!

It seems to work for me:
```html
<body style="font-family: Fira Sans">
  <div>Not tabular: 01234567890</div>
  <div style="font-variant-numeric: tabular-nums">Tabular: 01234567890</div>
  <div style="font-feature-settings: 'tnum'">Also tabular: 01234567890</div>
</body>
```

![Capture d’écran du 2024-06-06 17-21-21](https://github.com/Kozea/WeasyPrint/assets/952243/c3927cc5-8244-4cd7-83c8-25ab6a633344)

I’ve used [Fira Sans](https://github.com/mozilla/Fira/blob/master/otf/FiraSans-Medium.otf). Maybe your font doesn’t support this OpenType feature?

**Comment by martijnhartlief** [comment]
Hey liZe, thanks for the quick reply!

I'm using [Lora](https://github.com/cyrealtype/Lora-Cyrillic/blob/main/fonts/otf/Lora-Regular.otf). 

According to https://fontdrop.info/ the ttf, otf and woff all support tnum. The web preview I made works, but it's just not showing up in the PDF. 

Do I need to do something specific to the font loading?

**Comment by liZe** [comment]
Here’s what I get with your example:

![Capture d’écran du 2024-06-06 20-34-19](https://github.com/Kozea/WeasyPrint/assets/952243/b256bbb6-aa0b-41c6-936b-6c0921d1bd37)

Are you sure that the font you’re using is the one from your link? Otherwise I don’t know what’s wrong. Maybe using the `--verbose` CLI option could give interesting information.

**Comment by martijnhartlief** [comment]
After fiddling around I found out our dev server renders just fine....
The exact same code and weasyprint version on my dev machine unfortunately doesn't. 
The only difference being I'm using Mac OSX.

I'm using a few wrappers, but I'll come back to you with the cli output.

**Comment by liZe** [comment]
> The exact same code and weasyprint version on my dev machine unfortunately doesn't.

Maybe you have another font with the same name installed system-wide?

**Comment by martijnhartlief** [comment]
Indeed I have. It is the exact same file as I load from the font directory.

But after I removed it, it worked. So I reinstalled it again and it keeps working... So perhaps it wasn't the same?

Thanks for helping me out!
