### ISSUE TITLE
Flex layout does handle break-inside

### ISSUE THREAD

**Issue by inspiran** [Kozea/WeasyPrint#2183]
Break-inside isn't working as it supposed to do. 

Here is the gist:
https://gist.github.com/inspiran/4d1d4975c3ba430d9c0a07dc6cfcdb34

<img width="332" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/372447/6e0d0bcd-b1f5-4aba-983e-53dd7f9dca70">

**Comment by liZe** [comment]
This bug is now fixed and tested, but unfortunately there are many, many bugs left with flex layout…
