### ISSUE TITLE
Overflow issue with rotated text

### ISSUE THREAD

**Issue by alessandroghigi** [Kozea/WeasyPrint#2193]
Hi! We're experiencing a bug when some rotation is applied to a div element: if the "not" rotated text would not fit the page, then the rotated text doesn't work either, even if there is room for the entire div to be displayed. Find attached the pdf file, and here it is the html code. Some workarounds like break-inside: avoid or overflow: visible have been tested with no luck.

Thanks!

```
<html>
   <head>
      <title>PDF</title>
      <style id="79340657-abf4-49cc-8f1a-8eb113815280_style" type="text/css">@page { size: 62.00mm 100.00mm; margin: 0mm; }
         div.composition-ae271749-c795-440b-baa4-77994ea68c3a {color:rgb(0,0,0);font-family:Arial;font-weight:normal;line-height:12px;font-size:10px;font-style:normal;text-align:center;opacity:1;z-index:3;position:relative;vertical-align: middle;}
      </style>
   </head>
   <body>
      <div id="79340657-abf4-49cc-8f1a-8eb113815280_container000" style="transform: rotate(0deg) scale(1, 1); width: 100%; height: 100%; left: 0mm; top: 0mm; position: absolute; user-select: none; pointer-events: none;">
         <div style="border:1px solid red;position:absolute;left:110px;top:365px;width:315px;transform:rotate(270deg);transform-origin:top left;">
            <div class="composition-ae271749-c795-440b-baa4-77994ea68c3a"><span class="groupName" attrid="72027">AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA AAAAAAAAAA</span></div>
         </div>
      </div>
   </body>
</html>
```

[test_weasy.pdf](https://github.com/user-attachments/files/15973066/test_weasy.pdf)

**Comment by liZe** [comment]
Hi!

It’s a bit difficult to understand how transformations work in CSS: they change the appearance, but don’t change the layout. So, the layout, including pagination, is done just as if there’s no transformation. If you remove your transformation, the box is at the bottom of the page, that’s why it’s split.

The easiest solution is often to put the element a the top of the page, and use a translation that doesn’t change the layout. In your case, you can remove the `top` and `left` properties, and set them in transform: `transform: translate(110px 365px) rotate(270deg)`.

![Capture d’écran du 2024-06-25 16-44-32](https://github.com/Kozea/WeasyPrint/assets/952243/e8729ffe-28c4-4ae1-83af-0e02c05865ad)

**Comment by alessandroghigi** [comment]
That's a great solution, it works. Thanks!!
