### ISSUE TITLE
Extend WeasyPrint with Rest API and provide it as a service

### ISSUE THREAD

**Issue by nirikash** [Kozea/WeasyPrint#2194]
Hi, 

We have actively used WeasyPrint in context of SchweizerischeBundesbahnen (SBB) open source Polarion integration.
To facilitate this integration, we have developed a REST API around the WeasyPrint Python library.

This API has been packaged into a Docker container and is available as an open-source project on GitHub: https://github.com/SchweizerischeBundesbahnen/weasyprint-service.

We are exploring opportunities for collaboration to enhance and extend the capabilities of this REST API. We believe your expertise and interest in the WeasyPrint project could be invaluable in this context. If you find this project interesting, we would love to discuss potential collaboration ideas with you.

Regards,
Andrei.

**Comment by grewn0uille** [comment]
Hi @nirikash,
We answered your email, let’s continue the chat by email then!
