### ISSUE TITLE
Cannot find pango on Windows 10 (Python)

### ISSUE THREAD

**Issue by m-gallesio** [Kozea/WeasyPrint#2197]
Greetings.

I am trying to run [mkdocs-with-pdf](https://github.com/orzih/mkdocs-with-pdf) on Windows 10.

My environment:
- Windows 10
- Python 3.12.4 downloaded from the [official website](https://www.python.org/downloads/)
- Pango 1.52.2 installed via MSYS2 per [official instructions](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows)
- Environment variable `WEASYPRINT_DLL_DIRECTORIES` set to the MSYS2 `bin` directory per [official instructions](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#missing-library)
- weasyprint 62.3 installed via pip GLOBALLY (as administrator, no virtual environment)

Running `weasyprint` on its own yields the following error:

```

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\weasyprint.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\weasyprint\__init__.py", line 419, in <module>
    from .css import preprocess_stylesheet  # noqa: I001, E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\weasyprint\css\__init__.py", line 28, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "C:\Program Files\Python312\Lib\site-packages\weasyprint\css\computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\Program Files\Python312\Lib\site-packages\weasyprint\text\ffi.py", line 434, in <module>
    pango = _dlopen(
            ^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\weasyprint\text\ffi.py", line 420, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'pango-1.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'
```

I have tried running weasyprint in a [Cygwin](https://cygwin.com/) shell, which still fails but also yields the following message:

![immagine](https://github.com/Kozea/WeasyPrint/assets/46478501/9464aa1a-e02b-4ad9-add0-d5de0f6f1995)
(Roughly translates as "Cannot find entry point `hb_set_invisible_glyph` in DLL `libpango-1.0.0.dll`".)

Am I missing something?

As further reference I have tried replicating the whole installation process in a WSL environment (Ubuntu 20.04) and it works.

**Comment by liZe** [comment]
Hi!

The only supported way to install WeasyPrint is the one described in the documentation, please follow it carefully. Some people reported that using Python from the Python website doesn’t work, and that you have to install Python from Microsoft Store (see #2105). Maybe it will help?

I don’t know why, I’d be interested to know why, but I don’t have Windows installed on my computer. And to be honest I don’t want to spend days to debug this, we already spent **weeks** trying to get a reliable way to use WeasyPrint on Windows (and it doesn’t include the time spent to generate an executable…) If you want to take this time, that would be helpful, and we would be really grateful!

**Comment by m-gallesio** [comment]
Understandable, I get this kind of issue is very painful to sort out.
For now I think I will stick with WSL or whip up a dedicated Linux environment. Maybe I will have more time to dig into this in the future, but this does not seem likely.
Thank you anyway for your quick response.

**Comment by liZe** [comment]
WSL generally works well.

Have fun with WeasyPrint!
