### ISSUE TITLE
Weasyprint 61.x - PDF.__init__() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by jbpenrath** [Kozea/WeasyPrint#2204]
I'm using Weasyprint 61.x in one of my project. Yesterday I rebuilt my project (that's reinstalled all packages). Since this build, all my tests testing PDF generation are failing with the following error : `PDF.__init__() takes 1 positional argument but 3 were given`.

As I do not pin exactly Weasyprint, I first believed that the version 61.2 introduces a breaking change but actually not, rollback to a previous minor version does not fix the issue.

But, I think this is due to the upprade of a sub-dependency.

**From my side, upgrading to version 62 has fixed the issue** and all is working well so it's ok but I still believe something is wrong with Weasyprint 61.x.

**Comment by liZe** [comment]
Hi!

That’s a duplicate of #2202 and #2203.

**Comment by LarryJason** [comment]
I just switched to weasyprint 62 and I solved my problem, thank you
