### ISSUE TITLE
Bug: pydyf version 0.11.0 breaks PDF generation

### ISSUE THREAD

**Issue by paultop6** [Kozea/WeasyPrint#2207]
Call to pydyf.PDF in weasyprint/pdf/__init__.py no longer works with pydyf version 0.11.0 (works fine with 0.11.0).

The function signature has been changed from `__init__(self, version=None, identifier=None)` to `__init__(self)`

**Comment by grewn0uille** [comment]
Hi,

That’s a duplicate of #2206, https://github.com/Kozea/WeasyPrint/issues/2205, https://github.com/Kozea/WeasyPrint/issues/2204, https://github.com/Kozea/WeasyPrint/issues/2203, https://github.com/Kozea/WeasyPrint/issues/2202 and https://github.com/Kozea/WeasyPrint/issues/2200.
