### ISSUE TITLE
content overflow in multi page issue with header/footer.

### ISSUE THREAD

**Issue by MalekianDev** [Kozea/WeasyPrint#2212]
I have a header with `position: fixed;` style (data got blurred because of confidentiality):

![1403-05-08 17 42 26](https://github.com/user-attachments/assets/9c1545f1-a91f-48bb-aa01-4cc54c52a991)

And a fixed footer also:

![footer](https://github.com/user-attachments/assets/8a003bf8-403a-4c16-861e-10350916e935)

& When texts or any type of content get overflowed, this happened:

![issue](https://github.com/user-attachments/assets/0efc6bfd-9006-4a3a-a538-594510692af0)

As you can see, texts overflowed to the some parts of footer on current page & header in next page!

How can i handle that?

**Comment by liZe** [comment]
Hi!

`position: fixed` doesn’t change the layout of other boxes, that can be displayed on top of the fixed element. If you want to have a header repeated on each page with nothing on top of it, you can put the header in the page margin with [running elements](https://drafts.csswg.org/css-gcpm/#running-elements). If it’s just an image, you can even display it as the background of the page margin.

**Comment by MalekianDev** [comment]
@liZe Thanks a lot!
