### ISSUE TITLE
Weasyprint dependency 'gobject-2.0-0' installation error on Railway

### ISSUE THREAD

**Issue by osahene** [Kozea/WeasyPrint#2221]
I am using this dockerfile configuration for my django project

FROM python:3.12.2-slim-bullseye

# Install system dependencies

RUN apt-get update && apt-get install -y \

    python3-pip \

    python3-cffi \

    python3-brotli \

    libpango1.0-0 \

    libpangoft2-1.0-0 \

    libharfbuzz-subset0 \

    libffi-dev \

    libcairo2 \

    libcairo2-dev \

    libjpeg62-turbo-dev \

    libgdk-pixbuf2.0-0 \

    libgdk-pixbuf2.0-dev \

    libgobject-2.0-0 \

    libgobject2.0-dev \

    build-essential \

    && apt-get clean

# Set environment variables

ENV LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

# Set the working directory

WORKDIR /PAQSBackend

# Copy the application code

COPY . /PAQSBackend/

# Install Python dependencies

RUN pip install -r requirements.txt

# Copy the WSGI entry point

COPY PAQSBackend.wsgi /PAQSBackend/PAQSBackend.wsgi

# Command to run the application

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "PAQSBackend.wsgi"]

The build and deployment runs fine. However, when I run the project, I get this error message

File "/opt/venv/lib/python3.11/site-packages/cffi/api.py", line 827, in loadbackend_lib

 raise OSError(msg)

OSError: cannot load library 'gobject-2.0-0': gobject-2.0-0: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

I would want to know what is actually happening and also how to resolve this

**Comment by liZe** [comment]
Hi!

WeasyPrint is packaged for Debian, that’s the easiest way to get WeasyPrint working.

If you really want to install it with pip, you only have to install [the list of packages given in the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#debian-11), some of your packages are useless.

> File "/opt/venv/lib/python3.11/site-packages/cffi/api.py", line 827, in loadbackend_lib

You use a Python 3.11 installation on a Python 3.12 Docker image. There’s probably something wrong in your configuration. :smile:

**Comment by osahene** [comment]
Well noted. I tried to change the python version in the dockerfile to 3.11 and also made a separate RUN for wesayprint and also removed the numerous packages. Here is the dockerfile

FROM python:3.11-slim-bullseye

WORKDIR /app

ENV PIP_DEFAULT_TIMEOUT=100 \
    # Allow statements and log messages to immediately appear
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    # disable a pip version check to reduce run-time & log-spam
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    # cache is useless in docker image, so disable it to reduce image size
    PIP_NO_CACHE_DIR=1
# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-brotli \
    build-essential \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 

RUN apt install weasyprint

# Set environment variables
ENV LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

# Set the working directory

# Copy the application code
COPY . /app

# Install Python dependencies
RUN  pip install -r requirements.txt --no-cache-dir --compile

RUN apt-get -y purge gcc libc-dev python3-dev

# Add all application code from this folder, including deployment entrypoints
COPY --chown=python:python ./ /app


# Create staticfiles folder
RUN mkdir -p staticfiles && \
    chown -R python:python staticfiles

# Copy the WSGI entry point
RUN chmod +x /app/deployment/server-entrypoint.sh && \
    chmod +x /app/deployment/worker-entrypoint.sh

# Command to run the application
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "PAQSBackend.wsgi"]

EXPOSE 8000
CMD [ "/app/deployment/server-entrypoint.sh" ]

After running it, I had this error

  File "/root/.nix-profile/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/payments/urls.py", line 2, in <module>
    from .views import  (
  File "/app/payments/views.py", line 23, in <module>
    from weasyprint import HTML
  File "/opt/venv/lib/python3.11/site-packages/weasyprint/__init__.py", line 419, in <module>
    from .css import preprocess_stylesheet  # noqa: I001, E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/weasyprint/css/__init__.py", line 28, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "/opt/venv/lib/python3.11/site-packages/weasyprint/css/computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/opt/venv/lib/python3.11/site-packages/weasyprint/text/ffi.py", line 431, in <module>
    gobject = _dlopen(
              ^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/weasyprint/text/ffi.py", line 420, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': gobject-2.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

Please, what am I doing wrong again? I need your assistance

**Comment by liZe** [comment]
Your problem is not the Python version of your Docker image, it’s that you install another version of Python in parallel of the one provided by your Debian image.

>"/root/.nix-profile/lib/python3.11/importlib/init.py"

I have the impression that you install another version of Python with Nix. That would explain why it doesn’t work.

WeasyPrint works with `apt install weasyprint`. You can launch `weasyprint --info` or `python3 -m weasyprint --info` and see that it works well. The problem is that you install and use another version of Python for your app.

Please use the Python version provided by Debian, not another one installed elsewhere by Nix. If you really want to use Python from Nix (why do you use Nix?), install WeasyPrint’s dependencies with Nix too.

I’m sorry, but we don’t provide free integration support here: that’s WeasyPrint’s bug tracker, and the problem here is in your stack configuration, not in WeasyPrint’s code or documentation. (And I’ve never used Nix in my life, I’m definitely not the best person to help you! :smile:)
