### ISSUE TITLE
Pango library missing 

### ISSUE THREAD

**Issue by saguileran** [Kozea/WeasyPrint#2225]
I am working on Ubuntu 24.04 and with Python 3.12. After installing WeasyPrint using "sudo apt" and "pip install" I have not been able to solve the following problem:

OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'

what can I do?

**Comment by liZe** [comment]
Hi,

WeasyPrint is packaged for Ubuntu, you don’t even need to use pip.

```
sudo apt install weasyprint
weasyprint --info
```

Does it work for you?

**Comment by rasarkar** [comment]
I'm having this same issue, but on macOS 14.6. For some reason, the error only occurs if I use psycopg 3 (not psycopg2). I've tried installing weasyprint using both pip and brew, but I still get the same error. I currently have pango 1.54.0 installed. I'm pretty sure that the error has something to do with where libraries are installed, but I haven't been able to get further than that

**Comment by liZe** [comment]
> I'm having this same issue, but on macOS 14.6 using python 3.10.5.

That’s not the same problem, please open a new issue.

**Comment by saguileran** [comment]
> Hi,
> 
> WeasyPrint is packaged for Ubuntu, you don’t even need to use pip.
> 
> ```
> sudo apt install weasyprint
> weasyprint --info
> ```
> 
> Does it work for you?

I removed weasyprint from pip and installed as same as you said, but I still have the same error executing `weasyprint --info`. I want to use it in a Python project.

**Comment by liZe** [comment]
> I removed weasyprint from pip and installed as same as you said, but I still have the same error executing `weasyprint --info`.

Then there’s something really wrong with your Ubuntu installation.

When you type these two lines in a fresh terminal, you get the Pango error? If so, there’s nothing I can do to help you. Maybe you’ll get more useful help on a Ubuntu forum.

**Comment by saguileran** [comment]
The problem is because I am using Python through Anaconda, so I have to install pango with the conda command:

```bash
 conda install anaconda::pango 
```
