### ISSUE TITLE
Windows V62.3 triggers virus alert in Kapersky again (FYI)

### ISSUE THREAD

**Issue by bm98** [Kozea/WeasyPrint#2226]
This is just for your information ...
the exe file triggered as of today 13-Aug-2024 with the current virus database in Kapersky.
Have sent it to Kapersky for reconsideration but it may cause others (Defender etc.) to trigger as well.

Is there anything to avoid this issue popping up with further releases? 
I think it is not appropriate to ask anybody to switch their virus checker off in order to install it and then mark it as exception.

**Comment by liZe** [comment]
Hi!

> This is just for your information ...

Thanks for the report. It’s already been reported earlier in #2092.

> I think it is not appropriate to ask anybody to switch their virus checker off in order to install it and then mark it as exception.

Unfortunately, we’re not responsible for Kaspersky’s trojan list. It’s already been reported, but they don’t care. It’s definitely a problem in their virus detection heuristic (the executable contains Python code, and that’s seen as a threat), and we’re not powerful enough to fix a $700M-revenue company piece of software :smile:.

If you find a solution, don’t hesitate to add a comment here!

**Comment by bm98** [comment]
Got a fast reply from Kapersky

--
Hello,

Sorry, it was a false detection. It will be fixed.
Thank you for your help.

Best regards, Danila, Malware Analyst
--

**Comment by liZe** [comment]
> Got a fast reply from Kapersky

Yes, they remove the specific reported version quickly, but unfortunately don’t fix the heuristic that will detect future versions as virus.
