### ISSUE TITLE
Pango library missing (macOS)

### ISSUE THREAD

**Issue by rasarkar** [Kozea/WeasyPrint#2229]
I am working on macOS 14.6 and with Python 3.10.5. I have not been able to solve the following problem:

`OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'`

I've tried installing WeasyPrint using both pip and brew, but I get the same error. I have pango 1.54 installed.

**Comment by liZe** [comment]
Hi!

If you launch `brew install weasyprint` and then launch `weasyprint`, does it work?

**Comment by rasarkar** [comment]
I can run "weasyprint --version" on the command line. But if I try to import from weasyprint in my python code, I still get the error

**Comment by liZe** [comment]
Are you sure that your `python3` command leads to Homebrew’s Python 3? What does `which python3` gives you?

**Comment by rasarkar** [comment]
`/usr/bin/python3`

**Comment by liZe** [comment]
Then that’s why it doesn’t work. You have to use Homebrew’s Python, that is in this folder: `$(brew --prefix python)/libexec/bin`.

More about Homebrew’s Python in [the documentation](https://docs.brew.sh/Homebrew-and-Python).

**Comment by rasarkar** [comment]
Thank you for your help. I believe the issue is that brew requires python 3.12, but I'm currently using python 3.10. I'll try to run my project on python 3.12, and see if that fixes the library issue
