### ISSUE TITLE
Flex column layout - a question

### ISSUE THREAD

**Issue by lafar6502** [Kozea/WeasyPrint#2235]
Hi, i think i need to confirm something

I'm trying to obtain a 2-column layout based on flex 
Similar to the picture below (as shown in the browser).
But weasyprint doesn't keep that layout in pdf created, instead the content boxes are moved to next two pages and in the last page - only the second column remains. I suppose this is the way weasyprint handles flex columns. But maybe there's a way to split the content into 2 or more columns that would be flowed 'equally' without introducing unexpected page breaks?

I know i can experiment with table-based layout, but it has its own quirks, so maybe there's another way that's already well known for weasyprint users?

Thanks!

![image](https://github.com/user-attachments/assets/e4949c8c-594b-4a45-ade4-48dd719261c1)

The results of transforming this into pdf can be seen in the attached file.
[test_flex.zip](https://github.com/user-attachments/files/16692737/test_flex.zip)

**Comment by liZe** [comment]
> But weasyprint doesn't keep that layout in pdf created, instead the content boxes are moved to next two pages and in the last page - only the second column remains. I suppose this is the way weasyprint handles flex columns. But maybe there's a way to split the content into 2 or more columns that would be flowed 'equally' without introducing unexpected page breaks?

Yes, that’s because of #1967.

As far as I can tell, the best way to do this with WeasyPrint (until this bug is fixed) is to use tables.

**Comment by lafar6502** [comment]
Yep, thanks - came to same conclusion yesterday, no success with flex or grid layouts - tables seem to be better fit for the purpose.
