### ISSUE TITLE
Debian 11 - Installation Problem

### ISSUE THREAD

**Issue by ngyss** [Kozea/WeasyPrint#2236]
Hello,

I'm running a Debian 11 bullseye version and I cannot install a version upper than 59.0

Debian version:
`PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

Weasyprint info

> System: Linux
Machine: x86_64
Version: #1 SMP Debian 5.10.205-2 (2023-12-31)
Release: 5.10.0-27-amd64

> WeasyPrint version: 59.0
Python version: 3.9.2
Pydyf version: 0.6.0
Pango version: 14602

I'm trying to upgrade the version of pydyf but I stuck to 0.60...
Do you know how to install the 0.11 required?

Thanks

**Comment by liZe** [comment]
Hi!

> I'm trying to upgrade the version of pydyf but I stuck to 0.60...

I don’t understand what you’re trying to do. Do you want to update WeasyPrint to 60.0?

If you want to install the latest version of WeasyPrint, you’ll have to create a virtual environment as explained in [the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#linux). And if you want to install a specific version of a package, you can use the syntax described in [pip’s documentation](https://pip.pypa.io/en/stable/cli/pip_install/#examples).

**Comment by liZe** [comment]
Don’t hesitate to add a comment if there’s anything we can do.
