### ISSUE TITLE
Multiple HTML files in a single PDF

### ISSUE THREAD

**Issue by fredericvergnaud** [Kozea/WeasyPrint#2237]
Hello,
First, thanks a lot for this awsome tool, it changed my life :)
I've read [this issue](https://github.com/Kozea/WeasyPrint/issues/212#issuecomment-52408306 ) but as I'm not a pro in Python, I don't understand where `documents` come from in the line `all_pages = [p for p in doc.pages for doc in documents]` 
Here's my script : 

```python
from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration

font_config = FontConfiguration()
css = CSS('book_html_files/custom_style.css', font_config=font_config)

# The following works very good and output 2 PDF files
html_introduction = HTML('book_html_files/test/introduction.html')
html_introduction.write_pdf("introduction.pdf", stylesheets=[css], font_config=font_config)
html_rvest = HTML('book_html_files/test/rvest.html')
html_rvest.write_pdf("rvest.pdf", stylesheets=[css], font_config=font_config)

# The following part is ok
doc_introduction = html_introduction.render(font_config=font_config)
doc_rvest = html_rvest.render(font_config=font_config)

# When I do this, it's still ok
doc_introduction.copy(doc_introduction.pages[::2]).write_pdf('introduction_odd_pages.pdf')
doc_introduction.copy(doc_introduction.pages[1::2]).write_pdf('introduction_even_pages.pdf') 

# But I'm stuck on this : I don't understand where documents come from
all_pages_introduction = [p for p in doc_introduction.pages for doc in documents]
```

I think it's my lack of understanding of python syntax ...
Thanks for your help !

**Comment by liZe** [comment]
Hi!

> First, thanks a lot for this awsome tool, it changed my life :)

It changed ours too!

> I don't understand where `documents` come from

`documents` is just a list of your documents. In your case:
```py
documents = [doc_introduction, doc_rvest]
all_pages = [page for document in documents for page in document.pages]
doc_introduction.copy(all_pages).render('document.pdf')
```

(The original comment has the wrong order for the `all_pages` "for" loops.)

If your goal is just to concatenate PDF files, it’s probably better to use a dedicated lib such as [pypdf](https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html): you’ll have a real toolkit to play with pages and metadata, and the code will be simpler. Using WeasyPrint’s `copy()` to concatenate documents is more a smart hack than a clean feature. :smile:

**Comment by fredericvergnaud** [comment]
Ok, I didn't understand documents was just a list !
Many thanks ! It works perfectly !
I don't use Weasyprint simply to concatenate PDFs. I'm working on a quarto book (qmd) that I render in HTML, and then I use Weasyprint to create the final PDF of all the chapters. By the way, I'll probably have more questions later, especially about the table of contents or adding page numbers. If you could give me some useful links, that would be great !

**Comment by liZe** [comment]
> I don't use Weasyprint simply to concatenate PDFs. I'm working on a quarto book (qmd) that I render in HTML, and then I use Weasyprint to create the final PDF of all the chapters.

That’s cool!

> By the way, I'll probably have more questions later, especially about the table of contents or adding page numbers. If you could give me some useful links, that would be great !

You can check [WeasyPrint’s samples](https://weasyprint.org/#samples) with useful examples (including a table of contents and page numbers) and the related source code. You can also read [CourtBouillon’s blog](https://www.courtbouillon.org/blog-articles/), especially the CSS tricks entries that will give you simple examples on specific topics.

Have fun with WeasyPrint!
