### ISSUE TITLE
svg rendering - Failed to render SVG image error

### ISSUE THREAD

**Issue by lafar6502** [Kozea/WeasyPrint#2239]
Hi, i'm attaching a test case (SVG image within html) where Weasyprint doesn't render SVG at all - there is an error message reported on console.

`ERROR: Failed to render SVG image`
but no information about what exactly is the problem

[test_p1.zip](https://github.com/user-attachments/files/16726687/test_p1.zip)

https://github.com/Kozea/WeasyPrint/actions/runs/10515859855

Best regards
RG

**Comment by liZe** [comment]
Thanks for the report.

The image can’t be rendered because markers (startarrow and endarrow) are not included in your file. We should render the image without the markers instead.

**Comment by lafar6502** [comment]
Thanks, you're right - markers were missing. But after removing the markers - still the picture is not rendered correctly.
But this time i'm not getting any error message.

Here's the test case - updated svg.
[test_p2.zip](https://github.com/user-attachments/files/16729627/test_p2.zip)
(let me know if this should be registered as new issue, can't reopen this one)

RG
