### ISSUE TITLE
SVG rendering problem - part of picture not visible in pdf render

### ISSUE THREAD

**Issue by lafar6502** [Kozea/WeasyPrint#2240]
(continued from #2239)

Thanks, you're right - markers were missing. But after removing the markers - still the picture is not rendered correctly.
But this time i'm not getting any error message.
pdf:
![image](https://github.com/user-attachments/assets/e2da6dd0-7db1-4bbd-9df7-35f1be904231)
svg: something like
![image](https://github.com/user-attachments/assets/63026a0a-e5b7-4c8d-981d-ce7e9e58fb89)

Here's the test case - updated svg.
[test_p2.zip](https://github.com/user-attachments/files/16729627/test_p2.zip)
RG

_Originally posted by @lafar6502 in https://github.com/Kozea/WeasyPrint/issues/2239#issuecomment-2307145347_

(edit) i think nesting of SVG elements might be related to this problem

**Comment by liZe** [comment]
> i think nesting of SVG elements might be related to this problem

Yes, that’s because `svg` tags with no size are not supported. We could do the same hack as cf72dfc.

**Comment by lafar6502** [comment]
You mean, change <svg> to <g> tag?
For some cases it would work, but i have also a case where a larger svg is composed of sub-svgs coming from another place, so some xml manipulation would be necessary.

**Comment by liZe** [comment]
> You mean, change to tag?

I mean we should use the same fix in WeasyPrint for `svg` than the one we used for `symbol` in cf72dfc.

Using `g` instead of `svg` in your sample should work as a workaround, but let’s really fix that in WeasyPrint instead!
