### ISSUE TITLE
Inherited style attributes from parent element is not being applied.

### ISSUE THREAD

**Issue by codehunter1992** [Kozea/WeasyPrint#2244]
Inherited style attributes from parent element is being ignored when builds PDF.

For example,
```
<span style="font-family: 'comic sans ms', sans-serif'; font-size: 16px;">
    Hello world, welcome to <strong>WeasyPrint</strong>.
</span>
```

Word "WeasyPrint" in rendered PDF, has no correct font family and size.

Is there any solution?

**Comment by liZe** [comment]
Hi!

Do you have bold Comic Sans installed on your system?

**Comment by codehunter1992** [comment]
Yes, since if I apply bold to entire sentence like `<strong><span style="font-family: 'comic sans ms', sans-serif'; font-size: 16px;">Hello world, welcome to WeasyPrint</span></strong>`, it works properly.

**Comment by liZe** [comment]
Could you please share your PDF with the wrong font?

**Comment by codehunter1992** [comment]
[1725022933811.pdf](https://github.com/user-attachments/files/16817426/1725022933811.pdf)
This is the PDF file.
The words _Lorem Ipsum_, dummy text (read color), **Lorem Ipsum** (underline) are all should have same font family and size.

**Comment by liZe** [comment]
Your original example works for me (when I remove the extra quote).

[ms.pdf](https://github.com/user-attachments/files/16817498/ms.pdf)

Your PDF seems to be rendered using an old version of WeasyPrint. Could you try a recent version?

**Comment by codehunter1992** [comment]
I upgraded Weasyprint version 62.3

This is my html code:
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
</head>
<body>
   <p><span style="font-family: 'comic sans ms', sans-serif; font-size: 18pt;">Hello world, welcome to <strong>WeasyPrint</strong>.</span></p>
 <body>
</html>
```

This is generated PDF file using the latest version of package.
[be2d30e4-fbe2-44e2-ac04-9e55cab1de6e.pdf](https://github.com/user-attachments/files/16817719/be2d30e4-fbe2-44e2-ac04-9e55cab1de6e.pdf)

I also tried to test without html wrapper, same issue.

**Comment by codehunter1992** [comment]
I am using MacOS 14.3.1.
I didn't install the font myself, I just guessed that the font was installed because below html works properly.
```
<strong><span style="font-family: 'comic sans ms', sans-serif'; font-size: 16px;">Hello world, welcome to WeasyPrint</span></strong>
```

**Comment by codehunter1992** [comment]
Here you go the PDF file.
[1725025244839.pdf](https://github.com/user-attachments/files/16817892/1725025244839.pdf)

**Comment by liZe** [comment]
Well, it’s installed, and the documentation says [it’s installed by default](https://developer.apple.com/fonts/system-fonts/). To be honest, I have no idea why it doesn’t work for you. Do you have the same problem with other fonts? You can try with Futura or Didot, for example.

**Comment by codehunter1992** [comment]
Same issue with another font.
For example:
`<p><span style="font-family: tahoma, arial, helvetica, sans-serif; font-size: 18pt;">Hello world, welcome to <strong>WeasyPrint</strong>.</span></p>`

`<p><span style="font-family: arial, helvetica, sans-serif; font-size: 18pt;">Hello world, welcome to <strong>WeasyPrint</strong>.</span></p>`

All didn't work. :(

**Comment by liZe** [comment]
> Does this mean it works from your side?

Yes, it does work for me.

[ms.pdf](https://github.com/user-attachments/files/16818009/ms.pdf)

> If so, what is your Weasyprint version and OS? Can I know?

I use version 62.3 on Linux.

Did you install WeasyPrint with Homebrew?

**Comment by codehunter1992** [comment]
No, I installed using `pip` and running it in python project.
What is your version number of Linux?
Since I run a server on Ubuntu 20 and got same issue on it.

**Comment by liZe** [comment]
It works for me on latest Gentoo and Ubuntu computers. I’ve never seen this problem before, on countless Linux distributions. And it’s never been reported, as far as I can remember.

> Since I run a server on Ubuntu 20 and got same issue on it.

It’s really unlikely this error could happen on a fresh Ubuntu 20.04 install, or we would have spotted this before. Is there any specific configuration (maybe a Fontconfig configuration) you may have on both computers?

> No, I installed using `pip` and running it in python project.

On MacOS, how did you install the non-Python dependencies, such as Pango and Fontconfig?

**Comment by codehunter1992** [comment]
I have no any specific configuration regarding it.

I didn't install non-python dependencies such as `Pango` and `Fontfonfig` manually from MacOS. Nothing let me install them manually.

On Ubuntu, I installed Weasyprint 52.5 because of the dependencies' version conflicts.

**Comment by liZe** [comment]
> I didn't install non-python dependencies such as `Pango` and `Fontfonfig` manually from MacOS. Nothing let me install them manually.

Then they were already installed by another application, maybe with older broken versions.

The only documented way to make WeasyPrint work is to use Homebrew, and unfortunately we can’t help you much if you used anything else. You should try with Homebrew, as it’s known to work.

> On Ubuntu, I installed Weasyprint 52.5 because of the dependencies' version conflicts.

Just to be sure, could you please write `ms.html` with
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
</head>
<body>
   <p><span style="font-family: 'comic sans ms', sans-serif; font-size: 18pt;">Hello world, welcome to <strong>WeasyPrint</strong>.</span></p>
 <body>
</html>
```

then try:
```
sudo apt install weasyprint
weasyprint --info
weasyprint ms.html ms.pdf
```

and share your PDF?

**Comment by codehunter1992** [comment]
I did tested on MacOS with this command line - `weasyprint ms.html ms.pdf` (not in python project) and it generates PDF file properly without any issue.

```
html = HTML(string=html_string, encoding="utf-8")
page_formatter = CSS(string="@page { size: A4; margin: 0.75in }", encoding="utf-8")
page_stylesheet = CSS(filename=f"{MEDIA_ROOT}assets/document_template/style.css")
html.write_pdf(
    MEDIA_ROOT + self.file_path, stylesheets=[page_formatter, page_stylesheet], presentational_hints=True
)
```
These are my python code to generate PDF from html string.
Any code line may occur such issue do you think?

**Comment by liZe** [comment]
> I did tested on MacOS with this command line - `weasyprint ms.html ms.pdf` (not in python project) and it generates PDF file properly without any issue.

:+1:

> Any code line may occur such issue do you think?

It’s hard to tell without the whole code, but maybe using a [shared `FontConfiguration`](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#instantiating-html-and-css-objects) will help?

**Comment by codehunter1992** [comment]
Yes, after install `ttf-mscorefonts-installer`, `weasyprint ms.html ms.pdf` generates PDF correctly.
Thanks.
But I need to make python project work :)
Any other more suggestions?

**Comment by liZe** [comment]
> Any other more suggestions?

Did you try the shared FontConfiguration as explained above?

Otherwise, it means that something specific to your project breaks WeasyPrint. You probably know better what your project does, so we can’t really help you about that :/.

**Comment by codehunter1992** [comment]
OK, Thanks, I will try more myself, and keep posted here.
You can also update once you get a new idea.

**Comment by liZe** [comment]
> You can also update once you get a new idea.

I really don’t know what can cause this issue.

**Comment by liZe** [comment]
@codehunter1992 Did you find anything interesting about this issue?

**Comment by codehunter1992** [comment]
It was a silly issue.
There was a bad line in the css file that I used to generate to PDF.
After remove that line from css, it works properly.
Thank you for your attention.
