### ISSUE TITLE
Table grid not displayed correctly in production enviroment

### ISSUE THREAD

**Issue by patrick-norton-92** [Kozea/WeasyPrint#2245]
I am having trouble creating a grid layout.  The layout works fine locally, but in production it doesn't seem to be working.
file:///home/paddy/IdeaProjects/farmeye-core-2/farmeye-doc-generator/src/main/resources/templates/report/eit/micronutrients.html

The css in another file
`
.table-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr); /* Adjust the number of columns */
    gap: 10px;
    padding: 10px;
}`
For reference we are a spring boot java application, and use WeasyPrint along with thymeleaf in a docker enviroment to build the webpages and then weasy print turns it all into pdf's for downloading.  
The issue is with this file
![issue](https://github.com/user-attachments/assets/8ab9873c-61ac-47ff-9c88-1d9ef44ca240)

**Comment by liZe** [comment]
Hi!

Grid has been added quite recently to WeasyPrint. Do you use a recent version of WeasyPrint on production?

**Comment by liZe** [comment]
Feel free to add a comment if there’s anything we can do for you.
