### ISSUE TITLE
Images not showing in PDF but in HTML

### ISSUE THREAD

**Issue by JoNarmada** [Kozea/WeasyPrint#2251]
I am currently looking into the issue that involves our company using a rich text editor values and using Weasy print to be able to showcase the values and a variety of other information that is being read by a @HTML.Raw. It is able to read tables and other properties but with images it is not showcasing it at all.

`<div class="mx-4 my-1" style="justify-content: center; align-items: center; width: 200px; height:200px;">
        @Html.Raw(custom_page_editor_content_html) 
      </div>`
      
      Underneath is the HTML string that is being rendered with the image. Only works with HTML but not the pdf. Any ideas on the why?

```
<div>
  <div class="container-fluid">
    <div class="row g-20">
      <div class="mx-4 my-1">
        <p> </p>

<p>GLOBAL <em>TESTING</em></p>

<figure class="easyimage easyimage-full"><img alt="" src="blob:https://localhost:7204/939509c1-74a6-4fb3-9f38-258725dbeded" width="1226" />
<figcaption></figcaption>
</figure>

<figure class="easyimage easyimage-full"><img alt="" src="blob:https://localhost:7204/bd543d60-e2b5-4595-a5c7-fbd9c31e4d46" width="1226" />
<figcaption></figcaption>
</figure>
      </div>
    </div>
  </div>
</div>
```

Any ideas, tips or suggestions would be appreciated!

**Comment by liZe** [comment]
Hi!

`blob` URLs refer to memory in the current browser, they can’t be resolved if you give them to another browser (to WeasyPrint in your case).

There’s probably a way in your rich HTML editor to use the original URL instead of the in-memory image.

**Comment by JoNarmada** [comment]
@liZe  Thank you for responding! So are you saying that if I delete the `blob `portion of the url then it would showcase on the pdf?

**Comment by liZe** [comment]
> So are you saying that if I delete the `blob `portion of the url then it would showcase on the pdf?

`blob` points to a resource that’s in your browser. In your specific case, if the part of the URL after `blob:` leads to a real resource, you can then remove the `blob:` part and it will be displayed in the PDF.

**Comment by JoNarmada** [comment]
@liZe Yeah the blob is needed, I tested it on my local/staging and see that the `blob `portion is important as when it is deleted no image appears. So it may be something with my Rich Text Editor? I am using CkEditor

**Comment by liZe** [comment]
> So it may be something with my Rich Text Editor? I am using CkEditor

Yes, it looks like CkEditor stores the image in the browser and add a blob URL to it. You should check its documentation to see if it’s possible to use data-URL instead, for example.

**Comment by liZe** [comment]
The forum issues complaining about blob URLs in CkEditor are quite old. Do you use a recent version of CkEditor?

**Comment by JoNarmada** [comment]
@liZe I believe it is CkEditor4 for this section in particular but it should still be good. However, I am realizing that it has to do with the plugins that are not attached to the CKEditor, like SimpleUploadAdapter which would allow us to upload the images to our server without storing it with the `blob` portion

**Comment by liZe** [comment]
> However, I am realizing that it has to do with the plugins that are not attached to the CKEditor, like SimpleUploadAdapter which would allow us to upload the images to our server without storing it with the `blob` portion

That would explain your problem!

I’m closing the bug, as there’s probably nothing we can do about it in WeasyPrint. Don’t hesitate to add a comment if necessary, and have fun with WeasyPrint!
