### ISSUE TITLE
High Vulnerability - Multiple licenses: GPL-2.0, LGPL-2.0, MPL-1.1

### ISSUE THREAD

**Issue by ersanjeev007** [Kozea/WeasyPrint#2259]
Hi, there's a high vulnerability introduced through weasyprint@62.3.0 › pyphen@0.16.0

That's 
`
Multiple licenses: GPL-2.0, LGPL-2.0, MPL-1.1
`

**Comment by liZe** [comment]
Hi! This has already been discussed many times, in Kozea/Pyphen#52. In Pyphen’s README:

> GPL 2.0+ or LGPL 2.1+ or MPL 1.1 for the code

**or** means that you can choose the licence you prefer.
