### ISSUE TITLE
OverflowError in draw_first_line

### ISSUE THREAD

**Issue by Shamzik** [Kozea/WeasyPrint#2262]
I encountered an OverflowError when trying to generate a PDF document from an HTML file using WeasyPrint version 62.3. The error occurs on the following line of code: [weasyprint/draw.py#L1430](https://github.com/Kozea/WeasyPrint/blob/62.x/weasyprint/draw.py#L1430).

## Reproduction Steps

To reproduce the issue, you can use the minimal HTML and Python code snippets below.

### Minimal HTML file:

```html
<!DOCTYPE html>
<html>
<head>
    <style type="text/css">
        table {
            text-align: justify;
        }
    </style>
</head>
<body>
<table>
    <tr>
        <td>
            X Y ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
        </td>
    </tr>
</table>
</body>
</html>

```

### Minimal Python code:

```python
import argparse

import weasyprint


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('html')
    parser.add_argument('pdf')
    args = parser.parse_args()

    with open(args.html, 'r') as html:
        with open(args.pdf, 'wb') as pdf:
            weasyprint.HTML(string=html.read()).write_pdf(pdf)
```

## Expected Behavior

A PDF document should be generated without any errors.

## Actual Behavior

An OverflowError is raised when attempting to generate the PDF.

## Environment

- WeasyPrint version: 62.3
- Python version: 3.12
- Operating System: Ubuntu

**Comment by grewn0uille** [comment]
Thanks for your report!

Font to reproduce: DejaVu Serif.

**Comment by liZe** [comment]
It’s now fixed, feedback is welcome!
