### ISSUE TITLE
How to specify maximum allowed space between words?

### ISSUE THREAD

**Issue by ondras** [Kozea/WeasyPrint#2268]
I am trying to justify my paragraphs and I am not very happy with the result (see https://github.com/Kozea/WeasyPrint/issues/2264). However, I think that even the default fast'n'dirty line breaking algorithm could do better, especially when I see the same HTML+CSS being rendered more nicely in a browser.

In this example rendering: 
![obrazek](https://github.com/user-attachments/assets/75a35e41-cf2a-46ef-bc5d-1a3f2d4b9c98)

  - the first line has too large inter-word spaces
  - the second line has a non-breakable space after `i`

I have hyphenation turned on (`lang=cs`). In my opinion, hyphenating at `i jedno | tlivých` or `i jed | notlivých` would result in the first line having better/smaller spacing. Is there a way to define the "maximum allowed space between words"?

**Comment by ondras** [comment]
Update: I think the problem is caused by https://github.com/Kozea/WeasyPrint/issues/2270 instead.

**Comment by liZe** [comment]
> Update: I think the problem is caused by #2270 instead.

Yes, the current algorithm should hyphenate as soon as it can, unless [`hyphenate-limit-zone`](https://www.w3.org/TR/2024/WD-css-text-4-20240529/#propdef-hyphenate-limit-zone) is set.

Let’s continue the discussion on #2270.
