### ISSUE TITLE
img width is ignored inside tables

### ISSUE THREAD

**Issue by aquavitae** [Kozea/WeasyPrint#227]
With html of the following form:

```
<table>
  <tbody>
    <tr>
      <td><img ...></img></td>
    </tr>
  </tbody>
</table>
```

And css:

```
table img {max-width: 100%; width:100%}
```

The width spec is ignored, and the image displays full size

**Comment by liZe** [comment]
Here's what we get in the [spec](https://drafts.csswg.org/css-sizing/#intrinsic-contribution) now:

> However, in the case of a replaced box with a percentage-based width/max-width/height/max-height, the percentage is resolved to zero when calculating the min-content contribution in the corresponding axis.

That's not the most precise rule I've ever seen. BTW, I've followed what this rule seems to imply (at least for width), and the result is more or less what we get in browsers. It fixes the example given in this issue and in #521, I hope that nobody relies on the old behavior (that wasn't really specified anyway).
