### ISSUE TITLE
Producing destinations with bounding boxes (FitR) rather than coords (XYZ)

### ISSUE THREAD

**Issue by jambudipa** [Kozea/WeasyPrint#2280]
So I should not have [closed this issue](https://github.com/Kozea/WeasyPrint/issues/2279), I have follow up questions...

I would like to know how if anyone has had success creating destination types other than `/XYZ`? I need to indicate the bounding box of elements, and of course `/XYZ` does not support that.

I am guessing I have to [tinker with this call](https://github.com/Kozea/WeasyPrint/blob/1aae1452da384de0160f599d4e2500aa1f3bebfc/weasyprint/pdf/__init__.py#L218) to provide a bounding box?

**Comment by liZe** [comment]
I think that there’s no real advantage for WeasyPrint to use other destination types than `/XYZ`, as its goal is to always make links lead to hit boxes, which are always border boxes.

But if your goal is to "hack" the PDF, you have two solutions:
- You can define your [`finisher`](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.HTML.write_pdf) function to change the PDF structure, with access to the `document` and `pydyf.PDF` objects.
- You can use a third-party library such as pypdf, that may give you full access to the PDF internals you want to change.

**Comment by jambudipa** [comment]
Well I'm not sure what you mean, because `/XYZ` is a point, rather than a bounding box.

I achieved what I needed anyway updating these two functions:
```
def add_links(links_and_anchors, matrix, pdf, page, names, mark):
    // ...
    for anchor in anchors:
        anchor_name, x1, y1, x2, y2 = anchor
        x1, y1 = matrix.transform_point(x1, y1)
        x2, y2 = matrix.transform_point(x2, y2)
        names.append([
            anchor_name, pydyf.Array([page.reference, '/FitR', x1, y1, x2, y2])])
    
def resolve_links(pages):
    anchors = set()
    paged_anchors = []
    for i, page in enumerate(pages):
        paged_anchors.append([])
        for anchor_name, (point_x1, point_y1, point_x2, point_y2) in page.anchors.items():
            if anchor_name not in anchors:
                paged_anchors[-1].append((anchor_name, point_x1, point_y1, point_x2, point_y2))
                anchors.add(anchor_name)
    for page in pages:
        page_links = []
        for link in page.links:
            link_type, anchor_name, _, _ = link
            if link_type == 'internal':
                if anchor_name not in anchors:
                    LOGGER.error(
                        'No anchor #%s for internal URI reference',
                        anchor_name)
                else:
                    page_links.append(link)
            else:
                # External link
                page_links.append(link)
        yield page_links, paged_anchors.pop(0)
```
Now this produced `/FitR` bounding rectangles, which is precisely what I need.

**Comment by liZe** [comment]
> Well I'm not sure what you mean, because `/XYZ` is a point, rather than a bounding box.

What I mean is that for a browser or a PDF reader, reaching an anchor is actually reaching the top-left corner of the border box, which is a point.

> Now this produced `/FitR` bounding rectangles, which is precisely what I need.

Cool for you! What’s your use case?

**Comment by jambudipa** [comment]
My use case is navigating to search results in a PDF.

So I save the PDF as HTML, apply IDs to the fragments of the HTML, create embeddings for these fragments, and then when a vector search is performed on these fragments, their ID is returned.

Then clicking on the fragment search result navigates to that in the PDF, which is highlighted using the bounding box.

Although it literally just occurred to me that I don't need to extract the bounding box at all, since I can probably just apply a class to that ID in the PDF when it ends up as HTML in the browser 😆

**Comment by liZe** [comment]
> Although it literally just occurred to me that I don't need to extract the bounding box at all, since I can probably just apply a class to that ID in the PDF when it ends up as HTML in the browser 😆

That’s probably easier! 🤣

I’m closing the issue, as there’s probably no obvious use case for bounding boxes destinations for WeasyPrint. Feel free to add a comment if there’s anything more we can do!

**Comment by jambudipa** [comment]
@liZe  There absolutely is a use case. I have just such a use case.

I was mistaken when I said I could use the IDs in the HTML. They don’t end up in the HTML when rendered, and so now I am relying upon the bounding boxes to overlay a highlight on the element.

**Comment by liZe** [comment]
> There absolutely is a use case. I have just such a use case.

I mean, a use case for users that want to render PDF files, because that’s what WeasyPrint does. Altering HTML generated from PDF files with a browser is not what we can call a common use case :smile:.

> so now I am relying upon the bounding boxes to overlay a highlight on the element.

The `--pdf-variant=debug` option adds links on ids, and these links contain the bounding box. Isn’t that sufficient for your use case?

**Comment by jambudipa** [comment]
Not sure, will check that out. Thanks.
