### ISSUE TITLE
Problem with specifying width of img

### ISSUE THREAD

**Issue by tobiasgardner** [Kozea/WeasyPrint#2283]
I am having problems with converting html to pdf with weasyprint (python).

It seems like it is not adhering to "width" in the img tag:

`<img src="..." alt="Logo" width="300" />`

No matter what I try here, it takes up 100% of the width of the page in the pdf output. However, it works when looking at the html code through a browser.

I have tried
- Putting the tag inside a table with width specified on column level
- Putting the tag inside tag with CSS to define with of the columns

I have created a html file here which illustrates the problem: 
https://gist.github.com/tobiasgardner/be6e9efba80f13e6aa6464cbcf8613ad

The output in the browser (html) looks like this.
![Image](https://github.com/user-attachments/assets/6926746a-41c9-4f79-9b03-ba504ab1925a)

The generated pdf can be found here:
[Weasyprint_debug.pdf](https://github.com/user-attachments/files/17486242/Weasyprint_debug.pdf)

**Comment by liZe** [comment]
Hi!

You need to add the [`--presentational-hints`](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#cmdoption-p) option to handle the `width` HTML attribute.

Note that using CSS instead of HTML attributes is often preferred for styling information.

**Comment by tobiasgardner** [comment]
Thank you @liZe! That did the trick! Or in my case, I used the following:

`HTML(string=html_content).write_pdf(target=filename, presentational_hints=True)`

**Comment by tobiasgardner** [comment]
@liZe May I ask another question... I am trying to setup the CSS so that my pages have:
- a header -repeated on all pages
- a footer - repeated on all pages
- content - between the header and footer, this is where the main content goes which CAN span over >1 page.

I have tried a bunch of different ways but I am failing. If you have a guide/tutorial which shows how this can be done, I would appreciate it a lot :)

**Comment by liZe** [comment]
> I have tried a bunch of different ways but I am failing. If you have a guide/tutorial which shows how this can be done, I would appreciate it a lot :)

You can take a look at our [samples](https://weasyprint.org/#samples), the "Reports" one should be useful.
