### ISSUE TITLE
Support for Pillow 11

### ISSUE THREAD

**Issue by paulocoutinhox** [Kozea/WeasyPrint#2294]
Hi,

Can you add support for Pillow 11?

Error:

```
weasyprint 63.0 depends on Pillow<11 and >=9.1.0
```

Thanks.

**Comment by paulocoutinhox** [comment]
Can you create a new release with this fix? Thanks.

**Comment by nijel** [comment]
Fix is in https://github.com/Kozea/WeasyPrint/pull/2288, so only the release is missing.

**Comment by grewn0uille** [comment]
We’ll do the release when the regression issues introduced by v63 have been fixed, as we always do.

**Comment by paulocoutinhox** [comment]
New version man pls.

**Comment by grewn0uille** [comment]
Not a man here :)

And:

> We’ll do the release when the regression issues introduced by v63 have been fixed, as we always do.

**Comment by paulocoutinhox** [comment]
Sorry, not pay attention, hahaha. Thanks.
