### ISSUE TITLE
Svg fill attributes unusual behaviour in v63

### ISSUE THREAD

**Issue by summersz** [Kozea/WeasyPrint#2302]
This was working as expected and matching browser renderings in v62

`<svg width="300" height="130" xmlns="http://www.w3.org/2000/svg">
    <rect width="200" height="100" x="10" y="10" rx="20" ry="20" fill="#000" fill-opacity=".098"
        fill-rule="evenodd" />
    <circle cx="50" cy="50" r="50" fill="#1c87c9" fill-opacity=".098"
        fill-rule="evenodd" />
</svg> `

In v63, the rect is not applying the fill-opacity.  If the order of the rect and circle are switched, the circle does not apply the fill-opacity.  Both are applied in browsers.

**Comment by summersz** [comment]
Thanks for the quick fix. I have tested on my larger template with the fix branch and it is working.

**Comment by liZe** [comment]
> Thanks for the quick fix. I have tested on my larger template with the fix branch and it is working.

Thanks for the report! It’s really useful to get a small sample to reproduce problems, and to have feedback when it’s fixed. :heart:
