### ISSUE TITLE
test_borders_table_collapse and assert_different_renderings seem flaky

### ISSUE THREAD

**Issue by benoitkugler** [Kozea/WeasyPrint#2305]
Hi,

I think there is currently two issues regarding `test_borders_table_collapse` : 

1. Under collapsed borders, the `groove` and `outset` styles render the same (as well as the `inset`/`ridge` pair), so that the test should not ask for different renderings
2. I think Weasyprint _actually_ properly follows the spec, but that `assert_different_renderings` seems broken : at tests/draw/__init__.py line 85, the pixels comparison `pixels_1 == pixels_2` seems to always be `False`, since the variables are compared by reference, not by actual pixel content. A simple fix should be to change the comparison to `list(pixels_1) == list(pixels_2)`

From what I understand, no change is required to the library, only to the tests.

**Comment by liZe** [comment]
Hi,

Thanks for the report, I don’t know how you caught this! Interested in providing a pull request?

**Comment by benoitkugler** [comment]
I'm writing a port of WeasyPrint for the Go programming language. Thanks by the way for your work, it has been very interesting to dig into the depths of HTML rendering ! 
I've discovered the issue because the Go version of the test was failing, yet with a seemimgly correct rendering.

I can send a PR,  not sure when however

**Comment by liZe** [comment]
> I can send a PR, not sure when however

Let me do this for you 😄 

Thanks again for the report!

**Comment by benoitkugler** [comment]
> Let me do this for you 😄

Thank you ;)

On est jamais mieux servi que par soi-même 😅
