### ISSUE TITLE
Windows executable failed

### ISSUE THREAD

**Issue by KasaarLtagta** [Kozea/WeasyPrint#2309]
Hello, I tried to install WeasyPrint v63 on my Windows 11 computer. After confirming that I wanted to execute it (malware suspicion warning), I briefly get this screen and then nothing happens :
![Image](https://github.com/user-attachments/assets/94cea478-1226-443c-acd1-e44323c6f949)

**Comment by grewn0uille** [comment]
Hello,

The WeasyPrint executable needs to have at least two parameters: the input (the HTML you want to transform) and the output (name of the outputed PDF).

You can use the executable from a terminal and use the CLI, or you can call the executable from your code.

WeasyPrint doesn’t come with a graphic interface.

**Comment by KasaarLtagta** [comment]
Oooh OK, Thank you

So my problem is slightly different : I successfully used WeasyPrint with Quarto on my Ubuntu (POP OS) computer, but I don't know how to replicate the process on my Windows machine.

Do you have any ideas?
