### ISSUE TITLE
WARNING - Ignored `background-image:  weasyprint 51.0

### ISSUE THREAD

**Issue by Khalil-Badrane** [Kozea/WeasyPrint#2313]
in this example the pdf return  logo and not bg.png why ?![Image](https://github.com/user-attachments/assets/7c605d08-4371-4e31-8f4f-fcd3108c537a)

**Comment by Khalil-Badrane** [comment]
"<div class="h-a4 w-a4 bg-center" style="background-image: url('{base_path}/bg.png'); display: flex; flex-direction: column;">
    <table style="border-collapse: collapse; flex-grow: 1;">
        <tr>
            <td style="padding: 5% 0 0 5%;">
                <img src="{base_path}/Logo.png" alt="Company Logo" style="width: 40%;" />
            </td>
        <tr>
            <td style="padding-left: 5%;">
                <h1 class="text-white uppercase text-7xl font-bold tracking-wide leading-tight">
                    RFID Readiness <br> Assessment <br> Report
                </h1>
            </td>
        </tr>
    </table>
    <div style="margin-top: auto; padding: 25% 0 5% 0; text-align: center;">
        <table class="p-8 bg-purple" style="margin-left: auto">
            <tr>
                <td>
                    <p class="text-gray-300 text-2xl"><strong>Company Name:</strong></p>
                    <p class="text-gray-300 text-2xl">{response[0]}</p>
                    <p class="text-gray-300 text-2xl"><strong>Date of Assessment:</strong></p>
                    <p class="text-gray-300 text-2xl">{current_date}</p>
                </td>
            </tr>
        </table>
    </div>
</div>"

**Comment by liZe** [comment]
Hi!

Could you please try a more recent version of WeasyPrint? Version 51 is almost 5 years old.
