### ISSUE TITLE
Memory leak in version 63

### ISSUE THREAD

**Issue by MarouaneMan** [Kozea/WeasyPrint#2319]
Hello 👋,

We've discovered that we have a high memory usage in one of our services, and after investigating, it seems that the latest version of weasyprint 63 consumes more memory than expected.

The example below consumes over 2GB using weasyprint 63.
Using version 62.3 it is stable at ~60MB.

Python 3.13.0

Thanks a lot !
```
python
import gc
import psutil
from weasyprint import HTML

iterations = 10000
for i in range(iterations):
    pdf = HTML(string="<html>Hello world</html>").write_pdf(
    '/tmp/example.pdf', stylesheets=[],
    font_config=None)

    progress = (i + 1) / iterations * 100
    process = psutil.Process()
    memory_info = process.memory_info()
    print(
        f"Progress: {progress:.2f}% | "
        f"Current Memory Usage: {memory_info.rss / (1024 * 1024):.2f} MB"
    )
    if i % 200 == 0:
        #gc.collect()
        pass
```

**Comment by liZe** [comment]
Thanks for the report. `git bisect` gives a culprit: 3e87175.

**Comment by liZe** [comment]
There’s even a second memory leak in 95d2c37.

**Comment by liZe** [comment]
We’ve fixed multiple memory leaks, memory use is quite stable now. Feedback is welcome!
