### ISSUE TITLE
Page background images are not displayed when viewing pdf in pdf.js

### ISSUE THREAD

**Issue by lananelson** [Kozea/WeasyPrint#232]
This is most definitely not an issue with weasyprint and is an issue with pdf.js but I wanted to ask here just in case anyone came across the same problem.

I am using weasyprint to render pdf out of html that has following CSS:
```
<style type="text/css">
      @page {
        background: url('....') no-repeat;
        background-size: cover;
        margin: 0;
      }
...
```
This works great for me when I view pdfs in Chrome and Acrobat but not in pdf.js
pdf.js does not render background image, it does render images that are included with `img` tag though. Could anyone here provide any help with this?

**Comment by liZe** [comment]
Duplicates #238.
