### ISSUE TITLE
How can we create a PDF/A-3 PDF file?

### ISSUE THREAD

**Issue by sowinski** [Kozea/WeasyPrint#2327]
Hi,

I would like to generate a PDF which supports PDF/A-3.
(Because I want later add a ZUGFeRD XML to this PDF)

Currently I am generating my pdf like that with python:

```
        template = get_template("payment/invoice/default.html")
        context = self.get_context_data()
        html = template.render(context)
        byte = HTML(string=html).write_pdf()
```

How can I activate the experimental PDF/A-3 feature here?

**Comment by grewn0uille** [comment]
Hello,

You can select a PDF variant when calling `write_pdf()` with the `pdf_variant` option.
The list of the variants is available [in the documentation](https://doc.courtbouillon.org/weasyprint/latest/api_reference.html#cmdoption-pdf-variant).

**Comment by sowinski** [comment]
Great thank you!

I was looking at the wrong place:
https://doc.courtbouillon.org/weasyprint/latest/api_reference.html#weasyprint.DEFAULT_OPTIONS

Now the docs make totally sense :)
