### ISSUE TITLE
CSS background-color does not work for display: grid elements with position: relative

### ISSUE THREAD

**Issue by TechInterMezzo** [Kozea/WeasyPrint#2331]
As soon as I set display to grid the background-color is not working anymore.
For example:

```
div.test {
  display: grid;
  width: 200px;
  height: 200px;
  background-color: black;
}
```

**Comment by liZe** [comment]
Hi!

This example works correctly for me:
```html
<style>
  div {
    display: grid;
    width: 200px;
    height: 200px;
    background-color: black;
  }
</style>
<div></div>
```

Do you have an example that doesn’t work?

**Comment by TechInterMezzo** [comment]
I just found out, that the div inherited another style with position: relative.
So that was easier to fix than i thought.
Now I don't know if display: grid and position: relative should be even compatible together.
I think you have more experience to judge that.
