### ISSUE TITLE
Text in SVG with alpha <1 gets cut off when converting HTML to PDF

### ISSUE THREAD

**Issue by victorhartman** [Kozea/WeasyPrint#2332]
This is a regression. This showed up when we performed an upgrade, used to work fine with an older version of the package. Unfortunately I don't know which version.

I have create a reproduction of the bug here:

```
import matplotlib.pyplot as plt
import numpy as np
from weasyprint import HTML

# plotting code
x = np.linspace(0, 10, 100)
y = np.sin(x)
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(x, y)

# Add annotation
ax.annotate('gyj', 
            xy=(4.7, 1),      
            xytext=(5.5, 0.5),
            alpha=0.999999 # This is the issue
            )

# Save to SVG
plt.savefig('test.svg', transparent=True, dpi=300, bbox_inches='tight', format='svg')

# Read the SVG file
with open('test.svg', 'r') as f:
    svg_content = f.read()

# Create HTML with embedded SVG
html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Plot Export</title>
    <style>
        body {{
            margin: 0;
            padding: 20px;
        }}
    </style>
</head>
<body>
    {svg_content}
</body>
</html>
"""

# Convert HTML string directly to PDF
HTML(string=html_content).write_pdf('plot.pdf')
```

Output is this
[plot.pdf](https://github.com/user-attachments/files/18199572/plot.pdf)

While the svg looks fine:
![Image](https://github.com/user-attachments/assets/73fbc4ea-69f9-4cd1-8367-acf54d5aa1de)

System info:
System: Windows
Machine: AMD64
Version: 10.0.22631
Release: 11

WeasyPrint version: 62.3
Python version: 3.12.2
Pydyf version: 0.10.0
Pango version: 15003

**Comment by liZe** [comment]
Hi!

Thanks for the report. The bug has been introduced in WeasyPrint 60.2 by 4dfe6079.

**Comment by liZe** [comment]
The bug is now fixed and tested!

**Comment by victorhartman** [comment]
Wow super, thanks! Looking forward to the release!
