### ISSUE TITLE
CSS border-collapse: collapse; not working as expected for tables

### ISSUE THREAD

**Issue by TechInterMezzo** [Kozea/WeasyPrint#2333]
The following CSS is not working as expected:

```
table {
  border-collapse: collapse;
  border-spacing: 0;
}
td {
  border: 1px solid black;
}
```

The borders of neighbour table cells are not collapsed and so the borders between cells seem twice as thick.

**Comment by liZe** [comment]
`border-collapse: collapse` should work and merge borders. `visibility: collapse` is another, unrelated feature.
