### ISSUE TITLE
list-style-position behavior

### ISSUE THREAD

**Issue by martijnhartlief** [Kozea/WeasyPrint#2337]
With the following html:
```html
<!DOCTYPE html>
<html>
	<head>
		<style>
			ol, li {
				margin: 0;
				padding: 0;
			}
			ol {
				list-style-position: outside;
				padding-left: 5rem;
				border: 2px solid red;
			}
			li {
			 	padding-left: 5rem;
			 	border: 2px solid green;
			}
		</style>
	</head>
	<body>
		<ol>
		  <li>Item 1</li>
		  <li>Item 1</li>
		</ol>
	</body>
</html>
```

I would expect this behavior:
<img width="826" alt="Image" src="https://github.com/user-attachments/assets/02f89632-8900-433e-91ea-b6df063af566" />

Instead I get
<img width="732" alt="Image" src="https://github.com/user-attachments/assets/09923809-a69c-4fd8-8036-0b73f120e877" />

It looks like it renders the marker inside the li, is this intended or am I doing something wrong?

**Comment by liZe** [comment]
Hi!

Thanks for the issue. It’s a bug, already reported in #1557, with workarounds if you’re interested!
