### ISSUE TITLE
Failed to load SVG image

### ISSUE THREAD

**Issue by diethardsteiner** [Kozea/WeasyPrint#236]
Hi,
I wrote a message to the mailing list earlier on asking why SVG images are not showing up in the output. I had a closer look at the log now and I could find one error message:

```
Failed to load image at [...]/logo_v4_small.svg : ValueError: invalid literal for float(): 0
```

Any ideas why this is happening?

**Comment by liZe** [comment]
Could you give the SVG file, please?

**Comment by diethardsteiner** [comment]
Here you go:
https://www.dropbox.com/s/wv9o3ic8ldohv3z/missing.svg?dl=0

**Comment by liZe** [comment]
CairoSVG crashes when trying to render this image, I'm trying to find why.

**Comment by diethardsteiner** [comment]
Thanks a lot!

**Comment by liZe** [comment]
It's fixed in CairoSVG 1.0.11 (released 1 minute ago), thanks for the report!

**Comment by diethardsteiner** [comment]
Wow, excellent! Thanks a lot! 
I initially installed CairoSVG via the Fedora package. I guess it will take some time until this is updated, or? Would I be better off compiling it myself?

**Comment by liZe** [comment]
One really simple solution is to remove the commas from the "viewbox" attribute of the SVG.

**Comment by diethardsteiner** [comment]
Thanks! I try this workaround for now. How long does it usually take until a new version is available in a specific OS package?
