### ISSUE TITLE
SVG: kerning value not applied

### ISSUE THREAD

**Issue by diethardsteiner** [Kozea/WeasyPrint#237]
Hi,
In my SVG image the text has kerning set to -23.5. However, in the WeasyPrint output it looks like the kerning is not applied at all.

```
    <text transform="matrix(1.069, 0, 0, 0.936, 187.264, 66.537)" id="tspan2989">
      <tspan x="-186.869" y="48" font-family="Helvetica-Bold" font-size="130.725" kerning="-23.5" fill="#000000">Test</tspan>
    </text>
```
Can you please have a look at this? Thanks!

**Comment by liZe** [comment]
Please report this bug on CairoSVG if you really want it to be fixed. But I've got bad news for you:
- http://cairosvg.org/svg_support/#idid96
- https://github.com/Kozea/CairoSVG/blob/master/test/fail/font/README.rst

**Comment by diethardsteiner** [comment]
Ok, thanks
