### ISSUE TITLE
'break-before' left vs. right page

### ISSUE THREAD

**Issue by E-M-P-I-R-E** [Kozea/WeasyPrint#241]
I want to define page breaks where the page must begin on the right side - so if the previous page is also a 'right' page, there should be a blank page inserted and correctly numbered.

After reading the following section I thought that I might be able to accomplish my goal

>If the UA supports the direction and writing-mode properties from the CSS 3 Writing Modes Module [CSS3-WRITING-MODES], it must determine whether the first page is a left or right page from the values of those properties on the root element.

>To explicitly force a document to begin printing on a left or right page, authors can specify a break-before value that that propagates a page break to the root. [CSS3-BREAK] The UA must suppress the first (empty) page(s) in this case (and the :first pseudo-class matches the first printed page).

http://dev.w3.org/csswg/css-page-3/#progression

I've tried a few different combinations of 'break-before' with values left, always and even on a pseudo 'before' element but I'm not seeing any difference. I was experimenting with an h2 element.

Edit: sorry for the multiple edits, hit submit accidentally.

**Comment by SimonSapin** [comment]
WeasyPrint does not support (yet) the `break-before` alias, you need to use the `page-break-before` property. `left` and `right` keywords for that property are supported however.

If that doesn’t help, please provide a minimal test case with HTML + CSS with explenations of what you expected to see, and what you get instead.

**Comment by E-M-P-I-R-E** [comment]
Thank you very much for your quick reply. After writing my test I got it working; I'm thrilled =D
My requirement was that elements with class-name "new_section" always be on a right hand page. The code below produces a four page document (page 3 is blank) with correct numbering.

```html
<html>
<head>
<style>
@page{
    @bottom-center {
        content: counter(page);
    }
}
.page{
      page-break-before: always;
}
.new_section{
      page-break-before: left;
}
</style>
<body>
    <div class="page">CONTENT</div>
    <div class="page">CONTENT</div>
    <div class="page new_section">CONTENT</div>
</body>
</html>
```
Thanks again. Now, on to section headers [and skipping the blank pages]!
