### ISSUE TITLE
Page-margin-box content based on current bookmark level

### ISSUE THREAD

**Issue by E-M-P-I-R-E** [Kozea/WeasyPrint#242]
I think I've read all the discussion on margin content and the current limitations [because there is no CSS spec. to follow] but I am hoping I could tackle this limited case.

All of the techniques I've seen have ended up with the same content on every page (except for page number/counter). Is it feasible to have the header content on a given page be based on the current bookmark level? So, every page after an H1 element has the text therein (which is [hopefully] already known at that time because it will become a bookmark.)

**Comment by SimonSapin** [comment]
This sounds a lot like "named strings", which are discussed in #174. Closing as duplicate, but feel free to reopen if it’s not.
