### ISSUE TITLE
PDF Page Resolution

### ISSUE THREAD

**Issue by pdx971** [Kozea/WeasyPrint#248]
We are trying to generate print quality (300 dpi) documents html-to-pdf. Because the pages are 96dpi, the images are too large. In other html-to-pdf converters (in php) you can set the default page resolution in a config file to 300dpi. Because we are using Python, we are using Weasyprint.

Is there something we can do to ensure the image quality is 300dpi? Do you have any recommendations?

**Comment by SimonSapin** [comment]
You’re probably looking for the `image-resolution` property: `img { image-resolution: 300dpi }`. Alternatively, set the `width` or `height` property to a non-`auto` value to size images explicitly.

**Comment by SimonSapin** [comment]
By the way, the things that WeasyPrint supports are listed in http://weasyprint.org/docs/features/

**Comment by liZe** [comment]
@pdx971 Did this property solve your problem?

**Comment by davidkjoy** [comment]
> You’re probably looking for the image-resolution property: img { image-resolution: 300dpi }. Alternatively, set the width or height property to a non-auto value to size images explicitly.

I can't figure out how to use it. Could you please specify how to use it .

**Comment by SimonSapin** [comment]
`img { image-resolution: 300dpi }` is a CSS rule, to be included in your stylesheet, that sets the `image-resolution` property to a value of three hundreds "dots-per-inch" (image pixels per CSS `in` unit, with `1in` = `96px`) for every `<img>` element in your HTML document.
