### ISSUE TITLE
font-family works in h1 css, but not body css

### ISSUE THREAD

**Issue by ntregillus** [Kozea/WeasyPrint#249]
I have been tracking down a strange issue where our pdf's generated with weasyprint look fine in chrome's viewer, and the mac preview app, but when you open the doc in Acrobat Pro, you get the infamous "An error exists on this page" message.

we are using the font-family css attribute to assign the following font-family setting:

font-family: 'Helvetica Light', 'Helvetica', Arial, sans-serif;

this exact same attribute is applied to both the body css and the h1 css. if I remove the font-family from the body css, the pdf renders correctly and has no errors in Acrobat Pro.

here is the snippet of css we have:

 body{
                color: #505150;
                padding: 0;
                margin: 0;
                font-family: 'Helvetica Light', 'Helvetica', Arial, sans-serif;
                background-color: #FFFFFF;
                font-weight: lighter;
            }
            p{
                margin:0;
                padding:0;
            }
            table{
                border-spacing: 0;
            }
            * {
                box-sizing: border-box;
            }
            h1 {
                display: block;
                font-size: 13pt;
                color: #107E50;
                padding: 0;
                margin: 3px 0 2px 0;
                font-family: 'Helvetica Light', 'Helvetica', Arial, sans-serif;
            }

**Comment by liZe** [comment]
Here's an advice from Adobe's forums:
>If you have Acrobat Pro, use the Preflight tools. There's a profile that performs a low-level syntax check of the file. Provided you can get as far as opening it, Preflight will report what the problem is.

(Don't even imagine that you can ask me how to do this :wink:)

I suppose that there's either:
- a bug in Cairo, creating an invalid PDF that works with other readers, or
- a bug in Acrobat Pro (you'll find funny forum entries where it's said that PDF files created with Acrobat Pro give this error too).

So, you're probably on the wrong issue tracker, but I may help you to report the bug if you find what's wrong with this PDF.

**Comment by ntregillus** [comment]
wow, thanks for the help! I was able to identify the problem seems to be applying the Font-Family to containing elements that do not normally deal with this font-family attribute. I am applying the font-family attribute to div's and other components in the html, and it is correctly rendering.

when I add the font-family attribute to the following css element tags, I get the error:
body
div (though, if I assign a css class, it works correctly)
td

I am still trying to find a workaround for now, but I will try these preflight tools! (Thanks again)

**Comment by ntregillus** [comment]
HA! gotta love tools. I ran the Preflight tools on the pdf, and it say "No problems found". Thanks Adobe

**Comment by SimonSapin** [comment]
As you can see [here](https://github.com/Kozea/WeasyPrint/blob/9249f8d33af7cc95eaea455eabaf4b615099105f/weasyprint/text.py#L307-L308), WeasyPrint builds a string of comma-separated family names (without quotes) and just gives that to `pango_font_description_set_family` then it’s up to Pango, together with fontconfig, freetype, and cairo, to find the font, load it, pick a font face, subset it, and embed it in the PDF. Font embedding in PDF is horribly complicated, so I wouldn’t be surprised if there’s a bug there than only happens with some font faces.

What’s more surprising is that you get different results on `h1` and `body`. Possibly, the `font-weight` property (which is `bold` for `h1` in the user-agent stylesheet) leads to a different font face being picked.

> elements that do not normally deal with this font-family attribute

There is no such thing. The `font-family` property applies to every element. It inherits to descendant elements that don’t have it specified themselves, and only for text nodes does WeasyPrint look at it and invoke Pango at all.

**Comment by liZe** [comment]
If the Preflight tools couldn't find an error in this PDF, then it's probably time to report the bug to Adobe, give them the PDF and hope for a fix in Acrobat Pro (aka a miracle)! Let us know if they find anything wrong with the file!
