### ISSUE TITLE
Unicode character problem introduced after v0.19

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#251]
Problem with character: ○

v19:

![screen shot 2015-05-04 at 10 31 59](https://cloud.githubusercontent.com/assets/401107/7450747/dd1084f8-f248-11e4-9dd4-65649eab4649.png)

v23:

![screen shot 2015-05-04 at 10 31 43](https://cloud.githubusercontent.com/assets/401107/7450749/e42b303a-f248-11e4-9aee-05a89d9ba272.png)

The source is the same for both documents and uses ○ directly as UTF-8 character.

**Comment by knyttl** [comment]
Minimum example which demonstrate this issue:

```html
<!DOCTYPE html>
<html>
  <head><meta charset="utf-8"/></head>
  <body>●○</body>
</html>
```

**Comment by knyttl** [comment]
It seems to me it must be an issue with some of 3rd party packages – when I try to go through the git commits, the issue does not go away. It just happens with the python package.

**Comment by SimonSapin** [comment]
I could not reproduce this, either with WeasyPrint master or with version 0.23. It looks like a font issue, and unfortunately these are very system-dependent *and* WeasyPrint has very little control over them. (Pango takes care of font selection and embedding and hides all the details away.)

**Comment by knyttl** [comment]
I am pretty sure it must be some other package, but as I am not familiar with PIP packaging, I am not sure how to see which versions are used. Could you provide with some hints?

**Comment by SimonSapin** [comment]
I’m not sure what you mean. What else is different between the two cases in your first message? Are they on the same machine? Do you use virtualenv? Are they separate virtualenv environments? What’s the output of `pip --version` and `pip freeze` in either case?

**Comment by knyttl** [comment]
Okay, `pip freeze` showed different versions, however when I tried to downgrade all of them to the functional the versions I have working in production, it did not help. Obviously it must be some package out of `pip`. 

Where else should I look? Which debian packages might be affected? I tried the packages in install guide and those are all of same version.

**Comment by SimonSapin** [comment]
I’m more likely to be able to help if you answer each of my question individually, and copy/paste any output rather than paraphrase it. Thanks!

**Comment by knyttl** [comment]
```
# pip freeze
Warning: cannot find svn location for distribute==0.6.24dev-r0
CairoSVG==1.0.9
Pyphen==0.9.1
WeasyPrint==0.19
argparse==1.2.1
cairocffi==0.6
cffi==0.8.6
cssselect==0.9.1
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
html5lib==1.0b3
lxml==3.4.0
pycparser==2.10
six==1.8.0
tinycss==0.3
wsgiref==0.1.2

# pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

The results are the same for both working and not working versions now.

**Comment by SimonSapin** [comment]
Could these containers have different versions of other software? Relevant packages include Pango, cairo, hafbuzz, fontconfig, freetype. Could they have a different set of fonts available/installed?

**Comment by SimonSapin** [comment]
Why close, did you find a solution?

**Comment by knyttl** [comment]
No, in the end I gave up, I just destroyed the dev machine and cloned the production machine. All the versions were the same, fonts were the same, but on the dev machine it just kept doing this.
