### ISSUE TITLE
Style attributes mentioned in the <td> tags are getting ignored

### ISSUE THREAD

**Issue by manoharp** [Kozea/WeasyPrint#252]
I attempted to convert a simple html table where every cell has a different bgcolor into the PDF but the style attributes are not getting ignored. I enabled logging and found there were no parsing errors as well.

```
html_output_test = """
<html>
<table cellspacing="0" cellpadding="0" border="0" width="100%">
 <caption> Testing WeasyPrint </caption>
 <tbody>
  <tr>
    <td align="left" valign="top" width="1%" title bgcolor="#ffeaea">72</td>
    <td align="left" valign="top" width="1%" title bgcolor="##ffc3c3">28.5</td>
    <td align="left" valign="top" width="1%" title bgcolor="#fffdfd">102.5</td>
    <td align="left" valign="top" width="1%" title bgcolor="#ffdada">200.5</td>
  </tr>
 </tbody>

</table>
</html>
"""
HTML(string=html_output_test).write_pdf("snapshot.pdf")
```

Any thoughts on how to convert HTML which has embedded styles into PDF?

**Comment by liZe** [comment]
Actually, HTML style attrubutes are not at all supported in WeasyPrint. You can use the `style="text-align: left; ..."` syntax that works.

Grouped into #253.
