### ISSUE TITLE
Support HTML presentational attributes

### ISSUE THREAD

**Issue by liZe** [Kozea/WeasyPrint#253]

**Comment by SimonSapin** [comment]
The `style` attribute is already supported. Do you mean presentational hints? https://html.spec.whatwg.org/multipage/rendering.html#the-css-user-agent-style-sheet-and-presentational-hints

**Comment by liZe** [comment]
Yes, I do!

**Comment by liZe** [comment]
I've tried to support presentational attributes using custom `-weasy-*` functions in user-agent CSS. It's just handling size-related attributes, but this mechanism should be able to handle colors and text alignements too.

See 173d294.

Good news:
- most of the rules described in http://www.w3.org/TR/html5/rendering.html#the-css-user-agent-style-sheet-and-presentational-hints are easy to write in CSS,
- fallback values are possible.

Bad news:
- it's impossible to handle attributes that modify their children's properties (`cellpadding` for example),
- we add another prefixed CSS function.

I'm not sure that's it's done the RightWay™, but I'm interested on working on that feature if anybody's got better ideas (or if my idea is not that bad).
