### ISSUE TITLE
page-break-inside: avoid on tall elements leads to infinite loop

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#255]
When you create a very tall element with `page-break-inside: avoid` which does not fit to page, it leads to infinite looping and weasyprint never produce any result.

Test case:

```
<div style="page-break-inside: avoid;">
... lot of contents
</div>
```

**Comment by PepsiOtaku** [comment]
I'm having the same problem with a project I am using weasyprint for. If I have several block elements arranged in a parent element with "columns: 2" (or more, most likely) and one of the elements is positioned in such a way that its contents extends beyond the bottom of the page with "page-break-inside: avoid", the entire parent element (and the rest of the content contained within it) doesn't render. This is kind of a big problem as the "columns: 2" method is the best solution for multi-column print layouts.  Would be nice if this could be addressed in an update.

Current workaround is to not use "page-break-inside: avoid" at all, which makes content broken up in uneven places that doesn't make sense in the print world.

**Comment by knyttl** [comment]
I found out that in some cases it will work for `<div>`. But it will never work for `<tbody>` as follows:

```
<table>
<tbody style="page-break-inside: avoid;">
<tr><td>... lot of contents</td></tr>
<tr><td>... lot of contents</td></tr>
<tr><td>... lot of contents</td></tr>
...
</tbody>
</table>
```

**Comment by liZe** [comment]
Let's merge this issue with #273.
