### ISSUE TITLE
Under Windows pathname2url.pathname2url raises "TypeError: 'str' does not support the buffer interface"

### ISSUE THREAD

**Issue by marangonico** [Kozea/WeasyPrint#261]
Under Windows, the function path2url defined in urls.py encodes the path using 'mbcs'

    if isinstance(path, unicode):
        path = path.encode(FILESYSTEM_ENCODING)

The subsequent call to pathname2url raises *TypeError: 'str' does not support the buffer interface*

    File "c:\Python34\Lib\nturl2path.py", line 46, in pathname2url
        if not ':' in p:
    TypeError: 'str' does not support the buffer interface

**Comment by SimonSapin** [comment]
Is this on Python 2 or 3 ?

Probably WeasyPrint should give a Unicode string to `open()` rather than try to deal with filesystem encodings itself, but that would require some refactoring and unfortunately nobody is actively working on WeasyPrint at the moment.

**Comment by marangonico** [comment]
It's python 3.4

I'll see if I can send a pull request for a fix..

**Comment by Wenze** [comment]
I don't know if this is the only place where this code is used? Otherwise it can easily be fixed by converting lin 87:
    path = pathname2url(path)
to:
    path = pathname2url(path.decode('utf-8'))

**Comment by lashleykeith** [comment]
I have a problem with line 48 in nturl2path.py whenever I tried to run weasyprint.  I know it is telling me to `  File "c:\users\g\appdata\local\programs\python\python36-32\Lib\nturl2path.py", line 48, in pathname2url
    if not ':' in p:
TypeError: a bytes-like object is required, not 'str'`

However I am not sure about how to change this.  I have the nturl2path.py and the app that I am using in my repo.
![screenshot_1](https://user-images.githubusercontent.com/21030885/44836411-d3d47c00-ac71-11e8-9885-410406f17726.jpg)
