### ISSUE TITLE
Page counter zero after reset (to non-zero number)

### ISSUE THREAD

**Issue by marine-dj** [Kozea/WeasyPrint#267]
I've managed to do alternating page-margin decorations depending on whether the page is odd or even, and by counting pages in the model->pdf python program (which invokes weasyprint api), I've made it so that the page side (left/right) matches with the chapter's place in the book.

As such, I can generate each chapter individually, some chapters need a different color decorations than others, otherwise they could all be one big htm file at first.

Anyways, the counter resets to zero, and the counter-reset -rule isn't supported by weasyprint yet.

Is there any convenient way around it? I was thinking it would be pretty easy, since I keep track of the page count in each chapter, and can reset the counter accordingly.

If i concatenate the chapters before generating the pdf, only a single decoration color will be applied, which is not the intention.

**Comment by liZe** [comment]
Duplicates #93.
