### ISSUE TITLE
Is the website of weasyprint.org going to be up to date??

### ISSUE THREAD

**Issue by corebyte** [Kozea/WeasyPrint#271]
Is the website of weasyprint.org going to be up to date?

For example the news, releases, changelog and new features..

Greeting.

**Comment by SimonSapin** [comment]
There is no reason the website in particular is gonna be out of date, but the thing is not much development as happening at all on WeasyPrint at the moment, so there are no news to report.

**Comment by marclaporte** [comment]
http://weasyprint.org/news/ reports WeasyPrint 0.20
http://weasyprint.org/docs/ reports WeasyPrint 0.22
https://github.com/Kozea/WeasyPrint/releases reports WeasyPrint 0.24

Maybe add a link everywhere to Gitgub releases URLs?

Thanks!

**Comment by SimonSapin** [comment]
Thanks for the details Marc. /news/ has indeed been neglected. I think it’s mostly redundant with the changelog. We can add a notice on top that not all new releases are announced there.

/docs/ *should* be updated automatically whenever we push to git master. @liZe, any idea what’s going on? I can also set up Travis-CI to do this automatically on Other People’s Computers, if I have some way to push to weasyprint.org. We can move it to GitHub Pages, for example.

I had never seen the GitHub "Releases" page before. It looks like it’s generated automatically from git tags.

https://pypi.python.org/pypi/WeasyPrint is where releases are, so it’s authoritative as to which one is the latest.

**Comment by liZe** [comment]
The docs are updated, there was a problem with the automatic update. Switching to readthedocs could be a good idea, if possible. Removing the News section from the website and adding a link to the changelog on the front page is probably a good idea too.

**Comment by liZe** [comment]
The doc is up to date now, I've even written a news entry for 0.26!
