### ISSUE TITLE
text being truncated when rendering with @page{} style set.

### ISSUE THREAD

**Issue by alandmoore** [Kozea/WeasyPrint#275]
OS is Debian Jessie 64-bit, using weasyprint 0.24 in a Python 3.4 virtualenv.  All python dependencies installed with pip, C libraries are just default versions from the repositories.

The following html:
```
<html>
	<head>
		<style>
		@page {
			size: letter;
			margin: .5in;
			padding: 0;
		}
		</style>
	</head>
	<body>
			<p>
				Alice thought the whole thing very absurd, but they all looked so grave that she did not dare to laugh; and, as she could not think of anything to say, she simply bowed, and took the thimble, looking as solemn as she could.		
			</p>
	</body>
</html>
```
generates a pdf file as seen here: http://i.imgur.com/sdBEKpK.png .  As you can see, the text is trunctated in various ways.  If I remove the `@page{}` section of the CSS, the truncation doesn't occur.

I cannot reproduce this on an Arch linux system, which could mean that it's something to do with Debian's binary packages, but compiling versions of harfbuzz and libpango from Debian Sid did not make any difference in the problem.

I can provide the pdf if needed, github would not allow me to attach it.

**Comment by liZe** [comment]
It's probably related to #233. Debian Jessie provides Cairo 1.14.0, and Arch 1.14.2.

**Comment by alandmoore** [comment]
I upgraded to cairo 1.4.2 and indeed, it fixed the problem.  I'm closing this since it's a duplicate.
Thanks for your help.
