### ISSUE TITLE
Pictures blowing up the size of the PDF.

### ISSUE THREAD

**Issue by philippeowagner** [Kozea/WeasyPrint#282]
![screen shot 2015-12-04 at 09 51 37](https://cloud.githubusercontent.com/assets/113043/11589652/743cd31a-9a8a-11e5-90d7-0e9042ca7666.png)
![screen shot 2015-12-04 at 09 51 45](https://cloud.githubusercontent.com/assets/113043/11589653/743e9236-9a8a-11e5-8d66-5c3ffc576d4d.png)

**Comment by philippeowagner** [comment]
![screen shot 2015-12-04 at 13 26 37](https://cloud.githubusercontent.com/assets/113043/11589716/ec1fcf2c-9a8a-11e5-8929-cbbda69d57e1.png)
The images added to the HTML are small and optimized, but the final PDF has a huge file size at the end.

**Comment by liZe** [comment]
Could you provide the source please? (Image, HTML, CSS)

**Comment by philippeowagner** [comment]
Sure, http://pastebin.com/yPDL7XWV.
CSS is all inline and the images are loaded from the server. 
The logo in the top left was added as a post process (adding background) using PDFTK.

**Comment by liZe** [comment]
With your example, the images are 63 + 41 + 87 = 191 kB, and the PDF is 216 kB, there's no problem for me!

**Comment by philippeowagner** [comment]
Thats good and bad at the same time ;-) We got this output http://www.inflexion.ch/github-issues-12-2015/6-20xx-1449129895-congohoundfesttage2015.pdf . So, the next in the chain would be PDFTK?!  Could you please provide the generated PDF to compare the inner structure?

**Comment by liZe** [comment]
[letter.pdf](https://github.com/Kozea/WeasyPrint/files/52092/letter.pdf)

**Comment by philippeowagner** [comment]
Thanks @liZe !

**Comment by philippeowagner** [comment]
Thanks again @liZe for your support. It seems that the error comes from the post processing using PDFTK.

**Comment by liZe** [comment]
You're welcome, good luck!
