### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'attachments'

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#286]
bin/weasyprint  -a test.svg  index.html index.pdf
Traceback (most recent call last):
  File "bin/weasyprint", line 9, in <module>
    load_entry_point('WeasyPrint==0.25', 'console_scripts', 'weasyprint')()
  File "/Users/ajung/src/enbit/lib/python3.4/site-packages/weasyprint/__main__.py", line 150, in main
    kwargs['attachments'] = args.attachments
AttributeError: 'Namespace' object has no attribute 'attachments'

How about quality control and unit tests?

**Comment by SimonSapin** [comment]
> How about quality control and unit tests?

So entitlement. Many helpful. Wow.

**Comment by zopyx** [comment]
Some more blather?

**Comment by SimonSapin** [comment]
In other language: you’re using for free the fruit of a couple years of work, and you think that a hostile comment like this is gonna improve your chances of getting help from strangers?

This honestly doesn’t look hard to fix, but now I’m going to do something else instead and won’t comment further on this issue.

By the way, unit tests for `__main__.py` are in `test_command_line_render()` in `weasyprint/tests/test_api.py`.

**Comment by zopyx** [comment]
Software breaking after a few tries...and then couple of years work....poor software..yes, hostile...too much broken software out in the wild that would be better kept in a private repo.

**Comment by liZe** [comment]
See d09ba47.
