### ISSUE TITLE
Table header (maybe footer too) not repeated on each pages

### ISSUE THREAD

**Issue by Daisho** [Kozea/WeasyPrint#29]
With weasyprint 0.16 and an html document with a big table taking at least 2 pages, and a thead section, those header are not repeated on next pages.

**Comment by NailaAkbar00** [comment]
@Daisho  I'm trying to show a big table in weasyprint but it only shows one page and truncate remaining data. Can you help me out with this issue? How you managed to show all data on multiple pages?

**Comment by ritiksoni00** [comment]
> @Daisho I'm trying to show a big table in weasyprint but it only shows one page and truncate remaining data. Can you help me out with this issue? How you managed to show all data on multiple pages?


@NailaAkbar00  its a bit late. you able to make it or not

**Comment by nailaakbar** [comment]
Its been very long time..but I guess we achieved this somehow. (Not remember the exact solution)
