### ISSUE TITLE
Cannot `extractText` from generated PDF

### ISSUE THREAD

**Issue by mattjmorrison-imt** [Kozea/WeasyPrint#290]
For some reason when I use WeasyPrint to generate a pdf document I am unable to get any text from the document using PyPDF2. 

```python
"""
PyPDF2==1.25.1
WeasyPrint==0.23
"""

from PyPDF2 import PdfFileReader
from weasyprint import HTML


HTML(string="""
<html>
<body>
<div>Hello World</div>
</body>
</html>
""").write_pdf('/tmp/out.pdf')


reader = PdfFileReader('/tmp/out.pdf')
print reader.getPage(0).extractText()

```

**Comment by SimonSapin** [comment]
Cairo (and maybe Pango) are responsible for how text is represented in PDF, so this is largely outside WeasyPrint’s control.

**Comment by liZe** [comment]
The text is definitely available from the PDF, I can get it at least with poppler (library used by many PDF readers) and command tools such as `pdftotext` and `ps2ascii`. Looks like a bug in PyPDF2.
