### ISSUE TITLE
font-family works in pango-view doesn't work from weasyprint

### ISSUE THREAD

**Issue by BodhiSukha** [Kozea/WeasyPrint#292]
I'm experiencing a similar problem to #231. When I test like this ```pango-view --no-display --output out.png --text '0123456789 - @ The lazy fox something something' --font 'Neuton' ``` it produces image with correct font, however when I use weasyprint render (via django) it some how can't find the fonts and falls back to some default font. And I tried many different name combinations ('Neutron', Neutron-Regular etc.)

What is right approach to debug this? Is there a way to, for example from pyhon shell, to check/list which fonts are available for weasyprint font-family (and I read it's passed directly to pango, so in other words available to pango)? 

Thanks,

Using OSX (dev) and Ubuntu (prod) 
- WeasyPrint (0.23)
- cairocffi (0.5.4)
- cffi (0.8.6)

**Comment by liZe** [comment]
First of all, you can try to convert a simple HTML sample (`<p style="font-family: Neuton">test`) to PDF with the command-line, and see if it works (it does for me with the Neuton-Regular.ttf font dowloaded from dafont and installed on my system).

If it does work for you, then it's probably related to the user launching your django app. It's a common mistake to install a font for just you (and not for the whole system), and then try to render a document with another user who cannot reach the font.

**Comment by BodhiSukha** [comment]
Hi @liZe , thank you for your time and quick response. 

It was indeed the case; the font wasn't installed globally. On a side note though, on OSX I actually thought about it before and tried to reinstall globally and system gave me "duplicate font" errors so I assumed it was actually installed globally. However, when I uninstalled the font and reinstalled only globally and it started working.
