### ISSUE TITLE
footnote support

### ISSUE THREAD

**Issue by simblestudios** [Kozea/WeasyPrint#296]
I'm unable to tell if WeasyPrint is supposed to support footnotes or not (I'm probably missing where it says it doesn't) but if it _doesn't_ support them, then this is a feature request. If it is supposed to support them, then it's a bug.

    (weasy)test $ weasyprint --version
    WeasyPrint version 0.26
    (weasy)test $ weasyprint book.html footy.pdf
    Ignored `float: footnote` at 34:11, invalid value.
    Invalid or unsupported selector '.fn::footnote-call', Unknown pseudo-element: footnote-call
    Invalid or unsupported selector '.fn::footnote-marker', Unknown pseudo-element: footnote-marker

**Comment by SimonSapin** [comment]
They’re not supported at the moment. http://weasyprint.org/docs/features/ should be exhaustive. (If it’s not, that’s a documentation bug.)

**Comment by simblestudios** [comment]
Thanks for the clarification! I wasn't sure if footnote-call and the other Generated Content stuff was part of this on the features page:

    The following features are supported:
        CSS Colors Level 3 (except the deprecated System Colors)
        **CSS Paged Media (except named pages)**
        ...

Maybe some clarification on that would be useful? I'd be happy to PR an update, but I'm not sure what is / isn't supported as it seems some parts (like `string()`) are.

Thanks again for the info, and thanks even more for Weasy!

**Comment by SimonSapin** [comment]
"CSS Paged Media" in your quote links to https://drafts.csswg.org/css-page-3/ . That’s a different document from https://drafts.csswg.org/css-gcpm/

**Comment by simblestudios** [comment]
Understood. But remember, some of your users are dumb people (like me!) who are new to all this stuff and might get confused. ;)

**Comment by SimonSapin** [comment]
No worries :) How do you think the docs could be clarified?

**Comment by simblestudios** [comment]
Not sure exactly. Perhaps a line about the Generated Content (because you *do* seem to support some of it, yes?) in the `Other CSS Modules` section would be helpful. Footnotes are an important feature to some, and if you happen to know it's a Generated Content thing, you can infer it's not supported by omission, but for people just getting into this realm who have no / limited knowledge of the various specs, this might save them from fighting for a while with El Capitan to install only to find no footnotes.

**Comment by SimonSapin** [comment]
@liZe, do you wanna rewrite this section? http://weasyprint.org/docs/features/#css-gcpm-bookmarks

**Comment by liZe** [comment]
I do!

**Comment by simblestudios** [comment]
Just saw the updated docs... good stuff!

**Comment by liZe** [comment]
I've open #298 about adding the feature.
