### ISSUE TITLE
Support footnotes

### ISSUE THREAD

**Issue by liZe** [Kozea/WeasyPrint#298]

**Comment by liZe** [comment]
> Is there a workaround for footnotes at this moment?

There's unfortunately no real workaround, unless you know the maximum height of your footnotes and thus can put them on the bottom page margin. (That's ugly.)

What we have to support is page floats, see #259.

**Comment by liZe** [comment]
Oh, and there's [a section dedicated to footnotes in GCPM](https://www.w3.org/TR/css-gcpm-3/#footnotes).

**Comment by remofritzsche** [comment]
Great, thanks for your support 😃

**Comment by fabiobatalha** [comment]
Is this feature in the roadmap of WeasyPrint?

**Comment by Tontyna** [comment]
Implementing page floats will require a complete redesign of WeasyPrint's layout concept. Rendering  the pages first and filling the margin boxes afterwards won't work anymore. A huge task. 
But when somebody undertakes it I hope we'll finally get parallel flows, too.

**Comment by Stigjb** [comment]
Support for footnotes would be really useful, especially if the required changes in Weasyprint would also lead to support for other floated content. It's been a year since the last comment, is there anything on the roadmap that leads in this direction? Are there any tasks where new contributors could be helpful, for instance?

**Comment by liZe** [comment]
> It's been a year since the last comment, is there anything on the roadmap that leads in this direction?

The feature is listed in the [roadmap](https://www.courtbouillon.org/blog/00002-on-the-road), but there’s no specific date yet. As explained in that article, we’ll ask what’s important for users as soon as Cairo has been removed. For sure, this feature will probably be in good place judging from the 👍🏼s.

> Are there any tasks where new contributors could be helpful, for instance?

Unfortunately, that’s not the easiest feature to add for new contributors. The paged layout features and modern layouts (and even proper right-to-left support) will probably need #36 to be solved before. It may be the next big change to come in WeasyPrint.

If anyone wants to start contributing, a good start is to solve one of the [good first issues](https://github.com/Kozea/WeasyPrint/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). And if you’re not fond of Python and CSS specs, [donations](https://opencollective.com/courtbouillon) really help us to give more time and love to WeasyPrint.

**Comment by grewn0uille** [comment]
Hello!

If you’re interested in footnotes, we created a [short survey](https://app.evalandgo.com/s/index.php?id=JTk4cCU5NG8lOUQlQUQ%3D&a=JTk3biU5M2glOUMlQUI%3D) where you can give a boost to this feature and help us to improve WeasyPrint 😉

Vote for it!

**Comment by liZe** [comment]
Thanks to 💜 @code-and-co 💜, [footnotes](https://www.w3.org/TR/css-gcpm-3/#footnotes) are now supported by WeasyPrint.

What’s missing from the specification:
- the compact value of [`footnote-display`](https://drafts.csswg.org/css-gcpm/#propdef-footnote-display),
- [resetting](https://drafts.csswg.org/css-gcpm/#resetting-footnote-counter) the counter value for each page (because the footnote counter is not a page-based counter).

Everything else should work correctly. Don’t hesitate to test and give us feedback!

**Comment by dlpgit22407** [comment]
I was recently asked to look at weasyprint to replace out current tool to create pdfs. Most everything seems to work but I am seeing some problems with footnotes and cannot find documentation on exactly what you support.  

![example_page](https://user-images.githubusercontent.com/93775787/158810629-6f53352c-7a38-4970-9f3b-da27f8843c4a.PNG)
[test-case.log](https://github.com/Kozea/WeasyPrint/files/8286083/test-case.log)
 
The test-case.log file includes data, css style, and the instructions to recreate the problem that I am seeing. The footnotes seem to work fine until I start using columns. 

The example_page image shows one of our documents and how we current handle footnotes for this service. 

I am new to css but I tried a number of ways to get this to work and this was the simplest way to demo the problem. 

Please let me know if this is a bug or if I am doing something wrong. Also let me know if your tool can match what we are currently doing or what is the best you can offer now or in the near future. 

Thank You

**Comment by anthonyalayo** [comment]
> [resetting](https://drafts.csswg.org/css-gcpm/#resetting-footnote-counter) the counter value for each page (because the footnote counter is not a page-based counter).

@liZe has this been implemented? I am presently trying to call `counter-reset: footnote;` inside `@page`, but nothing is happening.

**Comment by liZe** [comment]
> has this been implemented? I am presently trying to call `counter-reset: footnote;` inside `@page`, but nothing is happening.

@anthonyalayo I don’t think so, could you please open a new issue?

**Comment by arikrupnik** [comment]
> > has this been implemented? I am presently trying to call `counter-reset: footnote;` inside `@page`, but nothing is happening.
> 
> [@anthonyalayo](https://github.com/anthonyalayo) I don’t think so, could you please open a new issue?

@igor-makarov opened a new issue for this in September: #2553 
This would be helpful for my use case. Can I help, or is it one of those not-good-as-a-first-issue issue?

**Comment by liZe** [comment]
> This would be helpful for my use case. Can I help, or is it one of those not-good-as-a-first-issue issue?

@arikrupnik That’s definitely not easy, but you can try! I’ll add more information in #2553, let’s continue the discussion over there.
