### ISSUE TITLE
Silence logs

### ISSUE THREAD

**Issue by sibeliusseraphini** [Kozea/WeasyPrint#300]
I'm using WeasyPrint to generate pdf using Celery with Flask

I've tried to use this code

```python
import logging
logger = logging.getLogger('weasyprint')
logger.handlers = []  # Remove the default stderr handler
logger.addHandler(logging.FileHandler('/path/to/weasyprint.log'))
```

But it didn't silent the logs on celery.

how can I just remove the logging ?

**Comment by SimonSapin** [comment]
I honestly don’t remember how the logging module works. What happens if you use `import weasyprint; logger = weasyprint.LOGGER` instead of `getLogger`?

If all else fails, you can always brutally monkey-patch:

```python
weasyprint.LOGGER.warning = lambda *a, **kw: None
```

**Comment by sibeliusseraphini** [comment]
thanks
