### ISSUE TITLE
Weasyprint not building properly

### ISSUE THREAD

**Issue by ttasket** [Kozea/WeasyPrint#302]
After following install instructions from the website, I get this error on debian 8 if I run 'weasyprint' or 'weasyprint --help':

```
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (cffi 0.8.6 (/usr/lib/python2.7/dist-packages), Requirement.parse('cffi>=1.1.0'))
```

**Comment by ttasket** [comment]
I also tried installing on fedora 23 and got this during pip install:

```
Collecting cffi>=0.6 (from weasyprint)
  Downloading cffi-1.5.2.tar.gz (388kB)
    100% || 389kB 1.0MB/s 
    Complete output from command python setup.py egg_info:
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    
        No working compiler found, or bogus compiler options
        passed to the compiler from Python's distutils module.
        See the error messages above.
        (If they are about -mno-fused-madd and you are on OS/X 10.8,
        see http://stackoverflow.com/questions/22313407/ .)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6kEwrd/cffi

```

**Comment by liZe** [comment]
@ttasket did you install the needed packages, [as written in the documentation](http://weasyprint.org/docs/install/#fedora)?

**Comment by ttasket** [comment]
Yes, I did.

**Comment by liZe** [comment]
Looks like [a problem with Fedora](https://developer.fedoraproject.org/tech/languages/ruby/gems-installation.html). You can try `sudo dnf install redhat-rpm-config` as proposed in that page.

**Comment by liZe** [comment]
I've added `redhat-rpm-config` in the documentation. Moreover, WeasyPrint seems to be packaged in Fedora now :smile:.

**Comment by ttasket** [comment]
I just tried the fedora install and get this when I run weasyprint:

$ weasyprint
Traceback (most recent call last):
   File "/usr/bin/weasyprint", line 5, in <module>
     from pkg_resources import load_entry_point
   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", 
line 3084, in <module>
     @_call_aside
   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", 
line 3070, in _call_aside
     f(*args, **kwargs)
   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", 
line 3097, in _initialize_master_working_set
     working_set = WorkingSet._build_master()
   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", 
line 651, in _build_master
     ws.require(__requires__)
   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", 
line 952, in require
     needed = self.resolve(parse_requirements(requirements))
   File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", 
line 839, in resolve
     raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'WeasyPrint==0.22' distribution 
was not found and is required by the application

**Comment by ttasket** [comment]
Although the fedora 23 package appears broken (see above), I was able to get weasyprint working by installing redhat-rpm-config and then pip install weasyprint.

The pip install is still broken on debian 8.

**Comment by liZe** [comment]
> The pip install is still broken on debian 8.

I think that you have the `python-cffi` package installed by your system (version 0.8.6), and there's probably a bug in cairocffi's `setup.py` needing at least 1.1.0 at runtime (but not during the installation). See #281.

The easiest solution is to install WeasyPrint in a virtual environment, where you can safely install the latest version of cairocffi.

**Comment by liZe** [comment]
@ttasket Is everything OK for you now?

**Comment by BrettCan** [comment]
I'm also having trouble with installing WeasyPrint on Debian 7.10.  
After following all installation instructions, `weasyprint` and `weasyprint --help` just return: 

Traceback (most recent call last):                                              
  File "/usr/local/bin/weasyprint", line 5, in <module>                         
    from pkg_resources import load_entry_point                                  
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <modul
e>                                                                              
    working_set.require(__requires__)                                           
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))                     
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)                                             
pkg_resources.DistributionNotFound: Pyphen>=0.8

**Comment by liZe** [comment]
Wow. Believe me or not, we have 3 different problems with almost the same error.

# First problem

`pkg_resources.VersionConflict: (cffi 0.8.6 (/usr/lib/python2.7/dist-packages), Requirement.parse('cffi>=1.1.0'))`

This bug is explained in #281. It's a dirty bug in cairocffi's `setup.py`. This can be solved by installing the latest version of cffi: `pip install --upgrade cffi`.

# Second problem

`pkg_resources.DistributionNotFound: The 'WeasyPrint==0.22' distribution was not found and is required by the application`

Two different versions of WeasyPrint are installed in two different locations. The `weasyprint` executable is from one version, but it imports the `weasyprint` library from the other version (over-simplified explanation). This can be solved by keeping only one version of WeasyPrint installed, or by installing different versions of WeasyPrint in different virtualenvs.

# Third problem

`pkg_resources.DistributionNotFound: Pyphen>=0.8`

WeasyPrint has been installed or updated without its dependencies. This can probably be solved by upgrading or reinstalling WeasyPrint with `pip install --upgrade weasyprint`. In this specific case, you can also install a new version of Pyphen with `pip install --upgrade pyphen`.

**Comment by zobaken** [comment]
Hi, i have the same situation:

```
# weasyprint 
Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Pyphen>=0.8
```

```
# pip show weasyprint
---
Metadata-Version: 1.1
Name: WeasyPrint
Version: 0.28
Summary: WeasyPrint converts web documents to PDF.
Home-page: http://weasyprint.org/
Author: Simon Sapin
Author-email: simon.sapin@kozea.fr
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires: lxml, html5lib, tinycss, cssselect, CairoSVG, cffi, cairocffi, Pyphen
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: BSD License
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Topic :: Internet :: WWW/HTTP
  Topic :: Text Processing :: Markup :: HTML
  Topic :: Multimedia :: Graphics :: Graphics Conversion
  Topic :: Printing
Entry-points:
  [console_scripts]
  weasyprint = weasyprint.__main__:main
```

```
# pip show pyphen
---
Metadata-Version: 2.0
Name: Pyphen
Version: 0.9.4
Summary: Pure Python module to hyphenate text
Home-page: https://github.com/Kozea/Pyphen
Author: Guillaume Ayoub
Author-email: guillaume.ayoub@kozea.fr
Installer: pip
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
  License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)
  License :: OSI Approved :: Mozilla Public License 1.1 (MPL 1.1)
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.1
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy
  Topic :: Text Processing
  Topic :: Text Processing :: Linguistic
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

I followed the instructions and did `pip install --upgrade weasyprint` and `pip install --upgrade pyphen`.

**Comment by zobaken** [comment]
solved with `sudo pip install —upgrade ndg-httpsclient`

**Comment by BrettCan** [comment]
zobaken, that just worked for me!  Thank you so much!!!
