### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by liZe** [Kozea/WeasyPrint#305]
Example:

```html
<table>
  <tr>
    <td>
      <table>
        <tr>
          <th>Test</th>
        </tr>
        <tr>
          <td style="min-width: 100%;"></td>
          <td style="width: 48px;"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
```

**Comment by liZe** [comment]
Probably related:

`cairocffi.CairoError: cairo returned CAIRO_STATUS_INVALID_MATRIX: b'invalid matrix (not invertible)'`

```
<table>
  <tr>
    <td>
      <table>
        <tr>
          <td style="width: 100%;"></td>
          <td style="width: 48px;"><img src="http://weasyprint.org/samples/acid2-small.png"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
```

**Comment by elenberg** [comment]
Any luck on this getting fixed soon? 

I'm really wanting to use Weasyprint.

**Comment by liZe** [comment]
And probably related too:

`ValueError: cannot convert float NaN to integer`

```html
<table>
  <tr>
    <td>
      <table style="display: inline-table">
        <tr>
          <th style="min-width: 100%;"></th>
          <td></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
```

@elenberg that's a really dirty bug mixing percentages and nested tables… Each time I'm trying to find a solution, I find another related bug.

**Comment by liZe** [comment]
@elenberg That was awful and it's 1AM: you owe me a :beer: :wink:.

**Comment by elenberg** [comment]
Sure thing! What's the best way for me to send you one?
