### ISSUE TITLE
Timeout for default_url_fetcher

### ISSUE THREAD

**Issue by PAStheLoD** [Kozea/WeasyPrint#306]
Hello!

In some cases slow external assets can basically lock up WeasyPrint, because currently no timeout is given to Requests. Maybe a default value of 30 seconds is reasonable, though making it user configurable would be better.

Thanks!

**Comment by SimonSapin** [comment]
WeasyPrint uses `urllib2` / `urllib.request`, not Requests. The `urlopen` function has had an optional `timeout` parameter since Python 2.6, so it shouldn’t be hard to use that. What should this look like in WeasyPrint’s Python API? Something like this?

```python
weasyprint.HTML(…, url_fetcher=weasyprint.default_url_fetcher.with_timeout(30))
```

**Comment by PAStheLoD** [comment]
I had a global setting in mind, sort of 

```
import weasyprint
weasyprint.URL_FETCHER_TIMEOUT = 30.0
```

But the `.with_timeout(30)` provides call site customizability.

I tried to chase the type of the timeout argument, but let's just say that urllib is not the most elegant piece of code I've seen, so going the empirical way it seems it accepts and respects floats.

**Comment by SimonSapin** [comment]
Docs say

> The optional timeout parameter specifies a timeout in seconds for blocking operations like the connection attempt (if not specified, the global default timeout setting will be used). 

I’m fairly sure both integers and float arguments work.

If you want a global setting, it sounds like `socket.setdefaulttimeout()` would work without any change to WeasyPrint.

**Comment by yardensachs** [comment]
+1

**Comment by yardensachs** [comment]
+1 
Recent S3 issue, made the generation of PDF a failure because S3 did not return the images.

I would like to change the timeout for PDF files without changing the timeout for all sockets.
