### ISSUE TITLE
local variable 'lower_guess' referenced before assignment

### ISSUE THREAD

**Issue by jgelens** [Kozea/WeasyPrint#307]
The following error occured using 0.26. Version 0.25 was working fine.

```
File "python2.7/site-packages/weasyprint/layout/tables.py", line 582, in auto_table_layout
    if upper_guess == lower_guess:
UnboundLocalError: local variable 'lower_guess' referenced before assignment

```

**Comment by liZe** [comment]
@jgelens thank you for your report. Could you please provide a example of HTML/CSS raising this error?

**Comment by jgelens** [comment]
Thanks for quick reply. I pasted the HTML here: http://pastebin.com/FJJqRkRB

**Comment by liZe** [comment]
It was **SO FUN** to debug :smile:, a lot of interesting corner cases in a single bug report, I've spent a good time, thank you!

(A real table-Jedi I'm becoming. Zviou Zviou.)

I've added a lot of tests, I hope that it'll cover all the strange cases like this one.

**Comment by jgelens** [comment]
wow great, you're fast :-D Not perfect HTML/CSS is kinda tricky I guess. Thanks a lot for your great lib. Will you do a new release soonish or shall I try it with the git master?

**Comment by liZe** [comment]
0.27 will be released today.
