### ISSUE TITLE
ImportError: cannot import name HTML

### ISSUE THREAD

**Issue by asarch** [Kozea/WeasyPrint#308]
No matter which tool you are currently using (virtualenv, virtualenvwrapper) I get:

```
Traceback (most recent call last):
  File "./to_render.py", line 18, in <module>
    from weasyprint import HTML
  File "/home/asarch/weasyprint.py", line 18, in <module>
ImportError: cannot import name HTML
```

pip freeze reports:

```
CairoSVG==1.0.20
Jinja2==2.8
MarkupSafe==0.23
Pyphen==0.9.4
WeasyPrint==0.26
argparse==1.2.1
cairocffi==0.7.2
cffi==1.5.2
cssselect==0.9.1
html5lib==0.9999999
lxml==3.6.0
pycparser==2.14
six==1.10.0
tinycss==0.3
wsgiref==0.1.2

```

**Comment by SimonSapin** [comment]
Your `weasyprint.py` file is probably what’s being imported by `from weasyprint import …`, shadowing the `WeasyPrint==0.26` package. Try renaming that file to something else.

**Comment by SimonSapin** [comment]
To be sure that’s indeed what’s going on, try adding this at the start of your `to_render.py` file:

```python
import weasyprint
print(weasyprint.__file__)
```

**Comment by asarch** [comment]
Thank you! It worked! Thank you very much :-)
