### ISSUE TITLE
Honor the vertical-align property in fixed-height cells

### ISSUE THREAD

**Issue by Daisho** [Kozea/WeasyPrint#31]
inside table cell vertical align is not working

**Comment by honi** [comment]
Having the same problem here. Does anybody know if @s31415 fix works? Any plan on merging it?

**Comment by knyttl** [comment]
vertical-align: center does not work either.

**Comment by liZe** [comment]
I'll take a look at this

**Comment by liZe** [comment]
The patch proposed in #214 works for fixed-height rows, but not for fixed-height cells. I'm trying to find a better solution.

**Comment by liZe** [comment]
`vertical-align` was handled for cells with an auto height (ie. adding padding to make it fit in the row), but it was not handled for cells with a fixed height (ie. changing the position of the content in the cell).

f4f8c25 fixes the main common cases (and doesn't break any test). I'm not sure about many corner cases, including:
- cells with a `vertical-align: baseline` property
- cells with a fixed height and a vertical padding
- cells in fixed-height rows (what #214 is about)

I'll add some tests and fix the bugs I can find. @honi @knyttl : you are welcome to test and find any case that's not working for you!
