### ISSUE TITLE
Hide stderr warnings

### ISSUE THREAD

**Issue by erichonkanen** [Kozea/WeasyPrint#312]
Hello,

I am using this library and have added bootstrap to my html template that gets rendered to pdf. Although this works it is also causing lots of warnings to be sent to the server logs and I'm wondering if there is a way to turn that off?

`You may see warnings on stderr about unsupported CSS properties`
http://weasyprint.readthedocs.org/en/latest/tutorial.html

That link says it outputs to stderr so I'm wondering how I can disable the warnings?

Here is my template http://dpaste.com/2SKSP7Q

**Comment by SimonSapin** [comment]
From the page you linked to: https://weasyprint.readthedocs.org/en/latest/tutorial.html#logging

> ```python
> import logging
> logger = logging.getLogger('weasyprint')
> logger.handlers = []  # Remove the default stderr handler
> logger.addHandler(logging.FileHandler('/path/to/weasyprint.log'))
> ```

(You can also skip the last line.)

If you’re using the command-line API, for now you’ll have to switch to Python to change logging. Maybe we can add command-line arguments for this.

**Comment by erichonkanen** [comment]
@SimonSapin I tried add the following and it did not turn off the log output into stderr (maybe I need to add it somewhere else in my django project?

# proj/apps/orders/models.py

```
import uuid
import logging

from django.apps import apps
...
from weasyprint import HTML

wlogger = logging.getLogger('weasyprint')
wlogger.handlers = []
```

**Comment by SimonSapin** [comment]
Uh, it’s been a while since I’ve messed with the `logging` module. @liZe, any idea?

**Comment by liZe** [comment]
@erichonkanen I've found `logging.getLogger('weasyprint').setLevel(100)` in WeasySuite, it may solve your problem.

**Comment by liZe** [comment]
@erichonkanen Did it help?

**Comment by liZe** [comment]
It probably did.

**Comment by erichonkanen** [comment]
will try shortly thanks

**Comment by rrggrr** [comment]
Can confirm this works. 

`import logging
logging.getLogger('weasyprint').setLevel(100)
`

**Comment by liZe** [comment]
See #412 too.

**Comment by alacret** [comment]
This: 

```
import logging 
logging.getLogger('weasyprint').setLevel(100)
```

Doesn't work for Django applications.

**Comment by liZe** [comment]
> This:
> 
> ```
> import logging 
> logging.getLogger('weasyprint').setLevel(100)
> ```
> 
> Doesn't work for Django applications.

Since #412 is solved, WeasyPrint logging has no handler when it’s used as a library, so using setlevel will not be enough. Please follow [the example from the documentation](https://weasyprint.readthedocs.io/en/stable/tutorial.html#logging) to add a handler.

**Comment by alacret** [comment]
@liZe Examples in the documentation didn't work either. I updated the comment for the settings.py on Django, that is a mix of different solutions here.

**Comment by taylanpince** [comment]
Suggestions here didn't work for me, so I ended up going with:

```
import warnings
warnings.filterwarnings("ignore", module="weasyprint")
```

Just put it in `settings.py` if you are using Django.
