### ISSUE TITLE
Nested unordered list produces weird symbols

### ISSUE THREAD

**Issue by rvanheest** [Kozea/WeasyPrint#318]
If I have a nested unordered list in my HTML and generate a pdf with it using WeasyPrint, I get a weird symbol for the list items in the 'inner-list':

```html
<ol>
	<li>abc</li>
	<li>
		<ul>
			<li>foo</li>
			<li>bar</li>
		</ul>
	</li>
	<li>def</li>
</ol>
```

It doesn't matter whether I use CSS here, it just shows weird symbols!

```css
ul { list-style-type: circle; }
```

Image of the 'weird symbol':
![image](https://cloud.githubusercontent.com/assets/5938204/15539888/52489be4-2285-11e6-84f5-fded7813245b.png)

I noticed though that when I change `circle` in my CSS to `square`, it shows a different 'weird symbol':
![image](https://cloud.githubusercontent.com/assets/5938204/15539918/98529f2c-2285-11e6-838d-5d61b989b3de.png)

**Comment by SimonSapin** [comment]
These symbols are supposed to be "white bullet" and "small black square":

http://www.fileformat.info/info/unicode/char/25e6/index.htm
http://www.fileformat.info/info/unicode/char/25aa/index.htm

It looks like you don’t have any font with glyphs for them. Is this a server? Does installing some more fonts help?

**Comment by rvanheest** [comment]
To answer your questions first: yes, its running on a CentOS 6 server and yes, we have very limited fonts installed (currently using one of the default fonts: 'Bitstream Charter') which probably don't have these characters.

Regarding my question, turns out what I wanted was a disc rather than a circle. Stupid me switched those names around... My solution now is as follows:

```css
ol li ul { list-style-type: disc; }
```

Thanks for the quick response!

**Comment by EugenMayer** [comment]
@SimonSapin we are running into the same issues. 
we are using 

```css
font-family:  Helvetica, Arial, sans-serif;
```

and `list-style-type: square` is not shown (garbage as you have shown). We are using an alpine:latest container with 

```
apk --no-cache add msttcorefonts-installer fontconfig 
update-ms-fonts
fc-cache
```

reproduceable for weasy using

```bash
FROM alpine:latest

RUN apk --update --upgrade add supervisor cairo pango gdk-pixbuf py3-cffi py3-pillow py-lxml py3-pip \
 && apk --no-cache add msttcorefonts-installer fontconfig \
 && apk --no-cache add ca-certificates dpkg bash curl su-exec \
 && update-ms-fonts \
 && fc-cache
```

could we reopen the issue for further investigation?

**Comment by SimonSapin** [comment]
I’d recommend filing a new issue, although Pango does all of the font selection and WeasyPrint doesn’t have a lot of control over that. (Note though that I’m less involved in the project these days, so no need to ping me personally.)

**Comment by EugenMayer** [comment]
thank you, opened an new issue https://github.com/Kozea/WeasyPrint/issues/1182
