### ISSUE TITLE
Installing dependencies on Fedora

### ISSUE THREAD

**Issue by rvanheest** [Kozea/WeasyPrint#321]
On [this page](http://weasyprint.readthedocs.io/en/latest/install.html#fedora) I see a command that starts with `sudo yum install redhat-rpm-configrpm`. This dependency however cannot be resolved. Shouldn't this be just `redhat-rpm-config`, without the last `rpm`? Or should there be a whitespace between those?

**Comment by liZe** [comment]
Thanks for the report! It was probably a typo, even if I can't remember who told us to add `redhat-rpm-config`.
