### ISSUE TITLE
I could not install windows version of weasyprint because lack of information ...

### ISSUE THREAD

**Issue by ChameleonRed** [Kozea/WeasyPrint#329]
I installed weasyprint with pip on Python 2.7.x 32 and it not works after gtk installation.

I trying install weasyprint with pip on Python 3.5.x 32 and it can not install lxml.

Can you specify what exactly version of files works if you tested at least one configuration?

This information no specify anything apart Python 2.7.
http://weasyprint.readthedocs.io/en/latest/install.html

>     Get CPython 2.7 from python.org,
>     Christoph Gohlke’s unofficial binaries for CFFI and lxml,
>     and Alexander Shaduri’s GTK+ installer. Make sure that Set up PATH environment variable checked.

Which GTK I need from?
http://gtk-win.sourceforge.net/home/index.php/Main/Downloads

Why I receive: "The procedure entry point pango_font_map_changed could not be located in the dynamic link library libpango-1.0-0.dll"?

Is lxml cffi must be installed from http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml not from pypi?

**Comment by liZe** [comment]
I've updated the documenation, the new instructions should be online in a couple of minutes.
