### ISSUE TITLE
Weasyprint fails on Windows 7/Python 2.7.x

### ISSUE THREAD

**Issue by ChameleonRed** [Kozea/WeasyPrint#330]
Python 2.7.x
GTK+ Ash (last version)

Why cairo2 not want to load?

```
$weasyprint
Traceback (most recent call last):
  File "c:\root\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\root\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\root\python27\scripts\weasyprint.exe\__main__.py", line 5, in <module>
  File "c:\root\python27\lib\site-packages\weasyprint\__init__.py", line 336, in <module>
    from .css import PARSER, preprocess_stylesheet  # noqa
  File "c:\root\python27\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values
  File "c:\root\python27\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "c:\root\python27\lib\site-packages\weasyprint\text.py", line 18, in <module>
    import cairocffi as cairo
  File "c:\root\python27\lib\site-packages\cairocffi\__init__.py", line 46, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "c:\root\python27\lib\site-packages\cairocffi\__init__.py", line 43, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2
```

**Comment by jbouclier** [comment]
I did need to add the route to my GTK instalation before running weasyprint.

Have you tried run it like this?

```
@set PATH=C:\path_to_your_installation\GTK2_RT64\lib;%PATH%
weasyprint
 
```

**Comment by ChameleonRed** [comment]
I added GTK path and not works - GTK explained in documentation. I can try it with different version of GTK - I am using currently Python 2.7 - maybe I need to use Python 3. It takes some weeks until will be time to do it.

**Comment by liZe** [comment]
@jbouclier @ChameleonRed I've written [a small list of instructions](https://github.com/Kozea/WeasyPrint/pull/132#issuecomment-230515756) to make WeasyPrint work on Windows. Could you try it?

**Comment by jbouclier** [comment]
@ChameleonRed 

I'm using Python 2.7.11 (64bits) for windows together with GTK2 (64bits) I downloaded from here:

https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

May be there are some other dependecies on native libraries, like the C++ complier @liZe mentions. Is hard for me to tell. I did the installation in a development machine. I lost track what I installed there and why.

**Comment by liZe** [comment]
When trying to install random GTK versions (for example mixing 64 bit Python with 32 bit), I've met this error, but it works with the new instructions. I close the bug now, @ChameleonRed feel free to re-open it if needed.

**Comment by cmaliwal** [comment]
I am also getting same error in my window 8 .
I uninstalled flask_weasyprint and again installed but isuue not resolved.

**Comment by liZe** [comment]
@cmaliwal Reinstalling flask_weasyprint is not enough. You can uninstall and reinstall Python and GTK carefully following [the steps described in the documentation](http://weasyprint.readthedocs.io/en/latest/install.html#windows).

**Comment by akash1551** [comment]
@ChameleonRed This might help you,

sudo apt-get install libcairo2 libpango1.0-0
