### ISSUE TITLE
Installation on Alpine Linux

### ISSUE THREAD

**Issue by mjsisley** [Kozea/WeasyPrint#336]
It would be awesome if installation for WeasyPrint on an Alpine Linux platform was included in the docs. 

I would like to use weasyprint in a python:3.5-alpine docker container, but am having trouble finding packages for cairocffi that works.

Or is it currently immpossible to use WeasyPrint on Alpine with python3?

**Comment by SimonSapin** [comment]
It’s probably not impossible, but so far nobody who uses Alpine has told us how :)

**Comment by mjsisley** [comment]
Thanks. I suppose I meant are the needed dependencies not built with musl c yet (which doesn't mean it is impossible, but is time prohibitive for me)?

I'm just reverting to a Debian Docker container for now, but hopefully someone comes around sometime because the alpine containers are quite a bit smaller!

**Comment by mjsisley** [comment]
It looks as if it depends on Python 2, so no support for Python 3?

**Comment by liZe** [comment]
> It looks as if it depends on Python 2, so no support for Python 3?

Yes, it depends on Python 2. You should ask the creator of the Alpine package to update its package, he's probably your man! Or you can even try to update the [build script](http://git.alpinelinux.org/cgit/aports/tree/testing/py-weasyprint/APKBUILD) yourself. I don't know Alpine packages but it seems to be pretty easy to update this kind of scripts and then generate updated packages.

I'm closing this ticket as sadly we can't do anything more :cry:.

**Comment by tamhv** [comment]
hi guys, thanks for this awesome package,  i just want to confirm it works well (generate a simple invoice with text, table, logo,..) in my python3.5 alpine container https://github.com/gooesoft/docker-axe

**Comment by liZe** [comment]
> i just want to confirm it works well (generate a simple invoice with text, table, logo,..) in my python3.5 alpine container

Please don't give life to dead issues, you're turning them into zombies :wink:.

As it's been written above, WeasyPrint has been even packaged for Alpine, so I suppose that it works. If recent versions don't work, please ask the maintainer or update the build script yourself, it looks pretty easy.
