### ISSUE TITLE
Installation of weasyprint on OS X 10.11.4 Python 2.7.10 is not working

### ISSUE THREAD

**Issue by prof-schacht** [Kozea/WeasyPrint#338]
Hello Guys,

I followed the installation guide with the following commands:
`brew install python cairo pango gdk-pixbuf libxml2 libxslt libffi`

No issues after this command

`sudo pip install weasyprint`

No issues after this command

But when I try to import weasyprint in python script or try to call weasyprint --help in terminal I get the following error. 

```
 Traceback (most recent call last):
  File "/usr/local/bin/weasyprint", line 7, in <module>
    from weasyprint.__main__ import main
  File "/Library/Python/2.7/site-packages/weasyprint/__init__.py", line 19, in <module>
    import html5lib  # nova
  File "/Library/Python/2.7/site-packages/html5lib/__init__.py", line 16, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/Library/Python/2.7/site-packages/html5lib/html5parser.py", line 2, in <module>
    from six import with_metaclass, viewkeys, PY3
ImportError: cannot import name view keys
```

Did somebody have an idea how to solve this?

BR

**Comment by liZe** [comment]
According to [this report](https://review.openstack.org/gitweb?p=openstack/swift.git;a=commitdiff;h=c6ef2ab015a2c3bf0349f4b63f261f29dbfb75a5), you have an old version of six. You can try to update six with `pip install -U six`.

**Comment by liZe** [comment]
@prof-schacht Feel free to reopen if there's something new.

**Comment by 4fung** [comment]
my six is already up-to-date (1.10.0) but still have the error of importing:
"ImportError: cannot import name view keys"

**Comment by liZe** [comment]
I'm pretty sure that there are two versions of six installed on your system. Python on OSX is hell (I don't want to be rude).

You can try to launch Python and see if `from six import viewkeys` work:
- If it does, then there's something wrong with your Python installation, and the easiest (and dirtiest) way to know what's going on is to add `import six; six.__file__` in `/Library/Python/2.7/site-packages/html5lib/html5parser.py` a line before `from six import with_metaclass, viewkeys, PY3`.
- If it doesn't, then there's definitely another old version of six installed on your system (you can check where it is with `import six; six.__file__`).

**Comment by 4fung** [comment]
Thanks. I use OSX and had already amended the path of six.py to pip's folder /Library/Python/2.7/site-packages beforehand. But that doesn't fix the issue.

After searching the web around, I fix it by upgrading html5lib to 1.0b8.

**Comment by madelinezec** [comment]
I have six==1.10.0 and get this error. Deprecating my html5lib from 0.999999999 to 1.0b8, I get the same error.

**Comment by liZe** [comment]
@madelinezec I can't say anything else than my latest comment. You can read [this question on StackOverflow](http://stackoverflow.com/questions/39658404/python-cannot-import-name-viewkeys).
