### ISSUE TITLE
text in PDF is corrupted

### ISSUE THREAD

**Issue by truhlik** [Kozea/WeasyPrint#341]
Hi guys,

I can't figure out why the text in my PDF documents generated by WeasyPrint is corrupted.
See attached screenshots of PDF file and HTML document - the large text area. First, fourth and fifth line is truncated. 
It must some kind of wring computer settings, because my development machine is not affected by this issue. Only server is.

![generated_pdf](https://cloud.githubusercontent.com/assets/15262443/17526222/a693314c-5e66-11e6-99a1-e15f1227b470.png)
![template](https://cloud.githubusercontent.com/assets/15262443/17526223/a6aaef44-5e66-11e6-9bff-7caa7ed3f32d.png)
[generated.pdf](https://github.com/Kozea/WeasyPrint/files/409546/generated.pdf)

**Comment by liZe** [comment]
It's probably a duplicate of #233, #275 and #320. The solution is to use Cairo >= 1.14.2.

**Comment by truhlik** [comment]
Thank you, it fixed the problem.
Debian stable has Cairo==1.14.0, so the package must be upgraded from testing repository.
