### ISSUE TITLE
Replace cairo

### ISSUE THREAD

**Issue by oz123** [Kozea/WeasyPrint#342]
I know it's a bit ambitious... but cairo does more than PDF, and that what makes it so complex and awesome. Maybe for WeasyPrint a small specialized library is enough?

https://github.com/rk700/PyMuPDF

**Comment by liZe** [comment]
This library looks cool, but it seems to be a PDF reader, not a PDF writer :smile:.

It could be useful to solve #52 but it's released under GPL just like Poppler.

**Comment by oz123** [comment]
You can definitely write PDF with MuPDF. Just the Python Binding wraps only the view functions.

**Comment by oz123** [comment]
There is also https://github.com/pmaupin/pdfrw which is pure Python. The author says the following:

> pdfrw will faithfully reproduce vector formats without rasterization, so the rst2pdf package has used pdfrw for PDF and SVG images by default since March 2010.

**Comment by oz123** [comment]
One more interesting option which I could suggest is to reap off the `matplotlib.backend_pdf` for using as the basic canvas. 
The code is really neat to look at, and I have been fooling around with to create A4 pages with text on them. 

I am willing to collaborate on this too. 

as a side note, I took over the maintenance of rst2pdf, which share a lot of functionality through xhtml2pdf with weasyprint, css parsing and other stuff for sure. Maybe some things can be joint projects.

**Comment by stuaxo** [comment]
Changing itself cairo to split up it's backends could be fruitful (so you could install cairo, but only the pdf backend).

As mentioned in the #841 you then have Pango with its dependencies, and may want to do something similar there.

**Comment by liZe** [comment]
A lot of work has been done in the `pydyf` branch to remove Cairo, we’ll discuss this topic in #1232!

**Comment by liZe** [comment]
It’s done!
