### ISSUE TITLE
I can't show images in my pdf

### ISSUE THREAD

**Issue by eduardocalil** [Kozea/WeasyPrint#347]
I'm using weasyprint to generate PDFs in my Django App. It is working well, but when I try to show an image in my pdf, an error appears. 

I've written this in my .html :  <img src="{% static 'images/logo_seguranca.png' %}"

And in terminal, it appears: Failed to load image at http://localhost:8000/static/images/logo_seguranca.png

Thanks for your help.

**Comment by liZe** [comment]
With web apps, you have to check that:
- you don't use authentication (otherwise you'll have to use something like django-weasyprint),
- you don't have only one thread/process (because your app can't handle the second request while generating the PDF in the first one).

**Comment by eduardocalil** [comment]
I have to use authentication in this view, only the superuser can generate this pdf. Have you ever user django-weasyprint? Is it reliable? Because its repository seems abandoned.

**Comment by eduardocalil** [comment]
I've got it ! I've just removed url_fetcher from weasyprint.HTML. Thanks.
