### ISSUE TITLE
pip install fails due to missing cffi reference

### ISSUE THREAD

**Issue by rcarmo** [Kozea/WeasyPrint#348]
I get this error when trying to install `weasyprint` on both Mac OS X and Ubuntu 16.04:
```
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.1.0')
```

Easily fixed by installing `cffi`separately, but fixable in `requirements.txt`

**Comment by liZe** [comment]
I've reported this bug in SimonSapin/cairocffi#89.
