### ISSUE TITLE
parse() got an unexpected keyword argument 'override_encoding'

### ISSUE THREAD

**Issue by MaxBear** [Kozea/WeasyPrint#353]
When I follow tutorial and run 
weasyprint http://weasyprint.org /tmp/weasyprint-website.pdf

I got following error: 
TypeError: parse() got an unexpected keyword argument 'override_encoding'

Has anyone else run into the same error ? The version I installed is WeasyPrint-0.31

**Comment by liZe** [comment]
Strange, it looks like your html5lib is not up to date. You should update it (something like `pip install --upgrade html5lib`).

How did you install WeasyPrint? Using `pip` as described in the documentation should have installed a recent version of html5lib.

Related to #334.

**Comment by iainctduncan** [comment]
I'm getting the same error on CentOS and have just upgraded html5lib.

`Traceback (most recent call last):
  File "/home/s4/iain/ARRP/env/bin/weasyprint", line 11, in <module>
    load_entry_point('WeasyPrint==0.31', 'console_scripts', 'weasyprint')()
  File "/home/s4/iain/ARRP/env/lib/python2.7/site-packages/weasyprint/__main__.py", line 155, in main
    media_type=args.media_type)
  File "/home/s4/iain/ARRP/env/lib/python2.7/site-packages/weasyprint/__init__.py", line 94, in __init__
    namespaceHTMLElements=False)
TypeError: parse() got an unexpected keyword argument 'override_encoding'`

**Comment by liZe** [comment]
@iainctduncan

> have just upgraded html5lib to 1.05b8

You mean 1.0b8, right?

WeasyPrint 0.31 needs at least html5lib-1.0b9, aka html5lib-0.999999999. Please update html5lib to the latest release.

**Comment by iainctduncan** [comment]
thanks, that got it to run!

**Comment by liZe** [comment]
@MaxBear Is this problem fixed for you too?

**Comment by Kunal31** [comment]
I was facing same problem so i upgraded html5lib as suggested.
I have following packages installed in system.

html5lib==1.0b10
WeasyPrint==0.31

I am now getting following error:
cannot import name inputstream

to be specific, Its coming line no 17 of xhtml2pdf/parser.py
xhtml2pdf version is 0.0.6.

up until now i was having htmllib==1.0b8
i used to add '**kwargs' in line 25 of html5lib/html5parser.py

i am asking this because I dont want to change any library code.
what can be done now?

**Comment by liZe** [comment]
> to be specific, Its coming line no 17 of xhtml2pdf/parser.py

@Kunal31 xhtml2pdf depends on html5lib < 1.0b9 and WeasyPrint depends on html5lib >= 1.0b9, so you can:
- use independant virtual environment for WeasyPrint and xhtml2pdf,
- use an older version of WeasyPrint,
- don't use xhtml2pdf anymore as it's [officially dead](https://github.com/xhtml2pdf/xhtml2pdf).

**Comment by liZe** [comment]
I'm closing this ticket as there's no real problem with WeasyPrint. If anyone is having problems with other libraries that are not compatible with html5lib-1.0b9+, please fill a bug in the project's bug tracker.

**Comment by henrysky** [comment]
I am also suffering from this issue.

`pip install tensorflow` will break pip by installing an outdated version of `html5lib`
You can resolve the issue temporarily by installing a newer version of `html5lib` wheel downloaded to your computer locally

But updating a newer version of `html5lib `will break `tensorboard`

> (C:\Users\Henry\Anaconda3) C:\Users\Henry\Documents>tensorboard
> Traceback (most recent call last):
>   File "c:\users\henry\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\henry\anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Henry\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
>   File "c:\users\henry\anaconda3\lib\site-packages\tensorboard\main.py", line 36, in <module>
>     from tensorboard.plugins.audio import audio_plugin
>   File "c:\users\henry\anaconda3\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 27, in <module>
>     from tensorboard import plugin_util
>   File "c:\users\henry\anaconda3\lib\site-packages\tensorboard\plugin_util.py", line 21, in <module>
>     import bleach
>   File "c:\users\henry\anaconda3\lib\site-packages\bleach\__init__.py", line 14, in <module>
>     from html5lib.sanitizer import HTMLSanitizer
> ModuleNotFoundError: No module named 'html5lib.sanitizer'
