### ISSUE TITLE
Bootstrap glyphicons are not displayed properly

### ISSUE THREAD

**Issue by andrius-senulis** [Kozea/WeasyPrint#356]
Hi,

I want to use the Bootstrap glyphicons in the HTML template that I write to PDF. However, the icons are not displayed properly.

For example, this icon:
![star](https://cloud.githubusercontent.com/assets/1100012/18384467/f106f38a-768a-11e6-8434-237d8ad3fcfa.png)
is displayed like this:
![arrow](https://cloud.githubusercontent.com/assets/1100012/18384468/f10a1164-768a-11e6-98f1-7e1fa0a58db5.png)

I am including the bootstrap CSS stylesheet when generating the PDF. In the static files, the `fonts` folder location is in `../fonts/` relative to the `bootstrap.min.css` file.

Does anyone know why this might be happening?

Cheers,
Andrius

**Comment by andrius-senulis** [comment]
Solved it myself. The font "Glyphicons Halflings" should be installed. It was enough for me to copy the file `bootstrap/fonts/glyphicons-halflings-regular.ttf` to the folder `~/.fonts/`, but it can also be installed system-wide.

Reference:
http://askubuntu.com/questions/3697/how-do-i-install-fonts

**Comment by liZe** [comment]
Good to know :)
