### ISSUE TITLE
Splitting table between pages

### ISSUE THREAD

**Issue by eltadziko** [Kozea/WeasyPrint#358]
1. Is it possible to split row in table between pages in pdf?
2. When row is very long, it hides below the page instead goes to next page.
[report(1).pdf](https://github.com/Kozea/WeasyPrint/files/474930/report.1.pdf)

**Comment by liZe** [comment]
Thanks for reporting!

> Is it possible to split row in table between pages in pdf?

Unfortunately no…

> When row is very long, it hides below the page instead goes to next page.

… and that's exactly the problem :sad:. This ticket is already reported in #96.
