### ISSUE TITLE
[text coding error] Adobe  acrobat reader DC

### ISSUE THREAD

**Issue by smileboywtu** [Kozea/WeasyPrint#361]
when printing chinese code and the pdf file text coding is ok when use foxit or chrom to open it, but get encoding bug when open with acrobat reader dc.
![test1](https://cloud.githubusercontent.com/assets/12299551/18871226/0a08b340-84e7-11e6-927c-e6f382127396.png)

**Comment by liZe** [comment]
If you only get errors with Adobe Reader, then it's probably a bug in Adobe Reader :wink:. Do you only have the bug in bookmarks?

**Comment by smileboywtu** [comment]
yes

**Comment by smileboywtu** [comment]
if it's possible the font error?

 pre{ font-family: "微软雅黑", "Arial", "宋体";}

**Comment by liZe** [comment]
> if it's possible the font error?

The font used in bookmarks is not at all related to the font used in the PDF, this problem is probably not related to CSS.

Do you only have the problem with one single character?

**Comment by smileboywtu** [comment]
only find one

**Comment by liZe** [comment]
> only find one

Then I suppose that it's a bug in the font used by Reader to display the bookmarks. The shape of this character may be wrong directly in the font.

Just to be sure, you can try to generate another PDF with the same character in the bookmarks with another software, and check that the character is badly drawn as well.

**Comment by liZe** [comment]
@smileboywtu Did you find the time to try with another PDF?

**Comment by smileboywtu** [comment]
@liZe I have try with wkhtmltopdf, but i show the font really good
![test4](https://cloud.githubusercontent.com/assets/12299551/19209747/2436f51e-8d44-11e6-8e0c-7d822391a51d.png)

**Comment by smileboywtu** [comment]
@liZe  same problem with wkhtmltopdf tools with adobe dc
![test4](https://cloud.githubusercontent.com/assets/12299551/19209796/c76b7caa-8d44-11e6-855d-fe4615360875.png)

**Comment by liZe** [comment]
Then it's sure that the bug is in the font used by Adobe to display bookmarks, and the only solution is to contact Adobe to make them fix the font. Thanks for your time!
