### ISSUE TITLE
Text with font-family font is not visible

### ISSUE THREAD

**Issue by z0rr0** [Kozea/WeasyPrint#366]
Hi,

I have a problem similar to #231 and #292 - installed font is not visible, but it's presented in `fc-list` and `pango-view`. Only regular font is affected, bold and italic texts are readable. The problem has randomly nature and looks like some cache issue. `fc-cache` and application restart temporary help.

Does anyone have any idea how to fix it?

**Comment by liZe** [comment]
> Does anyone have any idea how to fix it?

Looks like nobody has met this problem. #231 and #292 are different from this problem.

> The problem has randomly nature and looks like some cache issue.

You can see which font is included in the PDF when it's the wrong font, that'll give us a hint. It's for example possible to have random results from FontConfig when you have 2 different fonts installed with the same name, or when you have different aliases with the same matching pattern.

To know exactly what's going on, you can also set the FC_DEBUG environment variable to 1.

**Comment by liZe** [comment]
@z0rr0 Do you have news about this issue?

**Comment by z0rr0** [comment]
Hi @liZe 

Affected document fonts properties contain "All fonts are either standard or embedded." and three fonts names: CairoFont-0-0, CairoFont-1-0, CairoFont-2-0.

I set "FC_DEBUG=1" and see debug info with correct font file "/usr/share/fonts/msttcorefonts/Times_New_Roman.ttf". But there is no debug output if the problem appears.

How can I trace font getting/usage?

**Comment by liZe** [comment]
> How can I trace font getting/usage?

Setting other values to `FC_DEBUG` may help, you'll find some help in [the fontconfig documentation](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html). It's probably long and painful, but I don't see any other solution.

**Comment by z0rr0** [comment]
Hi,

I think, the problem is not related with WeasyPrint directly. My investigations show, the issue doesn't appear during PNG rendering (only PDF docs). I suspect, it's related with cairo library bugs.

For my case, the problem is reproducible on CentOS 6.8 (cairo 1.8.8) and not - on CentOS 7 (cairo 1.14.2). I can assume, the [patch](https://git.centos.org/blob/rpms!cairo.git/ac1da3c1d0bf20a0037d3e83746a7d86864ad86c/SOURCES!0004-font-Generate-PDFs-with-correct-font-names.patch) (font names escaping) resolves this issue. But I didn't check this, unfortunately it's hardly to do a backport patch for version 1.8.8.

I use font's alias name "times" instead "Times New Roman" and it works as a workaround.
