### ISSUE TITLE
Line height and margin applied incorrectly

### ISSUE THREAD

**Issue by matthewkogan** [Kozea/WeasyPrint#37]
```
<head>
	<style>
		.numbered {
			font-family: Verdana, Arial;
			margin-left: 9em;
		}
		.numberspan	{
			float: left;
			margin-left: -4em;
		}
	</style>
</head>
<body>
	<div class="numbered"><span class="numberspan">1.1.1.</span><span>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.</span></div>
</body>
```

Chrome renders it as:
![Chrome rendering](https://f.cloud.github.com/assets/3594657/157256/33059bc0-76bb-11e2-8571-43caf2453152.png)

WeasyPrint renders it as:
![WeasyPrint rendering](https://f.cloud.github.com/assets/3594657/157313/6d6ba4b0-76bd-11e2-9072-7ff526828872.png)

**Comment by liZe** [comment]
Is this problem fixed with the latest version of Pango?

**Comment by liZe** [comment]
@cleitner @benique @byoungb @matthewkogan is thi bug fixed with new versions of Pango?

**Comment by liZe** [comment]
Let's say it is.
