### ISSUE TITLE
Table using colgroup and col for widths

### ISSUE THREAD

**Issue by jeffgabhart** [Kozea/WeasyPrint#382]
Either a bug or something I am doing wrong.. I'm creating a 100% width table with fixed width columns, and the last column needs to take up the rest of the table width.

I end up with columns of the same size that run off the right side of the page.

```
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
</style>
<table style="width: 100%">
    <colgroup>
        <col style="width: 200px">
        <col style="width: 100px">
        <col style="width: 50px">
        <col>
    </colgroup>
    <tbody>
        <tr>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
        </tr>
        <tr>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
        </tr>
    </tbody>
</table>
```

![report](https://cloud.githubusercontent.com/assets/2814/19908656/4050a328-a052-11e6-91e5-a310bf6b4fe9.png)

**Comment by liZe** [comment]
> Either a bug or something I am doing wrong.

It was a bug and it's now fixed and tested. Thank you for this report!

**Comment by jeffgabhart** [comment]
@liZe Thanks! How close is v0.32 to release?

**Comment by liZe** [comment]
Probably in a week or two!
