### ISSUE TITLE
Images in repeated table headers are broken

### ISSUE THREAD

**Issue by naringas** [Kozea/WeasyPrint#387]
I have a table with a table header (`thead`) which contains images (as icons).
Whenever the whole `table` is longer than one page, the image inside the `thead` on the first page breaks.

page 1:
<img width="197" alt="screen shot 2016-11-10 at 2 19 49 pm" src="https://cloud.githubusercontent.com/assets/566811/20192736/ca8e8d8e-a750-11e6-8718-6a3adc9d1143.png">

page 2 (correct):
<img width="211" alt="screen shot 2016-11-10 at 2 19 55 pm" src="https://cloud.githubusercontent.com/assets/566811/20192737/ca8fc91a-a750-11e6-9b5d-8827812e0034.png">

screenshots made with the following example (adjusted so it breaks through to a second page)
```
<table>
  <thead>
  <tr>
    <td style="border: 1px solid black;"><img class="inline-logo" src="http://pas-bplans.s3.amazonaws.com/styleguide/images/compressedLogoColor.png"></td>
  </tr>
  </thead>
  <tbody>
   <!-- repeat next line until it's longer than one page -->
   <tr><td>a</td></tr>
  </tbody>
</table>
```

tested on mac os X (El capitan) with weasyprint 0.31 
also tested on git cloned weasyprint

**Comment by liZe** [comment]
I've tried to debug, but that's surprisingly hard to find the real cause of this issue. It's caused by collapsing margins for sure, but I didn't find why it only happens with images (it works fine with other contents).
