### ISSUE TITLE
print(collapsed_margin) within WeasyPrint-0.32-py3-none-any.whl

### ISSUE THREAD

**Issue by Netex** [Kozea/WeasyPrint#395]
Hi,

I've recently upgraded from 0.31 to 0.32 and started to notice some unexpected output on stdout. I was able to trace this back to a print() within layout/block.py line 593:

```python
            if adjoining_margins and isinstance(child, boxes.TableBox):
                collapsed_margin = collapse_margin(adjoining_margins)
                print(collapsed_margin)
                child.position_y += collapsed_margin
                position_y += collapsed_margin
                adjoining_margins = []
```

This line of code seems to be only part of the WeasyPrint-0.32-py3-none-any.whl and not the [WeasyPrint-0.32.tar.gz](https://pypi.python.org/packages/79/e5/bfdcaa7270b4c5cecd76e3ef350fcfec3f906eaf5c925cbfcc46a429b018/WeasyPrint-0.32.tar.gz#md5=a0bab4363ea5acceb50658ab788c87bd) on pypi. Below is the verbose pip output from my WeasyPrint-0.32 install.

>   "GET /packages/6b/4f/f48ed23b49165d92b2648fb443994af1a44d97e285a00c4c15e80c3d929e/WeasyPrint-0.32-py3-none-any.whl HTTP/1.1" 200 286038
>   Downloading WeasyPrint-0.32-py3-none-any.whl (286kB)
>   Downloading from URL https://pypi.python.org/packages/6b/4f/f48ed23b49165d92b2648fb443994af1a44d97e285a00c4c15e80c3d929e/WeasyPrint-0.32-py3-none-any.whl#md5=995ab814b4dd64f8ce6d23fe8a76a8b2 (from https://pypi.python.org/simple/weasyprint/)

I looked at the layout/block.py with the release tag of 0.32 but it's not part of it.

**Comment by liZe** [comment]
My bad, sorry, I shouldn't play with wheels to fix bugs after the release. No wheel for 0.32.
