### ISSUE TITLE
Python has stopped working

### ISSUE THREAD

**Issue by sander76** [Kozea/WeasyPrint#400]
Win10, python3.5.

I install weasyprint using the online manual.

when doing ```weasyprint http://www.google.com c:\test.pdf``` python seems to crash. (See screenshot below)

![image](https://cloud.githubusercontent.com/assets/1688712/21045390/6e4adf34-be00-11e6-9cff-8707331afb2b.png)

**Comment by liZe** [comment]
I can't reproduce on my testing systems (Windows 7 and Windows 10, 64bit, Python 3.5). If anyone knows how to debug on Windows and/or has this problem too, that would be really helpful!

**Comment by liZe** [comment]
@sander76 Can you reproduce the bug with recent versions of Python and WeasyPrint?

**Comment by liZe** [comment]
Feel free to reopen this issue if you have more information.

**Comment by sander76** [comment]
@liZe Sorry for not checking... I'll re-open when I run into it...
