### ISSUE TITLE
Incorrect installation of fontconfig on Mac: Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by ndubbaka** [Kozea/WeasyPrint#402]
If you see this error ```Fontconfig error: Cannot load default config file```

Follow the steps at http://stackoverflow.com/questions/35249881/octave-fontconfig-error
Below steps worked for me.
```
brew uninstall fontconfig
brew install fontconfig --universal
```

Test by running ```fc-list```

**Comment by liZe** [comment]
Is it time to add the famous "Troubleshooting" section of the "Installation" chapter?

**Comment by tawanda** [comment]
worked for me, thanks :)
