### ISSUE TITLE
Displaying Checkbox Inputs

### ISSUE THREAD

**Issue by apardes** [Kozea/WeasyPrint#404]
I'm trying to display checkboxes from a form on my page. I've been playing around with custom CSS to make them visible but have had no luck. Has anyone been able to make this happen?

**Comment by liZe** [comment]
Sure!

```html
<style>
  input[type=checkbox] {
    background-clip: content-box;
    background-color: grey;
    border: 1px solid;
    border-radius: 2px;
    display: inline-block;
    height: 0.5em;
    margin: 0.5em 0.5em 0 0.5em;
    padding: 2px;
    width: 0.5em;
  }
  input[type=checkbox][checked] {
    background-color: blue;
  }
  label {
    display: block;
  }
</style>

<label><input type="checkbox" checked> checked</label>
<label><input type="checkbox"> not checked</label>
```

That's a solution with no image, but you can of course use background images to get exactly what you want!

**Comment by apardes** [comment]
@liZe Thanks, that's very helpful. I am now able to see the checkbox input but the `background-color` is not getting applied. Any ideas there?

**Comment by liZe** [comment]
Could you please provide an example of what doesn't work?

**Comment by apardes** [comment]
<img width="200" alt="screen shot 2016-12-17 at 9 53 39 pm" src="https://cloud.githubusercontent.com/assets/595297/21291165/5fca5418-c4a3-11e6-8987-c257c800a687.png">

This is a screenshot of my PDF output with your CSS implemented. In this image Option 1 is checked but option 2 and 3 are not. All of these inputs are also `disabled` but I've tried styling `[:disabled]` as well with no luck.

**Comment by liZe** [comment]
Here's what I get with my example:
![capture d ecran de 2016-12-18 12-22-11](https://cloud.githubusercontent.com/assets/952243/21293162/99042032-c51c-11e6-8a1f-e00447db546d.png)
Please write your whole HTML+CSS document so that I can help you.

**Comment by apardes** [comment]
Okay. Here is the HTML

```

		<div class="row">
			<div class="col-sm-12">

				<div class="form-group form-inline custom-options">
					<div class="input-group">
						

						<label>Option 1</label>
						<input checked="checked" id="id_option1" name="option1" type="checkbox" disabled />
					</div>

					<div class="input-group">
						

						<label>Option 2</label>
						<input checked="checked" id="id_option2" name="option2" type="checkbox" disabled />
					</div>

					<div class="input-group">
						

						<label>Option 3</label>
						<input checked="checked" id="id_option3" name="option3" type="checkbox" disabled />
					</div>
                                  </div>
                              </div>
                         </div>
```

I am loading 3 stylesheets when creating the PDF. A standard `boostrap.min.css`, `custom.css`, and `pdf.css`

`custom.css`
```
.custom-options input[type=checkbox]{
	margin-left: 5px;
	margin-right: 10px;
	margin-bottom: 5px;
}
```

`pdf.css`
```
input:before{content:attr(value)}

select:before{content:attr(value)}

label {
	display: block;
}

input[type=checkbox] {
	background-clip: content-box;
	background-color: grey;
	border: 1px solid;
	border-radius: 2px;
	display: inline-block;
	height: 0.5em;
	margin: 0.5em 0.5em 0 0.5em;
	padding: 2px;
	width: 0.5em;
}

input[type=checkbox][checked] {
	background-color: red;
}

input[type="checkbox"][:diabled][:checked] {
	background-color: red;
}
```

Thanks @liZe !

**Comment by liZe** [comment]
I've tried with this code, copy-pasted from your comment:
```html
<style>
  .custom-options input[type=checkbox]{
    margin-left: 5px;
    margin-right: 10px;
    margin-bottom: 5px;
  }
  input:before{content:attr(value)}
  select:before{content:attr(value)}
  label {
    display: block;
  }
  input[type=checkbox] {
    background-clip: content-box;
    background-color: grey;
    border: 1px solid;
    border-radius: 2px;
    display: inline-block;
    height: 0.5em;
    margin: 0.5em 0.5em 0 0.5em;
    padding: 2px;
    width: 0.5em;
  }
  input[type=checkbox][checked] {
    background-color: red;
  }
</style>

<div class="row">
  <div class="col-sm-12">
        <div class="form-group form-inline custom-options">
          <div class="input-group">
                <label>Option 1</label>
                <input checked="checked" id="id_option1" name="option1" type="checkbox" disabled />
          </div>
          <div class="input-group">
                <label>Option 2</label>
                <input checked="checked" id="id_option2" name="option2" type="checkbox" disabled />
          </div>
          <div class="input-group">
                <label>Option 3</label>
                <input checked="checked" id="id_option3" name="option3" type="checkbox" disabled />
          </div>
    </div>
  </div>
</div>
```
I get this:
![capture d ecran de 2016-12-18 15-38-53](https://cloud.githubusercontent.com/assets/952243/21294377/28eaccc8-c53b-11e6-9269-5183d97aecae.png)
Looks good to me!
(I've removed `input[type="checkbox"][:diabled][:checked]` that doesn't exist.)

**Comment by apardes** [comment]
@liZe That is the resulting PDF? I continue to get the same empty boxes with no background color.

**Comment by apardes** [comment]
@liZe It seems the cause is `boostrap.min.css` but removing it creates a range of new layout issues. Trying to override the bootstrap checkbox styling now.

**Comment by liZe** [comment]
Yes, it is. You can put the HTML+CSS sample in a file and render it with WP, it should work for you too.

If this example works but your page doesn't, then the problem comes from somewhere else (maybe some CSS rule in bootstrap).
