### ISSUE TITLE
Table breaks into different page.

### ISSUE THREAD

**Issue by l0o0** [Kozea/WeasyPrint#413]
I am trying to convert a html with many tables to pdf.  If the table is at the end of page, it will be broken into different page. Is there any way to keep the table complete. when there is not enough space for the table, we can move the whole table to the next page instead of break it.

**Comment by liZe** [comment]
> Is there any way to keep the table complete

Yes!

You can use `page-break-inside: avoid` (as defined in [CSS 2.1](https://www.w3.org/TR/CSS2/page.html#page-break-props)) or `break-inside: avoid` (as defined in [CSS Fragmentation](https://drafts.csswg.org/css-break-3/#break-within)), they're both implemented. And it's not restricted to tables :wink:.

**Comment by kylegibson** [comment]
I'm having the opposite issue. The table is being moved to the next page, but I don't want that. I want the table split across pages. Additionally, it seems if the table's content is too large to fit on a single page, the overflow disappears. 
[doc.html.txt](https://github.com/Kozea/WeasyPrint/files/733508/doc.html.txt)

**Comment by liZe** [comment]
> I'm having the opposite issue.

Yes, WeasyPrint doesn't split cells between pages, that's reported in #96.

@l0o0 Is the issue fixed for you?

**Comment by l0o0** [comment]
@liZe Sorry for the late reply. I will do the test after the Spring Festival.

**Comment by l0o0** [comment]
I use the html below to test. It works fine. Thank you.
```html
<table style="break-inside:avoid-page"><caption>Test</caption><tbody><tr><th>Ac</th><th>Bc</th></tr><tr><td>A1</td><td>B1</td></tr><tr><td>A2</td><td>B2</td></tr><tr><td>A3</td><td>B3</td></tr><tr><td>A4</td><td>B4</td></tr></tbody></table>
<table style="break-inside:avoid-page"><caption>Test</caption><tbody><tr><th>Ac</th><th>Bc</th></tr><tr><td>A1</td><td>B1</td></tr><tr><td>A2</td><td>B2</td></tr><tr><td>A3</td><td>B3</td></tr><tr><td>A4</td><td>B4</td></tr></tbody></table>
<table style="break-inside:avoid-page"><caption>Test</caption><tbody><tr><th>Ac</th><th>Bc</th></tr><tr><td>A1</td><td>B1</td></tr><tr><td>A2</td><td>B2</td></tr><tr><td>A3</td><td>B3</td></tr><tr><td>A4</td><td>B4</td></tr></tbody></table>
<table style="break-inside:avoid-page"><caption>Test</caption><tbody><tr><th>Ac</th><th>Bc</th></tr><tr><td>A1</td><td>B1</td></tr><tr><td>A2</td><td>B2</td></tr><tr><td>A3</td><td>B3</td></tr><tr><td>A4</td><td>B4</td></tr></tbody></table>

**Comment by liZe** [comment]
:smile:!

**Comment by NailaAkbar00** [comment]
@liZe - @l0o0  I want to split my table on multiple pages but page-break-inside not working.. Is there any other solution for this? I'm using weasyprint.

**Comment by liZe** [comment]
Tables are broken between lines, but are currently not broken inside lines. There are other kind of properties that prevent page breaks, please see #36. If your problem is not related to #36, please open a new issue instead of turning closed issues into zombies :wink:.
