### ISSUE TITLE
AssertionError, Got u'Y' between two lines. Expected nothing or a preserved line break

### ISSUE THREAD

**Issue by lrodorigo** [Kozea/WeasyPrint#418]
[similar to https://github.com/Kozea/WeasyPrint/issues/313]
**Assertion Error**
```
Exception Value:	
Got u'Y' between two lines. Expected nothing or a preserved line break
Exception Location:
/usr/local/lib/python2.7/site-packages/weasyprint/layout/inlines.py in split_text_box, line 718
```

Hi all,
I get the above error when I try to output in pdf this file [http://pcb.dev.nextechs.it/test_weasy.html](http://pcb.dev.nextechs.it/test_weasy.html) on my production server.
`WeasyPrint==0.34

It's running on Debian Jessie (inside a Docker container). I also tried to update `libpango-1.0.0` from `1.36.8-3` (on default Debian Jessie branch)  to `1.40.3-3` (using Debian Stretch branch)

I don't have problems on my ArchLinux (with same WeasyPrint and libpango versions).

I temporally "brutally workarounded" the issue by replacing with `assert True or` the above line. But I would like a clean solution.

Which others libraries should I check and compare versions?

Best Regards
Luigi Rodorigo

**Comment by liZe** [comment]
Thanks for reporting, this issue is just like #417 too :smile:.

I think that it's been fixed by #410, could you please try the current master branch?

**Comment by lrodorigo** [comment]
Fixed on master branch (git pull and setup.py install).
Can you forecast when updated pip package will be released?
Regards

**Comment by liZe** [comment]
No problem!
