### ISSUE TITLE
Links do not render in PDF.

### ISSUE THREAD

**Issue by migrome** [Kozea/WeasyPrint#42]
```
from weasyprint import HTML
HTML(string='<a href="http://google.com">link</a>').write_pdf('tmp.pdf')
```

Makes non-clickable links in PDF

**Comment by EugeneKovalev** [comment]
@SimonSapin the same thing appeared.

0.42.* works great but 44 (the last version at the moment) does not render clickable links in PDF

**Comment by Tontyna** [comment]
@EugeneKovalev Any warnings logged? What's your Cairo version? What's your OS?

**Comment by SimonSapin** [comment]
Sorry, I’m not actively working on WeasyPrint anymore. Consider filing a new bug with steps to reproduce, it’ll have more visibility.

**Comment by EugeneKovalev** [comment]
@Tontyna 
OS - Ubuntu 18.10
Cairo - v1.14.8

Could you please tell me how to upgrade Cairo?
I have already tried to install [the latest stable version](https://cairographics.org/releases/cairo-1.16.0.tar.xz). I ran ./configure, make, make install and it went to /usr/local/lib (seems to be OK)

But in python code when I run:
```
from cairocffi import cairo
print(cairo.cairo_version())
```
the output is 1.14.08

Any thoughts?

**Comment by Tontyna** [comment]
> Any thoughts?

Obviously the package repository isn't up-to-date. Since I dont know nothing about Ubuntu I have no idea how to get & install special versions of libraries.

**Comment by Afoucaul** [comment]
@EugeneKovalev's solution fixed `cairocffi`, but it broke Pycairo for me. I had to remove the `cairo` directory in my install, and to re-install it.

**Comment by Afoucaul** [comment]
Hi @rjdebastiani, yeah I followed @EugeneKovalev's steps which fixed cairocffi, and then I uninstalled manually pycairo and re-installed it from pip.
