### ISSUE TITLE
0.34 failing on very simple source

### ISSUE THREAD

**Issue by andreas-p** [Kozea/WeasyPrint#422]
I've installed easyprint to two debian machines, both using jessie. One of them with libpango upgraded to 1.40 from stretch, the other is the latest jessie release.
Both machines won't render the attached test.html correctly, some words are omitted.

On OSX, the rendering is ok.

[test.pdf](https://github.com/Kozea/WeasyPrint/files/754124/test.pdf)

**Comment by andreas-p** [comment]
Added test.html source; didn't upload previously.

[test.html.txt](https://github.com/Kozea/WeasyPrint/files/754125/test.html.txt)

**Comment by liZe** [comment]
It's probably a duplicate of #233, could you please try to update libcairo2? There's a bug in libcairo2-1.14.0 (the current version in jessie).

**Comment by andreas-p** [comment]
After upgrading to libcairo2 1.14.8 from stretch, the problem is gone.
Thanks for your feedback!

**Comment by andreas-p** [comment]
This warning might prevent more issue posts:
https://github.com/Kozea/WeasyPrint/pull/423
