### ISSUE TITLE
This tool can't get any picture in a website by printing

### ISSUE THREAD

**Issue by yingshaoxo** [Kozea/WeasyPrint#424]
You know what, man. When use your tool to print PDF from a URL, I get nothing but text... Why can't get picture?  This is the website: http://mp.weixin.qq.com/s?__biz=MzA3ODQ1ODM0MA==&mid=2656561038&idx=2&sn=351e3390962bd08bec7c6a58bca8d4c4&scene=19#wechat_redirect

**Comment by liZe** [comment]
The images in this page are loaded using Javascript, and WeasyPrint doesn't support Javascript. That's why, man.
