### ISSUE TITLE
Images print fine on Ubuntu, but don't work on Amazon Linux

### ISSUE THREAD

**Issue by TravisHardman** [Kozea/WeasyPrint#428]
I'm using Weasyprint to generate some PDFs that include jpg, png, and svg graphics. All the images render fine on my Ubuntu developer machine, but then only some of them render on the Amazon Linux machine.

At first, I thought the problem may just be with JPEGs so I was encoding all JPEGs in png data urls and rendering that way. But that didn't help. It seems like SVG images work fine. PNG images work fine over HTTP, but not from data urls, and only one out of about 20 JPGs works.

All of the various approaches work on the Ubuntu machine.

Thoughts?

**Comment by TravisHardman** [comment]
Okay, after playing with this a bit, it does seem to be an issue with JPG images, which work sometimes but not others. I am able to work around the problem by converting to PNG like so:

```
jpg = BytesIO(requests.get(photo_url).content)
png = BytesIO()
Image.open(jpg).save(png, format='PNG')
photo_url = 'data:image/png;base64,' + base64.b64encode(png.getvalue()).decode('utf-8')
```

I'm still curious though how to get JPEGs working on Amazon Linux. Logging is not too revealing. Looking at the source, maybe related to pixbuf?

**Comment by liZe** [comment]
> maybe related to pixbuf?

Indeed. You should get a warning (`Could not load GDK-Pixbuf. PNG and SVG are the only image formats available`).

Cairo can read PNG images and CairoSVG can handle SVG files, but other formats (including JPG) need GDK-Pixbuf. If it's already installed, I suppose that one of its optional (libjpeg-turbo, I think) needs to be installed too.

**Comment by TravisHardman** [comment]
I messed around with installing GDK-Pixbuf on Amazon Linux for a while there. Seems to be available through apt-get on Ubuntu, but I don't believe it's available at all through yum.

I got stuck on dependencies trying to install it manually, so I'll probably just stick with my PNG conversion work-around.

This thread might just end up being a feature request to remove the dependency on GDK-Pixbuf for rendering JPGs. Since it's not readily available across different versions of linux, it seems that it can get a bit hairy.

**Comment by liZe** [comment]
This article may help: https://joekiller.com/2012/06/03/install-firefox-on-amazon-linux-x86_64-compiling-gtk/. libjpeg-devel is installed with yum, GDK-Pixbuf is compiled from source.

> This thread might just end up being a feature request to remove the dependency on GDK-Pixbuf for rendering JPGs. Since it's not readily available across different versions of linux, it seems that it can get a bit hairy.

GDK-Pixbuf has been split from GDK/GTK+ in order to be easy to compile and install, even on servers without X. I'm not sure that many Linux distributions miss this package :wink:, it's maybe easier to ask Amazon to add this package (or to compile it yourself, looks pretty easy).

**Comment by liZe** [comment]
@TravisHardman Is this problem solved for you?

**Comment by y0rd4nis** [comment]
I'm generating PDF files using AWS Lambda function, Python and WeasyPrint, at first gif images wasn't printed:

> PNG and SVG are the only image formats available.

 I tried @TravisHardman [solution](https://github.com/Kozea/WeasyPrint/issues/428#issuecomment-278444750) but isn't working, I'm getting this error when returning the png base64 image in the response 'string' key:

> GdkPixbufLoader finalized without calling gdk_pixbuf_loader_close() - this is not allowed. You must explicitly and the data stream to the loader before dropping the last reference.

I tried returning the **png** object itself in the response 'file_obj' key and setting response 'mime_type' key to 'image/png' but isn't working, I'm getting this error:

> Pixbuf error: Unrecognized image file format

Even if I return a fixed png base64 formatted I got the previous error. I uploaded a png image to [https://www.base64-image.de/](https://www.base64-image.de/).

I got gif images working by converting it manually to png, uploading it with my lambda source code, asking if the image to be resolved is one of my gif images and:

1. opening the corresponding png image file and return a File-like object in the 'file_obj' key or reading the opened File-like object and returning its content in the 'string' key.

or

2. overwriting the original URL to a local file URL (file://) pointing to my local png image and passing that local URL to default_url_resolver

I don't want to convert every gif image to png manually neither uploading it as part of my lambda function, any ideas why am I getting the errors I mentioned above?

**Comment by liZe** [comment]
@TravisHardman @y0rd4nis Did you find a solution to get WeasyPrint handle images correctly on AWS Lambda? It would be great to have a nice documentation :wink:.

**Comment by deepak-ace12** [comment]
Hi @TravisHardman Could you please tell me how the images are working on Ubuntu...For me, It's working well on mac but it's not working on Ubuntu 14.04

**Comment by liZe** [comment]
Feel free to reopen if needed.

**Comment by igventurelli** [comment]
Not sure if this can be helpful, but I just faced a similar problem with .png images and .css files.
I just force the copy of my assets to `/tmp` folder with:
`from distutils.dir_util import copy_tree`
`copy_tree('img', '/tmp/img')`
`copy_tree('css', '/tmp/css')`
And that's it
