### ISSUE TITLE
Why would in-line use not work.....

### ISSUE THREAD

**Issue by eszekeres** [Kozea/WeasyPrint#429]
I can successfully create a valid PDF file outputting to file, but I would like to output directly to browser, why would this not work (I can't seem to get a valid output, though the data in the file looks same), I just get a "PDF Document might not be display correctly." error in the browser PDF plug in:

```perl
my $test = qq[<head><title>Default Message</title></head><body><hr size=1px><table width=100% border=0><tr><td align=center><font color=red><h4>No HTML input defined!<h4></font></td></tr></table></body>];
print "Content-type: application/pdf\r\n\r\n";
my $FH;
open($FH,"| weasyprint --format pdf - - 2>/dev/null");
print $FH $test;
close($FH);
```

**Comment by liZe** [comment]
I don't get it. Do you use a web server written in perl?

**Comment by liZe** [comment]
@eszekeres ?

**Comment by eszekeres** [comment]
Yes, believe it or not PERL still can be quite an effective tool :-). Not withstanding the choice of the infrastructure I am still not clear on why piping output to a file yields a PDF that is usable but piping PDF to the browser does not work.  I was also testing Prince and it works in the same code sample, but I was looking for an alternative.

**Comment by liZe** [comment]
I'm no piping guru, so here's my stupid question: how do you pipe some content to a browser? I've found [this](http://unix.stackexchange.com/questions/24931/how-to-make-firefox-read-stdin) but it doesn't work for me, even with cat.

**Comment by eszekeres** [comment]
I am not sure I understand your question, that is the function of a webserver, basically sending data to a browser via STDOUT (a pipe), typically you have to provide a MIME type header line so the browser understands how the data should be handled….from a CGI script you just do print

**Comment by liZe** [comment]
> I am not sure I understand your question, that is the function of a webserver

I'm stupid, I had already forgotten my own question, sorry.

I've tried your script and it works for me: The PDF is open correctly by both Firefox and Chrome. I've used the default CGI server included in Python (`python3 -m http.server --bind localhost --cgi 8000`) and just added the shebang to your file.

**Comment by liZe** [comment]
@eszekeres Did you solve this problem?

**Comment by eszekeres** [comment]
In a way we did, we ended up just licensing Prince which works fine in-line…

**Comment by liZe** [comment]
> In a way we did, we ended up just licensing Prince which works fine in-line…

Well, that's a way to solve this problem :smile:.

Just for the record: the perl script was working for me behind the CGI server built in Python, I really don't know why you got this problem. If anyone finds a reason…

**Comment by eszekeres** [comment]
I would have preferred the no-cost option, but with so many other issues I am dealing with I just did not have time to do deep debugging, maybe I will come back to this someday in the future…
