### ISSUE TITLE
Set absolute path for hyperlinks

### ISSUE THREAD

**Issue by l0o0** [Kozea/WeasyPrint#437]
Is there any way to set absolute path for hyperlinks for weasyprint?
I try to use `HTML(string='<a href="html/images/poisson_chs.png">This is a link</a>', base_url='.').write_pdf('tmp.pdf')`, but the pdf is automatically changed to a absolute path. Even I set `base_url` in `weasyprint.HTML`.  
Is it any way to keep the relative path in the html code?

**Comment by liZe** [comment]
Thanks for the good idea! It's now possible, without `base_url` (`base_url` is being transformed to an absolute path, it's an useful feature).

**Comment by l0o0** [comment]
Is possible in the new version of weasyprint?  I thinks it's quite useful for setting absolute path in the pdf when I copy the folder with pictures or other resources to another's machine.

**Comment by liZe** [comment]
> Is possible in the new version of weasyprint?

Yes, it is (with the current git version).
