### ISSUE TITLE
display issue: cut off text on right with embedded svgs

### ISSUE THREAD

**Issue by lutostag** [Kozea/WeasyPrint#438]
Rendering http://pastebin.com/VnFjqJeg the bottom right text isnt displayed. https://imgur.com/a/xFpid is the example render.

For the non-base64 encoded svg cairosvg renders it as expected with the text.

http://pastebin.com/RavWhMrp is pip freeze

**Comment by liZe** [comment]
Thank you for reporting this issue!

It's a duplicate of #278. TL;DR: it's a bug in Cairo fixed in the ustable 1.15.4 version.
