### ISSUE TITLE
Unable to control width and height of an SVG in the PDF

### ISSUE THREAD

**Issue by plahoti** [Kozea/WeasyPrint#442]
I'm trying to link an SVG image into an HTML and converting this HTML into PDF using WeasyPrint. However, I'm unable to control the 'width' and 'height' attributes of the 'img' tag.

Sample code:

```
report_gen.py
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML

env = Environment(loader=FileSystemLoader('.'))
template = env.get_template("template.html")
html_out = template.render()
HTML(string=html_out).write_pdf("report.pdf")
```

template.html
```
<!DOCTYPE html>
<html>
<head lang="en"><meta charset="UTF-8"></head>
<body>
  <img width=800px height=600px src="file://chart.svg" />
</body>
</html>

```
The PDF output has an SVG embedded into it whose width and height are not configurable.

**Comment by plahoti** [comment]
A couple of observations:
1. If the SVG has width and height defined in it, the width and height as specified in the HTML 'img' do not take effect.
2. If the SVG does not have width and height in it, the PDF output is blank.

**Comment by liZe** [comment]
Attributes specified in the HTML tags are called [presentational hints](https://www.w3.org/TR/html51/rendering.html#the-css-user-agent-style-sheet-and-presentational-hints), they are supported in WeasyPrint if you give `presentational_hints=True` to the [`write_pdf` method](http://weasyprint.readthedocs.io/en/latest/api.html#weasyprint.HTML.write_pdf).

You can also use CSS  stylesheets or the HTML `style` attribute that are always supported.
