### ISSUE TITLE
AssertionError: Got u'Regional-' between two lines. Expected nothing or a preserved line break

### ISSUE THREAD

**Issue by nicbrown** [Kozea/WeasyPrint#449]
Hello, 

I'm experiencing a similar issue to other people I suspect. I've had a look at the code but can't quite figure out where the error lies for this problem. 

I'm using ubuntu 16.04 with version 0.36. 
When using this file:

I get this error:
    'Expected nothing or a preserved line break' % (between,))
AssertionError: Got u'Regional-' between two lines. Expected nothing or a preserved line break

Any help would be greatly appreciated. 

Nick

**Comment by liZe** [comment]
> I'm experiencing a similar issue to other people I suspect.

And as usual, I can't reproduce… :cry:

Could you please tell me which font you use? There's `Verdana` in the CSS, but even with the version of Verdana I have, it works for me. As you're on Ubuntu, I suppose that you're using an alias. If you don't know which font is used instead of Verdana, can you launch `fc-match Verdana` in a terminal?

**Comment by nicbrown** [comment]
I’m using DejaVuSans.ttf: "DejaVu Sans" "Book"

Nick Brown
Deloitte Ventures
Mobile: +44 (0)788 521 3537


IMPORTANT NOTICE

This communication is from Deloitte LLP, a limited liability partnership registered in England and Wales with registered number OC303675. Its registered office is 2, New Street Square, London EC4A 3BZ, United Kingdom. Deloitte LLP is the United Kingdom member firm of Deloitte Touche Tohmatsu Limited (“DTTL”), a UK private company limited by guarantee, whose member firms are legally separate and independent entities. Please see www.deloitte.co.uk/about<http://www.deloitte.co.uk/about> for a detailed description of the legal structure of DTTL and its member firms.

This communication contains information which is confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), please (1) notify it.security.uk@deloitte.co.uk<mailto:it.security.uk@deloitte.co.uk> by forwarding this email and delete all copies from your system and (2) note that disclosure, distribution, copying or use of this communication is strictly prohibited. Email communications cannot be guaranteed to be secure or free from error or viruses. All emails sent to or from a Deloitte UK email account are securely archived and stored by an external supplier within the European Union.

To the extent permitted by law, Deloitte LLP does not accept any liability for use of or reliance on the contents of this email by any person save by the intended recipient(s) to the extent agreed in a Deloitte LLP engagement contract.

Opinions, conclusions and other information in this email which have not been delivered by way of the business of Deloitte LLP are neither given nor endorsed by it.

**Comment by liZe** [comment]
I've tried with DejaVuSans and … it works for me.

Does it fail with the example file you're providing? It seems to be modified by hand (at least the `title` tag is broken).

**Comment by nicbrown** [comment]
Ah sorry, looks like I attached the wrong file. This one is the one that fails on my system. 

Nick
[test.html.txt](https://github.com/Kozea/WeasyPrint/files/893042/test.html.txt)

**Comment by liZe** [comment]
Yay!!!! It's broken for me too!

**Comment by liZe** [comment]
Minimum HTML:
```html
<div style="font-family: DejaVuSans; font-size: 10px; width: 131px">EU-DataTransfer-Regional-Bytes</div>
```
