### ISSUE TITLE
OSError: cannot load library gobject-2.0: dlopen(gobject-2.0, 2): image not found

### ISSUE THREAD

**Issue by jernejkase** [Kozea/WeasyPrint#450]
OS: OSX Yosemite 10.10.5
Python3.6

Install procedure:
brew install python3 cairo pango gdk-pixbuf libxml2 libxslt libffi
xcode-select --install
pip3 install weasyprint

weasyprint -- help fails with:
OSError: cannot load library gobject-2.0: dlopen(gobject-2.0, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0'

I tried to install various packages, gtk+,gtk+3,pygobject etc.. nothing helps

**Comment by liZe** [comment]
gobject-2.0 is installed with [glib](http://brewformulas.org/Glib), which is required by [cairo](http://brewformulas.org/cairo). There's probably a problem with your homebrew installation, as it works with a fresh installation of OSX (at least 10.11).

I don't really know how homebrew works, but you can probably try to reinstall glib, find where gobject-2.0 is installed and try to find why it's not found by ffi.

**Comment by liZe** [comment]
@jernejkase Did it work?

**Comment by chickendude** [comment]
Hey @liZe, i've been having this issue on Windows:
`OSError: cannot load library gobject-2.0: error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0'`

I'm not sure what (i, probably) changed, i've been using it for a while without issues, today i found it wasn't running anymore. I've got GTK3 installed and added to the PATH, i've tried reinstalling/updating it but that hasn't changed anything.
