### ISSUE TITLE
Tkinter Canvas Backend

### ISSUE THREAD

**Issue by aplicacionamedida** [Kozea/WeasyPrint#452]
Using the generated box structure very probably it's possible to render the web page on a Canvas Tkinter widget. This is an interesting feature to provide an HTML widget to Tkinter. This will also make the Cairo dependency optional.

A good idea is to abstract a little bit more the rendering process and make possible to subclass an abstract rendering class to work with other backends.

**Comment by liZe** [comment]
We could talk about this in #342.
