### ISSUE TITLE
Javascript generated content

### ISSUE THREAD

**Issue by sander76** [Kozea/WeasyPrint#454]
Not really an issue, but more a question:
Can weasyprint render javascript created content? I did search the docs, but there is no mention of it.

**Comment by liZe** [comment]
> Can weasyprint render javascript created content?

Short answer: unfortunately, no.

You'll find some interesting comments in #23 explaining how you can add some generated content using Python. That's the easiest way to do this currently.

**Comment by drukepple** [comment]
@sander76 I wanted this feature in order to run a JS syntax highlighter. Check out this SO answer: [https://stackoverflow.com/questions/12450868/how-to-print-html-source-to-console-with-phantomjs/12469284#12469284]()

As a pre-PDF step, I'm running my HTML through PhantomJS and writing the output to a new file, which now includes DOM manipulations from JS, and using _that_ to feed into WeasyPrint.

Worth noting that Prince can do this just fine by using the `--javascript` option. But Prince is ridiculously expensive, and WeasyPrint is priced just right. For which I thank you.

**Comment by Tontyna** [comment]
GitHub ruined the link to SO ... try this one:
https://stackoverflow.com/questions/12450868/how-to-print-html-source-to-console-with-phantomjs/12469284#12469284

**Comment by liZe** [comment]
As we won't include a JS engine in WeasyPrint, I close this issue. Using a preprocessing JS tool is the best solution if you want to rely on JS, otherwise editing the document with Python (or anything else) is possible too.

**Comment by luizmof** [comment]
> @sander76 I wanted this feature in order to run a JS syntax highlighter. Check out this SO answer: https://stackoverflow.com/questions/12450868/how-to-print-html-source-to-console-with-phantomjs/12469284#12469284
> 
> As a pre-PDF step, I'm running my HTML through PhantomJS and writing the output to a new file, which now includes DOM manipulations from JS, and using _that_ to feed into WeasyPrint.
> 
> Worth noting that Prince can do this just fine by using the `--javascript` option. But Prince is ridiculously expensive, and WeasyPrint is priced just right. For which I thank you.

Hi, can you show some example how you doing it? I'm trying to figure out this to implement a template with JS that render maps em graphs.

**Comment by MaximeDdnn** [comment]
> @sander76 I wanted this feature in order to run a JS syntax highlighter. Check out this SO answer: https://stackoverflow.com/questions/12450868/how-to-print-html-source-to-console-with-phantomjs/12469284#12469284
> 
> As a pre-PDF step, I'm running my HTML through PhantomJS and writing the output to a new file, which now includes DOM manipulations from JS, and using _that_ to feed into WeasyPrint.
> 
> Worth noting that Prince can do this just fine by using the `--javascript` option. But Prince is ridiculously expensive, and WeasyPrint is priced just right. For which I thank you.

@drukepple thank you for your answer ! could you please give an exemple ? what do you mean by "I'm running my HTML through PhantomJS" please ? thanks a lot !  maxime
