### ISSUE TITLE
The Webpage  will be cut off while use write_png method

### ISSUE THREAD

**Issue by wilslee** [Kozea/WeasyPrint#455]
The Webpage will be cut off while use write_png method, just like:
![qq 20170410165820](https://cloud.githubusercontent.com/assets/12045687/24853924/2f643012-1e0f-11e7-9833-d77fb77b8815.png)
For you origin url : http://weasyprint.org/

**Comment by liZe** [comment]
Even when generating PNGs, the rendering is split into pages, that's why there's an empty space. There's an open issue about dynamic page height, I think that's what you want: #193.

**Comment by wilslee** [comment]
I has set `page-break-inside: avoid` in div class for print, but still no effect, I have no idea to fix this problem

**Comment by liZe** [comment]
To fix the problem, you can set a higher page size:
```
@page {
  size: 210mm 500mm;
}
```
![weasyprint](https://cloud.githubusercontent.com/assets/952243/25085964/2dbb54c4-2365-11e7-80aa-d1169e5c9d5d.png)

**Comment by wilslee** [comment]
Thx，it can solve this problem，but if need to generate the pdf file when generating PNGs，we need to set `@page { size: A4; }`. Anyway，I think it's best that has some option or kwargs in the `write_png` method, then we can control the height space

**Comment by liZe** [comment]
Closing, as the real fix would be to have #193 implemented.
