### ISSUE TITLE
Non ascii characters replaced with numerical boxes on AWS

### ISSUE THREAD

**Issue by narenderp** [Kozea/WeasyPrint#456]
I have deployed latest code to AWS. I have installed Weasyprint too. I have provided a url for font. Everything seems to be OK but it doesn't work on AWS. I've restarted font-cache also, Although It works fine on local environment, don't exactly know what's happening.

Do I need something else to make it work on AWS?

**Comment by liZe** [comment]
Do you have some logs during the rendering?

**Comment by narenderp** [comment]
WARNING: Named pages are not supported yet, the whole @page page_landscape rule was ignored.
    [pid: 10775|app: 0|req: 7/71] 52.88.26.206 () {34 vars in 507 bytes} [Mon Apr 17 10:09:47 2017] GET 
    /media/project_fonts/DejaVuSansMono.ttf => generated 340240 bytes in 2 msecs via sendfile() 

    (HTTP/1.1 200) 5 headers in 179 bytes (1 switches on core 0)
    WARNING: Parse error at 8:17, unknown at-rule in @page context: @frame
    WARNING: Parse error at 19:17, unknown at-rule in @page context: @frame

These are the logs which I found during rendering. Although It is able to find the url path for font "DejaVuSansMono.ttf".

**Comment by narenderp** [comment]
Do you have any idea regarding it?

**Comment by liZe** [comment]
2 months with no answer, sorry… :disappointed:

I've no idea. You can try other fonts and see if it fixes your problem. You can also try to install fonts on the system and try to use them instead of external fonts.

Could you please attach the generated PDF and the HTML source?

**Comment by liZe** [comment]
@narenderp Did you try anything else to solve this issue?

**Comment by liZe** [comment]
If someone's got the same problem, feel free to reopen.
