### ISSUE TITLE
doupt about ffi dependency on debian 8 

### ISSUE THREAD

**Issue by CorentinBrule** [Kozea/WeasyPrint#461]
The documentation says we should install `python-cffi` for Debian 8. 
But I had to install `libffi-dev`, the way for debian 7.

```
Debian Gnu/Linux 8 
Distributor ID:	BunsenLabs
Description:	BunsenLabs GNU/Linux 8.7 (Hydrogen)
Release:	8.7
Codename:	bunsen-hydrogen
```

**Comment by CorentinBrule** [comment]
sorry I think is the same problem on [#458](https://github.com/Kozea/WeasyPrint/issues/458)

**Comment by liZe** [comment]
Indeed, I have to fix this.
