### ISSUE TITLE
Using weasyprint.css in other projects

### ISSUE THREAD

**Issue by jnothman** [Kozea/WeasyPrint#468]
Hi, I recently implemented a portion of CSS declaration expansion and computation for the Pandas data wrangling library, in order to export CSS-styled tables to Excel (and perhaps LaTeX and other formats in the future). There, cells are individually marked with `style` attributes.

Now seeing how feature complete `weasyprint.css` is in this task, I would rather rely on its implementation. I would rather a more lightweight version that doesn't involve importing all of `weasyprint` if possible. It seems to me that all that is required for those purposes is `preprocess_declarations`, `computed_from_cascaded`, `StyleDict` and their dependents.

These are not currently considered reliable public API according to the weasyprint docs. (Perhaps this is not surprising given the custom representations used in the result of `computed_from_cascaded`.) And I'd be tempted to pull them into a separate library.

Do the maintainers of weasyprint have any opinion on how this should best be done?

**Comment by jnothman** [comment]
I've now realised that already this assumes the code in master. When is a release using tinycss2 expected?

**Comment by liZe** [comment]
Hello @jnothman,

> These are not currently considered reliable public API according to the weasyprint docs.

It's true, even if it didn't change that much during the last years.

> And I'd be tempted to pull them into a separate library.

It's possible. The hardest part is creating a clean API if you really want to create a library that could be used for other cases than your own or for WeasyPrint. And of course packaging, maintaining, managing a community, etc. :smile:

> Do the maintainers of weasyprint have any opinion on how this should best be done?

If you want to keep the code for your use case and don't want to spend much time with it, **you'd better copy the code from WeasyPrint, clean and adapt it for your needs, and let it as a module in your project**. The other solution is to keep WeasyPrint, hope that the API won't change and get the bugfixes and new features for free (I know, relying on Cairo and Pango is painful).

If you're really interested in creating a library, I'm available to talk and give some advice, but the extra work it will add in the future is bigger than it seems to be now. Creating a good API is hard, updating and maintaining it is even harder (and not that interesting).

> I've now realised that already this assumes the code in master. When is a release using tinycss2 expected?

Soon, probably before the end of May.

**Comment by jnothman** [comment]
thanks. if I provided a stable API for parts of weasyprint.css in an
external package, would weasyprint be interested in using it instead?

**Comment by liZe** [comment]
> thanks. if I provided a stable API for parts of weasyprint.css in an
> external package, would weasyprint be interested in using it instead?

I'd be interested, as long as the API is well designed and I can make the fixes and improvements when needed :smile:.

IMHO it's not impossible, but a bit hard. `weasyprint.css.computed_values` currently relies on `text` (needing both Cairo and Pango, that's the hard part) and various parts and internal structures of WeasyPrint (for URLs, counters, gradients, etc). It will probably take some time before finding a smart way to split without getting an "artificial" API.

**Comment by jnothman** [comment]
yes I've realised compute is more coupled than i first thought

**Comment by liZe** [comment]
Is there anything more that can be done about this, before I can close this issue?

**Comment by jnothman** [comment]
I'd like to get started on it, but I've not had a chance.

**Comment by liZe** [comment]
Well, there's probably nothing easy we can do for now about this. Let's close this issue, feel free to reopen or create a pull request if there's something new.
