### ISSUE TITLE
Support page marks and bleed

### ISSUE THREAD

**Issue by deathowl** [Kozea/WeasyPrint#471]
```css
@page {
  size: 159mm 237mm;
  margin: 3mm 3mm 3mm 3mm;
  marks: crop;
}
```
WARNING: Ignored `marks: crop` at 4:5, unknown property.

**Comment by liZe** [comment]
These features should be quite easy to add, using a SVG file for crop marks and another one for crosses, and applying them to the bleed area box.

**Comment by dark-light-cz** [comment]
Hello!
I know it's nor in standard nor in any draft but can you extend support of bleedbox to be available in 4 sizes. I expect it's not problem and is only extension and does't bkeak anything functional.
Th reason is that i use weasyprint to generate pages for printer working with SRA4(225x320 mm) paper an i need bleed mark to paper A4(210mmx297mm)
I tried to extend the functionality myself but I was unable to find out how adding validators and computers works.

**Comment by liZe** [comment]
Hi @dark-light-cz!

You want `bleed` to behave like `padding`. Good news: it's not that hard :smile:.

In `validation.py`, you can add a decorator for `bleed` around `expand_four_sides` and 4 for `bleed-left/right/top/bottom` around bleed.

In `properties.py`, you can add `bleed-left/right/top/bottom` where `bleed` was added in 71d5409.

In `css/__init__.py`, you can replace `bleed` by `bleed(_(left|right|top|bottom))?` (not tested) in `RE_INITIAL_NOT_COMPUTED` (`bleed`'s initial value is `'auto'` where the calculated value depends on the value of `marks`).

You can then use a list where `bleed` is used as a single value (for example in `document.py`), and report these values when creating the bleed box (in `pdf.py`).

I think that's all! If you have any questions, you can fork and push what you've done even if it doesn't work, I'll help you to solve the problems you meet!

**Comment by dark-light-cz** [comment]
Hi @liZe 

I re-wrote your implementation of blled as you suggest in my fork in https://github.com/dark-light-cz/WeasyPrint/commit/05446f5effe3c67655551e51a74b5a97a2808aa2

If you like it I can create pull request.

Only thing I'm not sure with is changes in weasyprint/pdf.py. Can you please take a look at it and tell me whether it is right. I'm not sure why there is dividing by 2 in create of self.BleedBox and I'm not sure if there should be used left or right on x axis and top or bottom on y axis.

If you want my patch to included we propably need some tests. If so, please suggest me how to do it.

**Comment by liZe** [comment]
@dark-light-cz Sorry for the delay.

Yes, that's cool, thank you, you can create a pull request! I'll merge it and clean a couple of little things later.
