### ISSUE TITLE
Is it possible to hide elements on the first page (example: footer)?

### ISSUE THREAD

**Issue by cymen** [Kozea/WeasyPrint#474]
Is it possible to hide elements on the first page of the generated PDF? I have some footer elements that repeat on every page. I would like to hide them on the first page.

I tried the [@page :first](https://drafts.csswg.org/css-page-3/#first-pseudo) selector like so:

```css
      @page :first .footer {
        display: none;
      } 
```
However, running weasyprint emits:

```log
WARNING: Parse error at 67:13, invalid @page selector
```
(67:13 corresponds to the above CSS)

**Comment by cymen** [comment]
Ah! I see that I missed this part:

> The @page rule can only contain page properties and margin at-rules.

So it is logical that @page cannot support this. Is there another mechanism that might work?

**Comment by MindFluid** [comment]
You can use named pages, as mentioned in this issue: [#511](https://github.com/Kozea/WeasyPrint/issues/511).

If you have the ability, you could define your first page in a separate section or block, plug in its unique data, and give it a break after property.

**Comment by liZe** [comment]
> You can use named pages, as mentioned in this issue: [#511](https://github.com/Kozea/WeasyPrint/issues/511).

It's right, using named pages as explained should be enough.

**Comment by ritiksoni00** [comment]
> > The @page rule can only contain page properties and margin at-rules.

give it a break after the property I'm not able to get it. can you please explain a Lil bit.

**Comment by movahhedi** [comment]
I'm not able to get it too. Any ideas?

**Comment by liZe** [comment]
> I'm not able to get it too. Any ideas?

You can use [named pages](https://drafts.csswg.org/css-page/#using-named-pages) (or just `:first` for the first page) to put different things in the page margins.

**Comment by movahhedi** [comment]
How though?

This doesn't work:
```css
@page :first .header {
    display: none;
} 
```

I need the first page not to have a header.

**Comment by liZe** [comment]
> I need the first page not to have a header.

You can take a look at what’s done in the [Report sample](https://weasyprint.org/#samples). The header is repeated on some but not all pages.
