### ISSUE TITLE
weasyprint (v0,29 Gentoo) requires CairoSVG 1.0.20 to run

### ISSUE THREAD

**Issue by angelus2014** [Kozea/WeasyPrint#476]
We have 3 Linux containers, Gentoo based, which have weasyprint installed. In the Gentoo repositories version 0.29 is the latest available and in the ebuild it requires CairoSVG 1.0.7 at least. This version is installed, It works on two systems, but on _one_ system, when trying to run I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (CairoSVG 1.0.7 (/usr/lib64/python3.4/site-packages), Requirement.parse(
'CairoSVG>=1.0.20'), {'WeasyPrint'})                                                                             
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/weasyprint", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_s
et                                                                                                                   working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'CairoSVG>=1.0.20' distribution was not found and is required by WeasyPrint
```

**Comment by liZe** [comment]
[WeasyPrint 0.29 does require CairoSVG>=1.0.20](https://github.com/Kozea/WeasyPrint/blob/v0.29/setup.py), that's a problem in [Gentoo's ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/weasyprint/weasyprint-0.29.ebuild) that's already reported on [Gentoo's bugzilla](https://bugs.gentoo.org/show_bug.cgi?id=620286).

**Comment by liZe** [comment]
By the way, you may find interesting ebuilds in [Kozea's repository](https://github.com/Kozea/overlay).

**Comment by angelus2014** [comment]
The ebuild does _not_ require >=1.0.20, but 1.0.7 that's why I can install it without problems. Only when _running_ it, it errors out while stating that now it needs >=1.0.20

**Comment by liZe** [comment]
> The ebuild does not require >=1.0.20, but 1.0.7

Indeed. That's the bug.

> And like I said, it works on 2 containers, same weasyprint version, same cairosvg version as on the one where it doesn't work.

I don't know why, but that's what users tell on the bug report too. It's a Gentoo bug, it's already been reported, we can't do anything here :cry:.

**Comment by angelus2014** [comment]
Okay, clear. I already added my 'me too' to the bugzilla at Gentoo, but it's still on 'unconfirmed', so I won't hold my breath waiting for an update there. Only way it seems is to add your overlay, even though I'm not that keen on these on production servers...... But thank you for the explanation.

**Comment by angelus2014** [comment]
Hello, I installed the overlay you mentioned on a Gentoo LXC and after a eix-sync, I get a LOT of errors concerning your overlay. See https://pastebin.com/NY2ZFCSy

**Comment by liZe** [comment]
Thanks! There's a lot of old stuff :smile:. I've removed many packages, it should be clean now.

**Comment by angelus2014** [comment]
Hello, still getting the errors though.....

**Comment by liZe** [comment]
[The ebuilds have been removed](https://wiki.gentoo.org/wiki/Project:Overlays/Overlays_guide), you probably have some cache or something like that… I've also updated the README to use the new Gentoo's repo system instead of layman, it may help.

**Comment by angelus2014** [comment]
Oeps, forgot the layman -S :D No more errors now.
