### ISSUE TITLE
Truncation of text if font-size is set to 12px

### ISSUE THREAD

**Issue by mark-cameron** [Kozea/WeasyPrint#478]
When exporting a document this string "Study of the association between SOD3G362A polymorphism, seminal SOD activity and risk for male infertility in Algeria" is truncated to when the font-size is set to 12px:
![image](https://user-images.githubusercontent.com/5310733/27210295-81b42bcc-52a5-11e7-9100-a1371834f5e7.png)
If the styling is changed so that the font-size is 11px or 13px then it is fine:
![image](https://user-images.githubusercontent.com/5310733/27210297-87b6f2d4-52a5-11e7-99dd-5bd27280a0d0.png)

**Comment by liZe** [comment]
Looks like #233. Do you use Cairo < 1.14.2?

**Comment by mark-cameron** [comment]
Good to know it could be this. 
No we don't currently as we are using Debian and the current stable version is 1.14.0.
Will wait until the release the next version and update the issue then.

**Comment by liZe** [comment]
> we are using Debian and the current stable version is 1.14.0.

Then I'm pretty sure it's #233. We've even added a message in #423 to warn users, that wasn't enough :smile:.
