### ISSUE TITLE
slow performance with Pygments?

### ISSUE THREAD

**Issue by dmalan** [Kozea/WeasyPrint#483]
Is particularly slow performance on HTML generated by [Pygments](http://pygments.org/) to be expected, even on relatively small files? On Ubuntu 14.04 with WeasyPrint 0.39 (and, to be fair, an older Cairo and Pango), we're currently seeing the following if we try to syntax-highlight, e.g., `weasyprint/fonts.py` (which only has 294 lines) from WeasyPrint's own package:

```
$  pygmentize -O full -o fonts.html fonts.py
$ time weasyprint fonts.html fonts.pdf
/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/weasyprint/text.py:29: UserWarning: There are known rendering problems with Cairo <= 1.14.0
  warnings.warn('There are known rendering problems with Cairo <= 1.14.0')
/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/weasyprint/fonts.py:46: UserWarning: @font-face support needs Pango >= 1.38
  warnings.warn('@font-face support needs Pango >= 1.38')

real	0m46.330s
user	0m45.970s
sys	0m0.200s
```

But is 46 seconds (inside a Docker container on a recent Mac Pro) indeed to be expected for a 294-line syntax-highlighted file? We've experimented with a few Weasy and Pygments options, but none seem to boost performance noticeably. Runtime seems to increase noticeably, though, as soon as the input fills more than 1 page of the PDF. 

Sample inputs at https://gist.github.com/dmalan/9519e730b207e524bc6165966a492acf, and sample output at https://github.com/Kozea/WeasyPrint/files/1120994/fonts.pdf.

Runtime aside, everything is rendering quite nicely. Thank you!

**Comment by liZe** [comment]
Re-applying the "optimization" removed in cff4452 gives me -30% rendering time for your use case. We should try to revert this commit in a smart way. And I'm sure that we can do even better than that.

**Comment by liZe** [comment]
> And I'm sure that we can do even better than that.

Of course, we can do better than that! When there's no text wrap, we already know where to break lines: at `\n` characters…

**Comment by liZe** [comment]
It now takes less than 2s instead of about 28s for me. Not that bad!

For the record: cutting the lines isn't that useful in this case because there are lots of spans.

**Comment by dmalan** [comment]
Amazing, thanks so much for such a quick commit, Guillaume. Just went from 1m8s to 4s (on a laptop) on our end! Game-changing for sure. Much appreciated!
