### ISSUE TITLE
WeasyPrint crashes when there's a local() with a font name with a space in it and no quotes around in CSS

### ISSUE THREAD

**Issue by tulphoon** [Kozea/WeasyPrint#487]
minimum test case:
```@font-face { font-family: "Test"; src: local(Test Test) }```

**Comment by liZe** [comment]
It's also broken with `local()` for a slightly different reason.

**Comment by liZe** [comment]
The first use case was broken when WeasyPrint was ported to tinycss2. The second one was broken since the beginning. Thanks for reporting!
