### ISSUE TITLE
Show progress during document rendering

### ISSUE THREAD

**Issue by morlandi** [Kozea/WeasyPrint#488]
Any chances to hook into a inner loop inside render_doc() to notify app about process progress ?
I'm thinking about the possibility to have a user supplied callback called at sensible times when rendering an heavy document.

**Comment by liZe** [comment]
That's a good idea. During the various tests I've done during the last weeks, I've been wondering why we don't have a `--verbose` option showing the debug information and the rendering steps. It's possible to add your feature and the logging feature, maybe using the logging module.

**Comment by liZe** [comment]
Related to #416.

**Comment by morlandi** [comment]
Using the logging module would be a very nice option, as long as I can capture the log statements during document rendering from another process; maybe this can be done connecting a StreamHandler to a StreamBuffer .. not sure.
I'm currently rendering documents in a background process (controlled by a django-rq queue), and wish to deliver the progress value to the user waiting for completion. 
Ideally, this progress should be express in percentage; no particular precision is required, but the progress update should be reasonably linear.

After a quick look at the sources, I guess that the loop inside layout.pages.make_all_pages() could be a good starting point. Any suggestion ?

**Comment by liZe** [comment]
> Using the logging module would be a very nice option, as long as I can capture the log statements during document rendering from another process

Of course!

> Ideally, this progress should be express in percentage; no particular precision is required, but the progress update should be reasonably linear.

Reliable percentage is quite hard to get, because we need to:
- know what's the ratio of time spent between [the 8 steps](http://weasyprint.readthedocs.io/en/latest/hacking.html#dive-into-the-source),
- and know in a step what's the percentage (easy in 7, hard in 5, useless everywhere else).

> After a quick look at the sources, I guess that the loop inside layout.pages.make_all_pages() could be a good starting point. Any suggestion ?

Yes, that's the main part. Now that I've got quite a good idea about what I want, I'll add some code really soon.

**Comment by liZe** [comment]
(And related to #351 too.)

**Comment by morlandi** [comment]
Thank you @liZe; I'll be abroad for vacation for a few weeks; on my coming back to work, we might keep in touch to exchange some ideas and maybe some coding; at the very least, I'ld be glad to help in testing the new logging feature, when available, in a real project.

You're right, it's difficult to obtain a linear progression, and maybe it's not required, either.
Let's downgrade to a more affordable solution: we might assign a fixed "progress range" for the first steps, then progress linearly where the hard and time consuming work is delivered; especially when it's proportional to the complexity and size of the rendered document. 
In practice, we only need to reassure the end user that the process is not stuck and something is still going on when we keep him waiting for long.

**Comment by morlandi** [comment]
Very nice, thank you @liZe

**Comment by morlandi** [comment]
@liZe ... thank you very much for the new logging feature, which works pretty well.
A little question  ... I'm afraid I already know the answer, but just to make sure ...

During pages layout creation, is there any chance to estimate in advance the total number of pages, thus logging:

`INFO Step 5 - Creating layout - Page 6/100`

instead of 

`INFO Step 5 - Creating layout - Page 6`

Thank you again for the new feature; you might very well want to close this issue; I do believe that the new logging feature fully fits the bill.

**Comment by liZe** [comment]
> During pages layout creation, is there any chance to estimate in advance the total number of pages, thus logging:
> 
> INFO Step 5 - Creating layout - Page 6/100
> 
> instead of
> 
> INFO Step 5 - Creating layout - Page 6

Unfortunately not, we only know the number of pages at the end of the layout. We could have used the HTML line numbers to have an (unreliable) estimation, but it's been removed with the removal of lxml as it's not supported by ElementTree.

We **may** be able to write a function with `resume_at` and the document boxes as inputs, and returning a percentage as output, but that's a lot of work to get a very bad result in my opinion.

> Thank you again for the new feature; you might very well want to close this issue; I do believe that the new logging feature fully fits the bill.

Let's close that issue even if it's not perfect. If anyone is interested in working (hard) trying to improve progress reporting, just ask, I'll try to do my best to help!

**Comment by morlandi** [comment]
In a project I'm workin on, Weasyprint is used to render PDF documents from background tasks (based on django-rq).
In this context, the new logging feature of Weasyprint has been proven useful not only for logging purposes, but also to give each background task a chance to update it's own progress indicator, in order to inform the user that the process is still alive, and also to give a rough indication of how far the document rendering has proceeded so far.

This can easily be done attaching a logging.Filter instance to weasyprint logger.

Should someone be interested in this technique, here's a simplified code snippet:


```
import weasyprint
from weasyprint.logger import LOGGER as weayprint_logger


@job(PrintTask.TASK_QUEUE)
def print_job(**kwargs):

    job = get_current_job(connection=redis.Redis.from_url(settings.REDIS_URL))
    task, created = PrintTask.objects.get_or_create(job_id=job.get_id(), **kwargs)
    task.set_status('STARTED')

    # intercept Weasyprint logger messages to update task progress 
    # during document rendering
    weayprint_logger.setLevel(logging.DEBUG)
    weayprint_logger.addFilter(WesyprintLoggerFilter(task))
    ...
    weasyprint.HTML(...).render(...)
    ...


# See:
# https://stackoverflow.com/questions/28603159/python-intercept-logging-to-email-or-sms#28603520
class WesyprintLoggerFilter(logging.Filter):

    task = None

    def __init__(self, task):
        self.task = task

    def filter(self, record):
        print('%s| %s' % (self.task.id, record.getMessage()))
        progress = self.task.get_progress()
        self.task.set_progress(progress + 1)
        return True


```

**Comment by liZe** [comment]
@morlandi Thank you! I've added code similar to your snippet into the documentation.

**Comment by morlandi** [comment]
You're welcome !
BTW, I was just wondering whether you suggest to use:

`logger = logging.getLogger('weasyprint')`

as you did in the doc, or

`from weasyprint.logger import LOGGER as weayprint_logger`

as seems suggested in the project code.

**Comment by liZe** [comment]
It's the same, you'll find `LOGGER = logging.getLogger('weasyprint')` in `weasyprint.logger` :smile:.
