### ISSUE TITLE
Add CLI options for using stdio

### ISSUE THREAD

**Issue by MattSturgeon** [Kozea/WeasyPrint#492]
I am using weasyprint as part of a [gulp](//gulpjs.com) buildscript. Gulp works on the principal of piping data from one build task to the next, without writing unnecessary files (similar to using `|`, `>` and `<` on a POSIX shell).

[As far as I can tell](http://weasyprint.readthedocs.io/en/latest/api.html#command-line-api) WeasyPrint only supports using actual files for CLI IO, and while on POSIX systems I could use the `/dev/stdin` and `/dev/stdout` files, it would be nice to have a cross-platform CLI option to use stdin for the input file and stdout for the output.

This would also mean printing errors, warnings, etc to stderr to keep it separate from the output.

**Comment by MattSturgeon** [comment]
Doh, just took a look to see if I could implement this and the first thing I see is

> help='URL or filename of the HTML input, **or - for stdin**'

Feel free to mark this as invalid, don't know how I missed that from the docs.

**Comment by liZe** [comment]
:smile:
