### ISSUE TITLE
Silently ignore known CSS vendor prefixes

### ISSUE THREAD

**Issue by MattSturgeon** [Kozea/WeasyPrint#493]
Currently, if your stylesheet includes vendor prefixes such as `-webkit-` WeasyPrint produces a lot of spam output:

```
WARNING: Ignored `overflow-y: scroll` at 6:3, unknown property.
WARNING: Ignored `-webkit-text-size-adjust: 100%` at 7:3, unknown property.
WARNING: Ignored `-ms-text-size-adjust: 100%` at 8:3, unknown property.
WARNING: Invalid or unsupported selector '*::-moz-selection', Unknown pseudo-element: -moz-selection
WARNING: Invalid or unsupported selector '*::selection', Unknown pseudo-element: selection
WARNING: Invalid or unsupported selector 'a::-moz-selection', Unknown pseudo-element: -moz-selection
WARNING: Invalid or unsupported selector 'a::selection', Unknown pseudo-element: selection
WARNING: Ignored `_font-family: 'courier new', monospace` at 120:3, unknown property.
WARNING: Ignored `-ms-interpolation-mode: bicubic` at 192:3, unknown property.
WARNING: Ignored `filter: none` at 246:5, unknown property.
WARNING: Ignored `-ms-filter: none` at 247:5, unknown property.
```

I would recommend silently ignoring known vendor prefixes in the same way that `:hover` and others are silently ignored.

OTTOMH, common prefixes include `-webkit-`, `-moz-`, `-ms-`, `-o-`. People also sometimes use `_` and `*` within property names to [target old buggy IE versions](https://learntech.imsu.ox.ac.uk/blog/?p=494).

While this may not be the biggest issue when styles are built specifically for weasyprint, when sharing styles with other media types this would go a long way to cleaning up the output.

**Comment by liZe** [comment]
It's done since version 45 (see 74f56f7), it's now a debug message, not a warning anymore.
