### ISSUE TITLE
Installing in debian 9 using python3

### ISSUE THREAD

**Issue by bustawin** [Kozea/WeasyPrint#496]
Hello,

First, let me congratulate you for this library –by far the best HTML - PDF conversion I have tried.

To achieve a successful install in Debian 9 and python 3.5 (as you recommend Python 3 for Linux), I had to install the dependencies using the command you suggest for _Ubuntu 16.04 or newer_ and an extra package: ``build-essential`` (otherwise ``cairocffi`` can't compile some stuff and fails).

And let me mention that the documentation can be slightly confusing, as you recommend python 3 but then you offer only, for Debian, instructions for python2, which can be interpreted as the python2 version could work with python3 (which I suppose it can't, please correct me if I am wrong).

**Comment by liZe** [comment]
> Hello,

Hello!

> First, let me congratulate you for this library –by far the best HTML - PDF conversion I have tried.

:smile:

> To achieve a successful install in Debian 9 and python 3.5 (as you recommend Python 3 for Linux), I had to install the dependencies using the command you suggest for Ubuntu 16.04 or newer and an extra package: build-essential (otherwise cairocffi can't compile some stuff and fails).

Strange, I thought that python3-dev was installing the needed packages. I'll change the documentation.

> And let me mention that the documentation can be slightly confusing, as you recommend python 3 but then you offer only, for Debian, instructions for python2, which can be interpreted as the python2 version could work with python3 (which I suppose it can't, please correct me if I am wrong).

Yes, the documentation has been updated for Debian 9 in f225f8b, it's up-to-date online when the "latest" version is selected. It'll be included with the code in the next version.

I'll keep the documentation with Python2 for older versions of Debian/Ubuntu as I can't test these distibutions, but if anyone wants to test and update the documentation, I'll merge the PR for sure!
