### ISSUE TITLE
Zapfino typface (font) not correctly rendered

### ISSUE THREAD

**Issue by ghost** [Kozea/WeasyPrint#50]
![zapfino_sm](https://f.cloud.github.com/assets/85394/264733/1e53ffb0-8d99-11e2-9af1-d2a2fc089b14.png)
![Screen shot 2013-03-15 at 17 53 40](https://f.cloud.github.com/assets/85394/264737/55fd50ce-8d99-11e2-93ee-54e260717d31.png)

On OS X 10.6.8, Firefox, TextEdit and others render the word "Zapfino" in the typeface Zapfino as in the first attached image. However, WeasyPrint renders it as in the second attached image.

My understanding is that in this particular case, Firefox, TextEdit, etc, are honouring Zapf's intentions, and that WeasyPrint is not.

**Comment by SimonSapin** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=738505 might be relevant, but I don’t know if it’s in a Pango release yet. We’d want some conditional code to only use it when available.
