### ISSUE TITLE
Bug: URLs starting with slash treated as absolute with respect to file system, not base-url

### ISSUE THREAD

**Issue by martijnthe** [Kozea/WeasyPrint#501]
Example:

File tree:
- /cwd
  - /folder
    - index.html
  - /css
    - style.css

`/cwd/folder/index.html` contains this snippet:
```
<link rel="stylesheet" href="/css/style.css">
```

When running `weasyprint --base-url path/to/cwd cwd/folder/index.html out.pdf` I'm getting this error:

```
ERROR: Failed to load stylesheet at file:///css/style.css : URLError: <urlopen error [Errno 2] No such file or directory: '/css/style.css'>
```

This suggests to me that the URL that starts with a slash (`/`) is incorrectly mapped to the root of the entire file system and using base-url as a root (what a browser would do).

**Comment by liZe** [comment]
Thanks for taking the time to report this issue!

It's a bit hard to explain, but I think that there's no problem in WeasyPrint's code here (but maybe in the documentation).

[`base_url`](https://tools.ietf.org/html/rfc3986#page-28) is an URL used as base to transform relative paths into absolute URLs. It basically means that:
- `base_url` + `relative_path` = `absolute_url`, i.e.
- `http://server.com/test/` + `css/style.css` = `http://server.com/test/css/style.css`.

`base_url` is also used to solve absolute paths, removing `base_url`'s path:
- `base_url` - `base_url_path` + `absolute_path` = `absolute_url`, i.e.
- `http://server.com/test/` - `/test/` + `/css/style.css` = `http://server.com/css/style.css`.

You give `path/to/cwd` as `base_url`. As it's not an URL, WeasyPrint transforms this path to an URL. If your give `/tmp/`, it will be changed into `file:///tmp/`. If you give `relative/path/`, it will give you `file:///absolute/current/path/relative/path/`.

When you use absolute paths in your HTML or CSS files, WeasyPrint will apply the rule explained above:
- `base_url` - `base_url_path` + `absolute_path` = `absolute_url`, i.e.
- `file:///tmp/` - `/tmp/` + `/css/style.css` = `file:///css/style.css`.

> This suggests to me that the URL that starts with a slash (/) is incorrectly mapped to the root of the entire file system and using base-url as a root (what a browser would do).

Yes, when paths starting with a slash are resolved, the path part of the base URL is removed. That's not incorrect, that's what other browsers do too.

I've tried:

```html
<!-- /tmp/lol.html -->
<link rel="stylesheet" href="/css/style.css">
<body>a</body>
```

```css
/* /tmp/css/style.css */
body{background:red}
```

Just like WeasyPrint, browsers (at least Chrome and Epiphany) don't find the CSS file when I open `/tmp/lol.html`. They do if I remove the leading slash of `/css/style.css`.

**Comment by martijnthe** [comment]
Aha! Thanks for clarifying!
