### ISSUE TITLE
Prevent orphaned list items?

### ISSUE THREAD

**Issue by mb21** [Kozea/WeasyPrint#503]
Is it possible to prevent a single list item from being orphaned on the next page? E.g. prevent the following rendering:

```
- list item one
- list item two

<page break>

- list item three

following paragraph
```

I was thinking of something like:

```
ul {
  orphans: 3;
}
```

Not even sure this is intended behaviour by the CSS spec though (c.f. this [SO question](https://stackoverflow.com/questions/18041146/should-css-orphan-operate-at-line-or-block-level))

**Comment by liZe** [comment]
> Is it possible to prevent a single list item from being orphaned on the next page?

Orphans / Widows only work for line-boxes, not for block-like boxes.

Fortunately, you can define rules like:
```css
li:last-child {
  break-before: avoid;
}
li:first-child {
  break-after: avoid;
}```

Didn't test, but it should work.

**Comment by mb21** [comment]
Thanks a lot, that did the trick!

**Comment by HiroDane** [comment]
Any idea how to apply the same logic for tables? I want to ensure headers and at least 1 data row are together

**Comment by liZe** [comment]
> This does not work

Could you please open a separate issue for your question?
