### ISSUE TITLE
Linear gradient does not work with Pdf rendering

### ISSUE THREAD

**Issue by mcherkassky** [Kozea/WeasyPrint#504]
Trying to get linear gradients to work in tables a la Pandas style bar charts (https://pandas.pydata.org/pandas-docs/stable/style.html)

However, when rendering these in Pdf form it seems like the transparency isn't working in the background linear-gradient css function. Not sure what's going on as if I render it into a PNG file everything looks fine. 

This is the output from PDF
![image](https://user-images.githubusercontent.com/1049127/30250468-d3912ab6-961c-11e7-9011-a2b46372d3bc.png)

This is the correct output from PNG:
![image](https://user-images.githubusercontent.com/1049127/30250476-084b81fc-961d-11e7-909e-c44421ba8386.png)

Note how the bars in the PDF version don't change size for some reason

Here's some raw html to play around with
[test.txt](https://github.com/Kozea/WeasyPrint/files/1290665/test.txt)

I understand it may be a cairo issue...

**Comment by liZe** [comment]
> I understand it may be a cairo issue...

Yes, that's probably the case, as we get different renderings in PNG and PDF documents. I'll try to find the cause of the problem, report an issue for Cairo and/or find a workaround in WeasyPrint.

**Comment by liZe** [comment]
@mcherkassky You’ll be happy to learn that the current `pydyf` branch works well for your example 😉. Cairo was the problem.

**Comment by liZe** [comment]
`pydyf` is now `master` :tada:.
