### ISSUE TITLE
@font-face issue

### ISSUE THREAD

**Issue by leesus** [Kozea/WeasyPrint#506]
Using the Python API, my custom font isn't showing in the PDF. When I try using the command line arguments on Mac, the PDF is output fine, with the font. Minimal example below, hopefully I'm just missing something simple.

CSS
```
@font-face {
  font-family: MyCustomFont;
  font-style: normal;
  src: url(http://path.to/MyCustomFont.ttf) format('truetype');
}

body {
  font-family: MyCustomFont;
}
```

Python
```
font_config = FontConfiguration()
stylesheet = CSS(path_to_my_stylesheet, font_config=font_config)
pdf = HTML(string=my_html_template_string).write_pdf(stylesheets=[stylesheet])
```

The CSS is output correctly, just the fonts aren't showing up.

**Comment by liZe** [comment]
Thanks for taking the time to report this issue.

That was actually a problem in the API, you couldn't use the `font_config` attribute with `render` and `write_*` methods. That's now fixed if you give `font_config` to `write_pdf`. I've also updated the [tutorial](http://weasyprint.readthedocs.io/en/latest/tutorial.html#as-a-python-library).

**Comment by sunanda-sarbadhikary-navsoft** [comment]
It cannot support Thai character when creating pdf
Example: ซอยกรุงเทพกรีฑา
Output: Not supporting the character.
But from my local linux machine it works fine.
Only server its not working. I use docker for build to server.
Please reply as soon as possible.

**Comment by liZe** [comment]
> Only server its not working. I use docker for build to server.

You probably don't have fonts with Thai characters installed on your server. Install such fonts or use `@font-face` rules with Thai fonts to solve the issue.

> Please reply as soon as possible.

People here already reply as soon as possible. You don't have to ask them, it just makes them angry :angry: :wink:.
