### ISSUE TITLE
Convert selection html to pdf?

### ISSUE THREAD

**Issue by eromoe** [Kozea/WeasyPrint#510]
Hi,

Actually I am searching a lib to convert web site content to text (such as evernote, get just title and content of an article ).  There are many lib use to convert html to text, but none of them accept css files, 
because I want content be plain text and **layout(blank and line-feed)** looks like original html . So So I make compromise to  html -> pdf -> text . WeasyPrint  is the best one html&css to pdf convertor as I see.

1. convert selection html(only some css selector, but applied the  styles inherient from parent) to pdf

2. Additinal   but everytime convert to pdf then use another lib convert pdf to text may be costly,   so I wonder if WeasyPrint can directly give me  text instead of pdf ?

**Comment by liZe** [comment]
> convert selection html(only some css selector, but applied the styles inherient from parent) to pdf

You can add specific CSS stylesheets to your document to hide the elements you don't want to display, that's all I can think about.

> Additinal but everytime convert to pdf then use another lib convert pdf to text may be costly, so I wonder if WeasyPrint can directly give me text instead of pdf ?

Unfortunately no, there's no easy trick to skip the PDF part. By the way, I think that the main part of the time is used to create the layout, not to put this layout on a PDF.

**Comment by liZe** [comment]
@eromoe Can I close this issue?
