### ISSUE TITLE
How to add cover page? and How to hide some contents in first page only?

### ISSUE THREAD

**Issue by xploregopi** [Kozea/WeasyPrint#511]
How to add cover page?
 How to hide some contents in first page only?

**Comment by liZe** [comment]
Cover pages can be added using either:
- the [`:first` pseudo-class](https://www.w3.org/TR/CSS2/page.html#page-selectors), or
- [named pages](https://drafts.csswg.org/css-page-3/#using-named-pages).

You can find other related stuff in #92 too.

**Comment by ritiksoni00** [comment]
> Cover pages can be added using either:
> 
> * the [`:first` pseudo-class](https://www.w3.org/TR/CSS2/page.html#page-selectors), or
> * [named pages](https://drafts.csswg.org/css-page-3/#using-named-pages).
> 
> You can find other related stuff in #92 too.


i tried||

 ```html
@page first{
    display: table-row;
}
.first-page {
    page: first;
    display: none;
}
```

 and it doesn't work. What's wrong in it?

**Comment by kdipippo** [comment]
Replying to this thread from 5 years ago with a possible solution: make 2 `WeasyPrint.HTML` objects: one containing the cover page and another containing the rest of the content and merge them together.

This applies at least to `weasyprint==60.1`.

```py
# Assemble cover page Document, should generate only 1 page within weasy_coverpage_doc.pages.
coverpage_html_string = "... your function that returns coverpage html string ..."
weasy_coverpage_html = HTML(string=coverpage_html_string)
weasy_coverpage_doc = weasy_coverpage_html.render()

# Assemble content Document.
html_string = "... your function that returns content html string ..."
weasy_html = HTML(string=html_string, base_url=markdown_path)
weasy_doc = weasy_coverpage_html.render()

# Insert first (will be only) page from weasy_coverpage_doc into pages in weasy_doc.
weasy_doc.pages.insert(0, weasy_coverpage_doc.pages[0])
weasy_doc.write_pdf(f"content_with_coverpage.pdf")
```
