### ISSUE TITLE
Failed to load image at data:image/svg+xml, incorrect padding

### ISSUE THREAD

**Issue by sfdye** [Kozea/WeasyPrint#515]
I have an issue to render base64 svg to pdf that ends with something like:

"z48L2c+PC9zdmc+/" 
(not ending in "=")

(The error message goes like: Incorrect padding)

I notice when I install/uninstall `lxml`, sometimes the problem goes away, but it's nondeterministic for different cases.

I am using pygal with weasyprint in Django and my code is like:
```python
year_chart = pygal.HorizontalBar()
year_chart.add('2016', 4)
print(year_chart.render_data_uri())
```

The print will give different result based on whether `lxml` is installed or not.

I also saw #75, not sure if this is related.

**Comment by liZe** [comment]
That's really strange. `render_data_uri` uses the standard `base64.b64encode` to generate the base64 string. Could you provide a full example of base64 string that raises the "Incorrect padding" error?

**Comment by sfdye** [comment]
PFA
[error.log](https://github.com/Kozea/WeasyPrint/files/1363113/error.log)

**Comment by liZe** [comment]
You have an extra `/` at the end of the data URL, it's probably not related to Pygal or WeasyPrint :wink:.

**Comment by sfdye** [comment]
Interesting, but I didn't add the `/` myself. It's all rendered by the `render_data_uri ` method.

My template goes like,
```html
<embed type="image/svg+xml" src={{ year_chart|safe }}/>
```

Do you spot any error?

**Comment by liZe** [comment]
Yes! You have to add quotes after `src=`, or the slash used to close the tag is included in the `src` attribute!

```html
<embed type="image/svg+xml" src="{{ year_chart|safe }}" />
```

**Comment by sfdye** [comment]
Oops, thanks for pointing out my silly mistake.
