### ISSUE TITLE
SVG paths getting dropped when SVG has intrinsic size

### ISSUE THREAD

**Issue by martijnthe** [Kozea/WeasyPrint#518]
I found a weird bug where paths of an SVG are getting dropped.
I tried to create a minimal test case that reproduces the issue: [test.zip](https://github.com/Kozea/WeasyPrint/files/1360644/test.zip)

The test.svg has `width="458.2583mm"` which is larger than the page width, but in the test.html the element is scaled to 80%:
```
<img src="test.svg" style="width: 80%;">
```

A whole bunch of paths from the test.svg are getting dropped in the PDF output:
<img width="448" alt="screen shot 2017-10-05 at 21 46 46" src="https://user-images.githubusercontent.com/193881/31249205-bab22582-aa16-11e7-9ea6-074169279b9d.png">

Interestingly, if the `width` and `height` in the test.svg are removed, the PDF output is correct:
<img width="400" alt="screen shot 2017-10-05 at 21 44 22" src="https://user-images.githubusercontent.com/193881/31249098-5f51726a-aa16-11e7-97a0-3e196e274fac.png">

I also tried running the test.svg (with the `width`) through `cairosvg` directly. The (PDF) output is correct there, so I suspect the bug is in WeasyPrint.

**Comment by liZe** [comment]
I've tried your example, and it works for me. You're probably using an old version of WeasyPrint or CairoSVG. It can also be caused by Cairo (see #278).

**Comment by martijnthe** [comment]
I was on the latest WeasyPrint and CairoSVG, however, Cairo was 1.14.10 (I installed from homebrew and didn't realize it was so old). Your patch was only included in 1.15.4 I believe.

**Comment by martijnthe** [comment]
Thanks for the quick response BTW!
