### ISSUE TITLE
WeasyPrint Logo not on First Page in Test

### ISSUE THREAD

**Issue by wilbersmith** [Kozea/WeasyPrint#519]
Hello, 

This is my first issue ever so I apologise if this is the wrong place. I tried getting into the IRC chat and had no luck. The site says:

> You should see warnings about unsupported CSS 3 stuff; this is expected. In the PDF you should see the WeasyPrint logo on the first page.

Everything prints out fine except that there is no logo. I am wondering if I have missed something. Please help. 

My errors are below:
ERROR: Failed to load stylesheet at https://fonts.googleapis.com/css?family=Oswald : URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
ERROR: Failed to load stylesheet at https://fonts.googleapis.com/css?family=Alegreya+Sans:400,400italic,700 : URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
ERROR: Failed to load stylesheet at https://fonts.googleapis.com/css?family=Cousine : URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
WARNING: Ignored `transition:color 0.25s` at 1:459, unknown property.
WARNING: Ignored `text-shadow:1px 1px 1px #111` at 1:664, unknown property.

**Comment by wilbersmith** [comment]
I apologize. I am on a Mac. All other libraries are installed through homebrew with no issue as far as I can tell. I still have the output from the homebrew install command if needed. 

This was from the first test command: weasyprint http://weasyprint.org ./weasyprint-website.pdf

I thought I would throw is the pdf as well. 
[weasyprint-website.pdf](https://github.com/Kozea/WeasyPrint/files/1361425/weasyprint-website.pdf)

**Comment by wilbersmith** [comment]
Additionally, looking through the homebrew install there was only this as a relevant error:

> ==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.sierra.bottle.tar.gz
> ######################################################################## 100.0%
> ==> Pouring libffi-3.0.13.sierra.bottle.tar.gz
> ==> Caveats
> This formula is keg-only, which means it was not symlinked into /usr/local.
> 
> Some formulae require a newer version of libffi.
> 
> Generally there are no consequences of this for you. If you build your
> own software and it requires this formula, you'll need to add to your
> build variables:
> 
>     LDFLAGS:  -L/usr/local/opt/libffi/lib
>     PKG_CONFIG_PATH: /usr/local/opt/libffi/lib/pkgconfig

**Comment by liZe** [comment]
Don't worry, the logo was not displayed in the printed version of the website, it was an error in the documentation :smile:. The logo is back, you can try again!

**Comment by wilbersmith** [comment]
Face-palm. I should've looked at the site itself. Tried again. The logo is especially beautiful. Thanks!

**Comment by liZe** [comment]
Thank you :smile:!
