### ISSUE TITLE
CSS @page rule seems to be ignored if imported by @import rule

### ISSUE THREAD

**Issue by berndnicklas** [Kozea/WeasyPrint#520]
Hello,

while referencing a file `pagerule.css` containing

```
/* rule #1 */
@page {
  size: A4;
  margin-top: 1.5cm;
  margin-right: 1.5cm;
  margin-bottom: 1.5cm;
  margin-left: 2.5cm;
}

/* rule #2 */
body {
  background-color: lime;
}
```
directly in HTML via

`<link rel="stylesheet" href="pagerule.css" />
`

works like a charm, it seems that importing the file via CSS

`@import url("pagerule.css");
`

or

`@import url("pagerule.css") all;
`

into a referenced CSS file only processes rule `#2` while rule `#1` (the page rule) is completely ignored. On weasyprint command line interface with verbosity switched on, no warnings or errors are printed.

In Chrome print preview this is rendered correctly.

Is this a bug or intended behaviour?

Best regards,

Bernd

**Comment by liZe** [comment]
What a dirty bug! Thanks for your really explicit report!

**Comment by berndnicklas** [comment]
Thank's for your quick fix!

**Comment by djKooks** [comment]
@liZe I'm also facing with same bug. Is this fixed?

**Comment by liZe** [comment]
> @liZe I'm also facing with same bug. Is fixed version released?

No, it's not released yet, there's a couple of issues I'd like to fix before the next version.

**Comment by djKooks** [comment]
@liZe Okay, thanks. Is the fix commit merged in master?

**Comment by liZe** [comment]
> Is the fix commit merged in master?

Yes, it is.
