### ISSUE TITLE
ImportError: cannot import name properties

### ISSUE THREAD

**Issue by benmolin** [Kozea/WeasyPrint#524]
Hi -- 

I'm sure that this is a basic question, but I am having trouble importing the files needed to run to run WeasyPrint.

**My code, up to the error:**

```
import weasyprint
from __future__ import print_function
import pandas as pd
import numpy as np
import argparse
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML
```

**The Error**

```
----> 6 import weasyprint
      7 from __future__ import print_function
      8 import pandas as pd

...   /python2.7/site-packages/weasyprint/__init__.py in <module>()
    373 
    374 # Work around circular imports.
--> 375 from .css import preprocess_stylesheet  # noqa
    376 from .html import (
    377     find_base_url, HTML5_UA_STYLESHEET, HTML5_PH_STYLESHEET,

...   /python2.7/site-packages/weasyprint/css/__init__.py in <module>()
     27 import tinycss2
     28 
---> 29 from . import properties
     30 from . import computed_values
     31 from .descriptors import preprocess_descriptors

ImportError: cannot import name properties
```

I am running this code on a Jupyter notebook using a Mac. Is there a simple package that I am missing that I can pip install? Thank you

**Comment by liZe** [comment]
> I am running this code on a Jupyter notebook using a Mac. Is there a simple package that I am missing that I can pip install?

No, this line imports a file that is in the same directory, it should be included in WeasyPrint. I really don't know how you can have this error if you installed WeasyPrint with pip.

Do you have the same problem in a Python interpreter instead of a Jupyter notebook?

**Comment by liZe** [comment]
@benmolin Can I close this issue?

**Comment by GoldenRatio3** [comment]
@benmolin Did you work out what the problem was/ the solution? 

I seem to be having the same issue

**Comment by benmolin** [comment]
@GoldenRatio3 I did not -- didn't end up using this package

**Comment by liZe** [comment]
@GoldenRatio3 I really don't know how it's possible to get this error… Do you use Jupyter too?

**Comment by GoldenRatio3** [comment]
@liZe Currently it works locally then when I deploy to ec2 instance I get this exact error in Django

**Comment by GoldenRatio3** [comment]
@liZe Solved!

For anyone else having this problem it is due to missing dependencies, to fix ssh into ec2 box and run this command:

sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel

To save time you can include these dependencies in your .ebextensions/django.config file

**Comment by sunsetjunks** [comment]
> @liZe Solved!
> 
> For anyone else having this problem it is due to missing dependencies, to fix ssh into ec2 box and run this command:
> 
> sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel
> 
> To save time you can include these dependencies in your .ebextensions/django.config file

this helped me!
