### ISSUE TITLE
setup.py does not play nicely with pipenv

### ISSUE THREAD

**Issue by jmichalicek** [Kozea/WeasyPrint#525]
With the new pipenv, which is [recommended by python.org now](https://packaging.python.org/new-tutorials/installing-and-using-packages/#installing-pipenv), there are issues with using os.sys_version in setup.py to determine which dependencies to install.

It appears that since pipenv technically runs in your main python environment rather than inside the virtualenv it manages, setup.py detects that python version.  So for example I use python 3.6 as my main python, but have a few legacy projects which are on 2.7 for now.  If I use pipenv then weasyprint's setup.py sees python 3.6 in os.sys_version and sets an incorrect version of CairSVG in the requirements.

Would it be possible to use the `extras_require` feature of setuptools 18.0 and up to handle the conditional dependency?

Please also see https://github.com/kennethreitz/pipenv/issues/924

**Comment by liZe** [comment]
Well… I can understand the problem and I'd like to solve it, but I don't understand how `extras_require` could help without breaking the current behavior (`pip2 install weasyprint` installs CairoSVG 1, `pip3 install weasyprint` installs CairoSVG 2). Could you give me a hint?

**Comment by jmichalicek** [comment]
I have not tested this in setup.py, but my understanding is that you should be able to use the environment markers in `extras_require` to install the intended version of CairoSVG.  I've tested this with putting them in a requirements.txt and hard setting the CairoSVG version with markers in the Pipfile successfully.

https://hynek.me/articles/conditional-python-dependencies/ discusses using them in setup.py in `extra_requires`.
https://github.com/pypa/setuptools/issues/1087 also discusses it quite a bit and gives a few examples.

If I've understood correctly, you can remove the bit checking `sys.version_info` and setting the dependency and instead use one of the following
```
setup(
# ...stuff which is already there,
    extra_requires={
        ":python_version<'3.0'":  ['CairoSVG >= 1.0.20, < 2.0.0'],
        ":python_version>='3.0'": ['CairoSVG >= 1.0.20']}
) 
```

**Comment by liZe** [comment]
Looks good to me, thanks for the hint!

**Comment by jmichalicek** [comment]
No problem, I'm glad to see that it works.  Working on getting several projects migrated over to using pipenv has definitely been a bit of a learning experience.
