### ISSUE TITLE
SVG of plot not properly masked

### ISSUE THREAD

**Issue by jmidgren** [Kozea/WeasyPrint#526]
When using matplotlib.pyplot to plot data and "zooming in" to show areas of interest, plotted curves are not masked outside of the plot region when using the produced plot in a PDF. Instead curves are visible beneath axis and labels in the plot.

This only occurs when using SVG format, by using e.g. PNG it works fine. Also, if I open the produced SVG file of the plot in e.g. Firefox, it displays properly with no curve visible outside the plot region.

I can reproduce the problem with various combinations of WeasyPrint 0.36 and 0.41 and libcairo 1.14.0.8 (included in ubuntu 16.04) and 1.15.6.

The small example program below reproduces the problem and will generate the attached PDF:
[test.pdf](https://github.com/Kozea/WeasyPrint/files/1401257/test.pdf)

```python
#!/usr/bin/env python3
from weasyprint import HTML
import matplotlib
matplotlib.use('Agg')         # This is necessary to be able to use matplotlib on headless computers
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(-100, 100)
y = x**2

plt.plot(x, y)
plt.axis([-27.6, 33.3, 0, 1000])

figure = plt.gcf()
figure.savefig("test.svg")
figure.savefig("test.png")

html = """
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Test WeasyPrint</title>
  </head>
  <body>
    <h3>SVG</h3>
    <img src="test.svg" style="height: 100mm;">
    <h3>PNG</h3>
    <img src="test.png" style="height: 100mm;">
  </body>
</html>
"""

html_doc = HTML(string=html, base_url="./")
html_doc.write_pdf("test.pdf")
```

**Comment by jmidgren** [comment]
If it matters: I'm running Ubuntu 16.04 and have installed WeasyPrint through pip3 and other requirements according to your instructions.

Current versions of python packages:
```bash
$ pip3 list --user --format=columns
Package    Version
---------- -------
CairoSVG   2.1.1  
cffi       1.11.2 
cssselect2 0.2.1  
defusedxml 0.5.0  
pdfrw      0.4    
Pillow     4.3.0  
pip        9.0.1  
pycparser  2.18   
setuptools 36.6.0 
six        1.11.0 
tinycss2   0.6.1  
WeasyPrint 0.41   
```

**Comment by liZe** [comment]
Thank you for this bug report.

Could you please provide your `test.svg` file? Matplotlib tries to import `tkinter` but my Python version doesn't support it.

**Comment by jmidgren** [comment]
Thanks for the feed back!

I updated the example above using a special construct for the pyplot import. This works for me on headless machines, so hopefully it will make the example work in your environment too.

Here is the svg (zipped though, or github would not accept it): [test.zip](https://github.com/Kozea/WeasyPrint/files/1410885/test.zip)

**Comment by liZe** [comment]
That's actually a (quite embarrassing) bug in CairoSVG, I've open Kozea/CairoSVG#161.

**Comment by jmidgren** [comment]
Ok, I suspected it might have something to do with cairo svg. Thanks for filing the bug with the correct project!
