### ISSUE TITLE
Table align attribute center

### ISSUE THREAD

**Issue by adoreleon** [Kozea/WeasyPrint#527]
Hello,

When trying to generate a pdf with an table, it doesn't align using the element attribute align.

Here are my HTML so you can do some sort of test.

Obs.
I'm using ckeditor to create this html body, so i can't use the style inline to center this table because this is a very customizable document.

[question_table_not_aligned.txt](https://github.com/Kozea/WeasyPrint/files/1407248/question_table_not_aligned.txt)

**Comment by liZe** [comment]
Hi!

WeasyPrint doesn't support [deprecated presentational hints](https://www.w3.org/TR/html5/introduction.html#presentational-markup) … unless you use the `--presentational-hints` command-line parameter! You'll find extra info in the [documentation](http://weasyprint.readthedocs.io/en/latest/features.html#html).

**Comment by RafaelLinux** [comment]
Please, a question about this clarified "issue" ... Will be "--presentational-hints " parameter removed in future versions?

Thank you

**Comment by liZe** [comment]
> Will be "--presentational-hints " parameter removed in future versions?

No, we'll keep it!

**Comment by liZe** [comment]
:smile:
