### ISSUE TITLE
"Failed to draw an SVG image" when including SVG image with raster content

### ISSUE THREAD

**Issue by astraujums** [Kozea/WeasyPrint#529]
When generating PDF from a HTML file that includes an SVG image which, in turn, contains raster data in the form of `<image xlink:href="data:image/png;base64..." ... />`, an error is generated:
`ERROR: Failed to draw an SVG image at file:///C:/test/logo_error.svg : 'file_obj'`

The platform is Windows 10 Pro, 64-bit, Python 3.6.3 64-bit, GTK from `gtk3-runtime-3.22.21-2017-09-25-ts-win64`

Attached is a set of files that show the problem.

There are three versions of the image with corresponding HTML files that include it.
The PNG version and SVG version without raster content work fine but when trying to generate PDF from 
the file `test_svg_error.html` which uses the image `logo_error.svg`, the error occurs.

[weasyprint_raster_data_in_svg_bug.zip](https://github.com/Kozea/WeasyPrint/files/1440567/weasyprint_raster_data_in_svg_bug.zip)

**Comment by martijnthe** [comment]
I just ran into this issue as well.

```
WeasyPrint-0.41
macOS 10.12.6 (16G1036)
Python 3.6.2
Cairo @ 5a9dba9
```

FWIW, I just tried installing WeasyPrint from `master` and am not hitting this issue, but another problem... will open a separate ticket about that.

**Comment by martijnthe** [comment]
I found and fixed the bug, will put up a PR in a bit (still need to write a test case for it).
