### ISSUE TITLE
Using WeasyPrint with Pyinstaller

### ISSUE THREAD

**Issue by JauntyJJS** [Kozea/WeasyPrint#530]
Hi,

I tried to convert a python script that depends on weasyprint into an exe file using pyinstaller.
The good news is that pyinstaller is able to create a folder called "weasyprint" containing the necessary dependencies such as the css files in weasyprint/css and files in weasyprint/tests/resources.

However, the code in html.py assumes that these file dependencies are in the same directory as the exe files.
Around line 36
```python
if hasattr(sys, "frozen"): 
    root = os.path.dirname(sys.executable)
...
HTML5_UA_STYLESHEET = CSS(filename=os.path.join(root, 'css', 'html5_ua.css'))
HTML5_PH_STYLESHEET = CSS(filename=os.path.join(root, 'css', 'html5_ph.css'))
```
This may not be suitable if someone uses the pyinstaller to create a standalone exe file instead.

I suggest the following modification based on how pyinstaller works.

```python
if hasattr(sys, "frozen"):
    # MEIPASS explanation:
    # https://pythonhosted.org/PyInstaller/#run-time-operation
    root = getattr(sys, '_MEIPASS', None) #To handle standalone exe case 
    if not root:
        root = os.path.dirname(sys.executable) #To handle exe with file dependencies in the same directory
    root = os.path.join(root,'weasyprint')
else:
    root = os.path.dirname(__file__)
HTML5_UA_STYLESHEET = CSS(filename=os.path.join(root, 'css', 'html5_ua.css'))
HTML5_PH_STYLESHEET = CSS(filename=os.path.join(root, 'css', 'html5_ph.css'))
```

Hope this helps.

PS: 
Please note that weasyprint also depends on the file dependencies from the pyphen package as well. 
For this package, pyinstaller will not create a folder called "pyphen" by default.
To do so, please write in the *.spec file

```python
import pyphen
pyphen_root = os.path.dirname(pyphen.__file__)
pyphen_dictionaries = Tree(os.path.join(pyphen_root, 'dictionaries'), prefix = 'pyphen/dictionaries')
```

and put the variable pyphen_dictionary into 

```python
exe = EXE(pyz,
          pyphen_dictionaries,
          ... (other necessary inputs)
```

**Comment by liZe** [comment]
Fixed in #540.

**Comment by LoicGRENON** [comment]
This fix can also be done this way : https://stackoverflow.com/a/38734218/849022

However, the dist/css/html5_ua.css and dist/css/html5_ph.css should manually be created after building the executable with PyInstaller.

**Comment by pfctdayelise** [comment]
@JauntyJJS Sorry for commenting on an old issue, but are you able to share any details about using PyInstaller with WeasyPrint? Like a blog or a gist? It seems like it would be super valuable info to share, especially if you did it on Windows! :)

**Comment by Cheaterman** [comment]
@pfctdayelise I don't know if you checked the PR #540 but there's some additional info on there thanks to @johnnymetz. :-)
