### ISSUE TITLE
Guide user selection in generated PDF files

### ISSUE THREAD

**Issue by dmalan** [Kozea/WeasyPrint#531]
We're currently using WeasyPrint to render text files as PDFs but tend to experience unexpected behavior when it comes to selecting/highlighting text in those PDFs, particularly if some lines of text end up wrapping, at least with Preview on macOS. For instance, if the below, aka `demo.txt`,

```
demo demo demo demo demo demo demo demo demo demo

demo demo demo demo demo demo demo demo demo demo
    demo demo demo demo demo demo demo demo demo demo
    demo demo demo demo demo demo demo demo demo demo
    demo demo demo demo demo demo demo demo
    demo demo demo demo demo demo demo demo
    demo demo demo demo demo demo demo demo demo demo
    demo demo demo demo demo demo demo demo demo demo
    demo demo demo demo demo demo demo demo demo demo
demo demo demo demo demo demo demo demo demo demo
```

is rendered as a 5.5"x8.5" PDF, as with

```py
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers.special import TextLexer
from warnings import filterwarnings
filterwarnings("ignore", category=UserWarning, module="weasyprint")
from weasyprint import CSS, HTML

with open("demo.txt", "rb") as file:
    code = file.read().decode("utf-8", "ignore")
    string = highlight(code, TextLexer(), HtmlFormatter(linenos="inline", nobackground=True))

stylesheets = [
    CSS(string="@page { border-top: 1px #808080 solid; margin: .5in; padding-top: 1em; size: 5.5in 8.5in; }"),
    CSS(string="@page { @top-right { color: #808080; content: 'demo.txt'; padding-bottom: 1em; vertical-align: bottom; } }"),
    CSS(string="* { font-family: monospace; font-size: 10pt; margin: 0; white-space: pre-wrap; }"),
    CSS(string=".lineno { color: #808080; }"),
    CSS(string=".lineno:after { content: '  '; }")]

document = HTML(string=string).render(stylesheets=stylesheets)
document.write_pdf("demo.pdf")
```

the output, `demo.pdf`, is as expected, with some of the text wrapping (deliberately for demo's sake):

![screen shot 2017-11-08 at 12 36 23 pm](https://user-images.githubusercontent.com/788678/32564274-c18fd3a6-c481-11e7-8f29-50e781974609.png)

However, when trying to highlight/select lines in that PDF with Preview, as by clicking to the left of the top-left `1` and dragging right or down, it's not actually possible to select complete and contiguous lines:

![screen shot 2017-11-08 at 12 36 30 pm](https://user-images.githubusercontent.com/788678/32564280-c548b170-c481-11e7-9d31-3cdacbcbf293.png)

![screen shot 2017-11-08 at 12 36 36 pm](https://user-images.githubusercontent.com/788678/32564285-c8d911ae-c481-11e7-968c-33f909c6b062.png)

This might indeed just be an issue with Preview (or a challenge with PDFs more generally), but might there nonetheless be something we could do differently with our input to WeasyPrint to ensure that lines can be selected reliably, perhaps via tweaks to our HTML and/or CSS? We originally noticed this issue when "concatenating" WeasyPrint-generated PDFs side by side (cf. https://github.com/mstamy2/PyPDF2/issues/376), but we're not sure at which stage in our pipeline it might be ideal to redress.

If helpful, Pyments is currently outputting HTML like the below, which we're then feeding into WeasyPrint with the CSS above:

```html
<div class="highlight"><pre><span></span><span class="lineno"> 1 </span>demo demo demo demo demo demo demo demo demo demo
<span class="lineno"> 2 </span>
<span class="lineno"> 3 </span>demo demo demo demo demo demo demo demo demo demo
<span class="lineno"> 4 </span>    demo demo demo demo demo demo demo demo demo demo
<span class="lineno"> 5 </span>    demo demo demo demo demo demo demo demo demo demo
<span class="lineno"> 6 </span>    demo demo demo demo demo demo demo demo
<span class="lineno"> 7 </span>    demo demo demo demo demo demo demo demo
<span class="lineno"> 8 </span>    demo demo demo demo demo demo demo demo demo demo
<span class="lineno"> 9 </span>    demo demo demo demo demo demo demo demo demo demo
<span class="lineno">10 </span>    demo demo demo demo demo demo demo demo demo demo
<span class="lineno">11 </span>demo demo demo demo demo demo demo demo demo demo
</pre></div>
```
(We're seeing this behavior with `weasyprint 0.41` and `libcairo2 1.14.6-1` on Ubuntu 16.04.)

Thank you!

**Comment by liZe** [comment]
That would be really useful, but I'm not even sure that there's a theoretical solution to "how to handle text selection according to the HTML structure".

By the way, it may be at least possible to avoid the behavior of your last image, but it would probably need a lot of work for a result that may not always fit user's needs.

**Comment by liZe** [comment]
@dmalan @rhodon-jargon Did you try with the `--pdf-variant=pdf/ua-1` option? Maybe accessible PDFs give better results for selection.

**Comment by dmalan** [comment]
Hi @liZe, not sure if it's the result of a WeasyPrint change or macOS change, but as of WeasyPrint 59.0 and macOS 13.4.1, we're now seeing that same demo highlight as expected:

<img width="492" alt="Screenshot 2023-07-26 at 11 05 31 AM" src="https://github.com/Kozea/WeasyPrint/assets/788678/e321c35e-2407-468d-9cdd-bc537fe373e1">

Thank you!

**Comment by liZe** [comment]
> Hi @liZe, not sure if it's the result of a WeasyPrint change or macOS change, but as of WeasyPrint 59.0 and macOS 13.4.1, we're now seeing that same demo highlight as expected:

Cool!

Let’s keep this issue open until it works for @rhodon-jargon too.

**Comment by liZe** [comment]
@rhodon-jargon Please add a comment here if needed!
