### ISSUE TITLE
Python can't import weasyprint

### ISSUE THREAD

**Issue by McEwenTito** [Kozea/WeasyPrint#533]
WeasyPrint is installed and running in my virtualenv:
weasyprint --version
WeasyPrint version 0.26

But when I try to call in from python I get the following error:
python -m weasyprint.navigator
/home/tito/new/bin/python: No module named weasyprint

Environment:
Ubuntu 16.04LTS
python 2.7

**Comment by liZe** [comment]
WeasyPrint version 0.26 is really old, it's probably not what you've installed in a recent virtualenv. I suppose that you've installed it on your system a long time ago. `weasyprint` finds the executable on your system but your virtualenv's `python`can't see the module.

In your virtualenv, run `pip install --upgrade weasyprint`.

**Comment by TomasMiloCA** [comment]
I did "pip install --upgrade weasyprint" and I still cannot import the package. Any update to this? Thank you!

**Comment by liZe** [comment]
Hi!

> Any update to this?

The problem you have is not related to this old bug, but probably to a problem in the way you installed WeasyPrint. Following the [installation guide](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html) is the best way to get a working installation.
