### ISSUE TITLE
Add  footers with different content for different pages

### ISSUE THREAD

**Issue by ig-ksv** [Kozea/WeasyPrint#536]
Hello!
How can I add footers with different content for different pages? - for example -  for the last page I need to set footer with different content.

**Comment by liZe** [comment]
You can try [named pages](https://drafts.csswg.org/css-page-3/#using-named-pages). If it doesn't fit your needs, I'd need an example of what you're trying to do!

**Comment by liZe** [comment]
Named pages is definitely what you want.

**Comment by Tontyna** [comment]
Though, nabbing the ***last*** page is a challenge.

**Comment by liZe** [comment]
> Though, nabbing the _**last**_ page is a challenge.

That's a bug for the CSSWG: w3c/csswg-drafts#1110.
