### ISSUE TITLE
Line breaks not working on Windows

### ISSUE THREAD

**Issue by chesstrian** [Kozea/WeasyPrint#538]
Hi everyone,

I implemented a simple solution for a company, a user enter a document, the program in Django reads database and returns a bill. It has been working perfect on Ubuntu until now that the client asked to install the program on a Windows Server, I have no errors or warnings, but `<br>` tags are not rendered. Any hint where to look or what to test is welcome.

Thanks in advance.

**Comment by liZe** [comment]
Which version of Pango are you using? Pango 1.40.13 introduced a bug in line breaks, 1.40.14 (released today) fixes this problem.

If you get the problem with a Pango version different from 1.40.13, then it's probably a Windows-related bug that I've no idea how to debug without Windows…

**Comment by chesstrian** [comment]
Thanks @liZe for your answer.

We need to install [GTK](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer) for Windows which contains Pango, there we can see that current version is 1.40.11.

**Comment by chesstrian** [comment]
Error due to using `font-family` in the styles.

**Comment by liZe** [comment]
> Error due to using font-family in the styles.

Thanks a lot for taking the time to close this issue, you saved me a lot of time.
