### ISSUE TITLE
Pixbuf error: Unrecognized image file format

### ISSUE THREAD

**Issue by cheojeg** [Kozea/WeasyPrint#542]
Hello, I am working in Ubuntu with a project on Flask using Flask-WeasyPrint==0.5 and i trying to show some images in differents formats in a pdf file and works fine locally on Ubuntu, but when i deploy the project in a centos server (centos-release-6-9.el6.12.3.x86_64) happend the next error.

Failed to load image at https://www.interpol.int/var/interpol/cache/ws/2012-8982/wanted-GetThumbnail-56336592.jpg : Pixbuf error: Unrecognized image file format

Is possible show jpg images with centos or i have to convert all the images to png?

**Comment by liZe** [comment]
You have to install the gdk-pixbuf package to get JPEG support.

(Interpol?)

**Comment by cheojeg** [comment]
Thanks, i kwon that i need gdk-pixbuf, but in CentOs is just availables the next ones:

gdk-pixbuf2-devel.i686 : Development files for gdk-pixbuf
gdk-pixbuf2-devel.x86_64 : Development files for gdk-pixbuf
gdk-pixbuf2.i686 : An image loading library
gdk-pixbuf2.x86_64 : An image loading library

I installed all the options and still appearing the same error.

Yeah! interpol because i'm looking for bad guys to claim a reward.

**Comment by liZe** [comment]
Hmmmm… Unlike many other linux distributions, [CentOS' gdk-pixbuf package](https://centos.pkgs.org/6/puias-x86_64/gdk-pixbuf-0.22.0-38.puias6.x86_64.rpm.html) doesn't seem to rely explicitely on libjpeg. You probably need to install libjpeg or libjpeg-turbo.

**Comment by liZe** [comment]
@cheojeg Can I close this issue?

**Comment by cheojeg** [comment]
Well, I still have not the problem with CentOS 'gdk-pixbuf to JPEG support. I already install libjpeg or libjpeg-turbo but it do not work.

**Comment by cheojeg** [comment]
This is the error on CentOS on entos-release-6-9.el6.12.3.x86_64
symbol 'gdk_pixbuf_get_byte_length' not found in library 'libgdk_pixbuf-2.0.so': /usr/lib64/libgdk_pixbuf-2.0.so: undefined symbol: gdk_pixbuf_get_byte_length

What is the lastest version of gdk-pixbuf for CentOS?

**Comment by liZe** [comment]
> What is the lastest version of gdk-pixbuf for CentOS?

According to [this page](http://mirror.centos.org/centos/6/os/x86_64/Packages/), it's 2.24.1 for CentOS 6. But according to [this tutorial](http://lois.di-qual.net/blog/python-install-weasyprint-on-a-dedicated-webfaction-server/), GdkPixbuf >= 2.25 is needed.

I'll update the install page of the documentation to reflect the (reaaaaaaaaly old) needed versions of GdkPixbuf and Pango.
