### ISSUE TITLE
Add support for CSS Custom Properties

### ISSUE THREAD

**Issue by whitelynx** [Kozea/WeasyPrint#546]
This would allow CSS authors to define shared variables ("custom properties") and reference them using [the `var()` function](https://developer.mozilla.org/en-US/docs/Web/CSS/var).

See the [CSS Custom Properties for Cascading Variables Module Level 1](https://drafts.csswg.org/css-variables/) spec.

**Comment by LukasKlement** [comment]
Are there any updates on this ticket? What would be needed to build this feature?

In my eyes, this feature would be critical for more dynamic documents. Personally, I would use it to add user-specified variables (e.g. colours) in the template files in a :root {} declaration, and have static CSS files using these variables. This would avoid a lot of CSS overwriting in .html template files.

**Comment by liZe** [comment]
Syntax is now supported by [tinycss2](https://github.com/Kozea/tinycss2/commit/6cc2d1e7f2e1c616c103c88403a4e3ac273e3f7e).

**Comment by esmail** [comment]
Will the version of tinycss2 required here be bumped?

**Comment by liZe** [comment]
> Will the version of tinycss2 required here be bumped?

Yes, but having the syntax support is not enough. I have to add some code in WeasyPrint too!

**Comment by liZe** [comment]
I've open a branch supporting variables. Current work only works with very simple cases, but more will come (including tests of course).
