### ISSUE TITLE
images are not reflecting in pdf for ubuntu 14.04

### ISSUE THREAD

**Issue by deepak-ace12** [Kozea/WeasyPrint#556]
Hi,

I am trying to generate a pdf using weasyprint. I have installed everything as per the doc http://weasyprint.readthedocs.io/en/latest/install.html The pdf is working well on my mac locally but when I am trying to deploy it on server (Ubuntu 14.04), the pdf gets generated but the images are not printed on the pdf file.

**Comment by liZe** [comment]
Could you please provide an image that doesn't work for you on Ubuntu?

**Comment by deepak-ace12** [comment]
it's a png image, basically a logo. I also tried it with some random google images also...It worked with mac but it didn't work with ubuntu 14.04.

**Comment by deepak-ace12** [comment]
@liZe yes... I am using the same version of Cairo...
How did you solve it?

**Comment by liZe** [comment]
> @liZe yes... I am using the same version of Cairo...
> How did you solve it?

You can either use the latest git version of cairo or use 1.14.10.

**Comment by liZe** [comment]
Closing, as the bug is in Cairo…

**Comment by deepak-ace12** [comment]
I upgraded Ubuntu to 16.04...now png images are not coming..jpeg is working fine...
