### ISSUE TITLE
Invalid attachments

### ISSUE THREAD

**Issue by gigelu** [Kozea/WeasyPrint#558]
Hello

I am trying to attach a file to the pdf and when I try to save the attached file I am getting a 0 bytes file.
The code is this:
```
from io import BytesIO
from weasyprint import HTML

html = HTML(string='test')
with open('/tmp/test.pdf', mode='wb') as out_file:
    html.write_pdf(out_file, attachments=[BytesIO(b'attachment')])
```

The relevant part in the output is:
```
3 0 obj
<</Filter /FlateDecode /Length 18 /Params
  <</CheckSum <44290cefe42924d04a92d99428a95f27> /Size 10>> /Type
  /EmbeddedFile>>
stream
b'x\x9cK,)IL\xce\xc8M\xcd+\x01\x00\x16\xbc\x04*'
endstream
endobj
```

I don't think that the stream should be a python string (`b'...'`).
Any help in what may be the problem?

Thank you.

**Comment by dnezic** [comment]
I have the same problem, so I downgraded to version WeasyPrint==0.40, where the attachments work, at least using `<a rel=attachment ...` in HTML.

**Comment by gigelu** [comment]
Confirm, downgrading to 0.40 fixes the attachment.

**Comment by archatas** [comment]
I can confirm that with WeasyPrint 0.42 <link rel=attachment /> creates empty attachments.

**Comment by liZe** [comment]
Sorry, my mistake… I've added more tests to catch this, but generating and reading the PDF file with the same library makes a perfect garbage-in-garbage-out problem.
