### ISSUE TITLE
Emoji not being printed as expected

### ISSUE THREAD

**Issue by craiga** [Kozea/WeasyPrint#568]
I'm not sure if this is an issue with WeasyPrint, one of the libraries it depends upon, or something silly that I'm doing, but it appears that emoji aren't being rendered as you might expect.

I'd expect that each emoji character would be rendered one after the other as they are in a web browser. In the generated PDF, it appears that each emoji character is being mapped to something strange, then possibly being printed on top of each other?

HTML: http://www.craiga.id.au/emoji.html
PDF generated from that PDF: http://www.craiga.id.au/emoji.pdf

The code used to generate these files is at http://github.com/craiga/craiga.id.au.

**Comment by liZe** [comment]
I don't have the problem. I suppose that the font used to display emojis in your system is somehow broken, you may get different fallback fonts in a browser and in WeasyPrint. To be sure, add a font family that have these emojis to your `font-family: "Merryweather", serif`.

**Comment by craiga** [comment]
Hmm. When you say you don't have the problem, do you mean that you can render emoji in PDFs without issue, or do you mean that you don't see a problem in the PDF I linked to? Either way, this may be a Mac OS-specific issue.

I've tried including `'Apple Color Emoji'` to this list, but with no luck.

I even tried with this as the _only_ font—all the characters in the document were rendered as question marks in squares except for the emoji which are still being rendered strangely.

**Comment by liZe** [comment]
> When you say you don't have the problem, do you mean that you can render emoji in PDFs without issue

Exactly. The only problem I have is that emojis get rasterized.

[emoji.pdf](https://github.com/Kozea/WeasyPrint/files/1718002/emoji.pdf)

> Either way, this may be a Mac OS-specific issue.

Oh, OK. This [post](https://stackoverflow.com/questions/38064048/pango-color-glyphs) may help, using another font looks like the way to go.

**Comment by craiga** [comment]
Thanks for this. Tried installing [Noto Emoji](https://www.google.com/get/noto/) as a font locally and specifying it in my CSS, but not having much luck. Will keep trying and will report back.

**Comment by liZe** [comment]
@craiga Did you find a solution to your problem?

**Comment by craiga** [comment]
@liZe Unfortunately not. Tried a few things with the two Noto Emoji fonts installed via the standard Mac OS processes with no luck. I'm guessing it's got something to do with Mac OS.

**Comment by liZe** [comment]
@craiga Could you try recent versions of WeasyPrint, Pango and Cairo?

**Comment by craiga** [comment]
Hey @liZe, thanks for following up!

Things are better on macOS now!

Characters are no longer black and white, but it looks like the characters are just printed on top of each other. I added another test to the document, and it looks like it's because the characters have no width.

I've updated https://www.craiga.id.au/emoji.html and https://www.craiga.id.au/emoji.pdf with the latest results.

I'm using WeasyPrint version 0.42.3, Pango 1.42.4 and Cairo 1.6.0.

**Comment by craiga** [comment]
This appears to be fixed now! 🎉

PDF generated on macOS 10.14.2 using WeasyPrint 44, Pango 1.42.4 and Cairo 1.6.0.

**Comment by btsunjin** [comment]
This is a good case. But I found another problem, which reads as follows:
Using this string will trigger OOM.

**Comment by btsunjin** [comment]
This is a good case. But I found another problem, which reads as follows:
Using this string will trigger OOM.
