### ISSUE TITLE
Support full text-decoration syntax

### ISSUE THREAD

**Issue by mdekstrand** [Kozea/WeasyPrint#571]
WeasyPrint does not currently support the full `text-decoration` syntax (`text-decoration-line`, `text-decoration-style`, `text-decoration-color`, and `text-decoration` as a shorthand for them).

These are in the CSS Text Decoration Level 3 CR, and are [documented by Mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration) and supported by Firefox, Chrome, and (mostly) Safari.

**Comment by randomstuff** [comment]
I started a branch to try to add support for this.

**Comment by mdekstrand** [comment]
@randomstuff fantastic! If you want a real-world test case, this document is the reason I filed this issue: https://md.ekstrandom.net/cv

**Comment by liZe** [comment]
> @randomstuff fantastic! If you want a real-world test case, this document is the reason I filed this issue: https://md.ekstrandom.net/cv

Looks like [it works](https://github.com/Kozea/WeasyPrint/files/3178845/cv.pdf)!

As @randomstuff said in #855, we have small limitations (no wave, glitches with nested tags) but it should fit your needs!
