### ISSUE TITLE
New page-margin boxes layout algorithm

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/WeasyPrint#58]
Catch up with spec changes: http://dev.w3.org/csswg/css3-page/#margin-dimension

**Comment by galbwe** [comment]
@liZe Hi, I'd like to get started contributing to this project. I'm still familiarizing myself with the codebase, and am not 100% certain about which part of the code to modify to address this issue. I think I need to edit the ```compute_variable_dimension``` function in ```layout/pages.py```, based on a search for the w3 url. Is this on the right track? Thanks.

**Comment by liZe** [comment]
> Hi, I'd like to get started contributing to this project.

Thank you! Don't hesitate to ask if you have any questions, I'll do my best to help you.

> I think I need to edit the `compute_variable_dimension` function in `layout/pages.py`, based on a search for the w3 url. Is this on the right track?

Yes, it is.

In 2012, when @SimonSapin implemented the page-margins layout, the specification was this one:
https://www.w3.org/TR/2006/WD-css3-page-20061010/#margin-dimension

The algorithm was really hard to implement and didn't give good results. Simon decided to implement something else, and he proposed a replacement of the specification, based on what he implemented in WeasyPrint:
https://github.com/SimonSapin/css/blob/8c17fbe/margin-boxes-variable-dimension

This proposition was accepted, probably with some changes (I don't remember, maybe Simon does). So the first step is to find what's different between the current specification and the current implementation in `compute_variable_dimension`, and then fix these differences.

You can spend some time reading [Chapter 5.3 of the specification](https://www.w3.org/TR/css-page-3/#margin-dimension). It's totally normal to find it over-complicated at first :smile:, but it gets easier with time. [The algorithm](https://www.w3.org/TR/css-page-3/#variable-sizing) is close to the [current code](https://github.com/Kozea/WeasyPrint/blob/bb69424d811b39821697326ea0fe1d26fe540bc2/weasyprint/layout/pages.py#L182-L276), so it can be helpful to have both side by side to understand how it works.

I'll be happy to help, so feel free to ask anything.

**Comment by galbwe** [comment]
@liZe Thank you for the context, and for the speedy reply! I'll start working through the specs and reach out if I have any questions.

**Comment by liZe** [comment]
Closed by #1890.
