### ISSUE TITLE
Table rendering flaws

### ISSUE THREAD

**Issue by ivoronin** [Kozea/WeasyPrint#582]
# Source file
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.css" integrity="sha256-7GAtDQ79wTEOjhBKf70uBQG7A5yyb+8rigu07atXWDY=" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.10.0/github-markdown.css" integrity="sha256-qTBXiGmok0OwSTNA1uvNgoO6GSylS8Ty3TBjogwOxVo=" crossorigin="anonymous">
</head>
<body>
  <article class="markdown-body">
    <table>
      <thead>
        <tr>
          <th>Non numquam</th>
          <th>Lorem markdownum</th>
          <th>Duis aute</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Google Chrome</td>
          <td>Eaque ipsa quae ab illo inventore veritatis et
          quasi</td>
          <td>Cupiditate non provident, similique sunt in culpa qui
          officia deserunt mollitia.</td>
        </tr>
        <tr>
          <td>Mozilla Firefox</td>
          <td>Eaque ipsa quae ab illo inventore veritatis et
          quasi</td>
          <td>Cupiditate non provident, similique sunt in culpa qui
          officia deserunt mollitia.</td>
        </tr>
      </tbody>
    </table>
  </article>
</body>
</html>
```
# Expected result (rendered with [Prince](https://www.princexml.com/) 11.3)
![default](https://user-images.githubusercontent.com/1638389/36949557-260d66ca-1ffb-11e8-9852-e9b28ed8bc7f.png)
# Actual result (rendered with weasyprint 0.42.2)
![default](https://user-images.githubusercontent.com/1638389/36949560-32be510e-1ffb-11e8-9d97-5ec9e962322c.png)
# Discrepancies
  - Wrong word wrapping
  - Right table border is missing

**Comment by liZe** [comment]
Minimal use case:
```html
<style>
  body {
    word-wrap: break-word;
  }

  table {
    border-collapse: collapse;
    display: block;
    width: 100%;
    overflow: auto;
  }

  th, td {
    border: 1px solid;
  }
</style>
<table>
  <tbody>
    <tr>
      <td>Non numquam</td>
      <td>Eaque ipsa quae ab illo inventore veritatis et quasi</td>
      <td>Cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia.</td>
    </tr>
  </tbody>
</table>
```

- The word is broken because of `word-wrap: break-word`, but in table layout this seems to be ignored for some reason. It's more an implementation detail than a real bug in WeasyPrint IMHO, but I'll try to fix this if it's easy.
- The right border is missing because of `table { display: block; width: 100%; overflow: auto }`. That's a bug I have to fix.

**Comment by liZe** [comment]
For the record, [the spec](https://drafts.csswg.org/css-text-3/#overflow-wrap-property) says:
> Soft wrap opportunities introduced by overflow-wrap: break-word are not considered when calculating min-content intrinsic sizes.

**Comment by liZe** [comment]
![capture d ecran de 2018-03-05 01-27-19](https://user-images.githubusercontent.com/952243/36952763-69255ff8-2014-11e8-9580-17f4006bdd22.png)

(Don't expect future bugs to be fixed that fast :wink:)
