### ISSUE TITLE
Installing on clean debian stretch:

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#584]
I did following:

1. `apt-get install -y --no-install-recommends build-essential python3-dev python3-pip python3-cffi  libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info`
2. `pip` command is missing, we must use `pip3`: `pip3 install WeasyPrint`

```
Collecting WeasyPrint
  Downloading WeasyPrint-0.42.2-py3-none-any.whl (296kB)
Collecting pdfrw>=0.4 (from WeasyPrint)
  Downloading pdfrw-0.4-py2.py3-none-any.whl (69kB)
Collecting cssselect2>=0.1 (from WeasyPrint)
  Downloading cssselect2-0.2.1-py2.py3-none-any.whl
Collecting Pyphen>=0.8 (from WeasyPrint)
  Downloading Pyphen-0.9.4-py2.py3-none-any.whl (1.9MB)
Collecting html5lib>=0.999999999 (from WeasyPrint)
  Downloading html5lib-1.0.1-py2.py3-none-any.whl (117kB)
Collecting cairocffi>=0.5 (from WeasyPrint)
  Downloading cairocffi-0.8.0.tar.gz (79kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
```

So I guess the `python3-setuptools` are missing in the https://github.com/Kozea/WeasyPrint/blob/master/docs/install.rst.

3. `apt-get install python3-setuptools`
4. `pip3 install WeasyPrint`

```
Collecting WeasyPrint
  Downloading WeasyPrint-0.42.2-py3-none-any.whl (296kB)
Collecting Pyphen>=0.8 (from WeasyPrint)
  Downloading Pyphen-0.9.4-py2.py3-none-any.whl (1.9MB)
Collecting cairocffi>=0.5 (from WeasyPrint)
  Downloading cairocffi-0.8.0.tar.gz (79kB)
Requirement already satisfied: cffi>=0.6 in /usr/lib/python3/dist-packages (from WeasyPrint)
Collecting html5lib>=0.999999999 (from WeasyPrint)
  Downloading html5lib-1.0.1-py2.py3-none-any.whl (117kB)
Collecting CairoSVG>=1.0.20; python_version >= "3.0" (from WeasyPrint)
  Downloading CairoSVG-2.1.3-py3-none-any.whl (101kB)
Collecting pdfrw>=0.4 (from WeasyPrint)
  Downloading pdfrw-0.4-py2.py3-none-any.whl (69kB)
Collecting cssselect2>=0.1 (from WeasyPrint)
  Downloading cssselect2-0.2.1-py2.py3-none-any.whl
Collecting tinycss2>=0.5 (from WeasyPrint)
  Downloading tinycss2-0.6.1-py2.py3-none-any.whl (61kB)
Collecting webencodings (from html5lib>=0.999999999->WeasyPrint)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl
Collecting six>=1.9 (from html5lib>=0.999999999->WeasyPrint)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting defusedxml (from CairoSVG>=1.0.20; python_version >= "3.0"->WeasyPrint)
  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
Collecting pillow (from CairoSVG>=1.0.20; python_version >= "3.0"->WeasyPrint)
  Downloading Pillow-5.0.0-cp35-cp35m-manylinux1_x86_64.whl (5.9MB)
Building wheels for collected packages: cairocffi
  Running setup.py bdist_wheel for cairocffi: started
  Running setup.py bdist_wheel for cairocffi: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g2ww1udq/cairocffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpgycjro20pip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for cairocffi
  Running setup.py clean for cairocffi
Failed to build cairocffi
Installing collected packages: Pyphen, cairocffi, webencodings, six, html5lib, tinycss2, cssselect2, defusedxml, pillow, CairoSVG, pdfrw, WeasyPrint
```

Don't know what else we can do.

**Comment by liZe** [comment]
Thank you for reporting this issue.

> Don't know what else we can do.

You need to install the python3-wheel package. I've fixed the documentation.

**Comment by RafaelLinux** [comment]
I have near same problem. I followed the instructions in  http://weasyprint.readthedocs.io/en/stable/install.html  for Debian Stretch (doesn't include nothing about python3-wheel nor pip3) and launched a lot of errors:
`ting WeasyPrint
Exception:
Traceback (most recent call last):                                                                                                                
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 138, in _new_conn                               
    (self.host, self.port), self.timeout, **extra_kw)                                                                                             
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 75, in create_connection                   
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):                                                                        
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo                                                                                   
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):                                                                       
socket.gaierror: [Errno -2] Nombre o servicio desconocido                                                                                         

During handling of the above exception, another exception occurred:                                                                               

Traceback (most recent call last):                                                                                                                
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen                             
    chunked=chunked)                                                                                                                              
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 350, in _make_request                       
    self._validate_conn(conn)                                                                                                                     
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 837, in _validate_conn                      
    conn.connect()                                                                                                                                
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 281, in connect                                 
    conn = self._new_conn()                                                                                                                       
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 147, in _new_conn                               
    self, "Failed to establish a new connection: %s" % e)                                                                                         
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed2ba31ba8>: Failed to establish a new connection: [Errno -2] Nombre o servicio desconocido                                                                    

During handling of the above exception, another exception occurred:                                                                               

Traceback (most recent call last):                                                                                                                
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main                                                                     
    status = self.run(options, args)                                                                                                              
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run                                                                 
    wb.build(autobuilding=True)                                                                                                                   
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build                                                                          
    self.requirement_set.prepare_files(self.finder)                                                                                               
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files                                                            
    ignore_dependencies=self.ignore_dependencies))                                                                                                
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file                                                            
    require_hashes                                                                                                                                
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link                                                        
    self.link = finder.find_requirement(self, upgrade)                                                                                            
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement                                                               
    all_candidates = self.find_all_candidates(req.name)                                                                                           
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates                                                            
    for page in self._get_pages(url_locations, project_name):                                                                                     
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages                                                                     
    page = self._get_page(location)                                                                                                               
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page                                                                      
    return HTMLPage.get_page(link, session=self.session)                                                                                          
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page                                                                       
    "Cache-Control": "max-age=600",                                                                                                               
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get                                     
    return self.request('GET', url, **kwargs)                                                                                                     
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in request                                                                     
    return super(PipSession, self).request(method, url, *args, **kwargs)                                                                          
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request                                 
    resp = self.send(prep, **send_kwargs)                                                                                                         
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send                                    
    r = adapter.send(request, **kwargs)                                                                                                           
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send                              
    resp = super(CacheControlAdapter, self).send(request, **kw)                                                                                   
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send                                    
    timeout=timeout                                                                                                                               
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen                             
    _stacktrace=sys.exc_info()[2])                                                                                                                
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment                               
    total -= 1                                                                                                                                    
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'  `

So, what's the matter here????

**Comment by return42** [comment]
My experience is, that this problem resists.  What I do on a clean ubuntu (debian):

    $ sudo apt-get install build-essential python3-dev python3-pip python3-setuptools \
        python3-wheel  python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 \
        libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
    ...
    $ python3 -m venv ./venv
    ...
    $ .  ./venv/bin/activate
    (venv)$ pip install WeasyPrint
    ...
    Collecting cairocffi>=0.9.0 (from WeasyPrint)
```
  Using cached https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz
  Requested cairocffi>=0.9.0 from https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz#sha256=f1c0c5878f74ac9ccb5d48b2601fcc75390c881ce476e79f4cfedd288b1b05db (from WeasyPrint), but installing version None
    ...
    
Building wheels for collected packages: cairocffi, pycparser
  Running setup.py bdist_wheel for cairocffi ... error
  Complete output from command /x/share/test123/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5_zk82n9/cairocffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpq8f9lgl0pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for cairocffi
  Running setup.py clean for cairocffi
  Running setup.py bdist_wheel for pycparser ... error
  Complete output from command /x/share/test123/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5_zk82n9/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpedzgs5rwpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pycparser
  Running setup.py clean for pycparser
Failed to build cairocffi pycparser
Installing collected packages: Pyphen, webencodings, six, html5lib, setuptools, tinycss2, cssselect2, pycparser, cffi, cairocffi, defusedxml, pillow, CairoSVG, WeasyPrint
  Found existing installation: setuptools 39.0.1
    Uninstalling setuptools-39.0.1:
      Successfully uninstalled setuptools-39.0.1
  Running setup.py install for pycparser ... done
  Running setup.py install for cairocffi ... done
Successfully installed CairoSVG-2.4.2 Pyphen-0.9.5 WeasyPrint-49 cairocffi-1.1.0 cffi-1.12.3 cssselect2-0.2.2 defusedxml-0.6.0 html5lib-1.0.1 pillow-6.1.0 pycparser-2.19 setuptools-41.2.0 six-1.12.0 tinycss2-1.0.2 webencodings-0.5.1
```

    (venv)$  pip --version
    pip 9.0.1 from /x/share/test123/venv/lib/python3.6/site-packages (python 3.6)

So I gave it a new try, adding a pip upgrade in the venv

    (venv)$ deactivate 
    $ rm -rf ./venv

    $ python3 -m venv ./venv
    ...
    $ .  ./venv/bin/activate
    (venv)$ pip install --upgrade pip
    ...
    (venv)$ pip --version
    pip 19.2.3 from /x/share/test123/venv/lib/python3.6/site-packages/pip (python 3.6)
    (venv)$ pip install WeasyPrint
    ...
```

Collecting WeasyPrint
 ...
Collecting cairocffi>=0.9.0 (from WeasyPrint)
  Using cached https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz
  WARNING: Requested cairocffi>=0.9.0 from https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz#sha256=f1c0c5878f74ac9ccb5d48b2601fcc75390c881ce476e79f4cfedd288b1b05db (from WeasyPrint), but installing version file-.cairocffi-VERSION
...
ERROR: weasyprint 49 has requirement cairocffi>=0.9.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.
...
```

I do not understand, whats going wrong with the version number in **but installing version file-.cairocffi-VERSION**
