### ISSUE TITLE
[0.42.2 py2] Freeze with invalid image

### ISSUE THREAD

**Issue by voidus** [Kozea/WeasyPrint#588]
Script to reproduce:

```python
import weasyprint
import tempfile


temp_dir = tempfile.mkdtemp()
with open(temp_dir + '/invalid.png', 'w') as f:
    f.write(b'not a valid image')

html = '<html><head></head><body><img src="file://{}/invalid.png"></body></html>'.format(temp_dir)
writer = weasyprint.HTML(string=html)
with open('/dev/null', 'w') as output:
    writer.write_pdf(output)
```

This doesn't happen with python3, so I'm not sure if you want to fix it, but I spent the better part of the afternoon tracking this down. I hope nobody has to do that again :+1: 

Update: Just had a chat with a colleague and this doesn't happen for them. I am on arch Linux, so this might be a problem with never (or broken?) cairo or whatever version.

**Comment by liZe** [comment]
Thank you for this report! That's a [bug in cairo 1.14.12 and 1.15.10](https://bugs.freedesktop.org/show_bug.cgi?id=104325), fixed in their master branch but unfortunately not in a release yet!
