### ISSUE TITLE
Absolutely positioned element stays on the previous page

### ISSUE THREAD

**Issue by janek37** [Kozea/WeasyPrint#591]
Consider this example:

```
<!DOCTYPE html>
<html>
  <head>
    <style>
      @page {
        size: A4;
        margin: 1.5cm;
      }

      div {
        border: 1mm solid;
      }

      .filler {
        width: 100%;
        height: 20cm;
        border-color: yellow;
      }

      .main {
        position: relative;
        width: 100%;
        border-color: blue;
      }

      .absolute {
        position: absolute;
        top: 0;
        left: 0;
        border-color: red;
        width: 1cm;
        height: 1cm;
      }

      .long {
        margin-left: 1.5cm;
        width: 15cm;
        height: 10cm;
        border-color: green;
      }
    </style>
  </head>
  <body>
    <div class="filler"></div>
    <div class="main">
      <div class="absolute"></div>
      <div class="long"></div>
    </div>
  </body>
</html>
```

This is what it looks like converted with WeasyPrint 0.42.2:
![test pdf](https://user-images.githubusercontent.com/4113233/38028619-becc9962-3293-11e8-9fb4-c101c31a7dcf.png)

For reference, this is what comes out of Prince (free version):
![prince pdf](https://user-images.githubusercontent.com/4113233/38028627-c48c207a-3293-11e8-9e2c-684f0fdf659f.png)

As you can see, in WeasyPrint the absolute element as well as the top border stay on the previous page when they should be on the next page with the rest of `div.main`. Note: the top border is positioned properly when the absolute element is removed.

**Comment by Tontyna** [comment]
Print Preview in my Browser (Pale Moon) paginates the sample like this:
![palemoon](https://user-images.githubusercontent.com/35614937/37790614-f42269fa-2dfe-11e8-8967-2d9d9b5483bd.png)
WeasyPrint pagination is buggy, but it's debatable whether Prince does it right ;)

**Comment by liZe** [comment]
> WeasyPrint pagination is buggy, but it's debatable whether Prince does it right ;)

Exactly. Having the blue box on a separate page (as Prince does) is an implementation detail that is not in the CSS specification AFAIK.

The "real" problem in WeasyPrint is the missing blue and green borders on the first page. You can find [another example on the W3C testing suite](http://test.weasyprint.org/suite-css21/chapter13/section2/test7/), where the purple border should be visible from the top to the bottom of the pages.

This problem is not directly related to the `position: absolute / relative` property, it also happens in normal flow. It's a very old bug that should be surprisingly easy to fix: at the end of the page, we have to increase the size of split boxes to make them reach the bottom of the page.

**Comment by janek37** [comment]
> It's a very old bug that should be surprisingly easy to fix: at the end of the page, we have to increase the size of split boxes to make them reach the bottom of the page.

Do you mean that in my example everything would be fine if only the border on the first page extended to the bottom? I don't think so, in my opinion the red frame should be next to the green one and not on separate pages.

**Comment by liZe** [comment]
> Do you mean that in my example everything would be fine if only the border on the first page extended to the bottom?

I don't know if would be fine, but AFAIK it would be right according to the spec.

> I don't think so, in my opinion the red frame should be next to the green one and not on separate pages.

In my opinion we should read [CSS Fragmentation](https://www.w3.org/TR/css-break-3/) to not rely on our opinions anymore :wink:.

**Comment by janek37** [comment]
I admit that I don't have resources to read and understand the standard. But I want to be able to make boxes next to each other and I can't see how it's a good idea to make one of them jump to the next page while the first one stays. If it can't be fixed, I have to move from WeasyPrint and find something that can do this.

**Comment by liZe** [comment]
> The "real" problem in WeasyPrint is the missing blue and green borders on the first page. You can find [another example on the W3C testing suite](http://test.weasyprint.org/suite-css21/chapter13/section2/test7/), where the purple border should be visible from the top to the bottom of the pages.

This problem is fixed.

> In my opinion we should read [CSS Fragmentation](https://www.w3.org/TR/css-break-3/) to not rely on our opinions anymore.

The spec says that we can break:
> Between the content edge of a block container box and the outer edges of its child content (margin edges of block-level children or line box edges for inline-level children) if there is a (non-zero) gap between them.

As there's no gap between the blue and the green boxes, we can't break here.
