### ISSUE TITLE
Add support of element() and running()

### ISSUE THREAD

**Issue by hajarghaem** [Kozea/WeasyPrint#598]
Dear,
I tried to load the content of an html tag with specific class via css in a @top-right of the header of the pdf file using weasyprint. Something like https://www.w3.org/TR/css-gcpm-3/#funcdef-running .
But it gives me a warning: Ignored 'content: element(heading) , invalid value . Also the same warning for poison: running(heading).
Could you please let me know if it is a supported feature or not?

Thanks in advance,
Kind regards,
Hajar

**Comment by Tontyna** [comment]
As the warning says: `element()` and `running()` not (yet?) supported by WeasyPrint.

**Comment by liZe** [comment]
Fixed by #882.
