### ISSUE TITLE
rendering problems and warning about cairo and pango versions 

### ISSUE THREAD

**Issue by amineparis** [Kozea/WeasyPrint#602]
I get this with some rendering issues (like borders not showing)

```
There are known rendering problems with Cairo <= 1.14.0
  warnings.warn('There are known rendering problems with Cairo <= 1.14.0')
/usr/local/lib/python3.6/site-packages/weasyprint/fonts.py:43: UserWarning: @font-face support needs Pango >= 1.38
  warnings.warn('@font-face support needs Pango >= 1.38')

```

Any ideas how to fix it ?

**Comment by liZe** [comment]
> Any ideas how to fix it ?

Installing a recent version of Cairo is mandatory to get correct renderings. You should upgrade Cairo.

**Comment by liZe** [comment]
@amineparis Can I close this issue?

**Comment by amineparis** [comment]
you would better change weasyprint dependencies since cairo was automatically installed from weasyprint dependencies

**Comment by liZe** [comment]
> you would better change weasyprint dependencies since cairo was automatically installed from weasyprint dependencies

No, it was not. Cairo is not a Python package and cannot be automatically by pip, you had to install it using your OS package manager (or it was already installed).

CairoSVG and CairoCFFI are Python packages installed by pip, but they're not Cairo itself :wink:.
