### ISSUE TITLE
based on the different css style sometimes some of contents in two columns are not in the pdf

### ISSUE THREAD

**Issue by hajarghaem** [Kozea/WeasyPrint#605]
Dear,
I have really short html file. I try to show some parts of its content in 2 columns. But based on different css styles, I see sometimes that the generated pdf does not cotains some of the contents of 2 columns divs. 
Is there specific trick to show the content always in the pdf?

**Comment by Tontyna** [comment]
Could you provide an example html/pdf?

**Comment by hajarghaem** [comment]
@Tontyna I will provide an example and send it here soon.

**Comment by vindarel** [comment]
Hello @hajarghaem, how about this example ? I may hit the same issue but I have difficulties reproducing it.

**Comment by liZe** [comment]
@hajarghaem @vindarel I'm closing this issue for now, but please reopen it as soon as you can get a sample to reproduce your problem.
