### ISSUE TITLE
No space after inside list markers

### ISSUE THREAD

**Issue by gsnedders** [Kozea/WeasyPrint#608]
```
<ul style="list-style-position: inside"><li>foo
```

This produces "•foo". Per CSS Counter Styles and CSS Lists, it should be "• foo" (which matches what every browser does).

**Comment by Tontyna** [comment]
Cannot reproduce the bug. What's your version of WeasyPrint?

**Comment by gsnedders** [comment]
WeasyPrint version 0.42.3

And, uh, it should be `inside` and not `inline` (as WeasyPrint rightly warns, `inline` is an invalid value.

**Comment by Tontyna** [comment]
Ah, right you are. Now I don't see the space, too.

**Comment by Tontyna** [comment]
The above PR only fixes the space issue. 

Still wrong (and not as easy to fix as the missing space):

- The marker position of lists styled with `direction: rtl; list-style-position: inline` 
- The dot-position of numbered list markers styled with `direction: rtl`
