### ISSUE TITLE
Form/Form Fields

### ISSUE THREAD

**Issue by schacki** [Kozea/WeasyPrint#61]
Hi all,
it would be really helpful to me, if any form input fields would be transformed to fillable input fields in the PDF document. To me it seems like this feature would be missing. Is that correct? If so, are there any plans to add this feature?
Regards,
Juergen

**Comment by MarZab** [comment]
And while someone is doing that I would like to have Digital Signature Fields too. :)

**Comment by djit** [comment]
+1000 for Digital Signature: this will be the killer feature for me.

**Comment by liZe** [comment]
> Does anyone feel like reading the PDF spec to figure this out?

Anyone? :wink:

**Comment by hicham-elmansouri** [comment]
Hi All,
Any update on this? I can try if it's strill pending.

**Comment by liZe** [comment]
Hi @hicham-elmansouri,

Sorry, there's no update on this. But it's probably no that hard to fix it, even if it may be a bit long and painful.

Here are the steps if you're interested in fixing this issue:
- Add a method gathering the form fields, just like it's done for anchors in `Document.resolve_links` (in `document.py`).
- Call this method in `pdf.py` to build the list of the fields positions (in `prepare_metadata`).
- Read the [PDF documentation](https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf) and find how we can create form fields (probably in 8.6).
- Add the form fields in the PDF (in `pdf.py`, in the `write_pdf_metadata` function).

Good luck!

**Comment by liZe** [comment]
If we use [pdfrw](https://github.com/Kozea/WeasyPrint/tree/pdfrw), the 4th point that was the hard part is no really easier.

Anyone interested?

**Comment by rdwrt** [comment]
any updates?

**Comment by liZe** [comment]
> any updates?

No. If anyone is interested, [my previous comment](https://github.com/Kozea/WeasyPrint/issues/61#issuecomment-301051989) is the way to go!

**Comment by liZe** [comment]
> I might give it a shot. Should I still follow [this](https://github.com/Kozea/WeasyPrint/issues/61#issuecomment-301051989)?

Here are the new steps:
- Add a method gathering the form fields, just like it's done for anchors in `Document.resolve_links` (in `document.py`).
- Call this method at the end of `Document.write_pdf` to build the list of the fields positions.
- Read the [PDF documentation](https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf) and find how we can create form fields (probably in 8.6).
- Add the form fields in the PDF at the end of `Document.write_pdf`.

**Comment by Kaos-Industries** [comment]
Also really need this feature, it's crucial for my documents to be electronically signable, and the only solutions that I know of for doing this are proprietary, like Adobe Acrobat.

**Comment by danfitz36** [comment]
Another +1 for this feature, would love to see it happen

**Comment by grewn0uille** [comment]
Hello!

If you’re interested in forms, we created a [short survey](https://app.evalandgo.com/s/index.php?id=JTk4cCU5NG8lOUQlQUQ%3D&a=JTk3biU5M2glOUMlQUI%3D) where you can give a boost to this feature and help us to improve WeasyPrint 😉

Vote for it!

**Comment by grewn0uille** [comment]
Hello!

As it’s soon our 2-year anniversary as CourtBouillon, we opened a [short survey](https://thym.courtbouillon.org/1) to know more about your expectations.
Don’t hesitate to support this feature and give it a boost 🚀!

The survey will be opened until October 10th.
