### ISSUE TITLE
flex-flow: row not working

### ISSUE THREAD

**Issue by jpabbuehl** [Kozea/WeasyPrint#613]
Hi.

I am rendering A4 document from html to pdf. I am using flexbox to render three items in a row as shown here [minimal example](http://scratchpad.io/responsible-death-5327)

Any browser correctly displays the html markup, but weasyprint can't. The items are always displayed vertically on top of each other.

Is flexible fully compatible now ? 
Is the following supported ?
```
display: flex;
flex-flow: row nowrap;
```
(flex-direction: row doesnt work either)

Thank you in advance
Jean-Paul

Version:
Windows 10
python 3.6
WeasyPrint0.42.3

**Comment by liZe** [comment]
Hello,

Flexbox support has been added in the current git version of WeasyPrint, it should work with your example.

I'd be glad to have some real-life tests, so if you can test the git version don't hesitate to open issues if you find some bugs (and you probably will)!

**Comment by liZe** [comment]
Hello @jpabbuehl, can I help you to solve this issue?

**Comment by Tontyna** [comment]
minimal example renders fine with current master branch
