### ISSUE TITLE
SVG Image partially rendered

### ISSUE THREAD

**Issue by andreaolivato** [Kozea/WeasyPrint#616]
Hi,

We are building a PDF containing Charts previously generated in SVG. The rendering works only partially, with a chunk of the image completely missing. 

.svg image: 
![screenshot from 2018-04-13 10-16-24](https://user-images.githubusercontent.com/100728/38713442-bcee9524-3f03-11e8-8dd7-db7e307a10d6.png)

.pdf rendering:
![screenshot from 2018-04-13 10-16-55](https://user-images.githubusercontent.com/100728/38713457-d143f884-3f03-11e8-867b-1826f7badd75.png)

Also attaching the source .svg
[demographics.zip](https://github.com/Kozea/WeasyPrint/files/1905580/demographics.zip)

The .svg image is simply included with an image tag
`<img src="path_to_svg.svg" style="width:100%" />`

There is no other element overlapping, is not contained in a parent div and extends to 100% of its width.

Working with Python 3.7.0b2 on Linux

Modules: 
> boto3==1.6.23
> botocore==1.9.23
> cairocffi==0.8.0
> CairoSVG==2.1.3
> certifi==2018.1.18
> cffi==1.11.5
> chardet==3.0.4
> cssselect2==0.2.1
> decorator==4.2.1
> defusedxml==0.5.0
> docutils==0.14
> freeze==1.0.10
> html5lib==1.0.1
> idna==2.6
> ipython-genutils==0.2.0
> jmespath==0.9.3
> jsonschema==2.6.0
> jupyter-core==4.4.0
> nbformat==4.4.0
> pdfrw==0.4
> Pillow==5.1.0
> plotly==2.5.1
> pycparser==2.18
> PyMySQL==0.8.0
> Pyphen==0.9.4
> python-dateutil==2.6.1
> pytz==2018.3
> requests==2.18.4
> s3transfer==0.1.13
> six==1.11.0
> tinycss2==0.6.1
> traitlets==4.3.2
> urllib3==1.22
> WeasyPrint==0.42.3
> webencodings==0.5.1

**Comment by liZe** [comment]
I've updated the documentation and added a warning in code when users have cairo < 1.15.4.
