### ISSUE TITLE
Font-family with fallback values break margins on windows.

### ISSUE THREAD

**Issue by romaia** [Kozea/WeasyPrint#62]
I noticed that when I specify font-family with more than one value, it will break the elements margins on windows (To be honest, I have being testing using wine). Happens with weasyprint 0.15 and 0.16 (I could not install 0.17 under wine yet).

```html
<html><head>
    <style>
      @page {size: 500px ; background-color: white; }
      .without { font-family: serif; } 
      .with { font-family: serif, sans-serif; } 
      h1 { margin: 0; } 
    </style>
</head><body>
      <div id="title" class="without">
        <h1>Without fallback</h1>
        <span class="subtitle">Subtitle</span>
      </div>

      <div style="height: 50px"></div>

      <div id="title" class="with">
        <h1>With fallback</h1>
        <span class="subtitle">Subtitle</span>
      </div>
</html>
```

On ubuntu:
![linux](https://f.cloud.github.com/assets/428053/290756/537c34c6-92f0-11e2-8fa6-2f7a7e65f754.png)

On windows:
![win](https://f.cloud.github.com/assets/428053/290757/57419830-92f0-11e2-9127-fe41fc3e1362.png)

On wine:
gtk version: (2, 28, 3)
cairo version: 1.8.10

**Comment by liZe** [comment]
Probably fixed now that #37 is fixed.
