### ISSUE TITLE
text and formatting lost / not rendered to pdf, using paste into Django admin

### ISSUE THREAD

**Issue by addsimm** [Kozea/WeasyPrint#634]
I have a Django website and WeasyPrint is working fine in nearly all instances, rendering a pdf and displaying it on the website from a textfield in a Django model; however, every so often -- about one time in forty, a user's document is rendered oddly, with missing text and random line breaks:

![screen shot 2018-06-05 at 2 08 04 pm](https://user-images.githubusercontent.com/2389450/41002889-e62672a0-68c9-11e8-9f2e-0a726f95abac.png)

![screen shot 2018-06-05 at 2 07 37 pm](https://user-images.githubusercontent.com/2389450/41002890-e63ec56c-68c9-11e8-917f-939fb3693618.png)

one renders fine and one not so much

I am not sure how to begin debugging this -

what I have discovered is that replacing the text in the Django admin's text field, ie stripping out the html or making it much shorter, nearly always resolves the problem; however going back to the original text causes the problem to reappear, and I cannot trace it to any particular tag or other content in the textfield.

Please let me know what information you need and I will be glad to provide it.

**Comment by Tontyna** [comment]
Not knowing nothing about Django, but when you say "stripping the HTML solves the problem", I assume the culprit is somewhere in the HTML.
Could you provide the HTML of *A Marine's Perspective*?

**Comment by addsimm** [comment]
its not so much stripping the tags - its replacing the content of the textfield.

So the problem (and successful renders) seems to be unrelated to the length of the text, any tags present as well as the escape characters I have tested. I have also tried any number of ways to "purify" the text by removing escaped characters, etc.  It also appears on my local dev server as well as the production site, which have completely different stacks.

Here is a piece of the file that won't work:

<p>It is interesting how perspective gives us opinions that guide Our life choices. Even during adolescent years the observations we make develop the perspective we have in life and ultimately guide us down the path that leads us to the same place 6 feet under. Although we all end up from where we came, it is how We choose to live our story that differentiates us as human beings. My entire life I&rsquo;ve had fortune much more enjoyable than any of my peers. My parents are married, I&rsquo;m an only child, I live in a good neighborhood, and I come from a reasonably solid upper middle class household.&nbsp; </p>

if if you were to change this to:

    test test test

or even

   <p>test test test&nbsp; </p>

it works fine

**Comment by Tontyna** [comment]
Looks like the `vince.poem.txt` is what you enter in the Django admin text field. And the extras, like the title, the authors' name and the decoration are added by Django.
That means: Django constructs the HTML, adds styling and finally hands it over to WeasyPrint.

I suspect: Django or one of its modules (??) has got the hiccups and delivers an already wrecked HTML (or styling)... Can you (on your dev server) somehow snatch the final HTML? Maybe insert a `print` or `file.write()` right before WeasyPrint is invoked?

But first of all I'd check whether the poem's text isn't already corrupted in the database -- there is a database, isnt it?

**Comment by addsimm** [comment]
I'm so sorry - my partner deleted the problematic poem and now I can't replicate the error - I guess that is a good thing.  If it recurs, I will contact you again.  Thanks for your help

**Comment by Tontyna** [comment]
BTW: Are there statistics on issues caused by bugs in Cairo/Pango?

**Comment by liZe** [comment]
> BTW: Are there statistics on issues caused by bugs in Cairo/Pango?

About 20-25% of issues talk about Cairo and 15-20% about Pango, but it doesn't mean that they're caused by Cairo/Pango.

**Comment by liZe** [comment]
> An update: Weasyprint is working fine on my end now; the problem was that Pango / Cairo was updated on my server but not inside the Docker container - thanks for your help all

Good to know! Thanks for your answer.
