### ISSUE TITLE
Problem with justify text and comma in end of line

### ISSUE THREAD

**Issue by manuthema** [Kozea/WeasyPrint#637]
Sometimes with justified text, the spaces between words are not well calculated and there is a space at the end of the line. This occurs when the line break coincides between a word and a comma. Previously (weasyprint 0.36) it happened that separated the comma from the word

I attach the minimum html with which I have been able to reproduce the problem.

I have the following versions:
weasyprint: 0.42.3
pango: 1.42.01

<img width="903" alt="texto justificado" src="https://user-images.githubusercontent.com/1440972/41153777-12e4f4d8-6b18-11e8-8ac9-bba6a779115a.png">

[pruebaPDF.txt](https://github.com/Kozea/WeasyPrint/files/2084033/pruebaPDF.txt)

**Comment by jiro412j** [comment]
I also experience the same problem

![memo_](https://user-images.githubusercontent.com/14954947/42151634-cd736562-7e07-11e8-9b2d-9ddf44931c35.png)

**Comment by liZe** [comment]
> The layout-code muddles my brain...

`split_inline_box` is a nightmare that I should rewrite.
