### ISSUE TITLE
Run on PyPy

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/WeasyPrint#64]
Switching to CFFI removed a big obstacle to running WeasyPrint on PyPy. The test suite now actually passes, but bigger document (anything useful) fail because of https://github.com/lxml/lxml/issues/99.

I’m hopeful that PyPy can bring great speed improvements, although there is absolutely no data yet.

**Comment by liZe** [comment]
I've tested with pypy 5.3.1 and it works very well. lxml now has an "official" support of pypy and everything else is OK, so :beers:.

lxml doesn't work (yet) with pypy3 (I've tried 5.2.0-a0), but there should be no problem when an updated version of pypy3 is released.

Here's the incredibly-awesomly-reliable benchmark on the whole HTML5 spec (1340 pages PDF generated):
- pypy 5.3.1 : 346 seconds,
- python 3.4.5 : 369 sseconds.

Yay, ≃10% faster!

Bonus question: why does pypy generate a 30MB PDF when python's generated PDF is 15MB? I'm soooooo excited, I'd love to spend days and weeks finding why!

(Well, my browser can do this in 4.7 seconds including JS, but it doesn't know how to break a table between two pages :wink:.)
