### ISSUE TITLE
some sites do not render properly from html to pdf

### ISSUE THREAD

**Issue by dfernan** [Kozea/WeasyPrint#642]
Example:
weasyprint 'https://www.lowes.com/pl/Electrical-wire-cable-Electrical/4294722493' lowes.pdf

I get a blank pdf with no content from the actual html site.

I am using last versions:
weasyprint --version
WeasyPrint version 0.42.3
python --version
Python 3.6.3 :: Anaconda custom (64-bit)

**Comment by Tontyna** [comment]
That's because of:

```html
<style id="antiClickjack">body{display:none !important;}</style>
```

There is probably some JavaScript which unhides the `<body>` again but WeasyPrint doesn't execute JavaScript.

BTW: Until I looked at your HTML source I thought HTML was a human readable text format...

**Comment by Tontyna** [comment]
N.B.: Removing only that style won't make you happy unless you fix the `@media print only` styles which are discarded as invalid by WeasyPrint.

Furthermore: Parsing your HTML with a visible body and a WeasyPrint version newer than 69b64d2 aka 'First working version of flex layout' will not satisfy you, too.
Those versions either crash with "TypeError: max-content width for InlineFlexBox not handled yet" or run into an endless loop (I stopped at page nr 250). But that's another issue...

**Comment by liZe** [comment]
@dfernan thanks for taking the time to report this issue.

 WeasyPrint's not designed to generate PDF from any website. Its lack of JS engine and its limited CSS support (when compared to web browsers) makes it pretty bad for this use case.

WeasyPrint is better when used with documents specially crafted for printing.

You'll get better result with a tool based on a web browser engine, such as [wkhtmltopdf](https://wkhtmltopdf.org/).

Good luck!
