### ISSUE TITLE
OL start attribute

### ISSUE THREAD

**Issue by mikosullivan** [Kozea/WeasyPrint#643]
It appears that WeasyPrint does not respect the START attribute for the OL tag. When I process a page in which every OL has a custom start attribute, those lists still always start at 1.

**Comment by liZe** [comment]
Hello!

The `start` attribute is an HTML presentational hint, it's supported in WeasyPrint only when you use the `--presentational-hint` option.

**Comment by mikosullivan** [comment]
Sweet! Thanks!
