### ISSUE TITLE
Images in pdf are enlarged and only parts of them are viewable

### ISSUE THREAD

**Issue by davidkjoy** [Kozea/WeasyPrint#646]
While exporting the pdf using weasyprint with the help of a html template, the image is highly enlarged in the pdf and only part of it is view-able. Any ways to solve this ?
Currently, I am just trying to view the files present in a folder.
When I open the html page, the image looks fine. Resizing in HTML doesn't work in pdf.
Is it because weasyprint uses image in directory as such ?
Can it be solved by changing the resolution ?

Thank You in advance!

**Comment by davidkjoy** [comment]
![screenshot 42](https://user-images.githubusercontent.com/26377147/41578728-3e0b2870-73b1-11e8-8613-df60873cffa0.png)

**Comment by davidkjoy** [comment]
That's how my pdf looks right now .

**Comment by Tontyna** [comment]
And how does your html look like? Especially the `<img>` tag and its style?

**Comment by liZe** [comment]
@davidkjoy could you please provide your HTML file?

**Comment by liZe** [comment]
Closing, as it's probably a CSS-related problem, not a bug in WeasyPrint. Feel free to reopen if needed.

**Comment by etownbetty** [comment]
I'm having the same issue.
My inserted images are huge in PDF, compared to the rendered HTML.
my img tag is: <img src="supportingLinesTriangle.png" width="400" height=auto alt="HPI Graphic">

**Comment by etownbetty** [comment]
Got it. I just altered in a .css style sheet instead of tag.
