### ISSUE TITLE
Installation manual

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#651]
1. Requirements.txt is missing Pillow
2. Pillow also requires `apt-get install libjpeg-dev zlib1g-dev`
3. warnings.warn('@font-face support needs Pango >= 1.38')

**Comment by liZe** [comment]
1) WeasyPrint doesn't rely on Pillow, but one of its deps called CairoSVG does. Pillow is in [CairoSVG's `setup.py` file](https://github.com/Kozea/CairoSVG/blob/master/setup.py#L47), so everything's fine IMO. Did I miss something?
2) [Pillow is packaged in binary wheels](http://pillow.readthedocs.io/en/5.1.x/installation.html), its installation should not depend on `*-dev` packages. Why did you get the need to install them?
3) You're right, it's been added into the documentation thanks to 5a40d2b.

**Comment by knyttl** [comment]
1. When I didn't install it, when running weasyprint, it said `ImportError: No module named PIL`. I googled and found Pillow. 
2. The installation failed until I installed these two. I am on Debian Jessie.

Basically, to install everything correctly I created this script and then run it on all machines:

```
apt-get install -y fonts-font-awesome libffi-dev libgdk-pixbuf2.0-0 libpango1.0-0=1.40.5-1\
            python3-dev python3-lxml shared-mime-info python3 python3-pip libcairo2=1.14.8-1 libjpeg-dev zlib1g-dev

echo "gunicorn==19.4" > requirements.txt
echo "WeasyPrint==0.42.3" >> requirements.txt
echo "flask==0.10" >> requirements.txt
echo Pillow >> requirements.txt

pip3 install -r requirements.txt
```

**Comment by liZe** [comment]
> When I didn't install it, when running weasyprint, it said ImportError: No module named PIL. I googled and found Pillow.

Is it possible to get the whole output of `pip3 install -r requirements.txt`?

**Comment by liZe** [comment]
> sorry i dont have those machiens available anymore :/

I'm closing this issue for now, as everything looks fine in various `setup.py` files and installation works fine on Travis, with both Linux and macOS. Please reopen the issue if there's something new.
