### ISSUE TITLE
Python recursion limit with large file

### ISSUE THREAD

**Issue by bassasaurus** [Kozea/WeasyPrint#654]
Traceback

https://pastebin.com/eAHZKiY1

I have a file with ~3.5k lines that keeps giving me a maximum recursion error.

It seems to concern this line in particular

/lib/python3.6/site-packages/weasyprint/formatting_structure/build.py" in element_to_box 155. child_element, style_for, get_image_from_uri, base_url, state))

This is my first time reporting a bug - forgive me for possibly not doing it properly.

Thank you for your attention.

**Comment by liZe** [comment]
Thank you for this bug report!

Could you please provide the HTML+CSS sample causing this error? There's probably a bug somewhere in WeasyPrint.

**Comment by liZe** [comment]
@bassasaurus ping?

**Comment by bassasaurus** [comment]
Guys, I'm sorry. I can only imagine that it was something wrong with the
HTML I was generating. I haven't been able to reproduce the error. It works
great now for whatever reason. Thank you very much for reaching out. It's a
great package!

Cheers

**Comment by liZe** [comment]
> Thank you very much for reaching out. It's a
> great package!

No problem :smile:!

We'll release our first stable version soon. To be sure that we focus on what's important for you, you can write a small comment on #635. Thank you!
