### ISSUE TITLE
write_pdf() not finishing

### ISSUE THREAD

**Issue by dgonza12** [Kozea/WeasyPrint#655]
For some reason write_pdf does not finish. I am trying to run it within a flask application. 

```
pdf_content = render_template('checklist_results_pdf.html',**template_args)
pdf_as_html = HTML(string=pdf_content, base_url='')
print 'hello1'
print pdf_content
pdf_as_html.write_pdf(pdf_file)
print 'goodbye'
```

goodbye does not print but both hello and the pdf_content do. 

Also I am on WeasyPrint==0.27

**Comment by liZe** [comment]
Thank you for this bug report.

Is it possible for you to try a more recent version of WeasyPrint? 0.29 is two years old, a lot of things have changed since then.

**Comment by dgonza12** [comment]
Hi sorry for the late response. The template had some css that I guess was not compatible with that version, once removed it was able to generate the pdf.
