### ISSUE TITLE
[Fontconfig] Weasyprint needs at least one local font or crashes

### ISSUE THREAD

**Issue by mes3yd** [Kozea/WeasyPrint#677]
When there are no fonts installed (`fc-list` returns no lines) weasyprint tries to reference the first member of a family that is not populated:
```
File "/usr/local/lib/python3.6/site-packages/weasyprint/__init__.py", line 182, in write_pdf
     font_config=font_config).write_pdf(
File "/usr/local/lib/python3.6/site-packages/weasyprint/__init__.py", line 143, in render
     font_config)
File "/usr/local/lib/python3.6/site-packages/weasyprint/document.py", line 315, in _render
     font_config=font_config, page_rules=page_rules)              
File "/usr/local/lib/python3.6/site-packages/weasyprint/css/__init__.py", line 845, in get_all_computed_styles
     html.base_url, font_config, page_rules):
File "/usr/local/lib/python3.6/site-packages/weasyprint/css/__init__.py", line 143, in find_stylesheets
     font_config=font_config, page_rules=page_rules)              
File "/usr/local/lib/python3.6/site-packages/weasyprint/__init__.py", line 278, in __init__                                                    
     self.page_rules, self.fonts, font_config)
File "/usr/local/lib/python3.6/site-packages/weasyprint/css/__init__.py", line 803, in preprocess_stylesheet
     rule_descriptors, url_fetcher)                              
File "/usr/local/lib/python3.6/site-packages/weasyprint/fonts.py", line 191, in add_font_face
     family = ffi.string(family[0])                              
File "/usr/local/lib/python3.6/site-packages/cffi/api.py", line 309, in string       return self._backend.string(cdata, maxlen)
RuntimeError: cannot use string() on <cdata 'unsigned char *' NULL>
```
This can be reproduced by having an installation (docker container) with no installed fonts and using an `@font-face` rule in css sheet, that prefers local fonts over remote. For example: `<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">`. Since we are only using remote fonts, we did not consider installing one locally in the docker container.

Additionally, if one does a check if there are any locally installed fonts, an entire code path can be avoided in the `add_font_face` method and one can just handle the remote font.

**Comment by Tontyna** [comment]
HA! See comment in fonts.py source: 
https://github.com/Kozea/WeasyPrint/blob/affbe00afdb3d8e5c2b55ae31b32a1865119614b/weasyprint/fonts.py#L175

Can think of two enhancements to fonts.py:

1. As you say, skip the local font loading when there are no local fonts
   ```python
   if font_type == 'local' and fontconfig.FcConfigGetFonts(...).nfonts == 0:
       continue
   ```
2. Wrap another `try...except WARN continue` around the ffi/fontconfig stuff in `add_font_face`

**Comment by Tontyna** [comment]
Not sure whether the abovementioned enhancement would prevent WeasyPrint from crashing -- having no fallback-font at all feels precarious, something that Pango/Cairo dont like at all...

**Comment by mes3yd** [comment]
I'm fine with a install doc enhancement :)

I think the fact that no one ever complained about such things is before docker & alpine linux. The [docker-weasyprint](https://github.com/drosboro/docker-weasyprint/blob/master/Dockerfile) service image forces you to install fonts, so it never has an issue with it.

I guess it's a bit of a corner case, but it is easily avoidable and instead of me researching null pointers, I could be installing a font, cause a warning told me to do so. :)

**Comment by Tontyna** [comment]
Besides an installation hint WeasyPrint could log a warning about `nfonts` being zero. And check `FcResult` when calling fontconfig functions.

**Comment by ohadperry** [comment]
The question here is how to install fonts for an alpine based docker?

**Comment by liZe** [comment]
> The question here is how to install fonts for an alpine based docker?

Noto fonts are packaged for Alpine: https://pkgs.alpinelinux.org/packages?name=font-*&branch=edge

**Comment by ohadperry** [comment]
are they pre installed on `alpine:3.6`?
if not, what is the Dockerfile command to install them?

**Comment by liZe** [comment]
> are they pre installed on `alpine:3.6`?

I don't use Alpine, so you should ask the Alpine devs.

> if not, what is the Dockerfile command to install them?

I don't use Docker, so you should ask the Docker devs :smile:.
