### ISSUE TITLE
Internal links are broken (Cairo bug)

### ISSUE THREAD

**Issue by Tontyna** [Kozea/WeasyPrint#678]
In commit "Don't use pdfrw anymore" 0834615b78070259c15b341c2661ddae46fe7b53 @liZe commented 

> some internal links are broken

May I ask which internal links still **do** work? 

Because it looks to me like **all** internal links are broken. Nothing special about my `id`s, but only external `hrefs`are clickable.

Edit: Cairo v 1.15.12

**Comment by Tontyna** [comment]
AH! Got it:

Internal links dont work if the target is on a page coming after the `<a>`'s page.
If the target is on the same or an earlier page they are clickable.

That means: `write_pdf` should draw the pages and collect the hyperlinks in 'Step 6 - Drawing' and add the hyperlinks in 'Step 7 - Adding PDF metadata'. 

Maybe adding the links with `CAIRO_TAG_DEST` instead of `CAIRO_TAG_LINK` could do the trick? Of course then we need not only `add_hyperlinks()` but also a `add_destonations()`.

BTW: Wondering why not issuing `context.tag_end(cairo.TAG_LINK)` doesnt upset Cairo.

**Comment by Tontyna** [comment]
... but it seems there isnt a function to reactivate an already emitted surface ...

**Comment by liZe** [comment]
It's a bug in Cairo, I've submitted a patch: https://lists.cairographics.org/archives/cairo/2018-August/028716.html

> BTW: Wondering why not issuing context.tag_end(cairo.TAG_LINK) doesnt upset Cairo.

We should call `tag_end`, it's useless for now in our case but that's just a Cairo's implementation detail.

**Comment by Tontyna** [comment]
Oh dear! Waiting for Cairo... (since Bryce Harrington took notice, the prospects are not too bad)

Until then I'll patch my personal WeasyPrint to stay with `pdfrw`. Or maybe I'll patch your patch into my personal Cairo -- [quoting myself](https://github.com/Kozea/WeasyPrint/pull/668#issuecomment-412619087): it won't harm me when I start using my MSYS2 shell and brain and learn something new...

**Comment by liZe** [comment]
> Oh dear! Waiting for Cairo... (since Bryce Harrington took notice, the prospects are not too bad)

Yes, after the review I have to fix my fix now :smile:.

> Or maybe I'll patch your patch into my personal Cairo -- quoting myself: it won't harm me when I start using my MSYS2 shell and brain and learn something new...

Good luck!

**Comment by Tontyna** [comment]
Out of interest: Why do you commincate this issue via mailing list and not via GitLab?

**Comment by liZe** [comment]
> Out of interest: Why do you communicate this issue via mailing list and not via GitLab?

[Cairo's GitLab has only been created yesterday](https://lists.cairographics.org/archives/cairo/2018-August/028729.html) :wink:.

There was a Bugzilla instance, but I wasn't sure that it was a bug at the beginning, so … the ML was a good option for me to get extra information before creating an issue.

**Comment by Tontyna** [comment]
Will it speed up the fixing when I create an account on GitLab and :+1: the [issue](https://gitlab.freedesktop.org/cairo/cairo/issues/336)?

Until now we could tell people in need of new features like flex, targets etc. to download master branch, but as long as that bug persists I cant recommend that anymore.

**Comment by Tontyna** [comment]
Will keep that [branch](https://github.com/Tontyna/WeasyPrint/tree/patch_for_678) in sync with master until the bug is fixed.

**Comment by liZe** [comment]
> Will it speed up the fixing when I create an account on GitLab and  the [issue](https://gitlab.freedesktop.org/cairo/cairo/issues/336)?

1.15.14 has been released as a beta for 1.16.0. I've added a comment on GitLab, but I'm a bit afraid I don't get a review before the stable release.

I don't understand how to talk with Cairo devs. I'm getting really frustrated :cry:.

**Comment by Tontyna** [comment]
Indeed, Adrian commented

>...  you are welcome to change it. [...] as long as the tests pass and Bryce is happy, I don't mind what you do with it.

How to make Bryce happy? More patches?

I suggest to implement what Adrian intended when he added pdf links:
Apply CAIRO_TAG_DEST to the intenal links and their destinations (and hope it works as expected).
If your patch eventually enters Cairo we can always switch back to CAIRO_TAG_LINK.

A dysfunctional master branch is ugly.

@liZe - shall I / will you rewrite `document.write_pdf()`? Or shall we wait another fortnight for happiness to arise?

**Comment by liZe** [comment]
> How to make Bryce happy? More patches?

Probably with a test, I've begun to work on it this week-end.

> I suggest to implement what Adrian intended when he added pdf links:
> Apply CAIRO_TAG_DEST to the intenal links and their destinations (and hope it works as expected).
> If your patch eventually enters Cairo we can always switch back to CAIRO_TAG_LINK.

Of course.

> @liZe - shall I / will you rewrite `document.write_pdf()`? Or shall we wait another fortnight for happiness to arise?

I'll do it :bomb: RIGHT NOW :bomb:.

**Comment by Tontyna** [comment]
:+1: :+1: :+1:
