### ISSUE TITLE
Table column widths with colspans involved

### ISSUE THREAD

**Issue by JohannesMunk** [Kozea/WeasyPrint#685]
Hey WP-Team! This issue is low priority for us, as I have found a simple workaround. But nonetheless maybe you want to investigate or declare this as expected behaviour!

Whenever there is content in a cell with colspan the size of the colspan'ed element influences the width of the columns in an unexpected/unwanted way. On the left is chrome; on the right the output from WP.

![test html pdf - adobe acrobat pro](https://user-images.githubusercontent.com/12482761/45456293-7b2dc600-b6ea-11e8-837d-2341c6ba6dc5.png)

It seems that while the layout is done the colspan is not taking into consideration. Giving WP a hint in terms of a style="width:1px" circumvents the issue.

```
<html>
<style>td {border: 1px solid black;}</style>
<body>
<div style="width:100%">
<table>
	<tr><td>A</td><td>B</td><td>C</td><td>D</td><td>E</td></tr>
	<tr>
		<td colspan='5'>Where does this go?</td>
	</tr>
</table>
<table>
	<tr><td>A</td><td>B</td><td>C</td><td>D</td><td>E</td></tr>
	<tr>
		<td colspan='5' style='width:1px' >Where does this go?</td>
	</tr>
</table>

</div>
</body>
</html>
```
What do you think?

**Comment by liZe** [comment]
I don't know what's the worst part of this table between the first row and the second row. I'll have to go back deep in automatic table layout and add more tests!

(Just after fixing #666, it's really sad :cry:.)

**Comment by liZe** [comment]
We're getting closer and closer to what other web browsers do. There are some bugs left (I've even added a failing test), but the current implementation should be solid with more than 50 tests just for auto layout of tables.

**Comment by JohannesMunk** [comment]
Most impressive work!
![2018-09-21 00_10_55-wp-column-balance-orig html pdf - adobe acrobat pro](https://user-images.githubusercontent.com/12482761/45849606-e0a93480-bd32-11e8-9819-2f1895c87147.png)
Thank you!
