### ISSUE TITLE
Fix column balance when children are not inline

### ISSUE THREAD

**Issue by JohannesMunk** [Kozea/WeasyPrint#686]
Hello WP-Team! Sorry for being the source of so many issues at the moment. But I have found another one, that seems harder to circumvent.

There is a problem in getting the height in a multi-column layout right. It is chosen so high, that a 3 column layout breaks down to an unbalanced 2 column layout!

![2018-09-14 10_26_26-avscrollview](https://user-images.githubusercontent.com/12482761/45538941-b58d8500-b808-11e8-9fe2-deee4396d82d.png)

```
<html lang="de">
 <head>
  <meta charset="utf-8" />
  <title>wp-column-balance-test</title>
  <style>
		body {
			font-size: 9pt !important;
			font-family: DejaVu Sans, sans-serif;
		}
		.legalInfoPrefix {
			margin-top: 0.5em;
			border: 1px solid blue;
			column-count: 3;
			-webkit-column-count: 3;
		}
		.legal {
			margin-top: 0;
			margin-bottom: 0.5em;
			break-inside: auto;
		}

		h3 {
			font-size: 1.0em;
			margin: 0;
			padding: 0;
		}
		@media print {
			@page {
				size: A4;
				margin: 0;
			}
		}
	</style>
 </head>
<body>
 <div id="full">
   <div class='legalInfoPrefix'>
	<h3>Title 1</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </p>
	<h3>Title 2</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </p>
	<h3>Title 3</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
    </p>
	<h3>Title 4</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing
    </p>
	<h3>Title 5</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut 
    </p>
  </div>
   <div class='legalInfoPrefix'>
	<h3>Title 1</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </p>
	<h3>Title 2</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </p>
	<h3>Title 3</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehend
    </p>
	<h3>Title 4</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehend
    </p>
	<h3>Title 5</h3>
    <p class='legal'>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut 
    </p>
  </div>
 </div>
</body>
</html>
```
[wp-column-balance-test.html.pdf](https://github.com/Kozea/WeasyPrint/files/2382546/wp-column-balance-test.html.pdf)

Any ideas? Thx a lot in advance!

**Comment by liZe** [comment]
Current column balancing is pretty stupid and [should be rewritten](https://github.com/Kozea/WeasyPrint/blob/4667a6b15952a96c7a8a5e1e790865babfa9e999/weasyprint/layout/blocks.py#L220). It assumes that children are unbreakable, that's what gives erratic rendering. The best solution is probably to implement fragmentation (part of #36) and use fragmentation points.

**Comment by JohannesMunk** [comment]
Ok! Except for manually putting each heading into a specific "column"-container side by side, without any automatic column-layout, do you see a way for me to cheat, until you have reworked the layout code?

**Comment by ramonski** [comment]
Not sure if this is a valid workaround, I did not test it yet:

Define `<div class="row"></div>` with a fixed height. Each paragraph inside there is defined as a column and floats to the left.

I'm not sure how this will affect page breaks and you probably need to do a `clear: left` after each row. Also see https://github.com/Kozea/WeasyPrint/issues/36

I'm using bootstrap for the reports and added recently this print CSS because WP does not yet support flex-box layouts: https://github.com/senaite/senaite.impress/blob/master/src/senaite/impress/static/css/bootstrap-print.css

Columns seem to work with this pretty well with this column definition, but as I said, the page breaks need to be considered.

**Comment by liZe** [comment]
Another awful hack is to only have inline boxes in columns. You can use:
```
h3 {
  display: inline-block;
  width: 100%;
}
p {
  display: inline;
}
```

Of course, it works for your example but may have to be adapted for more complex content.

**Comment by JohannesMunk** [comment]
@liZe: That works like a charm and is a suitable workaround for what we need right now! Thank you!

**Comment by liZe** [comment]
We now use the real layout to balance columns. It's slower, but the result is much better!

See #878.
