### ISSUE TITLE
base 64 image is not affected when using inline width props

### ISSUE THREAD

**Issue by khasburrahman** [Kozea/WeasyPrint#689]
I have html that has base 64 image,

`<p class="ql-align-center"><img src="data:image/png;base64,__base64string__" width="432"></p>`I 

I rendered the pdf using this code:
```
html = HTML(file_obj=htmlFile, media_type="screen")
pdf = html.write_pdf(stylesheets=['/a4page.css']) //set the pdf to a4 size using @page css
```

Tried to change the width of the image using `width` props. but any value I entered seems to get ignored. The image size stay at where is was before. is this a known bug/ limitation ?

**Comment by ramonski** [comment]
I think this question is related to the "presentational hints" support of WeasyPrint here: https://github.com/Kozea/WeasyPrint/issues/527 (also see here: https://www.w3.org/TR/html5/introduction.html#presentational-markup)

Therefore I would suggest you better size your base 64 images with CSS or the `style` attribute.

**Comment by khasburrahman** [comment]
@ramonski Thanks, the style attribute works! 
`<p class="ql-align-center"><img src="data:image/png;base64,__base64string__" style="width:432px"></p>`

 and using presentational_hints in write_pdf works too! 👍 
`pdf = html.write_pdf(presentational_hints=True, stylesheets=['/a4page.css'])`
