### ISSUE TITLE
Question: Is there a way to set the magnification?

### ISSUE THREAD

**Issue by adonig** [Kozea/WeasyPrint#692]
First of all, let me thank you for maintaining this great library! :-)

Is there a way to set the magnification to "Fit page" like with Acrobat Pro shown in [this video](https://youtu.be/UVMHqnMBn9M?t=57)?

**Comment by adonig** [comment]
Thank you for the explanation! It was so good, I was able to make it work :-)

I found no reference to the catalog in the v0.42.3 API, so I had to switch to the current master.

Here is a piece of code for other people who might read the issue and want to do the same:

```
from io import BytesIO
from weasyprint.pdf import PDFFile
from weasyprint.pdf import pdf_format

# Add your code rendering HTML into a weasyprint.Document here.
# In my case this was done by django-weasyprint.

content = BytesIO(document.write_pdf())
pdf_file = PDFFile(content)
params = pdf_format('/OpenAction [0 /FitV null]')
pdf_file.extend_dict(pdf_file.catalog, params)
pdf_file.finish()
return pdf_file.fileobj.getvalue()
```

**Comment by liZe** [comment]
> Thank you for the explanation! It was so good, I was able to make it work :-)

:tada:

> I found no reference to the catalog in the v0.42.3 API, so I had to switch to the current master.
> 
> Here is a piece of code for other people who might read the issue and want to do the same:

I keep the issue open as we should give this example in the documentation.
