### ISSUE TITLE
"--presentational-hints" parameter seems to ignore "align=center"

### ISSUE THREAD

**Issue by RafaelLinux** [Kozea/WeasyPrint#694]
We realized today that despite we are launching weasyprint with `"--presentational-hints"` parameter, it seems is ignoring  `<td align="center">1</td>` 
![weasyprint - tables - parameter legacy not working](https://user-images.githubusercontent.com/13048959/45808033-1283b200-bcc5-11e8-95d3-a35634bd1b00.png)
Source web page is [http://www.dip-badajoz.es/bop/ventana_anuncio.php?id_anuncio=115432&FechaSolicitada=2018-09-20](http://www.dip-badajoz.es/bop/ventana_anuncio.php?id_anuncio=115432&FechaSolicitada=2018-09-20) where the table is in.

We are launching weasyprint like this "`weasyprint --presentational-hints  source_URL output.pdf`"

We are maybe using parameter in the wrong way?

Thank you

**Comment by Tontyna** [comment]
Your parameters are ok. It's WeasyPrint ignoring `center`.

[css.\_\_init\_\_.py](https://github.com/Kozea/WeasyPrint/blob/6fdf578c6e84bb1cc76da7511617eaee1dead1fd/weasyprint/css/__init__.py#L260) doesn't include the 'center' value -- intentionally? by mistake?

**Comment by RafaelLinux** [comment]
Oops!! No idea. I even forgot Weasyprint is programmed in Python. Incredible. I didn't know it was so versatile.

**Comment by liZe** [comment]
> by mistake?

By mistake.

**Comment by RafaelLinux** [comment]
"mistake" sounds bad. For forgetfulness   ;)
