### ISSUE TITLE
Tables with fix width overflow their parent width

### ISSUE THREAD

**Issue by RafaelLinux** [Kozea/WeasyPrint#695]
As a typical case, when tables width exceeds his parent width, web browsers ignored the table width and (seems that) put the table width to 100%, in screen and when printing. Could you take a look to this example?
[http://www.dip-badajoz.es/bop/ventana_anuncio.php?id_anuncio=115621&FechaSolicitada=2018-09-21](http://www.dip-badajoz.es/bop/ventana_anuncio.php?id_anuncio=115621&FechaSolicitada=2018-09-21)
The table at the end has `width="1310"` , but it do not overflow the container where it is nested.

Please, it's important that Weasyprint follow the same behaviour that web browsers to maintain readable tables.

Thank you

**Comment by liZe** [comment]
Hello,

I don't understand your problem. Here is what I get with WeasyPrint:
![capture d ecran de 2018-10-11 16-44-25](https://user-images.githubusercontent.com/952243/46812437-03989880-cd75-11e8-90dd-4ed7147d3c1f.png)

And here is what I get with Chrome:
![capture d ecran de 2018-10-11 16-44-39](https://user-images.githubusercontent.com/952243/46812450-0bf0d380-cd75-11e8-8186-f6b2b60f8356.png)

Did I miss something?

**Comment by Tontyna** [comment]
@liZe render it with 0.42.3 and you'll understand.

**Comment by liZe** [comment]
> @liZe render it with 0.42.3 and you'll understand.

This good rendering needs the current master branch, but I suppose @RafaelLinux knows that because I've already fixed many table layout problems in master!

> Edit: Though I don't understand why my current master branch is able to fetch the stylesheets while my 0.42.3 gets a `403: Forbidden`

It's thanks to 9b9f4f2.

**Comment by liZe** [comment]
Closing this issue, as it's probably fixed between 0.42.3 and 43. Of course, other issues remain with tables…
