### ISSUE TITLE
Getting uincodeDecodeError

### ISSUE THREAD

**Issue by hybridpicker** [Kozea/WeasyPrint#696]
Trying to get WeasyPrint Running with this function:
def generate_pdf(request):
    # Model data
    context = {
                'invoice_id': 18001,
                'street_name': 'Rue 76',
                'postal_code': '3100',
                'city': 'Washington',
                'customer_name': 'John Cooper',
                'customer_mail': 'customer@customer.at',
                'amount': 1339.99,
                'today': 'Today',
                }

    # Rendered
    html_string = render_to_string('pdf/invoice.html', context)
    html = HTML(string=html_string)
    result = html.write_pdf()

    # Creating http response
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'inline; filename=list_people.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'r')
        response.write(output.read())
    return response

Got an UnicodeDecode -Error:
'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte

**Comment by Tontyna** [comment]
Not enough info to narrow down the error. Where is the UnicodeDecodeError produced? Could you provide a traceback?

**Comment by hybridpicker** [comment]
it is produced at the line "response.write(output.read())"

**Comment by Tontyna** [comment]
See [this answer](https://stackoverflow.com/a/46753879) on stackoverflow.
It's not WeasyPrint, it's the `r` (aka text) flag in your open(). Use `rb` instead.
