### ISSUE TITLE
Confirm versions of cairo, etc, to generate the sample report

### ISSUE THREAD

**Issue by guateandrew** [Kozea/WeasyPrint#702]
I cannot seem to reproduce the sample report that you provide on the site (using flask). In particular I am not getting the table of contents to render as they do on your pdf sample report.  I want to check what version of the various dependencies that relies on? I suspect that you might be using a later cairo version .....

I am using:
weasyprint v 0.43.3
cairo 1.14.12
flask_weasyprint 0.5

My table of contents looks like the image below:

<img width="709" alt="screen shot 2018-10-07 at 20 02 25" src="https://user-images.githubusercontent.com/1678174/46591002-929f6b00-ca6c-11e8-9f46-e457537092f7.png">

**Comment by liZe** [comment]
Hello! Samples come from the current `master` branch. A beta version is coming soon.
