### ISSUE TITLE
First Line of New Page is Incorrectly Indented when Indenting All But First Paragraph

### ISSUE THREAD

**Issue by OptikSage** [Kozea/WeasyPrint#706]
Given the following HTML: 

<html>
    <head>
        <style>
         @page {
             size: 5.06in 7.81in;
             margin-right: 0.5in;
             margin-left: 0.5in;
         }

         p {
             line-height: 1.5em;
             margin: 0;
             orphans: 3;
             widows: 3;
         }

         p+p {
             text-indent: 1.4em;
         }

        </style>
    </head>
    <body>
        <section>
            <p>Nullam eu ante vel est convallis dignissim.  Fusce suscipit, wisi nec facilisis facilisis, est dui fermentum leo, quis tempor ligula erat quis odio.  Nunc porta vulputate tellus.  Nunc rutrum turpis sed pede.  Sed bibendum.  Aliquam posuere.  Nunc aliquet, augue nec adipiscing interdum, lacus tellus malesuada massa, quis varius mi purus non odio.  Pellentesque condimentum, magna ut suscipit hendrerit, ipsum augue ornare nulla, non luctus diam neque sit amet urna.  Curabitur vulputate vestibulum lorem.  Fusce sagittis, libero non molestie mollis, magna orci ultrices dolor, at vulputate neque nulla lacinia eros.  Sed id ligula quis est convallis tempor.  Curabitur lacinia pulvinar nibh.  Nam a sapien. </p>
            <p>Nullam eu ante vel est convallis dignissim.  Fusce suscipit, wisi nec facilisis facilisis, est dui fermentum leo, quis tempor ligula erat quis odio.  Nunc porta vulputate tellus.  Nunc rutrum turpis sed pede.  Sed bibendum.  Aliquam posuere.  Nunc aliquet, augue nec adipiscing interdum, lacus tellus malesuada massa, quis varius mi purus non odio.  Pellentesque condimentum, magna ut suscipit hendrerit, ipsum augue ornare nulla, non luctus diam neque sit amet urna.  Curabitur vulputate vestibulum lorem.  Fusce sagittis, libero non molestie mollis, magna orci ultrices dolor, at vulputate neque nulla lacinia eros.  Sed id ligula quis est convallis tempor.  Curabitur lacinia pulvinar nibh.  Nam a sapien. </p>
            <p>Nullam eu ante vel est convallis dignissim.  Fusce suscipit, wisi nec facilisis facilisis, est dui fermentum leo, quis tempor ligula erat quis odio.  Nunc porta vulputate tellus.  Nunc rutrum turpis sed pede.  Sed bibendum.  Aliquam posuere.  Nunc aliquet, augue nec adipiscing interdum, lacus tellus malesuada massa, quis varius mi purus non odio.  Pellentesque condimentum, magna ut suscipit hendrerit, ipsum augue ornare nulla, non luctus diam neque sit amet urna.  Curabitur vulputate vestibulum lorem.  Fusce sagittis, libero non molestie mollis, magna orci ultrices dolor, at vulputate neque nulla lacinia eros.  Sed id ligula quis est convallis tempor.  Curabitur lacinia pulvinar nibh.  Nam a sapien. </p>
        </section>
    </body>
</html>

I am expecting that the only indented lines are the first line of each of the 2nd through Nth paragraph, but instead there are also indention in the middle of the paragraph at the beginning of each page.

![repro](https://user-images.githubusercontent.com/6692044/46901043-d1358b00-ce9b-11e8-93f0-3fde33582de6.png)

Currently running from sources (WeasyPrint version 43a0)
commit 8b7f52906405fe551982ca127b518fb05255157c

**Comment by liZe** [comment]
Thank you!

**Comment by OptikSage** [comment]
Verified this works for me. Thanks for the fix!
