### ISSUE TITLE
Header and footer on the same pages

### ISSUE THREAD

**Issue by guateandrew** [Kozea/WeasyPrint#708]
I'm not sure whether tis is a limitation of the spec or not, but I am unsuccessful in printing both a top header and a bottom footer on the same page. For example, the below will only show the bottom footer:

`@page {
      @top-left {
        background: #2D7687;
        content: counter(page);
        height: 1cm;
        text-align: center;
        width: 1cm;
        color: #FFF;
      }
     @bottom-left {
        background: #2D7687;
        content: counter(page);
        height: 1cm;
        text-align: center;
        width: 1cm;
        color: #FFF;
      }
`
Can you confirm please if this is a bug or a limitation?

**Comment by Tontyna** [comment]
Neither a bug nor a limitation. The following HTML:

```html
<html>
<head>
<style>
@page { 
 @top-left { background: #2D7687; content: counter(page); 
   height: 1cm; text-align: center; width: 1cm; color: #FFF; } 
@bottom-left { background: #2D7687; content: counter(page); 
  height: 1cm; text-align: center; width: 1cm; color: #FFF; }
}
</style>
</head>
<body>
<p>
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
<p>
</body>
</html
```

is rendered by WeasyPrint as expected:
![test](https://user-images.githubusercontent.com/35614937/47108855-03087200-d24d-11e8-9d15-01242bf29d49.png)

How does your output look like? Any errors or warnings?

**Comment by guateandrew** [comment]
You are right, I had a silly bug in my CSS. My apologies!
