### ISSUE TITLE
Error generating PDF with WeasyPrint (bytes-like object is required, not 'Template')

### ISSUE THREAD

**Issue by robertonqn** [Kozea/WeasyPrint#714]
Dear good morning, I am having an error and I do not know how to solve it because it is the first time it happens to me, I am using the WeasyPrint and try to do it in the following way:

/ ************************************************ **************************************
views.py

from weasyprint import HTML, CSS
from django.template.loader import get_template
from django.http import HttpResponse

def pdf_generation (request):
       html_template = get_template ('templates / invoice.html')
       pdf_file = HTML (string = html_template) .write_pdf ()
       response = HttpResponse (pdf_file, content_type = 'application / pdf')
       response ['Content-Disposition'] = 'filename = "invoice.pdf"'
       return response

/ ************************************************ **************************************

invoice.html

	<head>
		Home Page
	</head>
	<body>
		<h1>Hello !!!</h1>
		<p>First Pdf Generation using Weasyprint.</p>
	</body>

/ ************************************************ **************************************
urls.py
from django.conf.urls import url
from aplication.views import pdf_generation 

urlpatterns = [
				url(r'^resumen/$', pdf_generation, name='resumen'),
]

/ ************************************************ **************************************

and I get the following error: a bytes-like object is required, not 'Template'

They can help me please. I await answers.

Greetings.

**Comment by Tontyna** [comment]
At first glace it seems that there are a lot of space characters in your soure code where there shouldn't be space characters...

Dont know nothing about django, but if you post the traceback, maybe I can help.

**Comment by rpolisetti** [comment]
@robertonqn  Could you post the solution please?

**Comment by Tontyna** [comment]
Obviously `get_template` just **gets** a django `Template` object. 
Probably this Template must be executed/filled/rendered  to generate the html string that WeasyPrint needs. I guess something like the following did the trick

```
html_template = get_template('templates/invoice.html').render()
```

**Comment by rpolisetti** [comment]
@Tontyna Thank You. Will try it out and let u know.

**Comment by yadavanuj1996** [comment]
@Tontyna Thanks for solution ,it is working.
