### ISSUE TITLE
Error generating PDF with WeasyPrint (bytes-like object is required, not 'Template')

### ISSUE THREAD

**Issue by robertonqn** [Kozea/WeasyPrint#715]
Dear good morning, I am having an error and I do not know how to solve it because it is the first time it happens to me, I am using the WeasyPrint and try to do it in the following way:

/ ************************************************ **************************************
from weasyprint import HTML, CSS
from django.template.loader import get_template

def pdf_generation (request):
html_template = get_template ('templates / invoice.html')
pdf_file = HTML (string = html_template) .write_pdf ()
response = HttpResponse (pdf_file, content_type = 'application / pdf')
response ['Content-Disposition'] = 'filename = "invoice.pdf"'
return response

/ ************************************************ **************************************
Given the following HTML:

	<head>
		Home Page
	</head>
	<body>
		<h1>Hello !!!</h1>
		<p>First Pdf Generation using Weasyprint.</p>
	</body>

and I get the following error: a bytes-like object is required, not 'Template'

They can help me please. I await answers.

Greetings.

**Comment by liZe** [comment]
Duplicates #714.

**Comment by rpolisetti** [comment]
What was the solution for this issue?
