### ISSUE TITLE
I convert msg to pdf.But it's garbled

### ISSUE THREAD

**Issue by cctytw2000** [Kozea/WeasyPrint#716]
i use 
weasyprint 1010.msg  msg1010.pdf
But it's garbled

**Comment by liZe** [comment]
Hello,

Could you please provide your HTML file and the PDF you get?

**Comment by cctytw2000** [comment]
it's not html  
it's msg

**Comment by liZe** [comment]
What's MSG? WeasyPrint knows how to transform HTML files to PDF, but knows nothing about MSG files.

**Comment by cctytw2000** [comment]
ok , i'm sorry
I am still looking for python convert msg to pdf.
Can you give me some suggestions?

**Comment by liZe** [comment]
> I am still looking for python convert msg to pdf.

What's msg???

**Comment by cctytw2000** [comment]
it's like .eml

**Comment by cctytw2000** [comment]
use outlook

**Comment by liZe** [comment]
If your mail contains HTML, you can extract it and use WeasyPrint to render it.

You can use [this Stackoverflow code](https://stackoverflow.com/questions/31392361/how-to-read-eml-file-in-python#31392574) to read your .eml file and extract the HTML part of it.

**Comment by Tontyna** [comment]
@liZe is this real?  :heart: :heart: :heart:  for you being incredibly obliging
