### ISSUE TITLE
How to insert a Bar Code in WeasyPrint?

### ISSUE THREAD

**Issue by robertonqn** [Kozea/WeasyPrint#718]
Dear good afternoon, I am trying to create a bar code in WeasyPrint and I have looked for examples or guides to do it and I did not find anything.

Can you help me please? I show you an example of a reportLab:

if code_payment_facil:
barcode = code128.Code128 (easy_payment_code, barHeight = 30, barWidth = 1)
barcode.drawOn (p, 120 * mm, 260 * mm)
p.setFont ('Times', 8)
code_pago_facil_2 = ''
for c in codigo_pago_facil:
code_pago_facil_2 + = str (c) + ""
p.drawString (370, 730, code_payment_facil_2)

This I would like to be able to pass it to WeasyPrint.

I await answers.

Regards Dear,

**Comment by liZe** [comment]
Hello,

Please don't write "PLEASE HELP" in your issue title: it will not make people give you quicker answers, it will just be annoying for people trying to help you. We already know that you need help, that's often why people open issues :wink:.

> I have looked for examples or guides to do it and I did not find anything.

There's a [samples](https://weasyprint.org/samples/) page on the website, and among the presented features you'll find … a barcode!

The barcode number is in [the HTML file](https://github.com/Kozea/WeasyPrint/blob/gh-pages/samples/ticket/ticket.html#L28) and is automatically transformed into a barcode [thanks to a font](https://github.com/Kozea/WeasyPrint/blob/gh-pages/samples/ticket/ticket.css#L77).

**Comment by liZe** [comment]
@robertonqn Is that OK for you?

**Comment by robertonqn** [comment]
Good morning, I tell you that this bar code did not work for me, I am trying to find another type of source that is Code128, since the source of google code128 would not be working on my system.

so if you have any other idea I would appreciate it.

**Comment by liZe** [comment]
If you really want to use the code128 module, then use it to generate an image with something like
```python
with open("Hello World.svg", "w") as f:
    f.write(code128.svg("Hello World"))
```
and include this SVG image in your HTML file.

**Comment by liZe** [comment]
You can also install [a font specially designed for code128](https://www.dafont.com/fr/code-128.font).

**Comment by liZe** [comment]
@robertonqn Can I close this issue?

**Comment by liZe** [comment]
> Can I close this issue?

Let's say I can.
