### ISSUE TITLE
Support for column-span

### ISSUE THREAD

**Issue by fabiobatalha** [Kozea/WeasyPrint#719]
Is any kind of envisioning to give support for column-span.

Example of use of column-span using the tool PagedJS:

![screenshot from 2018-10-25 10-23-24](https://user-images.githubusercontent.com/504142/47507475-3dbb6d00-d840-11e8-930d-1f46d1f8b741.png)

The same PDF file produced with WeasyPrint using the same HTML and CSS's.

![screenshot from 2018-10-25 10-23-50](https://user-images.githubusercontent.com/504142/47507528-562b8780-d840-11e8-974a-025e1c3d2234.png)

**Comment by liZe** [comment]
> Is any kind of envisioning to give support for column-span.

Nothing has been done yet to support column-span, but it would be quite easy to handle simple cases (ie at least without fixed height).

The overall goal is to change the `columns_layout` function (in `layout/columns.py`) to split the `box` at the beginning of the function into multiple boxes. For example:

```css
div {columns: 2}
h2 {column-span: all}
```

```html
<div>abc def <h2>test</h2> ghi jkl</div>
```

In this case, we have to:
- go through `box` (the `div` element) to find the `h2` element,
- render `<div>abc def ` (with the current code) and `<h2>test</h2>` (with some added code),
- render ` ghi jkl</div>` for example by calling `columns_layout` with the current `skip_stack`.

If anyone is interested in implementing this feature, I'll be happy to help!
