### ISSUE TITLE
string-set attr(alt) fails if image is displayed [43rc1 regression]

### ISSUE THREAD

**Issue by Smylers** [Kozea/WeasyPrint#722]
Using `string-set foo attr(alt)` to set the string to an image's `alt` attribute no longer works in WeasyPrint 43rc1, when the image is displayed.

This is a regression; it works fine in version 0.39 (sorry, I haven't checked versions between those).

Demo:

```` html
<!DOCTYPE html>
<title>string-set Check</title>
<style>
h1 img { -weasy-string-set: left  attr(alt) }
h2 img { -weasy-string-set: right attr(alt) }
@page { @top-left  { content: '[' string(left)  ']' }
        @top-right { content: '{' string(right) '}' } }
</style>

<h1><img src=valid_image.png  alt=Chocolate></h1>
<h2><img src=no_such_file.png alt=Cake></h2>
````

Make `valid_image.png` exist (and ensure that `no_such_file.png` doesn't).

* In 0.39, the left header says ‘[Chocolate]’ and the top right says ‘{Cake}’, as intended.
* In 43rc1, the top left is just ‘[]’, but the top right is still ‘{Cake}’.

So when the `alt` text is needed for display in the document, it's still there for `attr(alt)` to find it. But in the (presumably more common) case where the image is actually available and `alt` isn't required for the document, its content no longer appears in `attr(alt)` either.

**Comment by liZe** [comment]
The regression is in 0.40.

**Comment by Tontyna** [comment]
The ugly `missing_link` property comes to mind -- introduced to hold a reference to the original box for the `target-*` functionality  -- suggestion was to make it an officail property of any box -- maybe in `Box.copy()` -- just an idea...

**Comment by liZe** [comment]
Bookmarks were broken too.

> The ugly `missing_link` property comes to mind

That was `string_set`, but the idea of having a list of "official" properties is a good idea.
