### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by StoneMoe** [Kozea/WeasyPrint#725]
[write_png @ readthedocs.io](https://weasyprint.readthedocs.io/en/stable/api.html#weasyprint.HTML.write_png) Shows this function return bytes of PNG image
![image](https://user-images.githubusercontent.com/5786577/47834637-317f6480-dd98-11e8-92c2-cc174f2d3736.png)

But the latest version(0.42.3) in Pypi shows:
```
def write_png(self, target=None, resolution=96):
..........
:returns:
A ``(png_bytes, png_width, png_height)`` tuple
```

**Comment by StoneMoe** [comment]
I misreading it, sorry for that

**Comment by Tontyna** [comment]
Same misreading happens to me each time I lookup the definition of `write_png` in the source :grimacing:
