### ISSUE TITLE
string-set '' doesn't clear previous value from named string [43rc1 regression]

### ISSUE THREAD

**Issue by Smylers** [Kozea/WeasyPrint#726]
`string-set: foo ''` used to clear the named string. It now seems to be ignored, leaving the previous value in there.

Demo:

````html
<!DOCTYPE html>
<title>Clear String Check</title>
<style>
@page { @top-left  { content: '[' string(left) ']' } }
p { page-break-before: always }
.initial { -weasy-string-set: left 'initial' }
.empty   { -weasy-string-set: left ''        }
.space   { -weasy-string-set: left ' '       }
</style>

<p class=initial>Initial
<p class=empty  >Empty
<p class=space  >Space
````

In WeasyPrint 0.39, the three page headings are the expected “[initial]”, “[]”, and “[ ]”. But in 43rc1, the middle one is still “[initial]”.

**Comment by liZe** [comment]
Oops, forgot this issue.

> @liZe any bad side-effects expected when changed to `if len(tests) > 0:` ?

Probably not, I'll change this.

**Comment by liZe** [comment]
> Probably not, I'll change this.

It actually was a bit more complicated than this, as `compute_content_list` has to return something when the string is empty, but empty text boxes are not allowed.

I used `None` when nothing has been found and `[]` when something has been found but didn't create a box.
