### ISSUE TITLE
Height, width set to auto causes typeerror

### ISSUE THREAD

**Issue by hydric** [Kozea/WeasyPrint#728]
In padding_height(self) and padding_width(self) in boxes.py the return values can't be added together when height and/or width is set to'auto'.

**Comment by liZe** [comment]
Hello,

Do you have the problem using the command-line interface, or did you try to use WeasyPrint as a library?

**Comment by hydric** [comment]
Using the below code in a file and calling it from the command-line.
The url in question was "https://lagen.nu/1991:614".
`   import weasyprint
    pdf_file = args.file
    pdf = weasyprint.HTML(args.url).write_pdf()
    file(pdf_file, 'w').write(pdf)`

**Comment by liZe** [comment]
Thank you, I can reproduce. I'll try to find what's wrong.

**Comment by liZe** [comment]
Minimal use case:
```html
<div style="position: fixed">
  <div style="position: fixed"></div>
</div>
<div style="break-after: page"></div>
<div></div>
```
