### ISSUE TITLE
No weasyprint.tools.navigator in 43rc2 ? 

### ISSUE THREAD

**Issue by bdamay** [Kozea/WeasyPrint#729]
I installed 43rc2 version of weasyprint on windows with 
> pip install Weasyprint==43rc2

Seems to be fine

> python -m weasyprint --version
> WeasyPrint version 43rc2

According to the docs i tried 

> python -m weasyprint.tools.navigator
> Error while finding module specification for 'weasyprint.tools.navigator' (ModuleNotFoundError: No module named 'weasyprint.tools')"

Do i miss something ?

**Comment by bdamay** [comment]
For the record, I reinstalled 43rc2 from cloned sources and it works fine now.
However it seems pip is missing the weasyprint.tools package

**Comment by liZe** [comment]
> However it seems pip is missing the weasyprint.tools package

Shame, Shame, Shame!

Thanks a lot for your report.

**Comment by bdamay** [comment]
> Thanks a lot for your report.

You're welcome, thanks for your work.
Have a nice day
