### ISSUE TITLE
Layout should use the actual resolution for text hinting

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/WeasyPrint#73]
… otherwise, we get results like this:
![text overflowing its container](https://f.cloud.github.com/assets/291359/374024/a58a5448-a392-11e2-9a7b-b39f6a7b521d.png)

Well, this is actually with the patch below. v0.18 just drops some words at the end of the line.

```
diff --git a/weasyprint/text.py b/weasyprint/text.py
index a43b1aa..acb636c 100644
--- a/weasyprint/text.py
+++ b/weasyprint/text.py
@@ -476,6 +476,7 @@ def line_widths(box, enable_hinting, width, skip=None):
 def show_first_line(context, pango_layout, hinting):
     """Draw the given ``line`` to the Cairo ``context``."""
     context = ffi.cast('cairo_t *', context._pointer)
+    pango.pango_layout_set_width(pango_layout.layout, -1)
     if hinting:
         pangocairo.pango_cairo_update_layout(context, pango_layout.layout)
     pangocairo.pango_cairo_show_layout_line(
```

**Comment by liZe** [comment]
This is a bit better with commit bbb42f2 (relying on the font size fixes at least main rounding problems), but the bug is not solved yet.

**Comment by liZe** [comment]
As we removed Cairo and only generate PDF documents, there’s no hinting anymore.
