### ISSUE TITLE
WeasyPrint Page Header

### ISSUE THREAD

**Issue by robertonqn** [Kozea/WeasyPrint#730]
Dear good afternoon, I am trying to add a page header to be repeated in all PDF pages, you can give me a hand or guide me with a few lines of code.
the content that I have inside my head I want it to be repeated as a header

I await answers.

Greetings.

**Comment by Tontyna** [comment]
What about searching the internet for "css paged media header"?
BTW: The css `@page` rule is your friend.

**Comment by liZe** [comment]
You can check what's done in our [report sample](https://weasyprint.org/samples/): headings and page numbers are put in the header using [these rules](https://github.com/Kozea/WeasyPrint/blob/gh-pages/samples/report/report.css#L29).
