### ISSUE TITLE
No display of proper version on running install

### ISSUE THREAD

**Issue by pepa65** [Kozea/WeasyPrint#734]
In the past, when running `sudo python3 setup.py install` the last line would print helpful version information, now it says: `WeasyPrint===file-.weasyprint-VERSION`.
(This is on current HEAD 63cc25b309088354cd7c38605969c38443836f34)

**Comment by liZe** [comment]
Thanks for reporting this issue.

The [needed feature](https://github.com/pypa/setuptools/pull/1359) (loading the version from a file) has been added in setuptools 39.2.0. You should update your setuptools package, or use a virtual environment if recent versions are not available in your distribution.
