### ISSUE TITLE
Features list not available

### ISSUE THREAD

**Issue by tombola** [Kozea/WeasyPrint#736]
... http://weasyprint.org/docs/features/ should be exhaustive. (If it’s not, that’s a documentation bug.)

_Originally posted by @SimonSapin in https://github.com/Kozea/WeasyPrint/issues/296#issuecomment-185428423_

This link does not work, and I could not locate the features list on the site.

**Comment by liZe** [comment]
It's in [the documentation](https://weasyprint.readthedocs.io/en/latest/features.html). Feel free to open an issue if you find errors or missing features on this page!
