### ISSUE TITLE
Generate pdf from browser page

### ISSUE THREAD

**Issue by cwagner22** [Kozea/WeasyPrint#739]
Is there a way to generate a pdf from a website opened in Google Chrome/Firefox?
Do I have to save as html and then use the `weasyprint` command to generate the pdf from the file?

The pages I want to save are interactive js web apps so I can't simply pass the url.

Is it technically possible to make a browser extension working with this tool?

**Comment by liZe** [comment]
Saving the HTML page is not enough if your web app is rendered client-side, as you'll only get the original state of the HTML before being modified by JS. What you want is really the current DOM tree export as HTML (more or less what you see in your browser's inspector). For now, you can try to do this by copying what's in your inspector and save it in a file, then change the stylesheets URL if needed and try to render it with WeasyPrint. If it works, you can theoretically do this with an extension.

**Comment by eregnier** [comment]
@cwagner22 you may use prerender.io to compute html rendering that you can then print with weasyprint.
Prerender takes a web page , compte javascript in it and "returns" a result of a computed page.

**Comment by cwagner22** [comment]
Thanks it helps but not as easy as I would like. Closing for now.
