### ISSUE TITLE
Absolute vs relative paths

### ISSUE THREAD

**Issue by sander76** [Kozea/WeasyPrint#740]
UPDATE: proper image naming

I am running into a relative vs absolute location issue when trying to make a pdf directly from a file folder.

Consider the following folder structure:

```
root
  |
  |--docs\
  |      -doc.html
  |
  |--imgs\
  |      -python.png
  |
  |--make_pdf.py
```
For testing purposes the html looks like:

```html
<html>
    <body>
        <img src="/imgs/python.png" alt="image 1">
        <img src="imgs/python.png" alt="image 2">
        <img src="../imgs/python.png" alt="image 3">
    </body>
</html>
```

The `make_pdf.py` file looks like:

```python
HERE = os.path.abspath(os.path.dirname(__file__))
html_file = str(Path(HERE).joinpath("docs", "doc.html"))

HTML(filename=html_file).write_pdf("out.pdf")
```

When running a python server from root folder `python -m http.server` and navigate to `http://localhost:8000/docs/doc.html` both *image 1* and *image 3* are displayed. Which makes sense: *Image 1* is a absolute url where the root points to the folder where I started the web server and *image 3* is a relative url relative to the actual html file.

Running the python script produces a pdf with only *image 3* included, which is the relative url from the actual html file. *Image 1* results in an image uri of `file:///imgs/python.png` which essentially the root of my c partition on windows if I'm not mistaken.

So I am wondering: Is this expected behaviour and should I solve this by creating a custom Url fetcher or is this a bug ?

**Comment by Tontyna** [comment]
Both, *image 2* and *image 3* are relative urls. It depends on the `base` url which of the images is found.

With no base url set I expect to see *image 3*, not *image 2*. Looks like your python server declares base url to be `root/` .

From the `make_pdf` python script I'd, expect to see *image 3*, only. 
To display *image 2* you'd have to call `HTML()` with a `base_url` parameter set to your `root` folder.

So I'm really surprised about *image 2* being in your PDF.

And yes, when PDF is rendered from a **filename** the absolute url of *image 1* expands to the root of the filesystem.

BTW: If WeasyPrint can't find an image it logs a `Failed to load image` error displaying the full file name it tried to load.

**Comment by sander76** [comment]
@Tontyna Thanks for pointing out my mistake. I mixed up 2 and 3 (even after double checking the post... sigh...)

So I will be creating a custom Url fetcher.

**Comment by sander76** [comment]
Put something together as a new url fetcher:

```python
def root_path_fetcher(root: Path):
    root_uri = root.as_uri().lower()

    def wrapper(url):
        LOGGER.debug("incoming url %s", url)

        if url.startswith("http"):
            return default_url_fetcher(url)

        lower_url = url.lower()
        if not lower_url.startswith(str(root_uri)):
            LOGGER.debug("appending base url")
            url = urlparse(url)
            url = "/".join((root_uri, url.path))
            LOGGER.debug(url)

        return default_url_fetcher(url)

    return wrapper
```

Not too happy about it, but it seems to do the job...

**Comment by Tontyna** [comment]
Why not make your htmls use relative urls, i.e. avoid urls starting with  `/`?

**Comment by sander76** [comment]
@Tontyna I have little to no control over that. I use MkDocs as a static site generator who handles PDF generation.
