### ISSUE TITLE
No-break spaces (&nbsp;) sometimes get hyphenated at a line break

### ISSUE THREAD

**Issue by bert-github** [Kozea/WeasyPrint#748]
Weasyprint (version 43, on Debian 9.6 "Stretch") sometimes breaks a line after a no-break space (\&nbsp;) and adds a hyphen. E.g., in this document:
```html
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <title>Test</title>
  <style>
     @page {size: 10cm 15cm; margin: 2cm}
     body {font-size: 12pt; hyphens: auto}
  </style>
  <p>Does this break in 12&nbsp;point
   fonts?
```
See the attached PDF. (The sizes may have to be adjusted, depending on what the default font is.)
[tmp.pdf](https://github.com/Kozea/WeasyPrint/files/2649856/tmp.pdf)

**Comment by liZe** [comment]
@bert-github Hello!

WeasyPrint's hyphenation is a bit stupid and splits words using line-break opportunities, instead of taking care of punctuation characters.

This issue shares its root problem with #109.

**Comment by liZe** [comment]
Hyphenation should now be fixed when used with various punctuation characters. If you find another broken example, I'll be happy to add one more test and to fix it!
