### ISSUE TITLE
Is it possible to add image using 'content', if i read url from html?

### ISSUE THREAD

**Issue by stmadm** [Kozea/WeasyPrint#749]
I could not see tutorial how to add image, if i read url from html attr? 

next I would like to add image to header.

for example:
html:
`<div class="logo" data-image-src="images/logo.png"></div>`

css:
`@page { 
              @top-left {
				 content: url(attr(data-image-src url))}`
				}	
}`

\- its not really code, I just want to show logic

or you can suggest another solution, but url is read from html.

Why am I using "content"? I want to add image to header

**Comment by Tontyna** [comment]
The only means of adding content to the `@page` margins is via "content" attribute. But this attribute is limited to **strings**. No chance to add an image.

You'll have to resort to elements with 'position:fixed`.

**Comment by Tontyna** [comment]
...shame on me, forgot the `content: url()` syntax...

**Comment by liZe** [comment]
@stmadm Does it work for you?

**Comment by liZe** [comment]
> @stmadm Does it work for you?

Let's say it does. Please reopen this issue if needed.
