### ISSUE TITLE
Add support for inline SVG

### ISSUE THREAD

**Issue by barryvan** [Kozea/WeasyPrint#75]
At the moment, to use SVG within WeasyPrint, you need to embed it (generally via an <img> tag). It'd be really useful if WeasyPrint could handle inline SVG as well.

In other words, one should be able to do the following:

```
<!doctype html>
<svg style="width: 100px; height: 100px;">
  <rect width="100px" height="100px" style="fill: #c00"/>
</svg>
```

and get a red square.

In our particular scenario, we're generating HTML for WeasyPrint by performing an XSLT transformation on an XML document -- and in some scenarios, we're hoping to generate SVG graphics (bar charts and the like) dynamically as part of this.

**Comment by diethardsteiner** [comment]
Please add inline SVG support.

**Comment by graingert** [comment]
@SimonSapin would it be possible to use `premailer` to flatten all the CSS directly onto attributes of the SVGs?

**Comment by SimonSapin** [comment]
@diethardsteiner There is no disagreement that this feature is desired. It’s mostly a matter of "someone" doing the work.

@graingert I don’t see why premailer wouldn’t work, but I don’t see either how it helps at all with inline SVG not being supported by WeasyPrint. Note that "inline" means different things in the context of premailer (`style` HTML attributes instead of stylesheets with selectors) and in the context of this issue (`<svg>` elements in an HTML document instead of `<img>` or `<object>` elements referencing an external SVG document).

**Comment by graingert** [comment]
This only fixes the issue that using passing a subtree would cause.

**Comment by SimonSapin** [comment]
Oh, I see. Yes, I suppose we could extract a subtree, "flatten" sytelsheets into `style` attributes, and give that to CairoSVG. Though I’d rather have the "flattening" done by re-using WeasyPrint’s existing CSS parsing and Selector matching code than using Premailer.

**Comment by diethardsteiner** [comment]
@SimonSapin Ok thanks for your feedback

**Comment by graingert** [comment]
@SimonSapin where in the code is both the html tree and the cario context available?

**Comment by SimonSapin** [comment]
@graingert The cairo context for the document (as opposed to contexts for intermediate surfaces used at various points) is created in the `write_*` methods (such as `write_pdf`) of the `Document` class in `weayprint/document.py`. But by the time that code is called, layout is entirely done and the HTML tree is not kept around anymore. We could pass it through so that it’s still available there, but modifying it at that point wouldn’t affect already-done layout.

**Comment by graingert** [comment]
@SimonSapin is it possible to just keep hold of the SVG fragments during the layout processing? So we can at least get it working by pretending the SVG is just an embedded image?

**Comment by SimonSapin** [comment]
I don’t have an answer to that right now, sorry. (I’m not as involved in WeasyPrint as I used to be, so I won’t be spending a lot of time to work on this or think about how it could be done.)

What I remember is that I thought that the CSS rendering and SVG rendering really should share their style system. (The thing that takes stylesheets and a DOM-like tree, matches selectors, runs the cascade, and gives one computed values for every property for every element.) Right now they’re completely separate (and somewhat duplicated) in WeasyPrint and CairoSVG.

But last I talked about merging the code bases, @liZe didn’t like the idea :)

**Comment by lutostag** [comment]
This is the code we are using for our specific use-case to inline the svgs generated by angular-nvd3.


(The selector for svgs was trickier due to namespacing, but I'm sure someone could figure it out). The issue is that it doesnt account for styling information, but got us to what we needed.


```diff
+from base64 import b64encode
+from lxml import etree
+
+    def svg_embed(html):
+        """For the child of nvd3 nodes (svg) munge them into b64encoded data
+        as a workaround for https://github.com/Kozea/WeasyPrint/issues/75"""
+        root = html.root_element
+        svgs = root.findall('.//nvd3')
+        for svg in svgs:
+            child = svg.getchildren()[0]
+            encoded = b64encode(etree.tostring(child)).decode()
+            encoded_data = "data:image/svg+xml;charset=utf-8;base64," + encoded
+            encoded_child = etree.fromstring('<img src="%s"/>' % encoded_data)
+            svg.replace(child, encoded_child)
+        return html
+
-    rendered = HTML(string=html, base_url=base_url).render()
+    rendered = svg_embed(HTML(string=html, base_url=base_url)).render()
```

**Comment by mr-katsini** [comment]
@liZe is there any possibility for this?

**Comment by liZe** [comment]
> @liZe is there any possibility for this?

Finding `svg` tags and rendering them as if they were embedded images seems to be somehow possible. But that's just a hack as it wouldn't handle CSS rules correctly (i.e. you would have to link stylesheets in the SVG file, not in the HTML file) and would probably introduce a lot of subtle problems that we can't imagine yet.

If anyone is interested in implementing that, I can give some advice, it's a good way to start hacking WeasyPrint.

**Comment by liZe** [comment]
The feature has been added in version 53.0. There are lots of limitations and bugs related to this initial support, but things will improve with time.

Please try version 53, and open new issues with the specific problems you may meet!
