### ISSUE TITLE
Digital signature

### ISSUE THREAD

**Issue by hejsan** [Kozea/WeasyPrint#752]
I'd like to ask for digital signatures to be supported in WeasyPrint.
See [wikipedia](https://en.wikipedia.org/wiki/Digital_signature) for definition.
Not to be confused with superimposing a scanned handwritten signature, a digital signature would allow anyone holding a public key to verify that the pdf has not been tampered with and was indeed produced by whoever.

My use case:
I work for a university and have used WeasyPrint to implement all of our certificates and transcripts.
The university wants to allow students to send out these documents themselves without the need to print them out and sign and stamp them.
The recipient could then upload the document to some page on our site where a simple verification routine would tell them if the document is untampered with and authentic.

I include these examples of implementations in php:
https://manuals.setasign.com/setapdf-signer-manual/the-main-class/#index-4-1
https://tcpdf.org/examples/example_052/
(relevant implementation: https://github.com/tecnickcom/TCPDF/blob/master/tcpdf.php#L13411 and https://github.com/tecnickcom/TCPDF/blob/master/tcpdf.php#L7564)
https://www.kryptokoder.com/signwithext.html

This document from Adobe explains how the PDF standard wants the signature to be structured: https://www.adobe.com/devnet-docs/acrobatetk/tools/DigSig/Acrobat_DigitalSignatures_in_PDF.pdf

I'm not sure if this feature request fits with the main goal of WeasyPrint, i.e. to be able to structure pdf's via html+css but a utility function providing this functionality would certainly make life easier and help avoiding having to add another huge library dependency.

Also if anyone knows of a simple command line utility providing PDF-standard compliant signatures I'd love to hear about it.

**Comment by liZe** [comment]
> I include these examples of implementations in php:

Thanks a lot, it gives a good idea about how to add digital signature to a PDF file. Looks like it's possible with our simple PDF post-processor (in https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/pdf.py).

> I'm not sure if this feature request fits with the main goal of WeasyPrint, i.e. to be able to structure pdf's via html+css but a utility function providing this functionality would certainly make life easier and help avoiding having to add another huge library dependency.

If it can be included with a small amount of maintainable code (and it probably can), there's no problem to include this feature.

**Comment by hejsan** [comment]
Great.
Trying to learn to navigate your code, would it be added as a public function to the PDF.py file similar to write_pdf_metadata()? (https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/pdf.py#L479)
Something like:
`def digitally_sign(pdf, signing_cert, private_key, ...):`
Where the first param is an instance of PDFFile?

**Comment by liZe** [comment]
> Something like:
> `def digitally_sign(pdf, signing_cert, private_key, ...):`
> Where the first param is an instance of PDFFile?

Definitely.

**Comment by hejsan** [comment]
I'm trying to take a stab at this but am running into issues using the PDFFile class to open a PDF generated with WeasyPrint.
It asserts on line 160 because the first_object is not 0. Looking at the PDF I see two trailers at the end and that likely causes the error:
```
trailer
<< /Size 33
   /Root 32 0 R
   /Info 31 0 R
>>
startxref
25108
%%EOF
31 0 obj
<< /Producer (.... \))
/Title (þÿ...t)/Author (þÿ)/Keywords (þÿ) >>
endobj
xref
31 1
0000025855 00000 n 
trailer
<< /Size 33 /Root 32 0 R /Info 31 0 R /Prev 25108 >>
startxref
26048
%%EOF
```
Could someone explain what is happening? Is there a regression in this version of WeasyPrint causing it not to be able to read pdf's generated by itself?

**Comment by liZe** [comment]
As far as I can remember, multiple trailers is a common feature in PDF documents: it enables users to edit documents by adding new objects or new versions of existing objects and a new table of contents (listing indexes of objects) at the end of the document, without touching anything from the original document.

PDFFile is a class designed to read PDF documents generated by Cairo, but not the ones generated by WeasyPrint :open_mouth:. You should add the signature in `pdf.write_pdf_metadata`, it's probably the easiest thing to do.

**Comment by hejsan** [comment]
Oh, I was under the impression that WeasyPrint used Cairo to generate the entire PDF's but I see now that it directly adds data after the cairo processing is done.
I'll proceed as you suggest.
