### ISSUE TITLE
Type conversion error when having side margins set to auto

### ISSUE THREAD

**Issue by mousavian** [Kozea/WeasyPrint#754]
Hey,
There's some cases where margins are set to `auto` and the code will raise an exception on [this line](https://github.com/Kozea/WeasyPrint/blob/43800519e79f043cf55f196160a7cb58c8bd1690/weasyprint/layout/flex.py#L48) complaining about not being able to convert `str` to `float`.

I don't have the exact error now ( I can provide later if you need ) but some sample pages I was trying to convert PDF which faced this issue are: 
- https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/
- https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/

Hopefully that will be sufficient to replicate the error.

Let me know if I can help with raising a PR and do something [similar to this](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/layout/flex.py#L91-L94) but I am not sure if that is the correct approach or not.

Thanks.

**Comment by liZe** [comment]
Duplicated by (now fixed) #800.
