### ISSUE TITLE
Nested flex boxes no longer working

### ISSUE THREAD

**Issue by tokyovigilante** [Kozea/WeasyPrint#756]
Seems to be releated to #673, however this time the right-aligned text is pushed too far right halfway off the page. The following commit is implicated:

commit 01b09c6
```(env) [Sat 11:49am] ryan ~/Projects/Develop/WeasyPrint/$ git bisect bad
01b09c6136179a2a3e74473d73d0bb6d90ac441c is the first bad commit
commit 01b09c6136179a2a3e74473d73d0bb6d90ac441c
Author: Guillaume Ayoub <guillaume.ayoub@kozea.fr>
Date:   Thu Aug 30 18:57:04 2018 +0200

    Fix crashes in flex layout

:040000 040000 b777414d70e5c1d887a91ff6fe97a2aed84722ac 5e7a77faa8da51ed3614b14b16db4449ac7fa52e M	weasyprint
```

Same sample code in that commit shows the bug. Sorry I never got a chance to accomplish much in the way of flexbox tests, probably would have caught this :/

**Comment by mojimi** [comment]
I have this same issue, by removing the flex from the inner elements it worked again.

**Comment by liZe** [comment]
It's fixed since version 46 :smile:.
