### ISSUE TITLE
WeasyPrint For .Net on Windows

### ISSUE THREAD

**Issue by balbarak** [Kozea/WeasyPrint#759]
I have created a .Net wrapper for WeasyPrint at https://github.com/balbarak/WeasyPrint-netcore

The library has embedded all necessary libraries for WeasyPrint without any extra installation required

1- WeasyPrint
2- Python 3.6
2- Gtk3  

Feel free to contribute

**Comment by liZe** [comment]
Thanks a lot! We should add a comment about that (and other projects such as Django-WeasyPrint, Flask-WeasyPrint…) in the documentation.

**Comment by tdextrous** [comment]
Where would be a good spot to add this in the documentation?

**Comment by liZe** [comment]
> Where would be a good spot to add this in the documentation?

Probably somewhere in the [Windows section of the install page](https://github.com/Kozea/WeasyPrint/blob/master/docs/install.rst#windows).

**Comment by liZe** [comment]
Closed by #899.
