### ISSUE TITLE
Downloading pdf with button

### ISSUE THREAD

**Issue by fevzican** [Kozea/WeasyPrint#761]
I create a page with django and when i click the download button it generates a pdf in a view. So i want to download this file, actually i return the file byte string, but i cant handle on html page.
```
pdf_file=html.write_pdf(stylesheets=[css],
font_config=font_config,presentational_hints=True)
print(pdf_file)
response = HttpResponse(pdf_file,content_type='application/pdf;')
response['Content-Disposition'] = 'inline; filename=list_people.pdf'
response['Content-Transfer-Encoding'] = 'binary'
return response
```

In html page, i have these codes:
```
pdfAsDataUri = "data:application/pdf;base64,"+response;
window.open(pdfAsDataUri);
```
but nothing occurs, i know it can be dumb question, but i struggle with this for one hour.

**Comment by liZe** [comment]
Hello!

I'm not sure to fully get your problem, here's what I understand:

You have a Django web app with a URL generating a PDF file. This URL works but the PDF is displayed by the browser PDF viewer, and you want the app users to be able to download this PDF.

Is that what you want?

**Comment by fevzican** [comment]
ok, i got it. i converted to base64 with:
```
    import base64

    encoded_string = base64.b64encode(pdf_file)
```
