### ISSUE TITLE
Percentage width is not working

### ISSUE THREAD

**Issue by darodriguez1994** [Kozea/WeasyPrint#766]
Percentage width is not working in tables with the latest release. I just update to the latest release and the percentage widths in my tables don't work anymore. I would appreciate any help. Thanks.

**Comment by liZe** [comment]
Hello! Thanks for taking the time to report your issue.

Could you please provide an HTML sample showing the problem?

**Comment by liZe** [comment]
@darodriguez1994 Can I close this issue?

**Comment by laggardkernel** [comment]
I encounter the same problem. It seems the percent width doesn't work on `table`s.

**Comment by liZe** [comment]
> Changing `width="33%"` to `style="width:33%"` fixed my problem.

You can also use the `--presentational-hints` option to get `width="33%"` working.

Have fun!
