### ISSUE TITLE
server running error

### ISSUE THREAD

**Issue by amarnav** [Kozea/WeasyPrint#767]
/home/nav168/venv/lib/python3.6/site-packages/weasyprint/document.py:34: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '

**Comment by liZe** [comment]
Hello,

This message is just a warning, not an error, and shouldn't prevent WeasyPrint from working.

**Comment by liZe** [comment]
@amarnav Can I close this issue?

**Comment by danielmartinezruiz** [comment]
Just a question about this warning. Is there any way to hide it when executing WeasyPrint?

**Comment by liZe** [comment]
> Just a question about this warning. Is there any way to hide it when executing WeasyPrint?

Good idea, I've just added a `--quiet` parameter.

**Comment by danielmartinezruiz** [comment]
Thank you very much!
