### ISSUE TITLE
Question: Looks like the output PDF is of version 1.5, my usecase requires 1.6. Is this possible?

### ISSUE THREAD

**Issue by TheDynomike** [Kozea/WeasyPrint#768]

**Comment by liZe** [comment]
As we rely on Cairo to generate PDF files, there's no easy way to change this directly in WeasyPrint.

But. If 1.6 is backward compatible with 1.5 (I suppose it is in most cases), changing the first line of the PDF should do the trick.

**Comment by liZe** [comment]
@TheDynomike Can I close this issue?

**Comment by TheDynomike** [comment]
Yes, thank you
