### ISSUE TITLE
Debianizing WeasyPrint

### ISSUE THREAD

**Issue by anasram** [Kozea/WeasyPrint#769]
Are you planing to add WeasyPrint to Debian/Ubuntu repositories?

Please think of dependency nightmare when user installs it manually, i.e. using `pip install weasyprint` command.

**Comment by liZe** [comment]
WeasyPrint has been packaged for many distributions, it's strange to see that no official Debian package has been created yet.

Distribution packages are generally created by people using the distribution. There's already a couple of requests for package ([1](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917038), [2](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844046)) but nobody took the time to package it and include it in Debian yet. You can kindly ask there if anyone is working on it, or possibly propose your help.
