### ISSUE TITLE
PDF metadata

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/WeasyPrint#77]
Suggested mapping of HTML metadata to PDF metadata:

`<title>` → Title
`<meta name=author>` → Author
Maybe? `<meta name=description>` → Subject
`<meta name=keywords>` → Keywords
`<meta name=generator>` → Creator
"WeasyPrint vX.Y" → Producer
`<meta name=dcterms.created>` → CreationDate
`<meta name=dcterms.modified>` → ModDate

Relevant specs:
http://www.whatwg.org/specs/web-apps/current-work/multipage/semantics.html#the-title-element
http://www.whatwg.org/specs/web-apps/current-work/multipage/semantics.html#standard-metadata-names
http://wiki.whatwg.org/wiki/MetaExtensions

**Comment by liZe** [comment]
It may be added to cairo: https://lists.cairographics.org/archives/cairo/2016-September/027755.html
