### ISSUE TITLE
Handle box-decoration-break

### ISSUE THREAD

**Issue by stolzweb** [Kozea/WeasyPrint#771]
i know there is the closed issue #139. But i think i really don't have a chance to solve my problem without this css "box-decoration-break". In the attached Screen you can see the splitted grey box. On the second page the text starts at the top of the grey box, but i need there a padding between box and text. The grey box has a padding-top, but that does not help. Is there a possibility to solve this problem? I also would pay for the implementation :)
![unbenannt-1](https://user-images.githubusercontent.com/36608478/51410163-1553be00-1b64-11e9-86d9-3fb4ddf50132.jpg)

**Comment by liZe** [comment]
> i know there is the closed issue #139.

That was 5 years ago. It's time to think of this now :smile:.

> Is there a possibility to solve this problem?

Yes, you're right, `box-decoration-break` is what you need.

> I also would pay for the implementation :)

Thank you! If you're interested, you can [contribute to our Patreon campaign](https://www.patreon.com/kozea). Some tiers give you the possibility to select an issue we'll work on. It's monthly donation but you can stop when you want.

**Comment by liZe** [comment]
We should be able to fix #115 too.

**Comment by liZe** [comment]
I'm currently working on it on the [`box-decoration-break` branch](https://github.com/Kozea/WeasyPrint/tree/box-decoration-break). It's far from being perfect for now, but it should fix your use case already. Feel free to test and tell me if it works!

**Comment by liZe** [comment]
What's left to do:
- [ ] fix backgrounds (will probably never be done)
- [ ] check inline boxes
- [ ] fix #115
- [ ] add tests

**Comment by liZe** [comment]
@stolzweb I'll add tests and merge the branch into master if everything goes well. I won't implement the background part of the spec if you're not interested in it. Feel free to test and tell me if everything's OK for you!

**Comment by stolzweb** [comment]
Sorry i was verry busy the last view months with other projects. Thanks a lot for doing this great job! I just tested it in my project. There are some tiny issues which eventually could be fixed. 
 - my grey box has a padding of 4mm and a margin-bottom of 4mm, inside this grey box is sometimes a table, while cutting the table, For my it looks like the padding bottom is not added after cutting the table.

![Unbenannt](https://user-images.githubusercontent.com/36608478/54635863-72e18980-4a85-11e9-9bf7-fe695e5fcc54.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/36608478/54635864-72e18980-4a85-11e9-9f6e-782720b7fb20.PNG)

**Comment by liZe** [comment]
> Sorry i was verry busy the last view months with other projects.

No problem!

> * my grey box has a padding of 4mm and a margin-bottom of 4mm, inside this grey box is sometimes a table, while cutting the table, For my it looks like the padding bottom is not added after cutting the table.

Small sample showing the problem:
```html
<style>
  @page { size: 80px; margin: 0 }
  body { margin: 0 }
  table { border: 0; border-collapse: collapse }
  td { background: red; border: none; height: 20px; padding: 0 }
  section { padding: 10px; background: yellow; margin: 5px; box-decoration-break: clone }
</style>
<section>
  <table>
    <tr>
      <td>a</td>
    </tr>
    <tr>
      <td>b</td>
    </tr>
    <tr>
      <td>c</td>
    </tr>
    <tr>
      <td>d</td>
    </tr>
  </table>
</section>
```

**Comment by liZe** [comment]
> my grey box has a padding of 4mm and a margin-bottom of 4mm, inside this grey box is sometimes a table, while cutting the table, For my it looks like the padding bottom is not added after cutting the table.

This problem has been fixed when using `box-decoration-break: clone`.

What's sad is that with `slice` (the default value, the default case before `box-decoration-break` was supported) the box may go further than the bottom of the page if the bottom padding or border is too wide. The bug is in WeasyPrint since the beginning and is not easy to fix, but it shouldn't bother you.

I've added a passing test for your `clone` case and a failing test for the `slice` case.

If everything's OK for you, I'll release the current master branch as version 46.

**Comment by stolzweb** [comment]
Hi Guilllaume

Thanks a lot. It is perfect! Looking forward to the version 46

br
manuel

Herzliche Grüsse

Manuel Stolz
_______________________
Stolz WEB GmbH
Davidstrasse 40
9000 St. Gallen

T: +41 (0)71 511 38 20
F: +41 (0)71 511 38 29
Skype: stolzweb
www.stolzweb.ch

------ Originalnachricht ------
Von: "Guillaume Ayoub" <notifications@github.com>
An: "Kozea/WeasyPrint" <WeasyPrint@noreply.github.com>
Cc: "stolzweb" <info@stolzweb.ch>; "Mention" 
<mention@noreply.github.com>
Gesendet: 20.03.2019 13:40:52
Betreff: Re: [Kozea/WeasyPrint] Handle box-decoration-break (#771)

**Comment by liZe** [comment]
Version 46 has been released!

**Comment by stolzweb** [comment]
thanks a lot

Herzliche Grüsse

Manuel Stolz
_______________________
Stolz WEB GmbH
Davidstrasse 40
9000 St. Gallen

T: +41 (0)71 511 38 20
F: +41 (0)71 511 38 29
Skype: stolzweb
www.stolzweb.ch

------ Originalnachricht ------
Von: "Guillaume Ayoub" <notifications@github.com>
An: "Kozea/WeasyPrint" <WeasyPrint@noreply.github.com>
Cc: "stolzweb" <info@stolzweb.ch>; "Mention" 
<mention@noreply.github.com>
Gesendet: 20.03.2019 17:43:10
Betreff: Re: [Kozea/WeasyPrint] Handle box-decoration-break (#771)

**Comment by stolzweb** [comment]
Hi

What do i have to do to force the "text-overflow: ellipsis" issue? :)

br
manuel
_______________________
Stolz WEB GmbH
Davidstrasse 40
9000 St. Gallen

T: +41 (0)71 511 38 20
F: +41 (0)71 511 38 29
Skype: stolzweb
www.stolzweb.ch

------ Originalnachricht ------
Von: "Guillaume Ayoub" <notifications@github.com>
An: "Kozea/WeasyPrint" <WeasyPrint@noreply.github.com>
Cc: "stolzweb" <info@stolzweb.ch>; "Mention" 
<mention@noreply.github.com>
Gesendet: 20.03.2019 17:43:10
Betreff: Re: [Kozea/WeasyPrint] Handle box-decoration-break (#771)
