### ISSUE TITLE
Possible to override URL generation for anchor tags?

### ISSUE THREAD

**Issue by zhaoterryy** [Kozea/WeasyPrint#772]
I have a project that converts mkdocs generated HTMLs to PDFs. I would like to implement custom logic/override the (current) behavior of converting the relative hrefs to absolute. Something like `url_fetcher`.

For example: `<a href="dev/overview.html"> -> /A (dev/overview.pdf) or /A (#overview)`

From digging around in the code I found: https://github.com/Kozea/WeasyPrint/blob/f67b7a6083a3c47d76c27f12fff7ef975566f7ef/weasyprint/urls.py#L116

I'm thinking we could add a custom behavior handler in there? Would a PR for this be accepted?

Thanks for this great project Kozea team!

**Comment by liZe** [comment]
Hello!

> I'm thinking we could add a custom behavior handler in there? Would a PR for this be accepted?

The idea is good, but I'm afraid of the number of functions we'll have to change to handle this the way it's done with `url_fetcher`.

As I was suggesting on IRC, pre-processing the HTML file is probably an easier way to solve your problem. Unlike `url_fetcher` that is a (configurable) behavior of the web engine, changing the links is equivalent to "just" changing the value of the `href` attributes in the source. I think that this can be done with a really small amount of code using `html5lib`, without interfering with WeasyPrint.

What do you think of that?

> Thanks for this great project Kozea team!

:heart:

**Comment by zhaoterryy** [comment]
Thanks for the prompt reply!

The thing preventing me from pre-processing the HTML file is that I want to keep the url's relative - like the way it behaves when no base_url is passed to HTML(). Without base_url passed in css files error at:

https://github.com/Kozea/WeasyPrint/blob/f67b7a6083a3c47d76c27f12fff7ef975566f7ef/weasyprint/urls.py#L144-L145

Well.. I could make those URIs absolute during the pre-processing. 🤔 

Ok if there aren't any other suggestions feel free to close this! 👍

**Comment by liZe** [comment]
> Well.. I could make those URIs absolute during the pre-processing.

You can add a [`<base>`](https://developer.mozilla.org/docs/Web/HTML/Element/base) tag to set the base URL of your relative links. I'm not sure that it's helpful for you, but…

**Comment by zhaoterryy** [comment]
Fixed the issue using a pre-processor. Thanks! ❤️
