### ISSUE TITLE
Quotes in links make Cairo crash

### ISSUE THREAD

**Issue by liZe** [Kozea/WeasyPrint#774]
When trying to render
```html
<a href="'">
```
we get `cairocffi.CairoError: cairo returned CAIRO_STATUS_TAG_ERROR: b'invalid tag name, attributes, or nesting'`.

**Comment by Northshoot** [comment]
getting same error 

`cairocffi.CairoError: cairo returned CAIRO_STATUS_TAG_ERROR: b'invalid tag name, attributes, or nesting'`

**Comment by liZe** [comment]
> getting same error

This error can appear for different reasons. You can try the current master branch and see if it fixes your problem.
