### ISSUE TITLE
HTML to PDF failed when table image is located between two page

### ISSUE THREAD

**Issue by sGeeK44** [Kozea/WeasyPrint#778]
Hi,

When I render html to pdf and image that should appear between two page. Pdf produce was invalid (unable to read with any pdf reader). After many hour to understand this, to solve problem I had put this in html style:
```
@page {
   size: A4; /* Change from the default size of A4 */
}
```

Could you maybe provide proper error in this case ?

**Comment by liZe** [comment]
Hello!

Could you please provide an example (HTML, CSS, images)? This style shouldn't change anything, as the default page size is … A4 :smile:.

**Comment by liZe** [comment]
@sGeeK44 Feel free to reopen if there's something new about this.
