### ISSUE TITLE
Export via PHP (or anything able to execute command lines)

### ISSUE THREAD

**Issue by jfcartier** [Kozea/WeasyPrint#781]
I know PHP isn't related to the WeasyPrint project, but since WeasyPrint is the best alternative to [wkhtmltopdf](https://wkhtmltopdf.org/), I think it's important to bring up this topic here. 

I try to use the [exec](http://php.net/manual/fr/function.exec.php) command from PHP. It normally mimic a command line. The problem here is that it doesn't work and I try to seek why. I don't necessary need you to provide me a PHP solution here. I just need to know if it's only possible to call a weasyprint command via another place than the terminal itself. I wonder why i get those errors 

![screen shot 2019-01-31 at 1 05 50 am](https://user-images.githubusercontent.com/3603641/52036491-353b9800-24fb-11e9-81fb-4d2cbc48a9b8.png)

I'd be grateful to have at least an hypothesis. Thanks!

For the curious, here's the command I run in PHP 

`<?php echo exec('/usr/local/bin/weasyprint --version'); ?>`

**Comment by liZe** [comment]
The error you get is "Unknown locale: UTF-8". It means that there's a problem with the locale used by the user launching your PHP script.

It's not related to WeasyPrint, but to Python. You can reproduce the problem with this little script:
```python
import locale
locale.getdefaultlocale()
```

You probably have to change the PHP user's locale in a way or another. Searching "Unknown locale: UTF-8" with your favorite search engine will give you many reasons why this problem happens, and many solutions to solve it.

**Comment by jfcartier** [comment]
I saw this [very popular fix ](https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python). So I applyed it, but the thing is, there's no problem using weasyprint in command line. The problem occures when you need to execute a weasyprint command via another language (ie. php exec). 

I tried making a .sh script instead of calling weasyprint directly in php. The result is the same. Python seems to react differently weather it's called directly in console or via a script executer.

**Comment by jfcartier** [comment]
Alright, so heres the php code to add (before exec) to get rid of that locale error. @liZe you were 100% right.

```php
$locale = 'en_US.utf-8';
setlocale(LC_ALL, $locale);
putenv('LC_ALL='.$locale);
```

Thanks again
