### ISSUE TITLE
Can load image from media ??

### ISSUE THREAD

**Issue by RodrigoNegao** [Kozea/WeasyPrint#799]
Hi,

I using Weasyprint, and I like that patch, I have a problem, I can load the static image to PDF like that

`<img  src="{% static 'images/face.jpg' %}" alt="">`

but when I tried to load from media

`<img src="{{ user.IMAGE.url }}" alt="">`

it doesn't work.

Firstly, I tested in HTML the result that ok.

That my code to convert from Html to PDF:

```
# Rendered
html_string = render_to_string('pdfmodels/resumedownload.html', context) 
html = HTML(string=html_string, base_url=request.build_absolute_uri())

result = html.write_pdf()  

# Creating http response
response = HttpResponse(content_type='application/pdf;')
response['Content-Disposition'] = 'inline; filename=resumedownload.pdf'
response['Content-Transfer-Encoding'] = 'binary'
with tempfile.NamedTemporaryFile(delete=True) as output:
    output.write(result)
    output.flush()
    output.seek(0)
    response.write(output.read())
return response
```

Maybe the problem would be `base_url=request.build_absolute_uri()` argument to convert it to an absolute URL.

What the problem? Help plz.

**Comment by liZe** [comment]
Hello!

> I using Weasyprint, and I like that patch, I have a problem, I can load the static image to PDF like that
> 
> `<img class="facep src="{% static 'images/face.jpg' %}" alt="">`
> 
> but when I tried to load from media
> 
> `<img src="{{ user.IMAGE.url }}" alt="">`
> 
> it doesn't work.

This code is not HTML, it's a template from a web framework, so I won't be able to help you :disappointed: as it's not a problem in WeasyPrint.

You have to know what URL `request.build_absolute_uri()` and `user.IMAGE.url` give. The URL of your image is `request.build_absolute_uri() + user.IMAGE.url`, you have to understand why WeasyPrint can't retrieve it.

**Comment by RodrigoNegao** [comment]
> 
> 
> Hello!
> 
> > I using Weasyprint, and I like that patch, I have a problem, I can load the static image to PDF like that
> > `<img class="facep src="{% static 'images/face.jpg' %}" alt="">`
> > but when I tried to load from media
> > `<img src="{{ user.IMAGE.url }}" alt="">`
> > it doesn't work.
> 
> This code is not HTML, it's a template from a web framework, so I won't be able to help you 😞 as it's not a problem in WeasyPrint.
> 
> You have to know what URL `request.build_absolute_uri()` and `user.IMAGE.url` give. The URL of your image is `request.build_absolute_uri() + user.IMAGE.url`, you have to understand why WeasyPrint can't retrieve it.

Hello @liZe ,
Thanks to answering me, I going to find something about that, i will read again the docs, when I found, I answer you ,thanks again

**Comment by liZe** [comment]
@RodrigoNegao Did you find a solution to your problem?

**Comment by RodrigoNegao** [comment]
Hello @liZe 
Sorry answer so late,
 I think a solution , but I didn't test it.
This command `{{ user.IMAGE.url }}` , use to loading url about a picture from user, because that django need a authentication .
I was reading Weasyprint again the document and found the topic call  "[URL fetchers](https://weasyprint.readthedocs.io/en/latest/tutorial.html#url-fetchers)" and said that

> The default fetcher can natively open file and HTTP URLs, but the HTTP client does not support advanced features like cookies or **authentication**.

Maybe that is the problem,
I will create a method to can use the url without authentication.
Thanks to ask.

**Comment by liZe** [comment]
If you want to work around Django authentication, you can use [Django-WeasyPrint](https://github.com/fdemmer/django-weasyprint) that will automatically use an URL fetcher that gets static files from the disc and not from HTTP requests.

**Comment by RodrigoNegao** [comment]
> Hi,
> 
> I using Weasyprint, and I like that patch, I have a problem, I can load the static image to PDF like that
> 
> `<img src="{% static 'images/face.jpg' %}" alt="">`
> 
> but when I tried to load from media
> 
> `<img src="{{ user.IMAGE.url }}" alt="">`
> 
> it doesn't work.
> 
> Firstly, I tested in HTML the result that ok.
> 
> That my code to convert from Html to PDF:
> 
> ```
> # Rendered
> html_string = render_to_string('pdfmodels/resumedownload.html', context) 
> html = HTML(string=html_string, base_url=request.build_absolute_uri())
> 
> result = html.write_pdf()  
> 
> # Creating http response
> response = HttpResponse(content_type='application/pdf;')
> response['Content-Disposition'] = 'inline; filename=resumedownload.pdf'
> response['Content-Transfer-Encoding'] = 'binary'
> with tempfile.NamedTemporaryFile(delete=True) as output:
>     output.write(result)
>     output.flush()
>     output.seek(0)
>     response.write(output.read())
> return response
> ```
> 
> Maybe the problem would be `base_url=request.build_absolute_uri()` argument to convert it to an absolute URL.
> 
> What the problem? Help plz.

I solve the problem,
the problem was 
`html_string = render_to_string('pdfmodels/resumedownload.html', context , request=request) `
Answer: **request=request**
The recommended method is to pass request when you call render_to_string. Django will then render the template with a request context. 

Obs: Im tested at Localhost works, but _pythonanywhere.com_ don't works cause some heavy processing

Source: [https://stackoverflow.com/questions/36488024/the-context-instance-argument-of-render-to-string-is-deprecated#36488142](url)
[https://help.pythonanywhere.com/pages/AsyncInWebApps](url)

Sorry to late
