### ISSUE TITLE
Error when trying to print PDF document

### ISSUE THREAD

**Issue by kummerer94** [Kozea/WeasyPrint#801]
Hey everyone,

I've been having fun with a particularly nasty bug. The good news is: I know one cause and there is an easy fix.

The story is that we have been using Weasyprint to generate PDF reports in our firm (it works beautifully and the documents look great without the hustle of using LaTeX). However, someone was reporting back to us that there was an error when he tried to print the PDF we sent to him. The error occurred in Adobe Acrobat Reader DC and says:

> An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem.

This error is strange since the generated PDF is perfectly fine and opens with no problems. But when trying to print, one would get this error.

Upon investigation, the problem was the following: we are displaying page numbers at the top of the page like in the example financial report. This works with the following SCSS:

```
@page {
  @top-left {
    content: counter(page);
    background: white;
    height: 1cm;
    text-align: center;
    width: 1cm;
    font-weight: bold;
    color: black;
  }

  @top-center {
    content: "";
    background: white;
    display: block;
    height: 0.05cm;
    opacity: 0.5;
    width: 100%;
  }

  @top-right {
    content: "Test";
    font-size: 9pt;
    height: 1cm;
    vertical-align: middle;
    color: grey;
    font-weight: bold;
    width: 100%;
  }
}
```

What you see here is that I removed the background from this element since we did not need it. What I found out later was that this seems to cause the problem. Whenever you try to generate a PDF in Weasyprint that includes this CSS but without the background property for the `@top-left` part, you run into the error from above. The fix is easy: just specify the background color as white or whatever you like.

Interestingly, when you specify `background: transparent` it does not fix the error. Also, when you remove `@top-center` and `@top-right` clauses, it also fixes the error.

I just wanted to share this with you guys since I did not find anything about this particular error online and other people may run into this.

Is there a reason for this strange behaviour? I am not really into PDF generation - but maybe one could set a default property?

Thank you in advance!

Alex

PS: I used the following jinja2 HTML. Just some default stuff with jinja.

```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="report.css" rel="stylesheet">
    <title>Report</title>
    <meta name="description" content="Report example">
  </head>

  <body>
    <article>
      <section>
        <h1>
          Test
        </h1>
      </section>
    </article>

    <article>
      <h2>Testing something</h2>
      <section>
        {{ lipsum(5) }}
      </section>
    </article>
    
    <article>
      <h2>Testing something</h2>
      <section>
        {{ lipsum(5) }}
      </section>
    </article>
    
    <article>
      <h2>Testing something</h2>
      <section>
        {{ lipsum(5) }}
      </section>
    </article>
  </body>
</html>


```

**Comment by liZe** [comment]
Hello!

Thanks a lot for the details. It's probably a problem with cairo, the library used to generate PDF files. Unfortunately, the PDF I can generate from your example seems to be OK, even for GhostScript. Could you please provide a "broken" PDF?

You can also try to update cairo (if you can) and see if it fixes your problem.

**Comment by kummerer94** [comment]
Sadly, I cannot update my cairo version as I am on a Windows system. But thanks for the tip!

**Comment by Tontyna** [comment]
> Sadly, I cannot update my cairo version as I am on a Windows system

What? Why? I mean: Of course it's possible to update Cairo on Windows

**Comment by kummerer94** [comment]
At the moment it is not worth the time and effort for me - that is what I should have said and what I meant. I used the installation provided by GTK.

**Comment by Yanal-Yves** [comment]
When opening the PDF I am generating for my application, I had the same error message in Adobe Acrobat Reader DC.
I have updated my installation of [GTK by using the installer pointed by the current version of Weasyprint documentation ](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases/download/2020-11-22/gtk3-runtime-3.24.23-2020-11-22-ts-win64.exeand): no more message now !
