### ISSUE TITLE
Repo for WeasyPrint stand alone executable

### ISSUE THREAD

**Issue by cakebake** [Kozea/WeasyPrint#802]
Hello @liZe,

I'm planning a GitHub repository, which hosts binary executables from WeasyPrint and generates them via Travis CI and App Veyor for Linux, Windows and Mac (freezing with pyinstaller).

Later, I plan to use these binaries in a cross platform node.js wrapper. Include later in [my package for Atom](https://github.com/cakebake/markdown-themeable-pdf). For example, a PHP composer package would be also conceivable.

Is it ok for you to include the LICENSE file from your repository in the release download? The release / download would theoretically consist of two files.

As soon as I have something to show, ~~I would also link the repo here~~. If that fits for you possibly also on the README. This might make it easier for some users to "install" because they no longer have dependencies to python and so on...

WIP Repo: https://github.com/cakebake/weasyprint-stand-alone-executable

I would appreciate your feedback.

**Comment by liZe** [comment]
> Hello @liZe,

Hello @cakebake,

> I'm planning a GitHub repository, which hosts binary executables from WeasyPrint and generates them via Travis CI and App Veyor for Linux, Windows and Mac (freezing with pyinstaller).

Impressive!

> Is it ok for you to include the LICENSE file from your repository in the release download? The release / download would theoretically consist of two files.

LICENSE is included since version 45.

> If that fits for you possibly also on the README. This might make it easier for some users to "install" because they no longer have dependencies to python and so on...

Of course, as soon as it works, I'll be happy to add a link in the README and in the documentation.

> I would appreciate your feedback.

A lot of people (especially on Windows) would be really happy to have all-in-one binaries.

**Comment by cakebake** [comment]
It's harder than I thought. I'm having trouble with glib because WeasyPrint needs a relative new version of it. That means, that I have to deal with the static executable. The latter, however, leads to further problems - including licensing problems.

An executable file for a new Linux is possible, but glib must be installed. On older Linux with older glib errors occur.

I will consider the project for a while. Possibly. however, docker is the only sustainable way to ship WeasyPrint to the host system without dependencies.

**Comment by liZe** [comment]
> I will consider the project for a while. Possibly. however, docker is the only sustainable way to ship WeasyPrint to the host system without dependencies.

OK, no problem. Good luck!

**Comment by liZe** [comment]
@cakebake Did you find a way to generate executable files?

**Comment by cakebake** [comment]
> Did you find a way to generate executable files?

Unfortunately not good enough to cover all operating systems and their versions. I haven't given it up completely, but I'm not currently pursuing it.

My current status:

- https://github.com/cakebake/weasyprint-stand-alone-executable
- https://github.com/cakebake/weasyprint-dockerized
- https://github.com/cakebake/WeasyPrintFreezedWithDocker

With this status it is at least possible to run and use weasyprint without installation. But that would have to be fine-tuned.

**Comment by cakebake** [comment]
Initially it should be a replacement for [puppeteer](https://github.com/puppeteer/puppeteer)/[phantomjs](https://github.com/ariya/phantomjs) in [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf), because I don't like the result and performance for large files.

Currently I think that with WeasyPrint only a web service is possible to use it to generate PDFs in a desktop application. However, I have not yet implemented this. I am not sure if I want it. I take compliance with privacy standards very seriously.

**Comment by liZe** [comment]
We’ll try to improve the documentation instead of generating standalone executables for now. If anyone wants to add documentation (or even create executables), please let us know!
