### ISSUE TITLE
Install with Setuptools =40.8.x Fails

### ISSUE THREAD

**Issue by rmackinnon** [Kozea/WeasyPrint#806]
As of right now, this issue is fixed on master, but affects users of v43 and v44:

I found that when installing version <=v44 on recently up-to-date systems where setuptools-40.8.0 is installed, the install bails out on a ValueError reporting that the license entry can only be a string not a file.  In ``setuptools`` v40.8.x the entry in the setup.cfg entry for ``license`` can only be a string, and a new entry for ``license_file`` is used to point to a project file.  Again this is fixed on master but, is not on any other versions. I suppose an update to setup.py could be in order to catch the version of setuptools and use one ``setup.cfg`` versus another.

I cherry picked in the setup.cfg from master to my v44 repo locally, and things came up rainbows and kittens.

**Comment by kavdev** [comment]
Running into this as well. For searchability:
``ValueError: Only strings are accepted for the license field, files are not accepted``

**Comment by liZe** [comment]
It's time to release a new version.

**Comment by JulianLiederer** [comment]
+1

**Comment by liZe** [comment]
Released!
