### ISSUE TITLE
Page numbers starting from custom value

### ISSUE THREAD

**Issue by pfctdayelise** [Kozea/WeasyPrint#809]
Is it possible to have page numbers starting from a value other than 1? And adjust the 'pages' counter (or create your own) accordingly?

I have been reading a lot of the issues but it's not fully clear to me if it is possible and if so, how to achieve it.

I want to generate a pdf from page 2 so that I can later insert a cover page as page 1. I also want to adjust the total page account to match this (ie total pages = counter(pages) + 1)

Thanks!

**Comment by liZe** [comment]
Hello,

Thank you for this issue. It's actually a pretty old feature request, as it's a duplicate #93 (created in 2013). I hope I'll find the time to fix it one day…

**Comment by Tontyna** [comment]
@pfctdayelise Actually, you **can** manipulate the `page` counter the way you want.
The total `pages` counter is another story. Cannot be reset or incremented because the spec forbids it, see #93, #289, #631...

**Comment by pfctdayelise** [comment]
OK well here is my worked example for my own benefit. ;) Thanks for your replies. I am not sure why I need to do `counter-increment: page 2` instead of the implicit 1, but whatever, it works.

```html
<html>
    <head>
            <style type="text/css">
                @page {
                    @bottom-right {
                        content: "Page " counter(page) " of " counter(totalpages);
                        border-top: .25pt solid #666;
                        width: 50%;
                    }

                    @bottom-left {
                        content: "Document Title";
                        border-top: .25pt solid #666;
                        width: 50%;
                    }
                }
                @page :first {
                    counter-increment: page 2;
                    counter-reset: totalpages 4; /* Manually calculating this */   
                }
                h1 {
                    break-before: always;
                }
            </style>
    </head>
    <body>
        <h1>First heading</h1>
        <p>First para</p>
        <h1>Second heading</h1>
        <p>Second para</p>
        <h1>Third heading</h1>
        <p>Third para</p>
    </body>
</html>
```

**Comment by Tontyna** [comment]
Instead of weird `counter-increment` you could say `counter-reset: page 2` to start with page number 2

**Comment by liZe** [comment]
> Instead of weird `counter-increment` you could say `counter-reset: page 2` to start with page number 2

I'm sorry for my misleading comment, I didn't remember this was working well. We can close #93 by the way.

**Comment by Tontyna** [comment]
> We can close #93 by the way.

Nah, despite the title being "counter-reset: page" the author asks for 

> [...]  and also make the counter(pages) evaluate correctly the number of pages since the last reset.

Ok, it can be closed because the silly spec doesn't allow manipulation of `counter(pages)`.

**Comment by liZe** [comment]
> Ok, it can be closed because the silly spec doesn't allow manipulation of `counter(pages)`.

Yes, that's what I think too.
