### ISSUE TITLE
Modify images based on calculated size

### ISSUE THREAD

**Issue by mojimi** [Kozea/WeasyPrint#810]
Hello, I have a html with images that are really large, but they sit inside a div with `max-height: 5cm` and `width: 100%` so that it maintains aspect ratios.

But there are cases with a lot of images sometimes, and the final PDF becomes 100mb+ since the images get downscaled but not downsampled.

I would like to know how/where can I insert a piece of code to "thumbnail" the images into the size they are calculated by the css rendering.

My main concerns are:

Can I do this via API, without "hacking" the library?

If yes, can I know the size the image is calculated to have in the css in Pixels?

If no, I understand I can probably calculate it myself, but considering I have the style set to use centimeters but the thumbnailing will be in pixels, how can I know the px-cm ratio?

More importantly, how can I do this per-image before adding them to memory? Adding all the original images to memory and **then** thumbnailing them is not feasible as processing would take too much memory.

Oh and I'm thumbnailing the images using PIL/Pillow Image.thumbnail method

**Comment by liZe** [comment]
Hello!

Embedding images in PDF files and talking about image resolution is a complicated question, even if it looks simple. I'll take my time to write a detailed answer, even if you may know everything I say: it may be helpful for other users.

---

A raster image is basically a table of pixels, and pixels are atomic cells corresponding to the smallest size you want to handle. Pixels alone are unrelated real-life sizes (like inches, meters, points…). It means that if you want to include a raster image in your PDF file, if the image has a width (in inches, meters, points…) in your PDF, it doesn't tell us anything about the width (in pixels) the image must have.

**So: we can't automatically resize the image based on its real-life size.** As PDF files can be displayed on high-resolution screens, zoomed, or printed with a very high-density printer, it's not WeasyPrint's duty to handle this.

(Pixels described here are "real" pixels, different from [CSS pixels](https://www.w3.org/Style/Examples/007/units.en.html).)

---

> Can I do this via API, without "hacking" the library?

Yes, you can. Using a [URL fetcher](https://weasyprint.readthedocs.io/en/stable/tutorial.html#url-fetchers) is probably the easiest solution.

> If yes, can I know the size the image is calculated to have in the css in Pixels?

I'm afraid you can't :cry:.

> If no, I understand I can probably calculate it myself, but considering I have the style set to use centimeters but the thumbnailing will be in pixels, how can I know the px-cm ratio?

Good news: it depends on what you want! For example, if you want to print it, you can use a typical resolution of 600 or 1200 dots per inch (dpi), ie. about 250 or 500 pixels per centimeter. As explained before, the ratio between pixels and real-life units depends on what you want to do.

> More importantly, how can I do this per-image before adding them to memory? Adding all the original images to memory and **then** thumbnailing them is not feasible as processing would take too much memory.

With the URL fetcher, you can do what you want. You can fetch the original image, thumbnail it (and keep it in memory or on disk, with a file-like object able to read it) and free the original image memory.

**Comment by mojimi** [comment]
@liZe Thanks! Great response.

Just one thing that wasn't clear to me in the docs, what is the object that a custom url fetcher is expected to return?

**Comment by liZe** [comment]
> Just one thing that wasn't clear to me in the docs, what is the object that a custom url fetcher is expected to return?

The same thing as [`default_url_fetcher`](https://weasyprint.readthedocs.io/en/stable/api.html#weasyprint.default_url_fetcher) (a dict with a string or a file-like object, plus optional properties).

**Comment by mojimi** [comment]
@liZe I know this isn't directly related to WeasyPrint, but I tried the following using PIL and the images aren't being shown, do you happen to know what I did wrong?

```python
from PIL import Image
from urllib.request import urlopen
from pathlib import Path
from weasyprint import HTML, CSS
...
def img_resizer_fetcher(url):
	image_data = BytesIO(urlopen(url).read())
	image = Image.open(image_data)
	image.thumbnail((500, 500))
	image_data = BytesIO()
	image.save(image_data,'JPEG',quality=95,optimize=True)
	return dict(file_obj=image_data, mime_type='image/jpeg')

def syncGeneratePdf(path, name, content):
	filePath = path / name
	html = HTML(string=content, encoding="utf-8", url_fetcher=img_resizer_fetcher)
	html.write_pdf(filePath.resolve(), stylesheets=['./css.css'])
	return filePath
```

**Comment by liZe** [comment]
There may be many reasons, but here's one: you probably have to call `image_data.seek(0)` before returning the dict.

**Comment by mojimi** [comment]
Yup that was it! I also had to use the bytes instead of returning the file object.

Here's the working url fetcher code if anyone in the future looks for this:

```python
from PIL import Image
from urllib.request import urlopen
from io import BytesIO
#...
def img_resizer_fetcher(url):
	image_data = BytesIO(urlopen(url).read())
	image = Image.open(image_data)
       #Set your desired size in pixels here, .thumbnail() automatically maintains aspect ratio so you can give your desired max size
	image.thumbnail((500, 500))
	image_data = BytesIO()
	image.save(image_data,'JPEG',quality=95,optimize=True)
	image_data.seek(0)
	return dict(string=image_data.read(), mime_type='image/jpeg')
#...
```

**Comment by liZe** [comment]
> Here's the working url fetcher code if anyone in the future looks for this:

Thanks a lot!
