### ISSUE TITLE
installation error in virtualenv on debian 9 (9.6)

### ISSUE THREAD

**Issue by BinaryOverdrive42** [Kozea/WeasyPrint#812]
**hello i'm trying to install Weasyprint in virtual environment**
`
python3 -m venv .venv
`

**this is my installation script** 

`
from setuptools import setup, find_packages

name = "test"
version = '0.0.0'

requires = [
    'weasyprint==44'
]

setup(
    name=name,
    version=version,
    packages=find_packages(),
    package_dir={'': "src"},
    install_requires=requires
)

`

**I run it with the next command:**
`
.venv/bin/python setup.py develop
`

**and get the following output:**
`
running develop
running egg_info
writing top-level names to src/test.egg-info/top_level.txt
writing src/test.egg-info/PKG-INFO
writing requirements to src/test.egg-info/requires.txt
writing dependency_links to src/test.egg-info/dependency_links.txt
reading manifest file 'src/test.egg-info/SOURCES.txt'
writing manifest file 'src/test.egg-info/SOURCES.txt'
running build_ext
Creating /home/vagrant/test/.venv/lib/python3.5/site-packages/test.egg-link (link to src)
test 0.0.0 is already the active version in easy-install.pth

Installed /home/vagrant/test/src
Processing dependencies for test==0.0.0
Searching for weasyprint==44
Reading https://pypi.python.org/simple/weasyprint/
Downloading https://files.pythonhosted.org/packages/89/05/4eb7b5135bf94465a61b6ddfa6e84526cdc1b15385a3bed7aa86b5bda621/WeasyPrint-44.tar.gz#sha256=799bf4e7df80ec307051d21c59ef91e3198b4013cdecc6b47e9cb0c014ffab38
Best match: WeasyPrint 44
Processing WeasyPrint-44.tar.gz
Writing /tmp/easy_install-asqc5fdt/WeasyPrint-44/setup.cfg
Running WeasyPrint-44/setup.py -q bdist_egg --dist-dir /tmp/easy_install-asqc5fdt/WeasyPrint-44/egg-dist-tmp-ylw45mlf
removing '/home/vagrant/test/.venv/lib/python3.5/site-packages/WeasyPrint-file_.weasyprint_VERSION-py3.5.egg' (and everything under it)
creating /home/vagrant/test/.venv/lib/python3.5/site-packages/WeasyPrint-file_.weasyprint_VERSION-py3.5.egg
Extracting WeasyPrint-file_.weasyprint_VERSION-py3.5.egg to /home/vagrant/test/.venv/lib/python3.5/site-packages
WeasyPrint file-.weasyprint-VERSION is already the active version in easy-install.pth
Installing weasyprint script to /home/vagrant/test/.venv/bin

Installed /home/vagrant/test/.venv/lib/python3.5/site-packages/WeasyPrint-file_.weasyprint_VERSION-py3.5.egg
error: The 'weasyprint==44' distribution was not found and is required by test
`

**Comment by liZe** [comment]
If you don't use pip to install WeasyPrint, [you need at least setuptools >= 39.2.0](https://weasyprint.readthedocs.io/en/stable/install.html#id9). Updating setuptools should fix your problem.

**Comment by liZe** [comment]
@BinaryOverdrive42 Does it work now?

**Comment by BinaryOverdrive42** [comment]
@liZe Yes, I changed the creation of a virtual environment to _virtualenv -p python3.5 .venv_ on my CI and it works fine
