### ISSUE TITLE
Documentation about file_obj and url_fetcher

### ISSUE THREAD

**Issue by SebCorbin** [Kozea/WeasyPrint#814]
Seeing https://github.com/Kozea/WeasyPrint/blob/e5f7ec97564c084f2221e7cf6b9f03e486412a21/weasyprint/urls.py#L230-L231 and https://github.com/Kozea/WeasyPrint/blob/e5f7ec97564c084f2221e7cf6b9f03e486412a21/weasyprint/urls.py#L272-L293

I'm guessing the documentation is either outdated or wrong, is that right?

**Comment by liZe** [comment]
> is that right?

It is, thanks!

**Comment by SebCorbin** [comment]
In a way, it's not, because `fetch()` is actually the caller and is closing `file_obj`, but updating the special section about URL fetchers in the docs to explain that would be nice.

**Comment by liZe** [comment]
Yes, I'm trying to find the exact words to say this.

**Comment by liZe** [comment]
> If a ``file_obj`` key is given, it is the caller’s responsibility to call ``file_obj.close()``. The default function used internally to fetch data in WeasyPrint tries to close ``file_obj`` after retreiving; but if this URL fetcher is used elsewhere, the file object has to be closed manually.

Is that OK for you?
