### ISSUE TITLE
Render Javascript Content

### ISSUE THREAD

**Issue by Javedgouri** [Kozea/WeasyPrint#817]
I have a javascript code in my HTML which generate a graph using chart.js.
but when i generate pdf using HTML, the graph doesn't generate in pdf.

**Comment by liZe** [comment]
Hello!

WeasyPrint doesn't support JavaScript at all, and there's no plan to support it in the future.

You'll find more in #23 and #454 about how to execute JS or Python code before rendering the result with WeasyPrint.

**Comment by Javedgouri** [comment]
Workaround to do that?

**Comment by liZe** [comment]
> Workaround to do that?

Yes, as I said in the previous comment, you'll find
- a workaround in #454 using PhantomJS to generate a DOM tree that is given to WeasyPrint,
- a workaround in #23 using Python do preprocess your HTML file before giving it to WeasyPrint.

**Comment by Javedgouri** [comment]
Thank you.

**Comment by Christophe31** [comment]
would the DOM contain a canvas js generated content like for chart.js? I doubt. @Javedgouri did you manage to make this work or did you use something else? Like a python charting library to generate images?

**Comment by Javedgouri** [comment]
i have used python library to generate the graph in svg and that svg i have rendered.

**Comment by Lohitha3** [comment]
> i have used python library to generate the graph in svg and that svg i have rendered.

@Javedgouri  Can you share the way you generated svg using some python library you mentioned
