### ISSUE TITLE
What kind of files cffi expects?

### ISSUE THREAD

**Issue by mojimi** [Kozea/WeasyPrint#818]
The context here is trying to make WeasyPrint run on a AWS Lambda (which is a Amazon Linux machine), I know there are similar discussions but the packages providaded by them are outdated.

Let's start with pango for example, I've found online the compiled libpango for RPM systems (Amazon Linux uses Yum), so I put the file `libpango-1.0.so.0` in the same directory as my WeasyPrint code.

It then says it can't find libpango-1.0.so.0 which is exactly there, so I don't really understand what are these files and how cffi looks for them. Another thing that gets me confused is that the file says libpango-1.0 but that 1.0 isn't the version, so what is it?

I also couldn't make it find gdk-pixbuff because it looks for it in the /usr/ folder and AWS doesn't have access to that, can I make it try to find somewhere else? So far my workaround is to convert everything to PNG in a custom url handler

**Comment by liZe** [comment]
Hello!

WeasyPrint uses [cffi's dlopen](https://cffi.readthedocs.io/en/latest/ref.html#ffi-dlopen-ffi-dlclose) function, and I don't know how it works. Reading [cffi's documentation](https://cffi.readthedocs.io/en/latest/embedding.html#issues-about-using-the-so) may help. Setting the `LD_LIBRARY_PATH` environment variable to the path where the library can help.

**Comment by mojimi** [comment]
> 
> 
> Hello!
> 
> WeasyPrint uses [cffi's dlopen](https://cffi.readthedocs.io/en/latest/ref.html#ffi-dlopen-ffi-dlclose) function, and I don't know how it works. Reading [cffi's documentation](https://cffi.readthedocs.io/en/latest/embedding.html#issues-about-using-the-so) may help. Setting the `LD_LIBRARY_PATH` environment variable to the path where the library can help.

That did help, except for the pixbuff part, because AFAIK cffi looks in the root folder by default, so it's probably something else that's looking for it in the /usr/ folder, do you happen to know which module is trying to find the pixbuf lib?

**Comment by liZe** [comment]
> do you happen to know which module is trying to find the pixbuf lib?

Yes, it's in cairocffi:

https://github.com/Kozea/cairocffi/blob/9fbcbaea7fe9f87ad6a783f57d308572ac0e9296/cairocffi/pixbuf.py#L22

**Comment by liZe** [comment]
@mojimi Did you find a solution to this issue?

**Comment by mojimi** [comment]
I haven't unfortunately, I did a workaround by converting the images to png with Pillow
