### ISSUE TITLE
Workaround to add externals fonts in pdf

### ISSUE THREAD

**Issue by Javedgouri** [Kozea/WeasyPrint#822]
i have tried this way but its not working and also tried writing css in html

```python
    css = CSS(string='''
        @font-face {
            font-family: Gotham Rounded;
            src: url(/home/javed/Downloads/fonts/GothamRoundedBold_21016.ttf);
            
        }

        @font-face{
            font-family: Gothan Narrow;
            src: url(/home/javed/Downloads/fonts/GothamNarrow-Light.otf)
        }
    ''', font_config=font_config)
    pdf_doc = HTML(string=render_output).write_pdf(response, stylesheets=[css], font_config=font_config)
```

**Comment by liZe** [comment]
Hello!

You have to use file URLs in your src property: `url(file:///home/javed/Downloads/fonts/GothamRoundedBold_21016.ttf);`

If you want to see errors and warnings you script may log, you can set up the [logging module](https://weasyprint.readthedocs.io/en/stable/tutorial.html#logging) or simply use the `weasyprint` command line that prints warnings on the standard output. It's easier to get errors this way :wink:.

**Comment by Javedgouri** [comment]
Thank you.

**Comment by laggardkernel** [comment]
> You have to use file URLs in your src property: `url(file:///home/javed/Downloads/fonts/GothamRoundedBold_21016.ttf);`

Thx. This solves my problem. It seems `file://` prefix must be added in the `src` property in an internal CSS.

-----

```python
# Example from the tutorial
from weasyprint import HTML, CSS
from weasyprint.fonts import FontConfiguration

font_config = FontConfiguration()
html = HTML(string='<h1>The title</h1>')
css = CSS(string='''
    @font-face {
        font-family: Gentium;
        src: url(http://example.com/fonts/Gentium.otf);
    }
    h1 { font-family: Gentium }''', font_config=font_config)
html.write_pdf(
    '/tmp/example.pdf', stylesheets=[css],
    font_config=font_config)
```

But in my test, when I passed the `stylesheets` and `font_config` to `HTML.write_pdf()` to render the PDF (see the example above), there's no need to add the `file://` prefix in the `src` property. Just the absolute path like `/home/username/dummy.otf"` is enough to get the font used in the output PDF.

Maybe we should make these two behaviors consistent?

**Comment by liZe** [comment]
> Maybe we should make these two behaviors consistent?

Resolving relative URLs is only possible when a base URL is provided, for example when the stylesheet comes from a real file. That’s why it’s sometimes allowed, and sometimes not.

`/home/username/dummy.otf` is a relative URL. It’s an absolute path if your stylesheet is on your filesystem (the absolute URL is `file:///home/username/dummy.otf`), but it’s not if your stylesheet is on a webserver: if your CSS is available at `http://example.com/static/style.css`, the absolute URL of your font will be `http://example.com/home/username/dummy.otf`.

If you don’t want to use real files, you can give the [`base_url`](https://weasyprint.readthedocs.io/en/stable/api.html#weasyprint.HTML) parameter to `HTML`.
