### ISSUE TITLE
Uppercase characters in named strings dont work

### ISSUE THREAD

**Issue by mattieusch** [Kozea/WeasyPrint#826]
Named strings seem to break when they contain uppercase characters in their label. See code snippet below. I would expect 'brokenTitle' to work as 'workingtitle'.

```<!doctype html>
<html>
<head>
    <style>
    div.page {
        page-break-after:always;
    }
    h1 {
      string-set: workingtitle content();
    }
    h2 {
      string-set: brokenTitle content();
    }
    #p1 {
        page: page1;
    }
    #p2 {
        page: paGe2;
    }
    @page {
        @top-left {
            content: string(workingtitle);
        }
        @top-right {
            content: string(brokenTitle);
        }
    }
    </style>
</head>
<body>
    <div class="page" id="p1">
      <h1>H1 Title on Page 1</h1>
      <h2>H2 Title on Page 1</h2>
    </div>
    <div class="page" id="p2">
      <h1>H1 Title on Page 1</h1>
      <h2>H2 Title on Page 2</h2>
    </div>
  </body>
</html>```

**Comment by Tontyna** [comment]
@liZe I assume, the names of named strings are meant to be case insensitive, like counter names. ?

**Comment by Tontyna** [comment]
Are they? Would like to find a relevant spec.

**Comment by Tontyna** [comment]
No, Iwas wrong! String and counter names are fully case sensitive [custom identifiers](https://drafts.csswg.org/css-values-3/#identifier-value)

**Comment by Tontyna** [comment]
Then, in `css.validation.properties` we must *not* call `get_keyword()` for `string-set` as this returns the token's `.lower_value`. We need the unaltered `token.value`!
