### ISSUE TITLE
stroke, stroke-width SVG CSS "Presentational" attributes giving "unknown property"

### ISSUE THREAD

**Issue by saschwarz** [Kozea/WeasyPrint#832]
I'm using CSS in my site to define the stroke color and stroke-width according to user preferences within some SVGs and I'm getting:
``` bash
# weasyprint source.html source.pdf
WARNING: Ignored `stroke: black` at 3:7, unknown property.
WARNING: Ignored `stroke-width: 0.4px` at 4:7, unknown property.
WARNING: Ignored `stroke-width: 0.1px` at 8:7, unknown property.
WARNING: Ignored `stroke: black` at 9:7, unknown property.
```
I'm defining them in the head > style of my HTML:
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>A Title</title>
  <style>
    rect {
      stroke: black;
      stroke-width: 0.4px;
    }

    line {
      stroke-width: 0.1px;
      stroke: black;
    }

    text {
      font-family: monospace;
    }
  </style>
</head>
```
Is it possible to support these CSS attributes?

**Comment by liZe** [comment]
Hello!

Inline SVG files are not supported (see #75), but you can include them using `embed` or `img` tags, and put the stylesheet in the SVG.

**Comment by liZe** [comment]
@saschwarz If the solution is OK for you, you can close this issue (as it's basically a duplicate of #75).

**Comment by saschwarz** [comment]
Thanks @liZe I'll see if I can apply the approaches in #75 to my situation.
