### ISSUE TITLE
Table td rowspan breaking not properly

### ISSUE THREAD

**Issue by stolzweb** [Kozea/WeasyPrint#833]
![Unbenannt](https://user-images.githubusercontent.com/36608478/54915915-87e07180-4ef8-11e9-85e6-919b7f08f97c.PNG)
Maybe it is the same issue #36 but i am not shure. Breaking a rowspan td is not prpperly. 
<table border="0" cellpadding="0" cellspacing="0"
![Unbenannt](https://user-images.githubusercontent.com/36608478/54915794-46e85d00-4ef8-11e9-98e2-b98a650ee482.PNG)
>
<thead>
		<tr>
			<th scope="col">St&ouml;rung</th>
			<th scope="col">Ursache</th>
			<th scope="col">L&ouml;sung</th>
		</tr>
	</thead>
	<tbody>
`<tr >
			<td colspan="1" rowspan="4"><strong>Kurze Laufzeit</strong></td>
			<td>
			<ol>
				<li>Batterie nicht voll geladen</li>
			</ol>
			</td>
			<td>
			<ul>
				<li>Batterie laden</li>
			</ul>
			</td>
		</tr>
		<tr>
			<td>
			<ol start="2">
				<li>Anwendung auf sehr rauem Boden</li>
			</ol>
			</td>
			<td>
			<ul>
				<li>Type der PAD&#39;s oder B&uuml;rsten pr&uuml;fen</li>
				<li>Weichere B&uuml;rsten oder Pad&#39;s verwenden</li>
			</ul>
			</td>
		</tr>
		<tr>
			<td>
			<ol start="3">
				<li>Ende der Lebensdauer der Batterie erreicht&nbsp; (5 Jahre oder 2000 volle Ladezyklen)</li>
			</ol>
			</td>
			<td>
			<ul>
				<li>Batterie durch Wetrok Service auslesen lassen</li>
				<li>Batterie eventuell ersetzen</li>
			</ul>
			</td>
		</tr>
		<tr>
			<td>
			<ol start="4">
				<li>Komponente defekt</li>
			</ol>
			</td>
			<td>
			<ul>
				<li><strong>Wetrok Service anfordern</strong></li>
				<li>Ladeger&auml;t pr&uuml;fen</li>
				<li>E-Board pr&uuml;fen</li>
				<li>HMI-Board pr&uuml;fen</li>
				<li>Batterie ersetzen</li>
			</ul>
			</td>
		</tr>`
</tbody>
</table>
![Unbenannt](https://user-images.githubusercontent.com/36608478/54915848-63849500-4ef8-11e9-9a7a-4b538d0b680a.PNG)

**Comment by liZe** [comment]
Hello.

> Maybe it is the same issue #36 but i am not shure.

Yes, it is. Solving #36 will magically solve this issue, as it's just a corner case of table cells that can't be split.

**Comment by stolzweb** [comment]
okay, will it be done somewhen?

Herzliche Grüsse

Manuel
_______________________
Stolz WEB GmbH
Davidstrasse 40
9000 St. Gallen

T: +41 (0)71 511 38 20
F: +41 (0)71 511 38 29
Skype: stolzweb
www.stolzweb.ch

------ Originalnachricht ------
Von: "Guillaume Ayoub" <notifications@github.com>
An: "Kozea/WeasyPrint" <WeasyPrint@noreply.github.com>
Cc: "stolzweb" <info@stolzweb.ch>; "Author" <author@noreply.github.com>
Gesendet: 25.03.2019 15:11:23
Betreff: Re: [Kozea/WeasyPrint] Table td rowspan breaking not properly 
(#833)

**Comment by liZe** [comment]
> okay, will it be done somewhen?

#36 is 6 years old, so… I'm really interested in solving this bug, but it would take a looooooot of time. We have to find a generous sponsor, or it may take some time :cry:.
