### ISSUE TITLE
Tutorial missing fore python 2.7.x

### ISSUE THREAD

**Issue by springjools** [Kozea/WeasyPrint#834]
I can't find a way to install weasyprint for python 2.7 and it's also not included in the tutorial.  Since python 2.7 is the standard version, I'm sure there are people who use this method. What is required to make this work?

**Comment by liZe** [comment]
Hello!

If anybody comes here from the Internet:

**Python 2 is not supported anymore by WeasyPrint, and [Python 2.7 support will be dropped by Python developers in 9 months](https://pythonclock.org/). A lot of projects are also [dropping Python 2 support in 2019](https://python3statement.org/).**

But you probably already know that :wink:.

If you really want (or have to) work with Python 2, you can use `pip install "weasyprint<43"`. Please note that this will install an old version of WeasyPrint that is not supported anymore.

Have fun with WeasyPrint!
