### ISSUE TITLE
Weasyprint 46 handles wrongly top-margin on H1

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#835]
Consider this document:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <style type="text/css">
        @page{size:69mm 146mm;margin:0;padding:0}
        body,html{margin:0;padding:0;height:100%;}
        body *,html *{box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box}
        h1 {
            margin-top: 9mm;
            margin-bottom: 3.5mm;
            padding-top: 0;
        }
        .page{page-break-after:always;position:relative;height:100%;padding:8mm 5mm 5mm 5mm}</style>
</head>
<body>
    <div class="page">
        <h1 style="background-color: #f00;">
            Respect festival 2019
        </h1>
    </div>

    <div class="page">
        <h1 style="background-color: #f00;">
            Respect festival 2019
        </h1>
    </div>

    <div class="page">
        <h1 style="background-color: #f00;">
            Respect festival 2019
        </h1>
    </div>
</body>
</html>
```

There are three equal pages, however the only two has correct top margin. It worked correctly with version `0.42.3`. See attached PDF. 

[ticket.pdf](https://github.com/Kozea/WeasyPrint/files/3012527/ticket.pdf)

**Comment by liZe** [comment]
Thank you.

Oops, there was a problem in the way `margin-break: auto` was handled. Top margins are discarded when an unforced page break happens, but it is kept with forced page breaks (as it is in your document).

**Comment by knyttl** [comment]
Wow. You fixed the issue an hour after my report? Just wow. When will you release it?

**Comment by liZe** [comment]
> Wow. You fixed the issue an hour after my report? Just wow.

:smile:

> When will you release it?

Probably not before a couple of weeks. Before that, you can use `margin-break: keep` as a workaround, or install the current `master` branch with `pip install git+https://github.com/Kozea/WeasyPrint.git`.

**Comment by knyttl** [comment]
thanks
