### ISSUE TITLE
How to show page number only if have > 1 pages

### ISSUE THREAD

**Issue by RomanCoding** [Kozea/WeasyPrint#838]
Is there any way to display page number only if document has more than one page?

So, i have CSS rule like this 

`@page{`

            size: A4;

            counter-increment: page;

            @bottom-right {

                content: "Page " counter(page) " of " counter(pages);

                border-top: .25pt solid #666;

                width: 50%;

            }

        }

Can i somehow show it only if have > 1 page?

I know this isn't 100% related to Weasyprint, but maybe somebody can help me with this. Thanks in advance

**Comment by Tontyna** [comment]
Define a rule for the first page without page numbers, sth. like this:

```css
 @page:first { 
    @bottom-right {
      content: '';
    }
}
```

**Comment by RomanCoding** [comment]
> Define a rule for the first page without page numbers, sth. like this:
> 
> ```css
>  @page:first { 
>     @bottom-right {
>       content: '';
>     }
> }
> ```

well, but if i have 5 pages, i will have numbers on all pages except first

i want to display all pages, but only if there are more than 1 page

**Comment by Tontyna** [comment]
Ah, that's a tricky one... no idea how to achieve that with pure css.

**Comment by MindFluid** [comment]
Is your only option to do this via pure CSS? ... if you have some reasonable way to predict if your document will be greater than one page you could insert a <style> tag to the document that declares the above optionally.

**Comment by LukasKlement** [comment]
I'd say this links to this ticket: https://github.com/Kozea/WeasyPrint/issues/724

If this were implemented, you could simply do:

`
@page {
    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
    }
}

@page :first {
    @bottom-right {
        content: '';
    }
}

@page :last {
    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
    }
}
`

**Comment by liZe** [comment]
> I'd say this links to this ticket: #724

It does, but I think that `:last` doesn't exist :disappointed:.

**Comment by Tontyna** [comment]
Depending how the documents are created `named pages` could do the trick, see https://stackoverflow.com/questions/42136333/css-paged-media-last-page-selector

**Comment by liZe** [comment]
> It does, but I think that `:last` doesn't exist .

See w3c/csswg-drafts#1110.

**Comment by liZe** [comment]
We're out of solutions for this problem. It may be a good idea to follow w3c/csswg-drafts#1110, as using a `@page:first:last` selector would do the trick.
