### ISSUE TITLE
iframes not showing properly

### ISSUE THREAD

**Issue by SylvainBigonneau** [Kozea/WeasyPrint#840]
System: Ubuntu 18.10
Weasyprint version: v46 (installed via pip3)

I made a small HTML file such as:

```html
<html>
  <head></head>
  <body>
    <iframe allowfullscreen="allowfullscreen" src="https://www.youtube.com/embed/0Bmhjf0rKe8?"></iframe>
    <iframe frameborder="0" src="https://maps.google.com/maps?&q=1 rue de la paix Paris&z=1&t=q&output=embed"></iframe>
  </body>
</html>
```
Which dislays as such, on Chrome and Firefox:

![image](https://user-images.githubusercontent.com/3440721/55251720-8e9d1a80-5251-11e9-926d-ded01434b444.png)

After processing it with weasyprint :

```
$ weasyprint test.html test.pdf
$ 
```

No errors are displayed, yet all I get are those 2 tiny marks on my PDF (each mark is a single iframe, if I remove one of them, only one mark appears):

![image](https://user-images.githubusercontent.com/3440721/55251819-b7bdab00-5251-11e9-9644-1181d62cd04c.png)

I could not see any issue or documentation referencing what could be done about this, so apologies if I am missing something!

**Comment by mojimi** [comment]
I have a clue, WeasyPrint does not process any Javascript, it only handles the HTML, CSS and images as far as I know.

Are you looking for a pdf that has a video and a interactive map? Or just their thumbnails? You could preprocess the iframe tags to become image tags with the thumbnails.

**Comment by MindFluid** [comment]
> You could preprocess the iframe tags to become image tags with the thumbnails.
What @mojimi has said ^

WeasyPrint produces a static end document. It doesn't quite make sense for it to correctly display an iframe. It would be better to grab a snap-shot of the thumbnail and/or include a hyperlink.

**Comment by liZe** [comment]
WeasyPrint actually supports iframes, it works well as long as:
1. the iframe tag has some style to at least define its size,
2. the root document and the embedded document don't rely on javascript (it obviously does in the original example).

> all I get are those 2 tiny marks on my PDF

These two marks are the default borders of the iframe tags.

@SylvainBigonneau I'm closing this issue, feel free to reopen if there's anything we can do!
