### ISSUE TITLE
Rendering special characters

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#842]
Consider this html page:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <style type="text/css">
        @page{size:a4 portrait;font-family:Arial;font-size:11px;width:100%;color:#000;display:block;text-align:right}}
        body{font-family:Arial;margin:0;padding:0}
    </style>
</head>

<body class="pdf">
    <h1>Alice_(Ƨ) based on Lewis Carroll</h1>
</body>
</html>
```

I tried different fonts, but it will always end up like this:

<img width="584" alt="Screenshot 2019-04-01 at 10 43 12" src="https://user-images.githubusercontent.com/401107/55314705-02663f80-546b-11e9-820a-5216e8248f7f.png">

Full pdf is here:

[ticket.pdf](https://github.com/Kozea/WeasyPrint/files/3028434/ticket.pdf)

This also happens with other UTF-8 characters.

**Comment by liZe** [comment]
Hello,

There's an extra `}` at the end of your first line in the `style` tag, it breaks the style and makes you use a fallback font that doesn't have the character you want.

The error is well detected by WeasyPrint and prints a warning in the console.

[Removing it works well with Arial.](https://github.com/Kozea/WeasyPrint/files/3028641/utf.pdf)

(That's not a good idea to play with `width` in the `@page` rule :wink:)

**Comment by knyttl** [comment]
Okay, thanks.

**Comment by knyttl** [comment]
Sorry for reopening this, but would it be possible to make some kind of fallback? For instance all web browsers fall back to Arial when given font doesn't support given special character. In most cases it is good enough that user doesn't even notices it. 

We have this problem with font ProximaNova, which doesn't have most of these UTF-8 characters. If there was a fallback, it would completely resolve our problem.

**Comment by liZe** [comment]
> Sorry for reopening this, but would it be possible to make some kind of fallback?

There's already a fallback, based on your system configuration. Fontconfig gives a list of fonts matching the font family set in CSS. The default one is "serif", so you can check the list of fonts available on your system using `fc-cache -a serif`.

The square with 01A7 is already a character in a fallback font :smile: (called [BMP](https://scripts.sil.org/cms/scripts/page.php?item_id=UnicodeBMPFallbackFont)).

> For instance all web browsers fall back to Arial when given font doesn't support given special character. In most cases it is good enough that user doesn't even notice it.

It's not that simple at all. I don't have Arial installed on my system, but fallbacks work for me too. If it's good enough that user doesn't even notice, you can be sure of one thing: it's not just an "Arial" value added in the fallback list :wink:. Here's what [Chrome's Blink does](https://github.com/chromium/chromium/tree/99f5438aba0fb5e137221ee18f6c6969f4654d0e/third_party/blink/renderer/platform/fonts#font-fallback) for example.

WeasyPrint does the same, relying on Pango and Fontconfig. And it's a better idea to rely on these libraries than trying to create our own fallback mechanism!

> We have this problem with font ProximaNova, which doesn't have most of these UTF-8 characters. If there was a fallback, it would completely resolve our problem.

You can define fallbacks using: `font-family: ProximaNova, Arial`. It's better if you want to finely define the fallbacks you need, independently from the system.

If you want to use a different fallback font on your system, you can tweak your Fontconfig configuration and give BMP a lower priority. Here's a [related post](https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/) that can help you to play with Fontconfig.

**Comment by knyttl** [comment]
Hm, I am now actually trying any font and it doesn't work for any. I am running weasyprint on debian with installed mscorefonts package. This issue happens for all of them as well as for my ProximaNova.

`fc-cache -a serif` doesn't work for me (at least on my debian), there is no `-a` option.

I tried also set `font-family: serif` but it doesn't work correctly either.

Could it be something else wrongly set on my installation?

**Comment by liZe** [comment]
> `fc-cache -a serif` doesn't work for me (at least on my debian), there is no `-a` option.

Oops, it is fc-match, not fc-cache, my bad.

> Hm, I am now actually trying any font and it doesn't work for any. I am running weasyprint on debian with installed mscorefonts package. This issue happens for all of the ms fonts as well as for my ProximaNova.

I've installed MS fonts, and it works well for me with Arial. There's no need to fallback as the character is included in Arial.

Could you attach the generated PDF file?

**Comment by knyttl** [comment]
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <style>
        @page{size:a4 portrait;margin:10mm 10mm 14mm 10mm;padding:0;}
    </style>
</head>



<body>
    <div>
    <h1 style="font-family: Arial">Alice_(Ƨ)</h1>
    <h1 style="font-family: 'Comic Sans'">Alice_(Ƨ)</h1>
    <h1 style="font-family: Serif">Alice_(Ƨ)</h1>
    <h1 style="font-family: 'Times New Roman'">Alice_(Ƨ)</h1>
    <h1 style="font-family: ProximaNova">Alice_(Ƨ)</h1>
    </div>
</body>
</html>
```

[tickets.pdf](https://github.com/Kozea/WeasyPrint/files/3035606/tickets.pdf)

**Comment by liZe** [comment]
I've opened MS fonts with a font editor, and the Ƨ character is not included in Arial or in Times (and probably not in the other fonts you tried). So… Using Arial as a fallback doesn't help at all :smile:.

You need to use a fallback font that has this character. [Ubuntu Font](https://design.ubuntu.com/font/) has it for example.



> it is not the newest version because of the margin bug I reported earlier.

Which one?

**Comment by knyttl** [comment]
I installed the Ubuntu Font, but with the same result :/

> > it is not the newest version because of the margin bug I reported earlier.
>
> Which one?

```
# weasyprint --version
WeasyPrint version 0.42.3
```

**Comment by knyttl** [comment]
Okay, it works with the Ubuntu font, thanks!

However, could I somehow set Ubuntu font as default - so that if my `font-family` doesn't have it? In this case if I have `font-family: ProximaNova, Arial, serif`, it won't work whereas in Chrome it would.

**Comment by liZe** [comment]
> Which one?

I mean, which issue?

> However, could I somehow set Ubuntu font as default - so that if my `font-family` doesn't have it?

That's a Fontconfig configuration. You can read [this post](http://eosrei.net/articles/2016/02/changing-default-fallback-subsitution-fonts-linux) about how to set default fonts for serif (and sans-serif, and monospace…). You should consider using a font with a large glyph coverage, DejaVu is pretty good for Latin and Cyrillic alphabets.

**Comment by knyttl** [comment]
> which issue?

https://github.com/Kozea/WeasyPrint/issues/835

Once this is released I will update to current version.

> That's a Fontconfig configuration. You can read this post about how to set default fonts for serif (and sans-serif, and monospace…). You should consider using a font with a large glyph coverage, DejaVu is pretty good for Latin and Cyrillic alphabets.

It seems all was resolved just by installing `fonts-dejavu`. No changes in configuration were necessary.
