### ISSUE TITLE
MacOS installation guide is incomplete and outdated

### ISSUE THREAD

**Issue by theopeek** [Kozea/WeasyPrint#849]
The macOS installation guide at https://weasyprint.readthedocs.io/en/stable/install.html#macos says "don't forget to use the pip3 command to install WeasyPrint", but the command itself is not listed.

Also `brew install fontconfig --universal` is outdated as `--universal` is deprecated. Btw omitting `--universal` solved the fontconfig error for me anyway

**Comment by liZe** [comment]
Thank you for this issue.

> The macOS installation guide at https://weasyprint.readthedocs.io/en/stable/install.html#macos says "don't forget to use the pip3 command to install WeasyPrint", but the command itself is not listed.

It's described [at the beginning of the page](https://weasyprint.readthedocs.io/en/stable/install.html), but we may add a link to help.

> Also `brew install fontconfig --universal` is outdated as `--universal` is deprecated. Btw omitting `--universal` solved the fontconfig error for me anyway

I believe you :smile:. Would you mind creating a pull request to solve this two points?

**Comment by liZe** [comment]
@theopeek Can I help you? You can write the text here if you don't want to create a pull request, I'll add it myself.

**Comment by theopeek** [comment]
@liZe thank you for getting back to me. I have been putting this off partly because I don't yet know how to do a pull request and partly because of some personal issues. Thank you for your offer to help. Give me some time and I'll respond with my suggestions

**Comment by theopeek** [comment]
@liZe Please double-check my work because this is my first ever pull request

**Comment by liZe** [comment]
It had been closed with #877.
