### ISSUE TITLE
Trouble with arabic text

### ISSUE THREAD

**Issue by StephanMeijer** [Kozea/WeasyPrint#850]
<img width="722" alt="Screenshot 2019-04-12 at 12 26 40" src="https://user-images.githubusercontent.com/3169264/56031026-9fa05e00-5d1e-11e9-8370-a90eb61b1ce0.png">

**Comment by StephanMeijer** [comment]
<img width="927" alt="Screenshot 2019-04-12 at 13 44 39" src="https://user-images.githubusercontent.com/3169264/56034955-265a3880-5d29-11e9-956d-5defddd94f55.png">

**Comment by liZe** [comment]
Duplicates #828.
