### ISSUE TITLE
Links are not clickable anymore

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#856]
With current version of Weasyprint, links in generated PDF cannot be clicked and it shows the "select" cursor instead of "pointer".

Example:

invoice.html
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
</head>

<body>
    <a href="https://goout.net/">
        01. 03. 2019 - 30. 03. 2019
    </a>
</body>
</html>
```

[invoice.pdf](https://github.com/Kozea/WeasyPrint/files/3112381/invoice.pdf)

**Comment by Tontyna** [comment]
I suppose your Cairo version isnt up-to-date. Any warnings in the console?

**Comment by knyttl** [comment]
Cairo is current stable debian version:

```
Package: libcairo2
Source: cairo
Version: 1.14.8-1
```

**Comment by knyttl** [comment]
Okay, debian version of cairo is outdated. Thanks.

**Comment by RNogales94** [comment]
I have the same problem in Ubuntu, my cairo version is 1.15.10
But if I check the version within Python:
python3 -c "import cairocffi; print(cairocffi.cairo_version_string())"

**I get 1.14.12**
Am I doing something wrong?

**Comment by liZe** [comment]
> Am I doing something wrong?

Then your version of cairo is 1.14.12.

You may have the two versions installed, and cairocffi finds the 1.14.12 version. Is that possible?
