### ISSUE TITLE
Cython Optimizations

### ISSUE THREAD

**Issue by chancyk** [Kozea/WeasyPrint#858]
I've been experimenting with replacing the base `Box` class with a Cython extension type to speed-up access on heavily referenced attributes. However, I'm running into some strange issues where the attribute have zero values like they were ever updated, despite it seemingly working fine on a small scale. Any suggestions as to some kind of tricky behavior or reflection around these attributes that might be tripping it up?

```python
cdef class BaseBox:
    cdef bint _width_auto, _height_auto, \
        _margin_left_auto, _margin_right_auto, \
        _margin_top_auto, _margin_bottom_auto

    cdef public float \
        _width, _height, \
        padding_left, padding_right, \
        padding_top, padding_bottom, \
        _margin_left, _margin_right, \
        _margin_top, _margin_bottom, \
        border_left_width, border_right_width, \
        border_top_width, border_bottom_width

    @property
    def width(self):
        if self._width_auto == 1:
            return 'auto'
        else:
            return self._width
```

**Comment by liZe** [comment]
Hello!

It's hard to say… WeasyPrint sometimes uses `setattr` to set attributes, I don't know if it's related. Another usual suspect is the `Box.copy` method, that uses the `__dict__` attribute to copy attributes.

**Comment by chancyk** [comment]
@liZe That actually might be exactly what was causing the issue. It looks like `_reset_spacing` is using setattr as a shortcut to avoid writing a few extra functions. I might experiment with this idea again soon, but I'll close this out for now. Thanks for the tips!
