### ISSUE TITLE
Fetch image from public url doesn't work

### ISSUE THREAD

**Issue by danieljausovec** [Kozea/WeasyPrint#861]
Hi.

I'm trying import image from public url and doesn't work.
Here is an html example:

```
<div class="header">
    <img src="https://cdn.my-domain.com/assets/logo.png" class="header-img" />
</div>
```

**Comment by knixeur** [comment]
It should work, you can try debugging using your own url fetcher https://weasyprint.readthedocs.io/en/stable/tutorial.html#url-fetchers and/or enable logging to spot any error https://weasyprint.readthedocs.io/en/stable/tutorial.html#logging

**Comment by danieljausovec** [comment]
It doesn't work.
Here is an example how I use url fetcher in code:

HTML:
```
<div class="header">
    <img src="https://cdn.my-domain.com/assets/logo.png" class="header-img" />
</div>
```

Python:
```
logo = 'https://cdn.my-domain.app/assets/eligma_logo.png'
print(default_url_fetcher(logo))
pdf = HTML(string=pdf_string, url_fetcher=default_url_fetcher(logo)).write_pdf(stylesheets=[css], font_config=font_config)
```

This is print results of `default_url_fetcher`:
`{'redirected_url': 'https://cdn.my-domain.app/assets/eligma_logo.png', 'mime_type': 'image/png', 'encoding': None, 'filename': None, 'file_obj': <http.client.HTTPResponse object at 0x7f898a99fac8>}`

And this is error:
```
weasyprint.get_image_from_uri:223
Failed to load image at "https://cdn.my-domain.app/assets/eligma_logo.png" (TypeError: 'dict' object is not callable)
```

**Comment by knixeur** [comment]
Glad to hear it's fixed! Maybe a new issue should be opened to display a better error message.

**Comment by dsilvapereira** [comment]
this works? i try to get the image but doesn't work..

`pdf_string = '<div class="header"><img src="http://itboon.pt/wp-content/uploads/2019/09/brevemente.jpg" class="header-img" /></div>'

logo = 'http://itboon.pt/wp-content/uploads/2019/09/brevemente.jpg'
print(default_url_fetcher(logo))
pdf = HTML(string=pdf_string, url_fetcher=default_url_fetcher(logo)).write_pdf('out.pdf')`

**Comment by Tontyna** [comment]
@dsilvapereira - which image? What's the error?

BTW: To enter Python code use a fenced code block:

<pre>
```Python
# code goes here
```
</pre>

**Comment by almamunkhan09** [comment]
> It doesn't work. Here is an example how I use url fetcher in code:
> 
> HTML:
> 
> ```
> <div class="header">
>     <img src="https://cdn.my-domain.com/assets/logo.png" class="header-img" />
> </div>
> ```
> 
> Python:
> 
> ```
> logo = 'https://cdn.my-domain.app/assets/eligma_logo.png'
> print(default_url_fetcher(logo))
> pdf = HTML(string=pdf_string, url_fetcher=default_url_fetcher(logo)).write_pdf(stylesheets=[css], font_config=font_config)
> ```
> 
> This is print results of `default_url_fetcher`: `{'redirected_url': 'https://cdn.my-domain.app/assets/eligma_logo.png', 'mime_type': 'image/png', 'encoding': None, 'filename': None, 'file_obj': <http.client.HTTPResponse object at 0x7f898a99fac8>}`
> 
> And this is error:
> 
> ```
> weasyprint.get_image_from_uri:223
> Failed to load image at "https://cdn.my-domain.app/assets/eligma_logo.png" (TypeError: 'dict' object is not callable)
> ```
> 
> **UPDATE** My image was broken so it's work with HTML and don't need url_fetcher.

Did you solve this?

**Comment by liZe** [comment]
> Did you solve this?

The image was broken in this case, there was no problem in WeasyPrint.

**Comment by almamunkhan09** [comment]
Thank you very much. For me I was unable to access to image. With The help of my senior I figured that Its ssl error from my local server. Fixed it. Thank you very much @liZe and @danieljausovec
