### ISSUE TITLE
Cannot Generate PDF from local HTML File (Windows 64 + GTK3-Runtime 64)

### ISSUE THREAD

**Issue by antsouffrant** [Kozea/WeasyPrint#863]
Hello WeasyPrint developers,

I'm trying to use weasyprint in order to convert a local HTML file (created in python) into a PDF.

As such, I've gone through the extensive installation instructions posted here: https://weasyprint.readthedocs.io/en/stable/install.html

First, I have python (64-bit) already installed on my computer: 

"python --version --version"
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

Secondly, I installed GTK3-Runtime (64 bit) and added its bin into my path, shown below: 

"ECHO %PATH%"
C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\PuTTY\;C:\Program Files\Dell\Dell Data Protection\Encryption\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Git\cmd;**C:\\Program Files\\GTK3-Runtime Win64\\bin**;C:\Users\SOUFFRAB\AppData\Local\Continuum\anaconda3;C:\Users\SOUFFRAB\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\SOUFFRAB\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\SOUFFRAB\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\SOUFFRAB\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\SOUFFRAB\AppData\Local\Microsoft\WindowsApps;C:\Users\SOUFFRAB\AppData\Local\Programs\Microsoft VS Code\bin;

To confirm, I am able to locate libcairo-2.dll properly: 

"WHERE libcairo-2.dll"
C:\Program Files\GTK3-Runtime Win64\bin\libcairo-2.dll

Next, I tried to test PDF generation for a simple webpage: 

"weasyprint http://google.com C:/Users/SOUFFRAB/Desktop/test.pdf"

Output of the call:
c:\users\souffrab\appdata\local\continuum\anaconda3\lib\site-packages\weasyprint\document.py:34: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
WARNING: Ignored `overflow-y:scroll` at 1:59, unknown property.
WARNING: Ignored `display:inline-box` at 1:387, invalid value.

I can see some warnings, but nothing to indicate that the execution has stopped in any way. **The problem: I cannot find any relevant PDF in the specified location.**

Any idea what is happening here? Any help is greatly appreciated.

Thanks,
antsouffrant

**Comment by Tontyna** [comment]
Did you install the latest GTK3-Runtime (3.24.8-2019-04-26)?
I know nothing about Anaconda -- does it provide a special shell to run Python scripts or do you run weasyprint from Windows command prompt?

**Comment by liZe** [comment]
@antsouffrant Did you find a solution to your problem?

**Comment by liZe** [comment]
Feel free to reopen if we can do anything for you.
