### ISSUE TITLE
Inkscape installation breaks webfont @import

### ISSUE THREAD

**Issue by simon-schubert** [Kozea/WeasyPrint#871]
This Issue can be reproduced by using my Dockerfile on the following repo: https://github.com/simon-schubert/weasydebian

**Background:**
Installing weasyprint on latest debian:stretch to generate pdf via command
`weasyprint input.html output.pdf`

**Expected:**
If i run `weasyprint input.html output.pdf` on an input.html including a webfont loaded in css like that:
`@import url("https://fonts.googleapis.com/css?family=Anton");`
I expect, that the font is correctly displayed.

Which in my case is as long as i'm not installing inkscape on the machone, and the result looks like that:
![right](https://user-images.githubusercontent.com/48808627/58263226-e8b2eb80-7d7b-11e9-9e20-f8539a7f257b.png)

**Problem**
If I afterwards install inkscape on the same machine like that:
`apt-get install -y inkscape`
Then with the same html/css i get the following output:
![wrong](https://user-images.githubusercontent.com/48808627/58263275-fc5e5200-7d7b-11e9-8ade-10b0f8acc53f.png)

**Steps to reproduce**
As previously mentioned, this can be reproduced by doing the following steps:
`git clone https://github.com/simon-schubert/weasydebian`
`docker-compose up`
`docker exec -it weasydebian_weasy_1 bash`
`weasyprint test/test.html test_before.pdf`
--> now the font was imported correctly
`apt-get install -y inkscape`
`weasyprint test/test.html test_after.pdf`
--> now the font is not imported anymore and some systems font is used

We first found this issue on a docker container, but we were able to reproduce it as well on one of our stagings, which is run by an external hoster without any docker involved.

**Important Hint:**
If I install inkscape without recommended packages, i was not able to reproduce it:
`apt-get install -y inkscape --no-install-recommends`

I really like the tool and it would be awesome if you could help us with that and check if its a bug or which dependency interference might occur.

**Comment by liZe** [comment]
There must be something in Inkscape's dependencies installing a font alias called Anton replacing the one from Google fonts.

Could you try to remplace `@import url("https://fonts.googleapis.com/css?family=Anton");` with
```css
@font-face {
  font-family: 'Anton';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/anton/v10/1Ptgg87LROyAm3Kz-Co.ttf) format('truetype');
}
```
If it works, it means that the `local(Anton Regular)` in Google's CSS matches another font on your system. We'll try then to find what's wrong.

**Comment by simon-schubert** [comment]
Hi @liZe ,

Thanks for your reply. It seems that you are on the right track. Replacing the @import with the @font-face fixes the issue indeed. But it seems that this is not related to „Anton“ itself because we made the same observation with `@import url("https://fonts.googleapis.com/css?family=Roboto")`

How did you find the correct source of Anton’s ttf? Maybe I can do some further checks with Roboto, to help to get closer to the root cause.

Cheers, Simon

**Comment by liZe** [comment]
> How did you find the correct source of Anton’s ttf? Maybe I can do some further checks with Roboto, to help to get closer to the root cause.

I think that there's an aggressive FontConfig default rule installed on your system that makes any font name match a real local font even with no fallback. You can find the culprit font by printing `path` or `url` in `fonts.py`:
https://github.com/Kozea/WeasyPrint/blob/8499379dd1762cc5c429f5f6704467ae3ca2ce4e/weasyprint/fonts.py#L343-L345

Playing with `fc-match` could help too.

With the font name, you could be able to guess which package causes the problem. If it doesn't help, you could check the FontConfig rules related to this font in your `/etc/fonts` folder.

**Comment by simon-schubert** [comment]
if i print url or path i get: /usr/share/fonts/type1/gsfonts/c059013l.pfb
this seems to be the applied serif-font from the screen, this might be the header of the file:

`%!PS-AdobeFont-1.0: CenturySchL-Roma 1.06
%%Title: CenturySchL-Roma
%Version: 1.06
%%CreationDate: Thu Aug  2 10:35:39 2007
%%Creator: frob
%Copyright: Copyright (URW)++,Copyright 1999 by (URW)++ Design &
%Copyright:  Development; Cyrillic glyphs added by Valek Filippov (C)
%Copyright:  2001-2005
% Generated by FontForge 20070723 (http://fontforge.sf.net/)
%%EndComments

FontDirectory/CenturySchL-Roma known{/CenturySchL-Roma findfont dup/UniqueID known{dup
/UniqueID get 5020141 eq exch/FontType get 1 eq and}{pop false}ifelse
{save true}{false}ifelse}{false}ifelse
11 dict begin
/FontType 1 def
/FontMatrix [0.001 0 0 0.001 0 0 ]readonly def
/FontName /CenturySchL-Roma def
/FontBBox {-217 -302 1188 988 }readonly def
/UniqueID 5020141 def
/PaintType 0 def
/FontInfo 9 dict dup begin
 /version (1.06) readonly def
 /Notice (Copyright \050URW\051++,Copyright 1999 by \050URW\051++ Design & Development; Cyrillic glyphs added by Valek Filippov \050C\051 2001-2005) readonly def
 /FullName (Century Schoolbook L Roman) readonly def
 /FamilyName (Century Schoolbook L) readonly def
 /Weight (Roman) readonly def
 /ItalicAngle 0 def
 /isFixedPitch false def
 /UnderlinePosition -104 def
 /UnderlineThickness 61 def
end readonly def
/Encoding StandardEncoding def
currentdict end
currentfile eexec`

this not the complete file, the rest is like:

`���i�AD4�=sd�SlC`

fc-match does always give me
DejaVuSans.ttf: "DejaVu Sans" "Book"

no matter what i try.

Do you see more, what i could check?

**Comment by liZe** [comment]
> Do you see more, what i could check?

I've tried to find the system font that's used in your example, and it looks like Century. On Debian, this font is installed with the "gsfonts" package, that's a dependency of ghostscript, that's a dependency of imagemagick, that's a recommended dependency of Inkscape, so… I suppose it's our culprit.

(Oh, I'm so stupid, that was the font from your previous comment, there was no need to search! I'm glad I've found the good one…)

You can try to install only this package and see if it breaks the rendering. You can also try to see if you get the same rendering when you generate PDF, PS or PNG files.

**Comment by liZe** [comment]
@simon-schubert Did you find the time to test without the gsfonts package?

**Comment by liZe** [comment]
> Did you find the time to test without the gsfonts package?

Closing this issue for now, feel free to reopen if there's something new.
