### ISSUE TITLE
Image size in PDF does not match HTML

### ISSUE THREAD

**Issue by keholmbeck** [Kozea/WeasyPrint#872]
We have some graphs generated in D3.js that are saved to PNG via [saveSvgAsPng](https://github.com/exupero/saveSvgAsPng). After enabling support for IE by using [canvg](https://github.com/canvg/canvg), our images are now scaled strangely (in PDF, not HTML) and do not fit to the page. 

Using Weasyprint 47, Python 3.6.5, Windows 7 64-bit.

Attached is HTML and Wesyprint PDF output

[temp.zip](https://github.com/Kozea/WeasyPrint/files/3213132/temp.zip)

**Comment by liZe** [comment]
Hello!

In your document, the height (and thus the width, as the image ratio is respected) of images is set using the `height` attribute in HTML. That's called a "presentational hint" and it's now recommended not to use them and use CSS instead.

Presentational hints are ignored by WeasyPrint by default, but you can handle them [using the `--presentational-hints` CLI parameter](https://weasyprint.readthedocs.io/en/latest/features.html?highlight=presentational#html).

Have fun!

**Comment by keholmbeck** [comment]
Perfect/fixed, thank you!

**Comment by liZe** [comment]
> How would I enable `presentational-hints` when not using the CLI, but the python lib instead ?

You can use [the `presentational_hints` parameter of the `write_pdf` function](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.HTML.write_pdf).

**Comment by varac** [comment]
@liZe Awesome, hhanks !
