### ISSUE TITLE
Empty sub bullet point causes next bullet point to be on the same line

### ISSUE THREAD

**Issue by AlexDvorak** [Kozea/WeasyPrint#873]
Given the following HTML, with an empty sub bullet point as seen in the HTML below, weasyprint (v47) renders the following bullet point on the same line ![weasyprint](https://i.imgur.com/mDJVAp9.png)
but when the same HTML is rendered in Firefox, the bullet point is on its own line. ![firefox](https://i.imgur.com/qTvctqa.png)
when checking inspect element, the HTML does not correct to anything else so it would appear that this is an issue with weasyprint and not bad HTML I believe.
HTML that breaks Weasyprint (Firefox does not do anything else to it)
```html
<ul>
  <li>
    hello
    <ul>
      <li>hi</li>
      <li></li>
    </ul>
  </li>
  <li>hu</li>
</ul>
```

**Comment by liZe** [comment]
Thanks a lot for this report. I'm always surprised (and really disappointed) to discover really simple corner cases that are broken…

**Comment by liZe** [comment]
Well, the behavior is actually not defined by CSS, even in [recent modules](https://drafts.csswg.org/css-lists-3/#list-style-position-outside):

> The size or contents of the marker box may affect the height of the principal block box and/or the height of its first line box, and in some cases may cause the creation of a new line box; this interaction is also not defined.

I can try to find a way to make `li` elements at least as high as their markers.

**Comment by liZe** [comment]
@AlexDvorak It's fixed, thanks for the report!

If anyone knows how it's implemented in other browsers, please tell me! I suppose that an empty linebox is added, but it sounds like a really big change in the DOM for a very small feature.
