### ISSUE TITLE
text-overflow: ellipsis

### ISSUE THREAD

**Issue by stolzweb** [Kozea/WeasyPrint#874]
Would be very helpful to have the css "text-overflow: ellipsis" supported in WeasyPrint. :)

**Comment by liZe** [comment]
I've tried to play with this feature, I hoped that it would be an easy one, but it's not *that* easy because the property set on boxes is not inherited by anonymous `LineBox` children. I need to spend some time on this, but nothing's impossible.

**Comment by liZe** [comment]
Everything is ready in the `text-overflow` branch! Everything, but the `text-overflow` value that's not available in the text box as the property is not inherited :sad:.

**Comment by stolzweb** [comment]
thanks a lot! I just tested it. It is already close. :)
In the HTML Version, text-overflow:ellipsis adds 3 dots at the end of the cutted part, and it always cuts between two letters. In my generated pdf, a single letter is cutted and i can not see the 3 dots. 
My css is 
`text-overflow: ellipsis; overflow:hidden; white-space:nowrap;` 
(this is how i usually use it in normal websites) 
Attached the HTML Output and the PDF output
![output_html_browser](https://user-images.githubusercontent.com/36608478/60616996-0049af00-9dd3-11e9-826d-60802731fc93.PNG)
[output_pdf.pdf](https://github.com/Kozea/WeasyPrint/files/3356395/output_pdf.pdf)

**Comment by liZe** [comment]
> In the HTML Version, text-overflow:ellipsis adds 3 dots at the end of the cutted part, and it always cuts between two letters. In my generated pdf, a single letter is cutted and i can not see the 3 dots.

Actually, with the current code you never see the dots, because there's a variable that should be set according to the `text-overflow` value but that's currently set to `False`. 

https://github.com/Kozea/WeasyPrint/blob/e88190fc144e26efdebf161439e99c85daeaaba1/weasyprint/text.py#L1234-L1237

You can change it into `True` to get the ellipsis.

(Bonus: if you select the text in the PDF, you get the whole text, not the ellipsis :star2:.)

The "only" problem left is to set this attribute, but in this function we only have the text box, whereas the property is set on its parent. It sounds easy, but it's actually hard to fix it in a clean way.

**Comment by stolzweb** [comment]
Thanks a lot for your help :) It looks just perfect. Just that i understand it correctly: The css property "text-overflow: ellipsis" has no effect right now. Correct? Its all about the variable `text_overflow = True`, right? 

On what type of elements does it has this effect? Is it just when i set a width to an element an fill all the content in one line with `white-space:nowrap;` or on what other elements has this varialbe an effect to?
I ask because we generate a pdf with more than 1000 pages an it is hard to check all the pages if it hans an unwanted effect somewhere else

**Comment by liZe** [comment]
> The css property "text-overflow: ellipsis" has no effect right now. Correct? Its all about the variable `text_overflow = True`, right?

That's it. That's what I have to fix.

> Is it just when i set a width to an element an fill all the content in one line with `white-space:nowrap;` or on what other elements has this varialbe an effect to?

Your element must have `overflow` set to something different from `visible`, and it must have some text longer than its width (either automatically or manually set) because a word is longer than the line or because the line can't be split (for example when using `white-space: nowrap`).

https://www.w3.org/TR/css-overflow-3/#text-overflow

**Comment by liZe** [comment]
@stolzweb I've updated the code to take care of `text-overflow` (and add mandatory tests). Could you check that it works for you?

**Comment by liZe** [comment]
I've merged the pull request as it is time to release 48. Feel free to come back to me if you find any problems (or if everything works just fine :stuck_out_tongue:).

**Comment by stolzweb** [comment]
perfect, it seems to work as a charm :)

Herzliche Grüsse

Manuel Stolz
_______________________
Stolz WEB GmbH
Davidstrasse 40
9000 St. Gallen

T: +41 (0)71 511 38 20
F: +41 (0)71 511 38 29
Skype: stolzweb
www.stolzweb.ch

------ Originalnachricht ------
Von: "Guillaume Ayoub" <notifications@github.com>
An: "Kozea/WeasyPrint" <WeasyPrint@noreply.github.com>
Cc: "stolzweb" <info@stolzweb.ch>; "Mention" 
<mention@noreply.github.com>
Gesendet: 08.07.2019 13:28:44
Betreff: Re: [Kozea/WeasyPrint] text-overflow: ellipsis (#874)

**Comment by stolzweb** [comment]
Hi Guillaume

Sorry for pushing, but is there any possibility to integrate that?
https://github.com/Kozea/WeasyPrint/issues/577

That would be the last thing before it would be perfect for us :)

Herzliche Grüsse

Manuel Stolz
_______________________
Stolz WEB GmbH
Davidstrasse 40
9000 St. Gallen

T: +41 (0)71 511 38 20
F: +41 (0)71 511 38 29
Skype: stolzweb
www.stolzweb.ch

------ Originalnachricht ------
Von: "Guillaume Ayoub" <notifications@github.com>
An: "Kozea/WeasyPrint" <WeasyPrint@noreply.github.com>
Cc: "stolzweb" <info@stolzweb.ch>; "Mention" 
<mention@noreply.github.com>
Gesendet: 08.07.2019 13:28:44
Betreff: Re: [Kozea/WeasyPrint] text-overflow: ellipsis (#874)
