### ISSUE TITLE
Table and column widths ignored.

### ISSUE THREAD

**Issue by GrantEdwards** [Kozea/WeasyPrint#879]
Specifying table width and individual column widths in percentages seems to be ignored.  Normally my HTML is being generated by asciidoc.  I've attached a stripped down html file that demonstrates the problem along with the pdf produced by Weasyprint 47.  I've tried v43 and v0.41 with the same results.  I thought this used to work, but can't actually produce any evidence that it did.

[tablewidth.html.txt](https://github.com/Kozea/WeasyPrint/files/3273456/tablewidth.html.txt)
[tablewidth.pdf](https://github.com/Kozea/WeasyPrint/files/3273457/tablewidth.pdf)

**Comment by GrantEdwards** [comment]
Oh, I was using a trivial .css file to add table borders.  The same problem happens without it, but I guess I should attach it as well.

[weasyprint.css.txt](https://github.com/Kozea/WeasyPrint/files/3273480/weasyprint.css.txt)

**Comment by GrantEdwards** [comment]
If I use asciidoctor instead of asciidoc to generate the HTML, then I get the expected results.  I think the relevant difference is that asciidoc produces html that looks like this:
~~~
<table rules="all"
width="100%"
frame="border"
cellspacing="0" cellpadding="4">
<col width="40%" />
<col width="10%" />
<col width="50%" />
<thead>
...
</thead>
<tbody>
...
</tbody>

~~~
While asciidoctor produces more "modern" HTML where the widths are set by CSS rather than HTML element attributes.
~~~
<table class="tableblock frame-all grid-all stretch">
<colgroup>
<col style="width: 40%;">
<col style="width: 10%;">
<col style="width: 50%;">
</colgroup>
<thead>
...
</thead>
<tbody>
...
</tbody>
</table>
~~~

Eventually, I'll be switching from asciidoc to ascidoctor, and that will render this issue moot. But, that switch does require a bit of work...

**Comment by liZe** [comment]
Hello,

The `width` attribute in HTML is called a "presentational hint", and it's now recommended not to use them and use CSS instead.

Presentational hints are ignored by WeasyPrint by default, but you can handle them [using the `--presentational-hints` CLI parameter](https://weasyprint.readthedocs.io/en/latest/features.html?highlight=presentational#html).

Have fun with WeasyPrint!

**Comment by GrantEdwards** [comment]
Thanks!  It's pretty obvious now that I know where to look in the documentation.  Sorry for the noise.
