### ISSUE TITLE
Incorrect handling of div height of a div with display: flex, with two child divs

### ISSUE THREAD

**Issue by rnduldulaojr** [Kozea/WeasyPrint#885]
Given a parent div with css style:

```
.content {
    display: flex;
    border-bottom: 1px solid #ccc;
}
```

and two child divs with CSS:

```
           .content .left-panel {
                border-right: 1px solid #ccc;
                width: 30%;
                height: 100%;
                padding: 20px 10px 0 0;
            }

            .content .right-panel {
                width: 65%;
                height: 100%;
                padding: 10px 0  0 16px;
            }
```

the bottom border of the parent seems to be intersecting the children divs.  For comparison, I used another library (pdfkit) to generate pdf and the output of that is much close to the web page.

**Comment by liZe** [comment]
Thank you for this bug report! There was a stupid bug about percentages for flex items, it's fixed now with a non-regression test.

**Comment by yerycs** [comment]
Is it solved?
I have faced height % issue now.
