### ISSUE TITLE
ERROR: Failed to draw an SVG image at None : float division by zero

### ISSUE THREAD

**Issue by randomstuff** [Kozea/WeasyPrint#888]
One test is faling on my computer:

<pre>$ pytest weasyprint/tests/test_draw/test_image.py
[...]
__________________________________________________________________________ test_images_alt ___________________________________________________________________________

    @assert_no_logs
    def test_images_alt():
        with capture_logs() as logs:
            assert_same_rendering(200, 30, [
                (name, '''
                  <style>
                    @page { size: 200px 30px }
                    body { margin: 0; background: #fff; font-size: 0 }
                  </style>
                  <div>%s</div>''' % html)
                for name, html in [
                    ('image_alt_text_reference', 'Hello, world!'),
                    ('image_alt_text_not_found',
                        '<img src="inexistent2.png" alt="Hello, world!">'),
                    ('image_alt_text_no_src',
                        '<img alt="Hello, world!">'),
                    ('image_svg_no_intrinsic_size',
                        '''<img src="data:image/svg+xml,<svg></svg>"
                                alt="Hello, world!">'''),
                ]
            ])
>       assert len(logs) == 1
E       assert 2 == 1
E        +  where 2 = len(['ERROR: Failed to load image at "file:///home/foo/WeasyPrint/weasyprint/tests/resources/inexistent2.png...weasyprint/tests/resources/inexistent2.png\'>)', 'ERROR: Failed to draw an SVG image at None : float division by zero'])
</pre>

**Comment by randomstuff** [comment]
Bisected to 37e788e8c3f23b6c2f1124cf311e21bf5220faec

**Comment by liZe** [comment]
What's strange is that [tests pass on Travis](https://travis-ci.org/Kozea/WeasyPrint/builds/549183163) and on my computer too. Do you use the latest version of CairoSVG for your tests?

**Comment by randomstuff** [comment]
Indeed, I failed to properly upgrade the package, somehow :/
