### ISSUE TITLE
Conda WeasyPrint package compatible with Python 3

### ISSUE THREAD

**Issue by mjbeyeler** [Kozea/WeasyPrint#890]
Currently all WeasyPrint packages available for Conda online are only compatible with Python 2, which is sad.

I unfortunately don't have any expertice with building Conda packages and releasing them on a channel online, so I was wondering if anyone on here would be interested in building such a package and making it available online.

Best

**Comment by mjbeyeler** [comment]
And just so you know: I have looked at this previous issue: https://github.com/Kozea/WeasyPrint/issues/316

The problem here is that you have to use pip as a workaround. I would like to avoid this, as pip-installed packages don't appear in `conda list --explicit`, which I use to reproduce environments on different computers.

**Comment by liZe** [comment]
Hello!

Some people are working on it: conda-forge/staged-recipes#8477. They may need some work and/or some feedback, it may be useful to get in touch with them.

**Comment by liZe** [comment]
The recipe tests pass, we can hope to have an updated Conda package soon.

**Comment by liZe** [comment]
[Here it is!](https://anaconda.org/conda-forge/weasyprint)
