### ISSUE TITLE
Printing page numbers incorrectly

### ISSUE THREAD

**Issue by WRossStreet** [Kozea/WeasyPrint#892]
Hey, I am using WeasyPrint to generate monthly statements for some transactions. Typically it's less than one page of transactions. 

Starting in April the statements started printing "Page 2 of 1" at the bottom of them. The code I am using to generate the page numbers is this:

    @page {
        size: letter;
        margin: 130px 30px 40px 30px;

        @bottom-center {
            counter-increment: page;
            content: "Page " counter(page) " of " counter(pages);
            margin: 10px 10px 25px 10px;
        }
    }

I thought maybe the incorrect page numbers was the result of a patch to the library since I was not locking down the version number. Switched to version 44 of WeasyPrint that was generated the correct page numbers page in February, but it still generated the "2 of 1". 

One more detail is that one a statement which has two pages, it prints "2 of 2", and then "3 of 2". Seems like the page variable is off by one.

Any ideas how to solve this?

**Comment by Tontyna** [comment]
Remove `counter-increment: page;` from your `@page` definition.

Don't increment the builtin automatic  `page` counter explicitly unless you really want it to become something else than the actual page number.

**Comment by WRossStreet** [comment]
> Remove `counter-increment: page;` from your `@page` definition.
> 
> Don't increment the builtin automatic `page` counter explicitly unless you really want it to become something else than the actual page number.

That fixed it. Thank you very much!
