### ISSUE TITLE
Support for CSS GCPM ‘page groups’

### ISSUE THREAD

**Issue by caesar** [Kozea/WeasyPrint#895]
When formatting books for printing, we need to be able to use different margin box content on the first page of each chapter. (In my case, specifically, empty margin boxes to suppress the page numbers and titles which are shown on other pages.)

Prince supports this via the `:first` pseudo-class on named pages (eg `@page chapter:first`), however WeasyPrint does not support this and I believe in this respect Prince is in  fact not compliant with [the spec](https://drafts.csswg.org/css-page/#first-pseudo), since `:first` is (sadly) only intended to match on the first page of a document, not on the first page of a group  of  named pages.

The spec-compliant way to achieve this seems to be with CSS-GCPM’s ‘[page groups](https://drafts.csswg.org/css-gcpm/#document-sequence-selectors)’, eg `@page:nth(1 of chapter)`.
It would be great to see support for this in WeasyPrint!

**Comment by liZe** [comment]
Hello!

Yes, this feature would be useful. It had tried to solve this when closing #724, but as far as I can remember it was not that easy.

**Comment by caesar** [comment]
@liZe yes, I saw that. 👍 

Unfortunately I can't dedicate any time to working on this myself at the moment (and #844 and #640 are also blockers for my use-case at the moment and seem much harder to fix). But I thought it would be good to have it in the issue tracker.

By the way WeasyPrint has come a long way since I last looked at it a couple of  years ago, awesome work!
