### ISSUE TITLE
Whole table wrapping to next page instead of breaking

### ISSUE THREAD

**Issue by pytrumpeter** [Kozea/WeasyPrint#905]
Hi,

I'm trying to get a table in my PDF to break between rows onto the next page, so the table fits as much as possible onto the first page, then the rest goes to the next page.  I have tried with and without `style="page-break-inside: auto;"` and the table never breaks, it always bumps the whole table to the next page.  

I'm understanding correctly that breaking in the middle of the table should happen, right?

**Comment by liZe** [comment]
> I'm understanding correctly that breaking in the middle of the table should happen, right?

Yes, it should break. There's a well known bug #36 meaning that WeasyPrint can't break between table lines or in absolute / floating blocks. Is that your problem too?

**Comment by pytrumpeter** [comment]
Ugh yes, sorry I didn't look at #36 earlier.  I believe I dismissed it when it looked like a new feature request rather than a bug, and I didn't make the connection with floats.  I was able to get a workaround in place by using [this suggestion](https://github.com/Kozea/WeasyPrint/issues/36#issuecomment-334385676) with `clear: both`.

**Comment by liZe** [comment]
> Ugh yes, sorry I didn't look at #36 earlier. I believe I dismissed it when it looked like a new feature request rather than a bug, and I didn't make the connection with floats.

No problem!

> I was able to get a workaround in place by using [this suggestion](https://github.com/Kozea/WeasyPrint/issues/36#issuecomment-334385676) with `clear: both`.

Good to know. You can probably just use `clear: both` on your table without adding an extra `div`.

**Comment by CarlosPrb** [comment]
I'm trying to get a table in my PDF to split between rows on the next page, so that the table fits as much as possible on the first page and then the rest goes to the next page. I have tried with and without this function, style="page-break-inside: auto; ”and the table never splits, it always passes the whole table to the next page.

**Comment by liZe** [comment]
@CarlosPrb This issue has been fixed, so your problem is different. Could you please open a new issue and share a document that shows your problem?
