### ISSUE TITLE
Trouble to get image centered when generating PDF

### ISSUE THREAD

**Issue by bioreps** [Kozea/WeasyPrint#908]
Weasyprint version: 47

I have the following piece of html (just the snippet where I have a problem):
```
<figure>
<img src="image.png"/>
<figcaption>This is my caption</figcaption>
</figure>
```

My Weasyprint call is:
`weasyprint input.html output.pdf -s my.css`

So pretty standard html. I am not able to center this image horizontally on the PDF page. I tried many ways via CSS but all failed. However, the CSS is NOT ignored by Weasyprint. For example modifying the size of the image works. Since I tried so many ways, I can not give you a minimal example there. Would not know how to pick one.

Can you confirm that this should be possible (center the image horizontally) and may someone provide a hint how to do this?

**Comment by liZe** [comment]
Using `text-align: center` on the figure works. You can also set `display: block; margin: auto` on the image if you only want to get the image centered (and not the caption).

**Comment by bioreps** [comment]
Oh, my bad. I had some embedded CSS in the html I was converting to PDF. And apparently the embedded CSS had higher priority. Sorry.
