### ISSUE TITLE
DLL hell at its finest

### ISSUE THREAD

**Issue by osmosishk** [Kozea/WeasyPrint#912]
I have tried install the weasyprint on my windows 10 , with python 3.7.4 , before that i have faced the problem of OSError: dlopen() failed to load a library: cairo / cairo-2 but I have solved it to add the path . But now i have faced another problem below
OSError: cannot load library 'pangocairo-1.0': error 0x7e.  Additionally, ctypes.util.find_library() did 
not manage to locate a library called 'pangocairo-1.0'

Is anyone has faced the same issue and any solutions

**Comment by guilt** [comment]
I just got the thing to work. So maybe I can help.

Steps:

1) Install Python 3.7.x

2) I installed the [GTK3 Runtime](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases/download/2019-07-02/gtk3-runtime-3.24.9-2019-07-02-ts-win64.exe) and default settings, it added it to PATH as well as put executables and DLLs in \bin

3) Simply ran: pip install WeasyPrint

4) weasyprint http://github.com test.pdf

It just worked for me. Can you at least give more details about the issue you are having?

**Comment by osmosishk** [comment]
Hi @guilt  , thanks for your steps. I have tried to uninstall all the thing and reinstall it on a fresh environment. But it still does not work. I tried it on other Win7 desktop but works very good, I think it is the problem on Windows 10

**Comment by Tontyna** [comment]
@osmosishk The error you get indicates that there is another (outdated?) GTK somewhere on your system, so please make sure that the GTK Runtime BIN-folder is **at the beginning** of your PATH, not at its end.

To check whether your Python/WeasyPrint has the correct PATH, you can execute the following command in the Command Prompt where WeasyPrint fails to run (you do run WeasyPrint from a Command Prompt, do you?):

```
python -c "import os; print(*os.environ['PATH'].split(os.pathsep), sep='\n')"
```

That's the PATH your Python/WeasyPrint knows. I'm quite sure that on your Windows 10 system your GTK Runtime BIN-folder isn't included.

**Comment by osmosishk** [comment]
Hi @Tontyna thanks for your input and i have checked my path showing all correct path , but it still not works

![20190730171318](https://user-images.githubusercontent.com/20733882/62116795-5d128980-b2ed-11e9-809f-2ba63d89a98b.png)
![20190730171416](https://user-images.githubusercontent.com/20733882/62116852-787d9480-b2ed-11e9-9e0f-7042d3ad7757.png)

**Comment by Tontyna** [comment]
This is not a regular Windows Command Prompt! Looks like a bash/msys/github shell -- see e.g. the string `%PATH%` in the first output.  In a regular Windows cmd this variable would be expanded to the previously set PATH value...

I fear, this shell doesn't load DLLs fom the PATH (what PATH?), like it does/should do on Windows. My experience with msys-shells is: They tend to identify themselves as **posix**

Try (in that shell) the following command:

```
python -c "import os; import sys; print(os.name,  sys.platform)"
```

Does your use case require that WeasyPrint is run from that shell? Cant you use a stupid normal Windows cmd prompt? I believe in a regular prompt your problem disappears.

**Comment by Tontyna** [comment]
Contemplating your screenshots it looks like the shell you are using is PowerShell, but a heavily modified one. Especially the PATH looks crazy to me: 

- first entry containing `/Scripts` (with slash!)
- third entry `%PATH%` -- there is no %PATH% in PowerShell, it's `$env:PATH`
- duplicate entries for mingw64
- duplicate entries for the GTK3 Runtime
- no Windows system folders at all, that's strange

@osmosishk I'd really like to know how you open this specialized shell...

Furthermore I suggest you 

- **either**
  remove `C:\mysy64\mingw64\bin` from the PATH and keep the GTK3 Runtime in `C:\Program Files` up-to-date
- **or**
  remove `C:\Program Files\GTK3-Runtime Win64\bin` from your PATH and update the `mingw-w64-x86_64-gtk3` package of your MSYS2 system

**Comment by osmosishk** [comment]
Hi @Tontyna for your great input , I will try it out today and give you a feedback

**Comment by osmosishk** [comment]
@Tontyna Finally i got to make it works! I make a stupid mistake and keep looping the errors.

1. I still got the error message in Powershell windows and i still try to make path work, since my attention was focused on path environment and i thought weasyprint cannot find the  library: cairo / 
cairo-2 .

2. Keep remove the python , weasyprint and GTK. but fail

3. I use cmd prompt and type WHERE libcairo-2.dll  , it show the correct path : C:\Program Files\GTK3-Runtime Win64\bin\libcairo-2.dll

4. i use cmd prompt and run python and import weasyprint , the windows pop up show " the procedure entry point inflatevalidate could not be located libpng16 16 dll "

5. The search this error in google and someone advise it is the problem of zlib1.dll , the program used the libary in c:\windows\system32 32bit one rather the 64 bit one in C:\windows\syswow64

6. I renamed the zlib1.dll in system32 , then it works

That is because i have installed a 32bit GTK before ... nightmare, it keeps finding the system32\zlib1.dll

6.

**Comment by Tontyna** [comment]
@osmosishk I suggest you rename the issue to *DLL hell at its finest*
