### ISSUE TITLE
Fix tests with Pango 1.44

### ISSUE THREAD

**Issue by liZe** [Kozea/WeasyPrint#917]
Pango 1.44 has been released with a lot of changes that break 13 tests (same results on Linux and macOS, that's good news).

**Comment by liZe** [comment]
Cairo 1.17.2 breaks 2 other tests.

**Comment by liZe** [comment]
Cairo 1.17.2 seems to be broken in many ways, let's wait for a more stable snapshot.

**Comment by liZe** [comment]
The fix in d6da699 is not really good, it's just a workaround. As it breaks one test with the previous versions of Pango, and as this test is not a corner case, I have to find a better fix.

**Comment by Tontyna** [comment]
Why bother with a fix for a broken Pango **patch** version? Will Pango 1.44.3 be widespread and last for long?

**Comment by liZe** [comment]
> Why bother with a fix for a broken Pango **patch** version? Will Pango 1.44.3 be widespread and last for long?

The fixes are for 1.44.x, not for 1.44.3 only (do you really think I'm such a masochist?). There's no workaround in d6da699 for 1.44.3's bug, we'll wait for 1.44.4 to have tests passing.

But the way line heights are calculated in Pango 1.44.x really breaks WeasyPrint rendering, that's what we have to fix.

**Comment by Tontyna** [comment]
> do you really think I'm such a masochist?

Of course you are -- it's Saturday! No sane person ever looks after stupid software on weekends

**Comment by Tontyna** [comment]
aab0fa5  is definitely much healthier than d6da699

**Comment by liZe** [comment]
> [aab0fa5](https://github.com/Kozea/WeasyPrint/commit/aab0fa5b9d8c8a3960ba79f6c54ad56c64a1c06d) is definitely much healthier than [d6da699](https://github.com/Kozea/WeasyPrint/commit/d6da699f9106eb5261faf21c551fba9d5656acfa)

It is.

**Comment by liZe** [comment]
The last failing test is fixed in Pango 1.44.4, that has been released (and works for me) but not packaged yet in Homebrew.

**Comment by Tontyna** [comment]
MSYS2 is still with Pango 1.43.0 .
There's even a (recent) comment in their PKGBUILD file:

> \# Don't update to 1.44.0! https://gitlab.gnome.org/GNOME/pango/issues/385

**Comment by liZe** [comment]
:tada: https://travis-ci.org/Kozea/WeasyPrint/builds/572272435 :tada:

> MSYS2 is still with Pango 1.43.0 .
> There's even a (recent) comment in their PKGBUILD file:
> 
> > \# Don't update to 1.44.0! https://gitlab.gnome.org/GNOME/pango/issues/385

This issue is fixed now, with a couple of "bad" changes they tried to include and that have been reverted now. These two blog entries ([1](https://blogs.gnome.org/mclasen/2019/07/27/more-text-rendering-updates/), [2](https://blogs.gnome.org/mclasen/2019/08/07/pango-1-44-wrap-up/)) are really interesting to understand their choices. We can expect other big changes in the future months, but I'm pretty confident, they know what they're doing.

> Cairo 1.17.2 seems to be broken in many ways, let's wait for a more stable snapshot.

This is just a dev snapshot, and they've tried hard to separate stable from unstable releases since 1.16.0, so we can wait a little bit more. My computer was barely usable with it… And I'm not the only one hoping for more regular releases, [even Behdad Esfahbod is fed up with that](https://lists.cairographics.org/archives/cairo/2019-August/028910.html).
