### ISSUE TITLE
Is required Pango 1.38 to handle @font-face rules in 0.29 version?

### ISSUE THREAD

**Issue by cinarizasyon** [Kozea/WeasyPrint#918]
I use weasyprint 0.29 version. I occured some issues when using @font-face css rules. My pango version is 1.28. Documentation of WeasyPrint 48 says you should install pango min 1.38 version to handle @font-face rules. Is same warning valid in 0.29 version?

**Comment by liZe** [comment]
Hello!

`@font-face` rules are supported since [version 0.32](https://weasyprint.readthedocs.io/en/latest/changelog.html#version-0-32). And even with version 0.32, Pango > 1.38 is needed.
