### ISSUE TITLE
Bad layout of CSS "flex" 

### ISSUE THREAD

**Issue by mPyth** [Kozea/WeasyPrint#919]
Here are the Chrome screenshots that demonstrate intention for using vertical flex.
![intentionForUsingFlex](https://user-images.githubusercontent.com/18519715/62864099-1b310c80-bd0b-11e9-8696-8e0ae3ae6486.png)
On the left side is example of Contract with body (light-green) that could vary a few lines. The goal is to keep the signature section at the bottom of the page (light-purple), independently of how much lines contract body has. On the right side is exactly same CSS and HTML with only added lines "Line 8" and "Line 9". Only yellow-light **div** has "**flex-grow**" set to **1**, so it takes the rest space from the parent.

For all examples here file [flexDemo.zip](https://github.com/Kozea/WeasyPrint/files/3492327/flexDemo.zip) is used.

-----------------------------------------------------------------------
Next two screenshots are taken from Chrome. To get screenshot on the left class "**vertFlex**" should be removed from the HTML (from root **div**), so layout will be standard "**block**" (there is no need to remove "takeTheRestVertSpace" class from HTML because its parent is not "**flex**" so it will be ignored).
![flexExpectedBehavior](https://user-images.githubusercontent.com/18519715/62864567-5b44bf00-bd0c-11e9-9c56-8b85349f990a.png)
Remark: the root **div** has light-cyan background – it is possible to see it on the left screenshot – area on the bottom.
On the right is the screenshot with the same file but with "**vertFlex**" class put back to root **div** element. It is important to notice next changes:
* all sections with exception of light yellow has the same height
* the whole document has the same height
* after root **div** got "**vertFlex**" its child with "**flex-grow**" set to **1** takes the all the space from the root **div**, so light-cyan area does not exist any more.
-----------------------------------------------------------------------
Below are screenshots which are created by using WeasyPrint Renderer (simple copy-paste from mentioned file). On the left class "**vertFlex**" is removed from root **div**, on the right "**vertFlex**" is put back.
![flexBehaviorInWeasyPrint](https://user-images.githubusercontent.com/18519715/62864703-beceec80-bd0c-11e9-95c5-6c252b4b4971.png)
It is possible to observe next changes:
* 1st section (Contract Title) has no the same height - NOT expected behavior
* root **div** height becomes larger – NOT expected behavior
* 2nd (light green) and 4th section (light-purple) has the same height as before change – this is expected behavior.
* light-cyan area is not visible any more – this is expected behavior
* light-yelow **div** takes more space than before – this is expected behavior 

Problem is reproduced by using Windows 10, Python 3.7.3 and WeasyPrint 48.

**Comment by liZe** [comment]
Thanks for the perfect bug report! It was just a stupid typo.
