### ISSUE TITLE
html.write_bmp?

### ISSUE THREAD

**Issue by devrosx** [Kozea/WeasyPrint#925]
hello, im using weasyprint as renderer html for my smart eink and works really great.... Problem is that only bmp file is supported  by eink driver and i have to use PIL to convert image to bmp and that makes script little slower. Could be posible to add  function html.write_bmp with raw file for faster procesing...

thanks Jan

**Comment by liZe** [comment]
Hello Jan!

> hello, im using weasyprint as renderer html for my smart eink

:roll_eyes: Wow! I'd love to see a picture of that!

> Could be posible to add function html.write_bmp with raw file for faster procesing...

Unfortunately not, as we depend on Cairo's output formats, which are PDF, PS, PNG and SVG, but not BMP. So, the only way to have this feature would be … to use the PIL :disappointed:.

**Comment by devrosx** [comment]
thanks for info here is picture of my first version :) its conected with domoticz and google calendar...
![IMG_0713](https://user-images.githubusercontent.com/13789041/63215194-70ae5480-c123-11e9-8daa-2123706ecb1a.jpg)

found this about cairo and bmp saving
https://lists.cairographics.org/archives/cairo/2008-November/015692.html
but looks its not directly supported

**Comment by liZe** [comment]
> thanks for info here is picture of my first version :) its conected with domoticz and google calendar...

:heart: :heart_eyes: :heart_eyes_cat: 

> found this about cairo and bmp saving
> https://lists.cairographics.org/archives/cairo/2008-November/015692.html
> but looks its not directly supported

Your example uses a C# imaging library, just as the PIL for Python. But it's better than generating a PNG file and converting it into a BMP, because it goes directly from the Cairo surface to a PNG file.

You can use WeasyPrint the same way:
```python
import PIL
from weasyprint import HTML

rendering = HTML('https://www.webstandards.org/files/acid2/test.html').render()
image_surface, width, height = rendering.write_image_surface()
image = PIL.Image.frombytes(
    'RGBA', (width, height), image_surface.get_data()[:], 'raw', 'BGRA')
image.save('/tmp/image.bmp')
```

Hope that it will work (and be faster) for you!

**Comment by devrosx** [comment]
great trick, thanks you saved me about 3 seconds in my tests...
used your code only added image = image.convert('L') to convert to grayscale...


thanks

**Comment by devrosx** [comment]
Hello looks like api is changed. Cant find way to save ti image, any idea?

**Comment by liZe** [comment]
> Hello looks like api is changed. Cant find way to save ti image, any idea?

It’s been [removed in version 53](https://www.courtbouillon.org/blog/00009-weasyprint-53-what-s-new). Using Ghostscript to transform the PDF into a bitmap is the best solution now.

**Comment by devrosx** [comment]
Thanks, I already see it, before I overlooked it in changelog, is there any chance that it will ever work again ...? How it worked was more elegant (without saving PDFs and reloading). So for now it's better for me to stay with the old version

**Comment by liZe** [comment]
> is there any chance that it will ever work again

Unfortunately no, the code is now really PDF-oriented.

> How it worked was more elegant

As WeasyPrint can write to and Ghostscript read from a pipe, you don’t have to save the PDF on disk:

```
weasyprint document.html - | gs -q -dNOPAUSE -dSAFER -dBATCH -sDEVICE=png16m -sOutputFile='document.png' -
```

And you have more options (reorganizing pages, change format, hinting, antialiasing…) with Ghostscript than you used to have with WeasyPrint.
