### ISSUE TITLE
Add support to open local files using Launch action instead of URI action

### ISSUE THREAD

**Issue by dvilchez** [Kozea/WeasyPrint#929]
As far as I know, currently the way to open local files is using a relative path and omitting the baseURL parameter #466 and #467 but, it doesn't work. WeasyPrint uses always the URI action and many viewers are not able to open the files (Foxit Reader, MacOS Preview) and in the case of Acrobat Reader the user have to accept to warnings before accessing to the file.
![2019-08-29 at 17 31](https://user-images.githubusercontent.com/153025/63954227-0e3e4800-ca83-11e9-9e84-fdc16d86df3f.png)
https://github.com/Kozea/WeasyPrint/blob/023a9f1220b79026b69289e11b7f627affea0ff0/weasyprint/document.py#L559

According to the standard the right way to open a local files is using the Launch action:
![2019-08-29 at 17 24](https://user-images.githubusercontent.com/153025/63953754-3aa59480-ca82-11e9-94c1-076b495c893e.png)

Cairo also support this option with File Links https://www.cairographics.org/manual/cairo-Tags-and-Links.html#file-link

I don't know enough about the WeasyPrint code-base to propose a solution but I would like to hear some opinions and ideas.

Regards,

**Comment by Tontyna** [comment]
Quoting the Cairo manual you linked (emphasis mine):

> file : File name of **PDF file** to link to.

**Comment by liZe** [comment]
> file : File name of **PDF file** to link to.

Yes, it only works with PDF files. Cairo uses the "GoToR" action, not "Launch" for that.

If the feature is not in Cairo, I'm afraid we can't do anything… I didn't know that it doesn't work for many PDF readers, because it perfectly works for mine (Evince).

**Comment by liZe** [comment]
As there's no solution, I think that I can close this issue. Please let me know if there's a way to do this, other than using something different from Cairo.
