### ISSUE TITLE
counter-reset: page

### ISSUE THREAD

**Issue by hejsan** [Kozea/WeasyPrint#93]
Is there a plan to support counter-reset?

I have to generate a pdf combined of a lot of reports for different students. Each report needs to have individual page numbers, i.e. not 1/117 thru 117/117 but instead each one would have numbers relative to just that one report, more like 1/5 thru 5/5 and so on.

So optimally counter-reset: page; should reset the counter to 1 and also make the counter(pages) evaluate correctly the number of pages since the last reset.

Is that even doable?

As a backup plan, do you know of any commandline tool to merge multiple pdf's into one that installs on centos?

Thanks for a superb tool btw.

**Comment by bimco-dbj** [comment]
It would be really sweet if weasyprint could use counter-reset at all - so far I'm surprised to see just how much can actually be done, and this seems to be the only immediate drawback. :)

**Comment by rpzk** [comment]
Hello! Could you please clarity this code to me and point me to more productive direction?
"""
    documents = [HTML(string=render_template(student)).render() for student in students]
    documents[0].copy([page for doc in documents for page in doc.pages]).write_pdf(target)
"""
Because I need to throw a pdf with several pages, with different orientations, backgrounds and sizes.
This is a fragment of my code:

    paginas = []
    if orientacoes['orientacoes']:
        orientacoes_template = loader.get_template("impressos/receitas/orientacoes.html")
        orientacoes_html = orientacoes_template.render(RequestContext(request, dict(contexto.items() + orientacoes.items())))
        orientacoes_pdf = HTML(string=orientacoes_html).render()
        paginas.append(orientacoes_pdf)
    if estadual['estadual']:
        estadual_template = loader.get_template("impressos/receitas/estadual.html")
        estadual_html = estadual_template.render(RequestContext(request, dict(contexto.items() + estadual.items())))
        estadual_pdf = HTML(string=estadual_html).render()
        paginas.append(estadual_pdf)
    paginas[0].copy([pagina for p in paginas for pagina in p.pages]).write_pdf('teste.pdf')
    return HttpResponse(paginas, content_type='application/pdf')

Thanks a lot for your knowledge and time.

**Comment by Tontyna** [comment]
The PrinceXML example provided by @ktross is desirable and plausible but doesn't conform to the [spec](https://www.w3.org/TR/css3-page/#page-based-counters). Quoting section 7.1:

> Additionally, a counter named ‘pages’ is automatically created by the UA. Its value is always the total number of pages in the document. (In continuous media this is always 1.) The value of ‘pages’ cannot be manipulated: while ‘counter-reset’ and ‘counter-increment’ statements that set it are valid, they have no effect. 

An immutable `pages` counter in combination with a changeable `page` counter? Sounds ill-conceived -- but that's what the spec says.

**Comment by liZe** [comment]
> An immutable `pages` counter in combination with a changeable `page` counter? Sounds ill-conceived -- but that's what the spec says.

Then we can close this issue. Reading #631 helps to understand how counters work according to the spec.

> named pages and custom counters would allow for separate page numbers per section, but is there a way to get the total pages per section?

I've tried hard to find a solution for this, but I can't find it :cry:. It's more a limitation of the spec than a limitation of WeasyPrint as far as I can tell.
