### ISSUE TITLE
libpng16-16dll missing entry point

### ISSUE THREAD

**Issue by PaulNel** [Kozea/WeasyPrint#933]
Entry Point Not Found

When running start up after installing I am getting a couple of popup dialogs

Entry Point Not Found
The procedure entry point inflateReset2 could not be located int he dynamic link Library c:\Program Files\GTK3-Runtime Win64\bin\libpng16-16.dll.

**Comment by Tontyna** [comment]
@PaulNel Please run the following code in a command prompt:

```
python -c "import os; os.environ['PATH'] = os.pathsep.join([r'c:\Program Files\GTK3-Runtime Win64\bin', os.environ.get('PATH', '')]); import weasyprint; print(weasyprint.VERSION)"
```

The output should be a single string and no strange errors.

I guess you have various GTKs on your PATH. Putting the required GTK folder at the beginning of the PATH should solve the issue.

**Comment by amesplant** [comment]
I am getting the same error:
`The procedure entry poing inflateValidate could not be located in the dynamic link Library C:\msys2\mingw64\bin\libpng16-16.dll`
followed by another dialog error:
`The procedure entry poing inflateValidate could not be located in the dynamic link Library C:\msys2\mingw64\bin\libfontconfig-1.dll`

When I enter in what you have above (with my correct path)
I get `'There are known rendering problems and missing features with' 48`

**Comment by Tontyna** [comment]
@amesplant update the GTK in your *correct path* (Cairo ≥ 1.15.4), put that folder at the top of your PATH and WeasyPrint will work like a charm.

**Comment by liZe** [comment]
@PaulNel @amesplant Is that fixed for you?

**Comment by liZe** [comment]
Please reopen if needed!

**Comment by amesplant** [comment]
> @PaulNel @amesplant Is that fixed for you?

Sorry, yes it did fix the issue for me.

**Comment by NickFaulkner101** [comment]
I'm facing the same issue, and my path is updated

**Comment by NickFaulkner101** [comment]
anyone know what to do?

**Comment by sayga231** [comment]
Having the same issue, when I run with Django runserver, it gives me the error, when I run from CMD it works flawlessly

**Comment by liZe** [comment]
> Having the same issue, when I run with Django runserver, it gives me the error, when I run from CMD it works flawlessly

It means that the libpng16 library used when you run Django is not the same as the one used with CMD. If you have the whole library path in the traceback, you can probably understand why.
