### ISSUE TITLE
Bleed & Page Backgrounds

### ISSUE THREAD

**Issue by ckorhonen** [Kozea/WeasyPrint#934]
I found WeasyPrint from a [blog post](https://blog.rebased.pl/2018/07/12/wkhtmltopdf-considered-harmful.html) and so far I'm finding it a great fit for my needs. I did however run into one issue with bleed marks and was wondering if I was missing something.

I want to generate a 6"x4" PDF for printing with bleed and crop marks. I have a HTML document sized slightly larger than the desired size (to give me some bleed), and it has a either an image or solid color as the background.

The PDF I'm getting out is clipping the background at the size of the `@page`, meaning that I have no bleed area.

This image I found on Google probably does the best to visually illustrate  what I want, with the background extending into the bleed area.

![image](https://user-images.githubusercontent.com/39121/64034734-3a0e0c00-cb1d-11e9-94c8-57e8fb75f7e0.png)

Am I missing something here?

```html
<html>
  <head>
    <meta charset="UTF-8">

      <style>
          body {
              width: 6.25in;
              height: 4.25in;
              margin: 0;
              padding: 0;
              background: red;
              color: white;
          }
      </style>
  </head>
  <body>
    <h1><center>Hello World!</center></h1>
  </body>
</html>
```

```css
@page {
  bleed: auto;
  margin: 0;
  marks: crop cross;
  size: 6in 4in;
}
```

```shell
weasyprint test.html test.pdf -s 4x6.css
```

**Comment by Zopieux** [comment]
If weasyprint has no bleed support, I'd suggest simulating it by having a div for your page box content, and put the content that shall bleed (eg. your image) outside of that div. Then adjust page size/margins to account for this hack.

**Comment by Tontyna** [comment]
According to the docs, page marks and bleeds are supported [since Version 0.41](https://weasyprint.readthedocs.io/en/stable/changelog.html?highlight=bleed#version-0-41)

I confess: I have no idea how marks and bleeds **should** be implemented (oops -- outside the page-box? non-printable area?) but a css like that produces something that comes close to the picture you provided

```css
body {
    margin: 0;
    background: red;
}    
@page {
    size: 6in 4in;
    bleed: 1in; 
    marks: crop cross;
    margin:-0.25in;
}     
```
The negative `@page margin` creates the *bleeding* area -- the `bleed` value of 1 inch gives room to draw the marks. The actual size of the page-box (red body) is 6.5 x 4.5

**Comment by liZe** [comment]
Hello!

> The negative `@page margin` creates a 0.25in wide _bleeding_ area -- the `bleed` value of 1 inch gives room to draw the marks. The actual size of the page-box (red body) is 6.5 x 4.5.

That's a solution.

If you prefer to keep a 6 × 4 page size, another solution is to set the background color in the `@page` rule. Page content that has to bleed outside the page area (for example the image of your example) must be positioned with negative margins for example.

```html
<html>
  <head>
    <meta charset="UTF-8">
    <style>
      @page {
        background: red;
        bleed: 0.5in;
        margin: 0;
        marks: crop cross;
        size: 6in 4in;
      }
      body {
        margin: 0;
        padding: 0;
        color: white;
      }
      img {
        display: block;
        width: 104%;
        margin-left: -2%;
        margin-top: -2%;
      }
    </style>
  </head>
  <body>
    <img src="https://picsum.photos/id/921/600/100" />
    <h1><center>Hello World!</center></h1>
  </body>
</html>
```

**Comment by liZe** [comment]
Feel free to reopen if needed.
