### ISSUE TITLE
Unsatisfiable versions in conda

### ISSUE THREAD

**Issue by galpsten** [Kozea/WeasyPrint#939]
Hi
I am running python in a miniconda environment. My relevant configuration looks like this

```
name: XYZ
channels:
   - conda-forge
   - defaults
dependencies:
   # Basic
   - python
   - pip
   - conda

   # Genearate html to PDF
   - weasyprint
   - cairo >= 1.15.4 # 2D graphics library, version required by Weasyprint
```

Weasyprint request certain cairo versions. This worked until today:

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cairo[version='>1.15.4']
  - weasyprint -> cairocffi[version='>=0.9.0'] -> cairo[version='1.14.*,>=1.14.12,<2.0a0']
```
I see that https://github.com/Kozea/cairocffi released a new version yesterday. I had initial issues with getting the versions to work out, but thought it might be good to flag for the issue in the meanwhile.

I have created a ticket in cairocffi while I experiment with restricting versions manually
https://github.com/Kozea/cairocffi/issues/138

**Comment by liZe** [comment]
See Kozea/cairocffi#138.

**Comment by galpsten** [comment]
It may have been another issue. Closing for now

**Comment by galpsten** [comment]
Thank you for the attention!
