### ISSUE TITLE
Support for nested ordered list

### ISSUE THREAD

**Issue by prem911** [Kozea/WeasyPrint#940]
I m on version 48 and it looks like nested ordered list is not supported.
```
	    <ol type="1">
            <li><strong>1111</strong>
                <ol type="a">
                    <li>aaaa</li>
                    <li>bbbb</li>
                    <li>cccc</li>
                    <li>dddd</li>
                </ol>
            </li>
            <li><strong>Salary:</strong></li>
            <li><strong>Employment Conditions:</strong></li>
        </ol>
```

Result
![image](https://user-images.githubusercontent.com/7778147/64523056-0bf8ab00-d319-11e9-837e-e9a7d3820b98.png)

Expected
![image](https://user-images.githubusercontent.com/7778147/64523102-2cc10080-d319-11e9-87c3-f601e5da8a33.png)

**Comment by liZe** [comment]
Hello!

This is supported in WeasyPrint, but you have to use the `presentational-hints` option. You'll find more about this in [the documentation](https://weasyprint.readthedocs.io/en/stable/features.html#html).
