### ISSUE TITLE
Footer appears to be bumping up list items on a `<ul>` that's split across pages

### ISSUE THREAD

**Issue by craigpla** [Kozea/WeasyPrint#943]
I'm only noticing this in the table of contents so far. Items 2, 4, 6, and 8 in the attached pdf. They appear to be bumped up about the same distance as my lower @page declarations.
I'm making the PDF with the following commands:
```
pandoc -s --template="templates/default.html" -f markdown-smart --toc -c style.css "$filename.md" -o "$filename.html"
python3 -m weasyprint "$filename.html" "$filename.pdf"
```
[test.pdf](https://github.com/Kozea/WeasyPrint/files/3622554/test.pdf)

**Comment by Tontyna** [comment]
Hard to tell without the HTML/CSS, but could be related to `widows` and `orphans` or `break-before` / `break-after` rules.

**Comment by craigpla** [comment]
Yeah, I was initially thinking css issue, but looking at the rendered html it's fine. Figured I'd start here and see if anyone might know what's shaking.

**Comment by Tontyna** [comment]
I recollect similar apparitions with margins (or was it padding?) when a document required *repagination* because of unresolved `target-counter`s. Forgot about it because I was so happy that the `target-counter` finally went smoothly ... I vaguely remember there were headings involved, didn't realize that *split-across-pages* might be the point ... will try to find my notes on this again.

**Comment by craigpla** [comment]
Just commented out all of my bottom- declarations, and it's still doing it, so I guess disregard my first comment about it being the same height...

**Comment by Tontyna** [comment]
Yes, I dont think it's related to footers. It's a side-effect of the **repagination**. But (slowly I remember) only the second pass suffers from that, no escalation in third, fourth etc. re-make.

**Comment by craigpla** [comment]
This PDF I just made, after some heading shenanigans, doesn't have the problem anymore, so I'm all set for now. But I've got a blog post coming out next week where I'm hoping to give my template (the whole pandoc/weasyprint process) away to anyone who wants it. Hopefully it will save some folks the months it's taken me to get this far. If you happen to find the answer, you'd be in the Very Awesome department.

**Comment by Tontyna** [comment]
Oh, "shenanigans", nice word :smiley:, had to look that up.
To find the answer it could be helpful to know what sort of shenanigans saved your day.

**Comment by craigpla** [comment]
There were a bunch of H3s in a row, and some were supposed to be H2, so I didn't end up having long enough lists to get broken over a page in the TOC.
I'm from the NorthEast US, but I think shenanigans is Irish. It was the name of an Irish pub I played in once, anyway.

**Comment by Tontyna** [comment]
Reason was IMHO a wrong comparison in `ParentBox._remove_decoration`. Not sure whether this didnt hurt when no **repagination** was required, but keeping (and restoring) the original style for boxes across page breaks is required for proper top-margin, top-padding and top-border.

**Comment by craigpla** [comment]
Can you translate a bit? Is there something I can do when running the weasyprint command, or it something bigger?

**Comment by Tontyna** [comment]
See my pull request #948 -- its just a one-character-edit in the WeasyPrint source file `weasyprint/formatting_structure/boxes.py`

**Comment by Tontyna** [comment]
Explanation: When, during pagination, a block (like a list or a pararaph) is spread across two pages, the part on the first page receives all the *top properties* like `margin-top`, `padding-top`, `border-top-width` -- its *bottom properties* are set to `0` (zero). The part on the second page gets the *bottom properties* and zero for the *top properties*, like that:

```
+----------------+
|                |    "top-properties"
| lorem ipsum    |
| dolor sit amet |
========================= page break
| continued      |
| on next pageed |
|                | "bottom-properties"
+----------------+
```

No problem when the pages are generated in one pass, but to resolve the `target-counters`, the box is sent through the pagination again -- (without my fix) with the modified (zeroed) *top properties* in its associated style.
Not sure whether my PR has unwanted side effects, but at least it does what the comment says

https://github.com/Kozea/WeasyPrint/blob/c33ca0893d0dcda00b89e6b3844e63ecb8d164aa/weasyprint/formatting_structure/boxes.py#L325

it copies the style when there's need for. And my test case is rendered properly. No bumped up paragraphs.
