### ISSUE TITLE
CSS question: container padding on each page

### ISSUE THREAD

**Issue by LukasKlement** [Kozea/WeasyPrint#947]
When a container spans multiple pages having a padding set, the padding will apply around the container. Is it possible to have the padding apply on each page instead?

Here an illustration of what is meant: https://cl.ly/09223d197d07

**Comment by liZe** [comment]
Hello!

> Is it possible to have the padding apply on each page instead?

Yes, you can use the [`box-decoration-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break) property.

Have fun!

**Comment by LukasKlement** [comment]
Thank you, I was unaware of its existence; it works marvellously.
