### ISSUE TITLE
PDF metadata from HTML 

### ISSUE THREAD

**Issue by osroca** [Kozea/WeasyPrint#949]
It looks like the `<meta name="author">` (author, title, descritption, generator, and the other tags) are being ignored when generating the  PDF metadata.
I have this in my html template:
```
  <head>
    <meta charset="utf-8">
    ... 
    <title>Purchase order #3321</title>
    <meta name=description content="Purchase order #3321">
    <meta name=author content="My Corp">
    <meta name=generator content="My Corp">
  </head>
```
and generating the pdf from:

```
html = HTML(string=html_string)
html.write_pdf(sys_path)
```

And at the end, in the PDF I only have this in the PDF metadata inspector:

![image](https://user-images.githubusercontent.com/743922/65455798-48afc080-de48-11e9-81e5-60b291d319de.png)

**Comment by Tontyna** [comment]
Reason is your Cairo. Metadata in the PDF require Cairo version >= 1.15.4 as explained in the [documentation](https://weasyprint.readthedocs.io/en/stable/install.html#id5)

**Comment by liZe** [comment]
If you're stuck with Cairo 1.14.x, you can use older versions of WeasyPrint. Metadata work with 0.42.3, even with older versions of Cairo.

**Comment by osroca** [comment]
Thanks both for pointing me into the right direction ... I had read the docs but missed the part on the metadata. I'll will test if I can upgrade to cairo >=1.15.4 or if I have to downgrade WeasyPrint to 0.42.3.
