### ISSUE TITLE
django + weasyprint

### ISSUE THREAD

**Issue by 3guk37** [Kozea/WeasyPrint#951]
Hello weasyprint team,

I have the following issue (see below) after I installed all requirements for Ubuntu 16.04 Xenial:

sudo apt-get install build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info

and after I installed with pip weasyprint and used it in my python views.py:

from weasyprint import HTML 
from weasyprint.fonts import FontConfiguration 

Following Warning i get after > python manage.py runserver

```
lib/python3.5/site-packages/weasyprint/document.py:36: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
System check identified no issues (0 silenced).
September 25, 2019 - 22:37:59
Django version 2.2.4, using settings '*****************'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

I also tried to install cairo with the package manager for Ubuntu:

sudo apt-get install libcairo2-dev

but it didn't helped. Now my question is: How I can update cairo to solve this problem with the warning after I starting my local server?

**Comment by Tontyna** [comment]
Quoting @liZe https://github.com/Kozea/WeasyPrint/issues/915#issuecomment-519241879 :

> It won't be easy to safely get a more recent version of Cairo on 16.04 (that's more than 3 years old)

@liZe -- looks like the [installation instructions](https://weasyprint.readthedocs.io/en/stable/install.html#debian-ubuntu) need an update.

**Comment by romainquencez** [comment]
I got this warning message with latest django-weasyprint version and django 2.2.5, too.
Everything works great  with PDF generation however, except this warning.

**Comment by 3guk37** [comment]
> I got this warning message with latest django-weasyprint version and django 2.2.5, too.
> Everything works great with PDF generation however, except this warning.

Can you render svg files too? And what in production? Is django 2.2.5 also working with weasyprint properly?

**Comment by 3guk37** [comment]
> Quoting @liZe [#915 (comment)](https://github.com/Kozea/WeasyPrint/issues/915#issuecomment-519241879) :
> 
> > It won't be easy to safely get a more recent version of Cairo on 16.04 (that's more than 3 years old)
> 
> @liZe -- looks like the [installation instructions](https://weasyprint.readthedocs.io/en/stable/install.html#debian-ubuntu) need an update.

Thank you!

**Comment by romainquencez** [comment]
> > I got this warning message with latest django-weasyprint version and django 2.2.5, too.
> > Everything works great with PDF generation however, except this warning.
> 
> Can you render svg files too? And what in production? Is django 2.2.5 also working with weasyprint properly?

I dont have SVG rendering in my project, so I dont know for this case, sorry.
The functionnality is not yet deployed in production. I will send you a feedback when it will be :)
And it works well with Django 2.2.5 (and Django REST Framework) yes !

**Comment by Tontyna** [comment]
Besides incomplete SVG rendering: PDF metadata, hyperlinks and bookmarks require Cairo >= 1.15.4.

**Comment by liZe** [comment]
> @liZe -- looks like the [installation instructions](https://weasyprint.readthedocs.io/en/stable/install.html#debian-ubuntu) need an update.

Fixed in 495f7621.

**Comment by 3guk37** [comment]
On Ubuntu 18.04 bionic it is working! 

Does something have an idea for an workaround for Ubuntu 16.04 xenial?

What do you suggest?

**Comment by liZe** [comment]
> from PIL import Imange

It's `Image`, not `Imange` :wink:.
