### ISSUE TITLE
Serverless + AWSLambda + WeasyPrint

### ISSUE THREAD

**Issue by nathanmrtns** [Kozea/WeasyPrint#952]
I'm posting this in order to help others to whom might have the same problem.

I'm using Serverless and Flask, with Weasyprint. Once deploy on AWS, the problem importing WeasyPrint happens. 

So here is how I solved the problem:

1 - I deploy de application on AWS.
2 - Go to API Gateway and select your application
3 - Click in Layers and add 2 layers, one with weasyprint and another with libcairo. (zip files below)
4 - Save it and your application will run

The zip files that I used:
I try to use [this one from @nelsonsar](https://github.com/Kozea/WeasyPrint/issues/916#issuecomment-535180637) but it was too big for my application. Then I used [this one](https://github.com/Prasengupta/weasyprint_for_awslambda) from @Prasengupta which is only 18MB.

So, wrapping up, I used the lib.zip from @Nelsonsar and the weasyprint_for_lambdat from @Prasengupta. 

When using serverless, you can configure the deploy to use the layers you created on AWS setting up on settings.yml.

**Comment by liZe** [comment]
Thank you for sharing this!

As I don't use AWS at all, it's hard for me to write the documentation out of this information. Could you please write a paragraph that I could include in the [install page](https://weasyprint.readthedocs.io/en/latest/install.html)?

**Comment by nathanmrtns** [comment]
> Thank you for sharing this!
> 
> As I don't use AWS at all, it's hard for me to write the documentation out of this information. Could you please write a paragraph that I could include in the [install page](https://weasyprint.readthedocs.io/en/latest/install.html)?

Is there a place(or repository) where we could put the lib.zip file so it stays like the @Prasengupta repo? This way we could put the links in the documentation too.

**Comment by nelsonsar** [comment]
I'll create a repo for that with an example of how to use it. Since I used lambci to build it there are a couple of packages that are not necessary in the zip file.

**Comment by Prasengupta** [comment]
> > Thank you for sharing this!
> > As I don't use AWS at all, it's hard for me to write the documentation out of this information. Could you please write a paragraph that I could include in the [install page](https://weasyprint.readthedocs.io/en/latest/install.html)?
> 
> Is there a place(or repository) where we could put the lib.zip (libcairo) file so it stays like the @Prasengupta repo? This way we could put the links in the documentation too.
> Once we have that, I can write and you can include in the install page.

I will welcome to do that and let me know where I can help. And as per the request, I would like to post the repo fo supporting weasy print in AWS lambda for python 3.

**Comment by nathanmrtns** [comment]
@liZe Here is something that you can put on the install page.

To use WeasyPrint with AWS Lambda or Serverless you need to user Layers.

If you're using Serverless:

1 - I deploy de application on AWS.
2 - Go to API Gateway and select your application
3 - Click in Layers and add 2 layers, one with Weasyprint and another with Libcairo.
4 - Save it and your application will run


If you're using only AWS Lambda:
1 - Create your lambda
2 - Click in Layers and add 2 layers, one with Weasyprint and another with Libcairo.
3 - Save it and your application will run

The zip files for the layers can be found here:
1 - [WeasyPrint Layer](https://github.com/Kozea/WeasyPrint/issues/916#issuecomment-540678232) or [this one](https://github.com/Kozea/WeasyPrint/issues/916#issuecomment-535180637) in the same issue comments

2 - Download the zip from [this repo](https://github.com/Prasengupta/weasyprint_for_awslambda) and add as a layer too

**Comment by liZe** [comment]
We’ll continue discussion in #1003.
