### ISSUE TITLE
Generated PDF differs slightly from sample on weasyprint site

### ISSUE THREAD

**Issue by espechtcfe** [Kozea/WeasyPrint#954]
When generating a PDF of the "Report" sample using Weasyprint 50, I'm seeing a difference in the PDF when compared to the sample on the weasyprint site.

I've attached the PDF that is being generated.  If you compare the typography features page (page 8) with the version on the weasyprint site, you'll notice that in the one I generated, the copy in the Ligatures and Numbers sections includes line breaks that don't exist in the version on the website.

I've installed Weasyprint 50 using this docker image - https://hub.docker.com/r/minidocks/weasyprint - which I modified by changing the Dockerfile to specify version 50.  I have verified that version 50 is running in the container.  The command I'm running from a folder above the report folder to generate the report is:
docker run --rm -v `pwd`:/app -w /app minidocks/weasyprint:latest ./report/report.html weasyprint_test.pdf

Thank you for looking into this.  I'm just getting started with Weasyprint and am very impressed with the product!
[weasyprint_test.pdf](https://github.com/Kozea/WeasyPrint/files/3663316/weasyprint_test.pdf)

**Comment by liZe** [comment]
There's also a difference in the small caps text. I have to find what's wrong.

> Thank you for looking into this. I'm just getting started with Weasyprint and am very impressed with the product!

:smile:

**Comment by knixeur** [comment]
Ok, that was hard to find.
There's a problem with font-variants that was introduced in v44 (v43 works fine).
The problem is that a new Pango attribute list is being generated and replacing the current attributes.

https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/text.py#L769
https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/text.py#L783

Replaces the attributes generated on setup https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/text.py#L728

**Comment by knixeur** [comment]
Ok, I made a PR but doesn't fix Ligatures and Numbers, it does fix small-caps example. If I open report.html in a browser I see break lines in Ligatures and Numbers examples.

**Comment by knixeur** [comment]
Line breaks in Ligatures and Numbers "broke" between v45 and v46

**Comment by liZe** [comment]
@knixeur Thanks a lot, your comments (and your PR) were really, really useful :heart:.
