### ISSUE TITLE
How to unit-test infinite loops?

### ISSUE THREAD

**Issue by Tontyna** [Kozea/WeasyPrint#955]
Lately I started `setup.py test`. It was the first time since about half a year. I know it's a lengthy task, it's tea-time, Sir. But this time I could bake a cake while the unit tests run and ate almost all memory.

Eventually, after more than half an hour I killed the process. Was tired to stare at 

```
weasyprint\tests\test_layout\test_inline.py ss.x.....
```

Yeah, I guess the beloved `test_breaking_linebox_regression_*`s are expensive, expensive, expensive.

But the latest successful Win build on travis only took 4 min 19 sec!

What's wrong with my system? It's 64bit Windows 7 (rebooted), Python 3.6 and Python 3.7, site-packages up-to-date.

Any advice? Other than not running unit tests at all?

**Comment by Tontyna** [comment]
Nothing wrong with my system, nothing wrong with pytest!

I tried to pytest a branch that introduced an infinte loop in `test_inline.py` -- will rename this issue.

**Comment by Tontyna** [comment]
Counting the dots finally disclosed `test_breaking_linebox_regression_3()` to be the hanging test. This test is a regression test for #560 and indeed my branch got stuck. Okay, regression to infinite loop prevented by infinite loop.

Of course a hanging layout-loop cannot be reported by assert statements (though there are 5 asserts to check the correct line breaks), but isn't there a pytest mark or decorator to stop (and report) a test that exceeds a certain time or memory limit?

**Comment by knixeur** [comment]
You could use unittest.mock.patch with side effect emulate a certain amount of return values and check that you never run out, but that will probably involve a lot of refactor. An easier solution and exactly what you're looking for is https://pypi.org/project/pytest-timeout/

**Comment by Tontyna** [comment]
Yes, pytest-timeout seems to be the only way to do that -- but I'm not convinced that the effort of implementing it in the test suite is worth the improvement.
