### ISSUE TITLE
OSError: no library called "cairo" was found

### ISSUE THREAD

**Issue by sadakchap** [Kozea/WeasyPrint#957]
Hi,
I completely followed each step mentioned in docs and then hours googling the error but still i am getting this error

`import cairocffi as cairo
  File "C:\Users\---\Dev\ecom\env\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))`
 `File "C:\Users\---\Dev\ecom\env\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover`
`OSError: no library called "cairo" was found`
`cannot load library 'C:\Program Files\GTK3-Runtime Win64\bin\libcairo-2.dll': error 0xc1`
`cannot load library 'libcairo.so': error 0x7e`
`cannot load library 'libcairo.2.dylib': error 0x7e`
`cannot load library 'libcairo-2.dll': error 0xc1`

**Comment by sadakchap** [comment]
I used the GTK+ 64 Bit Installer and it installed the GTK version 3 here "C:\Program Files\GTK2-Runtime Win64\bin". Added those to path (at the bottom) and later moved it to the top of the path. When running "WHERE libcairo-2.dll" there is no message outputted.
Exactly followed steps but still getting this error

**Comment by Tontyna** [comment]
> When running "WHERE libcairo-2.dll" there is no message outputted.

Not even a message that says "Nothing was found"? Bear in mind that the `WHERE` command doesn't work in PowerShell, only in the ordinary Window command prompt.
You can execute the following command in (any) shell (preferably the one where you wanna run WeasyPrint) and check whether your GTK folder is at the appropriate top position:

```
python -c "import os; print(*os.environ['PATH'].split(os.pathsep), sep='\n')"
```

**Comment by sadakchap** [comment]
Closing this issue ... after installing both python and GTK of 64 bit and adding a trailing '\' slash in path variable resolved this issue....😊

**Comment by nehatkkhan786** [comment]
> Closing this issue ... after installing both python and GTK of 64 bit and adding a trailing '' slash in path variable resolved this issue....

Hey, bro, I am also facing the same issue but don't know where I am wrong as I did everything as docs but still getting the error 'Cairo was not found '

**Comment by sadakchap** [comment]
check bit version of both python and GTK

**Comment by sadakchap** [comment]
> > Closing this issue ... after installing both python and GTK of 64 bit and adding a trailing '' slash in path variable resolved this issue....
> 
> Hey, bro, I am also facing the same issue but don't know where I am wrong as I did everything as docs but still getting the error 'Cairo was not found '

check bit version of both python and GTK

**Comment by nehatkkhan786** [comment]
Both are 64 bit

**Comment by sadakchap** [comment]
> Both are 64 bit
> […](#)
> Sent from my iPhone
> On 17-Mar-2020, at 7:00 AM, Prerna Mehra ***@***.***> wrote: ﻿ check bit version of both python and GTK — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

And the path variable? it has correct path na?
