### ISSUE TITLE
Hindi characters not rendering in the pdf

### ISSUE THREAD

**Issue by nadzimo** [Kozea/WeasyPrint#958]

**Comment by nadzimo** [comment]
On my mac Hindi characters are rendering correctly in the pdf, however on my linux server the characters are showing like below.
![image](https://user-images.githubusercontent.com/25529064/66203070-6981dc80-e6b8-11e9-8969-b9c89d9c6e60.png)

Do I need to install any special font libarires?

**Comment by liZe** [comment]
Hello!

> Do I need to install any special font libraries?

You need to install a font that includes the characters you need.

**Comment by nadzimo** [comment]
thanks, will have a look. Closing for now.
