### ISSUE TITLE
Table cells are not split between multiple pages

### ISSUE THREAD

**Issue by federicodalcastello** [Kozea/WeasyPrint#96]
Hello,

I am evaluating WeasyPrint for integration and I made tests converting specific pages. Unfortunately, I found an unexpected behaviour by converting the following page (italian holidays portal):

http://www.arca-enel.it/go/55155?wp_fn=dettaglio&codice=23882&codCat=2013E

In fact, all the content is rendered in page 2. Page 1 and 3 are left blank. Main browsers' print preview correctly separates the text among pages.

Is this a bug or is there something wrong in the page source?

Thankyou

**Comment by liZe** [comment]
Now duplicates #36.

**Comment by sameedahri** [comment]
To resolve issues with tables not breaking correctly across pages, please update you css to following.

Removed: "break-inside: avoid-page;" from td elements to allow rows to split naturally between pages.

Added: "box-decoration-break: clone;"  "-webkit-box-decoration-break: clone;" to ensure that borders, backgrounds, and padding are "cloned" and rendered correctly on both sides of the break.
