### ISSUE TITLE
Box with border spanning multiple pages leaves very thin border on page breaks

### ISSUE THREAD

**Issue by craiga** [Kozea/WeasyPrint#961]
**Steps to reproduce issue**

Use WeasyPrint to print a document with a box spanning multiple pages with a border.

```html
<div style="border: 2px solid black">
  <!-- lots and lots of content here -->
</div>
```

An example of this is at https://www.craiga.id.au/weasyprint-border.

**What I expect to see**

I'd like the border to be rendered at the top and bottom of this box as it continues across pages (though I'm not sure if this matches the spec—perhaps there should be no border?)

**What actually happens**

A very, very thin line is rendered across the top and bottom of the box as it spans pages (see https://www.craiga.id.au/weasyprint-border.pdf). Note that this only appears on some clients; on Mac OS, Preview and Chrome show it, though Safari does not.

This line is not printed (see https://www.craiga.id.au/weasyprint-border-printed.jpeg).

**Comment by Tontyna** [comment]
Seems to depend on the PDF reader whether the thin borders appear.
When I look at the PDF with outdated Adobe (10.1.2) I see the thin borders. When I open it with, e.g. SumatraPDF v3.1.2 -- no thin extra borders.

**Comment by Tontyna** [comment]
With this one thin borders appear on the left and right side: 

```html
<div style="border: 2px solid black; border-width: 2px 0">
Lorem ipsum dolor sit amet
</div>
```

Interestingly this one doesn't produce thin lines:

```html
<div style="border: 2px solid black; border-left: none; border-bottom-width:0">
Lorem ipsum dolor sit amet
</div>
```

Have no idea how such css-related artifacts could be prevented by WeasyPrint. The artifacts on page breaks could possibly be suppressed in `_reset_spacing()` -- by setting `box.border_%s_style = 'none'` instead of setting the width to zero

**Comment by liZe** [comment]
> I'd like the border to be rendered at the top and bottom of this box as it continues across pages (though I'm not sure if this matches the spec—perhaps there should be no border?)

You can repeat the border at the top and the bottom on each page using [`box-decoration-break: clone`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break).

> A very, very thin line is rendered across the top and bottom of the box as it spans pages (see https://www.craiga.id.au/weasyprint-border.pdf).

That's a common rendering problem of vector drawings, and there's nothing much you can do about it as long as we use zooms and floating-point arithmetic. The problem doesn't happen when generating PNG images, or when printing the PDF.

@craiga I think that we can close this issue now, feel free to add anything if you want.

**Comment by craiga** [comment]
@liZe Sounds fair enough. Thanks for the `box-decoration-break` tip.
