### ISSUE TITLE
Problem installing weasyprint on AWS Amazon Linux AMI 

### ISSUE THREAD

**Issue by glennmeader** [Kozea/WeasyPrint#962]
Attempting to install WeasyPrint on AWS Amazon Linux AMI version 2018.03 (Centos).
ran: `sudo pip3 install weasyprint`

got the following errors:

WARNING: Requested cairocffi>=0.9.0 from https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz#sha256=f1c0c5878f74ac9ccb5d48b2601fcc75390c881ce476e79f4cfedd288b1b05db (from weasyprint), **but installing version file-.cairocffi-VERSION**

**ERROR: weasyprint 50 has requirement cairocffi>=0.9.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.**

So I get:
`ModuleNotFoundError: No module named 'cairocffi._generated'`
when giving the command:
`weasyprint --help`

TIA for any suggestions.

**Comment by glennmeader** [comment]
This seems to explain some of what I experienced: https://github.com/Kozea/cairocffi/issues/123

I got weasyprint to work by doing **pip3 install cairocffi==1.0.2**
Something seems to be wrong with version 1.1.0

**Comment by liZe** [comment]
Thanks for reporting this issue.

> Something seems to be wrong with version 1.1.0

Could you please open an issue on CairoCFFI explaining the problem you have?

**Comment by liZe** [comment]
> ERROR: weasyprint 50 has requirement cairocffi>=0.9.0, but you'll have cairocffi file-.cairocffi-VERSION which is incompatible.

Oh, I think you just have to update setuptools. Installing cairocffi twice (even version 1.1.0) fixes the problem.
