### ISSUE TITLE
[Question] Planned release date for version 51

### ISSUE THREAD

**Issue by ptr1120** [Kozea/WeasyPrint#963]
Hello !

First of all thank you so much for your work !

Is there any planned release date for version 51 ? I need support for  the `element()` and `running()` feature in order to work with dynamic and html header/footer and this will help me a lot.

Once again thanks for the amazing work :)

**Comment by liZe** [comment]
> Hello !

Hello!

> First of all thank you so much for your work !

:heart:

> Is there any planned release date for version 51 ? I need support for the `element()` and `running()` feature in order to work with dynamic and html header/footer and this will help me a lot.

I've been very busy organizing PyConFr lately, but I'm now back to business! I have to check the long list of issues open in October and at least merge the pull requests. If the unit and performance tests are OK, if there's no outstanding bug open, I'll release version 51 in a week or two.

**Comment by ptr1120** [comment]
Thank you very much.
