### ISSUE TITLE
API-Question: Removing/suppressing elements from render output?

### ISSUE THREAD

**Issue by JohannesMunk** [Kozea/WeasyPrint#970]
Hey Weasyprint-Crew and Community,

I needed to hide/remove elements from the generated output depending wheter or not they are on an even or odd page. Selecting elements with the @page :left selector is explicitely excluded by the specs.... so I hacked together a workaround.

It only works for static / non-layout relevant changes. In my case some (formatted) text box had to be on the left on left pages and on the right side on right pages. What I do now, is just insert it twice, and let the code below hide the unwanted ones.

I adapted the main.py to render and output separately. In between all elements that are "tagged" (by @string_set = "onlyonright" or "onlyonleft") and do not meet their page modulo are set to zero opacity.

There must be nicer ways to do this!

* Easier tagging than string_set? I didnt know which attributes Weasyprint would let pass through the render step, so I took smth that was there. Another hack would be to use "magic" z_values. Or smth else?

* Can the target box be removed from the childrens tuple in order to really remove the box? My first try (commented) didnt work, and as my python is non-existent I stopped there. The opacity trick of course means that the text is still contained in the document. Other ways to achieve this?

Here comes my code.

```
___main__.py:
.....

def findAndApplyOnlyOn(pageNo, pbox):
    if not hasattr(pbox, "children"): return
    for i in range(len(pbox.children) - 1, -1, -1):
        box = pbox.children[i]
        if isinstance(box.string_set, list):
            if len(box.string_set) > 0:
                if isinstance(box.string_set[0], tuple):
                    if (box.string_set[0][0] == 'onlyonright' and pageNo % 2 == 1) or (box.string_set[0][0] == 'onlyonleft' and pageNo % 2 == 0):
                        # pbox.children = pbox.children[ : i ] + pbox.children[i+1 : ]
                        box.style['visibility'] = 'hidden'
                        box.style['opacity'] = 0
                        continue

        findAndApplyOnlyOn(pageNo, box)

def main(argv=None, stdout=None, stdin=None):
    """The ``weasyprint`` program takes at least two arguments:
.....

    if args.output == '-':
        if stdout is None:
            stdout = sys.stdout
        # stdout.buffer on Py3, stdout on Py2
        output = getattr(stdout, 'buffer', stdout)
    else:
        output = args.output

    kwargsRender = {
        'stylesheets': args.stylesheet,
        'presentational_hints': args.presentational_hints}
    kwargs = {}
    if args.resolution:
        if format_ == 'png':
            kwargs['resolution'] = args.resolution
        else:
            parser.error('--resolution only applies for the PNG format.')

    if args.attachment:
        if format_ == 'pdf':
            kwargs['attachments'] = args.attachment
        else:
            parser.error('--attachment only applies for the PDF format.')

....

    html = HTML(source, base_url=args.base_url, encoding=args.encoding,
                media_type=args.media_type)
    main_doc = getattr(html, 'render')(**kwargsRender)
    
    for i, page in enumerate(main_doc.pages):
        findAndApplyOnlyOn(i, page._page_box)

    getattr(main_doc, 'write_' + format_)(output, **kwargs)

if __name__ == '__main__':  # pragma: no cover
    main()
```
```
css:
	.infocol {
		string-set: onlyonright "1";
	}
	
	.infocolLeft {
		string-set: onlyonleft "1";
	}
```

Looking forward to a smarter, existing solution, that I just didnt see? :-)

Johannes

**Comment by Tontyna** [comment]
First thought that comes to my mind isn't a solution or enhancement but a concern: What happens if the element you want to hide spreads across two (or more) pages? Do you wanna see only the parts that are placed on the intended (odd or even) page?

**Comment by JohannesMunk** [comment]
True, that would be a problem. But in my case, the info box will never spread across pages - just a few lines of factual information, at the beginning of a new section and thus after a page break. But outside and aside of the actual content, so that it doesnt matter to have the box duplicated and hide the one that is unwanted.

**Comment by Tontyna** [comment]
Modifying the pbox.children in place while looping them is doomed to fail.

You'll need an independent loop to construct a modified (tuple) of children, e.g. with a generator expression that checks for a condition.
    
```python
def findAndApplyOnlyOn(pageNo, pbox):
    if hasattr(pbox, "children"): 
        # generator expression to remove unwanted children
        pbox.children = tuple(
            box for box in pbox.children if condition(box, pageNo))
        
        for box in pbox.children:
            findAndApplyOnlyOn(pageNo, box)
```
            
The `condition` can be coded inside the generator expression or as a separate function.

```python
def condition(box, pageNo):
    # return False for boxes we want to remove, True otherwise
    ...
```

**Comment by Tontyna** [comment]
BTW: Instead of checking for even/odd page numbers I suggest to check the `page_type` of the PageBox. It's a named tuple and has a `side` attribute which is 'right' or 'left'.
```python
for i, page in enumerate(main_doc.pages):
    side = page._page_box.page_type.side
    findAndApplyOnlyOn(side, page._page_box)
```

**Comment by JohannesMunk** [comment]
> Modifying the pbox.children in place while looping them is doomed to fail.
> 
> You'll need an independent loop to construct a modified (tuple) of children, e.g. with a generator expression that checks for a condition.

Well.. thats why I looped the index range backwards. Thats how you would do it in C/C++. That part should in principle work, but it didnt. Maybe the output (co)-depends on smth else than the children list?

> 
> ```python
> def findAndApplyOnlyOn(pageNo, pbox):
>     if hasattr(pbox, "children"): 
>         # generator expression to remove unwanted children
>         pbox.children = tuple(
>             box for box in pbox.children if condition(box, pageNo))
>         
>         for box in pbox.children:
>             findAndApplyOnlyOn(pageNo, box)
> ```
> 
> The `condition` can be coded inside the generator expression or as a separate function.
> 
> ```python
> def condition(box, pageNo):
>     # return False for boxes we want to remove, True otherwise
>     ...
> ```

Your code definitely looks nicer! :-) Thank you for your considerations.

**Comment by Tontyna** [comment]
> Well.. thats why I looped the index range backwards. Thats how you would do it in C/C++. That part should in principle work. 

And indeed, it works for me... at least with simple extractions from simple html snippets.

> Maybe the output (co)-depends on smth else than the children list?

If that's the case then my code won't work, too... what's the error you got?

**Comment by JohannesMunk** [comment]
Oh, wow! Now the deleting works on my end too! I guess smth else was wrong when I tried it. I should sleep more :-) Thats definitely nicer than the opacity hack. Do you have any better ideas for the "tagging", too? The css-classes are not available anymore after rendering, right? Gn8!

**Comment by Tontyna** [comment]
> Do you have any better ideas for the "tagging", too?

Unfortunately there is no link from the boxes to their html element. If there was, one could define and retrieve arbitrary attributes... 
There is only the `element_tag`, the `style`, the `string_set` and the `bookmark_label`. 

If it was me I'd "tag" the concerned elements

* either with an `id`, ignore WeasyPrints warnings about duplicate anchors and query for `if box.style['anchor'] == 'onlyonleft'`. 
* or with a css property `bookmark-label` and query for `if box.bookmark_label == 'onlyonleft'` 

That's easier than parsing the string_set.

**Comment by JohannesMunk** [comment]
> * or with a css property `bookmark-label` and query for `if box.bookmark_label == 'onlyonleft'`
Do bookmark-labels have any other effect on the PDF?

**Comment by Tontyna** [comment]
> Do bookmark-labels have any other effect on the PDF?

Only when there's also a `bookmark-level` set.

**Comment by Tontyna** [comment]
@JohannesMunk if my PR is accepted your can give your special text boxes an arbitrary attribute

```html
<div mytag="onlyonleft">
  lorem ipsum
</div>
```

and access that attribute via `box.element` like that:

```Python
    box = pbox.children[i]
    if box.element is not None:
        mytag = box.element.get('mytag')
        if mytag == 'onlyonleft':
            # ....
```

**Comment by JohannesMunk** [comment]
Oh, cool! That certainly will be handy in other cases too! Thank you!

**Comment by liZe** [comment]
> Oh, cool! That certainly will be handy in other cases too! Thank you!

@JohannesMunk #972 has been merged, you'll soon be able to use @Tontyna's magic trick!
