### ISSUE TITLE
Probable variable name typo 

### ISSUE THREAD

**Issue by benoitkugler** [Kozea/WeasyPrint#983]
Hi,

In layout/tables.py, line 185, `cell.position_y` seems a bit suspicious. 
Isn't it a typo, which should be replaced by row.position_y ?

Otherwise, it could be the last cell of row.children ?

Thanks for this amazing library !

**Comment by liZe** [comment]
Hi!

> In layout/tables.py, line 185, `cell.position_y` seems a bit suspicious.
> Isn't it a typo, which should be replaced by row.position_y ?

You're right. `cell.position_y` works too, as it's the last cell's position (which is the same as the row position), but it's much better to use `row.position_y` here.
