### ISSUE TITLE
Support for line-break using {content: }

### ISSUE THREAD

**Issue by fabiobatalha** [Kozea/WeasyPrint#986]
Is there any way to include a line-break between a string while using {content: }?

The following snippet is not working. I'm trying to use the **\A**

``` html
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <style>
      @media print {
        @page {
            @bottom-center {
                content: "Tous droits réservés, 2014 \A https://doi.org/10.7202/1027428ar";
            }
        }
      }
    </style>
  </head>
  <body>
    Content
  </body>
</html>
```

**Comment by Tontyna** [comment]
AFAIK only possible with `position: running()` and `content: element()`, e.g.:

```html
<style>    
.footer {
   position: running(footer);
   text-align:center;
}
@page {
  @bottom-center {
    content: element(footer);
  }  
}
</style>

<div class="footer">
  Tous droits réservés, 2014 <br>
  https://doi.org/10.7202/1027428ar
</div>
```

**Comment by liZe** [comment]
For the record, it also works with `\A` if you use a `white-space` value that keeps line breaks (for example `white-space: pre-wrap`).

Fun fact: [that's how `<br>` tags are handled in WeasyPrint](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/css/html5_ua.css#L216) :wink:.
