### ISSUE TITLE
Floating elements disappear when duplicating page

### ISSUE THREAD

**Issue by ewingrj** [Kozea/WeasyPrint#991]
Notice the date does not render on the 2nd page.

```
#!/usr/bin/env python
from weasyprint import HTML

if __name__ == "__main__":
    doc = HTML(string='''
    <style>
    h2 {
        margin-top: 8px;
        margin-bottom: 8px;
    }

    .items {
        clear: both;
        border-collapse: collapse;
        color: #333;
        width: 100%;
    }


    .items tr:nth-child(even) {
        background: #eee;
    }

    .items tr:first-child {
        background: white;
    }

    .items td, th {
        border: 1px solid #ccc;
        padding: 0.5em;
    }

    .items th {
        border: none;
        text-align: center;
    }

    .items tbody {
        border-bottom: 3px solid black;
    }

    .items .qty {
        text-align: right;
        width: 40px;
    }
</style>


<h3 style="">Disappearing header</h3>
<p style="float: right">Oct. 24, 2019</p>

<table class="items">
    <tr>
        <th>Item</th>
        <th class="qty">Qty</th>
    </tr>

    <tbody>
    
        <tr>
            <td>shirt</td>
            <td class="qty">1</td>
        </tr>
   
    </tbody>
</table>
''').render()

    doc = doc.copy(doc.pages + doc.pages)
    doc.write_pdf('example.pdf')
```

**Comment by Tontyna** [comment]
There is no need to copy the doc to make floats disappear -- just `write_*` twice:

```Python
snippet = '<div style="float:left">lorem ipsum</div>'
doc = HTML(string=snippet).render()

doc.write_pdf('example.pdf')
doc.write_png('example.png')
```

There is no "lorem ipsum" in the png.

This is a feature of `StackingContext.from_page()`, manipulating the (original! Pointers! no copies!) page box tree to facilitate the correct paint order (z-index, floats etc.)

**Comment by balliegojr** [comment]
I am having the same problem.

In my case, I'm using the PdfGenerator from the [Tips & Tricks ](https://weasyprint.readthedocs.io/en/stable/tips-tricks.html)page, to generate the headers of the document.
Floating elements will appear only in the header of the first page

First page:
![image](https://user-images.githubusercontent.com/3179320/70273553-10eac080-1789-11ea-8347-3f0babfd3274.png)

Second Page:
![image](https://user-images.githubusercontent.com/3179320/70273576-1cd68280-1789-11ea-9c3b-619aec651b1f.png)

**Comment by liZe** [comment]
Discussion continues in #1081, with other infamous examples.
