### ISSUE TITLE
Image in PDF from python, how does it work?

### ISSUE THREAD

**Issue by tb2johm** [Kozea/WeasyPrint#992]
Not sure if this is a issue, or just that I don't understand how it's done.

I'm generating a PDF from within Pyhton. Now I want to include a image in the PDF.

### This works:
I. In the stylesheet, set the background of a class to a image file.
II. Read and encode the image in Base64, straight into the `<img>` in the HTML.

### This doesn't work:
Just use the standard `<img>` tag and set the source to a file. It just renders the _alt_.
Do the image need to be located at some special location, or am I doing something else wrong? Is there an example anywhere to how it's supposed to be done?

**Comment by Tontyna** [comment]
> Just use the standard `<img>` tag and set the source to a file.

No special location required. Just a valid, resolvable (relative or absolute) **URL**. Even absolute `file:///` urls work (three slashes!).

**Comment by tb2johm** [comment]
Great! Thanks alot!
