### ISSUE TITLE
Concat does not work anymore

### ISSUE THREAD

**Issue by Azd325** [Kozea/WeasyPrint#993]
I did an big update from `0.42.3` to `50` the concat from itertools does not work anymore if I pass it to the document. I had to cast it beforehand to an list that the code works again to generate an PDF.
I could not find anything related to in in the news. 

```diff
index 698531211..1d1b47223 100644
--- a/pdf.py
+++ b/pdf.py
@@ -35,7 +35,7 @@ def multipage_from_html(htmls):
     The HTML documents are concatenated in order.
     """
     pages = concat(weasyprint.HTML(string=html).render().pages for html in htmls)
-    document = weasyprint.Document(pages, weasyprint.document.DocumentMetadata(),
+    document = weasyprint.Document(list(pages), weasyprint.document.DocumentMetadata(),
                                    url_fetcher=weasyprint.default_url_fetcher, font_config=None)
     return document.write_pdf()
```

**Comment by Tontyna** [comment]
What is *concat from itertools*? There is no `concat()` in Python's [itertools module](https://docs.python.org/3/library/itertools.html)

**Comment by Azd325** [comment]
Ahh sorry I missed it. It is concat from toolz
https://github.com/pytoolz/toolz/blob/28945526c46d7e1a0dcd6599aa77709fd6d6ed0d/toolz/itertoolz.py#L478-L493

**Comment by Tontyna** [comment]
The `pages` parameter of the Document constructor was never supposed to be an iterable but a **list of :class:`Page` objects.**

Your `multipage_from_html` nevertheless happily worked until  v43rc1, when `zip()` was introduced in document.write_pdf to loop the pages and links.

**Comment by liZe** [comment]
> The `pages` parameter of the Document constructor was never supposed to be an iterable but a **list of :class:`Page` objects.**

Yes, you have to explicitly cast your iterable into a list.
