### ISSUE TITLE
Image zoom tags are ignored

### ISSUE THREAD

**Issue by howels** [Kozea/WeasyPrint#995]
HTML renders correctly but because the img zoom= tags are ignored the images are scaled to the maximum dimensions in all cases.  A global zoom=35% was used to scale images to an appropriate size. This works when printing from the browser but not using weasyprint, and I can see this:
`WARNING: Ignored zoom:35% at 82:40, unknown property.`

**Comment by liZe** [comment]
Hello!

Thank you for reporting this issue.

Unfortunately, [this property is non-standard](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom). As it's already hard to implement properties included in standards, I don't think that `size` will soon (or ever) be supported by WeasyPrint … unless it's included in the W3C's standards tracks!

You can open an issue [on the CSS working group bug tracker](https://github.com/w3c/csswg-drafts/issues). As it's already supported by many browsers, they may be interested in adding this feature into a working draft.

**Comment by howels** [comment]
Thanks, do you suggest an alternative CSS property to perform a similar function?

**Comment by Tontyna** [comment]
Quoting [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom):

> The non-standard `zoom` CSS property can be used to control the magnification level of an element. `transform: scale()` should be used instead of this property, if possible.

**Comment by liZe** [comment]
@howels If `transform` doesn't solve your use case, please open a new issue to find alternative solutions. I close this issue because `zoom` will not be implemented (unless it's included in a spec).

**Comment by howels** [comment]
> Quoting [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom):
> 
> > The non-standard `zoom` CSS property can be used to control the magnification level of an element. `transform: scale()` should be used instead of this property, if possible.

Thanks, missed that in the link!
